-- AERIAL SERVANT
-- Source: Monster Manual, page 7+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "AERIAL SERVANT",
  page = 7,
  hitDice = "16",
  hitDiceNum = 16,
  hitDiceBonus = 0,
  avgHp = 72,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 8, max = 32 } },
  xp = 5250,
  xpPerHp = 20,
  xpValue = 6690, -- 5250 + 20/hp x 72 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 24, modes = { { mode = "walk", rate = 24 } } },
  size = nil,
  sizeDetail = "8' tall",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Surprises on 1-4",
  specialDefenses = "Can be hit only by magic weapons",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The aerial servant is a semi-intelligent form of an air elemental. It is typically encountered only due to conjuration by a cleric, although these creatures roam the ethereal and astral planes and when encountered there can be dimly seen. An aerial servant is normally invisible. Aerial servants do not fight per se, but they are exceedingly strong and very fast. They can carry weights in excess of 10,000 gold pieces, and if they grasp any creature it requires an 18 strength to have any chance of breaking free. For each percentage point score the creature has, there is a like chance to escape the grasp of the aerial servant, i.e. a human with an 18/50% strength has a 50% chance of breaking free of the grasp, and a 00% or 19 indicates automatic breaking of the grasp. They travel at twice the speed of an invisible stalker, and when on the physical plane they are able to achieve surprise on a die roll of 1-4 (out of 6). If the aerial servant is frustrated from completion of its assigned mission it becomes insane, returns to the cleric which sent it forth, and attacks as a double strength invisible stalker. Likewise, if it is encountered ethereally or astrally the aerial servant will typically attack in the same fashion. For further details regarding aerial servants consult the volume detailing clerical spells.", -- complete Monster Manual prose, verbatim
}
