-- Ankylosaurus
-- Source: Monster Manual, page 24+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Ankylosaurus",
  page = 24,
  hitDice = "9",
  hitDiceNum = 9,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = 0,
  numAttacks = "1 23",
  damage = { { min = 3, max = 18 } },
  xp = 900,
  xpPerHp = 12,
  xpValue = 1380, -- 900 + 12/hp x 40 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 5 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = "15'+ long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "This armadillo-like ornithischian weighs four or five tons \u2014 most of this weight being his armor plating, side spines, and great knobbed tail. If attacked (or threatened) this creature will lash its tail delivering blows of considerable force. They are herbivores of the same family as paleocincus.", -- complete Monster Manual prose, verbatim
}
