-- ANT, Giant
-- Source: Monster Manual, page 8+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "ANT, Giant",
  page = 8,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 1, max = 6 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 38, -- 20 + 2/hp x 9 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 100 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "Q (x3), S" },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 } } },
  size = "S",
  sizeDetail = "2' long",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Warriors have poison sting",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "When giant ants are encountered it is 90% likely that they will simply be workers. If found in their lair (nest) there will be double the number rolled plus 1 warrior ant for every 5 workers. The warrior ant has 3 hit dice, does 2-8 hit points of damage with its mandibles, and if it hits with them it will also attempt to sting for 3-12 points of damage. If a sting hits, a saving throw versus poison must be made; if successful the victim takes only 1-4 hit points of damage. The queen ant has 10 hit dice, but she neither moves nor attacks. If she is killed the other ants will become confused (as if they were under the influence of that spell) for six melee rounds and then leave the nest. Treasure held by ants will be found in the chamber of the queen ant. The egg chamber will be guarded by 5-50 workers and 5 warriors. Giant ant eggs have no normal market value.", -- complete Monster Manual prose, verbatim
}
