-- Antrodemus (Allosaurus)
-- Source: Monster Manual, page 25+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Antrodemus (Allosaurus)",
  page = 25,
  hitDice = "15",
  hitDiceNum = 15,
  hitDiceBonus = 0,
  avgHp = 68,
  armorClass = 5,
  numAttacks = 3,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 6, max = 24 } },
  xp = 2400,
  xpPerHp = 20,
  xpValue = 3760, -- 2400 + 20/hp x 68 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 2 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "30' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "One of the most vicious of predators, this monster can run across hard ground at great speed.", -- complete Monster Manual prose, verbatim
}
