-- Apatosaurus (Brontosaurus)
-- Source: Monster Manual, page 25+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Apatosaurus (Brontosaurus)",
  page = 25,
  hitDice = "30",
  hitDiceNum = 30,
  hitDiceBonus = 0,
  avgHp = 135,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 3, max = 18 } },
  xp = 5000,
  xpPerHp = 35,
  xpValue = 9725, -- 5000 + 35/hp x 135 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 1, max = 6 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = "70' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The thunder-lizard is a 40 ton plant-eater found near marshes and lakes. The creature spends much of his time in shallow water to support his bulk. It moves to deep water to avoid carnivores. Apatosaurus ignores small things, but it is prone to step on anything in its way (doing 4-40 points of damage).", -- complete Monster Manual prose, verbatim
}
