-- APE (Gorilla)
-- Source: Monster Manual, page 8+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "APE (Gorilla)",
  page = 8,
  hitDice = "4 + 1",
  hitDiceNum = 4,
  hitDiceBonus = 1,
  avgHp = 19,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 1, max = 6 } },
  xp = 130,
  xpPerHp = 5,
  xpValue = 225, -- 130 + 5/hp x 19 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = "6' tall, broad",
  intelligence = "low",
  alignment = "neutral",
  specialAttacks = "Rending",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The typical ape is found only in lonely tropical forest regions. It is non-aggressive and shy, but if threatened or cornered will fight fiercely. If it scores hits with both of its hands it does an additional 1-6 points grabbing and rending its opponent.", -- complete Monster Manual prose, verbatim
}
