-- APE, Carnivorous
-- Source: Monster Manual, page 8+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "APE, Carnivorous",
  page = 8,
  hitDice = "5",
  hitDiceNum = 5,
  hitDiceBonus = 0,
  avgHp = 22,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 1, max = 8 } },
  xp = 90,
  xpPerHp = 5,
  xpValue = 200, -- 90 + 5/hp x 22 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 2, max = 8 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "C" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "7'+, very broad",
  intelligence = "low_upper",
  alignment = "neutral",
  specialAttacks = "Rending",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The carnivorous ape is a larger, stronger and very aggressive relative of the gorilla. This beast has fair intelligence (IQ 70+) and is very cunning. It hungers particularly for human flesh. The eyesight of the ape is keen, as is its hearing and sense of smell, so it is surprised only on a roll of 1. If it strikes its opponent with both hands the ape does an additional 1-8 hit points of rending damage.", -- complete Monster Manual prose, verbatim
}
