-- Asmodeus (Arch-devil)
-- Source: Monster Manual, page 21+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Asmodeus (Arch-devil)",
  page = 21,
  hitDice = "199 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 199,
  armorClass = -7,
  numAttacks = 1,
  damage = { { min = 4, max = 14 } },
  xp = 5000,
  xpPerHp = 35,
  xpValue = 11965, -- 5000 + 35/hp x 199 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 90,
  treasure = { individual = nil, inLair = "I, R, U, V" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = "13\u00bd' tall",
  intelligence = "supra_genius",
  alignment = "lawful_evil",
  specialAttacks = "See below",
  specialDefenses = "+3 or better weapon to hit",
  magicResistance = "90%",
  psionic = "366",
  attackDefenseModes = "All/all",
  text = "Asmodeus, arch-fiend, the Overlord of all the dukes of Hell rules by both might and wit. He is physically stronger than any other devil (as strong as a storm giant) and the most cunning and artful. His mighty palace rests upon the floor of the lowest rift in Hell's ninth plane. His servitors are pit-fiends (q.v.) and whichever of the other lesser and greater devils he commands to service. Once per year he can command the arch-devils to attend his court and pay homage.\n\nThe powers possessed by Asmodeus which are usable at will, once per turn or melee round, are: pyrotechnics, produce flame, wall of fire, ice storm, wall of ice, continual light, read languages, read magic, detect invisible, locate object, invisibility, dispel magic, hold person, hold monster, shape change, beguile, rulership, mass charm, geas, restoration, raise dead fully, or (fulfill another's)\n\nwish. Asmodeus can use the following powers once per day: symbol of pain, symbol of insanity, symbol of hopelessness (save versus magic or submit to Asmodeus' will), (un) holy word. He can always summon 2 lesser or 1 greater devil. The gaze of this arch-friend causes fear, fear and weakness or chill (slows 50% and -5 on all dice rolls) at his option. Saving throw versus magic applies.\n\nAsmodeus has a glowing rod of pure ruby. It acts as a rod of absorption. It also causes serious wounds on anyone touched by its opaline tip. Upon command it will shoot forth a cone of frost, a jet of acid, or a bolt of lightning (all according to the appropriate dragon breath weapon). The value of this instrument is 1,000,000 gold pieces considering the gem qualities only!\n\nDescription: There can be no question that Asmodeus is the most handsome of all devils as well as being the strongest and most cunning. The ultimate evil he represents can be seen in his beauty only when he so wills or if he forgets himself and flies into a rage.", -- complete Monster Manual prose, verbatim
}
