-- AXE BEAK
-- Source: Monster Manual, page 8+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "AXE BEAK",
  page = 8,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 2, max = 8 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 6 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 } } },
  size = "L",
  sizeDetail = "7'+ tall",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Axe beaks are prehistoric carnivorous flightless birds. They are very fast runners and aggressively hunt during daylight. An axe beak resembles an ostrich in its lower portions, with a strong neck and a heavy, sharp beak.", -- complete Monster Manual prose, verbatim
}
