-- Baalzebul (Arch-devil)
-- Source: Monster Manual, page 22+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Baalzebul (Arch-devil)",
  page = 22,
  hitDice = "166 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 166,
  armorClass = -5,
  numAttacks = "1 bite",
  damage = { { min = 2, max = 12 } },
  xp = 5000,
  xpPerHp = 35,
  xpValue = 10810, -- 5000 + 35/hp x 166 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 80,
  treasure = { individual = nil, inLair = "E, R, V" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 }, { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = "12' tall",
  intelligence = "genius",
  alignment = "lawful_evil",
  specialAttacks = "See below",
  specialDefenses = "+3 or better weapon to hit",
  magicResistance = "85%",
  psionic = "313",
  attackDefenseModes = "All/all",
  text = "The sixth and seventh planes of Hell, Malbolge and Maladomini respectively, are ruled by Baalzebul, \"Lord of the Flies\" (\"lies\"?) He is an arch-devil of great power, second only to Asmodeus. Malbolge is a black stone plane, filled with stinking vapors, smokes, fire pits, and huge caves and caverns. Maladomini is similar, but there will be found the moated castles of the malebranche and the great fortress of Baalzebul.\n\nThis arch-devil can employ any of the following powers, one at a time, as desired, during a turn or melee round, as applicable: pyrotechnics, produce flame, wall of fire, continual light, read languages, read magic, detect invisible, locate object, invisibility, dispel magic, shape change, beguile, rulership (as a rod of rulership), hold person, charm monster, geas, restoration, raise dead fully, fulfill another's wish. Once per day Baalzebul can use: symbol of pain, symbol of insanity, (un) holy word. He can always summon 1-4 horned devils. His glance causes fear and weakness (saving throw versus magic or collapse in trembling until 1-4 melee rounds after the gaze is lifted) whenever he directly stares at any person.", -- complete Monster Manual prose, verbatim
}
