-- BABOON
-- Source: Monster Manual, page 9+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BABOON",
  page = 9,
  hitDice = "1 + 1",
  hitDiceNum = 1,
  hitDiceBonus = 1,
  avgHp = 5,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 30, -- 20 + 2/hp x 5 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 10, max = 40 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "S",
  sizeDetail = "4' + tall",
  intelligence = "low",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Climbing",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Baboons are basically herbivorous, group animals. The tribe will be led by 2-8 large males (+1 hit point damage on attacks). Half of the tribe will be young which will not attack. If the home territory of a tribe is invaded the baboons will attempt to drive the invaders off, but it is 90% likely that the tribe will flee if faced by determined resistance.", -- complete Monster Manual prose, verbatim
}
