-- BALUCHITHERIUM
-- Source: Monster Manual, page 9+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BALUCHITHERIUM",
  page = 9,
  hitDice = "14",
  hitDiceNum = 14,
  hitDiceBonus = 0,
  avgHp = 63,
  armorClass = 5,
  numAttacks = 2,
  damage = { { min = 5, max = 20 } },
  xp = 1800,
  xpPerHp = 18,
  xpValue = 2934, -- 1800 + 18/hp x 63 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 3 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "20' tall",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "This creature is a prehistoric ancestor of the rhinoceros. It is a huge herbivorous mammal with a tendency to charge at anything nearby in order to trample it. If two are encountered they will be a mated pair, if three are encountered the third will be a young baluchitherium (roll percentile dice to determine size).", -- complete Monster Manual prose, verbatim
}
