-- BARRACUDA
-- Source: Monster Manual, page 9+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BARRACUDA",
  page = 9,
  hitDice = "1-3",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 38, -- 20 + 2/hp x 9 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 30, modes = { { mode = "walk", rate = 30 } } },
  size = "S",
  sizeDetail = "to L",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Barracuda inhabit warm salt waters. These predatory fish are lightning quick, going from a motionless state to full speed in a single melee round. They attack any prey which is injured, appears helpless, or is relatively small.", -- complete Monster Manual prose, verbatim
}
