-- BEAR (Black)
-- Source: Monster Manual, page 10+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BEAR (Black)",
  page = 10,
  hitDice = "3 + 3",
  hitDiceNum = 3,
  hitDiceBonus = 3,
  avgHp = 17,
  armorClass = 7,
  numAttacks = 3,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 1, max = 6 } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 128, -- 60 + 4/hp x 17 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 1, max = 3 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = "6' + tall",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Hugs: 2-8",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "All of these uraoids are omnivorous, although the gigantic cave bear tends towards a diet of meat. All have excellent hearing and smell but rather poor eyesight. Size shown is average for the variety, and larger individuals will be correspondingly more powerful. The grizzly bear is a brown bear of very aggressive disposition. Black bears are usually not aggressive, brown bears are, and cave bears are quite aggressive. If a bear scores a paw hit with an 18 or better it also hugs for additional damage as indicated. The brown and cave bears will continue to fight for 1-4 melee rounds after reaching 0 to -8 hit points. At -9 or greater damage, they are killed immediately.\n\n[Shared family description from BEAR (Cave)]", -- complete Monster Manual prose, verbatim
}
