-- Berserker
-- Source: Monster Manual, page 68+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Berserker",
  page = 68,
  hitDice = "2-7 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 4,
  armorClass = 7,
  numAttacks = "1 (or 2)",
  damage = { { raw = "By weapon type" } },
  xp = 10,
  xpPerHp = 1,
  xpValue = 14, -- 10 + 1/hp x 4 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 10, max = 100 },
  lairPct = 10,
  treasure = { individual = "K, B in lair", inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "mean:_average_to_very",
  alignment = "neutral",
  specialAttacks = "Leader types",
  specialDefenses = "Leader types",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Berserkers are bands of fighters who gather together to go out and seek battle. They scorn armor and engage in combat mad with battle lust. This lust enables them to strike twice, or once with a +2 to hit.\n\nFor every 10 berserkers encountered there will be a 1st level fighter in addition, for every 20 there will be a 2nd level, for every 30 there will be a 3rd, for every 40 there will be a 4th, and for every 50 there will be a 5th \u2014 all in addition to the number indicated by the dice.\n\nBerserkers will be led by a war chief of 9th or 10th level and two subchieftains of 6th or 7th level \u2014 if 60 or less berserkers, the lower levels, if more than 60, the higher levels.\n\nFor every 10 berserkers encountered there is a 50% chance that there will be a berserk cleric of 7th level and 1-4 of his assistants of 3rd or 4th level.\n\nBerserkers never check morale. If they decide that a fight would bring them honor (and possibly loot) they will attack.", -- complete Monster Manual prose, verbatim
}
