-- BOAR (Warthog)
-- Source: Monster Manual, page 12+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BOAR (Warthog)",
  page = 12,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = 2,
  damage = { { min = 2, max = 8 }, { min = 2, max = 8 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 1, max = 6 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = "2\u00bd' at shoulder",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These creatures are typically pig-like omnivores. Only the warthog has a range restricted to warmer climes.\n\nBoar, Wild: If more than 1 is encountered the others will be sows (3 hit dice, 2-8 hit points damage/attack), on a 1:4, sows: sounders, ratio. Thus if 12 are encountered there will be 1 boar, 3 sows, and 8 young. The boar will fight for 2-5 melee rounds after reaching 0 to -6 hit points but dies immediately at -7 or greater damage.\n\nGiant Boar (Elothere): This prehistoric forerunner of the wild boar is also very aggressive. If 3 or more are encountered there is only a 25% chance that there will be young (2-6 hit dice, 1-4/2-5/2-7/2-8/3-12 hit points damage/attack) numbering from 1-4 of the total herd. The boars and sows fight equally, and either will fight for 1-4 melee rounds after reaching 0 to -10 hit points but die immediately upon reaching -11 or more hit points.\n\nWarthog: These tropical beasts are aggressive only if their territory is threatened or if cornered or threatened. They make two slashing attacks with their large tusks. Male and female fight equally. If 3-6 are encountered the balance will be young (1-2 hit dice, 1-3/2-5 hit points damage/attack). The warthog will continue to fight for 1-2 melee rounds after reaching 0 to -5 hit points but at -6 or greater damage dies immediately.", -- complete Monster Manual prose, verbatim
}
