-- BRAIN MOLE
-- Source: Monster Manual, page 12+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BRAIN MOLE",
  page = 12,
  hitDice = "1 hit point",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 0,
  armorClass = 9,
  numAttacks = "Nil",
  damage = {  },
  xp = 5,
  xpPerHp = 1,
  xpValue = 5, -- 5 + 1/hp x 0 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 3 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 } } },
  size = "S",
  sizeDetail = "3\" long",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Psionic only",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "121 point attack",
  attackDefenseModes = "B/Nil",
  text = "Small mole-like animals which inhabit most places above and below ground, brain moles are attracted by psionic activity of any sort \u2014 including magic spells which duplicate psionic effects. When a brain mole is within 30' of any creature exercising such psionic activity, it will seek to feed upon the energy being used by psionically \"burrowing\" into the mind. This has the effect of attacking the mind with a 121 point strength mind thrust upon the creature using psionic energy. This burrowing will have a 20% chance per melee round of causing permanent insanity in non-psionically endowed creatures employing psionic energy through spells or magical items. Cessation of the spell or abandoning the use of the magic item will immediately relieve the attack. A psionic under attack must escape the range of the brain mole or kill it to halt its burrowing.", -- complete Monster Manual prose, verbatim
}
