-- Brass Dragon (Draco Impudentus Gallus)
-- Source: Monster Manual, page 32+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Brass Dragon (Draco Impudentus Gallus)",
  page = 32,
  hitDice = "6-8",
  hitDiceNum = 6,
  hitDiceBonus = 0,
  avgHp = 32,
  armorClass = 2,
  numAttacks = 3,
  damage = {  },
  xp = 150,
  xpPerHp = 6,
  xpValue = 342, -- 150 + 6/hp x 32 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 4 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "H" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = "30' long",
  intelligence = "high",
  alignment = "chaotic_good_(neutral_tendencies)",
  specialAttacks = "Breath weapon",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "DAMAGE/ ATTACK: 1-4/1-4/4-16\n\n+ possible magic use\n\nCHANCE OF:\n\nSpeaking: 30%\n\nMagic Use: 30%\n\nSleeping: 50%\n\nSandy desert regions are the typical habitat of brass dragons, whose cavernous lairs are often found therein. Brass dragons are quite forward and officious, and they love to converse. They are rather selfish and tend towards neutrality because of this.\n\nThe brass dragon attacks with a claw/claw/bite routine or by breathing either of two weapons \u2014 a cone of sleep gas which extends 7\" from the creature's mouth to a terminating diameter of 2\", or a billowing cloud of fear gas 4\" wide by 5\" across by 2\" deep (ground upwards). Creatures in these gaseous clouds must save versus dragon breath regardless of their level or fall asleep/flee in fear. If the dragon is small sized, saves are at +2, and if the dragon is of huge size saving throws are at -2, from the number rolled.\n\nIf a brass dragon can speak and employ spells, it will gain a first level spell at each odd numbered stage of maturity it attains, and a second level spell at each even numbered age. As is usual with dragons, determine spells known by random selection.", -- complete Monster Manual prose, verbatim
}
