-- Bronze Dragon (Draco Gerus Bronzo)
-- Source: Monster Manual, page 33+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Bronze Dragon (Draco Gerus Bronzo)",
  page = 33,
  hitDice = "8-10",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = 0,
  numAttacks = 3,
  damage = { { min = 1, max = 6 }, { min = 1, max = 6 }, { min = 4, max = 24 } },
  xp = 375,
  xpPerHp = 10,
  xpValue = 775, -- 375 + 10/hp x 40 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 45,
  treasure = { individual = nil, inLair = "H, S, T" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 }, { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = "42' long",
  intelligence = "exceptional",
  alignment = "lawful_good",
  specialAttacks = "Breath weapon + possible magic use",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "CHANCE OF:\n\nSpeaking: 60%\n\nMagic Use: 60%\n\nSleeping: 25%\n\nBronze dragons prefer to dwell in subterranean lairs near substantial bodies of water such as lakes or seas. Despite their love of wealth, bronze dragons are basically of beneficent nature. They often assume the form of some animal in order to observe the affairs of humans.\n\nThe attack of a bronze dragon is either a claw/claw/bite or either of two breath weapons — a bolt of lightning 10\" long and ½\" wide, or a repulsion gas cloud 2\" long by 3\" wide by 3\" high which affects those within it just as a repulsion spell (move away from the dragon for 6 melee rounds unless a saving throw versus dragon breath is made).\n\nMagic-using bronze dragons gain a first level spell at their 1st and 2nd growth stages, an additional second level spell at their 3rd and 4th growth stages, third level spells at the 5th and 6th growth stages, and very old and ancient dragons gain additional spells of the 4th level; thus an ancient bronze dragon would know two each of 1st through 4th level spells. These spells should be selected randomly.", -- complete Monster Manual prose, verbatim
}
