-- BROWNIE
-- Source: Monster Manual, page 12+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BROWNIE",
  page = 12,
  hitDice = "\u00bd",
  hitDiceNum = 0.5,
  hitDiceBonus = 0,
  avgHp = 2,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 1, max = 3 } },
  xp = 65,
  xpPerHp = 1,
  xpValue = 67, -- 65 + 1/hp x 2 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 4, max = 16 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "O, P, Q" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "S",
  sizeDetail = "1\u00bd' tall",
  intelligence = "high",
  alignment = "lawful_good",
  specialAttacks = "Spells",
  specialDefenses = "Save as 9th level cleric",
  magicResistance = "As above",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Brownies are distant relatives of halflings, (perhaps half halfling, half pixie) but they are smaller and far less common. They are basically friendly to humans and their ilk (dwarves, elves, and halflings), but because they are shy, they are seldom seen and favor quiet, pastoral areas in which to dwell. If encountered on friendly terms, brownies can often (50%) be convinced to help lawful good characters. They are able to make or repair items of wood, leather, metal, etc. with ease. They are also good guides. Brownies can use the following spells once per day: protection from evil, ventriloquism, dancing lights, continual light, mirror image (3 images), confusion, and dimension door. Brownies do not usually carry weapons other than short swords. They have exceptional senses in general, are never surprised, and have 18 dexterity. Brownies are capable of blending into the landscape very quickly, in effect using natural cover and speed to become invisible (and escape if desired).\n\nBesides their own language and the alignment tongue, brownies speak elvish, pixieish, and the language of sprites and halflings.", -- complete Monster Manual prose, verbatim
}
