-- BULL
-- Source: Monster Manual, page 13+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "BULL",
  page = 13,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 7,
  numAttacks = 2,
  damage = { { min = 1, max = 6 }, { min = 1, max = 6 } },
  xp = 85,
  xpPerHp = 4,
  xpValue = 157, -- 85 + 4/hp x 18 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 1, max = 20 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "5' at shoulder",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Charge",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The bull is a dangerous opponent, being aggressive and easily aroused to anger. There is a 75% chance that if approached within 8\" it will attack. A charging bull will do 3-12 points of damage upon impact with an additional 1-4 points of trampling damage. A charge must cover at least 30'. Such animals as the wild ox and the aurochs fall under this general class. When a herd is present there will be several bulls which will defend the rest.", -- complete Monster Manual prose, verbatim
}
