-- CAMEL, Wild
-- Source: Monster Manual, page 14+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CAMEL, Wild",
  page = 14,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 1, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 21, modes = { { mode = "walk", rate = 21 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal_to_semi-",
  alignment = "neutral",
  specialAttacks = "Spitting",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Single humped camels (dromedaries) are found only in very warm desert areas. The double humped (bactrian) sort are able to abide cold and even non-desert regions. All camels are able to go for up to two weeks without food or water. They can carry loads up to 6,000 gold pieces weight, although this reduces their speed to 9\"; if loaded between 4,000 and 5,000 gold pieces, their speed is 15\" maximum. (The bactrian camel is 3\" slower than the dromedary, so reduce its movement accordingly).\n\nCamels can attack by biting (they can kick, but do not typically do so). They tend to be nasty tempered and may spit at persons coming to ride or use them similarly — 50% chance to do so, 25% chance of blinding for 1-3 melee rounds if they do spit.\n\nHorses tend to dislike the odor of camels.", -- complete Monster Manual prose, verbatim
}
