-- CARRION CRAWLER
-- Source: Monster Manual, page 14+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CARRION CRAWLER",
  page = 14,
  hitDice = "3 + 1",
  hitDiceNum = 3,
  hitDiceBonus = 1,
  avgHp = 15,
  armorClass = { 3, 7 },
  numAttacks = 8,
  damage = { { raw = "Paralysis" } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 120, -- 60 + 4/hp x 15 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 6 },
  lairPct = 50,
  treasure = { individual = nil, inLair = "B" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "9' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "As above",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Carrion crawlers strongly resemble a cross between a giant green cutworm and a huge cephalopod. They are usually found only in subterranean areas. The carrion crawler is, as its name implies, a scavenger, but this does not preclude aggressive attacks upon living creatures, for that insures a constant supply of corpses upon which to feed or for deposit of eggs. The head of the monster is well protected, but its body is only armor class 7. A carrion crawler moves quite rapidly on its multiple legs despite its bulk, and a wall or ceiling is as easily traveled as a floor, for each of the beast's feet are equipped with sharp claws which hold it fast. The head is equipped with 8 tentacles which flail at prey; each 2' long tentacle exudes a gummy secretion which when fresh, will paralyze opponents (save versus paralyzation or it takes effect). As there are so many tentacles with which to hit, and thus multiple chances of being paralyzed, these monsters are greatly feared.", -- complete Monster Manual prose, verbatim
}
