-- CATOBLEPAS
-- Source: Monster Manual, page 14+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CATOBLEPAS",
  page = 14,
  hitDice = "6 + 2",
  hitDiceNum = 6,
  hitDiceBonus = 2,
  avgHp = 29,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 6 } },
  xp = 225,
  xpPerHp = 8,
  xpValue = 457, -- 225 + 8/hp x 29 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 3 },
  lairPct = 60,
  treasure = { individual = nil, inLair = "C" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = "6' at shoulder",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Gaze causes death",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "This nightmare creature is loathsome beyond description and has no redeeming features. Its body resembles that of a huge, bloated buffalo and gives off an offensive odor. The catoblepas' neck is long and thin, and perched atop it is a big head uglier than that of a warthog. Its legs are thick and stumpy, much like a hippopotamus. The creature's tail is strong and snakey, however, and moves with amazing swiftness to strike enemies. Any creature so struck has a base 75% chance of being stunned for 1-10 melee rounds; the base chance being modified by adjustment downward by 5% for every level (or hit die for monsters) above 1. Thus, if an 11th level character is struck by the tail there is only a 25% chance of stunning. Perhaps its habitat — fetid swamps and miasmal marshes — caused the bizarre combination of genetic characteristics in this monster, or perhaps it was due to some ghastly tinkering with life by a demented godling. In any case, the most horrid aspect of the catoblepas is its bloodshot eyes.\n\nThe gaze of the catoblepas is equal to a death ray, extending 6\" from the eyes (even into the astral and ethereal planes). Any creature which meets this gaze dies without any chance to save itself. Complete surprise (a 2 on 6-sided die) means one of the party encountering the monster has met its gaze. Otherwise the very weak neck of the catoblepas has only a 25% chance of raising the head high enough to use its eyes. If both parties are still this chance increases by 15% per melee round. If the monster must follow quick movements, or if it is shambling along in pursuit of prey, there is only a 10% chance per melee round of the neck raising the head sufficiently high to fix its gaze. A fleeing victim, even with eyes averted, is subject to the deadly effect of the catoblepas' eyes, although there is a saving throw.", -- complete Monster Manual prose, verbatim
}
