-- CATTLE, Wild
-- Source: Monster Manual, page 14+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CATTLE, Wild",
  page = 14,
  hitDice = "1-4",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 11,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 10,
  xpPerHp = 1,
  xpValue = 21, -- 10 + 1/hp x 11 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 20, max = 200 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Stampede",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Wild cattle roam many wilderness areas, and they are frequently encountered. They are likely to flee any threat, although the males of the herd are likely (75%)\n\nto attack if the intruders come upon the herd before it has a chance to run away (see BULL). There is also a 25% chance that a herd of wild cattle will stampede directly at the party. If cattle stampede and there is no cover (rocks, trees, logs, a wall, etc.) then roll two 4-sided dice for each member of the party in the path of the stampede in order to find how many cattle trample each party member. Trampling causes 1-4 hit points of damage per creature trampling.", -- complete Monster Manual prose, verbatim
}
