-- CENTIPEDE, Giant
-- Source: Monster Manual, page 15+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CENTIPEDE, Giant",
  page = 15,
  hitDice = "½",
  hitDiceNum = 0.5,
  hitDiceBonus = 0,
  avgHp = 2,
  armorClass = 9,
  numAttacks = 1,
  damage = {  },
  xp = 5,
  xpPerHp = 1,
  xpValue = 7, -- 5 + 1/hp x 2 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 2, max = 24 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "S",
  sizeDetail = "1'+ long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Poison",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These nasty creatures are found nearly everywhere. They are aggressive and rush forth to bite their prey, injecting poison into the wound, but in many cases this poison is weak and not fatal (add +4 to saving throw die roll). Also, as the centipede is small, it is less likely to resist attacks which allow it a saving throw (-1 on die).\n\nCentipedes come in many colors — pale gray to black, red to brown.", -- complete Monster Manual prose, verbatim
}
