-- CHIMERA
-- Source: Monster Manual, page 15+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CHIMERA",
  page = 15,
  hitDice = "9",
  hitDiceNum = 9,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = { 6, 5, 2 },
  numAttacks = 6,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 2, max = 8 }, { min = 3, max = 12 } },
  xp = 1000,
  xpPerHp = 12,
  xpValue = 1480, -- 1000 + 12/hp x 40 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 40,
  treasure = { individual = nil, inLair = "F" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 }, { mode = "walk", rate = 18 } } },
  size = "L",
  sizeDetail = "4' at shoulder",
  intelligence = "semi-",
  alignment = "chaotic_evil",
  specialAttacks = "Breath weapon",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The chimera combines features of three creatures in a monstrous manner. Its hind quarters are those of a huge goat, its foreparts are those of a lion, its body sports dragon wings, and it has three large heads. It can claw with its fore legs, its goat head is armed with two long horns, its lion head has powerful jaws and sharp teeth, and its dragon head is likewise equipped. If a chimera desires (50% chance) its dragon head can breathe fire with a range of 5\" and causing 3-24 points damage (saving throw applicable). Chimerae speak a very limited form of red dragon language.\n\nDescription: The goatish body parts are black with amber eyes and yellowish horns. The lion-like parts are tawny yellow with a dark brown mane, green eyes, and red maw. The dragon wings are brownish-black, the dragon head orange, and the eyes and mouth black.", -- complete Monster Manual prose, verbatim
}
