-- Cloud Giant
-- Source: Monster Manual, page 45+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Cloud Giant",
  page = 45,
  hitDice = "12 + 2-7",
  hitDiceNum = 12,
  hitDiceBonus = 4,
  avgHp = 58,
  armorClass = 2,
  numAttacks = 1,
  damage = { { min = 6, max = 36 } },
  xp = 1800,
  xpPerHp = 18,
  xpValue = 2844, -- 1800 + 18/hp x 58 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 6 },
  lairPct = 40,
  treasure = { individual = nil, inLair = "E, Q (x5)" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "18' tall",
  intelligence = "average_to_very",
  alignment = "neutral_(good_50%,_evil_50%)",
  specialAttacks = "Hurling rocks for 2-24 hit points",
  specialDefenses = "Surprised only on 1",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Unlike the commoner sorts of giants, cloud giants usually reside in crude castles built atop mountains or on magical cloud islands. When found in their lair it is 60% likely that cloud giants will have 1-4 spotted lions as pets/guards. If more than 1 cloud giant is encountered in their lair it is 75% likely that the second will be a giantess (treat as fire giant for hit dice and damage/attack) and the others young giants (roll percentile dice to determine state of maturity). If 6 giants are thus encountered, one of the young will be a full-grown male, one a full-grown female, and the other two sub-adults of either sex (1-3 male, 4-6 female).\n\nAdult cloud giants can hurl rocks from 1\" to 24\" distance, inflicting from 2-24 hit points of damage when they hit. They have a 60% chance of catching like missiles. All cloud giants have a keen sense of smell, thus they are surprised only on a roll of 1 on a 6-sided die. 10% of cloud giants are very intelligent. These will be the ones found dwelling on cloud islands. All such cloud giants are able to levitate themselves and additional weight of up to 20,000 gold pieces twice per day.\n\nThere is a 50% chance that evil cloud giants will have 1-3 captives as slaves in their lair.\n\nDescription: Cloud giants have pale blue white to light blue skin, silver white or brass colored hair, and wear various items of clothing and jewelry. They are armed with great clubs.", -- complete Monster Manual prose, verbatim
}
