-- Copper Dragon (Draco Comes Stabuli)
-- Source: Monster Manual, page 33+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Copper Dragon (Draco Comes Stabuli)",
  page = 33,
  hitDice = "7-9",
  hitDiceNum = 7,
  hitDiceBonus = 0,
  avgHp = 36,
  armorClass = 1,
  numAttacks = 3,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 5, max = 20 } },
  xp = 225,
  xpPerHp = 8,
  xpValue = 513, -- 225 + 8/hp x 36 avg hp
  xpSource = "formula",
  frequency = "uncommon-rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 35,
  treasure = { individual = nil, inLair = "H, S" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 }, { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = "36' long",
  intelligence = "high",
  alignment = "chaotic_good",
  specialAttacks = "Breath weapon",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "+ possible magic use\n\nAttack Modes: Nil\n\nCHANCE OF:\n\nSpeaking: 45%\n\nMagic Use: 40%\n\nSleeping: 40%\n\nCopper dragons prefer to inhabit arid rocky regions, liking warmer climes in which to locate their cavern or cave lairs. They tend to be rather selfish, and thus many copper dragons are somewhat neutral in their outlook if gain is concerned.\n\nThe normal attack of this kind of dragon is either a claw/claw/bite or the use of one or the other of its breath weapons \u2014 a discharge of acid exactly similar to that of a black dragon (7\" x \u00bd\") or a cloud of gas 3\" long by 2\" wide by 2\" deep which will slow any creatures therein unless they make their saving throw vs. dragon breath. The slowing effect causes creatures to move/attack at one-half normal, and it lasts for 6 melee rounds.\n\nThose copper dragons able to use magic gain a 1st level spell for each of their first three age brackets, a 2nd level spell in addition at each bracket of the next three ages, and at the last two an additional 3rd level at each. Thus, a magic-using ancient copper dragon would know three 1st level spells, three 2nd level spells, and two 3rd level spells.", -- complete Monster Manual prose, verbatim
}
