-- CRAB, Giant
-- Source: Monster Manual, page 16+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CRAB, Giant",
  page = 16,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 3,
  numAttacks = 2,
  damage = { { min = 2, max = 8 }, { min = 2, max = 8 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 2, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "L",
  sizeDetail = "4'+ dia.",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant crabs are found in any area near water of any sort. They operate equally well on land or in water, always seeking to find something to eat. Their eyes, being on stalks, can peek over ledges or around corners with ease. They tend to hide and rush forth to seize their prey (surprise on a 1-4 on a 6-sided die).", -- complete Monster Manual prose, verbatim
}
