-- CROCODILE (Normal)
-- Source: Monster Manual, page 16+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CROCODILE (Normal)",
  page = 16,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 5,
  numAttacks = 2,
  damage = { { min = 2, max = 8 }, { min = 1, max = 12 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 3, max = 24 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "8'-15' long",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Although some of these reptiles are of giant-size, such monsters are typically found only in salt water or in prehistoric settings. All crocodiles are stupid and voracious eaters. They are sluggish in cold weather (cut movement 50%). They typically lie in concealment in order to surprise prey (surprise on 1-3 on a 6-sided die).\n\n[Shared family description from CROCODILE (Giant)]", -- complete Monster Manual prose, verbatim
}
