-- CROCODILE (Giant)
-- Source: Monster Manual, page 16+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "CROCODILE (Giant)",
  page = 16,
  hitDice = "7",
  hitDiceNum = 7,
  hitDiceBonus = 0,
  avgHp = 32,
  armorClass = 4,
  numAttacks = 2,
  damage = { { min = 3, max = 18 }, { min = 2, max = 20 } },
  xp = 225,
  xpPerHp = 8,
  xpValue = 481, -- 225 + 8/hp x 32 avg hp
  xpSource = "formula",
  frequency = "very_rare_to_common",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "21'-30' long",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Although some of these reptiles are of giant-size, such monsters are typically found only in salt water or in prehistoric settings. All crocodiles are stupid and voracious eaters. They are sluggish in cold weather (cut movement 50%). They typically lie in concealment in order to surprise prey (surprise on 1-3 on a 6-sided die).", -- complete Monster Manual prose, verbatim
}
