-- DEMON, Type I (Vrock)
-- Source: Monster Manual, page 19+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DEMON, Type I (Vrock)",
  page = 19,
  hitDice = "8",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 36,
  armorClass = 0,
  numAttacks = 5,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 1, max = 8 }, { min = 1, max = 8 }, { min = 1, max = 6 } },
  xp = 375,
  xpPerHp = 10,
  xpValue = 735, -- 375 + 10/hp x 36 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 1, max = 3 },
  lairPct = 5,
  treasure = { individual = nil, inLair = "B" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 18 } } },
  size = "L",
  sizeDetail = "8½' tall",
  intelligence = "low",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "50%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These are among the weakest of their kind; type 1 demons somewhat resemble a cross between a human and a vulture. Strength is standard. They may be struck with normal missiles and by normal weapons. Darkness caused by them is the typical 5' radius sort. In addition these demons have the ability\n\nto do any one of the following, one at a time, at will: Detect invisible objects, telekinese 2,000 gold piece weight, gate in another type I demon (10% chance of success).\n\nThese creatures are very fond of the flesh of the human sort, and they also prize precious metals and stones. Because of their stupidity they are not often prone to listen to bribe offers.", -- complete Monster Manual prose, verbatim
}
