-- DEMON, Type VI (Balor)
-- Source: Monster Manual, page 20+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DEMON, Type VI (Balor)",
  page = 20,
  hitDice = "8 + 8",
  hitDiceNum = 8,
  hitDiceBonus = 8,
  avgHp = 44,
  armorClass = -2,
  numAttacks = 1,
  damage = { { min = 2, max = 13 } },
  xp = 900,
  xpPerHp = 14,
  xpValue = 1516, -- 900 + 14/hp x 44 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 3 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "F" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "12' tall",
  intelligence = "high",
  alignment = "chaotic_evil",
  specialAttacks = "Whip & flame for 2-12/3-18/4-24",
  specialDefenses = "+1 or better weapon to hit",
  magicResistance = "75%",
  psionic = "180",
  attackDefenseModes = "A, B, C, E/F, G, H",
  text = "Each type VI demon has its own name. (Balor is a type VI demon of the largest size.) Six are known to exist. The favored weapons of these monsters are a large +1 sword and a whip with many \"tails.\" The latter weapon is employed to drag the opponent into the flames which the demons are able to create around themselves. During any combat there is a two-thirds chance (1-4 on a 6-sided die) each melee round that any type VI demon will immolate and use its whip. The two largest of these demons do 4-24 hit points of damage when a victim is drawn within their flames, the middle-sized and smallest do 3-18 and 2-12 respectively.\n\nThey shed darkness in a 10' radius at will. Their other singular abilities are: Cause fear (as a fear wand), detect magic, read magic, read languages, detect invisible objects, cause pyrotechnics, dispel magic, suggestion, telekinese 6,000 gold piece weight, use a symbol of fear, discord, sleep or stunning, and they also have a 70% chance of successfully gating in a demon of type III (80%) or type IV (20%). Each of these terrible abilities can be employed as often as desired, but only one may be used at any given time.\n\nWith proper invoking, offerings, and promises type VI demons might be convinced to co-operate with a character or group for a time. Naturally, the demon will attempt to assume/usurp command at every opportunity. Most chaotic evil monsters are drawn to the strong evil charisma of this creature, and of all its kind, the type VI demon tends towards a more organized evil (which makes it less than popular with demon lords and princes).", -- complete Monster Manual prose, verbatim
}
