-- DEMON, Type IV (Nalfeshnee)
-- Source: Monster Manual, page 20+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DEMON, Type IV (Nalfeshnee)",
  page = 20,
  hitDice = "11",
  hitDiceNum = 11,
  hitDiceBonus = 0,
  avgHp = 50,
  armorClass = -1,
  numAttacks = 3,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 2, max = 8 } },
  xp = 1300,
  xpPerHp = 16,
  xpValue = 2100, -- 1300 + 16/hp x 50 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 3 },
  lairPct = 15,
  treasure = { individual = nil, inLair = "E" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 }, { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "10½'+ tall",
  intelligence = "very",
  alignment = "chaotic_evil",
  specialAttacks = "bonus of +2 to hit; also see below",
  specialDefenses = "+1 or better weapons to hit",
  magicResistance = "65%",
  psionic = "150",
  attackDefenseModes = "A, C, E/F, G, H",
  text = "These demons combine the worst features of an ape and a boar, and their small wings appear unable to bear their ponderous ten foot tall bodies. Unlike lower sorts of demons, type IV can be hit only by weapons and missiles of the magical sort. Much as a type III, these demons cause darkness in a 10' radius at will. They have these other abilities which can be employed one per melee round: Create illusion (similar to that from an illusion wand), cause fear (as a fear wand), levitate (as a 12th level magic-user), detect magic, read languages, dispel magic, polymorph self, telekinese 5,000 gold piece weight, project image, use a symbol of fear or discord, and gate in a demon of type I-IV (dice for which sort) (60% chance).\n\nSome type IV demons have names, and these can be spoken with if the conjuring party knows the proper one to say; this will make it 90% certain the demon will listen to offers of great rewards for some small service. These demons are also fond of human flesh and blood.", -- complete Monster Manual prose, verbatim
}
