-- DEVIL, Bone (Lesser)
-- Source: Monster Manual, page 22+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DEVIL, Bone (Lesser)",
  page = 22,
  hitDice = "9",
  hitDiceNum = 9,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = -1,
  numAttacks = 1,
  damage = { { min = 3, max = 12 } },
  xp = 600,
  xpPerHp = 12,
  xpValue = 1080, -- 600 + 12/hp x 40 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 2 },
  lairPct = 55,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "9\u00bd' tall",
  intelligence = "very",
  alignment = "lawful_evil",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "40%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Bone devils populate the lower planes of Hell, particularly the fifth. They are particularly malicious and delight in making less powerful creatures suffer. As they prefer cold to heat, these monsters also have ultraviolet, seeing light in the ultra-violet spectrum at 60' range.\n\nBone devils have a great bone hook they employ to snare and wound opponents. Any creature caught (hit) by it has a 50% chance of being stuck fast. The bone devil will then strike such victims with its tail doing 2-8 hit points of damage, plus causing a loss of strength (1-4 points) unless a save versus poison is made; strength loss lasts for 10 melee rounds.\n\nAt will, once per turn or melee round, as applicable, bone devils can: generate fear in a 5' radius sphere, create illusion, fly, become invisible, detect invisible, fear (spell), or summon another bone devil (40% chance of success). Once per day it is able to create a wall of ice.", -- complete Monster Manual prose, verbatim
}
