-- DEVIL, Barbed (Lesser)
-- Source: Monster Manual, page 22+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DEVIL, Barbed (Lesser)",
  page = 22,
  hitDice = "8",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 36,
  armorClass = 0,
  numAttacks = 3,
  damage = { { min = 2, max = 8 }, { min = 2, max = 8 }, { min = 3, max = 12 } },
  xp = 375,
  xpPerHp = 10,
  xpValue = 735, -- 375 + 10/hp x 36 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 2 },
  lairPct = 50,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = "7' tall",
  intelligence = "very",
  alignment = "lawful_evil",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "35%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Barbed devils populate the third and fourth planes of Hell. They are excellent guards and alert at all times (never surprised). Unauthorized creatures are immediately cast into one of the many cells to be tormented.\n\nWhile these monsters carry no weapons, they have sufficient weaponry with their horny, barbed hands and horrid tails. They are able to generate fear (saving throw versus wand is applicable) upon striking an opponent. Barbed devils can perform any of the following, one at a time, per turn or melee round, as applicable: pyrotechnics, produce flame, hold person, or summon another barbed devil (30% chance of success).", -- complete Monster Manual prose, verbatim
}
