-- DOG (War)
-- Source: Monster Manual, page 30+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DOG (War)",
  page = 30,
  hitDice = "2 + 2",
  hitDiceNum = 2,
  hitDiceBonus = 2,
  avgHp = 11,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 68, -- 35 + 3/hp x 11 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = nil,
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Dog, War: These are simply large dogs which are trained to fight. They are loyal to their masters and ferocious in attack. They are typically protected by light studded leather armor and a spiked collar. The number appearing depends on their masters.\n\nDog, Wild: Packs of wild dogs inhabit most regions, and their ranges will sometimes overlap those of wolves. If well-fed they will simply avoid contact. They can be tamed only if separated from their pack.\n\n[Shared family description from DOG (Wild)]", -- complete Monster Manual prose, verbatim
}
