-- DOLPHIN
-- Source: Monster Manual, page 30+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DOLPHIN",
  page = 30,
  hitDice = "2 + 2",
  hitDiceNum = 2,
  hitDiceBonus = 2,
  avgHp = 11,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 65,
  xpPerHp = 3,
  xpValue = 98, -- 65 + 3/hp x 11 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 20 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 30, modes = { { mode = "walk", rate = 30 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "lawful_good",
  specialAttacks = "Nil",
  specialDefenses = "Save as 4th level fighter",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Most dolphins simply roam the oceans in nomadic schools. A small number (10%), however, have formed underwater communities, and if one is located it is 75% probable that there will be from 1-4 additional communities of\n\ndolphins within a 5 mile radius. Communal dolphins will have from 2-5 swordfish (AC 6, move 24\", 1 + 1 dice, 2-12 hit points damage/attack) or 1-3 narwhales (AC 6, move 21\", 4 + 4 hit dice, 2-24 hit points damage/attack), depending on the climatic region, as guards.\n\nDolphins will attack any creature which threatens them, although they will help humans in distress. They particularly hate sharks of all sorts and will attack unless outnumbered by 2 or more to 1.", -- complete Monster Manual prose, verbatim
}
