-- DOPPLEGANGER
-- Source: Monster Manual, page 30+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DOPPLEGANGER",
  page = 30,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 1, max = 12 } },
  xp = 330,
  xpPerHp = 4,
  xpValue = 402, -- 330 + 4/hp x 18 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 3, max = 12 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "E" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "neutral",
  specialAttacks = "Surprise on a 1-4",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These bipedal creatures are of mutable form so that they are able to shape themselves into the likeness of any humanoid creature of from 4' to 8' tall which they observe. Having become the double for a person they attempt to do away with that victim and assume its place. If unable to do this, the doppleganger will simply attack, counting on the confusion engendered to make it indistinguishable from the creature it is mimicking (surprise means this works). Dopplegangers are able to ESP and imitate with 90% accuracy. They are subject to neither sleep nor charm spells. Despite having only 4 hit dice they make all saving throws as if they were 10th level fighting men.\n\nNote: A doppleganger actually forms itself into the likeness of the clothing and equipment of the imitated creature as well as the physical features thereof.", -- complete Monster Manual prose, verbatim
}
