-- DRYAD
-- Source: Monster Manual, page 36+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "DRYAD",
  page = 36,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 9,
  numAttacks = 1,
  damage = { { raw = "Dagger" } },
  xp = 105,
  xpPerHp = 3,
  xpValue = 132, -- 105 + 3/hp x 9 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 6 },
  lairPct = 70,
  treasure = { individual = nil, inLair = "M (x100), Q (x10)" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "high",
  alignment = "neutral",
  specialAttacks = "Charm",
  specialDefenses = "See below",
  magicResistance = "50%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "PSONIC ABILITY: Nil  \n\nThese beautiful and alluring tree sprites are found only in the most secluded places. They are found only near oak trees and never more than 36' from their individual tree of which they are actually a part. A dryad is shy and non-violent. Unless surprised, a dryad can disappear by stepping into a tree, slipping out on a side unseen by the intruder(s), and dimension door to her own tree. Dryad trees are distinguished only by their large size; they do not radiate any magic. If seriously threatened, or if near a male with a 16 or greater charisma, the dryad will use her powerful charm person spell which may be cast up to three times per day, once per melee round, with a minus 3 on the victim's saving throw. If a person is taken away by a dryad, there is a 50% chance they will never return, and if they do return it will be from 1-4 years later. Dryads can speak their own tongue, elven, pixieish, sprite, and also speak with plants. If carefully approached they might be persuaded to aid a person or party. Dryads have exact knowledge of the wood or forest in which they dwell.", -- complete Monster Manual prose, verbatim
}
