-- EAGLE, Giant
-- Source: Monster Manual, page 37+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "EAGLE, Giant",
  page = 37,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 7,
  numAttacks = 3,
  damage = { { min = 1, max = 6 }, { min = 1, max = 6 }, { min = 2, max = 12 } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 132, -- 60 + 4/hp x 18 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 20 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "Q, C (magic only)" },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 }, { mode = "walk", rate = 48 } } },
  size = "M",
  sizeDetail = "20' wing spread",
  intelligence = "average",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant eagles are found only in places where there are great bluffs, cliffs, mesas, or mountain crags to nest on. Their eyesight is such that they are never surprised unless encountered in their lair or at night. If they attack by diving 50 or more feet they add +4 to hit probability, do double claw damage (2-12/2-12), but get no beak attack. They can carry up to 2,000 gold pieces at half speed.\n\nIf encountered outside their lair, giant eagles will typically ignore any good creatures but attack evil creatures which seem to be threatening. They are fairly friendly towards certain dwarves and elves. They have their own language and can also communicate through a limited form of telepathy. If encountered in their lair they will always be hostile. If there are young (50%) or eggs there they will attack any creature within 50'. There will be 1-4 young per nest, 1 nest per 2 giant eagles. They can be tamed. Eggs sell on the open market for 500 to 800 gold pieces each.", -- complete Monster Manual prose, verbatim
}
