-- Earth Elemental
-- Source: Monster Manual, page 39+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Earth Elemental",
  page = 39,
  hitDice = "16",
  hitDiceNum = 16,
  hitDiceBonus = 0,
  avgHp = 72,
  armorClass = 2,
  numAttacks = 1,
  damage = { { min = 4, max = 32 } },
  xp = 2400,
  xpPerHp = 20,
  xpValue = 3840, -- 2400 + 20/hp x 72 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "+2 or better weapon to hit",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These powerful creatures travel rather slowly, and in order to cross water they must travel through the ground and go under the bed of the body of water (possibly a long trip). They score full damage against any creature which rests on the earth, -2 on each die of damage against other opponents (flying, levitating, etc.). Against constructions built on stone or earth they act as a super battering ram, causing 2-8 points of structural damage (a typical cottage having about 7 structural points). They can be summoned from earth or stone.\n\nOn the elemental plane of earth there exists a boss rumored to be of astounding size.", -- complete Monster Manual prose, verbatim
}
