-- EEL (Electric)
-- Source: Monster Manual, page 37+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "EEL (Electric)",
  page = 37,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 9,
  numAttacks = 1,
  damage = { { min = 1, max = 3 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 38, -- 20 + 2/hp x 9 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 3, max = 7 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 72, modes = { { mode = "walk", rate = 72 } } },
  size = "M",
  sizeDetail = "9' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Jolt",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "All eels are water-dwellers. They are typically aggressive only when approached too closely.\n\nElectric eels are found in warm fresh water. They will give off a jolt of electricity in a radius of 15'. They are immune to electrical effects. Any creature within 5' of the eel takes 3-24 hit points damage; within 5' to 10' the jolt delivers 2-16 hit points damage, and between 10' and 15' the jolt delivers 1-8 hit points. The eel can do this but once per hour (six turns). Marine species are reported to be twice the size and do twice the damage.\n\nGiant eels are typically of the moray type. They have a nasty temper and teeth to match. Few (10%) are found in fresh water.\n\nWeed eels are masters of camouflage, appearing as a patch of normal seaweed to any but a highly trained observer. They live in colonies, sharing food and home alike. Their bite is poisonous, and unless a saving throw is made the creature bitten will die. Weed eel colonies consist of a network of small (six to eight inch diameter) holes which all lead to several 6' diameter tunnels, and the latter lead to a communal cave about 30' long, 20' wide, and 20' high. The eels use small stones, coins, gems, metal, etc. to floor this cave with. Colonies are found in both fresh and salt water, typically in water depths of 25' to 40'. If an attempt is made to enter any hole, the eel to whom it belongs will always strike with incredible speed. If eels note the entrance of foreign creatures, they will leave their holes to protect the cave where young are raised.\n\n[Shared family description from EEL (Weed)]", -- complete Monster Manual prose, verbatim
}
