-- ELEPHANT (African)
-- Source: Monster Manual, page 39+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "ELEPHANT (African)",
  page = 39,
  hitDice = "11",
  hitDiceNum = 11,
  hitDiceBonus = 0,
  avgHp = 50,
  armorClass = 6,
  numAttacks = 5,
  damage = { { min = 2, max = 16 }, { min = 2, max = 16 }, { min = 2, max = 16 }, { min = 2, max = 12 }, { min = 2, max = 12 } },
  xp = 1500,
  xpPerHp = 14,
  xpValue = 2200, -- 1500 + 14/hp x 50 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 1, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "11' tall",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The elephant is found only in warm climates. They attack by means of a stab with two tusks, a grab and squeeze with their trunk, and then two tramplings with their front feet. One opponent can be subject to no more than two of these attacks at the same time, but several opponents can be fought simultaneously \u2014 6 or more man-sized opponents for example. Ogre-sized opponents will not be affected by trunk attacks. Elephants are relatively intelligent, and will not trunk-attack creatures which will harm their trunk, i.e. spikey, hot, etc. They fear fire. An elephant can easily break open a great gate by pushing unless the gate is spiked to prevent this. They can be trained to carry equipment and/or men.\n\nElephant tusks have a value of 100 to 600 gold piece value each. Each gold piece of value equals one-quarter pound of weight.\n\nIf more than one-half the possible number is encountered, there will be young animals in the herd \u2014 from 1 to 4, 20% to 70% mature. If a single animal is\n\nencountered it will be a rogue bull, with no fewer than 6 hit points per die, and a very nasty and aggressive temper. Rogues will attack 90% of the time.\n\n(See also the headings MAMMOTH and MASTODON for information on elephants.)", -- complete Monster Manual prose, verbatim
}
