-- EYE OF THE DEEP
-- Source: Monster Manual, page 42+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "EYE OF THE DEEP",
  page = 42,
  hitDice = "10-12",
  hitDiceNum = 10,
  hitDiceBonus = 0,
  avgHp = 50,
  armorClass = 5,
  numAttacks = 3,
  damage = { { min = 2, max = 8 }, { min = 2, max = 8 }, { min = 1, max = 6 } },
  xp = 3700,
  xpPerHp = 16,
  xpValue = 4500, -- 3700 + 16/hp x 50 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "R" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = "3'-5' dia.",
  intelligence = "very",
  alignment = "lawful_evil",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "It is possible that this monster is a relative of the beholder, for there are remarkable similarities between the two species. The eye of the deep dwells only at great depths of the ocean, floating slowly about, stalking prey. It has two huge crab-like pincers to seize its victims and a mouth full of small sharp teeth. Its primary weapons, however, are its eyes. The creature has a large central eye which emits a blinding flash of light to dazzle and stun those in its ray (cone ½\" at eye extending 3\" to a 2\" diameter base) for 2-8 melee rounds unless a saving throw versus death ray/poison is made. The eye of the deep also has two smaller eyes on long stalks with which it is able to create an illusion; or, acting independently, the small eyes are able to cast hold person and hold monster spells respectively.\n\nBecause it inhabits the deeps, this monster has an armor class of 5 everywhere, including eyes and eye stalks. It can withstand 10 to 12 dice of damage before being killed. If its eyestalks are severed they will, as with those of a beholder, grow back in about a week of time.\n\nNature: The eye of the deep is hateful and aggressive, generally conforming to its land-dwelling cousin, the beholder, as regards temperament.", -- complete Monster Manual prose, verbatim
}
