-- EYE, Floating
-- Source: Monster Manual, page 41+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "EYE, Floating",
  page = 41,
  hitDice = "1-4 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 2,
  armorClass = 9,
  numAttacks = "Nil",
  damage = {  },
  xp = 5,
  xpPerHp = 1,
  xpValue = 7, -- 5 + 1/hp x 2 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 30, modes = { { mode = "walk", rate = 30 } } },
  size = "S",
  sizeDetail = "1' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Hypnotism",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Floating eyes are salt water fish of very unusual nature. They have transparent bodies and a single large eye of about three inch diameter. The latter is all that is readily visible of this fish, and when it is gazed at the creature so doing must save versus paralyzation or become hypnotized and remain stationary. Predatory fish (always near floating eyes) then eat the helpless prey, while the floating eyes feed upon the scraps. Naturally, these creatures also eat any small marine creatures they come upon and hypnotize.", -- complete Monster Manual prose, verbatim
}
