-- Fire Elemental
-- Source: Monster Manual, page 39+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Fire Elemental",
  page = 39,
  hitDice = "16",
  hitDiceNum = 16,
  hitDiceBonus = 0,
  avgHp = 72,
  armorClass = 2,
  numAttacks = 1,
  damage = { { min = 3, max = 24 } },
  xp = 2400,
  xpPerHp = 20,
  xpValue = 3840, -- 2400 + 20/hp x 72 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "+2 or better weapon to hit",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Fire elementals are terrible to behold and fierce opponents. They set fire to any inflammable material they touch. Against fire-using opponents they score -1 on their damage dice. Fire elementals are checked by water, being unable to pass over non-inflammable liquids.\n\nOn the elemental plane of fire exist many sorts of different fire elementals and similar beings. The ruler of all fire elementals is reported to be known as the tyrant.", -- complete Monster Manual prose, verbatim
}
