-- Fire Giant
-- Source: Monster Manual, page 45+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Fire Giant",
  page = 45,
  hitDice = "11 + 2-5",
  hitDiceNum = 11,
  hitDiceBonus = 3,
  avgHp = 53,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 5, max = 30 } },
  xp = 1300,
  xpPerHp = 16,
  xpValue = 2148, -- 1300 + 16/hp x 53 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 8 },
  lairPct = 35,
  treasure = { individual = nil, inLair = "E" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "12' tall",
  intelligence = "average_to_low",
  alignment = "lawful_evil",
  specialAttacks = "Hurling rocks for 2-20 hit points",
  specialDefenses = "Impervious to fire",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Fire giants are as often found in castles as in caverns. If found in their lair it is 25% likely that they will have 1-4 hell hounds of the largest size as watch dogs. If more than 4 fire giants are encountered in their lair the additional ones will be females (corresponding to frost giants for hit dice and damage/attack), except that if 7 or 8 are encountered the last one or two will be young (roll percentile dice for size).\n\nAdult fire giants are able to hurl rocks from 1\" to 20\" distances, inflicting 2-20 hit points of damage. They can catch like missiles 50% of the time. Fire giants are impervious to fire, even red dragon breath.\n\nDescription: Fire giants are very broad (about 6' at the shoulders), looking almost like dwarves. Their skins are coal black, hair is flaming red or bright orange, and eyes are deep red. Their teeth are usually yellow orange. They wear armor or dragon hides. They favor huge swords.", -- complete Monster Manual prose, verbatim
}
