-- Flesh Golem
-- Source: Monster Manual, page 49+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Flesh Golem",
  page = 49,
  hitDice = "40 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = 9,
  numAttacks = 2,
  damage = { { min = 2, max = 16 }, { min = 2, max = 16 } },
  xp = 600,
  xpPerHp = 12,
  xpValue = 1080, -- 600 + 12/hp x 40 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 8, modes = { { mode = "walk", rate = 8 } } },
  size = "L",
  sizeDetail = "7\u00bd' tall",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "A flesh golem can be created by means of a magical tome or by a high-level magic-user employing a wish spell, a polymorph any object, a geas, a protection from normal missiles and a strength spell. The latter case demands a level of magic-use of at least the 14th. The cost in materials is 1,000 gold pieces per hit point of the golem. It requires 1 month to fashion the creature.\n\nThe creator of the flesh golem controls the monster, being able to have it follow simple commands (go ahead, stop, kill, etc.). The master of the golem can have it suspend its functioning until a set event takes place (such as someone entering its room).\n\nHowever, for each turn of melee a flesh golem engages in there is a 1% per melee round cumulative chance it will go berserk, attacking at random anything in sight. The monster's master has a 10% per melee round chance of regaining control of the golem.\n\nThe flesh golem is very powerful and able to smash through doors and wooden structures of normal construction. For example, a flesh golem would break through an oaken door with iron reinforcing bands and hinges, in 5-8 melee rounds. It does 1 point of structural damage to wooden constructions only every 3 melee rounds.\n\nNormal weapons do not harm flesh golems, but magical weapons have normal effect. Spells of most sorts have no effect on such monsters, but fire or cold based spells (such as wall of fire, fire ball, ice storm, etc.) slow the golem by 50% for 2-12 melee rounds. Electrical attacks restore damage to the golem in direct relation to the number of dice of damage normally done, i.e. a 6 die lightning bolt restores 6 hit points of damage which the golem might have sustained.", -- complete Monster Manual prose, verbatim
}
