-- Frost Giant
-- Source: Monster Manual, page 45+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Frost Giant",
  page = 45,
  hitDice = "10 + 1-4",
  hitDiceNum = 10,
  hitDiceBonus = 2,
  avgHp = 47,
  armorClass = 4,
  numAttacks = 1,
  damage = { { min = 4, max = 24 } },
  xp = 1300,
  xpPerHp = 16,
  xpValue = 2052, -- 1300 + 16/hp x 47 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 8 },
  lairPct = 30,
  treasure = { individual = nil, inLair = "E" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "15' tall",
  intelligence = "average_to_low",
  alignment = "chaotic_evil",
  specialAttacks = "Hurling rocks for 2-20 hit points",
  specialDefenses = "Impervious to cold",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil 44",
  text = "Frost giants more commonly inhabit castles, although they often lair in large frigid caverns. There is a 50% probability that they will have from 1-6 winter wolves in their lair as watchdogs. If more than 4 frost giants are encountered in their lair numbers 5 and 6 will be females (treat as stone giants with respect to hit dice and damage/attack), and 7 and 8 will be young giants (roll percentile dice to determine size).\n\nAdult frost giants are able to hurl rocks from 1\" to 20\" distances, inflicting 2-20 hit points of damage. They can catch like missiles 40% of the time. Frost giants are impervious to cold, even white dragon breath.\n\nDescription: Frost giants have dead white or ivory skin color, blue-white or yellow hair, and pale blue or yellow eyes. Their build is basically similar to a muscular human, with appropriate size differences. Frost giants wear armor and bear arms similar to those of humans of the northern barbarian sort.", -- complete Monster Manual prose, verbatim
}
