-- FUNGI, Violet
-- Source: Monster Manual, page 43+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "FUNGI, Violet",
  page = 43,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = "1-4",
  damage = { { raw = "See below" } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 } } },
  size = "S",
  sizeDetail = "to M",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Violet fungus growths resemble shriekers, and are usually (75%) encountered with them. The latter are immune to the touch of violet fungi, and the two types of creatures complement each other's existence. Violet fungi favors rotted animal matter to grow upon. Each fungus has 1 to 4 branches which it will flail out with if any animal comes within their 1' to 4' range. The excretion from these branches rots flesh in but one melee round unless a saving throw versus poison is made or a cure disease is used. The branch length of this growth depends upon size. Violet fungi range from 4' to 7' tall, the smallest having 1' branches, the 5' sort having 2' branches, etc. Any sized growth can have 1 to 4 branches.", -- complete Monster Manual prose, verbatim
}
