-- GAR, Giant
-- Source: Monster Manual, page 43+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GAR, Giant",
  page = 43,
  hitDice = "8",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 36,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 5, max = 20 } },
  xp = 375,
  xpPerHp = 10,
  xpValue = 735, -- 375 + 10/hp x 36 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 6 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 30, modes = { { mode = "walk", rate = 30 } } },
  size = "L",
  sizeDetail = "21'-30' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Unlike their smaller relatives, giant gar tend to be aggressive hunters. They inhabit only large, deep lakes and rivers. They are capable of swallowing prey whole, and any hit of 20 indicates they have done so. Note that a small giant gar can swallow an elf or dwarf whole. If a creature is swallowed whole there is a 5% chance/melee round that it will die. A creature so swallowed must have a sharp-edged weapon in hand to have any chance of cutting its way out. The swallowed creature must be able to inflict damage equal to 25% of the fish's total hit points to get free. Attacks which pierce the gar can hit the creature swallowed whole (assume 20% chance), and this will cause appropriate damage to both the gar and the creature swallowed.", -- complete Monster Manual prose, verbatim
}
