-- GELATINOUS CUBE
-- Source: Monster Manual, page 44+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GELATINOUS CUBE",
  page = 44,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 8,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 150,
  xpPerHp = 4,
  xpValue = 222, -- 150 + 4/hp x 18 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = "See below" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = "10' cube",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Paralyzation, surprise on 1-3",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The gelatinous cube is one of the scavengers not uncommon in dungeons. Its cubic form is ideal for cleaning all living organisms, as well as carrion, from the floor and walls of underground passageways. Certain very large cubes are taller so as to be able to garner mosses and the like from ceilings as well.\n\nGelatinous cubes are nearly transparent and are difficult to see (thus surprise on 1-3). As these monsters travel about they sweep up metallic and other items which are \"indigestible\" to them. This includes treasure types J, K, L, M, N, Q as well as a potion, dagger, or similar items. Such material will remain in the body of a gelatinous cube for several weeks before being cast out (thus deposited somewhere on the floor).\n\nIf a gelatinous cube touches (hits) an opponent, a saving throw versus paralyzation must be made, or the creature touched is anesthetized for 5-20 melee rounds. The cube then surrounds the victim, secretes digestive fluids, and digests a meal. Damage caused to opponents is due to the digestive secretions.\n\nGelatinous cubes can be hit by all forms of weapons, and attacks by fire have normal effects. Cold will have no effect on these monsters unless they fail their saving throw, in which case they are slowed 50% and do only 1-4 hit points of damage. Electricity, fear, holds, paralyzation, polymorph, and sleep based attacks have no effect on gelatinous cubes.", -- complete Monster Manual prose, verbatim
}
