-- GHAST
-- Source: Monster Manual, page 44+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GHAST",
  page = 44,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 4,
  numAttacks = 3,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 1, max = 8 } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 132, -- 60 + 4/hp x 18 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 6 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "B, Q, R, S, T" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These creatures are so like ghouls as to be completely indistinguishable from them, and they are usually found only with a pack of ghouls. When the pack attacks it will quickly become evident that ghosts are present, however, for they exude a carrion stench in a 10' radius which causes retching and nausea unless a saving throw versus poison is made. Those failing to make this save will attack at a penalty of -2 on \"to hit\" dice rolls. Worse, the ghost attacks as a ghoul with regard to paralyzation, and this attack will affect elves as well.\n\nGhosts are of the \"undead\" class so sleep and charm spells do not affect them. They are struck by any sort of weapon; cold iron causes double\n\ndamage, and clerics can turn them. The circle of protection from evil does not keep them at bay unless it is used in conjunction with cold iron (such as a circle of powdered iron, an iron ring, etc.).\n\nThese creatures are often used as slaves by powerful demons.", -- complete Monster Manual prose, verbatim
}
