-- GHOST
-- Source: Monster Manual, page 44+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GHOST",
  page = 44,
  hitDice = "10",
  hitDiceNum = 10,
  hitDiceBonus = 0,
  avgHp = 45,
  armorClass = { "0 (or 8)", "see below" },
  numAttacks = 1,
  damage = { { min = 10, max = 40 } },
  xp = 4050,
  xpPerHp = 14,
  xpValue = 4680, -- 4050 + 14/hp x 45 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "E, S" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "high",
  alignment = "lawful_evil",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Ghosts are the spirits of evil humans who were so awful in their badness that they have been rewarded (or perhaps cursed) by being given undead status. Thus they roam about at night or in places of darkness. These spirits hate goodness and life, hungering to draw the living essences from humans. As ghosts are non-corporeal (ethereal), they are usually encountered by creatures in a like state, although they can be seen by non-ethereal creatures. The supernatural power of a ghost is such, however, that the mere sight of one causes any humanoid being to age 10 years and flee in panic for 2-12 turns unless a saving throw versus magic is made. Clerics above 6th level are immune to this effect, and all other humanoids above 8th level add +2 to their saving throws.\n\nGhosts attack by two means: Any creature within 6\" of one is subject to attack by magic jar spell from the ghost. Unless the ghost becomes semi-material to attack by other means, it can otherwise only be combatted by another in the ethereal plane (in which case the ghost has an armor class of 8) or by telepathic means. If the ghost fails to magic jar its chosen victim, it will then semi-materialize in order to attack by touch (in which case the ghost is armor class 0). Semi-materialized ghosts can only be struck by silver (doing 50% of normal damage) or magical weapons. If they strike an opponent it ages him 10-40 years. Note that ghosts can be attacked with spells only from creatures who are in an ethereal state. Any human — including dwarves, elves, gnomes, and halflings — killed by a ghost is forever dead.", -- complete Monster Manual prose, verbatim
}
