-- GHOUL
-- Source: Monster Manual, page 44+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GHOUL",
  page = 44,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 1, max = 6 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 38, -- 20 + 2/hp x 9 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 24 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "B, T" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "chaotic_evil",
  specialAttacks = "Paralyzation",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Ghouls are \"undead,\" once human creatures which feed on human and other corpses. Although their change from human to ghoul has deranged and destroyed their minds, ghouls have a terrible cunning which enables them to hunt their prey most effectively. Ghouls attack by clawing with their\n\nfilthy nails and with fangs. Their touch causes humans \u2014 including dwarves, gnomes, half-elves, and halflings, but excluding elves \u2014 to become rigid (paralysis) unless a saving throw versus paralysis is successful. Any human killed by a ghoulish attack will become a ghoul unless blessed (or blessed and then resurrected). Ghoul packs always attack without fear.\n\nThese creatures are subject to all attack forms except sleep and charm spells. They can be turned by clerics. The magic circle of protection from evil actually keeps these monsters completely at bay.\n\nLacedon: The lacedon is a marine form of the ghoul. It conforms in all other respects to ghouls.", -- complete Monster Manual prose, verbatim
}
