-- GORGON
-- Source: Monster Manual, page 50+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GORGON",
  page = 50,
  hitDice = "8",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 36,
  armorClass = 2,
  numAttacks = 1,
  damage = { { min = 2, max = 12 } },
  xp = 1750,
  xpPerHp = 10,
  xpValue = 2110, -- 1750 + 10/hp x 36 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 40,
  treasure = { individual = nil, inLair = "E" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Breath turns to stone",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Gorgons are bull-like creatures covered with thick metal scales. They prefer the fastness of a wilderness or dreary caverns for habitation. A gorgon is able to breathe out a cloud of noxious vapors which will turn any creature to stone unless they make the appropriate saving throw. The breath shoots forth in truncated cone-shape, \u00bd\" diameter at the beasts' mouth, 6\" in length, to an end diameter of 2\". A gorgon is able to use such breath up to 4 times per day. Gorgons will always use this attack form in preference to other sorts of attack.\n\nThe awareness of gorgons extends into the astral and ethereal planes. So do the effects of their breath weapon.", -- complete Monster Manual prose, verbatim
}
