-- GRAY OOZE
-- Source: Monster Manual, page 50+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GRAY OOZE",
  page = 50,
  hitDice = "3 + 3",
  hitDiceNum = 3,
  hitDiceBonus = 3,
  avgHp = 17,
  armorClass = 8,
  numAttacks = 1,
  damage = { { min = 2, max = 16 } },
  xp = 200,
  xpPerHp = 5,
  xpValue = 285, -- 200 + 5/hp x 17 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 3 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 } } },
  size = "M",
  sizeDetail = "to L",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "21-121",
  attackDefenseModes = "E/Nil",
  text = "Gray ooze is a slimy horror which inhabits subterranean places. I resembles wet stone or sedimentary cave formations.\n\nThis creature corrodes metal at the same rate a black pudding (qv) does, i.e. chainmail is eaten through in a single melee round. Its acids do no harm to stone or wood. Spells do not harm this creature, and it is impervious to heat or cold. Lightning, however, causes full damage to gray ooze, as do blows from weapons. Note, however, that in the latter case the weapons striking the creature may corrode and break. They strike like snakes when attacking.\n\nLarge specimens (over 18 hit points) are larger than a full grown man, some (those over 21 hit points) are fully 3' wide and 12' long, although only about 6 or 8 inches thick.\n\nIn exceptionally large individuals intelligence of a sort is well developed. Furthermore, these exceptional individuals have a latent psionic ability, and if psionic powers are used within 6\" of them they will prepare a psychic crush of from 21 to 121 psionic strength attack points and direct it at any individual within range who uses psionic abilities. After loosing its psionic attack the gray ooze can be psionically attacked.", -- complete Monster Manual prose, verbatim
}
