-- GRIFFON
-- Source: Monster Manual, page 51+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GRIFFON",
  page = 51,
  hitDice = "7",
  hitDiceNum = 7,
  hitDiceBonus = 0,
  avgHp = 32,
  armorClass = 3,
  numAttacks = 3,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 2, max = 16 } },
  xp = 375,
  xpPerHp = 10,
  xpValue = 695, -- 375 + 10/hp x 32 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 12 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "C, S" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 30 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Griffons seek cliffs and rocky habitats in which to build their nests. If conditions permit they will lair in a cave. They are aggressive carnivores, and their favorite prey are horses. If they come within sighting or smelling distance (36\" as a general rule) of horseflesh, the griffons will wing to the hunt. They are much sought after in their fledgling state, for they can be tamed for use as fierce, loyal, steeds if obtained before maturity. If encountered in their lair, there is a 75% chance that there will be 1 or 2 eggs or young for every 2 griffons. The young are non-combative, but the adults will attack until killed. Fledglings sell for 5,000 gold pieces, eggs for 2,000, on the open market.", -- complete Monster Manual prose, verbatim
}
