-- GROANING SPIRIT (Banshee)
-- Source: Monster Manual, page 51+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "GROANING SPIRIT (Banshee)",
  page = 51,
  hitDice = "7",
  hitDiceNum = 7,
  hitDiceBonus = 0,
  avgHp = 32,
  armorClass = 0,
  numAttacks = 1,
  damage = { { min = 1, max = 8 } },
  xp = 2450,
  xpPerHp = 10,
  xpValue = 2770, -- 2450 + 10/hp x 32 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 70,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "exceptional",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "+1 or better weapon to hit",
  magicResistance = "50%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The groaning spirit, or banshee, is the spirit of an evil female elf — a very rare thing indeed. The spirit returns to harm the living. It is found only in desolate countrysides, moors, etc. The groaning spirit can attack by its chilling touch, causing 1-8 hit points of damage/attack when it strikes. Its more fearsome mode of attack, however, is its wail, or keening, which will cause the hearers within 3\" to save versus magic or die on the spot. The sight of a groaning spirit causes fear unless an appropriate saving throw is made. It can wail but once per day, and only during darkness. Groaning spirits cannot be affected by charm, sleep, or hold spells. They are impervious to attack by cold or electricity. Exorcism kills them.", -- complete Monster Manual prose, verbatim
}
