-- HARPY
-- Source: Monster Manual, page 52+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "HARPY",
  page = 52,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = 3,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 1, max = 6 } },
  xp = 145,
  xpPerHp = 3,
  xpValue = 187, -- 145 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 2, max = 12 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "C" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 15 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "chaotic_evil",
  specialAttacks = "Singing & charm",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Harpies have the bodies of vultures but the upper torsos and heads of women. They are voracious carnivores and foul creatures. Those that dwell along seacoasts are generally known as sirens. All harpies are able to emit sweet-sounding calls. Any creature hearing these calls will proceed towards the harpies unless they save versus magic. Similarly, the touch of a harpy charms those creatures which fail to make their saving throw versus magic. The harpies attack, torture, and devour their charmed prey. What they do not want they foul with excrement. A harpy attacks with her vulture claws and some form of weapon — often a bone club or some weapon left from one of her former victims. They speak their own language and none other.", -- complete Monster Manual prose, verbatim
}
