-- HERD ANIMAL
-- Source: Monster Manual, page 52+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "HERD ANIMAL",
  page = 52,
  hitDice = "1-5",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = "8-7",
  numAttacks = "Variable",
  damage = { { raw = "Variable" } },
  xp = 10,
  xpPerHp = 1,
  xpValue = 24, -- 10 + 1/hp x 14 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 20, max = 200 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 }, { mode = "walk", rate = 24 } } },
  size = "S",
  sizeDetail = ", M, or L",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Stampede",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Herd animals live in all climes \u2014 musk oxen and reindeer at the North Pole, giraffe and antelopes at the equator. The smallest will have but 1 hit die, the largest will have 5. Attacks are simply a matter of the animals' in question modes of defense (horns, butting, hooves, flight). Damage is a factor of defense (attack) mode and size/strength. As herd animals are not aggressive, they will stampede away from what they perceive to be the greatest threat to their safety. Humans or humanoids of about man-size or less, will be trampled to death if caught in the path of a stampede.", -- complete Monster Manual prose, verbatim
}
