-- Hill Giant
-- Source: Monster Manual, page 46+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Hill Giant",
  page = 46,
  hitDice = "8 + 1-2",
  hitDiceNum = 8,
  hitDiceBonus = 1,
  avgHp = 37,
  armorClass = 4,
  numAttacks = 1,
  damage = { { min = 2, max = 16 } },
  xp = 600,
  xpPerHp = 12,
  xpValue = 1044, -- 600 + 12/hp x 37 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 1, max = 10 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "10½' tall",
  intelligence = "low",
  alignment = "chaotic_evil",
  specialAttacks = "Hurling rocks for 2-16 hit points",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Hill giants always dwell in caves or similar underground habitations. These lairs are typically of forsaken areas. Hill giants sometimes have other creatures in their lairs to act as guards; this is 50% likely, and the guarding creatures will be 2-8 dire wolves (50%), 1-3 giant lizards (30%) or a group of 2-8 ogres (20%). If more than 4 hill giants are encountered in their lair numbers 5, 7, and 9 will be giantesses (6 hit dice, and treat as ogres for damage/attack) and 6, 8, and 10 will be young hill giants (roll percentile dice for size).\n\nAdult hill giants are able to hurl rocks from 1\" to 20\" distances, inflicting 2-16 hit points of damage. They are able to catch similar missiles 30% of the time. 50% of hill giants also speak ogre.\n\nDescription: Hill giants have tan to reddish brown skins, brown to black hair, and red-rimmed eyes. They typically dress in rough hides or skins. They use any form of weapon available but favor clubs.", -- complete Monster Manual prose, verbatim
}
