-- HIPPOPOTAMUS
-- Source: Monster Manual, page 53+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "HIPPOPOTAMUS",
  page = 53,
  hitDice = "8",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 36,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 12 } },
  xp = 375,
  xpPerHp = 6,
  xpValue = 591, -- 375 + 6/hp x 36 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 }, { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "As their name implies, hippopotami are found in rivers and lakes of tropical regions. They are herbivores, but they aggressively defend their own territory. A hippopotami bites with exceedingly strong jaws, and a bull will do 3-18 hit points of damage/attack. There will be 1-3 bulls in a herd, 1 for every 4 animals. If a boat or canoe passes over submerged hippopotami there is a 50% chance that a bull will emerge under it and tip the craft over. Hippopotami travel underwater by running along the bottom. They can stay submerged for 15 minutes.", -- complete Monster Manual prose, verbatim
}
