-- HIPPOCAMPUS
-- Source: Monster Manual, page 52+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "HIPPOCAMPUS",
  page = 52,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 132, -- 60 + 4/hp x 18 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 2, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 24, modes = { { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "average",
  alignment = "chaotic_good",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The hippocampus is the most prized of marine steeds, for they are strong, swift, and intelligent. They differ from the normal seahorse in that they have a long rear body similar to that of a great fish, and the hippocampus has forelegs ending in powerful fins. Their bodies are covered with fine scales in the fore parts, large scales elsewhere. They speak their own language and can learn another if properly trained. Tritons are often found in possession of these creatures.", -- complete Monster Manual prose, verbatim
}
