-- HOMONCULOUS
-- Source: Monster Manual, page 54+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "HOMONCULOUS",
  page = 54,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 1, max = 3 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 38, -- 20 + 2/hp x 9 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 18 } } },
  size = "S",
  sizeDetail = "1½\"",
  intelligence = "see_below",
  alignment = "see_below",
  specialAttacks = "Bite causes sleep",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "This creature is created and animated through a special process by a magic-user and an alchemist (described hereafter). The homonculous travels on its hind legs or by flying. Its bite causes 1-3 points of damage, and forces the victim to save versus magic or fall into a comatose sleep which lasts for 5-30 minutes. The creature makes all of its saving throws at the same level as its creator. Although the homonculous cannot speak, it knows what the magic-user knows, and the latter is able to see and hear through the creature's eyes and ears. There is a telepathic link between the magic-user and his creature, and the homonculous can be controlled up to 48\" away from its master. It will never willingly pass from this maximum range. If the homonculous is killed the magic-user immediately suffers 2-20 points of damage.\n\nWhen a homonculous is desired the magic-user must hire an alchemist, and the latter will require from 1-4 weeks to create fluids for forming the creature. This will cost 1 pint of the magic-user's blood and 500-2,000 gold pieces.\n\nThe magic-user must then cast a mending spell, a mirror image, and a wizard eye upon the fluid to form the homonculous.\n\nDescription: When the homonculous is finished it will be man-like in form, about 18\" tall, have a greenish, reptilian skin, leathery wings, and a bat-like mouth with teeth passing on a venom which causes sleep unless the party bitten saves vs. magic.", -- complete Monster Manual prose, verbatim
}
