-- HYENA (Giant (Hyaenodon))
-- Source: Monster Manual, page 55+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "HYENA (Giant (Hyaenodon))",
  page = 55,
  hitDice = "5",
  hitDiceNum = 5,
  hitDiceBonus = 0,
  avgHp = 22,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 3, max = 12 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 101, -- 35 + 3/hp x 22 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 2, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Hyenas are pack animals dwelling on warm plains. They are hunter/scavengers with very strong jaws and aggressive if hungry.\n\nHyaenodons are simply huge (prehistoric) hyenas.", -- complete Monster Manual prose, verbatim
}
