-- HYENA (Hyena)
-- Source: Monster Manual, page 55+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "HYENA (Hyena)",
  page = 55,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 2, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Hyenas are pack animals dwelling on warm plains. They are hunter/scavengers with very strong jaws and aggressive if hungry.\n\nHyaenodons are simply huge (prehistoric) hyenas.\n\n[Shared family description from HYENA (Giant (Hyaenodon))]", -- complete Monster Manual prose, verbatim
}
