-- INTELLECT DEVOURER
-- Source: Monster Manual, page 55+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "INTELLECT DEVOURER",
  page = 55,
  hitDice = "6 + 6",
  hitDiceNum = 6,
  hitDiceBonus = 6,
  avgHp = 33,
  armorClass = 4,
  numAttacks = 4,
  damage = { { min = 1, max = 4 } },
  xp = 1510,
  xpPerHp = 8,
  xpValue = 1774, -- 1510 + 8/hp x 33 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 2 },
  lairPct = 60,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "200",
  attackDefenseModes = "C, E/F, G",
  text = "The intellect devourer is one of the most feared of monsters. They are found dwelling deep beneath the ground or in dark and dismal lairs in the wilderness. Although they are able to attack with their great claws, their primary offensive means is psionic, for they subsist on the psychic energy of their prey — whether gained from the dying shriek or by more subtle means.\n\nIf psionic energy (from abilities or magical means) is in use nearby (6\") they will stalk the user, seeking a time to attack him alone and by surprise. The monster then leaps upon his victim, tearing with his claws and psionically attacking with ego whip or id insinuation. If psionically successful the devourer will then house itself within the mindless body, seeking to deceive others by assuming the character of the person it has slain. The intellect devourer will then seek opportunities to attack and devour others.\n\nThey are able to hide in shadow as well as a 10th level thief. Normal weapons and most spells have no effect upon these monsters. Magical weapons +3 or more cause 1 point of damage upon them when they hit. Bright light will drive them off, and a protection from evil will keep them at a distance. Fireballs serve only as a bright light, but lightning bolts will cause them pain and some small damage (1 point per die of lightning bolt strength). A death spell has a 25% chance of success, and a power word kill will slay them. Of course, they can be psionically attacked, and their psionic strength of 200 total makes this not too difficult. However, if seriously threatened they will seek to flee and save themselves.\n\nTheir awareness extends to the astral and ethereal planes, and intellect devourers often roam the astral and ethereal planes. They are able to speak any human language.", -- complete Monster Manual prose, verbatim
}
