-- Iron Golem
-- Source: Monster Manual, page 49+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Iron Golem",
  page = 49,
  hitDice = "80 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 80,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 4, max = 40 } },
  xp = 3000,
  xpPerHp = 25,
  xpValue = 5000, -- 3000 + 25/hp x 80 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = "12' tall",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Construction of an iron golem, bipedal and manlike, requires a magical tome or a magic-user of 18th or higher level employing the following spells: wish, polymorph any object, geas, and cloud kill. The cost in materials is 1,000 gold pieces per hit point, and it requires 3 months construction time.\n\nThe golem created always remains under the control of the magic-user who created it. It can obey any simple commands. It will stand, non-functioning, as a guard until some event takes place, i.e. until a door is opened, a book read, etc.\n\nIn addition to striking, an iron golem will breathe out a cloud of poisonous gas, 1\" x 1\" x 1\", directly before it, once every 7 melee rounds.\n\nThe strength of an iron golem is three times greater than that of a flesh golem. An iron golem can do 1 point of structural damage per melee round.\n\nAn iron golem can be struck only by magical weapons of +3 or greater enchantment. Normal and magical weapons under +3 do no damage. The only magical attacks which affect the iron golem are electrical, such as a lightning bolt, which slows the monster 50% for 3 melee rounds. Magical fire attacks repair damage on a 1 hit point for 1 hit point basis. Iron golems are subject to attack from the rust monsters.", -- complete Monster Manual prose, verbatim
}
