-- IXITXACHITL
-- Source: Monster Manual, page 56+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "IXITXACHITL",
  page = 56,
  hitDice = "1 + 1",
  hitDiceNum = 1,
  hitDiceBonus = 1,
  avgHp = 5,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 3, max = 12 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 30, -- 20 + 2/hp x 5 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 10, max = 100 },
  lairPct = 60,
  treasure = { individual = nil, inLair = "See below" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "average_to_high",
  alignment = "chaotic_evil",
  specialAttacks = "Evil clerical spells",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil ixitxachitl are a race of intelligent rays which dwell in shallow tropical seas. They are of evil disposition, and clerical in nature. For every 10 encountered there will be one which is the equivalent of a 2nd level human cleric with regard to spell use; for every 20 encountered there will be a 3rd level equivalent; and for every 50 encountered there will be a 5th level equivalent. If more than 50 are encountered there will be the following additional ixitxachitl with the group: a leader with 8th level clerical spell ability and quadruple normal hit dice, two guards with 6th level clerical spell ability and triple normal hit dice. Also, some of these monsters are vampiric. For every 20 ixitxachitl encountered there is a 50% chance that there will be a vampiric form in the group. Vampiric ixitxachitl are similar to their fellows, but they regenerate 3 hit points per melee round and drain an energy level each time they strike an opponent, and they have double hit dice.",
  text = "Discovering an ixitxachitl lair is difficult, for they are typically made in coral reefs and hidden by a secret entrance. Inside the lair will be various items as shown for treasure types P, R, and S. If a leader is encountered there is the possibility that it and its guards will possess type U magic items which can be worn, or used without hands if the creatures are in their lair.", -- complete Monster Manual prose, verbatim
}
