-- Juiblex (The Faceless Lord)
-- Source: Monster Manual, page 18+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Juiblex (The Faceless Lord)",
  page = 18,
  hitDice = "88 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 88,
  armorClass = -7,
  numAttacks = 1,
  damage = { { min = 4, max = 40 } },
  xp = 4000,
  xpPerHp = 30,
  xpValue = 6640, -- 4000 + 30/hp x 88 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 60,
  treasure = { individual = nil, inLair = "P (x2), R (x2)" },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 } } },
  size = "L",
  sizeDetail = "9'+ tall",
  intelligence = "genius",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "+2 or better weapon to hit",
  magicResistance = "65%",
  psionic = "225",
  attackDefenseModes = "All/all",
  text = "There is no question that this is the most disgusting and loathsome of all demons. Juiblex is foul and nauseating in the extreme. His dripping form can lash forward in melee to cause terrible damage — both from the force of his blow and the caustic properties of his noisome secretions. Juiblex is reclusive and hates intrusion by any form of normal creature but surrounds his person with slimes, jellies, and puddings. If encountered in his lair there will be from 1-4 green slimes, 2-8 ochre jellies, 1-4 gray oozes, and 1-4 black puddings. He is similarly shunned by other demons and other creatures.\n\nJuiblex is able to shed a circle of darkness (15' radius) at will. He can also cause fear (as a fear wand), cast a circle of cold (10' radius), and regenerate at 2 hit points per melee round. This demon lord is also able to do any one of the following during a melee round: detect invisible, locate object, ESP, fly, dispel magic, invisibility (10' radius), charm monster, hold monster, telekinese 15,000 gold piece weight, project image, phase door, putrify food & water, cause disease, speak with monsters, speak an unholy word once per day, and gate in 1-4 type II demons (70% chance of success). He is also able to spew forth a jelly-like slime (combining the effects of an ochre jelly and green slime) once per turn (every ten melee rounds) with a 15' range and a blob size of 3 cubic feet.\n\nDescription: Juiblex has no set form (he can spread himself into a vast pool of slime or raise up into a towering column of disgusting ordure 18' or more in height) but he usually takes the form of a 9' tall cone-like heap, striated in disgusting blackish greens, foul browns and yellows, and sickly translucent grays and ambers. From this mass protrude several glaring red eyes.", -- complete Monster Manual prose, verbatim
}
