-- LAMIA
-- Source: Monster Manual, page 60+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LAMIA",
  page = 60,
  hitDice = "9",
  hitDiceNum = 9,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 1700,
  xpPerHp = 12,
  xpValue = 2180, -- 1700 + 12/hp x 40 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 60,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 24, modes = { { mode = "walk", rate = 24 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "high",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Lamias prefer to dwell in deserts \u2014 in ruined cities, caves, or the like. Their upper torso, arms, and head resemble a human female, while their lower body is that of a beast. Lamias are very fast and powerful. They usually are armed with daggers.\n\nA lamia is able to use the following spells once per day: charm person, mirror image, suggestion, and illusion (as a wand). These spells are typically used to lure persons to the lamia and then hold them there for the creature to devour. The lamia's touch permanently drains 1 point of wisdom from a victim, and when wisdom drops below 3 they willingly do whatever the lamia tells them to do. Lamias first drain their prey of blood and then feast upon the flesh. They can speak their alignment language and the common tongue.", -- complete Monster Manual prose, verbatim
}
