-- LAMPREY (Normal)
-- Source: Monster Manual, page 60+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LAMPREY (Normal)",
  page = 60,
  hitDice = "1 + 2",
  hitDiceNum = 1,
  hitDiceBonus = 2,
  avgHp = 6,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 2 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 32, -- 20 + 2/hp x 6 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 2 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "S",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Drain blood",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Lampreys are leech-like eels which inhabit both fresh and salt water: They do not inhabit shallow bodies of water. They feed by biting their victims, fastening themselves to the hapless creatures with sphincter-like mouths ringed with cruel teeth. Once attached the lamprey will begin to drain blood on the next and each successive melee round. The rate of blood drain is equivalent to 2 hit points of damage per hit die the lamprey has. Thus, a giant specimen will drain blood causing 10 hit points of damage per melee round.\n\n[Shared family description from LAMPREY (Giant)]", -- complete Monster Manual prose, verbatim
}
