-- LARVA
-- Source: Monster Manual, page 60+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LARVA",
  page = 60,
  hitDice = "1",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 4,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 2, max = 5 } },
  xp = 10,
  xpPerHp = 1,
  xpValue = 14, -- 10 + 1/hp x 4 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 10, max = 40 },
  lairPct = 100,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "evil",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The larvae are the most selfishly evil of all souls who sink to lower planes after death. They abide in the gloom of Hades, controlled by the night hags. These creatures are desired by demons and devils alike, as they are used to form quasits (qv) or imps (qv) respectively. Liches employ their essence in order to retain their un-dead status and powers. Because of the value of larva the night hags use them to trade off and thus maintain the freedom of their planes.\n\nLarvae appear as sickly yellow worms with distorted human faces.", -- complete Monster Manual prose, verbatim
}
