-- LEECH, Giant
-- Source: Monster Manual, page 61+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LEECH, Giant",
  page = 61,
  hitDice = "1-4",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 11,
  armorClass = 9,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 10,
  xpPerHp = 1,
  xpValue = 21, -- 10 + 1/hp x 11 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 4, max = 16 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 } } },
  size = "S",
  sizeDetail = "to M",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Drain blood",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Found only in the fetid waters of swamps and marshes, giant leeches are a threat to any warm-blooded creature which passes within their movement range of 3\". These horrors wait in the mud and slime for prey, and as it passes they strike. Giant leeches range from 1 to 4 hit dice in size; various sized creatures usually are found in the same group. The initial attack also attaches the sucker mouth of the giant leech, and on the next melee round, and on each round thereafter, it will drain blood the equivalent of 1 hit point damage per hit die it possesses. There is only a 1% chance that the victim will be aware of the attack unless it comes out of the water, for the leech has anesthetizing saliva, and its bite and blood drain are not usually felt until weakness (loss of 50% of hit points) makes the victim aware that something is amiss. Giant leeches will come out of water at night to attack prey within 3\". They can be killed by attack or with quantities of salt sprinkled on their bodies. There is a 50% chance that the bite of one of these creatures will cause disease which will be fatal in 2-5 weeks unless cured.", -- complete Monster Manual prose, verbatim
}
