-- Lemure
-- Source: Monster Manual, page 24+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Lemure",
  page = 24,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 3 } },
  xp = 65,
  xpPerHp = 3,
  xpValue = 107, -- 65 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 5, max = 30 },
  lairPct = 100,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "lawful_evil",
  specialAttacks = "Nil",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The lemures are the form which the dead whom inhabit the Nine Hells are put in. These vaguely human blobs are then tormented by devils. Their minds are quite gone, and they will attack anything non-devilish which they see. Lemures regenerate at a rate of 1 hit point per melee round, so they are not usually destroyed by the wounds inflicted on them by their environment or by the devils filling it. These wretched things can be destroyed permanently only by blessed things (holy water, holy swords, etc.). They are not subject to any form of sleep, charm, or the like.\n\nAfter being in hell for a time certain lemures will be chosen to form wraiths or spectres (qqv).", -- complete Monster Manual prose, verbatim
}
