-- LEOPARD
-- Source: Monster Manual, page 61+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LEOPARD",
  page = 61,
  hitDice = "3 + 2",
  hitDiceNum = 3,
  hitDiceBonus = 2,
  avgHp = 16,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 1, max = 6 } },
  xp = 150,
  xpPerHp = 4,
  xpValue = 214, -- 150 + 4/hp x 16 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 2 },
  lairPct = 5,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Rear claws for 1-4/1-4",
  specialDefenses = "Surprised only on a 1",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These carnivores live in tropical woodlands and jungles. They hunt by laying in wait and leaping upon their prey, surprising on a 1-3. Leopards can spring 20' upwards or ahead 25'. If they score hits with both forepaws during a melee round, the leopard gains 2 additional attacks that round, each attack at 1-4 hit points damage.\n\nIf found in their lair, there is a 25% chance that there will be 1-3 cubs there. These young will have no effective attack.", -- complete Monster Manual prose, verbatim
}
