-- LEPRECHAUN
-- Source: Monster Manual, page 61+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LEPRECHAUN",
  page = 61,
  hitDice = "2-5 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 3,
  armorClass = 8,
  numAttacks = 0,
  damage = {  },
  xp = 80,
  xpPerHp = 1,
  xpValue = 83, -- 80 + 1/hp x 3 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 1 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "F" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "S",
  sizeDetail = "2' tall",
  intelligence = "exceptional",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "80%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Leprechauns normally dwell only in fair, green lands with lush hills and dales for them to frolic through. Occasionally a party of adventurous ones will reside elsewhere for a time. These small creatures of magical talent and mischievous nature can become invisible at will, polymorph nonliving objects, create illusions, and use ventriloquism spells as often as they like. Their keen ears prevent them from being surprised. Being full of mischief they will often (75%) snatch valuable objects from persons, turn invisible and dash away. The object stolen will be valuable, and there is 75% chance of such theft being successful. If pursued closely there is a 25% chance per turn of pursuit that the leprechaun will drop the stolen goods.\n\nIf caught or discovered in its lair the leprechaun will attempt to mislead its captor into believing he is giving over his treasure while he actually is duping the captor. It will require great care to actually obtain the leprechaun's treasure.\n\nNote: Leprechauns have a great fondness for wine, and this weakness may be used to outwit them.\n\nRumor has it leprechauns are a species of halfling with a strong strain of pixie.", -- complete Monster Manual prose, verbatim
}
