-- LEUCROTTA
-- Source: Monster Manual, page 61+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LEUCROTTA",
  page = 61,
  hitDice = "6 + 1",
  hitDiceNum = 6,
  hitDiceBonus = 1,
  avgHp = 28,
  armorClass = 4,
  numAttacks = 1,
  damage = { { min = 3, max = 18 } },
  xp = 475,
  xpPerHp = 8,
  xpValue = 699, -- 475 + 8/hp x 28 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 40,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "average",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "Kick in retreat",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "% TREASURE TYPE: D\n\nThis weird creature haunts deserted and desolated places, for it is so ugly most other creatures cannot bear the sight of it. The body of a leucrotta resembles that of a stag, its tail being rather lion-like, and its legs end in cloven hooves. Its head is that of a huge badger, but instead of teeth it has\n\nsharp, jagged bony ridges. This monster is very sly and can imitate the voice of a man or woman. They will do this to trick prey to approach within attack distance. When retreating the leucrotta can kick backwards with booth hooves, causing 1-6 hit points damage with each that hits. The monster speaks the language of its alignment as well as the common tongue.", -- complete Monster Manual prose, verbatim
}
