-- LEUCROTTA (Fire)
-- Source: Monster Manual, page 62+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LEUCROTTA (Fire)",
  page = 62,
  hitDice = "10",
  hitDiceNum = 10,
  hitDiceBonus = 0,
  avgHp = 45,
  armorClass = 3,
  numAttacks = 3,
  damage = { { min = 1, max = 8 }, { min = 1, max = 8 }, { min = 2, max = 16 } },
  xp = 475,
  xpPerHp = 8,
  xpValue = 835, -- 475 + 8/hp x 45 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 50,
  treasure = { individual = nil, inLair = "B, Q (x10), S, T" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "L",
  sizeDetail = "30' long",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "See below for each type of lizard",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "% TREASURE TYPE: D\n\nThis weird creature haunts deserted and desolated places, for it is so ugly most other creatures cannot bear the sight of it. The body of a leucrotta resembles that of a stag, its tail being rather lion-like, and its legs end in cloven hooves. Its head is that of a huge badger, but instead of teeth it has\n\nsharp, jagged bony ridges. This monster is very sly and can imitate the voice of a man or woman. They will do this to trick prey to approach within attack distance. When retreating the leucrotta can kick backwards with booth hooves, causing 1-6 hit points damage with each that hits. The monster speaks the language of its alignment as well as the common tongue.\n\n[Shared family description from LEUCROTTA]", -- complete Monster Manual prose, verbatim
}
