-- LEUCROTTA (Giant)
-- Source: Monster Manual, page 62+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LEUCROTTA (Giant)",
  page = 62,
  hitDice = "3 + 1",
  hitDiceNum = 3,
  hitDiceBonus = 1,
  avgHp = 15,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 1, max = 8 } },
  xp = 475,
  xpPerHp = 8,
  xpValue = 595, -- 475 + 8/hp x 15 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "15' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "% TREASURE TYPE: D\n\nThis weird creature haunts deserted and desolated places, for it is so ugly most other creatures cannot bear the sight of it. The body of a leucrotta resembles that of a stag, its tail being rather lion-like, and its legs end in cloven hooves. Its head is that of a huge badger, but instead of teeth it has\n\nsharp, jagged bony ridges. This monster is very sly and can imitate the voice of a man or woman. They will do this to trick prey to approach within attack distance. When retreating the leucrotta can kick backwards with booth hooves, causing 1-6 hit points damage with each that hits. The monster speaks the language of its alignment as well as the common tongue.\n\n[Shared family description from LEUCROTTA]", -- complete Monster Manual prose, verbatim
}
