-- LICH
-- Source: Monster Manual, page 62+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LICH",
  page = 62,
  hitDice = "11+",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 0,
  armorClass = 0,
  numAttacks = 1,
  damage = { { min = 1, max = 10 } },
  xp = 10500,
  xpPerHp = 16,
  xpValue = 10500, -- 10500 + 16/hp x 0 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 90,
  treasure = { individual = nil, inLair = "A" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "supra-genius",
  alignment = "neutral_(evil)",
  specialAttacks = "See below",
  specialDefenses = "+1 or better",
  magicResistance = "Standard",
  psionic = "See below",
  attackDefenseModes = "See below",
  text = "weapon to hit  \n\nA lich exists because of its own desires and the use of powerful and arcane magic. The lich passes from a state of humanity to a non-human, non-living existence through force of will. It retains this status by certain conjurations, enchantments, and a phylactery. A lich is most often encountered within its hidden chambers, this lair typically being in some wilderness area or vast underground labyrinth, and in any case both solidly constructed of stone and very dark. Through the power which changes this creature from human to lich, the armor class becomes the equivalent of +1 plate armor and +1 shield (armor class 0). Similarly, hit dice are 8-sided, and the lich can be affected only by magical attack forms or by monsters with magical properties or 6 or more hit dice.\n\nLiches were formerly ultra powerful magic-users or magic-user/clerics of not less than 18th level of magic-use. Their touch is so cold as to cause 1-10 points of damage and paralyze opponents who fail to make their saving throw. The mere sight of a lich will cause any creature below 5th level (or 5 hit dice) to flee in panic from fear. All liches are able to use magic appropriate to the level they had attained prior to becoming non-human.\n\nThe following spells or attack forms have no effect on liches: charm, sleep, enfeeblement, polymorph, cold, electricity, insanity or death spells/symbols.\n\nDescription: A lich appears very much as does a wight or mummy, being of skeletal form, eyesockets mere black holes with glowing points of light, and garments most often rotting (but most rich).", -- complete Monster Manual prose, verbatim
}
