-- LIZARD MAN
-- Source: Monster Manual, page 63+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LIZARD MAN",
  page = 63,
  hitDice = "2 + 1",
  hitDiceNum = 2,
  hitDiceBonus = 1,
  avgHp = 10,
  armorClass = "5 (4)",
  numAttacks = 3,
  damage = { { min = 1, max = 2 }, { min = 1, max = 2 }, { min = 1, max = 8 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 65, -- 35 + 3/hp x 10 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 10, max = 40 },
  lairPct = 30,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = "about 7' tall",
  intelligence = "low_average",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Lizard men are semi-aquatic, breathing air but often (35%) dwelling totally underwater and having caves which are not water filled in which they lair. They are typically found in swamps, marshes, and similar places. They band together in rough tribal form. They are omnivorous, but lizard men are likely to prefer human flesh to other foods. In this regard they have been known to ambush humans, gather up the corpses and survivors as captives, and take the lot back to their lair for a rude and horrid feast. About 1 tribe in 10 has evolved to a higher state. These lizard men will dwell in crude huts, use shields (thus armor class 4) and hurl barbed darts (3\" range, 1-4 points damage) or javelins (1-6 hit points damage) before closing with enemies. In combat these advanced lizard men employ clubs (treat as morning stars). They speak their own language.", -- complete Monster Manual prose, verbatim
}
