-- LURKER ABOVE
-- Source: Monster Manual, page 63+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LURKER ABOVE",
  page = 63,
  hitDice = "10",
  hitDiceNum = 10,
  hitDiceBonus = 0,
  avgHp = 45,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 1, max = 6 } },
  xp = 900,
  xpPerHp = 14,
  xpValue = 1530, -- 900 + 14/hp x 45 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 1 },
  lairPct = 50,
  treasure = { individual = nil, inLair = "C, Y" },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 }, { mode = "walk", rate = 9 } } },
  size = "L",
  sizeDetail = "20\" \"wing\" spread",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The lurker above is a carnivorous creature found only in subterranean places. If the chamber or cave is large there might be as many as 4 of them, but normally only 1 is encountered. A lurker can creep along surfaces but slowly (1\") or by using a gas which it generates and excretes into sacs about its body. This gives the lurker above a neutral buoyancy, and it then flaps its wing-like appendages and flies about.\n\nThey surprise prey on a 1-4 (on a 6-sided die). When disturbed the lurker drops from the ceiling, smothering all creatures beneath in the tough folds of its \"wings.\" This constriction causes 1-6 points of damage per round, and the victims will smother in 2-5 rounds in any event unless they kill the lurker and thus break free. Unintelligent, the lurker will fight until dead. Prey caught in its grip cannot fight unless the weapons used are both short and in hand at the time the creature falls upon them.\n\nDescription: This terrible beast somewhat resembles a large manta ray. Its greyish belly is so textured as to appear to be stone, and the lurker typically attaches itself to a ceiling where it is almost impossible to detect (90%) unless actually prodded.", -- complete Monster Manual prose, verbatim
}
