-- LYNX, Giant
-- Source: Monster Manual, page 65+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "LYNX, Giant",
  page = 65,
  hitDice = "2 + 2",
  hitDiceNum = 2,
  hitDiceBonus = 2,
  avgHp = 11,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 1, max = 2 }, { min = 1, max = 2 }, { min = 1, max = 4 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 68, -- 35 + 3/hp x 11 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 5,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "neutral",
  specialAttacks = "Rear claws for 1-3/1-3",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These forest cats prefer cold regions. They are aggressive and compete well with other predators because of their intelligence. If found in their lair there is a 25% chance that there will be 1-4 kittens there, 10% to 30% grown, with no effective attack. Giant lynx climb very well, swim reasonably well, and they can leap 15'. If the lynx strikes with both forepaws, it will then get two additional attacks, raking with the rear claws, each causing 1-3 hit points of damage.\n\nGiant lynx speak their own language. They have also learned to hide themselves in order to avoid detection (90% unlikely in normal circumstances) or surprise prey (surprise on 1-5). They are 75% accurate in detecting traps.\n\n\"Whaddya mean we gotta talk to this lynx?? The last monster we talked to ate half of the party!\"", -- complete Monster Manual prose, verbatim
}
