-- MAMMOTH
-- Source: Monster Manual, page 66+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MAMMOTH",
  page = 66,
  hitDice = "13",
  hitDiceNum = 13,
  hitDiceBonus = 0,
  avgHp = 58,
  armorClass = 5,
  numAttacks = 5,
  damage = { { min = 3, max = 18 }, { min = 3, max = 18 }, { min = 2, max = 16 }, { min = 2, max = 12 }, { min = 2, max = 12 } },
  xp = 3000,
  xpPerHp = 18,
  xpValue = 4044, -- 3000 + 18/hp x 58 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 1, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "10' to 14' tall",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "There are several varieties of mammoth, including the woolly and imperial —\nthe latter sort being the largest. They inhabit climes ranging from subarctic to\nsubtropical of the Pleistocene epoch. These massive herbivores are quite\naggressive if threatened.\n\nAs with elephants (q.v.) and mastodons, the mammoth has 5 attack forms, but\nin general can apply no more than 2 versus a single opponent.\n\nThe tusks of the mammoth are 50% heavier than those of the elephant, and\ntheir value is proportionately higher.", -- complete Monster Manual prose, verbatim
}
