-- MANTICORE
-- Source: Monster Manual, page 66+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MANTICORE",
  page = 66,
  hitDice = "6 + 3",
  hitDiceNum = 6,
  hitDiceBonus = 3,
  avgHp = 30,
  armorClass = 4,
  numAttacks = 3,
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 1, max = 8 } },
  xp = 225,
  xpPerHp = 8,
  xpValue = 465, -- 225 + 8/hp x 30 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 4 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "E" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 18 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "lawful_evil",
  specialAttacks = "Tail spikes",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Manticores prefer dismal lairs, so they are typically found in caves or\nunderground. They range in all climes, although they enjoy warm places\nmore than cold. The favorite prey of manticores is man, and they are usually\nencountered outside their lairs hunting for human victims.\n\nA manticore attacks first by loosing a volley of 6 of its iron tail spikes (18'\nrange as a light crossbow, 1-6 hit points damage per hit). They can fire four\nsuch volleys.\n\nDescription: The coloration of the manticore is that of its various parts \u2014\nlion-colored body, bat-brown wings, human flesh head.", -- complete Monster Manual prose, verbatim
}
