-- MASHER
-- Source: Monster Manual, page 66+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MASHER",
  page = 66,
  hitDice = "8",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 36,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 5, max = 20 } },
  xp = 375,
  xpPerHp = 10,
  xpValue = 735, -- 375 + 10/hp x 36 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Poison spines",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These worm-like fish move slowly along coral reefs, crushing and eating the\ncoral growth. If surprised or threatened they are prone to attack in \"self\ndefense.\"\n\nMashers have a number of dorsal spines, 4' long, with poisonous secretions.\nAn individual will have 4, 6, or 8. Unless fought from directly ahead or\nunderneath, the masher is able to jut these spines so as to prevent attack or\nbe stuck with a spine (save versus poison or be killed).", -- complete Monster Manual prose, verbatim
}
