-- MASTODON
-- Source: Monster Manual, page 66+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MASTODON",
  page = 66,
  hitDice = "12",
  hitDiceNum = 12,
  hitDiceBonus = 0,
  avgHp = 54,
  armorClass = 6,
  numAttacks = 5,
  damage = { { min = 2, max = 16 }, { min = 2, max = 16 }, { min = 2, max = 12 }, { min = 2, max = 12 }, { min = 2, max = 12 } },
  xp = 2000,
  xpPerHp = 16,
  xpValue = 2864, -- 2000 + 16/hp x 54 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 1, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "10' tall",
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Mastodons dwell in nearly any climate, from near arctic to tropical. These\nhuge herbivores are distantly related to elephants, but their body is somewhat\nlower and longer. They are common on Pleistocene plains.\n\nAlthough the mastodon has 5 attack modes (2 tusks, 1 trunk, 2 forefeet), they\ncannot employ more than 2 of them at one time against a single opponent.\nFor details of attack limitations and other data see ELEPHANT.\n\nTheir tusks are of the same weight and value as those of elephants.", -- complete Monster Manual prose, verbatim
}
