-- MERMAN
-- Source: Monster Manual, page 71+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MERMAN",
  page = 71,
  hitDice = "1 + 1",
  hitDiceNum = 1,
  hitDiceBonus = 1,
  avgHp = 5,
  armorClass = 7,
  numAttacks = 1,
  damage = { { raw = "By weapon type" } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 30, -- 20 + 2/hp x 5 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 20, max = 200 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "C, R" },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 }, { mode = "walk", rate = 18 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "average_to_very",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Mermen are found in the seas and oceans in the warm temperate and tropical areas. They range over areas harvesting the vegetation and hunting the fish the seas provide. Additionally, mermen actually herd certain fishes. They venture out of water only to sun themselves or to visit some coastal spot.\n\nMermen have regular undersea communities, generally a reef or cliff honeycombed with passages and rooms. Only 10% of the time will they construct a village of shells, rocks, and coral. This community will have areas where the merwomen and their young (100% and 100% of the total merman population respectively) live, netted pens where food fishes are kept, workshops, and so on. These communities will be guarded by from 3-18 of the larger-sized barracuda (q.v.), for mermen have learned to tame and use these fish.\n\nThe arms used by mermen are:\n\ntrident, dagger* 50%\n\ncrossbow, dagger 30%\n\nnet, javelin, dagger 20%\n\n*20% of these mermen will have grapples and 50' lines also.\n\nOn occasion mermen will attack surface vessels; to do so they must surface and grapple it. They are very accurate with these hooks and are 90% likely to hit. 10 mermen will then hold the line, and the ship will be slowed 1\" for every such grappling. Meanwhile, the other mermen will fire their crossbows and darts at exposed crewmen. Grappling hooks can be thrown up to 3\". If grappling hooks are loosened or cut, the mermen pulling on the line are not able to attack during the next melee round. A motionless ship will be held by the mermen in 4-16 melee rounds. The ship will then slowly sink and eventually be looted by the victors. During such an attempt the attacking mermen are exposed to missile fire from the vessel, and if flame is used against them the mermen take double damage.\n\nMermen speak their own language and 50% also speak locathah.", -- complete Monster Manual prose, verbatim
}
