-- MIMIC
-- Source: Monster Manual, page 71+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MIMIC",
  page = 71,
  hitDice = "7-10",
  hitDiceNum = 7,
  hitDiceBonus = 0,
  avgHp = 38,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 3, max = 12 } },
  xp = 1300,
  xpPerHp = 12,
  xpValue = 1756, -- 1300 + 12/hp x 38 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "semi-_to_average",
  alignment = "neutral",
  specialAttacks = "Glue",
  specialDefenses = "Camouflage",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Mimics are subterranean creatures which cannot stand the light of the sun.\n\nThey are able to perfectly mimic stone or wood. There are two varieties of this creature, the large (9-10 dice), semi-intelligent carnivorous \"killer mimic\" and the slightly smaller, intelligent sort. While the former will attack anything which is nearby, the latter are generally friendly if offered food. All mimics move about constantly in their search of prey.\n\nMimics pose as stonework, door, chests, or any other substance or item they can imitate. When a creature touches the mimic, the latter lashes out with a pseudopod, delivering 3-12 points of damage per hit. Meanwhile, the mimic excretes a glue which holds fast whatever member the creature touched the mimic with.\n\nThe killer mimics do not speak, but the other breeds have their own language and can usually speak several other tongues such as common, orcish, etc. For consideration they will usually tell a party about what they have seen nearby.", -- complete Monster Manual prose, verbatim
}
