-- MINOTAUR
-- Source: Monster Manual, page 72+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MINOTAUR",
  page = 72,
  hitDice = "6 + 3",
  hitDiceNum = 6,
  hitDiceBonus = 3,
  avgHp = 30,
  armorClass = 6,
  numAttacks = 2,
  damage = { { min = 2, max = 8 }, { raw = "By weapon type" } },
  xp = 1800,
  xpPerHp = 12,
  xpValue = 2160, -- 1800 + 12/hp x 30 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 8 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "C" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "chaotic_evil",
  specialAttacks = "Nil",
  specialDefenses = "Surprised only on a 1",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Minotaurs are typically found only in labyrinthine places in the wilderness or underground. They are cruel, man-eaters, and although not particularly intelligent, they are cunning and have excellent senses. They are able to track prey by scent with 50% accuracy, and they will always pursue if it is in sight. They attack anything without fear, unless it is obviously beyond their ability to defeat.\n\nIn combat the minotaur can butt an opponent of 6' or more in height, or bite a shorter one, the former attack doing 2-8, the latter 1-4, points of damage. The creature also uses some form of weapon \u2014 usually a huge axe (treat as a halberd) or a flail (+2 on damage).\n\nMinotaurs have their own language and are 25% likely to speak common as well.", -- complete Monster Manual prose, verbatim
}
