-- MULE
-- Source: Monster Manual, page 73+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "MULE",
  page = 73,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = "1 or 2",
  damage = { { min = 1, max = 2 }, { min = 1, max = 6 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Mules are generally sterile hybrids between horses and donkeys. They are strong and agile, thus able to negotiate dungeons well in most cases. Mules can be very stubborn and uncooperative at times, and they are likely to bite or kick their own handler if in a contrary mood. They are not panicked by fire, but strange smells may cause them to bolt away, or begin to bray loudly. A mule can carry 2,000 gold pieces in weight at normal speed, 6,000 at one-half speed.", -- complete Monster Manual prose, verbatim
}
