-- NEO-OTYUGH
-- Source: Monster Manual, page 74+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "NEO-OTYUGH",
  page = 74,
  hitDice = "9-12",
  hitDiceNum = 9,
  hitDiceBonus = 0,
  avgHp = 47,
  armorClass = 0,
  numAttacks = 3,
  damage = { { min = 2, max = 12 }, { min = 2, max = 12 }, { min = 1, max = 3 } },
  xp = 600,
  xpPerHp = 12,
  xpValue = 1164, -- 600 + 12/hp x 47 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = "See below" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "average-very",
  alignment = "neutral",
  specialAttacks = "Disease",
  specialDefenses = "Never surprised",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Neo-otyugh are a larger, more intelligent species of otyugh (qv). They conform to the general characteristics of otyugh, and are even more aggressive in their hunting of prey. Also, the neo-otyugh are slightly better at telepathic communication. Some specimens of these creatures reach 8' diameter and a height of 3' or more. The hide of a neo-otyugh is even tougher than that of an otyugh, although the appearance is similar.", -- complete Monster Manual prose, verbatim
}
