-- NIGHTMARE
-- Source: Monster Manual, page 75+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "NIGHTMARE",
  page = 75,
  hitDice = "6 + 6",
  hitDiceNum = 6,
  hitDiceBonus = 6,
  avgHp = 33,
  armorClass = 4,
  numAttacks = 3,
  damage = { { min = 2, max = 8 }, { min = 4, max = 10 }, { min = 4, max = 10 } },
  xp = 600,
  xpPerHp = 8,
  xpValue = 864, -- 600 + 8/hp x 33 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 }, { mode = "walk", rate = 36 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "high",
  alignment = "neutral_(evil)",
  specialAttacks = "Nil",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Also known as \"demon horses\" and \"hell horses,\" nightmares are creatures from the lower planes. They are ridden primarily by the more powerful demons and devils as well as by night hags. On occasion they serve as steeds for undead such as spectres, vampires and liches.\n\nThe nightmare attacks with its great fangs as well as its burning hooves. These creatures breathe out a smoking, hot cloud during combat, and it obscures vision by blinding the eyes and choking its opponent. Unless a saving throw is made the opponent attacks at -2 \"to hit\" and damage dice.\n\nNightmares can fly, become ethereal, and roam the astral plane. They hate material life and attack viciously, even without a rider to command them.\n\nDescription: The hell horse is gaunt and skeletal with a huge head, glowing red eyes, flaming orange nostrils, and hooves which burn like embers. The coat is dead black, and the creature's mane and tail are wild and rugged.", -- complete Monster Manual prose, verbatim
}
