-- NYMPH
-- Source: Monster Manual, page 75+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "NYMPH",
  page = 75,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 9,
  numAttacks = 0,
  damage = {  },
  xp = 350,
  xpPerHp = 3,
  xpValue = 392, -- 350 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 4 },
  lairPct = 100,
  treasure = { individual = nil, inLair = "Q (x10), X" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "exceptional",
  alignment = "neutral_(good)",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "50%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These beautiful, ever-young appearing women inhabit the loveliest of wilderness places, grottos in the sea, clear lakes and streams, and crystalline caverns. They dislike any form of intrusion, and they have means to prevent it. Nymphs are able to dimension door once per day. A nymph is able to use druidical cleric spells at 7th ability level, i.e. 4 — 1st, 2 — 2nd, 2 — 3rd, and 1 — 4th level spell once per day. Looking at one will cause permanent blindness unless the onlookers save versus magic. If the nymph is nude or disrobes, an onlooker will die unless a saving throw versus magic is successful. There is a 10% chance that the nymph will be friendly if approached by a good creature without the latter first glimpsing the nymph, i.e. by calling or other prior notice. Similarly, if a nymph sees a human male with 18 charisma and good alignment before he sees her, it is 90% probable that the nymph will be favorably inclined towards the person.\n\nNymphs speak their own language and the common tongue.", -- complete Monster Manual prose, verbatim
}
