-- OCHRE JELLY
-- Source: Monster Manual, page 76+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "OCHRE JELLY",
  page = 76,
  hitDice = "6",
  hitDiceNum = 6,
  hitDiceBonus = 0,
  avgHp = 27,
  armorClass = 8,
  numAttacks = 1,
  damage = { { min = 3, max = 12 } },
  xp = 150,
  xpPerHp = 6,
  xpValue = 312, -- 150 + 6/hp x 27 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 3 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Ochre jelly are a form of giant amoeba. They seep about in dungeons, hunting for any form of flesh or cellulose to devour \u2014 they far prefer the former. Their amorphous form allows them to flow through small spaces. They can travel along walls or ceilings with ease. The fluids excreted by these creatures dissolve flesh (3-12 hit points per round of exposure).\n\nStriking the ochre jelly with lightning bolts simply divides the creature into one or more smaller creatures, each doing one-half normal damage. Cold and attacks have normal effect.", -- complete Monster Manual prose, verbatim
}
