-- PEGASUS
-- Source: Monster Manual, page 79+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PEGASUS",
  page = 79,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 1, max = 8 }, { min = 1, max = 8 }, { min = 1, max = 3 } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 132, -- 60 + 4/hp x 18 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 10 },
  lairPct = 15,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 24, modes = { { mode = "walk", rate = 24 }, { mode = "walk", rate = 48 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "average",
  alignment = "chaotic_good",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Pegasi are found in remote places, for they are typically very shy and wild. These intelligent winged horses make the swiftest of steeds, and they are often sought for that reason. Pegasi will serve only good characters, but if they do so, they always serve unto death.\n\nA pegasus fights with its two forehooves and its powerful teeth. A male specimen can carry weight equal to a medium warhorse (qv), a female equal to a light warhorse.\n\nIf encountered in their lair there will be 1 nest for every pair of pegasi. There is a 20% chance per nest that there will be 1-2 eggs (30%) or young animals (70%) of 20% to 50% maturity. The eggs are worth 3,000 gold pieces, the young 5,000, on the open market.", -- complete Monster Manual prose, verbatim
}
