-- PERYTON
-- Source: Monster Manual, page 79+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PERYTON",
  page = 79,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 4, max = 16 } },
  xp = 150,
  xpPerHp = 4,
  xpValue = 222, -- 150 + 4/hp x 18 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 2, max = 8 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "B" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 21 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "average",
  alignment = "chaotic_evil",
  specialAttacks = "+2 to hit",
  specialDefenses = "+1 or better weapon to hit",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Perytons dwell in rocky hills or mountainous regions. They are omnivorous creatures of the weirdest appearance, likely the result of the same type of experimentation as brought about the awlbear.\n\nThe creature attacks with its sharp horns, having a +2 on \"to hit\" dice. Its claws are too weak to use. Each peryon attacks but a single creature, and when it is dead the peryon tears out the victim's heart with its teeth. The organ is necessary to the peryon to reproduce, and the creature immediately flies away in order to do so. Human hearts are the type most sought by perytons.\n\nNormal weapons do not harm these creatures.\n\nPerytons lair in caves high upon cliffs or in mountain peaks. They will sometimes take humans and similar creatures alive in order to hold them prisoner until needed as food and for reproduction needs.\n\nPerytons speak their own language.\n\nDescription: The upper body and head of the peryon is blue-black, the creature's horns being jet black. The wing and back feathers are dark green, and the chest of the male peryon is light blue to medium blue, the females being drab.", -- complete Monster Manual prose, verbatim
}
