-- PIERCER
-- Source: Monster Manual, page 79+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PIERCER",
  page = 79,
  hitDice = "1-4",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 11,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 1, max = 6 } },
  xp = 10,
  xpPerHp = 1,
  xpValue = 21, -- 10 + 1/hp x 11 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 3, max = 18 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 } } },
  size = "S",
  sizeDetail = "to M",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "95% likely to surprise",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Piercers inhabit caves, caverns, and similar subterranean places. With their stoney outer casing these monsters are indistinguishable from stalactites found on cave roofs. They are attracted by noise and heat, and when a living creature passes beneath their position above they will drop upon it in order to kill and devour it. Larger varieties will be found with smaller ones.\n\nThe size of a piercer is equal to its hit dice, and there is an equal probability of a piercer being 1, 2, 3, or 4 dice in size. The largest piercer is about 6' long, 1' base diameter, and weighs 500 pounds.", -- complete Monster Manual prose, verbatim
}
