-- PIKE, Giant
-- Source: Monster Manual, page 79+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PIKE, Giant",
  page = 79,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 4, max = 16 } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 132, -- 60 + 4/hp x 18 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 36, modes = { { mode = "walk", rate = 36 } } },
  size = "L",
  sizeDetail = "9'-14' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Surprise on a 1-4",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant pike inhabit large, deep lakes. They are aggressive predators and will not hesitate to attack any creature which is nearby when they are hungry. These creatures see well, and they move with great speed, surprising prey two-thirds of the time. Giant pike are often tamed by nixies.", -- complete Monster Manual prose, verbatim
}
