-- Pit Fiend (Greater devil)
-- Source: Monster Manual, page 24+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Pit Fiend (Greater devil)",
  page = 24,
  hitDice = "13",
  hitDiceNum = 13,
  hitDiceBonus = 0,
  avgHp = 58,
  armorClass = -3,
  numAttacks = 2,
  damage = { { min = 5, max = 8 }, { min = 7, max = 12 } },
  xp = 7900,
  xpPerHp = 18,
  xpValue = 8944, -- 7900 + 18/hp x 58 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 65,
  treasure = { individual = nil, inLair = "J, R" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "12' tall",
  intelligence = "exceptional",
  alignment = "lawful_evil",
  specialAttacks = "See below",
  specialDefenses = "+2 or better weapon to hit",
  magicResistance = "65%",
  psionic = "213",
  attackDefenseModes = "A, C, E/G, H, I",
  text = "The lowest plane of Hell is the home of the dreaded pit fiend, a devil of great power. They possess a terrible strength and the most evil nature. All pit fiends have personal names. They are the personal servants of Asmodeus. Each typically carries an ancus-like weapon and a jagged-toothed club, and all can strike with both in a melee round.\n\nPit fiends are able to perform any of the following at will, once per turn or melee round, as applicable: pyrotechnics, produce flame, wall of fire, detect magic, detect invisible, polymorph self, hold person, or gate in 1-3 barbed devils (60%) or another pit fiend (70% chance of success). Once per day a pit fiend can use a symbol of pain — (save versus magic or suffer -4 on attack dice rolls to hit and a -2 on dexterity for 2-20 melee rounds). They shed fear in a 20' radius (save versus magic is applicable).\n\nAll pit fiends have a strength of 18/00. They regenerate at 2 hit points per melee round. If they strike with their tail and score a hit the opponent is held with 2-8 hit points of constriction damage per turn.", -- complete Monster Manual prose, verbatim
}
