-- PIXIE
-- Source: Monster Manual, page 80+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PIXIE",
  page = 80,
  hitDice = "1-4 hp",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 2,
  armorClass = 5,
  numAttacks = 1,
  damage = { { raw = "By weapon type" } },
  xp = 105,
  xpPerHp = 1,
  xpValue = 107, -- 105 + 1/hp x 2 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 5, max = 20 },
  lairPct = 5,
  treasure = { individual = nil, inLair = "R, S, T, X" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 12 } } },
  size = "S",
  sizeDetail = "2½' tall",
  intelligence = "exceptional",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "25%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Pixies dwell only in the most idyllic of woodlands. They are naturally invisible and are thus almost never noted even though some creature passes near their secluded home.\n\nPixies normally carry slim swords and fine bows similar to those of sprites (qv). Their swords are equal to daggers, but their arrows are more effective and are of three types. All have +4 chance to hit. The pixie war arrow inflicts 2-5 hit points of damage. Their second type causes sleep in a comatose state for 1-6 hours to any creature which fails to save versus magic when struck. The third sort which the pixies use causes no harm physically, but being struck causes a complete loss of memory which can only be restored by clerical exorcism unless the victim saves versus magic.\n\nPixies can become visible at will, polymorph themselves at will, create illusions with both audial and visual components which last without concentration until magically dispelled once per day each, and know alignment. Pixies can, by touch, cause confusion in any creature which fails its saving throw versus magic. Confusion is permanent unless a remove curse spell is applied. Once per day pixies are able to use dispel magic (at 8th level/ability), dancing lights, ESP, and 1 in 10 can use Otto's Irresistible Dance spells.\n\nBecause pixies are normally invisible, they gain the advantage of subtracting 4 from \"to hit\" dice rolls of all opponents unable to detect invisible objects. Similarly, pixies can attack while invisible.\n\nPixies are highly mischievous, and they will be prone to bother, harass, or fool creatures. They speak their own tongue, that of sprites, and common speech.", -- complete Monster Manual prose, verbatim
}
