-- PORCUPINE, Giant
-- Source: Monster Manual, page 80+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PORCUPINE, Giant",
  page = 80,
  hitDice = "6",
  hitDiceNum = 6,
  hitDiceBonus = 0,
  avgHp = 27,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 150,
  xpPerHp = 6,
  xpValue = 312, -- 150 + 6/hp x 27 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 2 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Shoot quills",
  specialDefenses = "Quills",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant porcupines are found primarily in wooded areas. They are stupid and non-aggressive, but if threatened they are able to defend themselves with ease. The giant porcupine can bite with some effect, but they will do this only in the most desperate defense (10% chance per melee round the creature is above 50% damaged). The main defense of the giant porcupine is its ability to shoot 1-8 quills from its tail, each quill doing 1-4 hit points of damage and having a range of 30'. As its quills are up to 3' long, any attack which comes within 6' of the creature will likewise suffer 1-4 quills in return from the porcupine's defensive movements. There is no practical limit to the number of quills the creature can use, as there are over 80 in its tail and over 300 on\n\nits body. The porcupine views any approach within 30' as a threat.", -- complete Monster Manual prose, verbatim
}
