-- PORTUGUESE MAN-O-WAR, Giant
-- Source: Monster Manual, page 80+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PORTUGUESE MAN-O-WAR, Giant",
  page = 80,
  hitDice = "1-4",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 11,
  armorClass = 9,
  numAttacks = 1,
  damage = { { min = 1, max = 10 } },
  xp = 10,
  xpPerHp = 1,
  xpValue = 21, -- 10 + 1/hp x 11 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 10 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 } } },
  size = "S",
  sizeDetail = "to L",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Paralyzation",
  specialDefenses = "Transparent",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Portuguese men-o-war float in warm sea waters, trailing their deadly tentacles below. Any creature which touches these appendages takes damage from their poison, and if a saving throw versus paralyzation is not made the victim is paralyzed and will be drawn up by the Portuguese man-o-war's tentacles and devoured in 3-12 turns.\n\nEach of these creatures has 10-40 tentacles. Their length is a factor of size. For each die the creature has, the tentacles have 10' of length. A one hit die Portuguese man-o-war is 2\u00bd' in diameter and has 10 tentacles which are each 10' long. A two hit dice creature has 20 tentacles of 20' length, a three hit dice creature has 30 tentacles of 30' length and a four hit dice Portuguese man-o-war is 10' in diameter and has 40 tentacles which trail downwards 40'. Each tentacle requires but a single hit point to sever, but this does not inflict damage on the creature, and tentacles will regenerate in several days. Only hits scored on the body of the creature kill it.\n\nPortuguese men-o-war are transparent. It is 90% probable that they will be undetected unless the creature encountering them is able to detect invisible objects.", -- complete Monster Manual prose, verbatim
}
