-- PSEUDO-DRAGON
-- Source: Monster Manual, page 80+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PSEUDO-DRAGON",
  page = 80,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 2,
  numAttacks = 1,
  damage = { { min = 1, max = 3 } },
  xp = 200,
  xpPerHp = 2,
  xpValue = 218, -- 200 + 2/hp x 9 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 5,
  treasure = { individual = nil, inLair = "Q (x10)" },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 24 } } },
  size = "S",
  sizeDetail = "1\u00bd' long",
  intelligence = "average",
  alignment = "neutral_(good)",
  specialAttacks = "Poison sting",
  specialDefenses = "Chameleon power",
  magicResistance = "35%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Pseudo-dragons are found in any clime, save the coldest or hottest, when they are found at all. These creatures are rare indeed and highly sought after. They lair in great hollow trees or small caves.\n\nThe pseudo dragon can deliver a vicious bite with its small, dragon-like jaws, but its major weapon is its sting-equipped tail. This appendage is long and very flexible. The creature can move it with flashing speed, and strikes at +4 to its \"to hit\" dice. Any creature struck must save versus poison or go into a state of catalepsy which lasts for 1-6 days. During this time the victim appears dead and there is a 25% chance the creature will actually die.\n\nPseudo-dragons have a chameleon-like power, so that they can blend with any typical background and become 80% undetectable to creatures not able to see invisible objects. They can see invisible objects.\n\nMagic resistance is an innate characteristic of pseudo-dragons, and they are able to transmit this resistance to a human (or humanoid) companion when the pseudo-dragon is touching the other creature.\n\nA pseudo-dragon communicates by means of a limited form of telepathy. If the pseudo-dragon elects to become a companion of a human (or humanoid), it can also transmit what it sees and hears to its companion up to a distance of 24'.\n\nDescription: Pseudo-dragons appear exactly as miniature red dragons. However, their coloration is a basic red brown, and can be changed as noted.", -- complete Monster Manual prose, verbatim
}
