-- PURPLE WORM
-- Source: Monster Manual, page 81+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "PURPLE WORM",
  page = 81,
  hitDice = "15",
  hitDiceNum = 15,
  hitDiceBonus = 0,
  avgHp = 68,
  armorClass = 6,
  numAttacks = "1 and 1",
  damage = { { min = 2, max = 24 }, { min = 2, max = 8 } },
  xp = 4900,
  xpPerHp = 20,
  xpValue = 6260, -- 4900 + 20/hp x 68 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 2 },
  lairPct = 30,
  treasure = { individual = nil, inLair = "B, Q (x5), X" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "L",
  sizeDetail = "50' long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Purple worms burrow deep beneath the ground in a constant search for food. They sense vibrations at 60' and move to attack. Generally only adult specimens, 8'-9' in diameter and 40'-50' long, are encountered. Young are 1' in diameter and about 5' when they hatch, a typical hatching being 10-20, each with 1 hit die +4 hit points. They return to their lairs to rest, and there they expel such indigestible waste as metal and mineral crystals.\n\nA purple worm attacks by biting (2-24 points of damage), and any hit 20% over the required score (that is 4 or more over the required number) or a 100% (die roll of 20) score in any case indicates the creature has engulfed its victim. A mature purple worm can swallow, whole, a creature as large as 8' or so tall and up to 6' wide, or vice versa. Any creature swallowed will be dead in 6 melee rounds. The worm will digest its meal in 12 turns, and at that time the creature is totally gone and cannot be raised from the dead. Note, however, that a creature swallowed can try to cut its way out of the purple worm's stomach. The inner armor class of the 'worm is 9, but each round the creature is in the worm it subtracts 1 from the damage each of its attacks does. This subtraction is cumulative, so on the second melee round there is a -2, on the third a -3, etc.\n\nAdditionally, the purple worm has a poisonous stinger in its tail. This weapon is only used in rear defense, however, or if the 'worm is fighting large or numerous opponents in a very spacious area which will allow it freedom to use its stinger. The sting causes 2-8 hit points of damage when it hits, and if the victim fails its poison saving throw it is killed by the purple worm's poison.\n\n**Mottled Worm:** The mottled worm is an aquatic variety of the purple worm. It inhabits shallow bottom muck but will surface for prey. It otherwise conforms to the characteristics of the purple variety.", -- complete Monster Manual prose, verbatim
}
