-- RAM, Giant
-- Source: Monster Manual, page 82+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "RAM, Giant",
  page = 82,
  hitDice = "4",
  hitDiceNum = 4,
  hitDiceBonus = 0,
  avgHp = 18,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 12 } },
  xp = 60,
  xpPerHp = 4,
  xpValue = 132, -- 60 + 4/hp x 18 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 2, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "6' at shoulder",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Charge",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant sheep are found only in hilly or mountainous regions. All full-grown specimens, male or female, will conform to the above statistics. Males (giant rams), however, will charge to attack, delivering a butt of double the damage parameters shown. These animals are not normally aggressive, but if they believe the flock is threatened they will defend it to the death.\n\nA flock will consist of a ram, four ewes, and the balance will be lambs (roll percentile dice to determine size, halving the number rolled and adding it to 50%).", -- complete Monster Manual prose, verbatim
}
