-- RHINOCEROS (Rhinoceros)
-- Source: Monster Manual, page 83+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "RHINOCEROS (Rhinoceros)",
  page = 83,
  hitDice = "8-9",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 38,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 900,
  xpPerHp = 12,
  xpValue = 1356, -- 900 + 12/hp x 38 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 1, max = 6 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Charge",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Rhinoceroses are aggressive herbivores, by and large. A few types are less aggressive and will run away if they feel threatened, but most will charge. They have poor eyesight but keen senses of hearing and smell. If more than one-half the possible number are encountered, 1 or 2 will be young (from 30% to 60% mature).\n\nSingle horned rhinoceroses do 2-8 hit points of damage and have 8 hit dice. Two-horned rhinos have 9 hit dice and do more damage when they hit (2-12 points). A charging rhino does double damage. They will trample any opponent which is low enough for this action. Trampling inflicts 2-8 hit points of damage for each forefoot which hits.\n\nWoolly Rhinoceros: A large, very aggressive species of rhinoceros which roams the cold temperate and subarctic regions of the Pleistocene epoch, the woolly rhino conforms to the characteristics of its modern relatives.\n\nAttack/Defense Modes: Nil\n\nRocs are huge birds somewhat resembling eagles. They inhabit the highest mountains in warm regions. They prey upon large creatures such as cattle, horses, and elephants. The roc swoops down upon prey, seizes it in its powerful talons, and carries it off to its lair. If the creature resists, the roc will strike it with its beak, inflicting 4-24 points of damage per hit.\n\nThe lair of a roc will be a vast nest of trees, branches, and the like. There its treasure will be strewn about, for the creature does not value such . . . it is the residue of its victims.\n\nRocs are occasionally tamed and used by giants.\n\n[Shared family description from RHINOCEROS (Woolly Rhinoceros)]", -- complete Monster Manual prose, verbatim
}
