-- ROPER
-- Source: Monster Manual, page 84+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "ROPER",
  page = 84,
  hitDice = "10-12",
  hitDiceNum = 10,
  hitDiceBonus = 0,
  avgHp = 50,
  armorClass = 0,
  numAttacks = 1,
  damage = { { min = 5, max = 20 } },
  xp = 900,
  xpPerHp = 14,
  xpValue = 1600, -- 900 + 14/hp x 50 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 3 },
  lairPct = 90,
  treasure = { individual = nil, inLair = "See below" },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "exceptional",
  alignment = "chaotic_evil",
  specialAttacks = "6 poisonous strands",
  specialDefenses = "See below",
  magicResistance = "80%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Ropers inhabit subterranean caverns. They prey upon all forms of creatures, but humans are their favorite form of food. These monsters can stand upright in order to resemble a pillar or stalagmite or flatten themselves at full length upon the floor so as to look like nothing more than a hump. The roper has a gizzard-like organ which holds 3-18 platinum pieces and can contain 5-20 gems (35% chance).\n\nThe roper has six strands of strong, sticky rope-like excretion which it can shoot from 2\"-5\". A hit causes weakness (50% from strength in 1-3 melee rounds), and the roper then draws its prey into its toothy maw where it is quickly devoured. The chance for breaking a strand is the same for opening a door, but every round the roper will drag the victim 10' closer. They are unaffected by lightning, take half damage at most from cold, but are very susceptible to fire (-4 on saving throw).\n\nDescription: This yellowish gray monster appears to be a mass of foul, festering corruption. The roper is cigar-shaped, about 9' long, with a diameter of some 3'.", -- complete Monster Manual prose, verbatim
}
