-- ROT GRUB
-- Source: Monster Manual, page 84+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "ROT GRUB",
  page = 84,
  hitDice = "1 hit point",
  hitDiceNum = 0,
  hitDiceBonus = 0,
  avgHp = 0,
  armorClass = 9,
  numAttacks = 0,
  damage = {  },
  xp = 5,
  xpPerHp = 1,
  xpValue = 5, -- 5 + 1/hp x 0 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 5, max = 20 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 } } },
  size = nil,
  sizeDetail = "5",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Rot grubs are occasionally found in heaps of offal or dung. They are rarely found in ceilings, walls, or floors. These small creatures will viciously burrow into any living flesh which touches them, for they greatly enjoy such fare to dine upon. The victim must immediately apply flame to the wound (1-6 hit points damage per application) or have a cure disease spell cast upon him. Otherwise, the rot grubs will burrow to the heart and kill their host in 1-3 turns.", -- complete Monster Manual prose, verbatim
}
