-- SALAMANDER
-- Source: Monster Manual, page 86+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SALAMANDER",
  page = 86,
  hitDice = "7 + 7",
  hitDiceNum = 7,
  hitDiceBonus = 7,
  avgHp = 39,
  armorClass = { 5, 3 },
  numAttacks = 2,
  damage = { { raw = "By weapon type" }, { min = 2, max = 12 } },
  xp = 825,
  xpPerHp = 10,
  xpValue = 1215, -- 825 + 10/hp x 39 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 2, max = 5 },
  lairPct = 75,
  treasure = { individual = nil, inLair = "F" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "high",
  alignment = "chaotic_evil",
  specialAttacks = "Heat",
  specialDefenses = "+1 or better weapon to hit",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Salamanders are creatures of the elemental plane of fire. They come to the material plane occasionally for purposes known only to them. Salamanders hate cold, preferring temperatures of 300 degrees upwards, and they can abide lower temperatures only for a few hours. Their lair is typically at least 500 degrees temperature, and such treasure as is found there will be the sort to survive such heat.\n\nThe human-like upper body of a salamander has an armor class of 5, while the lower body is armor class 3.\n\nA salamander typically attacks with a metal spear which inflicts damage of 1-6 hit points plus a like amount for its heat. At the same time it can lash out and coil around an opponent with its snake-like tail, constricting for 2-12 hit points damage plus causing an additional 1-6 points of damage from the heat of its body. While fire resistant creatures will not suffer heat damage, they will be subject to normal attack damage.\n\nSalamanders can be affected only by magical weaponry or by creatures of a magical nature or with great strength. They are impervious to all fire-based attacks. Sleep, charm, and hold spells are ineffective against them. Cold based attacks cause an additional 1 point of damage per die of attack value.\n\nDescription: The head and torso of a salamander is copper-colored, with yellow, glowing eyes. The lower body is an orange shading to dull red at the tail end.", -- complete Monster Manual prose, verbatim
}
