-- SATYR
-- Source: Monster Manual, page 86+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SATYR",
  page = 86,
  hitDice = "5",
  hitDiceNum = 5,
  hitDiceBonus = 0,
  avgHp = 22,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 280,
  xpPerHp = 5,
  xpValue = 390, -- 280 + 5/hp x 22 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 8 },
  lairPct = 40,
  treasure = { individual = nil, inLair = "I, S, X" },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "50%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Satyrs (or fauns) inhabit only sylvan woodlands. They are interested primarily only in sport — frolicking, piping, chasing wood nymphs, etc. They resent intrusion, however, and will drive away any creature which offends them. They can sometimes be lured/tribed with superior wine.\n\nA satyr normally attacks by butting with its two sharp horns. They will occasionally (20%) make use of magical weapons. It is quite likely that a satyr will first play a tune on his pipes, an instrument only a satyr can properly employ. By means of these pipes the satyr can charm, sleep, or cause fear in all within a 6\" hearing radius unless they save versus magic.\n\nOnly 1 satyr per band is likely to have pipes. If comely females are in the group the piping will be to charm, if the intruder is relatively inoffensive the piping will be to sleep (and choice items will be stolen from the sleeper), but if the party is powerful the piping will be to cause fear. Any creature which saves versus any form of piping is not affected by additional music from the same pipes.\n\nSatyrs are very silent and have keen senses. They are surprised only on a 1, and they can blend with foliage so as to be 90% undetectable to creatures not able to see hidden or invisible things.\n\nThese creatures have their own tongue and are also able to speak elvish (understandable only to sylvan elves) and the common speech. Satyrs dwelling near centaurs are 80% likely to be friendly with the latter, cooperating with them and speaking their language.\n\nDescription: The skin of the upper body of a satyr is tan to light brown, its hair elsewhere being medium brown, reddish brown, or dark brown. Horns and hooves are black.", -- complete Monster Manual prose, verbatim
}
