-- SCORPION, Giant
-- Source: Monster Manual, page 86+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SCORPION, Giant",
  page = 86,
  hitDice = "5 + 5",
  hitDiceNum = 5,
  hitDiceBonus = 5,
  avgHp = 27,
  armorClass = 3,
  numAttacks = 3,
  damage = { { min = 1, max = 10 }, { min = 1, max = 10 }, { min = 1, max = 4 } },
  xp = 225,
  xpPerHp = 8,
  xpValue = 441, -- 225 + 8/hp x 27 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 4 },
  lairPct = 50,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Poison sting",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant scorpions are vicious predators which are likely to be found even in relatively cold places such as dungeons due to the adaptability of these mutations. They are likely to attack any creature which approaches. The monster seeks to grab prey with its huge pincers while its segmented tail lashes forward to sting its victim to death with poison. This latter attack inflicts 1-4 points of damage per hit and, if a poison saving throw fails, the victim dies immediately.\n\nThe giant scorpion can fight up to 3 opponents at once. Note that the scorpion's poison kills it if it accidentally stings itself. Creatures killed are dragged to the scorpion's lair to be eaten.", -- complete Monster Manual prose, verbatim
}
