-- SEA LION
-- Source: Monster Manual, page 87+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SEA LION",
  page = 87,
  hitDice = "6",
  hitDiceNum = 6,
  hitDiceBonus = 0,
  avgHp = 27,
  armorClass = { 5, 3 },
  numAttacks = 3,
  damage = { { min = 1, max = 6 }, { min = 1, max = 6 }, { min = 2, max = 12 } },
  xp = 150,
  xpPerHp = 6,
  xpValue = 312, -- 150 + 6/hp x 27 avg hp
  xpSource = "appendixE",
  frequency = "*uncommon*",
  noAppearing = { min = 3, max = 12 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "B" },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "*semi-*",
  alignment = "*neutral*",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "*Standard*",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Sea lions are fearsome carnivores which inhabit coastal marine waters. They hunt in packs and emit loud bellowing roars even underwater. Their maned heads are armor class 5, but their thick scales make the remainder of their body armor class 3. As they often drag prey to their lair, there is sometimes a residue of valuable items there. They attack with their clawed forelimbs and their jaws. Young sea lions can be tamed and trained for use in guarding and hunting.", -- complete Monster Manual prose, verbatim
}
