-- SEA HORSE, Giant
-- Source: Monster Manual, page 87+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SEA HORSE, Giant",
  page = 87,
  hitDice = "2-4",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 4 }, { min = 2, max = 5 }, { min = 2, max = 8 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 48, -- 20 + 2/hp x 14 avg hp
  xpSource = "formula",
  frequency = "*common*",
  noAppearing = { min = 1, max = 20 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 21, modes = { { mode = "walk", rate = 21 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "*semi-*",
  alignment = "*neutral*",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "*Standard*",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant sea horses are herbivorous marine creatures found in all but the coldest of waters. They are naturally shy and avoid contact. They can, however, be trained to serve as steeds. In combat, the sea horse delivers a butt with its head. Size varies, the most common sort of sea horse being 2 hit dice; 30% are 3, and 10% are 4 hit dice in size. Occasionally aquatic elves and locathah will capture and train sea horses.", -- complete Monster Manual prose, verbatim
}
