-- SHADOW
-- Source: Monster Manual, page 87+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SHADOW",
  page = 87,
  hitDice = "3 + 3",
  hitDiceNum = 3,
  hitDiceBonus = 3,
  avgHp = 17,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 2, max = 5 } },
  xp = 255,
  xpPerHp = 4,
  xpValue = 323, -- 255 + 4/hp x 17 avg hp
  xpSource = "appendixE",
  frequency = "*rare*",
  noAppearing = { min = 2, max = 20 },
  lairPct = 40,
  treasure = { individual = nil, inLair = "F" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "*low*",
  alignment = "*chaotic_evil*",
  specialAttacks = "*Strength drain*",
  specialDefenses = "+1 or better weapon to hit",
  magicResistance = "*See below*",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These horrible undead creatures are found amidst ancient ruins or deep beneath the ground. As they exist primarily on the negative material plane they drain strength by merely touching an opponent. They attack living things without hesitation in order to gain the life force of their prey. In addition to the 2-5 hit points of damage their chill touch causes, each hit also saps 1 point of the victim's strength. If a human opponent reaches 0 strength or hit points, the shadow drains his life force and he becomes a shadow. Note that strength returns to a creature 2-8 turns after being touched. Shadows are not affected by sleep, charm or hold spells. They are not subject to cold-based attacks. Shadows are 90% undetectable, as they appear to be nothing more than their name. If bright light is cast — such as from a *continual light* spell — they can be clearly seen.", -- complete Monster Manual prose, verbatim
}
