-- SHARK (Shark)
-- Source: Monster Manual, page 88+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SHARK (Shark)",
  page = 88,
  hitDice = "3-8",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 25,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 5 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 110, -- 35 + 3/hp x 25 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 3, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 24, modes = { { mode = "walk", rate = 24 } } },
  size = nil,
  sizeDetail = "Nil",
  intelligence = "non-neutral",
  alignment = "m_to_l",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Sharks of all sorts roam the oceans and seas, constantly in motion and seeking food to satisfy their voracious appetites. The shark is a killing machine, attacking any recognizable food source at any time. Sharks are attracted by noise (pressure changes) from a mile or more, and they can smell blood from at least the same distance. Any creature which appears hurt is 90% likely to be attacked. A wounded creature will always be attacked, and this will cause all sharks nearby to go into a frenzy where they will attack any thing that remotely resembles food. They seize prey, tearing off a mouthful if it is not bite-sized, and swim away to swallow it, only to return again for more. Sharks are particularly vulnerable to ramming attacks, such as dolphins deliver, for they rupture internal organs which allow the creatures to swim. Similarly, a motionless shark dies in 2-5 melee rounds.\n\nGiant Shark (Megalodon): Giant white sharks and prehistoric species of sharks range in size from 20' to 50', the largest being the prehistoric sharks.\n\nThe only difference between these monsters and their smaller kin is the former's ability to swallow large objects whole — commensurate with the other factors which large size gives them. A creature swallowed whole has 6 melee rounds to free itself by attack. If it cuts its way out (reduces the shark to 0 hit points) within this time it will not be dead Each attack from inside is at a cumulative -1 per round with regard to damage; thus attacks on the 1st round cause damage -1, those on the 2nd cause damage -2, etc.\n\n[Shared family description from SHARK (Giant Shark (Megalodon))]", -- complete Monster Manual prose, verbatim
}
