-- SHEDU
-- Source: Monster Manual, page 88+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SHEDU",
  page = 88,
  hitDice = "9 + 9",
  hitDiceNum = 9,
  hitDiceBonus = 9,
  avgHp = 49,
  armorClass = 4,
  numAttacks = 2,
  damage = { { min = 1, max = 6 }, { min = 1, max = 6 } },
  xp = 1950,
  xpPerHp = 14,
  xpValue = 2636, -- 1950 + 14/hp x 49 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 2, max = 8 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "G" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "exceptional",
  alignment = "lawful_good",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "25%",
  psionic = "70-100",
  attackDefenseModes = "All/all",
  text = "Shedu travel about the world seeking to further the ends of lawful good, helping allied creatures when in need. Although shedu can attack with their powerful front hooves, they are more likely to use their psionic abilities 3 major and 5 minor disciplines. All such abilities are performed at 9th level of mastery. Shedu can become ethereal at will, and they frequently travel the astral and ethereal planes. Shedu have their own language and know most human tongues; as they have a limited form of telepathy, shedu generally communicate by direct mind contact.", -- complete Monster Manual prose, verbatim
}
