-- SKELETON
-- Source: Monster Manual, page 88+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SKELETON",
  page = 88,
  hitDice = "1",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 4,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 6 } },
  xp = 14,
  xpPerHp = 1,
  xpValue = 18, -- 14 + 1/hp x 4 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 3, max = 30 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Skeletons are magically animated, undead monsters. They are enchanted by a powerful magic-user or cleric of evil alignment. The skeletons perform according to the command of their animator — the command being limited in scope to but a dozen or two words. They are found only in burial places or dungeons and similar forsaken places.\n\nThe skeleton strikes with some form of weapon, but regardless of the weapon type the damage caused by a hit will be 1-6 hit points.\n\nSkeletons suffer only one-half damage from sharp and/or edged weapons (such as spears, daggers, swords). Blunt weapons such as clubs, maces, flails, etc. score normal damage. Fire scores normal damage. Sleep, charm, hold and cold-based spells do not affect skeletons. Holy water causes 2-8 hit points of damage on a skeleton for each vial which strikes it. Skeletons attack until destroyed.", -- complete Monster Manual prose, verbatim
}
