-- SKUNK, Giant
-- Source: Monster Manual, page 89+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SKUNK, Giant",
  page = 89,
  hitDice = "5",
  hitDiceNum = 5,
  hitDiceBonus = 0,
  avgHp = 22,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 1, max = 6 } },
  xp = 90,
  xpPerHp = 5,
  xpValue = 200, -- 90 + 5/hp x 22 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Squirt musk",
  specialDefenses = "Squirt musk",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant skunks are forest dwelling omnivores not adverse to raiding human camps for a bit of food. They will react to any serious threat by backing towards an opponent and if the other creature does not quickly get beyond 6\", the skunk will loose a spray of vile musk quickly in a cloud 2\" wide by 2\" high by 6\" long. If the opponent fails to save versus poison it will be blinded for 1-8 hours, and in any event the musk will cause the creature to retreat a full move and lose 50% of both strength and dexterity due to nausea for 2-8 turns. Furthermore, any creature touched by the skunk's musk will have a disgusting stench. Other creatures will shun it. All cloth material will rot and become useless, including magical garb which fails its saving throw. Creatures and non-cloth garments and equipment must be washed and aired for several days to be completely free of the stench.", -- complete Monster Manual prose, verbatim
}
