-- SLITHERING TRACKER
-- Source: Monster Manual, page 89+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SLITHERING TRACKER",
  page = 89,
  hitDice = "5",
  hitDiceNum = 5,
  hitDiceBonus = 0,
  avgHp = 22,
  armorClass = 5,
  numAttacks = 0,
  damage = {  },
  xp = 280,
  xpPerHp = 5,
  xpValue = 390, -- 280 + 5/hp x 22 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "C" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "S",
  sizeDetail = "2\u00bd' long",
  intelligence = "average",
  alignment = "neutral",
  specialAttacks = "Paralyzation",
  specialDefenses = "Transparency",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "This monster is transparent and almost impossible to discover (5% chance of spotting). It inhabits dungeons and other dark places, and does not normally attack its prey immediately (10% chance of immediate attack). The tracker usually follows the chosen victim to the place where the victim sleeps, and only when its prey is asleep will it strike. Because of its semi-fluid body, the slithering tracker can flow through openings as small as a rat hole or a large crack under a door. Attack is by contact with the exposed flesh of its prey, and the secretions of the monster will paralyze the victim unless a saving throw versus paralyzation is made. Once the victim is immobilized the 'tracker will draw all the plasma from the body of its prey in 6 turns.", -- complete Monster Manual prose, verbatim
}
