-- SNAKE, Giant (Poisonous)
-- Source: Monster Manual, page 89+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SNAKE, Giant (Poisonous)",
  page = 89,
  hitDice = "4 + 2",
  hitDiceNum = 4,
  hitDiceBonus = 2,
  avgHp = 20,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 1, max = 3 } },
  xp = 90,
  xpPerHp = 5,
  xpValue = 190, -- 90 + 5/hp x 20 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 6 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Poison",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant snakes are likely to be found in any clime save the coldest. All are carnivorous.\n\nAmphisbaena: These monsters have heads at both ends, and both heads are armed with poisonous fangs. The creature travels by grasping one of its necks and rolling like a hoop. It is able to attack with both heads, and victims failing to save versus poison when bitten die instantly. Cold-based attacks do not harm the amphisbaena.\n\nConstrictor: These snakes usually drop coils from above, grab prey within their coils, deliver a bite, and then constrict causing 2-8 points of damage per melee round. If several strong creatures (such as 4 humans of 16 or greater strength) can grasp the creature at head and tail ends, they can uncoil it in 2-5 melee rounds. After eating, the snake sleeps for a period of several days.\n\nPoisonous: Giant poisonous snakes need no lengthy explanation or description. Some varieties, however, are worth noting, as their poison is so strong that even if a saving throw is made the victim takes up to 3-18 hit points damage.\n\nSea: Found only in tropical waters, these marine creatures attack only when hungry (20% chance). They otherwise ignore other creatures unless molested. Sea snakes have a poisonous bite. The largest are able to coil about small vessels and crush them at a rate of 10% of total value per melee round of constriction.\n\nSpitting: The spitting giant snake is a variety of the poisonous type which can emit a poisonous spittle, spraying it up to 3\" at any single creature. The victim must save versus poison. Naturally, the bite of these snakes is likewise poisonous. Giant spitting cobras are a typical example of the monster.\n\n[Shared family description from SNAKE, Giant (Spitting)]\n\n[Shared family description from SNAKE, Giant (Amphisbaenc)]", -- complete Monster Manual prose, verbatim
}
