-- SNAKE, Giant (Sea)
-- Source: Monster Manual, page 89+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SNAKE, Giant (Sea)",
  page = 89,
  hitDice = "8-10",
  hitDiceNum = 8,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = 5,
  numAttacks = 2,
  damage = { { min = 1, max = 6 }, { min = 3, max = 18 } },
  xp = 375,
  xpPerHp = 10,
  xpValue = 775, -- 375 + 10/hp x 40 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Constriction",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant snakes are likely to be found in any clime save the coldest. All are carnivorous.\n\nAmphisbaena: These monsters have heads at both ends, and both heads are armed with poisonous fangs. The creature travels by grasping one of its necks and rolling like a hoop. It is able to attack with both heads, and victims failing to save versus poison when bitten die instantly. Cold-based attacks do not harm the amphisbaena.\n\nConstrictor: These snakes usually drop coils from above, grab prey within their coils, deliver a bite, and then constrict causing 2-8 points of damage per melee round. If several strong creatures (such as 4 humans of 16 or greater strength) can grasp the creature at head and tail ends, they can uncoil it in 2-5 melee rounds. After eating, the snake sleeps for a period of several days.\n\nPoisonous: Giant poisonous snakes need no lengthy explanation or description. Some varieties, however, are worth noting, as their poison is so strong that even if a saving throw is made the victim takes up to 3-18 hit points damage.\n\nSea: Found only in tropical waters, these marine creatures attack only when hungry (20% chance). They otherwise ignore other creatures unless molested. Sea snakes have a poisonous bite. The largest are able to coil about small vessels and crush them at a rate of 10% of total value per melee round of constriction.\n\nSpitting: The spitting giant snake is a variety of the poisonous type which can emit a poisonous spittle, spraying it up to 3\" at any single creature. The victim must save versus poison. Naturally, the bite of these snakes is likewise poisonous. Giant spitting cobras are a typical example of the monster.\n\n[Shared family description from SNAKE, Giant (Spitting)]\n\n[Shared family description from SNAKE, Giant (Amphisbaenc)]", -- complete Monster Manual prose, verbatim
}
