-- SPECTRE
-- Source: Monster Manual, page 90+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SPECTRE",
  page = 90,
  hitDice = "7 + 3",
  hitDiceNum = 7,
  hitDiceBonus = 3,
  avgHp = 35,
  armorClass = 2,
  numAttacks = 1,
  damage = { { min = 1, max = 8 } },
  xp = 1650,
  xpPerHp = 10,
  xpValue = 2000, -- 1650 + 10/hp x 35 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 6 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "Q (x3), X, Y" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 }, { mode = "walk", rate = 30 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "high",
  alignment = "lawful_evil",
  specialAttacks = "Energy drain",
  specialDefenses = "+1 or better weapon to hit",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Spectres are very powerful undead humans whose primary existence is on the negative material plane. Spectres haunt the most desolate of places, tombs, and sturgeons. They hate sunlight and living things. Daylight makes them powerless. Life makes them lament their unlife.\n\nA spectre's chilling touch causes 1-8 hit points of damage and drains 2 life energy levels from an opponent, the latter due to the negative force of the spectre. Thus, an 11th level character, or an 11 hit dice creature, struck by a spectre would suffer 1-8 hit points of damage plus loss in level ability, hit dice, etc. Such loss is permanent, but characters can regain lost levels through continued acquisition of experience points, of course. Certain magic might restore lost levels as well.\n\nSpectres are not affected by sleep, charm, hold, or cold-based spells. Poison or paralyzation do not harm spectres. Holy water causes a spectre to suffer 2-8 hit points of damage for every vial-full which hits it. A raise dead spell will destroy a spectre unless it makes its saving throw versus magic. Any human totally drained of life energy by a spectre becomes a half-strength spectre under the control of the spectre which drained him.", -- complete Monster Manual prose, verbatim
}
