-- SPRITE
-- Source: Monster Manual, page 93+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SPRITE",
  page = 93,
  hitDice = "1",
  hitDiceNum = 1,
  hitDiceBonus = 0,
  avgHp = 4,
  armorClass = 6,
  numAttacks = 1,
  damage = { { raw = "By weapon type" } },
  xp = 80,
  xpPerHp = 1,
  xpValue = 84, -- 80 + 1/hp x 4 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 10, max = 100 },
  lairPct = 20,
  treasure = { individual = nil, inLair = "C" },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 }, { mode = "walk", rate = 18 } } },
  size = nil,
  sizeDetail = "5 (2' tall)",
  intelligence = "very",
  alignment = "neutral_(good)",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Sprites dwell in meadows and wooded glens. They are very shy and reclusive, but they hate evil and ugliness of all sorts. They are armed with slim swords (equal to daggers) and small bows with but half the range and effect of a short bow. However, their arrows are coated with a special ointment which causes any creature struck to save versus poison or sleep for 1-6 hours in a comatose state. The sprites will then slay evil creatures or remove good ones to a place far from where they encountered the sprites. Note that sprites are 75% likely to be unnoticed by any creature, and they will attack only evil creatures unless molested first.\n\nSprites are able to become invisible at will, detect good/evil at a 5\" range, and move silently. When invisible they cause opponents to strike with a -4 on \"to hit\" dice.\n\nSprites speak their own language and the common tongue.", -- complete Monster Manual prose, verbatim
}
