-- STIRGE
-- Source: Monster Manual, page 93+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "STIRGE",
  page = 93,
  hitDice = "1 + 1",
  hitDiceNum = 1,
  hitDiceBonus = 1,
  avgHp = 5,
  armorClass = 8,
  numAttacks = 1,
  damage = { { min = 1, max = 3 } },
  xp = 36,
  xpPerHp = 2,
  xpValue = 46, -- 36 + 2/hp x 5 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 3, max = 30 },
  lairPct = 60,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 }, { mode = "walk", rate = 18 } } },
  size = nil,
  sizeDetail = "5",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Drain blood",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Stirges are found only in very dark, tangled forests or in subterranean lairs. They lay in wait for warm-blooded creatures, swoop down, and when their long, sharp proboscis is attached, the blood of the victim is drawn through to be eaten.\n\nStirges attack as if they were creatures with 4 hit dice rather than 1 + 1. The proboscis of a stirge inflicts 1-3 hit points of damage when it hits. Each melee round after striking, until it has drained 12 hit points value in blood, the stirge drains blood equal to 1-4 hit points. Bloated with blood, a stirge draining 12\n\nhit points worth will flap off to digest its repast. The only method to detach a stirge from its prey is to kill it.\n\nDescription: The feathers of a stirge are rusty red to red brown. Its eyes and feet are yellowish. The dangling proboscis of a stirge is pink at the tip, fading to gray at the base.", -- complete Monster Manual prose, verbatim
}
