-- Stone Giant
-- Source: Monster Manual, page 46+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Stone Giant",
  page = 46,
  hitDice = "9 + 1-3",
  hitDiceNum = 9,
  hitDiceBonus = 2,
  avgHp = 42,
  armorClass = 0,
  numAttacks = 1,
  damage = { { min = 3, max = 18 } },
  xp = 900,
  xpPerHp = 14,
  xpValue = 1488, -- 900 + 14/hp x 42 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 8 },
  lairPct = 30,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "12' tall",
  intelligence = "average",
  alignment = "neutral",
  specialAttacks = "Hurling rocks for 3-30 hit points",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Stone giants inhabit mountainous regions in most cases, dwelling in caves\n\nor caverns. They are fond of cave bears and are 75% likely to have 1-4 guarding their lair. If more than 4 stone giants are encountered in their lair numbers 5 and 6 will be females (treat as hill giants with regard to hit dice and damage/attack), and numbers 7 and 8 will be young (roll percentile dice to determine size).\n\nStone giants are playful at times — especially at night. The adults find great sport hurling rocks from 1\" to 30\" distances, causing 3-30 hit points of damage when striking a creature, and stone giants are 90% likely to catch similar types of missiles hurled at them.\n\nDescription: With their gray to gray-brown skins, dark gray to blue-gray hair, and metallic-looking eyes (silver to steel), stone giants are both striking in appearance and able to blend easily into stoney settings. The latter effect is enhanced by their choice of rock-colored garments. Stone giants are typically armed with stone weapons.", -- complete Monster Manual prose, verbatim
}
