-- STRANGLE WEED
-- Source: Monster Manual, page 94+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "STRANGLE WEED",
  page = 94,
  hitDice = "2-4",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 6,
  numAttacks = 1,
  damage = { { raw = "See below" } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 77, -- 35 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 3, max = 12 },
  lairPct = 100,
  treasure = { individual = nil, inLair = "J-N, Q, C (magic only)" },
  move = { rate = 0, modes = {  } },
  size = "S",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Strangle weed is an intelligent kelp found in relatively warm sea water. A bed of this carnivorous plant is indistinguishable from normal seaweed. The plant grows in an oval with 3-12 fronds in a patch of 3-12 square feet. The fronds vary from 7' to 12' long, and any creature within grasp of 1 or more fronds will be attacked. A hit by the strangle weed indicates the victim is entwined by the attacking frond. Each frond has a strength of 4-16 points. A victim compares its strength against the frond or fronds which have entwined it. The difference in the victim's favor is its chance of escaping, i.e., 1 equals 10%, 2 is 20%, etc. A negative difference, a balance in favor of the weed, indicates the victim has taken that number of points of crushing damage, i.e. a victim's strength of 18 compared to the 3 fronds holding it, 30, so the strangle weeds inflict 12 points of damage on their prey. Any creature entwined strikes at -2 on its \"to hit\" rolls. Treasure is found beneath the sand of the bed of the strangle weed \u2014 left by former victims.", -- complete Monster Manual prose, verbatim
}
