-- SYLPH
-- Source: Monster Manual, page 94+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "SYLPH",
  page = 94,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 9,
  numAttacks = 0,
  damage = {  },
  xp = 325,
  xpPerHp = 3,
  xpValue = 367, -- 325 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "Q (x10), X" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 36 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "exceptional",
  alignment = "neutral_(good)",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "50%",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Sylphs are very beautiful creatures similar to nymphs. The sylphs, however, dwell primarily in aerial places. They are fond of flitting about, and it is not likely that they will be encountered near the place where they dwell.\n\nSylphs sometimes (20%) befriend creatures of good alignment, aiding them in some way. A sylph has magical ability of 7th level (4 \u2014 1st level spells, 3 \u2014 2nd, 2 \u2014 3rd, and 1 \u2014 4th once per day) in addition to the abilities of invisibility at will and conjuring an air elemental once per week.\n\nSylphs speak their own and the common tongue.", -- complete Monster Manual prose, verbatim
}
