-- TICK, Giant
-- Source: Monster Manual, page 95+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TICK, Giant",
  page = 95,
  hitDice = "2-4",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 3,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 48, -- 20 + 2/hp x 14 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 3, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 3, modes = { { mode = "walk", rate = 3 } } },
  size = "S",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Blood drain",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant ticks are found in forests and occasionally in caves or caverns as well. These insects seek to drop upon prey, insert their hollow mouthbub, and suck blood from the victim. A hit by a giant tick scores 1-4 points of damage and indicates the monster has attached itself. Each melee round thereafter it will drain 1-6 hit points of blood, until reaching satiation at a blood drain equal to its hit points, when it drops off. A giant tick must be killed, severely burned, or immersed in water to detach it prior to satiation. Any creature bitten has a 50% chance of contacting a fatal disease from the tick. The disease will be fatal in 2-8 days unless a cure disease spell is cast upon the victim.", -- complete Monster Manual prose, verbatim
}
