-- TIGER (Sabre-Tooth (Smilodon))
-- Source: Monster Manual, page 95+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TIGER (Sabre-Tooth (Smilodon))",
  page = 95,
  hitDice = "7 + 2",
  hitDiceNum = 7,
  hitDiceBonus = 2,
  avgHp = 34,
  armorClass = 6,
  numAttacks = 3,
  damage = { { min = 2, max = 5 }, { min = 2, max = 5 }, { min = 2, max = 12 } },
  xp = 225,
  xpPerHp = 6,
  xpValue = 429, -- 225 + 6/hp x 34 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 2 },
  lairPct = 10,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Rear claws for 2-8/2-8",
  specialDefenses = "Surprised only on a 1",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Tigers range from subarctic to tropical areas, for they are highly adaptable and superb hunters. They often hunt in pairs or family groups. They climb well, can leap 10' upwards and 30' to 50' ahead in attack. If encountered in their lair there is a 25% chance that there will be 1-3 cubs there, these young having no effective attacks, and are from 30% to 60% mature. When they score 2 forepaw hits in one melee round, tigers also get 2 additional rear claw attacks each at 2-8 hit points damage that round.\n\nSabre-Tooth Tiger: The most aggressive and fearsome predator of the Pleistocene epoch, these giants are seldom encountered elsewhere. They range only in warm regions but otherwise conform to the characteristics of normal tigers. Their six inch long fangs inflict terrible wounds, and the size of these teeth, along with the power of the sabre-tooth tiger's jaws, give the creature a +2 on \"to hit\" dice.", -- complete Monster Manual prose, verbatim
}
