-- TITANOTHERE
-- Source: Monster Manual, page 96+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TITANOTHERE",
  page = 96,
  hitDice = "12",
  hitDiceNum = 12,
  hitDiceBonus = 0,
  avgHp = 54,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 16 } },
  xp = 1300,
  xpPerHp = 16,
  xpValue = 2164, -- 1300 + 16/hp x 54 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 12 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "8'",
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "Charge & trample",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "These huge and fearless plant-eaters roam the temperate plains of the Pleistocene era in herds. If more than 6 are encountered 1-4 of those numbering over one-half the possible total will be young, from 10% to 80% grown.\n\nIf any creature threatens the herd, the largest animals (males) will charge. If the charge strikes home, damage inflicted is double the amount shown on the dice (4-32). Titanotheres will trample (2-12 per foot) any opponent low enough for them to step upon.\n\nTOAD, Giant", -- complete Monster Manual prose, verbatim
}
