-- TOAD, Giant (Poisonous)
-- Source: Monster Manual, page 96+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TOAD, Giant (Poisonous)",
  page = 96,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 7,
  numAttacks = 1,
  damage = { { min = 2, max = 5 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 38, -- 20 + 2/hp x 9 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "animal",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Giant toads are found in most regions. Although their smaller cousins are beneficial insect eaters, the large toads are prone to devour any creature which appears edible. All toads are capable of chopping their movement distance. This hop clears objects up to one-third the linear distance in height, and it requires but a single melee round to accomplish, and they can attack in mid-air or at the end of their leap.\n\nIce Toad: These creatures are found in cold climes or far beneath the surface of the ground. In addition to their typical abilities these monsters are able to radiate cold in a 1\" radius from their body.\n\nAll non-cold using creatures within 1\" of the ice toad suffer 3-18 points of damage. The toad can do this but once every other melee round. The ice toads have their own weird language.\n\nPoisonous Toad: The poisonous type of giant toad is indistinguishable from non-poisonous toads. Their bite necessitates a saving throw versus poison, or the victim will die immediately.", -- complete Monster Manual prose, verbatim
}
