-- TREANT
-- Source: Monster Manual, page 97+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TREANT",
  page = 97,
  hitDice = "7-12",
  hitDiceNum = 7,
  hitDiceBonus = 0,
  avgHp = 43,
  armorClass = 0,
  numAttacks = 2,
  damage = { { min = 2, max = 16 }, { raw = "attack (see below)" } },
  xp = 225,
  xpPerHp = 8,
  xpValue = 569, -- 225 + 8/hp x 43 avg hp
  xpSource = "formula",
  frequency = "rare",
  noAppearing = { min = 1, max = 20 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "Q (x5), S" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "chaotic_good",
  specialAttacks = "See below",
  specialDefenses = "Never surprised",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Treats are strangely related to humans and trees, combining features of both species. They dwell in woods and forests and are basically indistinguishable from trees. They hate evil things or unrestrained use of fire. If need arises treats can actually cause trees to come to life, move 3\" per turn, and attack as a full-grown treat (2 attacks for 4-24 hit points of damage/attack). Aroused treats must be within 6\" of a normal tree to cause it to move, and an individual treat can cause only one or two normal trees to move and attack as stipulated.\n\nBecause of their body and skin structures, treats have a very superior armor class rating. However, against fire they lose this superiority. Attacks based on fire are at a +4 on \"to hit\" dice; treats save against such attacks at a -4, and fire damage dice are +1 hit point.\n\nTreats of small size (12'-15' tall) have 7 or 8 hit dice and do 2-16 hit points of damage/attack, middle-sized treats (16'-19') have 9-10 hit dice and attack damage of 3-18, and those of large size (20'-23'+) have 11-12 hit dice and do 4-24 points of damage. Treats and treat-controlled trees cause 1 point of structural damage on fortifications (this is for both attacks possible to any given treat or treat-controlled tree), regardless of the size of the treat attacking.\n\nA treat lair will typically be a vast cave screened by many plants and trees. Treats resent greatly uninvited entrance into such a place.", -- complete Monster Manual prose, verbatim
}
