-- Triceratops
-- Source: Monster Manual, page 29+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Triceratops",
  page = 29,
  hitDice = "16",
  hitDiceNum = 16,
  hitDiceBonus = 0,
  avgHp = 72,
  armorClass = { 2, 6 },
  numAttacks = 3,
  damage = { { min = 1, max = 8 }, { min = 1, max = 12 }, { min = 1, max = 12 } },
  xp = 4000,
  xpPerHp = 20,
  xpValue = 5440, -- 4000 + 20/hp x 72 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 2, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 9, modes = { { mode = "walk", rate = 9 } } },
  size = "L",
  sizeDetail = "24'+ long",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The largest of the ceratopsians, and by far the most aggressive, this beaked herbivore is a plains dweller. It has a huge front plate of bone from which project two great horns (3'+ long), while a somewhat shorter horn juts from its nose. Its body is not armored, thus armor class 6. Any creature which infringes on the territory of these reptiles is likely to be charged and speared. Smaller creatures will simply be trampled for 2-24 hit points of damage.", -- complete Monster Manual prose, verbatim
}
