-- TROGLODYTE
-- Source: Monster Manual, page 98+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TROGLODYTE",
  page = 98,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 5,
  numAttacks = "3 or 1",
  damage = { { min = 1, max = 3 }, { min = 1, max = 3 }, { min = 2, max = 5 } },
  xp = 36,
  xpPerHp = 2,
  xpValue = 54, -- 36 + 2/hp x 9 avg hp
  xpSource = "appendixE",
  frequency = "common",
  noAppearing = { min = 10, max = 100 },
  lairPct = 15,
  treasure = { individual = nil, inLair = "A" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "chaotic_evil",
  specialAttacks = "Revulsion odor",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Troglodytes are a race of reptilian humanoids who dwell in subterranean places. They loathe humans, and their aim is to slaughter all whom they encounter. Troglodytes have excellent infravision (90').\n\nFor every 10 troglodytes encountered there will be 1 leader-type with 3 hit dice. For every 20 there will be an additional 2 leader types with 4 hit dice each. If 60 or more are encountered there will be a troglodyte chieftain with 6 hit dice, and 2-8 guards of 3 hit dice each.\n\nThe lair of a tribe of troglodytes is typically a large cave or cavern with small chambers adjoining it in which the individual units live. A lair will contain females equal to 100% of the males. Females fight as 1 + 1 hit dice monsters. There will also be hatchlings and eggs, but these are of no importance.\n\nTroglodytes can attack with claws and teeth, but 50% of them use weapons of some type. The armed half of a group encountered will have:\n\n|  javelin (2) | 25%  |\n| --- | --- |\n|  battle axe (stone) | 10%  |\n|  morning star (stone) | 10%  |\n|  sword | 5%  |\n\nTheir javelins are great vaned darts which have a +3 chance to hit when used by troglodytes and cause 2-8 hit points damage. They shun armor.\n\nWhen aroused for battle, troglodytes emit a secretion which smells extremely disgusting to humans \u2014 including dwarves, elves, gnomes, half-elves and halflings. Those humans failing their saving throw versus poison are affected by revulsion so as to lose 1 point of strength per melee round for 1-6 rounds, cumulative. Loss of strength lasts 10 melee rounds after it has taken final effect.\n\nTroglodytes have a chameleon-like power, so they can change their skin coloration to shades of gray, brown or green. They thus surprise on a 1-4 unless they are angry and excreting their stench. They use this coloration to hide when an encounter goes against them.", -- complete Monster Manual prose, verbatim
}
