-- TROLL
-- Source: Monster Manual, page 98+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TROLL",
  page = 98,
  hitDice = "6 + 6",
  hitDiceNum = 6,
  hitDiceBonus = 6,
  avgHp = 33,
  armorClass = 4,
  numAttacks = 3,
  damage = { { min = 5, max = 8 }, { min = 5, max = 8 }, { min = 2, max = 12 } },
  xp = 525,
  xpPerHp = 8,
  xpValue = 789, -- 525 + 8/hp x 33 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 12 },
  lairPct = 40,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "9\" + tall",
  intelligence = "low",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "Regeneration",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Trolls are horrid carnivores found in nearly every clime. They are feared by most creatures, as a troll knows no fear and attacks unceasingly. Their sense of smell is very acute, their infravision is superior (90'), and their strength is very great.\n\nA troll attacks with its clawed forelimbs and its great teeth. A troll is able to fight 3 different opponents at once. 3 melee rounds after being damaged, a troll will begin to regenerate. Regeneration repairs damage at 3 hit points per round; this regeneration includes the rebonding of severed members. The loathsome members of a troll have the ability to fight on even if severed from the body; a hand can claw or strangle, the head bite, etc. Total dismemberment will not slay a troll, for its parts will slither and scuttle together, rejoin, and the troll will arise whole and ready to continue combat. To kill a troll, the monster must be burned or immersed in acid, any separate pieces being treated in the same fashion or they create a whole again in 3-18 melee rounds.\n\nDescription: Troll hide is a nauseating moss green, mottled green and gray, or putrid gray. The writhing hair-like growth upon a troll's head is greenish black or iron gray. The eyes of a troll are dull black.", -- complete Monster Manual prose, verbatim
}
