-- TURTLE (Sea, Giant)
-- Source: Monster Manual, page 98+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "TURTLE (Sea, Giant)",
  page = 98,
  hitDice = "15",
  hitDiceNum = 15,
  hitDiceBonus = 0,
  avgHp = 68,
  armorClass = { 2, 5 },
  numAttacks = 1,
  damage = { { min = 4, max = 16 } },
  xp = 2400,
  xpPerHp = 20,
  xpValue = 3760, -- 2400 + 20/hp x 68 avg hp
  xpSource = "formula",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 3 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 1, modes = { { mode = "walk", rate = 1 }, { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Turtle, Sea, Giant: These basically non-aggressive marine creatures will fight fiercely if annoyed or threatened. If they surface beneath a small craft there is a possibility of upsetting the vessel, i.e. 90% for a long boat, 10% for a typical long ship. The head and flippers of the creature are armor class 5, but they can be withdrawn to make these areas armor class 3.\n\nTurtle, Snapping, Giant: Feared greatly for their voracious appetite and aggressiveness, giant snapping turtles are found in lakes and large rivers. They lurk near shore or on the bottom, as they do not swim quickly. They remain motionless, thus surprising on 1-4 (out of 6), and then shoot forth their long neck (up to 10' long) to grab their prey. The head and limbs of these monsters are armor class 5, but they can be withdrawn to offer armor class 2.\n\n[Shared family description from TURTLE (Snapping, Giant)]", -- complete Monster Manual prose, verbatim
}
