-- Tyrannosaurus Rex
-- Source: Monster Manual, page 29+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Tyrannosaurus Rex",
  page = 29,
  hitDice = "18",
  hitDiceNum = 18,
  hitDiceBonus = 0,
  avgHp = 81,
  armorClass = 5,
  numAttacks = 3,
  damage = { { min = 1, max = 6 }, { min = 1, max = 6 }, { min = 5, max = 40 } },
  xp = 6550,
  xpPerHp = 25,
  xpValue = 8575, -- 6550 + 25/hp x 81 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 2 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "50' long, 20' high",
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "There can be no question that this reptile is the most fearsome and terrible of all carnivorous dinosaurs. Despite its huge size the monster is swift afoot. Its huge head is nearly six feet long, and its teeth are from three to six inches in length. It is a plains dweller, and so stupidly fierce that it will attack a small triceratops, kill it, and swallow its head in one gulp \u2014 thus killing itself in a matter of hours as the horns of the victim pierce the stomach of the victor. Of course, this monster will pursue and eat nearly anything, engulfing man-sized creatures whole on a roll of 18 or better.", -- complete Monster Manual prose, verbatim
}
