-- Water Elemental
-- Source: Monster Manual, page 39+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "Water Elemental",
  page = 39,
  hitDice = "16",
  hitDiceNum = 16,
  hitDiceBonus = 0,
  avgHp = 72,
  armorClass = 2,
  numAttacks = 1,
  damage = { { min = 5, max = 30 } },
  xp = 2400,
  xpPerHp = 20,
  xpValue = 3840, -- 2400 + 20/hp x 72 avg hp
  xpSource = "formula",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 }, { mode = "walk", rate = 18 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "+2 or better weapon to hit",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Water elementals are, for all practical purposes, limited to water operations, for they can stray only 6\" from their element. It normally requires a considerable volume of water (or watery liquid) to create a water elemental \u2014 a pool of water of at least 1,000 cubic feet in volume, but several large barrels of ale or wine would suffice. Outside their element water elementals are less effective, and they lose 1 point from each die of damage they inflict. In a body of water they attack at full effect, move more swiftly, can upset small craft (1 ton of craft per hit die of elemental), or slow or stop craft (1 ton of vessel can be stopped per hit point of elemental; if greater tonnage, simply ratio the tons to hit points to find the rate the vessel is slowed).\n\nThere are many other elemental forms on the plane of water. Free-willed, intelligent beings are common as well as much more powerful elementals of the sort dealt with here. It is possible that they are ruled by a god-like king.", -- complete Monster Manual prose, verbatim
}
