-- WATER WEIRD
-- Source: Monster Manual, page 101+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WATER WEIRD",
  page = 101,
  hitDice = "3 + 3",
  hitDiceNum = 3,
  hitDiceBonus = 3,
  avgHp = 17,
  armorClass = 4,
  numAttacks = 0,
  damage = {  },
  xp = 370,
  xpPerHp = 4,
  xpValue = 438, -- 370 + 4/hp x 17 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 3 },
  lairPct = 50,
  treasure = { individual = nil, inLair = "I, O, P, Y" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "L",
  sizeDetail = "10'+ long",
  intelligence = "very",
  alignment = "chaotic_evil",
  specialAttacks = "Drowning",
  specialDefenses = "See below",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The water weird are a life form originating in the elemental plane of water. They attack all living things, feeding from their essences in some unknown manner. The creature forms in two melee rounds from the water, appearing as a serpent, and lashes out, striking as a 6 hit dice monster. Any creature struck will be dragged into the water unless it saves versus paralyzation. Sharp weapons cause but 1 hit point of damage; blunt ones cause normal damage when striking these monsters. Damage equal to its total hit points disrupts the water weird; it reforms again in 2 melee rounds. Cold spells slow it, fire-based spells do half or no damage, but a purify water spell actually kills. All other attacks simply do not harm or disrupt the creature. A water weird can take over a water elemental on a dice score of 11 or better on a 20-sided die.", -- complete Monster Manual prose, verbatim
}
