-- WHALE
-- Source: Monster Manual, page 101+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WHALE",
  page = 101,
  hitDice = "12-36",
  hitDiceNum = 12,
  hitDiceBonus = 0,
  avgHp = 108,
  armorClass = 4,
  numAttacks = "1 or 1",
  damage = { { min = 5, max = 20 } },
  xp = 1300,
  xpPerHp = 16,
  xpValue = 3028, -- 1300 + 16/hp x 108 avg hp
  xpSource = "formula",
  frequency = "common",
  noAppearing = { min = 1, max = 8 },
  lairPct = 0,
  treasure = { individual = nil, inLair = "See below" },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 }, { mode = "walk", rate = 24 } } },
  size = "L",
  sizeDetail = nil,
  intelligence = "low",
  alignment = "neutral",
  specialAttacks = "Tail",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Whales great and small (for whales) populate the oceans. Many are plant-eaters, but a few are carnivores. The latter will occasionally attack humans (killer whales will always do so), and all forms of whales are very dangerous if molested. The carnivorous whales attack by biting (5-20 to 15-60, depending on size). Other whales use their great flukes to smash opponents (1-8 to 5-40, based on size). Whales at the surface can smash with their tails, causing damage equal to half their number of hit dice to any creature struck. Carnivorous whales will swallow prey whole, the huge (36 hit dice) sperm whales being able to swallow a long boat and its crew whole and alive. (While it is not too difficult to then escape, digestive juices will cause 1 point of damage per turn, and if the whale disgorges the prey swallowed alive due to their irritation of its stomach, there is a 50% chance this will be done at considerable depth.)\n\nThe stomach of a carnivorous whale can contain treasure. A 1% per hit die chance is allowed for each coin type, gems, jewelry, and magic items. The number of coins is 1,000-3,000 per type. Gems and jewelry will number from 1-20 each. 1-4 magic items can be contained. Sick whales give forth ambergris, a stinking mess which is worth 1,000 to 20,000 gold pieces in a large city. A whale carcass can be sold in a port for 100 gold pieces per hit die of size.", -- complete Monster Manual prose, verbatim
}
