-- WIGHT
-- Source: Monster Manual, page 101+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WIGHT",
  page = 101,
  hitDice = "4 + 3",
  hitDiceNum = 4,
  hitDiceBonus = 3,
  avgHp = 21,
  armorClass = 5,
  numAttacks = 1,
  damage = { { min = 1, max = 4 } },
  xp = 540,
  xpPerHp = 5,
  xpValue = 645, -- 540 + 5/hp x 21 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 16 },
  lairPct = 70,
  treasure = { individual = nil, inLair = "B" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "average",
  alignment = "lawful_evil",
  specialAttacks = "Energy drain",
  specialDefenses = "Silver or magic weapons to hit",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "The term wight has lost its old meaning of a person and come to stand for those undead humans who typically inhabit barrow mounds or catacombs. These creatures are most evil and hateful, seeking to destroy any life form they encounter. Wights shun bright lights and hate sunlight.\n\nBecause these monsters exist simultaneously on the normal and negative planes of the material plane, they are affected only by silver or magical weapons. This existence allows them to drain life energy levels — one such level each time they score a hit on an opponent. The creature so hit loses the hit points of damage scored (1-4) plus one experience level and all the bonuses derived from that level, i.e. hit dice, class bonuses, thief abilities, spell levels, etc. A 9th level magic user struck by a wight loses 1-4 hit points and he becomes an 8th level magic user; he has the spells and the hit points of an 8th level magic user, and he melees as an 8th level character of his class.\n\nWights are not affected by sleep, charm, hold, or cold-based spells. Neither poison nor paralyzation harms wights. Holy water causes 2-8 hit points of damage for every viol-full which strikes. A raise dead spell will destroy a wight. Any human totally drained of life energy by a wight will become a half-strength wight under control of its slayer.", -- complete Monster Manual prose, verbatim
}
