-- WILL-O-(THE)-WISP
-- Source: Monster Manual, page 102+; XP from DMG p.86 formula
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WILL-O-(THE)-WISP",
  page = 102,
  hitDice = "9",
  hitDiceNum = 9,
  hitDiceBonus = 0,
  avgHp = 40,
  armorClass = -8,
  numAttacks = 1,
  damage = { { min = 2, max = 16 } },
  xp = 600,
  xpPerHp = 12,
  xpValue = 1080, -- 600 + 12/hp x 40 avg hp
  xpSource = "formula",
  frequency = "*uncommon*",
  noAppearing = { min = 1, max = 1 },
  lairPct = 5,
  treasure = { individual = nil, inLair = "Z" },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 } } },
  size = nil,
  sizeDetail = "5",
  intelligence = "exceptional",
  alignment = "chaotic_evil",
  specialAttacks = "See below",
  specialDefenses = "See below",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Will-o-wisps commonly haunt deserted, dangerous places such as bogs, fens, swamps, or catacombs where mires, quicksand, pit traps and the like are plentiful. A victim trapped by these hazards feeds the will-o-wisp as it expires, for the thing feeds upon the fleeing life force. Thus, will-o-wisps seek to lure prey to their doom. 10% of the time 1-3 are encountered, and in these cases the creatures' lair will be nearby 90% of the time. The creature can attack, however, any hit causing 2-16 points of electrical damage to the opponent.\n\nA will-o-wisp is able to grow bright or very dim in order to confuse prey. It can move slowly or flit about. It can blank out its glow entirely for 2-8 melee rounds if it does not attack, and at that time it can be detected only by creatures able to see invisible objects.\n\nWhile any weapon will harm a will-o-wisp, most spells do not affect it. The only spells which can affect the creature are *protection from evil, magic missile and maze*. If brought to 5 or fewer remaining hit points a will-o-wisp will reveal its lair and give over its treasure.\n\n*Description:* A will-o-wisp is a glowing sphere, looking like a lantern, torch or even a *dancing lights* spell effect. In combat they glow blue, violet or pale green.", -- complete Monster Manual prose, verbatim
}
