-- WOLF (Dire (Worg))
-- Source: Monster Manual, page 102+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WOLF (Dire (Worg))",
  page = 102,
  hitDice = "3 + 3",
  hitDiceNum = 3,
  hitDiceBonus = 3,
  avgHp = 17,
  armorClass = 6,
  numAttacks = 1,
  damage = { { min = 2, max = 8 } },
  xp = 35,
  xpPerHp = 3,
  xpValue = 86, -- 35 + 3/hp x 17 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 3, max = 12 },
  lairPct = 10,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 18, modes = { { mode = "walk", rate = 18 } } },
  size = "M",
  sizeDetail = "L",
  intelligence = "semi-low",
  alignment = "neutral_(evil)",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "**Wolf:** These carnivores are found in wild forests from the arctic to the temperate zones. They always hunt in packs and if hungry (75%) they will not hesitate to follow and attack prey, always seeking to strike at an unguarded moment. Their howling is 50% likely to panic herbivores which are not being held by humans and calmed. They love horse meat. If encountered in their lair there is a 30% chance that there will be 1-4 cubs per pair of adult wolves. Cubs do not fight and can be trained as war dogs or hunting beasts.\n\n**Wolf, Dire:** This variety of wolf is simply a huge specimen typical of the Pleistocene Epoch. They conform to the characteristics of normal wolves. (**Worgs**): Evil natured, neo-dire wolves are known as worgs. These creatures have a language and are often found in co-operation with goblins in order to gain prey or to simply enjoy killing. They are as large as ponies and can be ridden. They otherwise conform to the characteristics of wolves.\n\n**Wolf, Winter:** The winter wolf is a horrid carnivore which inhabits only chill regions. It is of great size and foul disposition. Winter wolves can use their savage jaws or howl forth a blast of frost which will coat any creature within 1' of their muzzle. This frost causes 6-24 hit points damage \u2014 half that amount if a saving throw versus dragon breath is successful. The winter wolf is able to use the howling frost but once per 10 melee rounds. *Cold-based* attacks do not harm them, but *fire-based* attacks cause +1 per die of damage normally caused. They have their own language and can also converse with worgs. The coat of the winter wolf is glistening white or silvery, and its eyes are very pale blue or silvery. The pelt of the creature is valued at 5,000 gold pieces.\n\n[Shared family description from WOLF (Winter)]\n\n[Shared family description from WOLF (Common)]", -- complete Monster Manual prose, verbatim
}
