-- WOLVERINE (Common)
-- Source: Monster Manual, page 102+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WOLVERINE (Common)",
  page = 102,
  hitDice = "3",
  hitDiceNum = 3,
  hitDiceBonus = 0,
  avgHp = 14,
  armorClass = 5,
  numAttacks = 3,
  damage = { { min = 1, max = 4 }, { min = 1, max = 4 }, { min = 2, max = 5 } },
  xp = 125,
  xpPerHp = 3,
  xpValue = 167, -- 125 + 3/hp x 14 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 1, max = 1 },
  lairPct = 15,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 } } },
  size = "S",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "neutral_(evil)",
  specialAttacks = "Musk",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Wolverines inhabit only colder regions (which is fortunate for mankind, for these animals are horrible). They are vicious, hateful, destructive carnivores who kill for the sheer love of ending another creature's life. Bears and wolves respect these creatures' ferocity. Their speed is partially responsible for their high armor class, and their ferocity in combat makes their attacks have a +4 on \"to hit\" dice rolls: A wolverine can squirt its disgusting musk at any opponent at its rear. The musk is equivalent to that of a skunk (q.v.). A wolverine will purposefully destroy food or human goods of any sort by spraying musk upon the unwanted items. Although only semi-intelligent in most things, in hunting and combat the creature is exceptionally intelligent.\n\n[Shared family description from WOLVERINE (Giant)]", -- complete Monster Manual prose, verbatim
}
