-- WOLVERINE (Giant)
-- Source: Monster Manual, page 102+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WOLVERINE (Giant)",
  page = 102,
  hitDice = "4 + 4",
  hitDiceNum = 4,
  hitDiceBonus = 4,
  avgHp = 22,
  armorClass = 4,
  numAttacks = 3,
  damage = { { min = 2, max = 5 }, { min = 2, max = 5 }, { min = 2, max = 8 } },
  xp = 125,
  xpPerHp = 3,
  xpValue = 191, -- 125 + 3/hp x 22 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 1, max = 1 },
  lairPct = 15,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "semi-",
  alignment = "neutral_(evil)",
  specialAttacks = "Musk",
  specialDefenses = "Nil",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil 101",
  text = "Wolverines inhabit only colder regions (which is fortunate for mankind, for these animals are horrible). They are vicious, hateful, destructive carnivores who kill for the sheer love of ending another creature's life. Bears and wolves respect these creatures' ferocity. Their speed is partially responsible for their high armor class, and their ferocity in combat makes their attacks have a +4 on \"to hit\" dice rolls: A wolverine can squirt its disgusting musk at any opponent at its rear. The musk is equivalent to that of a skunk (q.v.). A wolverine will purposefully destroy food or human goods of any sort by spraying musk upon the unwanted items. Although only semi-intelligent in most things, in hunting and combat the creature is exceptionally intelligent.", -- complete Monster Manual prose, verbatim
}
