-- WRAITH
-- Source: Monster Manual, page 103+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "WRAITH",
  page = 103,
  hitDice = "5 + 3",
  hitDiceNum = 5,
  hitDiceBonus = 3,
  avgHp = 25,
  armorClass = 4,
  numAttacks = 1,
  damage = { { min = 1, max = 6 } },
  xp = 575,
  xpPerHp = 6,
  xpValue = 725, -- 575 + 6/hp x 25 avg hp
  xpSource = "appendixE",
  frequency = "uncommon",
  noAppearing = { min = 2, max = 12 },
  lairPct = 25,
  treasure = { individual = nil, inLair = "E" },
  move = { rate = 12, modes = { { mode = "walk", rate = 12 }, { mode = "walk", rate = 24 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "very",
  alignment = "lawful_evil",
  specialAttacks = "Energy drain",
  specialDefenses = "Silver or magic weapons to hit",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Wraiths are undead, similar in nature to wights, but they exist more strongly on the negative material plane. They are found only in dark and gloomy places, for they have no power in full sunlight.\n\nIn addition to the chilling effect of its touch (1-6 hit points damage), a wraith drains on life energy at the rate of 1 per hit, just as a wight does. Similarly, the wraith can be struck only with silver weapons (which cause only one-half damage) or weapons which are magically enchanted (which score full damage).", -- complete Monster Manual prose, verbatim
}
