-- YETI
-- Source: Monster Manual, page 104+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "YETI",
  page = 104,
  hitDice = "4 + 4",
  hitDiceNum = 4,
  hitDiceBonus = 4,
  avgHp = 22,
  armorClass = 6,
  numAttacks = 2,
  damage = { { min = 1, max = 6 }, { min = 1, max = 6 } },
  xp = 435,
  xpPerHp = 5,
  xpValue = 545, -- 435 + 5/hp x 22 avg hp
  xpSource = "appendixE",
  frequency = "very_rare",
  noAppearing = { min = 1, max = 6 },
  lairPct = 10,
  treasure = { individual = nil, inLair = "D" },
  move = { rate = 15, modes = { { mode = "walk", rate = 15 } } },
  size = "L",
  sizeDetail = "8' tall",
  intelligence = "average",
  alignment = "neutral",
  specialAttacks = "See below",
  specialDefenses = "Impervious to cold",
  magicResistance = "Standard",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Inhabiting only regions of icy cold, yeti are seldom encountered by warm-blooded mankind. Those who do have the misfortune to stumble upon these monsters seldom live to tell the tale, for yeti are very fond of human flesh.\n\nYeti attacks with two clawing strikes, and if any one of these attacks succeeds with a die score of 20 the yeti has grabbed and squeezed his opponent for 2-16 points of additional damage from the chill of the creature. Worse still, if the creature surprised an opponent, a saving throw versus paralyzation must be made, or the victim has looked into the creature's eyes and is rigid with fright for 3 melee rounds and can be automatically struck twice and squeezed by the yeti.", -- complete Monster Manual prose, verbatim
}
