-- ZOMBIE
-- Source: Monster Manual, page 104+; XP from DMG Appendix E
-- Generated by mm2lua.py (R48 pipeline, Python edition), 2026-09-23.
return {
  name = "ZOMBIE",
  page = 104,
  hitDice = "2",
  hitDiceNum = 2,
  hitDiceBonus = 0,
  avgHp = 9,
  armorClass = 8,
  numAttacks = 1,
  damage = { { min = 1, max = 8 } },
  xp = 20,
  xpPerHp = 2,
  xpValue = 38, -- 20 + 2/hp x 9 avg hp
  xpSource = "appendixE",
  frequency = "rare",
  noAppearing = { min = 3, max = 24 },
  lairPct = 0,
  treasure = { individual = nil, inLair = nil },
  move = { rate = 6, modes = { { mode = "walk", rate = 6 } } },
  size = "M",
  sizeDetail = nil,
  intelligence = "non-",
  alignment = "neutral",
  specialAttacks = "Nil",
  specialDefenses = "Nil",
  magicResistance = "See below",
  psionic = "Nil",
  attackDefenseModes = "Nil",
  text = "Zombies are magically animated corpses, undead creatures under the command of the evil magic-users or clerics who animated them. These creatures follow commands \u2014 as spoken on the spot or as given previously \u2014 of limited length and complication (a dozen words or so). Zombies are typically found near graveyards, in dungeons, and in similar charnel places.\n\nZombies are slow, always striking last, but always doing 1-8 hit points of damage when they hit. They always fight until destroyed and nothing short of a cleric can turn them back.\n\nSleep, charm, hold and cold-based spells do not affect zombies. Holy water vials score 2-8 hit points of damage for each one which strikes.\n\nYeti are nearly invisible until within 10' to 30' of their prey. (For each level above 1st add 5% chance of spotting a yeti at normal distance, i.e. a 2nd level character has a 5% chance of spotting one.)\n\nBecause of their adaption to cold, yeti are very susceptible to fire, and attacks employing such heat do 50% greater damage.\n\nIf found in their lair there is a 30% chance that there are 1-3 females there also, and a 15% chance of an additional 2-5 young if females are present.\n\nDescription: These bulky, 300+ pound, creatures are covered in long white fur. Their eyes are pale blue or almost colorless. Their claws and teeth are ivory white.", -- complete Monster Manual prose, verbatim
}
