#!/usr/bin/env python3
# tools/r150_splice.py - R150: PIN the Appendix I
# dressing lists (DMG pp.217-220, the R149 bycatch
# the book-verify pass named ready-to-pin).
#
# (a) NEW dm/appendixi.h - the appendixa.h pattern:
#     pure data, header-only, no caller yet. Five d100
#     band lists, every band edge pinned in the audit:
#     air currents, odors, air, general items and
#     unexplained sounds. The 00 fold and the clamp
#     are named in place.
# (b) regtest.cpp - the include plus the R150 audit
#     block (band edges both ways, the house
#     discipline); the census reads 68 now.
# (c) tools/dmg_gap_report.md - the R150 header note
#     and the Appendix I box flips closed, with the
#     R149 box band-count slips corrected in place:
#     the prints read 14 air-current bands (not 16),
#     54 general-item bands (not 100) and 58 sound
#     bands (not 68); odors (14) and air (6) were
#     right, and the band content the box quoted was
#     correct all along.
#
# Idempotent: safe to run twice; a silent run means the
# paste was truncated - this tail ALWAYS prints. An
# assert follows EVERY patch (the R142 lesson). This
# file contains ZERO backslash characters and no
# literal apostrophe in any content string (the R133b
# + R147 lessons - the few needed are built with AP,
# and the audit printf newline with BS).
# Commit: "R150: Appendix I dressing pinned - air
# currents, odors, air, general items, sounds
# (census 68)"
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NL = chr(10)
AP = chr(39)
BS = chr(92)
applied, already, fails = [], [], []

def rd(p):
    with open(os.path.join(ROOT, p), encoding="ascii") as f:
        return f.read()

def wr(p, s):
    with open(os.path.join(ROOT, p), "w", encoding="ascii") as f:
        f.write(s)

def patch(p, old, new, tag, expect=1, marker=None):
    s = rd(p)
    if marker is None:
        marker = new
    if marker in s:
        already.append(tag)
        return
    n = s.count(old)
    if n != expect:
        fails.append(tag + ": anchor count " + str(n)
                     + " (expected " + str(expect) + ")")
        return
    wr(p, s.replace(old, new))
    applied.append(tag)

def patch_new(p, content, tag):
    fp = os.path.join(ROOT, p)
    if os.path.exists(fp):
        with open(fp, encoding="ascii") as f:
            if f.read() == content:
                already.append(tag)
                return
        fails.append(tag + ": file exists but differs")
        return
    wr(p, content)
    applied.append(tag)

# ---- (1) dm/appendixi.h, the new header ----
appendixi_h = NL.join([
    '// ============================================================================',
    '// Adnd1 - dm/appendixi.h',
    '// R150: DMG pp.217-220 - APPENDIX I, DUNGEON DRESSING (the',
    '// corridor/room dressing lists). Pure data,',
    '// header-only (the appendixa.h pattern: the caller',
    '// rolls and decides when; any table luck beyond a',
    '// row is the callers). Transcribed from the fresh',
    '// DMG upload (2026-10-04), which the R149 book-verify',
    '// pass read cell for cell against a clean book read.',
    '//',
    '// Conventions, all named in place:',
    '//   - All five lists are d100 band tables: the',
    '//     accessor takes the percentile roll (1-100) and',
    '//     returns the band; 0 folds to 100 (the book',
    '//     00), out-of-range rolls clamp (the engine',
    '//     standing band discipline).',
    '//   - R149 box count CORRECTIONS carried here: the',
    '//     print reads 14 air-current bands (the box said',
    '//     16), 54 general-item bands (the box said 100),',
    '//     and 58 sound bands (the box said 68); the',
    '//     odors (14) and air (6) counts were right. The',
    '//     band CONTENT the box quoted was correct - only',
    '//     the counts slipped.',
    '//   - The printed wording quirks are kept as',
    '//     printed: "mouldy" and "sulphurous" (the British',
    '//     spellings), "roar(ing)", "bellow (ing)", and',
    '//     the air table "foggy (or steamy)" family.',
    '//   - The book suggests selecting, not rolling, for',
    '//     most of these; the bands are pinned anyway -',
    '//     the roller discipline is the callers call.',
    '//   - The OTHER Appendix I lists (furnishings,',
    '//     torture chamber, magic-user and religious',
    '//     furnishings, container contents, misc items,',
    '//     jewelry, foodstuffs - the "as desired"',
    '//     selection lists) are selection aids, not band',
    '//     tables, and stay unpinned (named).',
    '// ============================================================================',
    '',
    '#pragma once',
    '',
    'namespace dm {',
    'namespace appendixi {',
    '',
    '// ---- AIR CURRENTS (p.217): 14 printed bands ------------------------------',
    'enum AirCurrent {',
    '    AC_BREEZE_SLIGHT = 0,        // 01-05',
    '    AC_BREEZE_SLIGHT_DAMP,       // 06-10',
    '    AC_BREEZE_GUSTING,           // 11-12',
    '    AC_COLD_CURRENT,            // 13-18',
    '    AC_DOWNDRAFT_SLIGHT,        // 19-20',
    '    AC_DOWNDRAFT_STRONG,        // 21-22',
    '    AC_STILL,                   // 23-69',
    '    AC_STILL_VERY_CHILL,        // 70-75',
    '    AC_STILL_WARM,              // 76-85',
    '    AC_UPDRAFT_SLIGHT,          // 86-87',
    '    AC_UPDRAFT_STRONG,          // 88-89',
    '    AC_WIND_STRONG,             // 90-93',
    '    AC_WIND_STRONG_GUSTING,     // 94-95',
    '    AC_WIND_STRONG_MOANING,     // 96-00',
    '    AC_COUNT',
    '};',
    '',
    'inline AirCurrent airCurrentFor(int r) {',
    '    if (r <= 0)   r = 100;              // 00 folds to 100',
    '    if (r > 100)  r = 100;',
    '    if (r <= 5)   return AC_BREEZE_SLIGHT;',
    '    if (r <= 10)  return AC_BREEZE_SLIGHT_DAMP;',
    '    if (r <= 12)  return AC_BREEZE_GUSTING;',
    '    if (r <= 18)  return AC_COLD_CURRENT;',
    '    if (r <= 20)  return AC_DOWNDRAFT_SLIGHT;',
    '    if (r <= 22)  return AC_DOWNDRAFT_STRONG;',
    '    if (r <= 69)  return AC_STILL;',
    '    if (r <= 75)  return AC_STILL_VERY_CHILL;',
    '    if (r <= 85)  return AC_STILL_WARM;',
    '    if (r <= 87)  return AC_UPDRAFT_SLIGHT;',
    '    if (r <= 89)  return AC_UPDRAFT_STRONG;',
    '    if (r <= 93)  return AC_WIND_STRONG;',
    '    if (r <= 95)  return AC_WIND_STRONG_GUSTING;',
    '    return AC_WIND_STRONG_MOANING;',
    '}',
    '',
    '// ---- ODORS (p.217): 14 printed bands ------------------------------------',
    'enum Odor {',
    '    OD_ACRID = 0,                // 01-03',
    '    OD_CHLORINE,                 // 04-05',
    '    OD_DANK_MOULDY,              // 06-39',
    '    OD_EARTHY,                   // 40-49',
    '    OD_MANURE,                   // 50-57',
    '    OD_METALLIC,                 // 58-61',
    '    OD_OZONE,                    // 62-65',
    '    OD_PUTRID,                   // 66-70',
    '    OD_ROTTING_VEGETATION,       // 71-75',
    '    OD_SALTY_WET,                // 76-77',
    '    OD_SMOKY,                    // 78-82',
    '    OD_STALE_FETID,              // 83-89',
    '    OD_SULPHUROUS,               // 90-95',
    '    OD_URINE,                    // 96-00',
    '    OD_COUNT',
    '};',
    '',
    'inline Odor odorFor(int r) {',
    '    if (r <= 0)   r = 100;',
    '    if (r > 100)  r = 100;',
    '    if (r <= 3)   return OD_ACRID;',
    '    if (r <= 5)   return OD_CHLORINE;',
    '    if (r <= 39)  return OD_DANK_MOULDY;',
    '    if (r <= 49)  return OD_EARTHY;',
    '    if (r <= 57)  return OD_MANURE;',
    '    if (r <= 61)  return OD_METALLIC;',
    '    if (r <= 65)  return OD_OZONE;',
    '    if (r <= 70)  return OD_PUTRID;',
    '    if (r <= 75)  return OD_ROTTING_VEGETATION;',
    '    if (r <= 77)  return OD_SALTY_WET;',
    '    if (r <= 82)  return OD_SMOKY;',
    '    if (r <= 89)  return OD_STALE_FETID;',
    '    if (r <= 95)  return OD_SULPHUROUS;',
    '    return OD_URINE;',
    '}',
    '',
    '// ---- AIR (p.219): 6 printed bands ----------------------------------------',
    'enum AirState {',
    '    AIR_CLEAR = 0,               // 01-70',
    '    AIR_FOGGY,                   // 71-80',
    '    AIR_FOGGY_NEAR_FLOOR,        // 81-88',
    '    AIR_HAZY_DUST,               // 89-90',
    '    AIR_HAZY_SMOKE,              // 91-98',
    '    AIR_MISTED,                  // 99-00',
    '    AIR_COUNT',
    '};',
    '',
    'inline AirState airStateFor(int r) {',
    '    if (r <= 0)   r = 100;',
    '    if (r > 100)  r = 100;',
    '    if (r <= 70)  return AIR_CLEAR;',
    '    if (r <= 80)  return AIR_FOGGY;',
    '    if (r <= 88)  return AIR_FOGGY_NEAR_FLOOR;',
    '    if (r <= 90)  return AIR_HAZY_DUST;',
    '    if (r <= 98)  return AIR_HAZY_SMOKE;',
    '    return AIR_MISTED;',
    '}',
    '',
    '// ---- GENERAL ITEMS (p.218): 54 printed bands ------------------------------',
    'enum GeneralItem {',
    '    GI_ARROW_BROKEN = 0,          // 01',
    '    GI_ASHES,                     // 02-04',
    '    GI_BONES,                     // 05-06',
    '    GI_BOTTLE_BROKEN,             // 07',
    '    GI_CHAIN_CORRODED,            // 08',
    '    GI_CLUB_SPLINTERED,           // 09',
    '    GI_COBWEBS,                   // 10-19',
    '    GI_COIN_COPPER_BENT,          // 20',
    '    GI_CRACKS_CEILING,            // 21-22',
    '    GI_CRACKS_FLOOR,              // 23-24',
    '    GI_CRACKS_WALL,               // 25-26',
    '    GI_DAGGER_HILT,               // 27',
    '    GI_DAMPNESS_CEILING,          // 28-29',
    '    GI_DAMPNESS_WALL,             // 30-33',
    '    GI_DRIPPING,                  // 34-40',
    '    GI_DRIED_BLOOD,               // 41',
    '    GI_DUNG,                      // 42-44',
    '    GI_DUST,                      // 45-49',
    '    GI_FLASK_CRACKED,             // 50',
    '    GI_FOOD_SCRAPS,               // 51',
    '    GI_FUNGI_COMMON,              // 52',
    '    GI_GUANO,                     // 53-55',
    '    GI_HAIR_FUR_BITS,            // 56',
    '    GI_HAMMER_HEAD_CRACKED,       // 57',
    '    GI_HELMET_DENTED,             // 58',
    '    GI_IRON_BAR_BENT,             // 59',
    '    GI_JAVELIN_HEAD_BLUNT,        // 60',
    '    GI_LEATHER_BOOT,              // 61',
    '    GI_LEAVES_TWIGS,              // 62-64',
    '    GI_MOLD,                      // 65-68',
    '    GI_PICK_HANDLE,               // 69',
    '    GI_POLE_BROKEN,               // 70',
    '    GI_POTTERY_SHARDS,            // 71',
    '    GI_RAGS,                      // 72-73',
    '    GI_ROPE_ROTTEN,               // 74',
    '    GI_RUBBLE_DIRT,               // 75-76',
    '    GI_SACK_TORN,                 // 77',
    '    GI_SLIMY_CEILING,             // 78',
    '    GI_SLIMY_FLOOR,               // 79',
    '    GI_SLIMY_WALL,                // 80',
    '    GI_SPIKE_RUSTED,              // 81',
    '    GI_STICKS,                    // 82-83',
    '    GI_STONES_SMALL,              // 84',
    '    GI_STRAW,                     // 85',
    '    GI_SWORD_BLADE_BROKEN,        // 86',
    '    GI_TEETH_SCATTERED,           // 87',
    '    GI_TORCH_STUB,                // 88',
    '    GI_WALL_SCRATCHINGS,          // 89',
    '    GI_WATER_SMALL_PUDDLE,        // 90-91',
    '    GI_WATER_LARGE_PUDDLE,        // 92-93',
    '    GI_WATER_TRICKLE,             // 94-95',
    '    GI_WAX_DRIPPINGS,             // 96',
    '    GI_WAX_BLOB,                  // 97',
    '    GI_WOOD_PIECES_ROTTING,       // 98-00',
    '    GI_COUNT',
    '};',
    '',
    'inline GeneralItem generalItemFor(int r) {',
    '    if (r <= 0)   r = 100;',
    '    if (r > 100)  r = 100;',
    '    if (r <= 1)   return GI_ARROW_BROKEN;',
    '    if (r <= 4)   return GI_ASHES;',
    '    if (r <= 6)   return GI_BONES;',
    '    if (r <= 7)   return GI_BOTTLE_BROKEN;',
    '    if (r <= 8)   return GI_CHAIN_CORRODED;',
    '    if (r <= 9)   return GI_CLUB_SPLINTERED;',
    '    if (r <= 19)  return GI_COBWEBS;',
    '    if (r <= 20)  return GI_COIN_COPPER_BENT;',
    '    if (r <= 22)  return GI_CRACKS_CEILING;',
    '    if (r <= 24)  return GI_CRACKS_FLOOR;',
    '    if (r <= 26)  return GI_CRACKS_WALL;',
    '    if (r <= 27)  return GI_DAGGER_HILT;',
    '    if (r <= 29)  return GI_DAMPNESS_CEILING;',
    '    if (r <= 33)  return GI_DAMPNESS_WALL;',
    '    if (r <= 40)  return GI_DRIPPING;',
    '    if (r <= 41)  return GI_DRIED_BLOOD;',
    '    if (r <= 44)  return GI_DUNG;',
    '    if (r <= 49)  return GI_DUST;',
    '    if (r <= 50)  return GI_FLASK_CRACKED;',
    '    if (r <= 51)  return GI_FOOD_SCRAPS;',
    '    if (r <= 52)  return GI_FUNGI_COMMON;',
    '    if (r <= 55)  return GI_GUANO;',
    '    if (r <= 56)  return GI_HAIR_FUR_BITS;',
    '    if (r <= 57)  return GI_HAMMER_HEAD_CRACKED;',
    '    if (r <= 58)  return GI_HELMET_DENTED;',
    '    if (r <= 59)  return GI_IRON_BAR_BENT;',
    '    if (r <= 60)  return GI_JAVELIN_HEAD_BLUNT;',
    '    if (r <= 61)  return GI_LEATHER_BOOT;',
    '    if (r <= 64)  return GI_LEAVES_TWIGS;',
    '    if (r <= 68)  return GI_MOLD;',
    '    if (r <= 69)  return GI_PICK_HANDLE;',
    '    if (r <= 70)  return GI_POLE_BROKEN;',
    '    if (r <= 71)  return GI_POTTERY_SHARDS;',
    '    if (r <= 73)  return GI_RAGS;',
    '    if (r <= 74)  return GI_ROPE_ROTTEN;',
    '    if (r <= 76)  return GI_RUBBLE_DIRT;',
    '    if (r <= 77)  return GI_SACK_TORN;',
    '    if (r <= 78)  return GI_SLIMY_CEILING;',
    '    if (r <= 79)  return GI_SLIMY_FLOOR;',
    '    if (r <= 80)  return GI_SLIMY_WALL;',
    '    if (r <= 81)  return GI_SPIKE_RUSTED;',
    '    if (r <= 83)  return GI_STICKS;',
    '    if (r <= 84)  return GI_STONES_SMALL;',
    '    if (r <= 85)  return GI_STRAW;',
    '    if (r <= 86)  return GI_SWORD_BLADE_BROKEN;',
    '    if (r <= 87)  return GI_TEETH_SCATTERED;',
    '    if (r <= 88)  return GI_TORCH_STUB;',
    '    if (r <= 89)  return GI_WALL_SCRATCHINGS;',
    '    if (r <= 91)  return GI_WATER_SMALL_PUDDLE;',
    '    if (r <= 93)  return GI_WATER_LARGE_PUDDLE;',
    '    if (r <= 95)  return GI_WATER_TRICKLE;',
    '    if (r <= 96)  return GI_WAX_DRIPPINGS;',
    '    if (r <= 97)  return GI_WAX_BLOB;',
    '    return GI_WOOD_PIECES_ROTTING;',
    '}',
    '',
    '// ---- UNEXPLAINED SOUNDS (p.219): 58 printed bands --------------------------',
    'enum SoundKind {',
    '    SK_BANG_SLAM = 0,            // 01-05',
    '    SK_BELLOW,                    // 06',
    '    SK_BONG,                      // 07',
    '    SK_BUZZING,                   // 08',
    '    SK_CHANTING,                  // 09-10',
    '    SK_CHIMING,                   // 11',
    '    SK_CHIRPING,                  // 12',
    '    SK_CLANKING,                  // 13',
    '    SK_CLASHING,                  // 14',
    '    SK_CLICKING,                  // 15',
    '    SK_COUGHING,                  // 16',
    '    SK_CREAKING,                  // 17-18',
    '    SK_DRUMMING,                  // 19',
    '    SK_FOOTSTEPS_AHEAD,           // 20-23',
    '    SK_FOOTSTEPS_APPROACHING,     // 24-26',
    '    SK_FOOTSTEPS_BEHIND,          // 27-29',
    '    SK_FOOTSTEPS_RECEDING,        // 30-31',
    '    SK_FOOTSTEPS_SIDE,            // 32-33',
    '    SK_GIGGLING,                  // 34-35',
    '    SK_GONG,                      // 36',
    '    SK_GRATING,                   // 37-39',
    '    SK_GROANING,                  // 40-41',
    '    SK_GRUNTING,                  // 42',
    '    SK_HISSING,                   // 43-44',
    '    SK_HOOTING,                   // 45',
    '    SK_HORN,                      // 46',
    '    SK_HOWLING,                   // 47',
    '    SK_HUMMING,                   // 48',
    '    SK_JINGLING,                  // 49',
    '    SK_KNOCKING,                  // 50-53',
    '    SK_LAUGHTER,                  // 54-55',
    '    SK_MOANING,                   // 56-57',
    '    SK_MURMURING,                 // 58-60',
    '    SK_MUSIC,                     // 61',
    '    SK_RATTLING,                  // 62',
    '    SK_RINGING,                   // 63',
    '    SK_ROAR,                      // 64',
    '    SK_RUSTLING,                  // 65-68',
    '    SK_SCRATCHING,                // 69-72',
    '    SK_SCREAMING,                 // 73-74',
    '    SK_SCUTTLING,                 // 75-77',
    '    SK_SHUFFLING,                 // 78',
    '    SK_SLITHERING,                // 79-80',
    '    SK_SNAPPING,                  // 81',
    '    SK_SNEEZING,                  // 82',
    '    SK_SOBBING,                   // 83',
    '    SK_SPLASHING,                 // 84',
    '    SK_SPLINTERING,               // 85',
    '    SK_SQUEAKING,                 // 86-87',
    '    SK_SQUEALING,                 // 88',
    '    SK_TAPPING,                   // 89-90',
    '    SK_THUD,                      // 91-92',
    '    SK_THUMPING,                  // 93-94',
    '    SK_TINKLING,                  // 95',
    '    SK_TWANGING,                  // 96',
    '    SK_WHINING,                   // 97',
    '    SK_WHISPERING,                // 98',
    '    SK_WHISTLING,                 // 99-00',
    '    SK_COUNT',
    '};',
    '',
    'inline SoundKind soundFor(int r) {',
    '    if (r <= 0)   r = 100;',
    '    if (r > 100)  r = 100;',
    '    if (r <= 5)   return SK_BANG_SLAM;',
    '    if (r <= 6)   return SK_BELLOW;',
    '    if (r <= 7)   return SK_BONG;',
    '    if (r <= 8)   return SK_BUZZING;',
    '    if (r <= 10)  return SK_CHANTING;',
    '    if (r <= 11)  return SK_CHIMING;',
    '    if (r <= 12)  return SK_CHIRPING;',
    '    if (r <= 13)  return SK_CLANKING;',
    '    if (r <= 14)  return SK_CLASHING;',
    '    if (r <= 15)  return SK_CLICKING;',
    '    if (r <= 16)  return SK_COUGHING;',
    '    if (r <= 18)  return SK_CREAKING;',
    '    if (r <= 19)  return SK_DRUMMING;',
    '    if (r <= 23)  return SK_FOOTSTEPS_AHEAD;',
    '    if (r <= 26)  return SK_FOOTSTEPS_APPROACHING;',
    '    if (r <= 29)  return SK_FOOTSTEPS_BEHIND;',
    '    if (r <= 31)  return SK_FOOTSTEPS_RECEDING;',
    '    if (r <= 33)  return SK_FOOTSTEPS_SIDE;',
    '    if (r <= 35)  return SK_GIGGLING;',
    '    if (r <= 36)  return SK_GONG;',
    '    if (r <= 39)  return SK_GRATING;',
    '    if (r <= 41)  return SK_GROANING;',
    '    if (r <= 42)  return SK_GRUNTING;',
    '    if (r <= 44)  return SK_HISSING;',
    '    if (r <= 45)  return SK_HOOTING;',
    '    if (r <= 46)  return SK_HORN;',
    '    if (r <= 47)  return SK_HOWLING;',
    '    if (r <= 48)  return SK_HUMMING;',
    '    if (r <= 49)  return SK_JINGLING;',
    '    if (r <= 53)  return SK_KNOCKING;',
    '    if (r <= 55)  return SK_LAUGHTER;',
    '    if (r <= 57)  return SK_MOANING;',
    '    if (r <= 60)  return SK_MURMURING;',
    '    if (r <= 61)  return SK_MUSIC;',
    '    if (r <= 62)  return SK_RATTLING;',
    '    if (r <= 63)  return SK_RINGING;',
    '    if (r <= 64)  return SK_ROAR;',
    '    if (r <= 68)  return SK_RUSTLING;',
    '    if (r <= 72)  return SK_SCRATCHING;',
    '    if (r <= 74)  return SK_SCREAMING;',
    '    if (r <= 77)  return SK_SCUTTLING;',
    '    if (r <= 78)  return SK_SHUFFLING;',
    '    if (r <= 80)  return SK_SLITHERING;',
    '    if (r <= 81)  return SK_SNAPPING;',
    '    if (r <= 82)  return SK_SNEEZING;',
    '    if (r <= 83)  return SK_SOBBING;',
    '    if (r <= 84)  return SK_SPLASHING;',
    '    if (r <= 85)  return SK_SPLINTERING;',
    '    if (r <= 87)  return SK_SQUEAKING;',
    '    if (r <= 88)  return SK_SQUEALING;',
    '    if (r <= 90)  return SK_TAPPING;',
    '    if (r <= 92)  return SK_THUD;',
    '    if (r <= 94)  return SK_THUMPING;',
    '    if (r <= 95)  return SK_TINKLING;',
    '    if (r <= 96)  return SK_TWANGING;',
    '    if (r <= 97)  return SK_WHINING;',
    '    if (r <= 98)  return SK_WHISPERING;',
    '    return SK_WHISTLING;',
    '}',
    '',
    '} // namespace appendixi',
    '} // namespace dm',
])

# ---- (2) regtest.cpp: the include ----
inc_old = NL.join([
    '#include "dm/appendixp.h"  // R147: pp.225-226 Appendix P tables',
])
inc_new = NL.join([
    '#include "dm/appendixp.h"  // R147: pp.225-226 Appendix P tables',
    '#include "dm/appendixi.h"  // R150: pp.217-220 Appendix I dressing',
])

# ---- (3) regtest.cpp: the R150 audit block ----
aud_old = NL.join([
    '        printf("R147 Appendix P audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
])
aud_new = NL.join([
    '        printf("R147 Appendix P audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R150: appendix I dressing audit ------------------------------',
    '    // The DMG pp.217-220 dressing lists (Appendix I), pinned',
    '    // band-by-band in dm/appendixi.h: air currents, odors,',
    '    // air, general items and unexplained sounds. Every band',
    '    // edge pinned both ways, the house discipline: at the',
    '    // edge the kind, one past the edge the next. The 00 fold',
    '    // and the clamp are pinned too. Count corrections, named',
    '    // in the header: the R149 box said 16/100/68 bands; the',
    '    // prints read 14/54/58 (odors 14 and air 6 were right).',
    '    {',
    '        int bad = 0;',
    '        namespace AI = dm::appendixi;',
    '        if (AI::AC_COUNT != 14 || AI::OD_COUNT != 14 ||',
    '            AI::AIR_COUNT != 6 || AI::GI_COUNT != 54 ||',
    '            AI::SK_COUNT != 58) ++bad;',
    '        // air currents: 14 bands, edges both ways',
    '        static const struct { int lo, hi; AI::AirCurrent k; }',
    '            kAC[] = {',
    '            {  1,  5, AI::AC_BREEZE_SLIGHT },',
    '            {  6, 10, AI::AC_BREEZE_SLIGHT_DAMP },',
    '            { 11, 12, AI::AC_BREEZE_GUSTING },',
    '            { 13, 18, AI::AC_COLD_CURRENT },',
    '            { 19, 20, AI::AC_DOWNDRAFT_SLIGHT },',
    '            { 21, 22, AI::AC_DOWNDRAFT_STRONG },',
    '            { 23, 69, AI::AC_STILL },',
    '            { 70, 75, AI::AC_STILL_VERY_CHILL },',
    '            { 76, 85, AI::AC_STILL_WARM },',
    '            { 86, 87, AI::AC_UPDRAFT_SLIGHT },',
    '            { 88, 89, AI::AC_UPDRAFT_STRONG },',
    '            { 90, 93, AI::AC_WIND_STRONG },',
    '            { 94, 95, AI::AC_WIND_STRONG_GUSTING },',
    '            { 96,100, AI::AC_WIND_STRONG_MOANING },',
    '        };',
    '        for (size_t i = 0; i < sizeof(kAC)/sizeof(kAC[0]); ++i) {',
    '            if (AI::airCurrentFor(kAC[i].lo) != kAC[i].k) ++bad;',
    '            if (AI::airCurrentFor(kAC[i].hi) != kAC[i].k) ++bad;',
    '            if (i + 1 < sizeof(kAC)/sizeof(kAC[0]) &&',
    '                AI::airCurrentFor(kAC[i].hi + 1) != kAC[i+1].k)',
    '                ++bad;',
    '        }',
    '        if (AI::airCurrentFor(0) != AI::AC_WIND_STRONG_MOANING)',
    '            ++bad;   // 00 folds to 100',
    '        // odors: 14 bands',
    '        static const struct { int lo, hi; AI::Odor k; }',
    '            kOD[] = {',
    '            {  1,  3, AI::OD_ACRID },',
    '            {  4,  5, AI::OD_CHLORINE },',
    '            {  6, 39, AI::OD_DANK_MOULDY },',
    '            { 40, 49, AI::OD_EARTHY },',
    '            { 50, 57, AI::OD_MANURE },',
    '            { 58, 61, AI::OD_METALLIC },',
    '            { 62, 65, AI::OD_OZONE },',
    '            { 66, 70, AI::OD_PUTRID },',
    '            { 71, 75, AI::OD_ROTTING_VEGETATION },',
    '            { 76, 77, AI::OD_SALTY_WET },',
    '            { 78, 82, AI::OD_SMOKY },',
    '            { 83, 89, AI::OD_STALE_FETID },',
    '            { 90, 95, AI::OD_SULPHUROUS },',
    '            { 96,100, AI::OD_URINE },',
    '        };',
    '        for (size_t i = 0; i < sizeof(kOD)/sizeof(kOD[0]); ++i) {',
    '            if (AI::odorFor(kOD[i].lo) != kOD[i].k) ++bad;',
    '            if (AI::odorFor(kOD[i].hi) != kOD[i].k) ++bad;',
    '            if (i + 1 < sizeof(kOD)/sizeof(kOD[0]) &&',
    '                AI::odorFor(kOD[i].hi + 1) != kOD[i+1].k) ++bad;',
    '        }',
    '        if (AI::odorFor(0) != AI::OD_URINE) ++bad;',
    '        // air: 6 bands',
    '        static const struct { int lo, hi; AI::AirState k; }',
    '            kAIR[] = {',
    '            {  1, 70, AI::AIR_CLEAR },',
    '            { 71, 80, AI::AIR_FOGGY },',
    '            { 81, 88, AI::AIR_FOGGY_NEAR_FLOOR },',
    '            { 89, 90, AI::AIR_HAZY_DUST },',
    '            { 91, 98, AI::AIR_HAZY_SMOKE },',
    '            { 99,100, AI::AIR_MISTED },',
    '        };',
    '        for (size_t i = 0; i < sizeof(kAIR)/sizeof(kAIR[0]); ++i) {',
    '            if (AI::airStateFor(kAIR[i].lo) != kAIR[i].k) ++bad;',
    '            if (AI::airStateFor(kAIR[i].hi) != kAIR[i].k) ++bad;',
    '            if (i + 1 < sizeof(kAIR)/sizeof(kAIR[0]) &&',
    '                AI::airStateFor(kAIR[i].hi + 1) != kAIR[i+1].k)',
    '                ++bad;',
    '        }',
    '        if (AI::airStateFor(0) != AI::AIR_MISTED) ++bad;',
    '        // general items: 54 bands',
    '        static const struct { int lo, hi; AI::GeneralItem k; }',
    '            kGI[] = {',
    '            {  1,  1, AI::GI_ARROW_BROKEN },',
    '            {  2,  4, AI::GI_ASHES },',
    '            {  5,  6, AI::GI_BONES },',
    '            {  7,  7, AI::GI_BOTTLE_BROKEN },',
    '            {  8,  8, AI::GI_CHAIN_CORRODED },',
    '            {  9,  9, AI::GI_CLUB_SPLINTERED },',
    '            { 10, 19, AI::GI_COBWEBS },',
    '            { 20, 20, AI::GI_COIN_COPPER_BENT },',
    '            { 21, 22, AI::GI_CRACKS_CEILING },',
    '            { 23, 24, AI::GI_CRACKS_FLOOR },',
    '            { 25, 26, AI::GI_CRACKS_WALL },',
    '            { 27, 27, AI::GI_DAGGER_HILT },',
    '            { 28, 29, AI::GI_DAMPNESS_CEILING },',
    '            { 30, 33, AI::GI_DAMPNESS_WALL },',
    '            { 34, 40, AI::GI_DRIPPING },',
    '            { 41, 41, AI::GI_DRIED_BLOOD },',
    '            { 42, 44, AI::GI_DUNG },',
    '            { 45, 49, AI::GI_DUST },',
    '            { 50, 50, AI::GI_FLASK_CRACKED },',
    '            { 51, 51, AI::GI_FOOD_SCRAPS },',
    '            { 52, 52, AI::GI_FUNGI_COMMON },',
    '            { 53, 55, AI::GI_GUANO },',
    '            { 56, 56, AI::GI_HAIR_FUR_BITS },',
    '            { 57, 57, AI::GI_HAMMER_HEAD_CRACKED },',
    '            { 58, 58, AI::GI_HELMET_DENTED },',
    '            { 59, 59, AI::GI_IRON_BAR_BENT },',
    '            { 60, 60, AI::GI_JAVELIN_HEAD_BLUNT },',
    '            { 61, 61, AI::GI_LEATHER_BOOT },',
    '            { 62, 64, AI::GI_LEAVES_TWIGS },',
    '            { 65, 68, AI::GI_MOLD },',
    '            { 69, 69, AI::GI_PICK_HANDLE },',
    '            { 70, 70, AI::GI_POLE_BROKEN },',
    '            { 71, 71, AI::GI_POTTERY_SHARDS },',
    '            { 72, 73, AI::GI_RAGS },',
    '            { 74, 74, AI::GI_ROPE_ROTTEN },',
    '            { 75, 76, AI::GI_RUBBLE_DIRT },',
    '            { 77, 77, AI::GI_SACK_TORN },',
    '            { 78, 78, AI::GI_SLIMY_CEILING },',
    '            { 79, 79, AI::GI_SLIMY_FLOOR },',
    '            { 80, 80, AI::GI_SLIMY_WALL },',
    '            { 81, 81, AI::GI_SPIKE_RUSTED },',
    '            { 82, 83, AI::GI_STICKS },',
    '            { 84, 84, AI::GI_STONES_SMALL },',
    '            { 85, 85, AI::GI_STRAW },',
    '            { 86, 86, AI::GI_SWORD_BLADE_BROKEN },',
    '            { 87, 87, AI::GI_TEETH_SCATTERED },',
    '            { 88, 88, AI::GI_TORCH_STUB },',
    '            { 89, 89, AI::GI_WALL_SCRATCHINGS },',
    '            { 90, 91, AI::GI_WATER_SMALL_PUDDLE },',
    '            { 92, 93, AI::GI_WATER_LARGE_PUDDLE },',
    '            { 94, 95, AI::GI_WATER_TRICKLE },',
    '            { 96, 96, AI::GI_WAX_DRIPPINGS },',
    '            { 97, 97, AI::GI_WAX_BLOB },',
    '            { 98,100, AI::GI_WOOD_PIECES_ROTTING },',
    '        };',
    '        for (size_t i = 0; i < sizeof(kGI)/sizeof(kGI[0]); ++i) {',
    '            if (AI::generalItemFor(kGI[i].lo) != kGI[i].k) ++bad;',
    '            if (AI::generalItemFor(kGI[i].hi) != kGI[i].k) ++bad;',
    '            if (i + 1 < sizeof(kGI)/sizeof(kGI[0]) &&',
    '                AI::generalItemFor(kGI[i].hi + 1) != kGI[i+1].k)',
    '                ++bad;',
    '        }',
    '        if (AI::generalItemFor(0) != AI::GI_WOOD_PIECES_ROTTING)',
    '            ++bad;',
    '        // unexplained sounds: 58 bands',
    '        static const struct { int lo, hi; AI::SoundKind k; }',
    '            kSK[] = {',
    '            {  1,  5, AI::SK_BANG_SLAM },',
    '            {  6,  6, AI::SK_BELLOW },',
    '            {  7,  7, AI::SK_BONG },',
    '            {  8,  8, AI::SK_BUZZING },',
    '            {  9, 10, AI::SK_CHANTING },',
    '            { 11, 11, AI::SK_CHIMING },',
    '            { 12, 12, AI::SK_CHIRPING },',
    '            { 13, 13, AI::SK_CLANKING },',
    '            { 14, 14, AI::SK_CLASHING },',
    '            { 15, 15, AI::SK_CLICKING },',
    '            { 16, 16, AI::SK_COUGHING },',
    '            { 17, 18, AI::SK_CREAKING },',
    '            { 19, 19, AI::SK_DRUMMING },',
    '            { 20, 23, AI::SK_FOOTSTEPS_AHEAD },',
    '            { 24, 26, AI::SK_FOOTSTEPS_APPROACHING },',
    '            { 27, 29, AI::SK_FOOTSTEPS_BEHIND },',
    '            { 30, 31, AI::SK_FOOTSTEPS_RECEDING },',
    '            { 32, 33, AI::SK_FOOTSTEPS_SIDE },',
    '            { 34, 35, AI::SK_GIGGLING },',
    '            { 36, 36, AI::SK_GONG },',
    '            { 37, 39, AI::SK_GRATING },',
    '            { 40, 41, AI::SK_GROANING },',
    '            { 42, 42, AI::SK_GRUNTING },',
    '            { 43, 44, AI::SK_HISSING },',
    '            { 45, 45, AI::SK_HOOTING },',
    '            { 46, 46, AI::SK_HORN },',
    '            { 47, 47, AI::SK_HOWLING },',
    '            { 48, 48, AI::SK_HUMMING },',
    '            { 49, 49, AI::SK_JINGLING },',
    '            { 50, 53, AI::SK_KNOCKING },',
    '            { 54, 55, AI::SK_LAUGHTER },',
    '            { 56, 57, AI::SK_MOANING },',
    '            { 58, 60, AI::SK_MURMURING },',
    '            { 61, 61, AI::SK_MUSIC },',
    '            { 62, 62, AI::SK_RATTLING },',
    '            { 63, 63, AI::SK_RINGING },',
    '            { 64, 64, AI::SK_ROAR },',
    '            { 65, 68, AI::SK_RUSTLING },',
    '            { 69, 72, AI::SK_SCRATCHING },',
    '            { 73, 74, AI::SK_SCREAMING },',
    '            { 75, 77, AI::SK_SCUTTLING },',
    '            { 78, 78, AI::SK_SHUFFLING },',
    '            { 79, 80, AI::SK_SLITHERING },',
    '            { 81, 81, AI::SK_SNAPPING },',
    '            { 82, 82, AI::SK_SNEEZING },',
    '            { 83, 83, AI::SK_SOBBING },',
    '            { 84, 84, AI::SK_SPLASHING },',
    '            { 85, 85, AI::SK_SPLINTERING },',
    '            { 86, 87, AI::SK_SQUEAKING },',
    '            { 88, 88, AI::SK_SQUEALING },',
    '            { 89, 90, AI::SK_TAPPING },',
    '            { 91, 92, AI::SK_THUD },',
    '            { 93, 94, AI::SK_THUMPING },',
    '            { 95, 95, AI::SK_TINKLING },',
    '            { 96, 96, AI::SK_TWANGING },',
    '            { 97, 97, AI::SK_WHINING },',
    '            { 98, 98, AI::SK_WHISPERING },',
    '            { 99,100, AI::SK_WHISTLING },',
    '        };',
    '        for (size_t i = 0; i < sizeof(kSK)/sizeof(kSK[0]); ++i) {',
    '            if (AI::soundFor(kSK[i].lo) != kSK[i].k) ++bad;',
    '            if (AI::soundFor(kSK[i].hi) != kSK[i].k) ++bad;',
    '            if (i + 1 < sizeof(kSK)/sizeof(kSK[0]) &&',
    '                AI::soundFor(kSK[i].hi + 1) != kSK[i+1].k) ++bad;',
    '        }',
    '        if (AI::soundFor(0) != AI::SK_WHISTLING) ++bad;',
    '        printf("R150 appendix I dressing audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
])
# ---- (4) gap report: the R150 round note ----
gap_head_old = NL.join([
    'site has gone dark - the fresh uploads are the',
    'last standing source. Census 67.',
    '',
    'Categories:',
])
gap_head_new = NL.join([
    'site has gone dark - the fresh uploads are the',
    'last standing source. Census 67.',
    'R150 PINNED the Appendix I dressing lists (the',
    'R149 bycatch): dm/appendixi.h, the appendixa.h',
    'pattern - the five band lists (air currents,',
    'odors, air, general items, unexplained sounds)',
    'pinned edge for edge, with the R149 box band',
    'counts corrected (14/54/58, not 16/100/68; the',
    'band content was right). Census 68.',
    '',
    'Categories:',
])
# ---- (5) gap report: the Appendix I box ----
gap_box_old = NL.join([
    '- [ ] **Appendix I, dungeon dressing (pp.219-221)** -',
    '      named R149 from the fresh read (a book-verify',
    '      pass bycatch, missed by the R148 sweep): the',
    '      printed lists are unpinned - air currents (16',
    '      bands, breeze, slight 01-05 through wind,',
    '      strong, moaning 96-00), odors (14, acrid 01-03',
    '      through urine 96-00), air (6, clear 01-70',
    '      through misted 99-00), general items (100,',
    '      arrow, broken 01 through wood pieces, rotting',
    '      98-00) and unexplained sounds (68, bang, slam',
    '      01-05 through whistling 99-00). The fresh',
    '      upload and a clean book read agree cell for',
    '      cell - the data is ready; the repo pins',
    '      Appendix A dressing only (R124, the',
    '      random-dungeon appendix).',
])
gap_box_new = NL.join([
    '- [x] **Appendix I, dungeon dressing (pp.219-221)** -',
    '      PINNED R150: dm/appendixi.h, the appendixa.h',
    '      pattern (pure data, header-only, no caller yet;',
    '      the audit is the regtest.cpp R150 block). The',
    '      five band lists pinned edge for edge: air',
    '      currents, odors, air, general items and',
    '      unexplained sounds. COUNT CORRECTIONS (the',
    '      R149 box' + AP + 's own slips, named in the header): the',
    '      prints read 14 air-current bands (not 16), 54',
    '      general-item bands (not 100) and 58 sound bands',
    '      (not 68); odors (14) and air (6) were right -',
    '      the band CONTENT the box quoted was correct all',
    '      along. The selection-aid lists the book prints',
    '      alongside them (furnishings, torture chamber,',
    '      magic-user and religious furnishings, container',
    '      contents, misc items, jewelry, foodstuffs) are',
    '      choose-as-desired aids, not band tables, and',
    '      stay unpinned (named).',
])
# ---- run ----
patch_new("dm/appendixi.h", appendixi_h, "NEW dm/appendixi.h")
assert len(applied) + len(already) == 1
patch("regtest.cpp", inc_old, inc_new,
      "regtest.cpp: appendixi include",
      marker='#include "dm/appendixi.h"')
assert len(applied) + len(already) == 2
patch("regtest.cpp", aud_old, aud_new,
      "regtest.cpp: R150 appendix I dressing audit",
      marker="R150 appendix I dressing audit")
assert len(applied) + len(already) == 3
patch("tools/dmg_gap_report.md", gap_head_old, gap_head_new,
      "gap report: R150 header note",
      marker="R150 PINNED the Appendix I dressing lists")
assert len(applied) + len(already) == 4
patch("tools/dmg_gap_report.md", gap_box_old, gap_box_new,
      "gap report: Appendix I box closed",
      marker="PINNED R150: dm/appendixi.h")
assert len(applied) + len(already) == 5
# ---- R150 fails/tail ----
if fails:
    print("R150 splice: FAIL - " + str(len(fails))
          + " patch(es) failed:")
    for f in fails:
        print("  " + f)
    sys.exit(1)
if len(applied) + len(already) != 5:
    print("R150 splice: FAIL - expected 5 patches, counted "
          + str(len(applied) + len(already))
          + " (a truncated paste?)")
    sys.exit(1)
if already and not applied:
    print("R150 splice: ALL OK (applied 0, already "
          + str(len(already)) + ")")
else:
    print("R150 splice: ALL OK (applied " + str(len(applied))
          + ", already " + str(len(already)) + ")")
print("R150 note: five patches; expect the battery to gain")
print("one audit line - AUDIT CENSUS 68; commit: R150:")
print("Appendix I dressing pinned - air currents, odors,")
print("air, general items, sounds (census 68)")
