# tools/r172_splice.py - R172, 6 patches: Appendix J (DMG
# p.220) - herbs, spices and medicinal vegetables. A new
# header-only layer, rules/herbs.h (the grenade.h pattern:
# the caller rolls and selects; a support table for the
# potion, scroll ink and magic item flavor).
#
# (1) rules/herbs.h: the alphabetical plant and uses table,
#     171 rows, abscess root (sweet root) through white
#     bryony (mandragora), cell by cell - including the
#     10 rows the book leaves with unknown uses (bay leaf,
#     cardamom, chervil, garden burnet, lotus, peppermint,
#     poppy, spearmint, tarragon, turmeric), the one
#     cross-reference row (blueberry - see bilberry) and
#     the restored turnip row (mouth disease, throat) that
#     the compilation drops; the intro prose (hundreds of
#     vegetable flavorings and seasonings reputed
#     medicinal and/or magic; not within the scope of this
#     work to detail all; an alphabetical listing with one
#     or two comments; the dedicated herbologist pursues
#     scholarly texts) and the closing prose (use the list
#     as a guide for potions, scroll inks and other magic
#     items; add to or delete as desired; reputed folk
#     uses as regards magic are the DM purview).
#     (2) the regtest include. (3) the R172 audit: all 171
#     rows mirrored and walked, the unknowns count, the
#     cross-reference, the prose - CENSUS 90. (4) the gap
#     report census note. (5) the gap report OUT
#     amendment. (6) the gap report box.
#
# JUDGMENTs: (a) the table structure follows the
# 1eonline.info compilation (the repo-trusted source, the
# R146 precedent), cell-verified against the book upload
# wherever the upload is legible, with per-run cell-count
# arithmetic used to detect compilation omissions.
# (b) print spellings win where they differ (abscess,
# artichoke juice, cocklebur, anesthetic, dysentery,
# hemorrhaging, melancholia, varicosities, abscesses,
# repellent; celery = liver functions, tonic, stimulant;
# saffron = respiratory infections; fennel = much, much
# more). (c) the compilation drops the turnip row and
# truncates the celery uses - both restored from the
# print. (d) the benzoin anti-septic line break is read
# as antiseptic. (e) the compilation artifacts are
# normalized (the belladonna stray parenthesis, the leek
# and rose doodles, the poppy wikipedia aside, the sage
# trailing comma and star). (f) Appendix J was OUT of
# scope by design until R172 reversed it
# (user-authorized).
#
# Idempotent: safe to run twice; a silent run means the
# paste was truncated - this tail ALWAYS prints. An assert
# follows EVERY patch (the R142 lesson). ZERO backslash
# characters in this file; no content string embeds a
# literal apostrophe (the R133b + R147 lessons).
# Commit: "R172: appendix J herbs spices and medicinal
# vegetables pinned - the p.220 plant and uses table
# (census 90)"
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NL = chr(10)
BS = chr(92)
Q = chr(39)
applied, already, fails = [], [], []

def rd(p):
    with open(os.path.join(ROOT, p), encoding="latin-1") as f:
        return f.read()

def wr(p, s):
    with open(os.path.join(ROOT, p), "w", encoding="latin-1") as f:
        f.write(s)

def patch(p, old, new, tag, marker):
    s = rd(p)
    if marker in s:
        already.append(tag)
        return
    n = s.count(old)
    if n != 1:
        fails.append(tag + ": anchor count " + str(n)
                     + " (expected 1)")
        return
    wr(p, s.replace(old, new))
    applied.append(tag)

def create(p, text, tag, marker):
    fp = os.path.join(ROOT, p)
    if os.path.exists(fp):
        s = rd(p)
        if marker in s:
            already.append(tag)
            return
        fails.append(tag + ": exists without the marker")
        return
    wr(p, text)
    applied.append(tag)


# ---- patch 1: rules/herbs.h (new file) ----
p1_text = NL.join([
    '// ====================================================================',
    '// Adnd1 - rules/herbs.h',
    '// R172: Appendix J (DMG p.220) - herbs, spices and',
    '// medicinal vegetables: the alphabetical plant and',
    '// uses table, 171 rows.',
    '//',
    '// Pure data, header-only (the grenade.h pattern:',
    '// the caller rolls and selects; a support table for',
    '// the potion, scroll ink and magic item flavor).',
    '//',
    '// JUDGMENTs: the table structure follows the',
    '// 1eonline.info compilation (the repo-trusted source,',
    '// the R146 precedent), cell-verified against the book',
    '// upload wherever the upload is legible, with per-run',
    '// cell-count arithmetic used to detect compilation',
    '// omissions; print spellings win where they differ;',
    '// the compilation drops the turnip row and truncates',
    '// the celery uses - both restored from the print; the',
    '// benzoin anti-septic line break is read as',
    '// antiseptic; the compilation artifacts (the belladonna',
    '// stray parenthesis, the leek and rose doodles, the',
    '// poppy wikipedia aside, the sage trailing comma and',
    '// star) are normalized; Appendix J was OUT of scope by',
    '// design until R172 reversed it (user-authorized).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    '// ----------------------------------------------------------------------------',
    '// Appendix J: the plant and uses table (p.220)',
    '// ----------------------------------------------------------------------------',
    '',
    'struct HerbRow {',
    '    const char* plant;',
    '    const char* uses;  // "?" where the book leaves it unknown',
    '};',
    '',
    'inline int herbsRowCount() { return 171; }',
    '',
    '// The rows: the uses and/or powers column exactly as',
    '// printed. The blueberry row is a printed cross-reference',
    '// to bilberry with an empty uses cell.',
    'inline const HerbRow& herbsRow(int i) {',
    '    static const HerbRow k[171] = {',
'        { "abscess root (sweet root)", "respiratory disorders" },',
'        { "acacia (Gum Arabic)", "tissue repair" },',
'        { "aconite (monkshood, wolfsbane, friar' + Q + 's cap, etc.)", "sedative/drives off werewolves" },',
'        { "acorn", "tissue hardening" },',
'        { "adder' + Q + 's tongue", "emetic, emollient" },',
'        { "adrue", "anti-vomiting, sedative" },',
'        { "agar-agar (jelly)", "anti-inflammation, nutrient" },',
'        { "agaric", "astringent, purgative" },',
'        { "agrimony (cocklebur, stickwort)", "muscle toner, diuretic" },',
'        { "alder", "anti-inflammation, tonic" },',
'        { "alkanet root", "emollient, antiseptic, wormer" },',
'        { "all-heal (wound-wort)", "antiseptic, anti-spasmodic" },',
'        { "almond milk/powder", "nutrient/emollient" },',
'        { "aloe (bitter aloe)", "bites, burns, laxative, tonic/insect repellent" },',
'        { "amaranth (red cockscomb, love-lies-bleeding)", "astringent, anti-hemorrhaging" },',
'        { "ammoniacum (Persian Gum)", "stimulant, respiratory aid" },',
'        { "angelica", "lungs, liver, spleen, vision, hearing" },',
'        { "anise", "antacid, digestion, coughing" },',
'        { "arbutus (mayflower)", "astringent, bladder infection" },',
'        { "areca nut (betel nut)", "astringent, tape wormer" },',
'        { "arenaria rubra (sandwort)", "diuretic, urinary diseases" },',
'        { "arrach (goosefoot)", "sedative (nervous tension or hysteria in particular)" },',
'        { "artichoke juice", "jaundice curative" },',
'        { "asafetida (gum asafetida, devil' + Q + 's dung, food of the gods)", "aphrodisiac, brain and nervous stimulant, tonic, many more" },',
'        { "asarabacca (hazelwort, wild nard)", "emetic, purgative" },',
'        { "ash (bark and leaves of)", "laxative, anti-inflammation, fever" },',
'        { "asparagus juice/root", "sedative, heart problems/anti-oxalic acid" },',
'        { "avens (colewort, herb bennet)", "astringent, anti-hemorrhaging, anti-weakness, tonic, more" },',
'        { "bael", "anti-inflammation, ulcers" },',
'        { "balm (sweet balm) leaves", "calms nerves, fevers" },',
'        { "balm of gilead", "nutrient, organ stimulant (general)" },',
'        { "balmony (bitter herb, snake head)", "tissue builder and strengthener, liver ailments, wormer" },',
'        { "barley", "nutrient (recuperative)" },',
'        { "basil", "nervous disorders" },',
'        { "bay leaf", "?" },',
'        { "beet", "organic cleanser" },',
'        { "belladonna (deadly nightshade, dwale, black cherry root)", "diuretic, sedative, pain reliever, anti-opiate, circulation, stimulant, poison/lycanthropy cure" },',
'        { "benne (sesam, sesame)", "respiratory disorders, eye infections, more" },',
'        { "benzoin (gum benzoin)", "expectorant, stimulant, antiseptic, wounds and sores" },',
'        { "berberis", "fevers" },',
'        { "beth root (lamb' + Q + 's quarters)", "astringent, coughs, tonic, anti-hemorrhaging, more" },',
'        { "bilberry (huckleberry, hurtleberry, whortleberry)", "anti-thirst, dropsy, typhoid, more" },',
'        { "birch (white birch)", "intestines and stomach, venereal diseases, skin conditions" },',
'        { "birthwort", "circulatory stimulant" },',
'        { "bistort (adderwort)", "astringent" },',
'        { "bittersweet (felonwort, scarlet berry, woody nightshade)", "abscesses, lymph infections, swelling and inflammation" },',
'        { "blackberry (dewberry)", "astringent, tonic, dysentery" },',
'        { "black currant", "diuretic, antiseptic, blood purifier" },',
'        { "black willow (pussy willow) bark", "astringent, antiseptic" },',
'        { "blueberry - see bilberry", "" },',
'        { "blue flag (flag lily, poison flag, water flag, water lily)", "diuretic, cathartic, blood purifier (vs. poison), wound healing, venereal disease, much more" },',
'        { "blue mallow (common mallow)", "coughs, colds" },',
'        { "boneset (thoughtwort)", "fevers, tonic, skin diseases" },',
'        { "borage", "coughs, lung infections" },',
'        { "box leaves", "tonic, blood purifier" },',
'        { "bryony", "paralysis, bruises" },',
'        { "bugle", "gastrointestinal disorders, hemorrhaging" },',
'        { "burdock", "laxative, tuberculosis, more" },',
'        { "butterbur", "fevers, urinary complaints" },',
'        { "cabbage juice", "ulcer and stomach treatment" },',
'        { "calotopis (mudar bark)", "skin leprosy, elephantiasis, more" },',
'        { "camphor (gum camphor)", "bruises, sprains, chills, fevers, cardiac stimulant" },',
'        { "caraway", "antacid, aids digestion" },',
'        { "cardamom", "?" },',
'        { "carrot juice and seeds", "tonic for improved health" },',
'        { "castor oil bush", "purgative, cathartic" },',
'        { "catnip", "colds, fevers, anti-spasmodic, hysteria" },',
'        { "cayenne", "stimulant" },',
'        { "celery", "liver functions, tonic, stimulant" },',
'        { "chamomile", "nervous conditions, ear and tooth aches" },',
'        { "chaulmoogra oil", "fevers, sedative, skin eruptions" },',
'        { "cherry gum", "respiratory infections/food substitute" },',
'        { "chervil", "?" },',
'        { "chives", "colds, general diseases/evil eye" },',
'        { "cinnamon", "disinfectant, nausea, preservative" },',
'        { "cleavers (goosegrass)", "fevers, circulation, blood purifier, wounds, liver disease" },',
'        { "clover", "tonic" },',
'        { "cloves", "anesthetic, circulation, germicide, disinfectant" },',
'        { "comfrey root (healing herb)", "colds, respiratory conditions, wounds, bone fractures, gangrene, much, much more" },',
'        { "coriander", "tonic" },',
'        { "couchgrass", "bladder and urinary infections" },',
'        { "cucumber", "inflammation" },',
'        { "cumin seed", "stimulant" },',
'        { "dandelion", "diuretic, purgative, tonic" },',
'        { "digitalis (dead men' + Q + 's bells, fairy bells, fairy cap, fairy fingers, foxglove, etc.)", "heart stimulant, tonic, kidney treatment (poison)" },',
'        { "dill", "nausea" },',
'        { "ergot (rye smut)", "hemorrhaging, venereal diseases" },',
'        { "eyebright", "astringent, eye infections" },',
'        { "fennel", "digestion, weight control, muscle tone, reflexes, vision, much, much more" },',
'        { "fenugreek", "stimulant" },',
'        { "fig", "demulcent" },',
'        { "figwort (scrofula plant, throatwort)", "abscesses, wounds, pain killer" },',
'        { "fireweed", "astringent, anti-spasmodic" },',
'        { "fluellin", "astringent, tissue strengthener" },',
'        { "garden burnet", "?" },',
'        { "garlic", "coughs, colds, blood purifier, detoxifier, kills parasites/wards off vampires" },',
'        { "gelsemium (wild woodbine)", "sedative, nerve tonic, fevers, more" },',
'        { "gentian (bitter root, felwort)", "tonic, fevers, anti-venom" },',
'        { "geranium (sweet geranium)", "alkalizer" },',
'        { "ginger", "stimulant, colds, cramps" },',
'        { "ginseng", "glandular stimulant, vision, dizziness, headaches, weakness" },',
'        { "goat' + Q + 's rue", "diuretic, wormer (vermifuge)" },',
'        { "grape juice", "blood fortifier" },',
'        { "hartstongue", "cough, liver, spleen, bladder" },',
'        { "hawthorn", "heart, arteries" },',
'        { "hedge mustard", "throat, lungs" },',
'        { "hellebore", "heart tonic (rootlets are poison)" },',
'        { "honeysuckle", "liver, spleen, respiratory disorders" },',
'        { "horehound, white", "coughs, pulmonary diseases, anti-venom" },',
'        { "horehound, black", "stimulant, wormer, hemorrhaging" },',
'        { "horseradish", "tonic, antiseptic, wormer" },',
'        { "hyssop", "respiratory ailments, jaundice, blood purifier, tonic, cuts and wounds, more" },',
'        { "ipecac", "dysentery, mouth infections, more" },',
'        { "irish moss", "coughs, scalds, burns" },',
'        { "jambul seed", "blood purifier, diabetes" },',
'        { "jewel weed (balsam weed, pale touch-me-not)", "diuretic, kidneys, skin growths, fungus, infections, liver" },',
'        { "juniper berry", "aphrodisiac, stimulant, disinfectant, venereal disease, more" },',
'        { "jurubera", "anemia" },',
'        { "kelp (seawrack)", "thyroid, heart, arteries, much more" },',
'        { "larkspur (knight' + Q + 's spur)", "external parasites" },',
'        { "leek", "same as chives" },',
'        { "lily-of-the-valley", "heart tonic" },',
'        { "lotus", "?" },',
'        { "lucerne (alfalfa)", "strength" },',
'        { "lycopodium (common club moss, fox tail, lamb' + Q + 's tail)", "wounds, lungs, kidneys, more" },',
'        { "mace", "stimulant" },',
'        { "marigold", "fevers, varicosities, eyes, heart" },',
'        { "marjoram", "melancholia, dizziness, brain disorders, toothaches" },',
'        { "masterwort", "stimulates organs, anti-spasmodic, more" },',
'        { "mistletoe", "convulsions, hysteria, narcotic, tonic, typhoid fever, heart" },',
'        { "muira-puama", "aphrodisiac" },',
'        { "mustard", "emetic, counter-irritant, colds, fevers" },',
'        { "nutmeg", "nausea, vomiting, diarrhea" },',
'        { "nux vomica (poison nut)", "stimulant, debility tonic" },',
'        { "onion", "poultice, colds (as chives)" },',
'        { "oregano", "germicide, pain killer" },',
'        { "paprika", "stimulant, poultice" },',
'        { "parsley", "blood purifier" },',
'        { "parsnip", "fevers" },',
'        { "peach seed", "fevers, blood tonic" },',
'        { "pepper, black", "sprains, neuritis" },',
'        { "peppermint", "?" },',
'        { "pitcher plant", "small pox preventative and cure, stomach, liver, kidneys" },',
'        { "plantain (ripple grass, waybread)", "minor wounds, stings, rashes" },',
'        { "pomegranate", "nerve sedative, wormer" },',
'        { "poppy", "?" },',
'        { "pumpkin seed", "virility, organ tonic" },',
'        { "quince", "eye disease, dysentery, skin disorders" },',
'        { "radish", "blood purifier, liver" },',
'        { "raspberry", "fevers, tonic" },',
'        { "rhubarb", "astringent, cathartic" },',
'        { "rose", "colds, fevers" },',
'        { "rosemary", "germicide, muscle tonic/drives off evil spirits" },',
'        { "saffron", "scarlet fever, measles, respiratory infections" },',
'        { "sage", "tonic, wounds" },',
'        { "sarsaparilla (china root, spikenard)", "system balance, blood purifier, venereal disease, many more" },',
'        { "scopolis", "nerve and muscle sedative, pain killer, coughs" },',
'        { "scullcap (madweed)", "nervous disorders, rabies" },',
'        { "senna", "purgative" },',
'        { "spearmint", "?" },',
'        { "strawberry", "vision, swelling and inflammation" },',
'        { "summer savory", "blood purifier, palsy" },',
'        { "tamarind", "infection, gangrene" },',
'        { "tansy", "tonic, narcotic, wormer" },',
'        { "tarragon", "?" },',
'        { "tea", "poison antidote" },',
'        { "thyme", "antiseptic, blood purifier" },',
'        { "turmeric", "?" },',
'        { "turnip", "mouth disease, throat" },',
'        { "watercress", "blood tonic (anemia)" },',
'        { "white bryony (mandragora)", "cathartic, respiratory diseases, heart, kidneys" },',
    '    };',
    '    if (i < 0) i = 0;',
    '    if (i > 170) i = 170;',
    '    return k[i];',
    '}',
    '',
    '// The rows the book leaves with unknown uses ("?").',
    'inline int herbsUnknownUsesCount() { return 10; }',
    '',
    '// True only for the one printed cross-reference row',
    '// (blueberry - see bilberry, index 49).',
    'inline bool herbsIsCrossReference(int i) {',
    '    static const bool k[171] = {',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, true,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false, false, false, false, false, false, false, false, false, false,',
        '        false,',
    '    };',
    '    if (i < 0) i = 0;',
    '    if (i > 170) i = 170;',
    '    return k[i];',
    '}',
    '',
    '// The intro prose: hundreds of different vegetable',
    '// flavorings and seasonings were or are reputed to have',
    '// medicinal and/or magic properties.',
    'inline bool herbsIntroHundredsReputedMedicinalAndMagic() {',
    '    return true;',
    '}',
    '',
    '// It is not within the scope of this work to detail all',
    '// of these herbs and spices, particularly as regards',
    '// their description, habitat, and the many uses claimed',
    '// for most.',
    'inline bool herbsIntroNotWithinScopeToDetailAll() {',
    '    return true;',
    '}',
    '',
    '// An alphabetical listing with one or two comments on',
    '// each is presented.',
    'inline bool herbsIntroAlphabeticalOneOrTwoComments() {',
    '    return true;',
    '}',
    '',
    '// The dedicated herbologist will have to pursue his or',
    '// her research in scholarly texts.',
    'inline bool herbsIntroHerbologistPursuesScholarlyTexts() {',
    '    return true;',
    '}',
    '',
    '// The closing prose: use the list as a guide to which',
    '// herbs, spices or vegetables are required for various',
    '// magical effects desired from potions, scroll inks and',
    '// other magic items.',
    'inline bool herbsClosingGuideForPotionsInksItems() {',
    '    return true;',
    '}',
    '',
    '// You may add to or delete from the list as you desire.',
    'inline bool herbsClosingAddOrDeleteAsDesired() {',
    '    return true;',
    '}',
    '',
    '// Reputed folk uses are not detailed with respect to',
    '// magic in most cases, as this decision is the purview',
    '// of the DM.',
    'inline bool herbsClosingFolkUsesMagicDMPurview() {',
    '    return true;',
    '}',
    '',
    '}  // namespace rules',
    '',
])
create("rules/herbs.h", p1_text,
      "rules/herbs.h",
      marker="R172: Appendix J (DMG p.220)")
assert len(applied) + len(already) == 1

# ---- patch 2: the regtest include ----
p2_old = '#include "rules/klm.h"  // R171: pp.221-224 appendices K L and M'
p2_new = NL.join([
    '#include "rules/klm.h"  // R171: pp.221-224 appendices K L and M',
    '#include "rules/herbs.h"  // R172: p.220 appendix J herbs spices and medicinal vegetables'
])
patch("regtest.cpp", p2_old, p2_new,
      "regtest.cpp: R172 include",
      marker="R172: p.220 appendix J herbs spices and medicinal vegetables")
assert len(applied) + len(already) == 2

# ---- patch 3: the R172 audit block ----
p3_old = NL.join(['        printf("R171 appendices K L and M audit: bad %d' + BS + 'n", bad);', '        if (bad) return 1;', '    }', '    // ---- R146: city flavor subtables audit ----'])
p3_new = NL.join([
    '        printf("R171 appendices K L and M audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R172: appendix J herbs audit --------------',
    '    // DMG p.220: the alphabetical plant and uses',
    '    // table, 171 rows, cell by cell - the',
    '    // trusted-compilation judgments recorded in',
    '    // the gap report.',
    '    {',
    '        int bad = 0;',
    '        static const char* jP[171] = {',
'            "abscess root (sweet root)",',
'            "acacia (Gum Arabic)",',
'            "aconite (monkshood, wolfsbane, friar' + Q + 's cap, etc.)",',
'            "acorn",',
'            "adder' + Q + 's tongue",',
'            "adrue",',
'            "agar-agar (jelly)",',
'            "agaric",',
'            "agrimony (cocklebur, stickwort)",',
'            "alder",',
'            "alkanet root",',
'            "all-heal (wound-wort)",',
'            "almond milk/powder",',
'            "aloe (bitter aloe)",',
'            "amaranth (red cockscomb, love-lies-bleeding)",',
'            "ammoniacum (Persian Gum)",',
'            "angelica",',
'            "anise",',
'            "arbutus (mayflower)",',
'            "areca nut (betel nut)",',
'            "arenaria rubra (sandwort)",',
'            "arrach (goosefoot)",',
'            "artichoke juice",',
'            "asafetida (gum asafetida, devil' + Q + 's dung, food of the gods)",',
'            "asarabacca (hazelwort, wild nard)",',
'            "ash (bark and leaves of)",',
'            "asparagus juice/root",',
'            "avens (colewort, herb bennet)",',
'            "bael",',
'            "balm (sweet balm) leaves",',
'            "balm of gilead",',
'            "balmony (bitter herb, snake head)",',
'            "barley",',
'            "basil",',
'            "bay leaf",',
'            "beet",',
'            "belladonna (deadly nightshade, dwale, black cherry root)",',
'            "benne (sesam, sesame)",',
'            "benzoin (gum benzoin)",',
'            "berberis",',
'            "beth root (lamb' + Q + 's quarters)",',
'            "bilberry (huckleberry, hurtleberry, whortleberry)",',
'            "birch (white birch)",',
'            "birthwort",',
'            "bistort (adderwort)",',
'            "bittersweet (felonwort, scarlet berry, woody nightshade)",',
'            "blackberry (dewberry)",',
'            "black currant",',
'            "black willow (pussy willow) bark",',
'            "blueberry - see bilberry",',
'            "blue flag (flag lily, poison flag, water flag, water lily)",',
'            "blue mallow (common mallow)",',
'            "boneset (thoughtwort)",',
'            "borage",',
'            "box leaves",',
'            "bryony",',
'            "bugle",',
'            "burdock",',
'            "butterbur",',
'            "cabbage juice",',
'            "calotopis (mudar bark)",',
'            "camphor (gum camphor)",',
'            "caraway",',
'            "cardamom",',
'            "carrot juice and seeds",',
'            "castor oil bush",',
'            "catnip",',
'            "cayenne",',
'            "celery",',
'            "chamomile",',
'            "chaulmoogra oil",',
'            "cherry gum",',
'            "chervil",',
'            "chives",',
'            "cinnamon",',
'            "cleavers (goosegrass)",',
'            "clover",',
'            "cloves",',
'            "comfrey root (healing herb)",',
'            "coriander",',
'            "couchgrass",',
'            "cucumber",',
'            "cumin seed",',
'            "dandelion",',
'            "digitalis (dead men' + Q + 's bells, fairy bells, fairy cap, fairy fingers, foxglove, etc.)",',
'            "dill",',
'            "ergot (rye smut)",',
'            "eyebright",',
'            "fennel",',
'            "fenugreek",',
'            "fig",',
'            "figwort (scrofula plant, throatwort)",',
'            "fireweed",',
'            "fluellin",',
'            "garden burnet",',
'            "garlic",',
'            "gelsemium (wild woodbine)",',
'            "gentian (bitter root, felwort)",',
'            "geranium (sweet geranium)",',
'            "ginger",',
'            "ginseng",',
'            "goat' + Q + 's rue",',
'            "grape juice",',
'            "hartstongue",',
'            "hawthorn",',
'            "hedge mustard",',
'            "hellebore",',
'            "honeysuckle",',
'            "horehound, white",',
'            "horehound, black",',
'            "horseradish",',
'            "hyssop",',
'            "ipecac",',
'            "irish moss",',
'            "jambul seed",',
'            "jewel weed (balsam weed, pale touch-me-not)",',
'            "juniper berry",',
'            "jurubera",',
'            "kelp (seawrack)",',
'            "larkspur (knight' + Q + 's spur)",',
'            "leek",',
'            "lily-of-the-valley",',
'            "lotus",',
'            "lucerne (alfalfa)",',
'            "lycopodium (common club moss, fox tail, lamb' + Q + 's tail)",',
'            "mace",',
'            "marigold",',
'            "marjoram",',
'            "masterwort",',
'            "mistletoe",',
'            "muira-puama",',
'            "mustard",',
'            "nutmeg",',
'            "nux vomica (poison nut)",',
'            "onion",',
'            "oregano",',
'            "paprika",',
'            "parsley",',
'            "parsnip",',
'            "peach seed",',
'            "pepper, black",',
'            "peppermint",',
'            "pitcher plant",',
'            "plantain (ripple grass, waybread)",',
'            "pomegranate",',
'            "poppy",',
'            "pumpkin seed",',
'            "quince",',
'            "radish",',
'            "raspberry",',
'            "rhubarb",',
'            "rose",',
'            "rosemary",',
'            "saffron",',
'            "sage",',
'            "sarsaparilla (china root, spikenard)",',
'            "scopolis",',
'            "scullcap (madweed)",',
'            "senna",',
'            "spearmint",',
'            "strawberry",',
'            "summer savory",',
'            "tamarind",',
'            "tansy",',
'            "tarragon",',
'            "tea",',
'            "thyme",',
'            "turmeric",',
'            "turnip",',
'            "watercress",',
'            "white bryony (mandragora)",',
    '        };',
    '        static const char* jU[171] = {',
'            "respiratory disorders",',
'            "tissue repair",',
'            "sedative/drives off werewolves",',
'            "tissue hardening",',
'            "emetic, emollient",',
'            "anti-vomiting, sedative",',
'            "anti-inflammation, nutrient",',
'            "astringent, purgative",',
'            "muscle toner, diuretic",',
'            "anti-inflammation, tonic",',
'            "emollient, antiseptic, wormer",',
'            "antiseptic, anti-spasmodic",',
'            "nutrient/emollient",',
'            "bites, burns, laxative, tonic/insect repellent",',
'            "astringent, anti-hemorrhaging",',
'            "stimulant, respiratory aid",',
'            "lungs, liver, spleen, vision, hearing",',
'            "antacid, digestion, coughing",',
'            "astringent, bladder infection",',
'            "astringent, tape wormer",',
'            "diuretic, urinary diseases",',
'            "sedative (nervous tension or hysteria in particular)",',
'            "jaundice curative",',
'            "aphrodisiac, brain and nervous stimulant, tonic, many more",',
'            "emetic, purgative",',
'            "laxative, anti-inflammation, fever",',
'            "sedative, heart problems/anti-oxalic acid",',
'            "astringent, anti-hemorrhaging, anti-weakness, tonic, more",',
'            "anti-inflammation, ulcers",',
'            "calms nerves, fevers",',
'            "nutrient, organ stimulant (general)",',
'            "tissue builder and strengthener, liver ailments, wormer",',
'            "nutrient (recuperative)",',
'            "nervous disorders",',
'            "?",',
'            "organic cleanser",',
'            "diuretic, sedative, pain reliever, anti-opiate, circulation, stimulant, poison/lycanthropy cure",',
'            "respiratory disorders, eye infections, more",',
'            "expectorant, stimulant, antiseptic, wounds and sores",',
'            "fevers",',
'            "astringent, coughs, tonic, anti-hemorrhaging, more",',
'            "anti-thirst, dropsy, typhoid, more",',
'            "intestines and stomach, venereal diseases, skin conditions",',
'            "circulatory stimulant",',
'            "astringent",',
'            "abscesses, lymph infections, swelling and inflammation",',
'            "astringent, tonic, dysentery",',
'            "diuretic, antiseptic, blood purifier",',
'            "astringent, antiseptic",',
'            "",',
'            "diuretic, cathartic, blood purifier (vs. poison), wound healing, venereal disease, much more",',
'            "coughs, colds",',
'            "fevers, tonic, skin diseases",',
'            "coughs, lung infections",',
'            "tonic, blood purifier",',
'            "paralysis, bruises",',
'            "gastrointestinal disorders, hemorrhaging",',
'            "laxative, tuberculosis, more",',
'            "fevers, urinary complaints",',
'            "ulcer and stomach treatment",',
'            "skin leprosy, elephantiasis, more",',
'            "bruises, sprains, chills, fevers, cardiac stimulant",',
'            "antacid, aids digestion",',
'            "?",',
'            "tonic for improved health",',
'            "purgative, cathartic",',
'            "colds, fevers, anti-spasmodic, hysteria",',
'            "stimulant",',
'            "liver functions, tonic, stimulant",',
'            "nervous conditions, ear and tooth aches",',
'            "fevers, sedative, skin eruptions",',
'            "respiratory infections/food substitute",',
'            "?",',
'            "colds, general diseases/evil eye",',
'            "disinfectant, nausea, preservative",',
'            "fevers, circulation, blood purifier, wounds, liver disease",',
'            "tonic",',
'            "anesthetic, circulation, germicide, disinfectant",',
'            "colds, respiratory conditions, wounds, bone fractures, gangrene, much, much more",',
'            "tonic",',
'            "bladder and urinary infections",',
'            "inflammation",',
'            "stimulant",',
'            "diuretic, purgative, tonic",',
'            "heart stimulant, tonic, kidney treatment (poison)",',
'            "nausea",',
'            "hemorrhaging, venereal diseases",',
'            "astringent, eye infections",',
'            "digestion, weight control, muscle tone, reflexes, vision, much, much more",',
'            "stimulant",',
'            "demulcent",',
'            "abscesses, wounds, pain killer",',
'            "astringent, anti-spasmodic",',
'            "astringent, tissue strengthener",',
'            "?",',
'            "coughs, colds, blood purifier, detoxifier, kills parasites/wards off vampires",',
'            "sedative, nerve tonic, fevers, more",',
'            "tonic, fevers, anti-venom",',
'            "alkalizer",',
'            "stimulant, colds, cramps",',
'            "glandular stimulant, vision, dizziness, headaches, weakness",',
'            "diuretic, wormer (vermifuge)",',
'            "blood fortifier",',
'            "cough, liver, spleen, bladder",',
'            "heart, arteries",',
'            "throat, lungs",',
'            "heart tonic (rootlets are poison)",',
'            "liver, spleen, respiratory disorders",',
'            "coughs, pulmonary diseases, anti-venom",',
'            "stimulant, wormer, hemorrhaging",',
'            "tonic, antiseptic, wormer",',
'            "respiratory ailments, jaundice, blood purifier, tonic, cuts and wounds, more",',
'            "dysentery, mouth infections, more",',
'            "coughs, scalds, burns",',
'            "blood purifier, diabetes",',
'            "diuretic, kidneys, skin growths, fungus, infections, liver",',
'            "aphrodisiac, stimulant, disinfectant, venereal disease, more",',
'            "anemia",',
'            "thyroid, heart, arteries, much more",',
'            "external parasites",',
'            "same as chives",',
'            "heart tonic",',
'            "?",',
'            "strength",',
'            "wounds, lungs, kidneys, more",',
'            "stimulant",',
'            "fevers, varicosities, eyes, heart",',
'            "melancholia, dizziness, brain disorders, toothaches",',
'            "stimulates organs, anti-spasmodic, more",',
'            "convulsions, hysteria, narcotic, tonic, typhoid fever, heart",',
'            "aphrodisiac",',
'            "emetic, counter-irritant, colds, fevers",',
'            "nausea, vomiting, diarrhea",',
'            "stimulant, debility tonic",',
'            "poultice, colds (as chives)",',
'            "germicide, pain killer",',
'            "stimulant, poultice",',
'            "blood purifier",',
'            "fevers",',
'            "fevers, blood tonic",',
'            "sprains, neuritis",',
'            "?",',
'            "small pox preventative and cure, stomach, liver, kidneys",',
'            "minor wounds, stings, rashes",',
'            "nerve sedative, wormer",',
'            "?",',
'            "virility, organ tonic",',
'            "eye disease, dysentery, skin disorders",',
'            "blood purifier, liver",',
'            "fevers, tonic",',
'            "astringent, cathartic",',
'            "colds, fevers",',
'            "germicide, muscle tonic/drives off evil spirits",',
'            "scarlet fever, measles, respiratory infections",',
'            "tonic, wounds",',
'            "system balance, blood purifier, venereal disease, many more",',
'            "nerve and muscle sedative, pain killer, coughs",',
'            "nervous disorders, rabies",',
'            "purgative",',
'            "?",',
'            "vision, swelling and inflammation",',
'            "blood purifier, palsy",',
'            "infection, gangrene",',
'            "tonic, narcotic, wormer",',
'            "?",',
'            "poison antidote",',
'            "antiseptic, blood purifier",',
'            "?",',
'            "mouth disease, throat",',
'            "blood tonic (anemia)",',
'            "cathartic, respiratory diseases, heart, kidneys",',
    '        };',
    '        if (rules::herbsRowCount() != 171) ++bad;',
    '        for (int i = 0; i < 171; ++i) {',
    '            if (std::string(rules::herbsRow(i).plant)',
    '                    != jP[i])',
    '                ++bad;',
    '            if (std::string(rules::herbsRow(i).uses)',
    '                    != jU[i])',
    '                ++bad;',
    '        }',
    '        // the rows the book leaves with unknown uses',
    '        int unknowns = 0;',
    '        for (int i = 0; i < 171; ++i)',
    '            if (std::string(rules::herbsRow(i).uses) == "?")',
    '                ++unknowns;',
    '        if (unknowns != 10) ++bad;',
    '        if (rules::herbsUnknownUsesCount() != 10) ++bad;',
    '        // the one cross-reference row (blueberry)',
    '        int crossrefs = 0;',
    '        for (int i = 0; i < 171; ++i)',
    '            if (rules::herbsIsCrossReference(i))',
    '                ++crossrefs;',
    '        if (crossrefs != 1) ++bad;',
    '        if (!rules::herbsIsCrossReference(49)) ++bad;',
    '        if (std::string(rules::herbsRow(49).plant)',
    '                != "blueberry - see bilberry")',
    '            ++bad;',
    '        if (std::string(rules::herbsRow(49).uses)',
    '                != "")',
    '            ++bad;',
    '        // the intro and closing prose',
    '        if (!rules::herbsIntroHundredsReputedMedicinalAndMagic() ||',
    '            !rules::herbsIntroNotWithinScopeToDetailAll() ||',
    '            !rules::herbsIntroAlphabeticalOneOrTwoComments() ||',
    '            !rules::herbsIntroHerbologistPursuesScholarlyTexts() ||',
    '            !rules::herbsClosingGuideForPotionsInksItems() ||',
    '            !rules::herbsClosingAddOrDeleteAsDesired() ||',
    '            !rules::herbsClosingFolkUsesMagicDMPurview())',
    '            ++bad;',
    '        printf("R172 appendix J herbs audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R146: city flavor subtables audit ----',
])
patch("regtest.cpp", p3_old, p3_new,
      "regtest.cpp: R172 audit block",
      marker="R172 appendix J herbs audit")
assert len(applied) + len(already) == 3

# ---- patch 4: the gap report census note ----
p4_old = NL.join([
    'box). The caller rolls and selects. Census 89.',
    '',
    'Categories:'])
p4_new = NL.join([
    'box). The caller rolls and selects. Census 89.',
    'R172 PINNED Appendix J (DMG p.220) - herbs, spices',
    'and medicinal vegetables - rules/herbs.h: the',
    'alphabetical plant and uses table, 171 rows, cell',
    'by cell (the compilation drops the turnip row and',
    'truncates the celery uses - both restored from the',
    'print), the 10 rows the book leaves with unknown',
    'uses, the one cross-reference row (blueberry - see',
    'bilberry) and the intro and closing prose.',
    'JUDGMENTs: the structure follows the 1eonline.info',
    'compilation (the repo-trusted source, the R146',
    'precedent), cell-verified against the book upload',
    'wherever legible, with per-run cell-count',
    'arithmetic used to detect compilation omissions;',
    'print spellings win where they differ; the benzoin',
    'anti-septic line break is read as antiseptic; the',
    'compilation artifacts are normalized; Appendix J was',
    'OUT of scope by design until this round reversed it',
    '(user-authorized). Census 90.',
    '',
    'Categories:'])
patch("tools/dmg_gap_report.md", p4_old, p4_new,
      "gap report: R172 header note",
      marker="R172 PINNED Appendix J (DMG p.220)")
assert len(applied) + len(already) == 4

# ---- patch 5: the gap report OUT amendment ----
p5_old = NL.join([
    '  conversion tables (pp.112-114), and Appendix J',
    '  herbs, spices, and medicinal vegetation (p.220).'])
p5_new = NL.join([
    '  conversion tables (pp.112-114). Appendix J was',
    '  OUT until R172 reversed it - pinned now (see the',
    '  R172 note and the box below).'])
patch("tools/dmg_gap_report.md", p5_old, p5_new,
      "gap report: OUT amendment",
      marker="OUT until R172 reversed it")
assert len(applied) + len(already) == 5

# ---- patch 6: the gap report box ----
p6_old = NL.join([
    '  R172 note and the box below).',
    '',
    '## How this doc lives'])
p6_new = NL.join([
    '  R172 note and the box below).',
    '',
    '- [x] **Appendix J: herbs, spices and medicinal',
    '      vegetables (p.220)** - PINNED R172:',
    '      rules/herbs.h (the 171-row plant and uses',
    '      table cell by cell; the turnip row the',
    '      compilation drops restored).',
    '',
    '## How this doc lives'])
patch("tools/dmg_gap_report.md", p6_old, p6_new,
      "gap report: appendix J box",
      marker="PINNED R172:")
assert len(applied) + len(already) == 6

# ---- R172 fails/tail ----
if fails:
    print("R172 splice: FAIL - " + str(len(fails)) + " patch(es) failed:")
    for f in fails:
        print("  " + f)
    sys.exit(1)
if len(applied) + len(already) != 6:
    print("R172 splice: FAIL - expected 6 patches, counted " + str(len(applied) + len(already)) + " (a truncated paste?)")
    sys.exit(1)
if already and not applied:
    print("R172 splice: ALL OK (applied 0, already " + str(len(already)) + ")")
else:
    print("R172 splice: ALL OK (applied " + str(len(applied)) + ", already " + str(len(already)) + ")")
print("R172 note: 6 patches; census 90; commit: R172: appendix J herbs spices and medicinal vegetables pinned - the p.220 plant and uses table (census 90)")

