#!/usr/bin/env python3
# R208 splice: the social class and rank system -
# DMG pp.88-89, SOCIAL CLASS AND RANK IN AD&D: the
# 19 government forms with their print defining
# traits, the worked example aristocracy (the
# service/land/income-tax rule with the 20 gold
# piece merchant land waiver; the senators, the
# tribunals, the senatorial police appointments),
# the town and city social structure (upper,
# middle, lower - what each draws), the municipal
# offices (the lifetime mayor, the aldermen chosen
# by the upper and elected by the middle class,
# the strata of judiciary, military command, law,
# customs and tax officials, the common council,
# the petty officials, the constabulary), the
# non-hereditary knights with order-varying
# precedence, the northern European title ladder
# (emperor down to knight, 10, duke preceding
# prince per the print table) with the German
# equivalents, and the 20 Asian titles.
# A seam with no prior coverage. Patches: 4 (new
# rules/socialrank.h, regtest include, audit block,
# gap-report log entry). Census 123 -> 124.

BS = chr(92)
NL = chr(10)

applied = 0
already = 0


def rd(p):
    with open(p, 'r') as f:
        return f.read()


def wr(p, s):
    with open(p, 'w') as f:
        f.write(s)


def patch(path, marker, old, new):
    # in-place marker patch; old must be unique;
    # old = None means the new-file form
    global applied, already
    try:
        t = rd(path)
    except IOError:
        # the file does not exist: create it
        assert old is None, 'anchor patch on absent file: ' + marker
        assert marker in new, 'marker missing in new file: ' + marker
        wr(path, new)
        applied += 1
        return
    if marker in t:
        already += 1
        return
    assert marker not in t, 'marker must be absent pre-patch: ' + marker
    assert t.count(old) == 1, 'anchor not unique in ' + path + ': ' + marker
    t = t.replace(old, new)
    assert marker in t, 'marker missing post-patch in ' + path
    assert NL not in marker, 'marker spans a newline: ' + marker
    wr(path, t)
    applied += 1


# ---------------------------------------------------------------------------
# Patch 1: rules/socialrank.h - the new header
# ---------------------------------------------------------------------------

hdr_lines = [
'// ====================================================================',
'// Adnd1 - rules/socialrank.h',
'// R208: the social class and rank system (DMG',
'// pp.88-89, SOCIAL CLASS AND RANK IN',
'// ADVANCED DUNGEONS AND DRAGONS) - the',
'// government forms, the worked example',
'// aristocracy, the town and city social',
'// structure, the noble titles.',
'//',
'// Pure data + helpers, header-only (the',
'// grenade.h pattern: the caller owns the',
'// society; the definitions read here). No',
'// random birth table exists in the print by',
'// design - the DM devises the social',
'// structure; what is pinned here is exactly',
'// what the print does state.',
'// ====================================================================',
'',
'#pragma once',
'',
'namespace rules {',
'',
'// -----------------------------------------------------------------------',
'// The government forms (p.89), the print list in order.',
'// -----------------------------------------------------------------------',
'enum GovForm {',
'    GOV_AUTOCRACY = 0,',
'    GOV_BUREAUCRACY,',
'    GOV_CONFEDERACY,',
'    GOV_DEMOCRACY,',
'    GOV_DICTATORSHIP,',
'    GOV_FEUDALITY,',
'    GOV_GERIATOCRACY,',
'    GOV_GYNARCHY,',
'    GOV_HIERARCHY,',
'    GOV_MAGOCRACY,',
'    GOV_MATRIARCHY,',
'    GOV_MILITOCRACY,',
'    GOV_MONARCHY,',
'    GOV_OLIGARCHY,',
'    GOV_PEDOCRACY,',
'    GOV_PLUTOCRACY,',
'    GOV_REPUBLIC,',
'    GOV_THEOCRACY,',
'    GOV_SYNDICRACY,',
'    GOV_FORM_COUNT',
'};',
'',
'// The defining trait of each form - the print',
'// definition, one code per form, in form order.',
'enum GovTrait {',
'    GOVT_SELF_DERIVED_ABSOLUTE = 0,',
'    GOVT_DEPARTMENT_HEADS,',
'    GOVT_LEAGUE_COMMON_GOOD,',
'    GOVT_CITIZENS_BODY,',
'    GOVT_ONE_SUPREME_HEAD,',
'    GOVT_LAYERED_FEALTY,',
'    GOVT_ELDERLY_ONLY,',
'    GOVT_FEMALES_ONLY,',
'    GOVT_RELIGIOUS_LIKE_FEUDAL,',
'    GOVT_MAGIC_USERS_ONLY,',
'    GOVT_ELDEST_FEMALES,',
'    GOVT_MILITARY_HEADS,',
'    GOVT_SINGLE_HEREDITARY_SOVEREIGN,',
'    GOVT_FEW_COEQUAL,',
'    GOVT_THE_LEARNED,',
'    GOVT_THE_WEALTHY,',
'    GOVT_REPRESENTATIVE_ELECTORATE,',
'    GOVT_GOD_RULE,',
'    GOVT_SYNDICS_BUSINESS,',
'    GOVT_TRAIT_COUNT',
'};',
'',
'inline int govFormCount() { return 19; }',
'',
'inline int govFormTrait(int form) {',
'    // the trait code of each form, in print',
'    // list order: autocracy is self-derived',
'    // absolute power, bureaucracy rule by',
'    // department heads, confederacy a league',
'    // for the common good, democracy the',
'    // body of citizens, dictatorship final',
'    // authority in one supreme head,',
'    // feudality layered fealty, geriatocracy',
'    // the elderly, gynarchy females only,',
'    // hierarchy religious like a feudality,',
'    // magocracy magic-users only, matriarchy',
'    // the eldest females, militocracy the',
'    // military heads, monarchy a single',
'    // hereditary sovereign, oligarchy a few',
'    // coequal rulers, pedocracy the learned,',
'    // plutocracy the wealthy, republic',
'    // representatives of an electorate,',
'    // theocracy rule by the god, syndicracy',
'    // a body of business syndics',
'    static const int t[19] = {',
'        0, 1, 2, 3, 4, 5, 6, 7, 8, 9,',
'        10, 11, 12, 13, 14, 15, 16, 17, 18,',
'    };',
'    if (form < 0) form = 0;',
'    if (form > 18) form = 18;',
'    return t[form];',
'}',
'',
'// -----------------------------------------------------------------------',
'// The worked example aristocracy (p.88): a',
'// non-hereditary ruling class. Members are',
'// those who have served in the military, own',
'// property of 100 or more acres extent, and',
'// pay an annual tax of not less than 10 gold',
'// pieces on their income - the serial list',
'// reads conjunctively (all three), and the',
'// merchant waiver settles it: land ownership',
'// is waived for merchants and tradesmen',
'// whose business pays not less than 20 gold',
'// pieces in taxes each year - a waiver that',
'// would be vacuous under an or-reading.',
'// -----------------------------------------------------------------------',
'inline bool aristocratEligible(',
'        bool servedMilitary, int acresOwned,',
'        int annualIncomeTaxGold) {',
'    if (!servedMilitary) return false;',
'    if (acresOwned < 100) return false;',
'    if (annualIncomeTaxGold < 10) return false;',
'    return true;',
'}',
'',
'inline bool aristocratMerchantEligible(',
'        bool servedMilitary, int annualTaxGold) {',
'    // the land criterion waived at 20 gold',
'    if (!servedMilitary) return false;',
'    if (annualTaxGold < 20) return false;',
'    return true;',
'}',
'',
'// The offices: aristocrats only, for any',
'// government office and command of the',
'// military; senators elected from their',
'// number; former senators eligible for the',
'// tribunals and judgeships; former military',
'// officers appointed by senatorial vote to',
'// keep the peace and police the land.',
'inline bool officeEligible(bool isAristocrat) {',
'    return isAristocrat;',
'}',
'',
'inline bool senateEligible(bool isAristocrat) {',
'    return isAristocrat;',
'}',
'',
'inline bool tribunalEligible(bool formerSenator) {',
'    return formerSenator;',
'}',
'',
'inline bool policeAppointedFrom(',
'        bool formerMilitaryOfficer) {',
'    return formerMilitaryOfficer;',
'}',
'',
'// -----------------------------------------------------------------------',
'// The town and city social structure (p.89):',
'// three classes, each drawing its officers.',
'// -----------------------------------------------------------------------',
'enum TownClass {',
'    TOWN_UPPER = 0,',
'    TOWN_MIDDLE,',
'    TOWN_LOWER,',
'    TOWN_CLASS_COUNT',
'};',
'',
'inline int townClassCount() { return 3; }',
'',
'// Upper: nobles, gentlemen, the wealthiest',
'// merchants and the most important guildmasters',
'// - the important law makers and executives.',
'inline bool townDrawsImportantLawmakers(int tc) {',
'    return tc == TOWN_UPPER;',
'}',
'',
'// Middle: merchants and guildmasters with the',
'// master artisans - the lesser officials.',
'inline bool townProvidesLesserOfficials(int tc) {',
'    return tc == TOWN_MIDDLE;',
'}',
'',
'// Lower: tradesmen, journeymen, laborers and',
'// all others - the common council.',
'inline bool townDrawsCommonCouncil(int tc) {',
'    return tc == TOWN_LOWER;',
'}',
'',
'// -----------------------------------------------------------------------',
'// The municipal offices (pp.89-90).',
'// -----------------------------------------------------------------------',
'// Mayor, magistrate or burgomaster: probably',
'// a lifetime office drawn only from the upper',
'// class.',
'inline int mayorTitleCount() { return 3; }',
'inline bool mayorOfficeLifetime() { return true; }',
'inline int mayorOfficeSourceClass() {',
'    return TOWN_UPPER;',
'}',
'',
'// Aldermen, burghers or burgesses: chosen by',
'// the upper class to serve as the major',
'// officers under the mayor; elected by the',
'// middle class.',
'inline int aldermanTitleCount() { return 3; }',
'inline bool aldermenChosenBy(int tc) {',
'    return tc == TOWN_UPPER;',
'}',
'inline bool aldermenElectedBy(int tc) {',
'    return tc == TOWN_MIDDLE;',
'}',
'',
'// The judiciary and the military commanders of',
'// the municipality fall within the upper',
'// stratum; law enforcement, customs and tax',
'// officials all come from the middle class.',
'inline int townJudiciaryStratum() {',
'    return TOWN_UPPER;',
'}',
'inline int townMilitaryCommandStratum() {',
'    return TOWN_UPPER;',
'}',
'inline int lawEnforcementSourceClass() {',
'    return TOWN_MIDDLE;',
'}',
'inline int customsOfficialSourceClass() {',
'    return TOWN_MIDDLE;',
'}',
'inline int taxOfficialSourceClass() {',
'    return TOWN_MIDDLE;',
'}',
'',
'// Councilors of the common council: selected',
'// by the upper and middle classes as well as',
'// the free lower class; petty officials drawn',
'// from the lower class, advisory or',
'// administrative only.',
'inline bool councilorSelectedBy(int tc) {',
'    return tc == TOWN_UPPER || tc == TOWN_MIDDLE;',
'}',
'inline bool councilorSelectedByLower(',
'        bool lowerIsFree) {',
'    return lowerIsFree;',
'}',
'inline int pettyOfficialsSourceClass() {',
'    return TOWN_LOWER;',
'}',
'inline bool pettyOfficialRoleAdministrative() {',
'    return true;',
'}',
'',
'// The constabulary: drawn in part from citizen',
'// soldiers, the city watch or police force, and',
'// militia called up in times of great need; by',
'// far the bulk of other soldiery hired',
'// mercenaries.',
'inline bool constabularyIncludesCitizenSoldiers() {',
'    return true;',
'}',
'inline bool constabularyIncludesWatchOrPolice() {',
'    return true;',
'}',
'inline bool militiaCalledInGreatNeed() {',
'    return true;',
'}',
'inline bool soldieryBulkMercenaries() {',
'    return true;',
'}',
'',
'// -----------------------------------------------------------------------',
'// Knights (p.89): non-hereditary peers, their',
'// precedence varying with the order of',
'// knighthood held.',
'// -----------------------------------------------------------------------',
'inline bool knightsHereditary() { return false; }',
'inline bool knightPrecedenceVariesByOrder() {',
'    return true;',
'}',
'',
'// -----------------------------------------------------------------------',
'// Royal and noble titles, northern European',
'// (p.89): the secular ladder of the table -',
'// the print lists duke before prince.',
'// -----------------------------------------------------------------------',
'enum NobleTitleRN {',
'    NT_EMPEROR = 0,',
'    NT_KING,',
'    NT_DUKE,',
'    NT_PRINCE,',
'    NT_MARQUIS,',
'    NT_COUNT_EARL,',
'    NT_VISCOUNT,',
'    NT_BARON_THANE,',
'    NT_BARONET,',
'    NT_KNIGHT,',
'    NT_RN_COUNT',
'};',
'',
'inline int nobleTitleRNCount() { return 10; }',
'',
'inline int nobleTitleRNPrecedence(int t) {',
'    // emperor highest, knight lowest',
'    if (t < 0) t = 0;',
'    if (t > 9) t = 9;',
'    return t;',
'}',
'',
'// The ecclesiastical ranks (archbishop, bishop,',
'// abbot, prior) sit among the nobility per the',
'// table rows.',
'inline int ecclesiasticalRanksAmongNobility() {',
'    return 4;',
'}',
'',
'// The German equivalents of the table: 0',
'// Pfalzgraf (with duke), 1 Herzog (with',
'// prince), 2 Margrave (with marquis), 3 Graf',
'// (with count/earl), 4 Waldgraf (with',
'// viscount), 5 Freiherr (with baronet), 6',
'// Ritter (with knight); -1 = no equivalent in',
'// the row.',
'enum GermanTitle {',
'    GT_PFALZGRAF = 0,',
'    GT_HERZOG,',
'    GT_MARGRAVE,',
'    GT_GRAF,',
'    GT_WALDGRAF,',
'    GT_FREIHERR,',
'    GT_RITTER,',
'    GT_COUNT',
'};',
'',
'inline int germanEquivalentCount() { return 7; }',
'',
'inline int germanEquivalentOf(int t) {',
'    static const int g[10] = {',
'        -1, -1, 0, 1, 2, 3, 4, -1, 5, 6,',
'    };',
'    if (t < 0) t = 0;',
'    if (t > 9) t = 9;',
'    return g[t];',
'}',
'',
'// The Asian title forms (p.89): twenty listed',
'// in the table - Padishah, Maharaja, Kha-Khan,',
'// Tarkhan, Sultan, Shah, Rajah, Ilkhan, Dey,',
'// Caliph, Bey, Orkhon, Bashaw, Pasha, Emir,',
'// Amir, Khan, Sheikh, Nawab, Malik.',
'inline int asianTitleCount() { return 20; }',
'',
'} // namespace rules',
]
hdr = NL.join(hdr_lines) + NL

patch('rules/socialrank.h',
      'R208: the social class and rank system (DMG',
      None,
      hdr)
# the new-file patch: the empty anchor means
# create-if-absent, marker-check-if-present

# ---------------------------------------------------------------------------
# Patch 2: regtest.cpp - the include
# ---------------------------------------------------------------------------

old2 = '#include "rules/taxation.h"  // R207: p.90 the town taxation system'

new2 = ('#include "rules/taxation.h"  // R207: p.90 the town taxation system'
        + NL + '#include "rules/socialrank.h"  // R208: pp.88-89 social class and rank')

patch('regtest.cpp',
      'R208: pp.88-89 social class and rank',
      old2,
      new2)

# ---------------------------------------------------------------------------
# Patch 3: regtest.cpp - the R208 audit block
# ---------------------------------------------------------------------------

audit_lines = [
'    // ---- R208: the social class and rank audit ----',
'    // DMG pp.88-89: the government forms,',
'    // the worked example aristocracy, the',
'    // town and city social structure and',
'    // offices, the knights and the noble',
'    // title ladders.',
'    {',
'        int bad = 0;',
'        // the government forms: 19 named,',
'        // each with its print definition trait',
'        if (rules::govFormCount() != 19) ++bad;',
'        static const int kTrait[19] = {',
'            0, 1, 2, 3, 4, 5, 6, 7, 8, 9,',
'            10, 11, 12, 13, 14, 15, 16, 17, 18,',
'        };',
'        for (int f = 0; f < 19; ++f)',
'            if (rules::govFormTrait(f) != kTrait[f]) ++bad;',
'        // the distinctive definitions, pinned',
'        if (rules::govFormTrait(rules::GOV_GYNARCHY)',
'                != rules::GOVT_FEMALES_ONLY ||',
'            rules::govFormTrait(rules::GOV_MATRIARCHY)',
'                != rules::GOVT_ELDEST_FEMALES) ++bad;',
'        if (rules::govFormTrait(rules::GOV_THEOCRACY)',
'                != rules::GOVT_GOD_RULE) ++bad;',
'        if (rules::govFormTrait(rules::GOV_MAGOCRACY)',
'                != rules::GOVT_MAGIC_USERS_ONLY ||',
'            rules::govFormTrait(rules::GOV_PLUTOCRACY)',
'                != rules::GOVT_THE_WEALTHY) ++bad;',
'        if (rules::govFormTrait(rules::GOV_PEDOCRACY)',
'                != rules::GOVT_THE_LEARNED ||',
'            rules::govFormTrait(rules::GOV_GERIATOCRACY)',
'                != rules::GOVT_ELDERLY_ONLY) ++bad;',
'        if (rules::govFormTrait(rules::GOV_SYNDICRACY)',
'                != rules::GOVT_SYNDICS_BUSINESS) ++bad;',
'        if (rules::govFormTrait(rules::GOV_FEUDALITY)',
'                != rules::GOVT_LAYERED_FEALTY ||',
'            rules::govFormTrait(rules::GOV_HIERARCHY)',
'                != rules::GOVT_RELIGIOUS_LIKE_FEUDAL) ++bad;',
'        if (rules::govFormTrait(rules::GOV_MONARCHY)',
'                != rules::GOVT_SINGLE_HEREDITARY_SOVEREIGN',
'            || rules::govFormTrait(rules::GOV_OLIGARCHY)',
'                != rules::GOVT_FEW_COEQUAL) ++bad;',
'        // the worked example aristocracy: all',
'        // three - service, land, income tax',
'        if (!rules::aristocratEligible(true, 100, 10) ||',
'            rules::aristocratEligible(false, 100, 10) ||',
'            rules::aristocratEligible(true, 99, 10) ||',
'            rules::aristocratEligible(true, 100, 9) ||',
'            !rules::aristocratEligible(true, 500, 50))',
'            ++bad;',
'        // the merchant waiver: land waived at',
'        // 20 gold pieces of annual business tax',
'        if (!rules::aristocratMerchantEligible(true, 20) ||',
'            rules::aristocratMerchantEligible(true, 19) ||',
'            !rules::aristocratMerchantEligible(true, 100) ||',
'            rules::aristocratMerchantEligible(false, 20))',
'            ++bad;',
'        // the offices: aristocrats only; the',
'        // senate from their number; tribunals',
'        // from former senators; the police',
'        // appointment from former officers',
'        if (!rules::officeEligible(true) ||',
'            rules::officeEligible(false) ||',
'            !rules::senateEligible(true) ||',
'            rules::senateEligible(false)) ++bad;',
'        if (!rules::tribunalEligible(true) ||',
'            rules::tribunalEligible(false) ||',
'            !rules::policeAppointedFrom(true) ||',
'            rules::policeAppointedFrom(false)) ++bad;',
'        // the town classes: three, and what',
'        // each draws',
'        if (rules::townClassCount() != 3) ++bad;',
'        if (!rules::townDrawsImportantLawmakers(',
'                rules::TOWN_UPPER) ||',
'            rules::townDrawsImportantLawmakers(',
'                rules::TOWN_MIDDLE) ||',
'            rules::townDrawsImportantLawmakers(',
'                rules::TOWN_LOWER)) ++bad;',
'        if (!rules::townProvidesLesserOfficials(',
'                rules::TOWN_MIDDLE) ||',
'            rules::townProvidesLesserOfficials(',
'                rules::TOWN_UPPER) ||',
'            rules::townProvidesLesserOfficials(',
'                rules::TOWN_LOWER)) ++bad;',
'        if (!rules::townDrawsCommonCouncil(',
'                rules::TOWN_LOWER) ||',
'            rules::townDrawsCommonCouncil(',
'                rules::TOWN_UPPER) ||',
'            rules::townDrawsCommonCouncil(',
'                rules::TOWN_MIDDLE)) ++bad;',
'        // the mayor: three titles, lifetime,',
'        // upper class only',
'        if (rules::mayorTitleCount() != 3 ||',
'            !rules::mayorOfficeLifetime() ||',
'            rules::mayorOfficeSourceClass()',
'                != rules::TOWN_UPPER) ++bad;',
'        // the aldermen: three titles, chosen by',
'        // the upper class as major officers,',
'        // elected by the middle class',
'        if (rules::aldermanTitleCount() != 3 ||',
'            !rules::aldermenChosenBy(rules::TOWN_UPPER) ||',
'            rules::aldermenChosenBy(rules::TOWN_MIDDLE) ||',
'            rules::aldermenChosenBy(rules::TOWN_LOWER) ||',
'            !rules::aldermenElectedBy(rules::TOWN_MIDDLE) ||',
'            rules::aldermenElectedBy(rules::TOWN_UPPER))',
'            ++bad;',
'        // the strata: judiciary and military',
'        // command upper; law, customs and tax',
'        // officials middle',
'        if (rules::townJudiciaryStratum()',
'                != rules::TOWN_UPPER ||',
'            rules::townMilitaryCommandStratum()',
'                != rules::TOWN_UPPER) ++bad;',
'        if (rules::lawEnforcementSourceClass()',
'                != rules::TOWN_MIDDLE ||',
'            rules::customsOfficialSourceClass()',
'                != rules::TOWN_MIDDLE ||',
'            rules::taxOfficialSourceClass()',
'                != rules::TOWN_MIDDLE) ++bad;',
'        // the councilors: selected by upper',
'        // and middle and the free lower; petty',
'        // officials lower, administrative only',
'        if (!rules::councilorSelectedBy(',
'                rules::TOWN_UPPER) ||',
'            !rules::councilorSelectedBy(',
'                rules::TOWN_MIDDLE) ||',
'            rules::councilorSelectedBy(',
'                rules::TOWN_LOWER)) ++bad;',
'        if (!rules::councilorSelectedByLower(true) ||',
'            rules::councilorSelectedByLower(false) ||',
'            rules::pettyOfficialsSourceClass()',
'                != rules::TOWN_LOWER ||',
'            !rules::pettyOfficialRoleAdministrative())',
'            ++bad;',
'        // the constabulary: citizen soldiers,',
'        // watch or police, militia in great',
'        // need; the bulk hired mercenaries',
'        if (!rules::constabularyIncludesCitizenSoldiers() ||',
'            !rules::constabularyIncludesWatchOrPolice() ||',
'            !rules::militiaCalledInGreatNeed() ||',
'            !rules::soldieryBulkMercenaries()) ++bad;',
'        // the knights: non-hereditary peers,',
'        // precedence varying by order',
'        if (rules::knightsHereditary() ||',
'            !rules::knightPrecedenceVariesByOrder())',
'            ++bad;',
'        // the northern European ladder: 10',
'        // secular titles, emperor highest,',
'        // knight lowest; duke precedes prince',
'        // per the print table',
'        if (rules::nobleTitleRNCount() != 10 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_EMPEROR) != 0 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_KING) != 1 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_DUKE) != 2 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_PRINCE) != 3 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_MARQUIS) != 4 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_COUNT_EARL) != 5 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_VISCOUNT) != 6 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_BARON_THANE) != 7 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_BARONET) != 8 ||',
'            rules::nobleTitleRNPrecedence(',
'                rules::NT_KNIGHT) != 9) ++bad;',
'        // the ecclesiastical ranks among the',
'        // nobility: archbishop, bishop, abbot,',
'        // prior',
'        if (rules::ecclesiasticalRanksAmongNobility() != 4)',
'            ++bad;',
'        // the German equivalents: seven mapped',
'        if (rules::germanEquivalentCount() != 7 ||',
'            rules::germanEquivalentOf(rules::NT_KNIGHT)',
'                != rules::GT_RITTER ||',
'            rules::germanEquivalentOf(rules::NT_EMPEROR)',
'                != -1 ||',
'            rules::germanEquivalentOf(rules::NT_DUKE)',
'                != rules::GT_PFALZGRAF ||',
'            rules::germanEquivalentOf(rules::NT_PRINCE)',
'                != rules::GT_HERZOG ||',
'            rules::germanEquivalentOf(rules::NT_BARON_THANE)',
'                != -1) ++bad;',
'        // the Asian titles: twenty listed',
'        if (rules::asianTitleCount() != 20) ++bad;',
'        printf("R208 social class and rank audit: bad %d' + BS + 'n", bad);',
'        if (bad) return 1;',
'    }',
]
audit = NL.join(audit_lines) + NL

old3 = '    // ---- R163: the poison table audit -------------'

new3 = audit + old3

patch('regtest.cpp',
      'R208: the social class and rank audit',
      old3,
      new3)

# ---------------------------------------------------------------------------
# Patch 4: tools/dmg_gap_report.md - the log entry
# ---------------------------------------------------------------------------

log_lines = [
'R208 landed the social class and rank',
'system (DMG pp.88-89) - the 19',
'government forms with their defining',
'traits, the worked example aristocracy',
'(the service, land and income-tax rule',
'with the 20 gold piece merchant land',
'waiver; the senators, the tribunals and',
'the senatorial police appointments), the',
'town and city social structure (the',
'upper, middle and lower classes and what',
'each draws), the municipal offices (the',
'lifetime mayor, the aldermen chosen by',
'the upper and elected by the middle',
'class, the strata of judiciary, military',
'command, law, customs and tax officials,',
'the common council and the petty',
'officials, the constabulary), the',
'non-hereditary knights with',
'order-varying precedence, the northern',
'European title ladder (emperor down to',
'knight, 10, duke preceding prince per',
'the print table) with the German',
'equivalents and the 20 Asian titles. New',
'R208 battery audit; census 124. Next:',
'the DMG-only sweep continues.',
]
log_entry = NL.join(log_lines)

old4 = 'sweep continues.' + NL + NL + 'Categories:'

new4 = ('sweep continues.' + NL + NL + log_entry + NL + NL
        + 'Categories:')

patch('tools/dmg_gap_report.md',
      'R208 landed the social class and rank',
      old4,
      new4)

# ---------------------------------------------------------------------------
# the tail (always prints)
# ---------------------------------------------------------------------------

assert applied + already == 4, 'patch count drift: ' + str(applied) + ' + ' + str(already)
print('R208 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R208 note: 4 patches; the social class and rank system pinned -')
print('the government forms, the worked example aristocracy, the town')
print('social structure and offices, the knights and the noble titles;')
print('census 124.')
print('commit: R208: the social class and rank system pinned - DMG')
print('pp.88-89, government, aristocracy, town structure, titles (census 124)')

