#!/usr/bin/env python3
# R211 splice: the NPC height and weight tables
# and the language determination - DMG
# pp.115-116, the personae chapter tail: the
# MALES and FEMALES height/weight tables (7
# races: average, the under and over dice), the
# HEIGHT AND WEIGHT DETERMINATION percent bands,
# and the RANDOM LANGUAGE DETERMINATION TABLE
# (100 faces, 55 kinds: brownie through xorn,
# 86-00 human foreign or other). Patches: 4
# (new rules/npcbody.h, regtest include, audit
# block, gap-report log entry). Census 126 -> 127.

BS = chr(92)
NL = chr(10)

applied = 0
already = 0


def rd(p):
    with open(p, 'r') as f:
        return f.read()


def wr(p, s):
    with open(p, 'w') as f:
        f.write(s)


def patch(path, marker, old, new):
    # in-place marker patch; old must be unique;
    # old = None means the new-file form
    global applied, already
    try:
        t = rd(path)
    except IOError:
        # the file does not exist: create it
        assert old is None, 'anchor patch on absent file: ' + marker
        assert marker in new, 'marker missing in new file: ' + marker
        wr(path, new)
        applied += 1
        return
    if marker in t:
        already += 1
        return
    assert marker not in t, 'marker must be absent pre-patch: ' + marker
    assert t.count(old) == 1, 'anchor not unique in ' + path + ': ' + marker
    t = t.replace(old, new)
    assert marker in t, 'marker missing post-patch in ' + path
    assert NL not in marker, 'marker spans a newline: ' + marker
    wr(path, t)
    applied += 1


# ---------------------------------------------------------------------------
# Patch 1: rules/npcbody.h - the new header
# ---------------------------------------------------------------------------

hdr_lines = [
'// ====================================================================',
'// Adnd1 - rules/npcbody.h',
'// R211: the NPC height and weight tables',
'// and the language determination (DMG',
'// pp.115-116, the personae chapter tail) -',
'// the MALES and FEMALES tables, the',
'// determination percent bands, and the',
'// random language table.',
'//',
'// Pure data + helpers, header-only (the',
'// grenade.h pattern: the caller owns the',
'// dice and the campaign milieu; the',
'// averages, the dice and the bands read',
'// here).',
'//',
'// Conventions and judgments, named in',
'// place:',
'//   - Race order: the print table order',
'//     (dwarf, elf, gnome, half-elf,',
'//     halfling, half-orc, human). Sex: 0',
'//     male, 1 female - the print MALES and',
'//     FEMALES tables.',
'//   - The print dice cells are ranges',
'//     (1-4, 2-16, 4-40); each encodes a',
'//     dice sum: 1-4 = 1d4, 2-16 = 2d8,',
'//     4-40 = 4d10, 5-60 = 5d12. Packed as',
'//     count * 100 + sides (212 = 2d12,',
'//     410 = 4d10); npcDieCount/npcDieSides',
'//     unpack.',
'//   - GROUND TRUTH NOTE: the live 1eonline',
'//     compilation editorializes this seam',
'//     (it splits Human into NPC and PC rows',
'//     with d20x10-style entries and cites',
'//     OSRIC; it reads the half-orc male',
'//     over-weight as d20 and the human male',
'//     over-weight as 5d6). The book upload',
'//     carries the print ranges (4-40 and',
'//     5-60) and ONE human row - the upload',
'//     is pinned; the compilation additions',
'//     are excluded (the R209/R210 rule).',
'//   - The determination bands are per race,',
'//     shared by both sexes (the print',
'//     HEIGHT AND WEIGHT DETERMINATION',
'//     table): a d100 roll picks under /',
'//     average / over for height, then',
'//     again for weight.',
'//   - The language table: the print reads',
'//     primarily for NPC (and magic sword)',
'//     language knowledge - player',
'//     characters learn foreign languages',
'//     from others. The ten dragon faces',
'//     (05-14), the eight giant faces',
'//     (28-35, hill on 31-33) and the three',
'//     naga faces (62-64) are each a',
'//     separate kind; 86-00 is human',
'//     foreign or other (the campaign',
'//     footnote - the caller names it).',
'// ====================================================================',
'',
'#pragma once',
'',
'namespace rules {',
'',
'// -----------------------------------------------------------------------',
'// The die packing: count * 100 + sides.',
'// -----------------------------------------------------------------------',
'inline int npcDieCount(int packed) { return packed / 100; }',
'',
'inline int npcDieSides(int packed) { return packed % 100; }',
'',
'// -----------------------------------------------------------------------',
'// The height and weight tables: 7 races,',
'// two sexes. Averages and the under/over',
'// adjustment dice.',
'// -----------------------------------------------------------------------',
'enum NpcBodyRace {',
'    NBR_DWARF = 0,',
'    NBR_ELF,',
'    NBR_GNOME,',
'    NBR_HALFELF,',
'    NBR_HALFLING,',
'    NBR_HALFORC,',
'    NBR_HUMAN,',
'    NBR_COUNT',
'};',
'',
'inline int npcBodyRaceCount() { return 7; }',
'',
'inline int npcHeightAvgInches(int female, int race) {',
'    // the print averages: male 48/60/42/',
'    // 66/36/66/72, female 46/54/39/62/33/',
'    // 62/66',
'    if (female < 0) female = 0;',
'    if (female > 1) female = 1;',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    static const int t[14] = {',
'        48, 60, 42, 66, 36, 66, 72,',
'        46, 54, 39, 62, 33, 62, 66,',
'    };',
'    return t[female * 7 + race];',
'}',
'',
'inline int npcWeightAvgPounds(int female, int race) {',
'    // male 150/100/80/130/60/150/175,',
'    // female 120/80/75/100/50/120/130',
'    if (female < 0) female = 0;',
'    if (female > 1) female = 1;',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    static const int t[14] = {',
'        150, 100, 80, 130, 60, 150, 175,',
'        120, 80, 75, 100, 50, 120, 130,',
'    };',
'    return t[female * 7 + race];',
'}',
'',
'inline int npcHeightDie(int female, int race, int over) {',
'    // the under/over adjustment dice,',
'    // packed count*100+sides: male dwarf',
'    // 1d4/1d6 ... female human 1d6/1d8',
'    if (female < 0) female = 0;',
'    if (female > 1) female = 1;',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    if (over < 0) over = 0;',
'    if (over > 1) over = 1;',
'    static const int t[28] = {',
'        104, 104, 103, 106, 103, 104, 112,',
'        106, 106, 103, 106, 106, 104, 112,',
'        104, 104, 103, 106, 103, 103, 106,',
'        104, 106, 103, 106, 103, 103, 108,',
'    };',
'    return t[female * 14 + over * 7 + race];',
'}',
'',
'inline int npcWeightDie(int female, int race, int over) {',
'    // male dwarf 2d8/2d12 ... half-orc',
'    // 2d8/4d10, human 3d12/5d12; female',
'    // half-orc 3d6/4d8, human 3d10/4d12',
'    if (female < 0) female = 0;',
'    if (female > 1) female = 1;',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    if (over < 0) over = 0;',
'    if (over > 1) over = 1;',
'    static const int t[28] = {',
'        208, 110, 204, 120, 204, 208, 312,',
'        212, 120, 206, 120, 206, 410, 512,',
'        208, 110, 108, 112, 204, 306, 310,',
'        210, 206, 108, 208, 204, 408, 412,',
'    };',
'    return t[female * 14 + over * 7 + race];',
'}',
'',
'// -----------------------------------------------------------------------',
'// The determination bands (per race, both',
'// sexes): the d100 under/average/over edges',
'// for height and weight.',
'// -----------------------------------------------------------------------',
'inline int npcHeightBandUnderEdge(int race) {',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    static const int e[7] = { 15, 10, 20, 35, 10, 45, 20 };',
'    return e[race];',
'}',
'',
'inline int npcHeightBandAvgEdge(int race) {',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    static const int e[7] = { 80, 80, 85, 90, 90, 75, 80 };',
'    return e[race];',
'}',
'',
'inline int npcWeightBandUnderEdge(int race) {',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    static const int e[7] = { 20, 15, 20, 20, 10, 30, 25 };',
'    return e[race];',
'}',
'',
'inline int npcWeightBandAvgEdge(int race) {',
'    if (race < 0) race = 0;',
'    if (race > 6) race = 6;',
'    static const int e[7] = { 65, 90, 75, 85, 50, 55, 75 };',
'    return e[race];',
'}',
'',
'inline int npcBandClass(int pct, int underEdge, int avgEdge) {',
'    // 0 under, 1 average, 2 over; the roll',
'    // clamps to 1..100',
'    if (pct < 1) pct = 1;',
'    if (pct > 100) pct = 100;',
'    if (pct <= underEdge) return 0;',
'    if (pct <= avgEdge) return 1;',
'    return 2;',
'}',
'',
'inline int npcDetermineHeightClass(int race, int pct) {',
'    return npcBandClass(pct,',
'        npcHeightBandUnderEdge(race),',
'        npcHeightBandAvgEdge(race));',
'}',
'',
'inline int npcDetermineWeightClass(int race, int pct) {',
'    return npcBandClass(pct,',
'        npcWeightBandUnderEdge(race),',
'        npcWeightBandAvgEdge(race));',
'}',
'',
'// -----------------------------------------------------------------------',
'// The random language determination table:',
'// 100 faces, 55 kinds, in print order -',
'// brownie, bugbear, centaur, the ten',
'// dragons, dryad, dwarvish, elvish, ettin,',
'// gargoyle, the eight giants, goblin,',
'// gnoll, gnome, halfling, hobgoblin,',
'// kobold, lammasu, lizard man, manticore,',
'// medusian, minotaur, the three nagas,',
'// nixie, nymph, ogrish, ogre magian,',
'// orcish, pixie, salamander, satyr, shedu,',
'// sprite, sylph, titan, troll, xorn, and',
'// 86-00 human foreign or other.',
'// -----------------------------------------------------------------------',
'enum NpcLang {',
'    NPC_LG_BROWNIE = 0,',
'    NPC_LG_BUGBEAR,',
'    NPC_LG_CENTAUR,',
'    NPC_LG_DRAGON_BLACK,',
'    NPC_LG_DRAGON_BLUE,',
'    NPC_LG_DRAGON_BRASS,',
'    NPC_LG_DRAGON_BRONZE,',
'    NPC_LG_DRAGON_COPPER,',
'    NPC_LG_DRAGON_GOLD,',
'    NPC_LG_DRAGON_GREEN,',
'    NPC_LG_DRAGON_RED,',
'    NPC_LG_DRAGON_SILVER,',
'    NPC_LG_DRAGON_WHITE,',
'    NPC_LG_DRYAD,',
'    NPC_LG_DWARVISH,',
'    NPC_LG_ELVISH,',
'    NPC_LG_ETTIN,',
'    NPC_LG_GARGOYLE,',
'    NPC_LG_GIANT_CLOUD,',
'    NPC_LG_GIANT_FIRE,',
'    NPC_LG_GIANT_FROST,',
'    NPC_LG_GIANT_HILL_1,',
'    NPC_LG_GIANT_HILL_2,',
'    NPC_LG_GIANT_HILL_3,',
'    NPC_LG_GIANT_STONE,',
'    NPC_LG_GIANT_STORM,',
'    NPC_LG_GOBLIN,',
'    NPC_LG_GNOLL,',
'    NPC_LG_GNOME,',
'    NPC_LG_HALFLING,',
'    NPC_LG_HOBGOBLIN,',
'    NPC_LG_KOBOLD,',
'    NPC_LG_LAMMASU,',
'    NPC_LG_LIZARD_MAN,',
'    NPC_LG_MANTICORE,',
'    NPC_LG_MEDUSIAN,',
'    NPC_LG_MINOTAUR,',
'    NPC_LG_NAGA_GUARDIAN,',
'    NPC_LG_NAGA_SPIRIT,',
'    NPC_LG_NAGA_WATER,',
'    NPC_LG_NIXIE,',
'    NPC_LG_NYMPH,',
'    NPC_LG_OGRISH,',
'    NPC_LG_OGRE_MAGIAN,',
'    NPC_LG_ORCISH,',
'    NPC_LG_PIXIE,',
'    NPC_LG_SALAMANDER,',
'    NPC_LG_SATYR,',
'    NPC_LG_SHEDU,',
'    NPC_LG_SPRITE,',
'    NPC_LG_SYLPH,',
'    NPC_LG_TITAN,',
'    NPC_LG_TROLL,',
'    NPC_LG_XORN,',
'    NPC_LG_HUMAN_FOREIGN,',
'    NPC_LG_COUNT',
'};',
'',
'inline int npcLanguageKindCount() { return 55; }',
'',
'inline int npcLanguageFor(int pct) {',
'    // the 100-face table, d100; the roll',
'    // clamps to 1..100',
'    if (pct < 1) pct = 1;',
'    if (pct > 100) pct = 100;',
'    static const int t[100] = {',
'        0, 1, 1, 2,',
'        3, 4, 5, 6, 7, 8, 9, 10, 11, 12,',
'        13,',
'        14, 14, 14, 14, 14,',
'        15, 15, 15, 15, 15,',
'        16,',
'        17,',
'        18, 19, 20, 21, 22, 23, 24, 25,',
'        26, 26, 26, 26,',
'        27,',
'        28, 28, 28, 28,',
'        29, 29, 29, 29, 29,',
'        30, 30,',
'        31, 31, 31,',
'        32,',
'        33, 33, 33,',
'        34,',
'        35,',
'        36,',
'        37, 38, 39,',
'        40,',
'        41,',
'        42, 42, 42, 42,',
'        43,',
'        44, 44, 44, 44, 44,',
'        45,',
'        46,',
'        47,',
'        48,',
'        49,',
'        50,',
'        51,',
'        52,',
'        53,',
'        54, 54, 54, 54, 54, 54, 54, 54,',
'        54, 54, 54, 54, 54, 54, 54,',
'    };',
'    return t[pct - 1];',
'}',
'',
'}  // namespace rules',
]
hdr = NL.join(hdr_lines) + NL

patch('rules/npcbody.h',
      'R211: the NPC height and weight tables',
      None,
      hdr)
# the new-file patch: the empty anchor means
# create-if-absent, marker-check-if-present

# ---------------------------------------------------------------------------
# Patch 2: regtest.cpp - the include
# ---------------------------------------------------------------------------

old2 = '#include "rules/npctraits.h"  // R210: pp.115-116 NPC personae traits'

new2 = ('#include "rules/npctraits.h"  // R210: pp.115-116 NPC personae traits'
        + NL + '#include "rules/npcbody.h"  // R211: pp.115-116 height, weight, languages')

patch('regtest.cpp',
      'R211: pp.115-116 height, weight, languages',
      old2,
      new2)

# ---------------------------------------------------------------------------
# Patch 3: regtest.cpp - the R211 audit block
# ---------------------------------------------------------------------------

audit_lines = [
'    // ---- R211: the NPC body and language audit ----',
'    // DMG pp.115-116: the height and weight',
'    // tables and determination bands, and the',
'    // random language table.',
'    {',
'        int bad = 0;',
'        // the averages and dice, every cell',
'        if (rules::npcBodyRaceCount() != 7) ++bad;',
'        static const int kHAvg[14] = {',
'            48, 60, 42, 66, 36, 66, 72,',
'            46, 54, 39, 62, 33, 62, 66,',
'        };',
'        static const int kWAvg[14] = {',
'            150, 100, 80, 130, 60, 150, 175,',
'            120, 80, 75, 100, 50, 120, 130,',
'        };',
'        static const int kHDice[28] = {',
'            104, 104, 103, 106, 103, 104, 112,',
'            106, 106, 103, 106, 106, 104, 112,',
'            104, 104, 103, 106, 103, 103, 106,',
'            104, 106, 103, 106, 103, 103, 108,',
'        };',
'        static const int kWDice[28] = {',
'            208, 110, 204, 120, 204, 208, 312,',
'            212, 120, 206, 120, 206, 410, 512,',
'            208, 110, 108, 112, 204, 306, 310,',
'            210, 206, 108, 208, 204, 408, 412,',
'        };',
'        for (int f = 0; f <= 1; ++f)',
'            for (int r = 0; r < 7; ++r)',
'                if (rules::npcHeightAvgInches(f, r)',
'                        != kHAvg[f * 7 + r] ||',
'                    rules::npcWeightAvgPounds(f, r)',
'                        != kWAvg[f * 7 + r]) ++bad;',
'        for (int f = 0; f <= 1; ++f)',
'            for (int d = 0; d <= 1; ++d)',
'                for (int r = 0; r < 7; ++r)',
'                    if (rules::npcHeightDie(f, r, d)',
'                            != kHDice[f * 14 + d * 7 + r] ||',
'                        rules::npcWeightDie(f, r, d)',
'                            != kWDice[f * 14 + d * 7 + r]) ++bad;',
'        // the packing: count and sides',
'        if (rules::npcDieCount(212) != 2 ||',
'            rules::npcDieSides(212) != 12 ||',
'            rules::npcDieCount(410) != 4 ||',
'            rules::npcDieSides(410) != 10 ||',
'            rules::npcDieCount(512) != 5 ||',
'            rules::npcDieSides(512) != 12 ||',
'            rules::npcDieCount(120) != 1 ||',
'            rules::npcDieSides(120) != 20) ++bad;',
'        // the determination bands: the edges',
'        static const int kHUnder[7] = { 15, 10, 20, 35, 10, 45, 20 };',
'        static const int kHAvgE[7] = { 80, 80, 85, 90, 90, 75, 80 };',
'        static const int kWUnder[7] = { 20, 15, 20, 20, 10, 30, 25 };',
'        static const int kWAvgE[7] = { 65, 90, 75, 85, 50, 55, 75 };',
'        for (int r = 0; r < 7; ++r)',
'            if (rules::npcHeightBandUnderEdge(r)',
'                    != kHUnder[r] ||',
'                rules::npcHeightBandAvgEdge(r)',
'                    != kHAvgE[r] ||',
'                rules::npcWeightBandUnderEdge(r)',
'                    != kWUnder[r] ||',
'                rules::npcWeightBandAvgEdge(r)',
'                    != kWAvgE[r]) ++bad;',
'        // the class walk: edges and clamps',
'        if (rules::npcDetermineHeightClass('
'                rules::NBR_DWARF, 15) != 0 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_DWARF, 16) != 1 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_DWARF, 80) != 1 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_DWARF, 81) != 2) ++bad;',
'        if (rules::npcDetermineHeightClass('
'                rules::NBR_HALFORC, 45) != 0 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_HALFORC, 46) != 1 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_HALFORC, 75) != 1 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_HALFORC, 76) != 2) ++bad;',
'        if (rules::npcDetermineWeightClass('
'                rules::NBR_HUMAN, 25) != 0 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_HUMAN, 26) != 1 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_HUMAN, 75) != 1 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_HUMAN, 76) != 2) ++bad;',
'        if (rules::npcDetermineHeightClass('
'                rules::NBR_ELF, 10) != 0 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_ELF, 11) != 1 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_ELF, 15) != 0 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_ELF, 16) != 1 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_ELF, 90) != 1 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_ELF, 91) != 2) ++bad;',
'        if (rules::npcDetermineWeightClass('
'                rules::NBR_HALFLING, 10) != 0 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_HALFLING, 11) != 1 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_HALFLING, 50) != 1 ||',
'            rules::npcDetermineWeightClass('
'                rules::NBR_HALFLING, 51) != 2) ++bad;',
'        // the clamps: 0 reads under, 101 reads',
'        // over',
'        if (rules::npcDetermineHeightClass('
'                rules::NBR_DWARF, 0) != 0 ||',
'            rules::npcDetermineHeightClass('
'                rules::NBR_DWARF, 101) != 2) ++bad;',
'        // the language table: every face',
'        if (rules::npcLanguageKindCount() != 55) ++bad;',
'        static const int kLang[100] = {',
'            0, 1, 1, 2,',
'            3, 4, 5, 6, 7, 8, 9, 10, 11, 12,',
'            13,',
'            14, 14, 14, 14, 14,',
'            15, 15, 15, 15, 15,',
'            16,',
'            17,',
'            18, 19, 20, 21, 22, 23, 24, 25,',
'            26, 26, 26, 26,',
'            27,',
'            28, 28, 28, 28,',
'            29, 29, 29, 29, 29,',
'            30, 30,',
'            31, 31, 31,',
'            32,',
'            33, 33, 33,',
'            34,',
'            35,',
'            36,',
'            37, 38, 39,',
'            40,',
'            41,',
'            42, 42, 42, 42,',
'            43,',
'            44, 44, 44, 44, 44,',
'            45,',
'            46,',
'            47,',
'            48,',
'            49,',
'            50,',
'            51,',
'            52,',
'            53,',
'            54, 54, 54, 54, 54, 54, 54, 54,',
'            54, 54, 54, 54, 54, 54, 54,',
'        };',
'        for (int d = 1; d <= 100; ++d)',
'            if (rules::npcLanguageFor(d) != kLang[d - 1]) ++bad;',
'        // the language boundaries: each band',
'        // start and the kind codes',
'        if (rules::npcLanguageFor(1)',
'                != rules::NPC_LG_BROWNIE ||',
'            rules::npcLanguageFor(2)',
'                != rules::NPC_LG_BUGBEAR ||',
'            rules::npcLanguageFor(4)',
'                != rules::NPC_LG_CENTAUR ||',
'            rules::npcLanguageFor(5)',
'                != rules::NPC_LG_DRAGON_BLACK ||',
'            rules::npcLanguageFor(14)',
'                != rules::NPC_LG_DRAGON_WHITE ||',
'            rules::npcLanguageFor(15)',
'                != rules::NPC_LG_DRYAD ||',
'            rules::npcLanguageFor(16)',
'                != rules::NPC_LG_DWARVISH ||',
'            rules::npcLanguageFor(21)',
'                != rules::NPC_LG_ELVISH ||',
'            rules::npcLanguageFor(26)',
'                != rules::NPC_LG_ETTIN ||',
'            rules::npcLanguageFor(28)',
'                != rules::NPC_LG_GIANT_CLOUD ||',
'            rules::npcLanguageFor(31)',
'                != rules::NPC_LG_GIANT_HILL_1 ||',
'            rules::npcLanguageFor(33)',
'                != rules::NPC_LG_GIANT_HILL_3 ||',
'            rules::npcLanguageFor(35)',
'                != rules::NPC_LG_GIANT_STORM ||',
'            rules::npcLanguageFor(36)',
'                != rules::NPC_LG_GOBLIN ||',
'            rules::npcLanguageFor(40)',
'                != rules::NPC_LG_GNOLL ||',
'            rules::npcLanguageFor(41)',
'                != rules::NPC_LG_GNOME ||',
'            rules::npcLanguageFor(45)',
'                != rules::NPC_LG_HALFLING ||',
'            rules::npcLanguageFor(50)',
'                != rules::NPC_LG_HOBGOBLIN ||',
'            rules::npcLanguageFor(52)',
'                != rules::NPC_LG_KOBOLD ||',
'            rules::npcLanguageFor(55)',
'                != rules::NPC_LG_LAMMASU ||',
'            rules::npcLanguageFor(56)',
'                != rules::NPC_LG_LIZARD_MAN ||',
'            rules::npcLanguageFor(59)',
'                != rules::NPC_LG_MANTICORE ||',
'            rules::npcLanguageFor(60)',
'                != rules::NPC_LG_MEDUSIAN ||',
'            rules::npcLanguageFor(61)',
'                != rules::NPC_LG_MINOTAUR ||',
'            rules::npcLanguageFor(62)',
'                != rules::NPC_LG_NAGA_GUARDIAN ||',
'            rules::npcLanguageFor(64)',
'                != rules::NPC_LG_NAGA_WATER ||',
'            rules::npcLanguageFor(65)',
'                != rules::NPC_LG_NIXIE ||',
'            rules::npcLanguageFor(66)',
'                != rules::NPC_LG_NYMPH ||',
'            rules::npcLanguageFor(67)',
'                != rules::NPC_LG_OGRISH ||',
'            rules::npcLanguageFor(71)',
'                != rules::NPC_LG_OGRE_MAGIAN ||',
'            rules::npcLanguageFor(72)',
'                != rules::NPC_LG_ORCISH ||',
'            rules::npcLanguageFor(77)',
'                != rules::NPC_LG_PIXIE ||',
'            rules::npcLanguageFor(78)',
'                != rules::NPC_LG_SALAMANDER ||',
'            rules::npcLanguageFor(79)',
'                != rules::NPC_LG_SATYR ||',
'            rules::npcLanguageFor(80)',
'                != rules::NPC_LG_SHEDU ||',
'            rules::npcLanguageFor(81)',
'                != rules::NPC_LG_SPRITE ||',
'            rules::npcLanguageFor(82)',
'                != rules::NPC_LG_SYLPH ||',
'            rules::npcLanguageFor(83)',
'                != rules::NPC_LG_TITAN ||',
'            rules::npcLanguageFor(84)',
'                != rules::NPC_LG_TROLL ||',
'            rules::npcLanguageFor(85)',
'                != rules::NPC_LG_XORN ||',
'            rules::npcLanguageFor(86)',
'                != rules::NPC_LG_HUMAN_FOREIGN ||',
'            rules::npcLanguageFor(100)',
'                != rules::NPC_LG_HUMAN_FOREIGN) ++bad;',
'        // the language clamps',
'        if (rules::npcLanguageFor(0)',
'                != rules::NPC_LG_BROWNIE ||',
'            rules::npcLanguageFor(101)',
'                != rules::NPC_LG_HUMAN_FOREIGN) ++bad;',
'        printf("R211 NPC body and language audit: bad %d' + BS + 'n", bad);',
'        if (bad) return 1;',
'    }',
]
audit = NL.join(audit_lines) + NL

old3 = '    // ---- R163: the poison table audit -------------'

new3 = audit + old3

patch('regtest.cpp',
      'R211: the NPC body and language audit',
      old3,
      new3)

# ---------------------------------------------------------------------------
# Patch 4: tools/dmg_gap_report.md - the log entry
# ---------------------------------------------------------------------------

log_lines = [
'R211 landed the NPC height and weight',
'tables and the language determination',
'(DMG pp.115-116, the personae chapter',
'tail) - a seam with zero prior coverage.',
'rules/npcbody.h (the grenade.h pattern):',
'the MALES and FEMALES height/weight',
'tables (7 races: the averages, the under',
'and over dice - the print range cells',
'2-16 = 2d8, 4-40 = 4d10, 5-60 = 5d12,',
'packed count*100+sides), the HEIGHT AND',
'WEIGHT DETERMINATION percent bands (per',
'race, both sexes: under/average/over',
'edges for height and weight), and the',
'RANDOM LANGUAGE DETERMINATION TABLE -',
'100 faces, 55 kinds: brownie through',
'xorn, the ten dragon faces, the eight',
'giant faces (hill on 31-33), the three',
'naga faces, 86-00 human foreign or other.',
'GROUND TRUTH NOTE: the live compilation',
'editorializes this seam (a Human NPC/PC',
'row split with d20x10 entries citing',
'OSRIC; half-orc male over-weight read as',
'd20, human male over-weight as 5d6) - the',
'book upload carries the print ranges and',
'one human row, and is pinned (the',
'R209/R210 exclusion rule). New R211',
'battery audit; census 127. Next: the',
'DMG-only sweep continues - the special',
'roles of the DM, hiring NPCs to cast',
'spells, monsters and organization.',
]
log_entry = NL.join(log_lines)

old4 = 'tables, the language determination.' + NL + NL + 'Categories:'

new4 = ('tables, the language determination.' + NL + NL + log_entry + NL + NL
        + 'Categories:')

patch('tools/dmg_gap_report.md',
      'R211 landed the NPC height and weight',
      old4,
      new4)

# ---------------------------------------------------------------------------
# the tail (always prints)
# ---------------------------------------------------------------------------

assert applied + already == 4, 'patch count drift: ' + str(applied) + ' + ' + str(already)
print('R211 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R211 note: 4 patches; the height and weight tables and the')
print('language determination pinned - 7 races both sexes, the')
print('determination bands, the 100-face language table; census 127.')
print('commit: R211: the NPC height and weight and language tables pinned - DMG')
print('pp.115-116, averages, dice, determination bands, languages (census 127)')

