#!/usr/bin/env python3
# R230 splice: the subclass creation gates. A character
# can now BE a paladin, ranger, druid, illusionist,
# assassin or monk at creation: rules/subclassgates.h
# gains the creation seam (the runtime base-class map,
# the con class, the starting-age band, the two-dice
# flag, the subclass hit die, the player-eligibility
# gate, the Table II effective cap with the footnote-8
# gnome conditional), creation gains the CR_SUBCLASS
# stage (eligibility on the adjusted minimums + Race
# Table I), makeSubclassMember (the subclass hit die,
# ranger/monk two dice with the per-die con
# adjustment, the druid/illusionist slot fills, the
# illusionist L1 book, the monk kit), the save/load
# subclass line (v1-compatible), the restoreSlots
# druid/illusionist branches, the member class-name
# display, the R230 battery audit, and the gap-report
# box flip. 18 patches; idempotent (markers = the new
# content); zero backslashes. Run on 1bb80e8 (R229
# landed). JUDGMENTs: the monk rides CLASS_FIGHTER at
# runtime and the fighter offer list; its con class is
# CLASS_THIEF; the alignment gates stay data-only (no
# alignment concept yet); the bard stays uncreatable.

NL = chr(10)
Q = chr(39)
BS = chr(92)
DQ = chr(34)
APPLIED = 0
ALREADY = 0


def patch(path, marker, old, new):
    # the R228 pattern: marker = a unique single-line snippet
    # of the NEW content (absent pre-patch, present post)
    global APPLIED, ALREADY
    assert NL not in marker, 'marker spans a newline: ' + marker
    s = open(path).read()
    if marker in s:
        ALREADY += 1
        return
    if old not in s:
        raise SystemExit('R230 FAIL: %s anchor not found in %s'
                         % (marker, path))
    if s.count(old) != 1:
        raise SystemExit('R230 FAIL: %s anchor not unique in %s'
                         % (marker, path))
    t = s.replace(old, new)
    if marker not in t:
        raise SystemExit('R230 FAIL: %s marker missing post-patch'
                         % marker)
    open(path, 'w').write(t)
    APPLIED += 1


def lines(ls):
    return NL.join(ls)


PATCHES = [
    ('rules/subclassgates.h',
     'inline int subclassRuntimeBase(int sub) {',
     lines([
         '} // namespace rules',
     ]),
     lines([
         '',
         '// ---------------------------------------------------------------------------',
         '// R230: the creation seam. The printed gates become a',
         '// character-creation gate chain: player eligibility',
         '// (Race Table I), the effective level cap (Table II',
         '// with the footnote-8 gnome illusionist conditional),',
         '// and the per-subclass creation parameters the engine',
         '// reads at the CR_SUBCLASS stage.',
         '//',
         '// JUDGMENTs:',
         '//   - the monk has no base class; its runtime base is',
         '//     CLASS_FIGHTER (the closest save matrix and kit;',
         '//     the specials round revisits) and it rides the',
         '//     fighter offer list at creation.',
         '//   - the monk con class is CLASS_THIEF (the registry',
         '//     group pin - NOT the fighter CON bonus group).',
         '//   - the monk starting age reads the fighter band.',
         '//   - the alignment requirements stay data-only: the',
         '//     engine has no alignment concept yet (a later',
         '//     arc round owns alignment).',
         '//',
         '// EVAL NOTE: these helpers use plain ints and private',
         '// flat copies of the R180 matrices - the audit',
         '// evaluator cannot parse the enum constants the R180',
         '// accessors read (the : int enums do not load). The',
         '// R230 battery pins the copies against the same',
         '// printed walks.',
         '// ---------------------------------------------------------------------------',
         '',
         '// The runtime base class (the save matrix, the gear',
         '// and the engine switches): paladin, ranger, druid,',
         '// illusionist, assassin, monk in registry order. The',
         '// monk rides CLASS_FIGHTER (the JUDGMENT).',
         'inline int subclassRuntimeBase(int sub) {',
         '    if (sub == 0) return 0;   // paladin -> fighter',
         '    if (sub == 1) return 0;   // ranger -> fighter',
         '    if (sub == 2) return 2;   // druid -> cleric',
         '    if (sub == 3) return 1;   // illusionist -> magic-user',
         '    if (sub == 4) return 3;   // assassin -> thief',
         '    return 0;                 // monk -> fighter',
         '}',
         '',
         '// The con-adjustment class: the paladin and ranger',
         '// join the fighter CON bonus group (the print); the',
         '// monk is not in the group (the registry pin).',
         'inline int subclassConClass(int sub) {',
         '    if (sub == 2) return 2;   // druid -> cleric',
         '    if (sub == 3) return 1;   // illusionist -> magic-user',
         '    if (sub == 4) return 3;   // assassin -> thief',
         '    if (sub == 5) return 3;   // monk -> thief',
         '    return 0;                 // paladin, ranger -> fighter',
         '}',
         '',
         '// The starting-age band (the base class table, PHB',
         '// p.20); the monk reads the fighter band.',
         'inline int subclassStartAgeBase(int sub) {',
         '    if (sub == 2) return 18;   // druid -> cleric band',
         '    if (sub == 3) return 24;   // illusionist -> MU band',
         '    if (sub == 4) return 18;   // assassin -> thief band',
         '    return 15;                 // paladin, ranger, monk',
         '}',
         '',
         '// Two hit dice at level 1 (the ranger and the monk -',
         '// the R179 JUDGMENT, the printed accumulated column).',
         'inline int subclassTwoDiceFirstLevel(int sub) {',
         '    if (sub == 1) return 1;   // ranger',
         '    if (sub == 5) return 1;   // monk',
         '    return 0;',
         '}',
         '',
         '// The subclass hit die (the registry pins:',
         '// paladin d10, ranger d8, druid d8, illusionist d4,',
         '// assassin d6, monk d4).',
         'inline int subclassHitDie(int sub) {',
         '    static const int kDie[6] = {',
         '        10, 8, 8, 4, 6, 4',
         '    };',
         '    if (sub < 0) sub = 0;',
         '    if (sub > 5) sub = 5;',
         '    return kDie[sub];',
         '}',
         '',
         '// Player eligibility: Race Table I, flat 42 (a private',
         '// copy - see the EVAL NOTE).',
         'inline int subclassPlayerAllowed(int sub, CharRace r) {',
         '    static const int kAllow[42] = {',
         '        1, 0, 0, 0, 0, 0, 0,',
         '        1, 0, 0, 0, 1, 0, 0,',
         '        1, 0, 0, 0, 1, 0, 0,',
         '        1, 0, 0, 1, 0, 0, 0,',
         '        1, 1, 1, 1, 1, 0, 1,',
         '        1, 0, 0, 0, 0, 0, 0',
         '    };',
         '    int si = sub;',
         '    if (si < 0) si = 0;',
         '    if (si > 5) si = 5;',
         '    int ri = (int)r;',
         '    if (ri < 0) ri = 0;',
         '    if (ri > 6) ri = 6;',
         '    return kAllow[si * 7 + ri];',
         '}',
         '',
         '// The effective level cap: Race Table II, flat 42 (a',
         '// private copy - see the EVAL NOTE), with the',
         '// footnote-8 gnome illusionist conditional. 0 =',
         '// forbidden; -1 = unlimited; positive = the printed',
         '// player cap; -n (n >= 2) = NPC-only cap n.',
         'inline int subclassLevelCapFor(int sub, CharRace r,',
         '                               int intScore, int dexScore) {',
         '    static const int kCap[42] = {',
         '        -1,  0,  0,  0,  0,  0,  0,',
         '        -1,  0,  0,  0,  8,  0,  0,',
         '        -1,  0,  0,  0, -1, -6,  0,',
         '        -1,  0,  0,  7,  0,  0,  0,',
         '        -1,  9, 10,  8, 11,  0, -1,',
         '        -1,  0,  0,  0,  0,  0,  0',
         '    };',
         '    int si = sub;',
         '    if (si < 0) si = 0;',
         '    if (si > 5) si = 5;',
         '    int ri = (int)r;',
         '    if (ri < 0) ri = 0;',
         '    if (ri > 6) ri = 6;',
         '    if (si == 3 && ri == 3)',
         '        return illusionistGnomeCap(intScore, dexScore);',
         '    return kCap[si * 7 + ri];',
         '}',
         '} // namespace rules',
     ])),
    ('game/appstate.h',
     '#include "../rules/subclassgates.h"',
     lines([
         '#include "../rules/classes.h"',
     ]),
     lines([
         '#include "../rules/classes.h"',
         '#include "../rules/subclasses.h"  // R230: the subclass registry',
         '#include "../rules/subclassgates.h"  // R230: the creation gates',
     ])),
    ('game/appstate.h',
     '    CR_SUBCLASS,   // R230: the subclass offer stage',
     lines([
         '    CR_CLASS,',
         '    CR_NAME,',
     ]),
     lines([
         '    CR_CLASS,',
         '    CR_SUBCLASS,   // R230: the subclass offer stage',
         '    CR_NAME,',
     ])),
    ('game/appstate.h',
     '    int  subPick = -1;',
     lines([
         '    int  classPick = 0;              // highlighted class row',
     ]),
     lines([
         '    int  classPick = 0;              // highlighted class row',
         '    int  subPick = -1;               // R230: registry subclass, -1 = plain',
     ])),
    ('game/appstate.h',
     '        subPick = -1;   // R230',
     lines([
         '        classPick = 0;',
         '        nameBuf.clear();',
     ]),
     lines([
         '        classPick = 0;',
         '        subPick = -1;   // R230',
         '        nameBuf.clear();',
     ])),
    ('game/appstate.h',
     '    int subclassOfferCount() const {',
     lines([
         '        // R35: everyone starts with a full quiver (20 missiles)',
         '        c.missileAmmo = 20;',
         '        return c;',
         '    }',
     ]),
     lines([
         '        // R35: everyone starts with a full quiver (20 missiles)',
         '        c.missileAmmo = 20;',
         '        return c;',
         '    }',
         '',
         '    // R230: the subclass offer rows for the chosen base:',
         '    // row 0 the plain base class, then every registry',
         '    // subclass whose runtime base matches (the monk',
         '    // rides the fighter list - the JUDGMENT)',
         '    int subclassOfferCount() const {',
         '        int n = 1;',
         '        for (int i = 0; i < rules::SUB_COUNT; ++i)',
         '            if (rules::subclassRuntimeBase(i) == classPick)',
         '                ++n;',
         '        return n;',
         '    }',
         '',
         '    // the registry index for offer row r;',
         '    // -1 = the plain base class (row 0)',
         '    int subclassOfferAt(int row) const {',
         '        if (row <= 0) return -1;',
         '        int n = 1;',
         '        for (int i = 0; i < rules::SUB_COUNT; ++i) {',
         '            if (rules::subclassRuntimeBase(i) == classPick) {',
         '                if (n == row) return i;',
         '                ++n;',
         '            }',
         '        }',
         '        return -1;',
         '    }',
         '',
         '    // R230: subclass eligibility - the base class must',
         '    // qualify, then the R180 gates on the ADJUSTED',
         '    // scores (the ability minimums) and Race Table I',
         '    // (player eligibility)',
         '    bool subclassEligible(int sub) const {',
         '        if (!classEligible(rules::subclassRuntimeBase(sub)))',
         '            return false;',
         '        if (!rules::subclassMeetsAbilityMin(sub,',
         '                raceAdjusted())) return false;',
         '        if (rules::subclassPlayerAllowed(sub,',
         '                (rules::CharRace)racePick) != 1)',
         '            return false;',
         '        return true;',
         '    }',
         '',
         '    // R230: finalize as a registry subclass (makeMember',
         '    // builds the base member; this overlays the subclass',
         '    // parameters)',
         '    Character makeSubclassMember(int sub) {',
         '        int base = rules::subclassRuntimeBase(sub);',
         '        Character c = makeMember(base);',
         '        c.subclass = sub;',
         '',
         '        // the start age reads the subclass band, with',
         '        // the base-class roll (2d8 the magic-user band,',
         '        // 1d4 otherwise - the p.20 convention)',
         '        if (base == rules::CLASS_MAGIC_USER)',
         '            c.startAge = rules::subclassStartAgeBase(sub)',
         '                + creationDice.roll(2, 8, 0);',
         '        else',
         '            c.startAge = rules::subclassStartAgeBase(sub)',
         '                + creationDice.roll(1, 4, 0);',
         '',
         '        // hit points: the subclass die; the ranger and',
         '        // monk roll TWO dice at level 1 (each die with',
         '        // its con adjustment - the engine per-die',
         '        // convention, the JUDGMENT; the floor is 1)',
         '        int conAdj = rules::conHPAdjustment(',
         '            rules::subclassConClass(sub), c.abilities.con);',
         '        int die = rules::subclassHitDie(sub);',
         '        int hp = (int)creationDice.roll(',
         '                     1, (uint32_t)die, 0) + conAdj;',
         '        if (rules::subclassTwoDiceFirstLevel(sub))',
         '            hp += (int)creationDice.roll(',
         '                      1, (uint32_t)die, 0) + conAdj;',
         '        if (hp < 1) hp = 1;',
         '        c.hp = c.maxHp = hp;',
         '',
         '        // slots: the druid and illusionist read their',
         '        // R228/R229 tables (the base fill is replaced)',
         '        if (sub == rules::SUB_DRUID) {',
         '            for (int lv = 1; lv <= 9; ++lv)   // R131',
         '                c.slotsByLevel[lv - 1] =',
         '                    spells::spellSlots(',
         '                        spells::SPELL_DRUID, 1, lv);',
         '        } else if (sub == rules::SUB_ILLUSIONIST) {',
         '            c.knownSpells.clear();   // the MU book out',
         '            for (int lv = 1; lv <= 9; ++lv)   // R131',
         '                c.slotsByLevel[lv - 1] =',
         '                    spells::spellSlots(',
         '                        spells::SPELL_ILLUSIONIST, 1, lv);',
         '            // the R33 convention: one random L1 spell',
         '            std::vector<int> l1;',
         '            for (int id = 0; id < spells::SPELL_COUNT;',
         '                 ++id) {',
         '                const spells::SpellDef& s =',
         '                    spells::spell((spells::SpellId)id);',
         '                if (s.sclass == spells::SPELL_ILLUSIONIST',
         '                    && s.level == 1) l1.push_back(id);',
         '            }',
         '            if (!l1.empty()) {',
         '                int pick = (int)creationDice.roll(',
         '                    1, (uint32_t)l1.size(), 0) - 1;',
         '                c.knownSpells.push_back(l1[pick]);',
         '            }',
         '        }',
         '',
         '        // the monk kit: quarterstaff, no armor, no',
         '        // shield (the JUDGMENT; the R24 sets stand for',
         '        // the rest)',
         '        if (sub == rules::SUB_MONK) {',
         '            c.weapon.id = items::WPN_QUARTERSTAFF;',
         '            c.armor.id = items::ARMOR_NONE_EQUIPPED;',
         '            c.shield = false;',
         '        }',
         '        return c;',
         '    }',
     ])),
    ('adnd1.cpp',
     '        case CR_SUBCLASS:   // R230: the subclass offer',
     lines([
         '        case CR_CLASS:',
         '            switch (wp) {',
         '                case ' + Q + '1' + Q + ': case ' + Q + '2' + Q + ': case ' + Q + '3' + Q + ': case ' + Q + '4' + Q + ': {',
         '                    int idx = (int)(wp - ' + Q + '1' + Q + ');',
         '                    if (cr.classEligible(idx)) {',
         '                        cr.classPick = idx;',
         '                        cr.stage = CR_NAME;',
         '                    }',
         '                    break;',
         '                }',
         '                case VK_ESCAPE:',
         '                    cr.stage = CR_RACE;   // back to race choice',
         '                    break;',
         '            }',
         '            break;',
     ]),
     lines([
         '        case CR_CLASS:',
         '            switch (wp) {',
         '                case ' + Q + '1' + Q + ': case ' + Q + '2' + Q + ': case ' + Q + '3' + Q + ': case ' + Q + '4' + Q + ': {',
         '                    int idx = (int)(wp - ' + Q + '1' + Q + ');',
         '                    if (cr.classEligible(idx)) {',
         '                        cr.classPick = idx;',
         '                        cr.subPick = -1;   // plain until chosen',
         '                        cr.stage = CR_SUBCLASS;   // R230',
         '                    }',
         '                    break;',
         '                }',
         '                case VK_ESCAPE:',
         '                    cr.stage = CR_RACE;   // back to race choice',
         '                    break;',
         '            }',
         '            break;',
         '',
         '        case CR_SUBCLASS:   // R230: the subclass offer',
         '            switch (wp) {',
         '                case ' + Q + '1' + Q + ': case ' + Q + '2' + Q + ': case ' + Q + '3' + Q + ': case ' + Q + '4' + Q + ': {',
         '                    int row = (int)(wp - ' + Q + '1' + Q + ');',
         '                    if (row < cr.subclassOfferCount()) {',
         '                        int sub = cr.subclassOfferAt(row);',
         '                        if (sub < 0',
         '                            || cr.subclassEligible(sub)) {',
         '                            cr.subPick = sub;',
         '                            cr.stage = CR_NAME;',
         '                        }',
         '                    }',
         '                    break;',
         '                }',
         '                case VK_ESCAPE:',
         '                    cr.stage = CR_CLASS;  // back to the class',
         '                    break;',
         '            }',
         '            break;',
     ])),
    ('adnd1.cpp',
     '        case CR_SUBCLASS: {   // R230: the subclass offer',
     lines([
         '            SetTextColor(dc, RGB(190, 175, 140));',
         '            TextOutA(dc, 20, VIEW_H - 60,',
         '                     "[1-4] choose class   [esc] back to race",',
         '                     39);',
         '            break;',
         '        }',
         '',
         '        case CR_NAME: {',
     ]),
     lines([
         '            SetTextColor(dc, RGB(190, 175, 140));',
         '            TextOutA(dc, 20, VIEW_H - 60,',
         '                     "[1-4] choose class   [esc] back to race",',
         '                     39);',
         '            break;',
         '        }',
         '',
         '        case CR_SUBCLASS: {   // R230: the subclass offer',
         '            TextOutA(dc, 20, py, "CHOOSE A SUBCLASS", 18);',
         '            py += 30;',
         '            for (int r = 0;',
         '                 r < cr.subclassOfferCount(); ++r) {',
         '                int sub = cr.subclassOfferAt(r);',
         '                bool ok = (sub < 0)',
         '                    || cr.subclassEligible(sub);',
         '                char srow[96];',
         '                if (sub < 0)',
         '                    snprintf(srow, sizeof srow,',
         '                             "  [%d] %-12s  (the base class)",',
         '                             r + 1,',
         '                             CLASS_NAMES[cr.classPick]);',
         '                else',
         '                    snprintf(srow, sizeof srow,',
         '                             "  [%d] %-12s  %s",',
         '                             r + 1,',
         '                             rules::subclassDef(sub).name,',
         '                             ok ? "" : "- not qualified");',
         '                SetTextColor(dc, ok ? RGB(210, 195, 165)',
         '                                    : RGB(110, 105, 95));',
         '                TextOutA(dc, 40, py, srow,',
         '                         (int)strlen(srow));',
         '                py += 26;',
         '            }',
         '            SetTextColor(dc, RGB(190, 175, 140));',
         '            TextOutA(dc, 20, VIEW_H - 60,',
         '                     "[1-4] choose   [esc] back to class",',
         '                     35);',
         '            break;',
         '        }',
         '',
         '        case CR_NAME: {',
     ])),
    ('adnd1.cpp',
     'static const char* memberClassName(const Character& c) {',
     lines([
         'static const char CLASS_INITIALS[4] = { ' + Q + 'F' + Q + ', ' + Q + 'M' + Q + ', ' + Q + 'C' + Q + ', ' + Q + 'T' + Q + ' };',
     ]),
     lines([
         'static const char CLASS_INITIALS[4] = { ' + Q + 'F' + Q + ', ' + Q + 'M' + Q + ', ' + Q + 'C' + Q + ', ' + Q + 'T' + Q + ' };',
         '',
         '// R230: the member display class - the registry',
         '// subclass name when set, the base class otherwise',
         'static const char* memberClassName(const Character& c) {',
         '    if (c.subclass >= 0)',
         '        return rules::subclassDef(c.subclass).name;',
         '    return CLASS_NAMES[c.classIndex];',
         '}',
     ])),
    ('adnd1.cpp',
     'cr.makeSubclassMember(cr.subPick)',
     lines([
         '    Character c = cr.makeMember(cr.classPick);',
     ]),
     lines([
         '    Character c = cr.subPick >= 0',
         '        ? cr.makeSubclassMember(cr.subPick)',
         '        : cr.makeMember(cr.classPick);',
     ])),
    ('adnd1.cpp',
     'memberClassName(c),',
     lines([
         '                     c.name.c_str(), CLASS_NAMES[c.classIndex],',
     ]),
     lines([
         '                     c.name.c_str(), memberClassName(c),',
     ])),
    ('adnd1.cpp',
     'memberClassName(c), c.startAge);',
     lines([
         '             rules::raceName((rules::CharRace)c.race),',
         '             CLASS_NAMES[c.classIndex], c.startAge);',
     ]),
     lines([
         '             rules::raceName((rules::CharRace)c.race),',
         '             memberClassName(c), c.startAge);',
     ])),
    ('game/party.h',
     '    int  subclass = -1;',
     lines([
         '    int  classIndex = 0;',
         '    int  xp   = 0;',
     ]),
     lines([
         '    int  classIndex = 0;',
         '    // R230: the registry subclass (rules::Subclass;',
         '    // -1 = a plain class member; v1 saves load -1)',
         '    int  subclass = -1;',
         '    int  xp   = 0;',
     ])),
    ('game/state_core.cpp',
     'fprintf(f, "subclass ',
     lines([
         '            if (c.race != 0)',
         '                fprintf(f, "race %d' + BS + 'n", c.race);',
     ]),
     lines([
         '            if (c.race != 0)',
         '                fprintf(f, "race %d' + BS + 'n", c.race);',
         '            // R230: the registry subclass (only when set -',
         '            // v1 saves carry no line and load as none)',
         '            if (c.subclass != -1)',
         '                fprintf(f, "subclass %d' + BS + 'n", c.subclass);',
     ])),
    ('game/state_core.cpp',
     'strcmp(tag, "subclass") == 0',
     lines([
         '                    c.race = rc;',
         '                } else if (strcmp(tag, "age") == 0) {',
     ]),
     lines([
         '                    c.race = rc;',
         '                } else if (strcmp(tag, "subclass") == 0) {',
         '                    int sb = -1;',
         '                    if (fscanf(f, "%d", &sb) != 1 ||',
         '                        sb < -1 ||',
         '                        sb >= rules::SUB_COUNT) {',
         '                        fclose(f);',
         '                        log.add("adnd1.sav is corrupt (subclass).");',
         '                        return false;',
         '                    }',
         '                    c.subclass = sb;',
         '                } else if (strcmp(tag, "age") == 0) {',
     ])),
    ('game/state_core.cpp',
     'c.subclass == rules::SUB_DRUID',
     lines([
         '        for (auto& c : party.members) {',
         '            if (c.classIndex != 1 && c.classIndex != 2) continue;',
         '            spells::SpellClass sc = c.classIndex == 1',
         '                ? spells::SPELL_MU : spells::SPELL_CLERIC;',
     ]),
     lines([
         '        for (auto& c : party.members) {',
         '            if (c.classIndex != 1 && c.classIndex != 2) continue;',
         '            // R230: the druid and illusionist read their own',
         '            // tables (the R228/R229 seams); plain members the',
         '            // base-class tables',
         '            spells::SpellClass sc =',
         '                c.subclass == rules::SUB_DRUID',
         '                    ? spells::SPELL_DRUID',
         '                    : c.subclass == rules::SUB_ILLUSIONIST',
         '                        ? spells::SPELL_ILLUSIONIST',
         '                        : c.classIndex == 1',
         '                            ? spells::SPELL_MU',
         '                            : spells::SPELL_CLERIC;',
     ])),
    ('regtest.cpp',
     'R230 subclass creation seam audit',
     lines([
         '        printf("R180 qualification and race gates audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
     ]),
     lines([
         '        printf("R180 qualification and race gates audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
         '',
         '    // ---- R230: the subclass creation seam audit ----',
         '    // The runtime base classes, the con classes, the',
         '    // starting-age bands, the two-dice flags, the hit',
         '    // dice, the player-eligibility gate (Table I with',
         '    // Table II agreement), and the effective level cap',
         '    // (Table II with the footnote-8 gnome conditional).',
         '    {',
         '        int bad = 0;',
         '        static const int kBase[6] = {',
         '            0, 0, 2, 1, 3, 0',
         '        };',
         '        static const int kCon[6] = {',
         '            0, 0, 2, 1, 3, 3',
         '        };',
         '        static const int kAge[6] = {',
         '            15, 15, 18, 24, 18, 15',
         '        };',
         '        static const int kTwo[6] = {',
         '            0, 1, 0, 0, 0, 1',
         '        };',
         '        static const int kDie[6] = {',
         '            10, 8, 8, 4, 6, 4',
         '        };',
         '        // Table I, flat 42 (the R180 walk)',
         '        static const int kAllowed[42] = {',
         '            1, 0, 0, 0, 0, 0, 0,',
         '            1, 0, 0, 0, 1, 0, 0,',
         '            1, 0, 0, 0, 1, 0, 0,',
         '            1, 0, 0, 1, 0, 0, 0,',
         '            1, 1, 1, 1, 1, 0, 1,',
         '            1, 0, 0, 0, 0, 0, 0',
         '        };',
         '        // the runtime base classes (the monk rides',
         '        // fighter - the JUDGMENT)',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassRuntimeBase(i)',
         '                != kBase[i]) ++bad;',
         '        // the con classes (paladin/ranger the fighter',
         '        // group; the monk is not - the registry pin)',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassConClass(i)',
         '                != kCon[i]) ++bad;',
         '        // the starting-age bands',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassStartAgeBase(i)',
         '                != kAge[i]) ++bad;',
         '        // the two-dice flags (ranger, monk)',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassTwoDiceFirstLevel(i)',
         '                != kTwo[i]) ++bad;',
         '        // the hit dice (d10 d8 d8 d4 d6 d4)',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassHitDie(i)',
         '                != kDie[i]) ++bad;',
         '        // the player-eligibility gate agrees with the',
         '        // R180 Table I walk, cell by cell',
         '        for (int i = 0; i <= 5; ++i)',
         '            for (int r = 0; r <= 6; ++r)',
         '                if (rules::subclassPlayerAllowed(',
         '                        i, (rules::CharRace)r)',
         '                    != kAllowed[i * 7 + r]) ++bad;',
         '        // the effective caps: the Table II matrix with',
         '        // the footnote-8 gnome illusionist conditional',
         '        if (rules::subclassLevelCapFor(',
         '                3, (rules::CharRace)3, 16, 18) != 5) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                3, (rules::CharRace)3, 17, 16) != 5) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                3, (rules::CharRace)3, 17, 17) != 6) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                3, (rules::CharRace)0, 18, 18) != -1) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                3, (rules::CharRace)1, 18, 18) != 0) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                0, (rules::CharRace)0, 18, 18) != -1) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                0, (rules::CharRace)1, 18, 18) != 0) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                1, (rules::CharRace)4, 18, 18) != 8) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                2, (rules::CharRace)5, 18, 18) != -6) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                4, (rules::CharRace)2, 18, 18) != 10) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                4, (rules::CharRace)6, 18, 18) != -1) ++bad;',
         '        if (rules::subclassLevelCapFor(',
         '                5, (rules::CharRace)0, 18, 18) != -1) ++bad;',
         '        // the clamps',
         '        if (rules::subclassPlayerAllowed(',
         '                99, (rules::CharRace)99) != 0) ++bad;',
         '        if (rules::subclassPlayerAllowed(',
         '                -1, (rules::CharRace)-1) != 1) ++bad;',
         '        if (rules::subclassHitDie(-1) != 10) ++bad;',
         '        if (rules::subclassHitDie(99) != 4) ++bad;',
         '        if (rules::subclassRuntimeBase(-3) != 0) ++bad;',
         '        if (rules::subclassRuntimeBase(99) != 0) ++bad;',
         '        printf("R230 subclass creation seam audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
     ])),
    ('tools/phb_gap_report.md',
     'R230 the subclass creation gates -',
     lines([
         '- [ ] the subclass creation gates - no',
         '      character can yet BE a paladin, ranger,',
         '      druid, illusionist, assassin, monk or',
         '      bard (registry + gates + specials all',
         '      data-only).',
     ]),
     lines([
         '- [x] R230 the subclass creation gates -',
         '      WIRED: rules/subclassgates.h gains the',
         '      creation seam (the runtime base-class map -',
         '      the monk rides fighter, the JUDGMENT - the',
         '      con class, the starting-age band, the',
         '      two-dice flag, the subclass hit die, the',
         '      player-eligibility gate, the Table II',
         '      effective cap with the footnote-8 gnome',
         '      conditional); creation gains the',
         '      CR_SUBCLASS stage (the base class, then',
         '      its registry subclasses; the monk rides',
         '      the fighter list), the eligibility gate',
         '      (adjusted minimums + Race Table I),',
         '      makeSubclassMember (the subclass hit die,',
         '      the ranger/monk two dice each with the',
         '      per-die con adjustment, the',
         '      druid/illusionist slot fills, the',
         '      illusionist L1 book, the monk kit), the',
         '      save/load subclass line (v1-compatible),',
         '      the restoreSlots druid/illusionist',
         '      branches, and the member class-name',
         '      display. The alignment gates stay',
         '      data-only (no alignment concept yet) and',
         '      the bard (Appendix II) stays',
         '      uncreatable; leveling, the specials hooks',
         '      and multi/dual-class are the next arc',
         '      items. Census 146.',
     ])),
]


# the base check: the R229 box is closed (census 145)
g = open('tools/phb_gap_report.md').read()
assert g.count('Census 145.') == 1, 'wrong base: the R229 box is not closed'

for p in PATCHES:
    patch(p[0], p[1], p[2], p[3])

print('R230 splice: ALL OK (applied %d, already %d)' % (APPLIED, ALREADY))
print('R230 note: 18 patches; a character can now BE a registry subclass -')
print('the creation seam, the CR_SUBCLASS stage, makeSubclassMember,')
print('the save/load line, the slot branches, the audit and the box flip.')
print('commit: R230: the subclass creation gates - a character can BE a paladin, ranger, druid, illusionist, assassin or monk (census 146)')
