#!/usr/bin/env python3
# R231 splice: the subclass leveling wire. A registry
# subclass member now levels on the printed subclass XP
# ladder: rules/subclassgates.h gains the leveling seam
# (subclassXpToAttain - the printed attain rows with
# the adders, a private flat copy per the R230 EVAL
# NOTE; subclassFixedHpLevel; subclassHpBeyondFixed;
# subclassLevelStop (the R179 levelCap pins - the
# name-cap analog, the druid 14 hierarchy ceiling);
# subclassLevelCapTotal - the leveling stop minus a
# positive Table II race cap and the footnote-8
# gnome conditional); gainXp queues promotions on
# registry ladder and applies the printed +10%
# subclass experience bonus when the R180 rule is
# earned (the illusionist, assassin and monk print
# none); trainNext promotes on the registry ladder
# (the subclass hit die and con class; the fixed hp
# past the fixed-hp level; the illusionist studies
# from the R229 roster); the energy-drain trick resets
# to the registry level start; the R231 battery audit
# walks the seam; the gap-report box flips. 11 patches;
# idempotent (markers = the new content); zero
# backslashes. Run on 1701912 (R230 landed).
# JUDGMENTs: the +10% bonus amount (the PHB percentage
# convention - the R180 layer pins the rules, not the
# amounts); the base-class convention stands (leveling
# stops at the fixed-hp level, as the engine stops
# plain members at the name cap); the prime-requisite
# % keeps the base-class ladder (the subclass primes
# match their base primes); the henchman stays
# base-class.

NL = chr(10)
Q = chr(39)
BS = chr(92)
DQ = chr(34)
APPLIED = 0
ALREADY = 0


def patch(path, marker, old, new):
    # the R228 pattern: marker = a unique single-line snippet
    # of the NEW content (absent pre-patch, present post)
    global APPLIED, ALREADY
    assert NL not in marker, 'marker spans a newline: ' + marker
    s = open(path).read()
    if marker in s:
        ALREADY += 1
        return
    if old not in s:
        raise SystemExit('R231 FAIL: %s anchor not found in %s'
                         % (marker, path))
    if s.count(old) != 1:
        raise SystemExit('R231 FAIL: %s anchor not unique in %s'
                         % (marker, path))
    t = s.replace(old, new)
    if marker not in t:
        raise SystemExit('R231 FAIL: %s marker missing post-patch'
                         % marker)
    open(path, 'w').write(t)
    APPLIED += 1


def lines(ls):
    return NL.join(ls)


PATCHES = [
    ('rules/subclassgates.h',
     'inline int subclassXpToAttain(int sub, int level) {',
     lines([
         '} // namespace rules',
     ]),
     lines([
         '',
         '// ---------------------------------------------------------------------------',
         '// R231: the leveling seam. The registry XP ladders',
         '// become the member leveling path: the printed XP',
         '// attain rows (the R176 convention), the adders',
         '// past them, the fixed-hp levels (past them the',
         '// fixed hp per level), and the effective leveling',
         '// stop (the R179 levelCap pins) minus the Race Table',
         '// II cap and the footnote-8 gnome conditional.',
         '//',
         '// EVAL NOTE (the R230 convention): plain ints and',
         '// private flat copies - the audit evaluator cannot',
         '// read the : int enums or the SubclassDef structs',
         '// the R179 registry carries; the battery pins the',
         '// copies against the same printed walks.',
         '// ---------------------------------------------------------------------------',
         '',
         '// The XP to ATTAIN the level (the printed band',
         '// lower bound - 1). Past the printed rows the',
         '// adder applies; adder 0 (druid, assassin, monk):',
         '// the top row repeats - the printed top is the',
         '// ceiling. Ragged rows pad with 0 (never read:',
         '// kLen guards).',
         'inline int subclassXpToAttain(int sub, int level) {',
         '    static const int kLen[6] = {',
         '        11, 12, 14, 12, 15, 17',
         '    };',
         '    static const int kXp[6][17] = {',
         '        { 0, 2750, 5500, 12000, 24000, 45000,',
         '          95000, 175000, 350000, 700000, 1050000,',
         '          0, 0, 0, 0, 0, 0 },',
         '        { 0, 2250, 4500, 10000, 20000, 40000,',
         '          90000, 150000, 225000, 325000, 650000,',
         '          975000, 0, 0, 0, 0, 0 },',
         '        { 0, 2000, 4000, 7500, 12500, 20000,',
         '          35000, 60000, 90000, 125000, 200000,',
         '          300000, 750000, 1500000, 0, 0, 0 },',
         '        { 0, 2250, 4500, 9000, 18000, 35000,',
         '          60000, 95000, 145000, 220000, 440000,',
         '          660000, 0, 0, 0, 0, 0 },',
         '        { 0, 1500, 3000, 6000, 12000, 25000,',
         '          50000, 100000, 200000, 300000, 425000,',
         '          575000, 750000, 1000000, 1500000, 0, 0 },',
         '        { 0, 2250, 4750, 10000, 22500, 47500,',
         '          98000, 200000, 350000, 500000, 700000,',
         '          950000, 1250000, 1750000, 2250000,',
         '          2750000, 3250000 }',
         '    };',
         '    static const int kAdd[6] = {',
         '        350000, 325000, 0, 220000, 0, 0',
         '    };',
         '    int si = sub;',
         '    if (si < 0) si = 0;',
         '    if (si > 5) si = 5;',
         '    if (level <= 1) return 0;',
         '    int n = kLen[si];',
         '    if (level <= n) return kXp[si][level - 1];',
         '    return kXp[si][n - 1] + (level - n) * kAdd[si];',
         '}',
         '',
         '// The fixed-hp level (the R179 levelCap pin: past',
         '// it the fixed hp per level): paladin 9, ranger',
         '// 10, druid 9, illusionist 10, assassin 10, monk',
         '// 17 (the monk rolls through all 17).',
         'inline int subclassFixedHpLevel(int sub) {',
         '    static const int kFixed[6] = {',
         '        9, 10, 9, 10, 10, 17',
         '    };',
         '    int si = sub;',
         '    if (si < 0) si = 0;',
         '    if (si > 5) si = 5;',
         '    return kFixed[si];',
         '}',
         '',
         '// The fixed hp per level past the fixed-hp level',
         '// (the R179 hpBeyondCap pin); the monk 0.',
         'inline int subclassHpBeyondFixed(int sub) {',
         '    static const int kHpB[6] = {',
         '        3, 2, 2, 1, 2, 0',
         '    };',
         '    int si = sub;',
         '    if (si < 0) si = 0;',
         '    if (si > 5) si = 5;',
         '    return kHpB[si];',
         '}',
         '',
         '// The leveling stop (the R179 levelCap pin: the',
         '// name-cap analog - paladin 9, ranger 10, druid 14',
         '// the hierarchy ceiling, illusionist 10, assassin',
         '// 10, monk 17). The engine convention stops plain',
         '// members at the name cap; this is the subclass',
         '// analog. NOTE the druid: leveling runs to 14 but',
         '// the fixed hp starts at the 9th (the print pin -',
         '// the two levels differ for the druid only).',
         'inline int subclassLevelStop(int sub) {',
         '    static const int kStop[6] = {',
         '        9, 10, 14, 10, 10, 17',
         '    };',
         '    int si = sub;',
         '    if (si < 0) si = 0;',
         '    if (si > 5) si = 5;',
         '    return kStop[si];',
         '}',
         '',
         '// The effective leveling cap: the leveling stop,',
         '// lowered by a positive Race Table II cap (the',
         '// footnote-8 gnome conditional included).',
         'inline int subclassLevelCapTotal(int sub, CharRace r,',
         '                                 int intScore,',
         '                                 int dexScore) {',
         '    int cap = subclassLevelStop(sub);',
         '    int rc = subclassLevelCapFor(sub, r,',
         '                                 intScore, dexScore);',
         '    if (rc > 0 && rc < cap) cap = rc;',
         '    return cap;',
         '}',
         '',
         '} // namespace rules',
     ])),
    ('game/party.h',
     'the subclass leveling seam',
     lines([
         '#include "../rules/classes.h"',
     ]),
     lines([
         '#include "../rules/classes.h"',
         '#include "../rules/subclassgates.h"  // R231: the subclass leveling seam',
     ])),
    ('game/party.h',
     'rules::subclassXpBonusEarned(c.subclass,',
     lines([
         '            int pct = rules::primeRequisitePct(',
         '                (uint8_t)primeAb);',
         '            int gained = amount + (amount * pct) / 100;',
         '            if (gained < 0) gained = 0;   // penalty floors at 0',
     ]),
     lines([
         '            int pct = rules::primeRequisitePct(',
         '                (uint8_t)primeAb);',
         '            int gained = amount + (amount * pct) / 100;',
         '            // R231: the printed subclass experience bonus',
         '            // - +10% when the R180 rule is earned (the',
         '            // PHB percentage convention); the illusionist,',
         '            // assassin and monk print none',
         '            if (c.subclass >= 0 &&',
         '                rules::subclassXpBonusEarned(c.subclass,',
         '                                             c.abilities))',
         '                gained += amount / 10;',
         '            if (gained < 0) gained = 0;   // penalty floors at 0',
     ])),
    ('game/party.h',
     '// R231: the subclass ladder - the registry XP',
     lines([
         '            int cap = rules::CLASS_LEVEL_CAP[c.classIndex];',
         '            if (c.level < cap &&',
         '                c.xp >= rules::xpForLevel(c.classIndex,',
         '                                          c.level + 1) &&',
         '                !isQueuedForTraining((int)(&c - members.data()))) {',
     ]),
     lines([
         '            // R231: the subclass ladder - the registry XP',
         '            // table and the effective level cap (Table II',
         '            // with the footnote-8 gnome conditional); plain',
         '            // members read the base-class table',
         '            int cap = rules::CLASS_LEVEL_CAP[c.classIndex];',
         '            int need = rules::xpForLevel(c.classIndex,',
         '                                        c.level + 1);',
         '            if (c.subclass >= 0) {',
         '                cap = rules::subclassLevelCapTotal(',
         '                    c.subclass, (rules::CharRace)c.race,',
         '                    c.abilities.int_, c.abilities.dex);',
         '                need = rules::subclassXpToAttain(c.subclass,',
         '                                                c.level + 1);',
         '            }',
         '            if (c.level < cap &&',
         '                c.xp >= need &&',
         '                !isQueuedForTraining((int)(&c - members.data()))) {',
     ])),
    ('game/party.h',
     '// R231: the subclass stale check reads the',
     lines([
         '            int cap = rules::CLASS_LEVEL_CAP[c.classIndex];',
         '            if (c.hp <= 0 || c.level >= cap ||',
         '                c.xp < rules::xpForLevel(c.classIndex,',
         '                                         c.level + 1))',
         '                continue;   // stale entry - try the next',
     ]),
     lines([
         '            // R231: the subclass stale check reads the',
         '            // registry ladder',
         '            int cap = rules::CLASS_LEVEL_CAP[c.classIndex];',
         '            int need = rules::xpForLevel(c.classIndex,',
         '                                        c.level + 1);',
         '            if (c.subclass >= 0) {',
         '                cap = rules::subclassLevelCapTotal(',
         '                    c.subclass, (rules::CharRace)c.race,',
         '                    c.abilities.int_, c.abilities.dex);',
         '                need = rules::subclassXpToAttain(c.subclass,',
         '                                                c.level + 1);',
         '            }',
         '            if (c.hp <= 0 || c.level >= cap ||',
         '                c.xp < need)',
         '                continue;   // stale entry - try the next',
     ])),
    ('game/party.h',
     '// R231: the subclass promotion die - the',
     lines([
         '            ++c.level;',
         '            int conAdj = rules::conHPAdjustment(c.classIndex,',
         '                                                c.abilities.con);',
         '            int die = rules::rollHitPoints(c.classIndex,',
         '                                           c.level, conAdj, dice);',
         '            c.maxHp += die;',
         '            c.hp += die;',
     ]),
     lines([
         '            ++c.level;',
         '            // R231: the subclass promotion die - the',
         '            // registry hit die and con class; past the',
         '            // fixed-hp level the fixed hp + conAdj (the',
         '            // R179 pins); the per-die floor is 1',
         '            int conAdj;',
         '            int die;',
         '            if (c.subclass >= 0) {',
         '                conAdj = rules::conHPAdjustment(',
         '                    rules::subclassConClass(c.subclass),',
         '                    c.abilities.con);',
         '                if (c.level >',
         '                        rules::subclassFixedHpLevel(',
         '                            c.subclass)) {',
         '                    die = rules::subclassHpBeyondFixed(',
         '                              c.subclass) + conAdj;',
         '                } else {',
         '                    die = (int)dice.roll(',
         '                              1, (uint32_t)rules::subclassHitDie(',
         '                                      c.subclass), 0) + conAdj;',
         '                }',
         '                if (die < 1) die = 1;',
         '            } else {',
         '                conAdj = rules::conHPAdjustment(',
         '                    c.classIndex, c.abilities.con);',
         '                die = rules::rollHitPoints(c.classIndex,',
         '                                           c.level, conAdj, dice);',
         '            }',
         '            c.maxHp += die;',
         '            c.hp += die;',
     ])),
    ('game/party.h',
     'spells::SpellClass wanted =',
     lines([
         '            if (c.classIndex == 1) {',
         '                int maxLv = spells::maxSpellLevelForInt(',
         '                    c.abilities.int_);',
         '                std::vector<int> cands;',
         '                for (int id = 0; id < spells::SPELL_COUNT;',
         '                     ++id) {',
         '                    const spells::SpellDef& s =',
         '                        spells::spell((spells::SpellId)id);',
         '                    if (s.sclass != spells::SPELL_MU)',
         '                        continue;',
     ]),
     lines([
         '            if (c.classIndex == 1) {',
         '                // R231: the illusionist studies from the',
         '                // illusionist roster (the R229 registry)',
         '                spells::SpellClass wanted =',
         '                    c.subclass == rules::SUB_ILLUSIONIST',
         '                        ? spells::SPELL_ILLUSIONIST',
         '                        : spells::SPELL_MU;',
         '                int maxLv = spells::maxSpellLevelForInt(',
         '                    c.abilities.int_);',
         '                std::vector<int> cands;',
         '                for (int id = 0; id < spells::SPELL_COUNT;',
         '                     ++id) {',
         '                    const spells::SpellDef& s =',
         '                        spells::spell((spells::SpellId)id);',
         '                    if (s.sclass != wanted)',
         '                        continue;',
     ])),
    ('game/party.h',
     '// R231: cap/need carry the subclass ladder from',
     lines([
         '            // XP reaching another level queues the member again',
         '            if (c.level < cap &&',
         '                c.xp >= rules::xpForLevel(c.classIndex,',
         '                                          c.level + 1))',
         '                pendingTraining.push_back(i);',
     ]),
     lines([
         '            // XP reaching another level queues the member again',
         '            // R231: cap/need carry the subclass ladder from',
         '            // the stale check above',
         '            if (c.level < cap &&',
         '                c.xp >= need)',
         '                pendingTraining.push_back(i);',
     ])),
    ('game/state_dungeon.cpp',
     '// R231: the subclass drain reads the registry',
     lines([
         '            c.xp = rules::xpForLevel(c.classIndex,',
         '                                     c.level);',
     ]),
     lines([
         '            // R231: the subclass drain reads the registry',
         '            // ladder (the level start)',
         '            c.xp = c.subclass >= 0',
         '                ? rules::subclassXpToAttain(c.subclass,',
         '                                            c.level)',
         '                : rules::xpForLevel(c.classIndex,',
         '                                    c.level);',
     ])),
    ('regtest.cpp',
     'R231 subclass leveling seam audit',
     lines([
         '        printf("R230 subclass creation seam audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
     ]),
     lines([
         '        printf("R230 subclass creation seam audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
         '',
         '    // ---- R231: the subclass leveling seam audit ----',
         '    // The printed XP attain rows cell by cell (the',
         '    // R176 convention), the adders past the rows,',
         '    // the fixed-hp levels, the fixed hp past them,',
         '    // and the effective leveling cap.',
         '    {',
         '        int bad = 0;',
         '        static const int kPal[11] = {',
         '            0, 2750, 5500, 12000, 24000,',
         '            45000, 95000, 175000, 350000, 700000,',
         '            1050000',
         '        };',
         '        static const int kRng[12] = {',
         '            0, 2250, 4500, 10000, 20000,',
         '            40000, 90000, 150000, 225000, 325000,',
         '            650000, 975000',
         '        };',
         '        static const int kDru[14] = {',
         '            0, 2000, 4000, 7500, 12500,',
         '            20000, 35000, 60000, 90000, 125000,',
         '            200000, 300000, 750000, 1500000',
         '        };',
         '        static const int kIll[12] = {',
         '            0, 2250, 4500, 9000, 18000,',
         '            35000, 60000, 95000, 145000, 220000,',
         '            440000, 660000',
         '        };',
         '        static const int kAsn[15] = {',
         '            0, 1500, 3000, 6000, 12000,',
         '            25000, 50000, 100000, 200000, 300000,',
         '            425000, 575000, 750000, 1000000,',
         '            1500000',
         '        };',
         '        static const int kMnk[17] = {',
         '            0, 2250, 4750, 10000, 22500,',
         '            47500, 98000, 200000, 350000, 500000,',
         '            700000, 950000, 1250000, 1750000,',
         '            2250000, 2750000, 3250000',
         '        };',
         '        for (int l = 1; l <= 11; ++l)',
         '            if (rules::subclassXpToAttain(0, l)',
         '                != kPal[l - 1]) ++bad;',
         '        for (int l = 1; l <= 12; ++l)',
         '            if (rules::subclassXpToAttain(1, l)',
         '                != kRng[l - 1]) ++bad;',
         '        for (int l = 1; l <= 14; ++l)',
         '            if (rules::subclassXpToAttain(2, l)',
         '                != kDru[l - 1]) ++bad;',
         '        for (int l = 1; l <= 12; ++l)',
         '            if (rules::subclassXpToAttain(3, l)',
         '                != kIll[l - 1]) ++bad;',
         '        for (int l = 1; l <= 15; ++l)',
         '            if (rules::subclassXpToAttain(4, l)',
         '                != kAsn[l - 1]) ++bad;',
         '        for (int l = 1; l <= 17; ++l)',
         '            if (rules::subclassXpToAttain(5, l)',
         '                != kMnk[l - 1]) ++bad;',
         '        // the adders past the printed rows: paladin',
         '        // 350k, ranger 325k, illusionist 220k; the',
         '        // druid, assassin and monk print none - the',
         '        // top row repeats (the ceiling)',
         '        if (rules::subclassXpToAttain(0, 12)',
         '            != 1400000) ++bad;',
         '        if (rules::subclassXpToAttain(0, 13)',
         '            != 1750000) ++bad;',
         '        if (rules::subclassXpToAttain(1, 13)',
         '            != 1300000) ++bad;',
         '        if (rules::subclassXpToAttain(3, 13)',
         '            != 880000) ++bad;',
         '        if (rules::subclassXpToAttain(2, 15)',
         '            != 1500000) ++bad;',
         '        if (rules::subclassXpToAttain(4, 16)',
         '            != 1500000) ++bad;',
         '        if (rules::subclassXpToAttain(5, 18)',
         '            != 3250000) ++bad;',
         '        // level 1 attains at 0',
         '        if (rules::subclassXpToAttain(0, 1) != 0) ++bad;',
         '        // the fixed-hp levels and the fixed hp past',
         '        // them (the R179 pins)',
         '        static const int kFix[6] = {',
         '            9, 10, 9, 10, 10, 17',
         '        };',
         '        static const int kHpB[6] = {',
         '            3, 2, 2, 1, 2, 0',
         '        };',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassFixedHpLevel(i)',
         '                != kFix[i]) ++bad;',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassHpBeyondFixed(i)',
         '                != kHpB[i]) ++bad;',
         '        // the leveling stops (the R179 levelCap pins;',
         '        // the druid 14 - the hierarchy ceiling, where',
         '        // the fixed hp starts at the 9th)',
         '        static const int kStop[6] = {',
         '            9, 10, 14, 10, 10, 17',
         '        };',
         '        for (int i = 0; i <= 5; ++i)',
         '            if (rules::subclassLevelStop(i)',
         '                != kStop[i]) ++bad;',
         '        // the effective leveling cap: the leveling',
         '        // level minus a positive Table II race cap',
         '        // (the footnote-8 gnome conditional included)',
         '        if (rules::subclassLevelCapTotal(',
         '                0, (rules::CharRace)0, 18, 18) != 9) ++bad;',
         '        if (rules::subclassLevelCapTotal(',
         '                2, (rules::CharRace)0, 18, 18) != 14) ++bad;',
         '        if (rules::subclassLevelCapTotal(',
         '                1, (rules::CharRace)4, 18, 18) != 8) ++bad;',
         '        if (rules::subclassLevelCapTotal(',
         '                3, (rules::CharRace)3, 17, 17) != 6) ++bad;',
         '        if (rules::subclassLevelCapTotal(',
         '                3, (rules::CharRace)3, 16, 18) != 5) ++bad;',
         '        if (rules::subclassLevelCapTotal(',
         '                4, (rules::CharRace)1, 18, 18) != 9) ++bad;',
         '        if (rules::subclassLevelCapTotal(',
         '                5, (rules::CharRace)0, 18, 18) != 17) ++bad;',
         '        // the clamps',
         '        if (rules::subclassXpToAttain(-1, 2)',
         '            != 2750) ++bad;',
         '        if (rules::subclassXpToAttain(99, 2)',
         '            != 2250) ++bad;',
         '        if (rules::subclassFixedHpLevel(-3) != 9) ++bad;',
         '        if (rules::subclassFixedHpLevel(99) != 17) ++bad;',
         '        if (rules::subclassLevelStop(-3) != 9) ++bad;',
         '        if (rules::subclassLevelStop(99) != 17) ++bad;',
         '        printf("R231 subclass leveling seam audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
     ])),
    ('tools/phb_gap_report.md',
     'R231 the subclass leveling wire - WIRED:',
     lines([
         '- [ ] the per-subclass specials hooks (lay on',
     ]),
     lines([
         '- [x] R231 the subclass leveling wire - WIRED:',
         '      rules/subclassgates.h gains the leveling seam',
         '      (subclassXpToAttain - the printed XP attain',
         '      rows with the adders, a private flat copy',
         '      per the R230 EVAL NOTE; subclassFixedHpLevel;',
         '      subclassHpBeyondFixed; subclassLevelStop (the',
         '      R179 levelCap pins - the name-cap analog, the',
         '      druid 14 hierarchy ceiling);',
         '      subclassLevelCapTotal - the leveling stop',
         '      minus a positive Table II race cap and the',
         '      footnote-8 gnome conditional); gainXp queues',
         '      promotions on the registry',
         '      ladder and applies the printed +10%',
         '      subclass experience bonus when the R180 rule',
         '      is earned (the illusionist, assassin and',
         '      monk print none); trainNext promotes on the',
         '      registry ladder (the subclass hit die and',
         '      con class, the fixed hp past the fixed-hp',
         '      level, the illusionist studying from the',
         '      R229 roster); the energy-drain trick resets',
         '      to the registry level start. The base-class',
         '      convention stands for plain members (the',
         '      engine stops them at the name cap) and the',
         '      henchman stays base-class. Census 147.',
         '- [ ] the per-subclass specials hooks (lay on',
     ])),
]


# the base check: the R230 box is closed (census 146)
g = open('tools/phb_gap_report.md').read()
assert g.count('Census 146.') == 1, 'wrong base: the R230 box is not closed'

for p in PATCHES:
    patch(p[0], p[1], p[2], p[3])

print('R231 splice: ALL OK (applied %d, already %d)' % (APPLIED, ALREADY))
print('R231 note: 11 patches; the registry subclasses level on the printed')
print('XP ladders - the leveling seam, the gainXp/trainNext wires, the')
print('illusionist study, the drain reset, the audit and the box flip.')
print('commit: R231: the subclass leveling wire - the registry XP ladders go live (census 147)')
