#!/usr/bin/env python3
# R232 splice: the per-subclass specials hooks. The four
# named specials go live: ai::Actor carries the registry
# subclass (toActor copies it); the monk reads the R181
# open-hand ladder (the attack rate, the Monks Table II
# damage, the flat to-hit - never modified by strength,
# the R181 pin; the engine carries no combat-form
# command, so the open hand is the class signature and
# the staff rides the pack - the JUDGMENT); the thief
# group (thief and assassin) backstabs a surprised foe in
# round one (+4 on the die, the x2..x5 multiplier - the
# surprise segment is the from-behind reading); the
# ranger adds the giant-class damage bonus (+1 hp per
# level vs the 11 listed creatures, family-name
# matching); the paladin lays on hands (2 hp per level,
# once per career day, the [F] town key, the v1-
# compatible layhands save line). The R232 battery
# audit (an engine audit, the R174 convention); the
# gap-report box flips. 17 patches; idempotent (markers
# = the new content); zero backslashes. Run on 1ca4fd2
# (R231 landed). The monk stun/kill and quivering palm
# and the ranger/paladin surprise and turn-undead
# numbers stay data (the R187 records) - a combat-form
# command round owns them.

NL = chr(10)
Q = chr(39)
BS = chr(92)
DQ = chr(34)
APPLIED = 0
ALREADY = 0


def patch(path, marker, old, new):
    # the R228 pattern: marker = a unique single-line snippet
    # of the NEW content (absent pre-patch, present post)
    global APPLIED, ALREADY
    assert NL not in marker, 'marker spans a newline: ' + marker
    s = open(path).read()
    if marker in s:
        ALREADY += 1
        return
    if old not in s:
        raise SystemExit('R232 FAIL: %s anchor not found in %s'
                         % (marker, path))
    if s.count(old) != 1:
        raise SystemExit('R232 FAIL: %s anchor not unique in %s'
                         % (marker, path))
    t = s.replace(old, new)
    if marker not in t:
        raise SystemExit('R232 FAIL: %s marker missing post-patch'
                         % marker)
    open(path, 'w').write(t)
    APPLIED += 1


def lines(ls):
    return NL.join(ls)


PATCHES = [
    ('ai/actor.h',
     'int  subclass = -1;',
     lines([
         '    int  classIndex = 0;           // CharClass index',
     ]),
     lines([
         '    int  classIndex = 0;           // CharClass index',
         '    // R232: the registry subclass (rules::Subclass; -1 = a',
         '    // plain class member) - the specials hooks read it',
         '    int  subclass = -1;',
     ])),
    ('ai/actor.h',
     'int m_monsSurprised = 0;',
     lines([
         '    int m_round = 0;',
     ]),
     lines([
         '    int m_round = 0;',
         '    int m_monsSurprised = 0;   // R232: monster-side surprise segments (round 1)',
     ])),
    ('ai/actor.cpp',
     '#include "../rules/attacksround.h"  // R232: the monk ladder',
     lines([
         '#include "../dm/encounters.h"   // R147: dm::NpcRace ints',
     ]),
     lines([
         '#include "../dm/encounters.h"   // R147: dm::NpcRace ints',
         '#include "../rules/subclasses.h"  // R232: the subclass ids',
         '#include "../rules/attacksround.h"  // R232: the monk ladder',
         '#include "../rules/subclassspecials.h"  // R232: backstab',
         '#include "../rules/palrangerspells.h"  // R232: the giant-class roster',
     ])),
    ('ai/actor.cpp',
     'if (subclass == rules::SUB_MONK) {',
     lines([
         'int Actor::attacksPerRound() const {',
         '    if (isCharacter)',
         '        return rules::meleeAttacksPerRound(classIndex, level);',
         '    return monsterAttacks;',
         '}',
     ]),
     lines([
         'int Actor::attacksPerRound() const {',
         '    if (isCharacter) {',
         '        // R232: the monk open-hand attacks - the R181',
         '        // ladder (Monks Table II); the engine round model',
         '        // carries two swing slots, so this returns the',
         '        // heavy round of the printed cycle (the turn.cpp',
         '        // convention)',
         '        if (subclass == rules::SUB_MONK) {',
         '            rules::AtkRate r =',
         '                rules::monkOpenHandAttacks(level);',
         '            return (r.attacks >= 2) ? 2 : 1;',
         '        }',
         '        return rules::meleeAttacksPerRound(classIndex, level);',
         '    }',
         '    return monsterAttacks;',
         '}',
     ])),
    ('ai/actor.cpp',
     'if (subclass == rules::SUB_MONK) return 0;',
     lines([
         'int Actor::hitAdjustment(const Actor& defender) const {',
         '    if (isCharacter) {',
         '        // R203: the per-weapon p.38 row keys on the',
     ]),
     lines([
         'int Actor::hitAdjustment(const Actor& defender) const {',
         '    if (isCharacter) {',
         '        // R232: the monk open hand - the to-hit is never',
         '        // modified by strength bonuses (the R181 pin)',
         '        if (subclass == rules::SUB_MONK) return 0;',
         '        // R203: the per-weapon p.38 row keys on the',
     ])),
    ('ai/actor.cpp',
     'static int monkOpenHandDamage(const Actor& a) {',
     lines([
         'int Encounter::resolveMelee(Actor& attacker, Actor& defender) {',
     ]),
     lines([
         '// R232: family-name matching for the giant-class roster',
         '',
         '// R232: the monk open-hand damage - the Monks Table II row',
         'static int monkOpenHandDamage(const Actor& a) {',
         '    const rules::MonkLadderRow& r =',
         '        rules::monkLadderRow(a.level);',
         '    int span = r.dmgHi - r.dmgLo + 1;',
         '    if (span <= 1) return r.dmgHi;',
         '    return (int)a.encounterDice().roll(',
         '               1, (uint32_t)span, 0) + r.dmgLo - 1;',
         '}',
         '// (the R184 caller concern): a lowercase exact match, or',
         '// a roster word as the trailing word of the name -',
         '// "hill giant" ends with " giant", "ogre mage" is exact.',
         '// A word-boundary check (" ettin", not "bettin") guards',
         '// the suffix.',
         'static bool giantClassFamilyMatch(const std::string& name) {',
         '    std::string low;',
         '    for (char ch : name)',
         '        low += (ch >= ' + Q + 'A' + Q + ' && ch <= ' + Q + 'Z' + Q + ')',
         '                ? (char)(ch + 32) : ch;',
         '    for (int i = 0; i < rules::rangerGiantClassCount();',
         '         ++i) {',
         '        std::string w = rules::rangerGiantClassName(i);',
         '        if (low == w) return true;',
         '        if (low.size() > w.size() + 1 &&',
         '            low[low.size() - w.size() - 1] == ' + Q + ' ' + Q + ' &&',
         '            low.compare(low.size() - w.size(), w.size(), w)',
         '                == 0)',
         '            return true;',
         '    }',
         '    return false;',
         '}',
         '',
         'int Encounter::resolveMelee(Actor& attacker, Actor& defender) {',
     ])),
    ('ai/actor.cpp',
     'bool backstab = attacker.isCharacter',
     lines([
         '    int toHit = attacker.toHit(defender);',
         '    int adj   = attacker.hitAdjustment(defender);',
         '    if (!rules::attackRollHits(m_dice, toHit, adj)) {',
         '        logLine(attacker.name + " misses " + defender.name);',
         '        return 0;',
         '    }',
         '',
         '    // damage',
         '    int dmg;',
         '    if (attacker.isCharacter) {',
         '        if (attacker.weaponThrown) {',
         '            // R36: hurled the weapon earlier - bare fists (1d2,',
         '            // no weapon dice or plus; logged simplification of',
         '            // the PHB unarmed rules)',
         '            dmg = (int)m_dice.roll(1, 2, 0);',
         '        } else {',
         '            const items::WeaponDef& w =',
         '                items::weapon(attacker.weapon.id);',
         '            bool large =',
         '                defender.hitDice >= 8 && !defender.isCharacter;',
         '            dmg = (int)m_dice.roll(',
         '                large ? w.lCount : w.smCount,',
         '                large ? w.lSides : w.smSides, 0);',
         '            dmg += attacker.weapon.plus;',
         '        }',
         '    } else {',
         '        dmg = (int)m_dice.roll((uint32_t)attacker.monsterDamageCount,',
         '                               (uint32_t)attacker.monsterDamageSides, 0);',
         '    }',
         '    if (dmg < 1) dmg = 1;',
     ]),
     lines([
         '    int toHit = attacker.toHit(defender);',
         '    int adj   = attacker.hitAdjustment(defender);',
         '    // R232: backstab - a thief-group character striking a',
         '    // surprised foe (round one, the monster side surprised)',
         '    // strikes from behind: +4 on the die (the R187 pin).',
         '    // The engine has no facing; the surprise segment is',
         '    // the from-behind reading - the JUDGMENT.',
         '    bool backstab = attacker.isCharacter',
         '        && attacker.classIndex == 3',
         '        && m_round == 1 && m_monsSurprised > 0;',
         '    if (backstab) adj += rules::backstabHitBonusDie();',
         '    if (!rules::attackRollHits(m_dice, toHit, adj)) {',
         '        logLine(attacker.name + " misses " + defender.name);',
         '        return 0;',
         '    }',
         '',
         '    // damage',
         '    int dmg;',
         '    if (attacker.isCharacter) {',
         '        if (attacker.weaponThrown) {',
         '            // R36: hurled the weapon earlier - bare fists (1d2,',
         '            // no weapon dice or plus; logged simplification of',
         '            // the PHB unarmed rules)',
         '            // R232: the monk reads the R181 open-hand ladder',
         '            // (Monks Table II) instead of the fist die',
         '            if (attacker.subclass == rules::SUB_MONK) {',
         '                dmg = monkOpenHandDamage(attacker);',
         '            } else {',
         '                dmg = (int)m_dice.roll(1, 2, 0);',
         '            }',
         '        } else if (attacker.subclass == rules::SUB_MONK) {',
         '            // R232: the monk fights open-handed - the ladder',
         '            // damage replaces the weapon dice. The engine',
         '            // carries no combat-form command; the open hand',
         '            // is the class signature, the staff rides the',
         '            // pack (the JUDGMENT)',
         '            dmg = monkOpenHandDamage(attacker);',
         '        } else {',
         '            const items::WeaponDef& w =',
         '                items::weapon(attacker.weapon.id);',
         '            bool large =',
         '                defender.hitDice >= 8 && !defender.isCharacter;',
         '            dmg = (int)m_dice.roll(',
         '                large ? w.lCount : w.smCount,',
         '                large ? w.lSides : w.smSides, 0);',
         '            dmg += attacker.weapon.plus;',
         '            // R232: the ranger giant-class damage bonus -',
         '            // +1 hp per level vs the 11 listed creatures',
         '            // (family-name matching, the R184 caller',
         '            // concern)',
         '            if (attacker.subclass == rules::SUB_RANGER &&',
         '                giantClassFamilyMatch(defender.name))',
         '                dmg += rules::rangerGiantClassBonus(',
         '                    attacker.level);',
         '        }',
         '    } else {',
         '        dmg = (int)m_dice.roll((uint32_t)attacker.monsterDamageCount,',
         '                               (uint32_t)attacker.monsterDamageSides, 0);',
         '    }',
         '    // R232: the backstab multiplier - the x2..x5 ladder by',
         '    // level (the R187 pin)',
         '    if (backstab)',
         '        dmg *= rules::backstabMultiplier(attacker.level);',
         '    if (dmg < 1) dmg = 1;',
     ])),
    ('ai/actor.cpp',
     'm_monsSurprised = mSurp;',
     lines([
         '    if (m_round == 1) {',
         '        rules::rollSurprise(m_dice, 0, 0, pSurp, mSurp);',
         '        if (pSurp > 0) logLine("The party is surprised (" +',
         '                               std::to_string(pSurp) + " segments)!");',
         '        if (mSurp > 0) logLine("The monsters are surprised (" +',
         '                               std::to_string(mSurp) + " segments)!");',
         '    }',
     ]),
     lines([
         '    if (m_round == 1) {',
         '        rules::rollSurprise(m_dice, 0, 0, pSurp, mSurp);',
         '        if (pSurp > 0) logLine("The party is surprised (" +',
         '                               std::to_string(pSurp) + " segments)!");',
         '        if (mSurp > 0) logLine("The monsters are surprised (" +',
         '                               std::to_string(mSurp) + " segments)!");',
         '        // R232: the backstab gate reads the monster-side',
         '        // surprise segments',
         '        m_monsSurprised = mSurp;',
         '    }',
     ])),
    ('game/party.h',
     'a.subclass    = subclass;',
     lines([
         '        a.classIndex  = classIndex;',
     ]),
     lines([
         '        a.classIndex  = classIndex;',
         '        a.subclass    = subclass;   // R232: the specials hooks',
     ])),
    ('game/party.h',
     'int  layHandsDay = -1;',
     lines([
         '    int  subclass = -1;',
         '    int  xp   = 0;',
     ]),
     lines([
         '    int  subclass = -1;',
         '    // R232: the lay-on-hands career day (-1 = never used;',
         '    // once per career day - the rest/camp day boundary)',
         '    int  layHandsDay = -1;',
         '    int  xp   = 0;',
     ])),
    ('game/appstate.h',
     'void townLayOnHands();',
     lines([
         '    void townRaiseDead();',
     ]),
     lines([
         '    void townRaiseDead();',
         '',
         '    // R232: lay on hands - the paladin heals 2 hp per level,',
         '    // once per day (the [F] town key)',
         '    void townLayOnHands();',
     ])),
    ('game/state_town.cpp',
     'void AppState::townLayOnHands(){',
     lines([
         '// ---- R81: study the carried scrolls ----',
         'void AppState::townStudyScrolls(){',
     ]),
     lines([
         '// ---- R232: lay on hands ----',
         '// The paladin heals 2 hp per level, once per day (the',
         '// career-day boundary = the rest/camp convention); the',
         '// target is the most-wounded living member.',
         'void AppState::townLayOnHands(){',
         '        if (mode != MODE_TOWN) return;',
         '        // the first living paladin',
         '        int pi = -1;',
         '        for (int i = 0; i < (int)party.members.size(); ++i) {',
         '            const Character& p = party.members[i];',
         '            if (p.hp > 0 && p.subclass == rules::SUB_PALADIN) {',
         '                pi = i;',
         '                break;',
         '            }',
         '        }',
         '        if (pi < 0) {',
         '            log.add("No paladin walks with the company.");',
         '            return;',
         '        }',
         '        Character& pal = party.members[pi];',
         '        if (pal.layHandsDay == party.careerDays) {',
         '            log.add(pal.name + " has already laid on hands "',
         '                    "today.");',
         '            return;',
         '        }',
         '        // the most-wounded living member',
         '        int ti = -1, worst = 0;',
         '        for (int i = 0; i < (int)party.members.size(); ++i) {',
         '            const Character& m = party.members[i];',
         '            if (m.hp <= 0 || m.hp >= m.maxHp) continue;',
         '            int missing = m.maxHp - m.hp;',
         '            if (missing > worst) { worst = missing; ti = i; }',
         '        }',
         '        if (ti < 0) {',
         '            log.add("The company is unhurt.");',
         '            return;',
         '        }',
         '        Character& tgt = party.members[ti];',
         '        int heal = 2 * pal.level;',
         '        if (heal > tgt.maxHp - tgt.hp)',
         '            heal = tgt.maxHp - tgt.hp;',
         '        tgt.hp += heal;',
         '        pal.layHandsDay = party.careerDays;',
         '        char buf[96];',
         '        snprintf(buf, sizeof buf,',
         '                 "%s lays on hands - %s regains %d hp "',
         '                 "(%d/%d).",',
         '                 pal.name.c_str(), tgt.name.c_str(), heal,',
         '                 tgt.hp, tgt.maxHp);',
         '        log.add(buf);',
         '    }',
         '',
         '// ---- R81: study the carried scrolls ----',
         'void AppState::townStudyScrolls(){',
     ])),
    ('game/state_core.cpp',
     'fprintf(f, "layhands %d' + BS + 'n", c.layHandsDay);',
     lines([
         '            if (c.subclass != -1)',
         '                fprintf(f, "subclass %d' + BS + 'n", c.subclass);',
     ]),
     lines([
         '            if (c.subclass != -1)',
         '                fprintf(f, "subclass %d' + BS + 'n", c.subclass);',
         '            // R232: the lay-on-hands career day (only when',
         '            // used - v1 saves carry no line and load as',
         '            // never-used)',
         '            if (c.layHandsDay >= 0)',
         '                fprintf(f, "layhands %d' + BS + 'n", c.layHandsDay);',
     ])),
    ('game/state_core.cpp',
     'strcmp(tag, "layhands") == 0',
     lines([
         '                    c.subclass = sb;',
         '                } else if (strcmp(tag, "age") == 0) {',
     ]),
     lines([
         '                    c.subclass = sb;',
         '                } else if (strcmp(tag, "layhands") == 0) {',
         '                    int lh = -1;',
         '                    if (fscanf(f, "%d", &lh) != 1 ||',
         '                        lh < 0 || lh > 2000000) {',
         '                        fclose(f);',
         '                        log.add("adnd1.sav is corrupt (layhands).");',
         '                        return false;',
         '                    }',
         '                    c.layHandsDay = lh;',
         '                } else if (strcmp(tag, "age") == 0) {',
     ])),
    ('adnd1.cpp',
     'g_app.townLayOnHands();',
     lines([
         '                    case ' + Q + 'R' + Q + ':',
         '                    case ' + Q + 'r' + Q + ':',
         '                        g_app.townRaiseDead();',
         '                        break;',
     ]),
     lines([
         '                    case ' + Q + 'R' + Q + ':',
         '                    case ' + Q + 'r' + Q + ':',
         '                        g_app.townRaiseDead();',
         '                        break;',
         '',
         '                    // R232: the paladin touch',
         '                    case ' + Q + 'F' + Q + ':',
         '                    case ' + Q + 'f' + Q + ':',
         '                        g_app.townLayOnHands();',
         '                        break;',
     ])),
    ('regtest.cpp',
     'R232 subclass specials hooks audit',
     lines([
         '        printf("R231 subclass leveling seam audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
     ]),
     lines([
         '        printf("R231 subclass leveling seam audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
         '',
         '    // ---- R232: the subclass specials hooks audit ----',
         '    // The specials the engine reads: the toActor subclass',
         '    // propagation and the monk attack rate, the monk',
         '    // open-hand ladder cells and attack slashes, the',
         '    // backstab ladder and hit bonus, the ranger',
         '    // giant-class roster and bonus, and the lay-hands',
         '    // career-day field contract (an engine audit - the',
         '    // R174 convention; the C++ battery is the gate).',
         '    {',
         '        int bad = 0;',
         '        // the toActor propagation + the monk attack rate',
         '        {',
         '            Character c;',
         '            c.subclass = rules::SUB_MONK;',
         '            c.level = 12;',
         '            ai::Actor a = c.toActor();',
         '            if (a.subclass != rules::SUB_MONK) ++bad;',
         '            if (a.attacksPerRound() != 2) ++bad;   // 12th: 5/2',
         '            c.level = 1;',
         '            a = c.toActor();',
         '            if (a.attacksPerRound() != 1) ++bad;   // 1st: 1/1',
         '            c.subclass = -1;',
         '            a = c.toActor();',
         '            if (a.subclass != -1) ++bad;',
         '            if (a.attacksPerRound() != 1) ++bad;   // fighter L1',
         '        }',
         '        // the monk open-hand ladder cells (Monks Table II)',
         '        if (rules::monkLadderRow(1).dmgLo != 1 ||',
         '            rules::monkLadderRow(1).dmgHi != 3) ++bad;',
         '        if (rules::monkLadderRow(13).dmgLo != 5 ||',
         '            rules::monkLadderRow(13).dmgHi != 17) ++bad;',
         '        if (rules::monkLadderRow(17).dmgLo != 8 ||',
         '            rules::monkLadderRow(17).dmgHi != 32) ++bad;',
         '        // the monk attack slashes (the printed cycle)',
         '        if (rules::monkOpenHandAttacks(4).attacks != 5 ||',
         '            rules::monkOpenHandAttacks(4).rounds != 4) ++bad;',
         '        if (rules::monkOpenHandAttacks(12).attacks != 5 ||',
         '            rules::monkOpenHandAttacks(12).rounds != 2) ++bad;',
         '        // the backstab ladder (double 1-4 ... quintuple',
         '        // 13-16, clamped at quintuple)',
         '        static const int kMult[16] = {',
         '            2, 2, 2, 2, 3, 3, 3, 3,',
         '            4, 4, 4, 4, 5, 5, 5, 5',
         '        };',
         '        for (int l = 1; l <= 16; ++l)',
         '            if (rules::backstabMultiplier(l)',
         '                != kMult[l - 1]) ++bad;',
         '        if (rules::backstabMultiplier(17) != 5) ++bad;',
         '        if (rules::backstabHitBonusDie() != 4) ++bad;',
         '        if (rules::backstabHitBonusPercent() != 20) ++bad;',
         '        // the assassin reads full level backstabbing',
         '        if (rules::assassinBackstabLevel(7) != 7) ++bad;',
         '        if (rules::assassinThiefSkillLevel(7) != 5) ++bad;',
         '        // the ranger giant-class roster (the R184 data',
         '        // the hook reads)',
         '        if (rules::rangerGiantClassCount() != 11) ++bad;',
         '        if (!rules::rangerIsGiantClass("ogre mage")) ++bad;',
         '        if (!rules::rangerIsGiantClass("ogre")) ++bad;',
         '        if (rules::rangerIsGiantClass("purple worm")) ++bad;',
         '        if (rules::rangerIsGiantClass("ogre ish")) ++bad;',
         '        if (rules::rangerGiantClassBonus(7) != 7) ++bad;',
         '        if (rules::rangerGiantClassBonus(0) != 0) ++bad;',
         '        // the lay-hands field contract: -1 = never used',
         '        {',
         '            Character c;',
         '            if (c.layHandsDay != -1) ++bad;',
         '            c.layHandsDay = 100;',
         '            if (c.layHandsDay == -1) ++bad;',
         '        }',
         '        printf("R232 subclass specials hooks audit: bad %d' + BS + 'n", bad);',
         '        if (bad) return 1;',
         '    }',
     ])),
    ('tools/phb_gap_report.md',
     '- [x] R232 the per-subclass specials hooks -',
     lines([
         '- [ ] the per-subclass specials hooks (lay on',
         '      hands, giant-class bonus, the monk',
         '      unarmed ladder, backstab multipliers).',
     ]),
     lines([
         '- [x] R232 the per-subclass specials hooks -',
         '      WIRED: ai::Actor carries the registry',
         '      subclass (toActor copies it); the monk',
         '      reads the R181 open-hand ladder (the',
         '      attack rate and the Monks Table II damage;',
         '      the to-hit never modified by strength -',
         '      the R181 pin; the engine carries no',
         '      combat-form command, so the open hand is',
         '      the class signature and the staff rides',
         '      the pack - the JUDGMENT); the thief group',
         '      (thief and assassin) backstabs a',
         '      surprised foe in round one (+4 on the',
         '      die, the x2..x5 multiplier - the',
         '      surprise segment is the from-behind',
         '      reading, the JUDGMENT); the ranger adds',
         '      the giant-class damage bonus (+1 hp per',
         '      level vs the 11 listed creatures,',
         '      family-name matching the R184 caller',
         '      concern); the paladin lays on hands',
         '      (2 hp per level, once per career day,',
         '      the [F] town key, the most-wounded',
         '      member, the v1-compatible layhands save',
         '      line). The monk stun/kill and quivering',
         '      palm, and the ranger/paladin surprise',
         '      and turn-undead numbers, stay data (the',
         '      R187 records) - a combat-form command',
         '      round owns them. Census 148.',
     ])),
]


# the base check: the R231 box is closed (census 147)
g = open('tools/phb_gap_report.md').read()
assert g.count('Census 147.') == 1, 'wrong base: the R231 box is not closed'

for p in PATCHES:
    patch(p[0], p[1], p[2], p[3])

print('R232 splice: ALL OK (applied %d, already %d)' % (APPLIED, ALREADY))
print('R232 note: 17 patches; the four named specials go live - the monk')
print('open hand, backstab, the giant-class bonus, lay on hands.')
print('commit: R232: the subclass specials hooks - backstab, the monk open hand, the giant-class bonus, lay on hands (census 148)')
