#!/usr/bin/env python3
# R244 splice: the III.D rods explanation prose pins.
#
# DMG pp.141-142, upload lines ~10562-10687 - the
# FIRST prose round of the EXPLANATIONS AND
# DESCRIPTIONS section (upload ~9996+): the section
# conventions of the RODS, et al. text (rods 50
# charges minus 0-9/d10-1, staves 25 minus 0-5/d6-1,
# wands 100 minus 0-19/d20-1; a completely drained
# item crumbles to powder, forever useless; the
# distance-discharge command-word rule; magical
# silence stops the device) and the per-item facts
# of the SEVEN rods: Absorption (50 spell levels,
# 1-segment casting, never recharged), Beguiling
# (2" radius, intelligence 1+, no save, 1 turn per
# charge, rechargeable), Cancellation (the 11-row
# item saving throw table - potion 20, scroll 19,
# ring 17, rod 14, staff 13, wand 15, misc magic 12,
# artifact/relic 3, armor/shield 11 (8 if +5), sword
# 9 (7 holy), misc weapon 10; drained items never
# restorable, the rod goes brittle), Lordly Might
# (10 lb, 16 Str, 3 spell-like functions at 1 charge
# each, fear 6", drain 2-8 hp; the 4 weapon forms
# +2/+1/+4/+3; the 3 mundane uses, pole to 50, 4,000
# lb, doors at 30, storm giant force; never
# recharged), Resurrection (once per day; the
# 11-class and 7-race charge tables; multi-classed
# takes the least favorable; never recharged),
# Rulership (12", 200-500 hit dice, save at
# intelligence 15 and 12 hit dice/levels, 5 segments
# to activate, 1 turn per charge, never recharged),
# and Smiting (+3, 4-11 damage, 8-22 and a 20+
# destroy vs golems with 1 charge per hit, 20+ vs
# outer-planar draws 1 charge and triples damage,
# never recharged). The seven rods are the first
# seven rows of the engine III.D table (kRods bands
# 01-19, the staff rows from 20 - cross-checked
# against the R224 rodswands.h bands in the audit).
# Patches: 4 (new rules/rodsprose.h, the regtest
# include, the audit block, the dmg-gap-report log
# entry). Census 162 -> 163.
#
# commit: R244: the III.D rods explanation prose pins pinned - DMG pp.141-142, the section conventions and the seven rods (census 163)

import sys

RP   = 'rules/rodsprose.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson); NO already-closed pre-check
# (the R235b lesson, re-caught at R237)
t = open(REG).read()
if t.count('audit: bad ') != 162 and t.count('audit: bad ') != 163:
    print('R244 FAIL: regtest census is neither 162 nor 163')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/rodsprose.h',
    '// R244: the III.D rods explanation prose',
    '// pins (DMG pp.141-142) - the section',
    '// conventions of the RODS, et al. text',
    '// (upload lines ~10562-10687) and the',
    '// per-item facts of the SEVEN rods:',
    '//   - the charges conventions: rods 50',
    '//     charges minus 0-9 (d10-1), staves',
    '//     25 minus 0-5 (d6-1), wands 100',
    '//     minus 0-19 (d20-1); an item',
    '//     completely drained crumbles to',
    '//     powder, forever useless.',
    '//   - the command-word rule for devices',
    '//     that discharge magic over a',
    '//     distance, and magical silence',
    '//     stopping such devices.',
    '//   - Rod of Absorption: absorbs 50',
    '//     spell levels, 1-segment casting,',
    '//     never recharged.',
    '//   - Rod of Beguiling: 2" radius, any',
    '//     intelligence 1+, no saving throw,',
    '//     1 turn per charge, rechargeable.',
    '//   - Rod of Cancellation: the 11-row',
    '//     item saving throw table with the',
    '//     +5 armor/shield and holy sword',
    '//     variants; drained items are not',
    '//     restorable, and the rod goes',
    '//     brittle.',
    '//   - Rod of Lordly Might: 10 pounds,',
    '//     strength 16, the 3 spell-like',
    '//     functions, the 4 weapon forms and',
    '//     the 3 mundane uses; never',
    '//     recharged.',
    '//   - Rod of Resurrection: the 11-class',
    '//     and 7-race charge tables, once',
    '//     per day, multi-classed takes the',
    '//     least favorable; never recharged.',
    '//   - Rod of Rulership: 12" radius,',
    '//     200-500 hit dice, save at',
    '//     intelligence 15 and 12 hit dice,',
    '//     5 segments to activate; never',
    '//     recharged.',
    '//   - Rod of Smiting: +3, 4-11 damage,',
    '//     the golem and outer-plane rules;',
    '//     never recharged.',
    '// JUDGMENT, named in place: of the seven',
    '// rods only Beguiling prints a',
    '// rechargeable statement; Cancellation',
    '// prints none (it goes brittle instead).',
    '// The seven rods are the first seven rows',
    '// of the engine III.D table (dm/treasure.',
    '// cpp kRods, bands 01-19); the staff rows',
    '// begin at band 20.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int rpRodChargesMax() {',
    '    // rods: 50 charges minus 0-9 (d10-1)',
    '    return 50;',
    '}',
    '',
    'inline int rpRodChargesDieLo() {',
    '    // the minus die rolls 0',
    '    return 0;',
    '}',
    '',
    'inline int rpRodChargesDieHi() {',
    '    // the minus die rolls 9',
    '    return 9;',
    '}',
    '',
    'inline int rpStaffChargesMax() {',
    '    // staves: 25 charges minus 0-5 (d6-1)',
    '    return 25;',
    '}',
    '',
    'inline int rpStaffChargesDieLo() {',
    '    // the minus die rolls 0',
    '    return 0;',
    '}',
    '',
    'inline int rpStaffChargesDieHi() {',
    '    // the minus die rolls 5',
    '    return 5;',
    '}',
    '',
    'inline int rpWandChargesMax() {',
    '    // wands: 100 charges minus 0-19 (d20-1)',
    '    return 100;',
    '}',
    '',
    'inline int rpWandChargesDieLo() {',
    '    // the minus die rolls 0',
    '    return 0;',
    '}',
    '',
    'inline int rpWandChargesDieHi() {',
    '    // the minus die rolls 19',
    '    return 19;',
    '}',
    '',
    'inline int rpDrainedCrumble() {',
    '    // completely drained: crumbles to powder,',
    '    // forever useless - printed as a rule',
    '    return 1;',
    '}',
    '',
    'inline int rpCommandWordRule() {',
    '    // distance-discharge devices need a',
    '    // command word - printed as a rule',
    '    return 1;',
    '}',
    '',
    'inline int rpSilenceBlocks() {',
    '    // magical silence stops the device',
    '    return 1;',
    '}',
    '',
    'inline int rpRodCount() {',
    '    // the rods subsection describes seven rods',
    '    return 7;',
    '}',
    '',
    'inline int rpAbsorbMaxSpellLevels() {',
    '    // Rod of Absorption: 50 spell levels',
    '    return 50;',
    '}',
    '',
    'inline int rpAbsorbCastSegments() {',
    '    // stored energy casts in 1 segment',
    '    return 1;',
    '}',
    '',
    'inline int rpAbsorbRechargeable() {',
    '    // it can never be recharged',
    '    return 0;',
    '}',
    '',
    'inline int rpBeguileRadiusInches() {',
    '    // Rod of Beguiling: 2" radius',
    '    return 2;',
    '}',
    '',
    'inline int rpBeguileMinIntelligence() {',
    '    // any intelligence whatsoever: 1 or higher',
    '    return 1;',
    '}',
    '',
    'inline int rpBeguileHasSave() {',
    '    // no saving throw',
    '    return 0;',
    '}',
    '',
    'inline int rpBeguileTurnsPerCharge() {',
    '    // each charge beguiles for 1 turn',
    '    return 1;',
    '}',
    '',
    'inline int rpBeguileRechargeable() {',
    '    // it can be recharged',
    '    return 1;',
    '}',
    '',
    'inline int rpCancSaveCount() {',
    '    // Rod of Cancellation: 11 item rows',
    '    return 11;',
    '}',
    '',
    'inline int rpCancSaveValue(int i) {',
    '    // the printed item saving throws; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 10) i = 10;',
    '    static const int t[11] = {',
    '        20, 19, 17, 14, 13, 15, 12, 3, 11, 9, 10,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rpCancArmorShieldPlus5() {',
    '    // armor or shield: 11, or 8 if +5',
    '    return 8;',
    '}',
    '',
    'inline int rpCancHolySword() {',
    '    // sword: 9, or 7 if a holy sword',
    '    return 7;',
    '}',
    '',
    'inline int rpCancDrainedRestorable() {',
    '    // drained items are not restorable,',
    '    // even by wish',
    '    return 0;',
    '}',
    '',
    'inline int rpCancRodBecomesBrittle() {',
    '    // upon the item draining, the rod',
    '    // becomes brittle, no longer potent',
    '    return 1;',
    '}',
    '',
    'inline int rpLmWeightPounds() {',
    '    // Rod of Lordly Might: 10 pounds',
    '    return 10;',
    '}',
    '',
    'inline int rpLmMinStrength() {',
    '    // 16 or greater strength to wield properly',
    '    return 16;',
    '}',
    '',
    'inline int rpLmStrBelowPenalty() {',
    '    // minus 1 to hit per point below 16',
    '    return 1;',
    '}',
    '',
    'inline int rpLmSpellLikeCount() {',
    '    // the 3 spell-like functions',
    '    return 3;',
    '}',
    '',
    'inline int rpLmSpellCostCharges() {',
    '    // each function draws off 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int rpLmFearRangeInches() {',
    '    // function 2, fear: 6" maximum range',
    '    return 6;',
    '}',
    '',
    'inline int rpLmDrainHpLo() {',
    '    // function 3, drain: 2-8 hit points',
    '    return 2;',
    '}',
    '',
    'inline int rpLmDrainHpHi() {',
    '    return 8;',
    '}',
    '',
    'inline int rpLmWeaponFormCount() {',
    '    // the 4 weapon forms',
    '    return 4;',
    '}',
    '',
    'inline int rpLmWeaponBonus(int i) {',
    '    // +2 mace, +1 flame sword, +4 battle axe,',
    '    // +3 spear; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        2, 1, 4, 3,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rpLmSpearLenMinFeet() {',
    '    // the +3 spear: 6 foot minimum',
    '    return 6;',
    '}',
    '',
    'inline int rpLmSpearLenMaxFeet() {',
    '    // 15 foot maximum',
    '    return 15;',
    '}',
    '',
    'inline int rpLmSpearHandleMaxFeet() {',
    '    // the handle lengthens up to 12 feet',
    '    return 12;',
    '}',
    '',
    'inline int rpLmMundaneUseCount() {',
    '    // the 3 mundane uses',
    '    return 3;',
    '}',
    '',
    'inline int rpLmPoleGrowthPerSegment() {',
    '    // the pole lengthens 5 feet per segment',
    '    return 5;',
    '}',
    '',
    'inline int rpLmPoleMaxFeet() {',
    '    // the pole stops at 50 feet',
    '    return 50;',
    '}',
    '',
    'inline int rpLmPoleBearPounds() {',
    '    // it bears up to 4,000 pounds',
    '    return 4000;',
    '}',
    '',
    'inline int rpLmDoorForceMaxFeet() {',
    '    // door force: planted 30 feet or less',
    '    // from the portal',
    '    return 30;',
    '}',
    '',
    'inline int rpLmRechargeable() {',
    '    // it cannot be recharged',
    '    return 0;',
    '}',
    '',
    'inline int rpLmExhaustedWeaponCeaseLo() {',
    '    // charges exhausted: weapon functions',
    '    // 2 and 3 cease (the spell-like all do)',
    '    return 2;',
    '}',
    '',
    'inline int rpLmExhaustedWeaponCeaseHi() {',
    '    return 3;',
    '}',
    '',
    'inline int rpResUsesPerDay() {',
    '    // Rod of Resurrection: once per day',
    '    return 1;',
    '}',
    '',
    'inline int rpResClassCount() {',
    '    // the charge table lists 11 classes',
    '    return 11;',
    '}',
    '',
    'inline int rpResClassCharges(int i) {',
    '    // cleric, druid, fighter, paladin, ranger,',
    '    // magic-user, illusionist, thief, assassin,',
    '    // monk, bard; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 10) i = 10;',
    '    static const int t[11] = {',
    '        1, 2, 2, 1, 2, 3, 3, 3, 4, 3, 2,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rpResRaceCount() {',
    '    // the charge table lists 7 races',
    '    return 7;',
    '}',
    '',
    'inline int rpResRaceCharges(int i) {',
    '    // dwarf, elf, gnome, half-elf, halfling,',
    '    // half-orc, human; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        3, 4, 3, 2, 2, 4, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rpResMultiLeastFavorable() {',
    '    // multi-classed uses the least favorable',
    '    return 1;',
    '}',
    '',
    'inline int rpResRechargeable() {',
    '    // it cannot be recharged',
    '    return 0;',
    '}',
    '',
    'inline int rpRuleRadiusInches() {',
    '    // Rod of Rulership: creatures within 12"',
    '    return 12;',
    '}',
    '',
    'inline int rpRuleHdLo() {',
    '    // from 200 hit dice',
    '    return 200;',
    '}',
    '',
    'inline int rpRuleHdHi() {',
    '    // to 500 hit dice',
    '    return 500;',
    '}',
    '',
    'inline int rpRuleSaveIntMin() {',
    '    // save at 15 or greater intelligence',
    '    return 15;',
    '}',
    '',
    'inline int rpRuleSaveHdMin() {',
    '    // and 12 or more hit dice/levels',
    '    return 12;',
    '}',
    '',
    'inline int rpRuleActivateSegments() {',
    '    // 5 segments to activate',
    '    return 5;',
    '}',
    '',
    'inline int rpRuleTurnsPerCharge() {',
    '    // each charge lasts 1 turn',
    '    return 1;',
    '}',
    '',
    'inline int rpRuleRechargeable() {',
    '    // it cannot be recharged',
    '    return 0;',
    '}',
    '',
    'inline int rpSmiteBonus() {',
    '    // Rod of Smiting: a +3 magic weapon',
    '    return 3;',
    '}',
    '',
    'inline int rpSmiteDamageLo() {',
    '    // 4-11 (d8 + 3) hit points',
    '    return 4;',
    '}',
    '',
    'inline int rpSmiteDamageHi() {',
    '    return 11;',
    '}',
    '',
    'inline int rpSmiteGolemDamageLo() {',
    '    // vs golems: 8-22 (2d8 + 6) hit points',
    '    return 8;',
    '}',
    '',
    'inline int rpSmiteGolemDamageHi() {',
    '    return 22;',
    '}',
    '',
    'inline int rpSmiteGolemDestroyRoll() {',
    '    // any score of 20 or better destroys',
    '    return 20;',
    '}',
    '',
    'inline int rpSmiteGolemHitChargeDrain() {',
    '    // any hit upon a golem drains 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int rpSmiteOuterTripleRoll() {',
    '    // outer planes: 20 or better',
    '    return 20;',
    '}',
    '',
    'inline int rpSmiteOuterChargeDrain() {',
    '    // draws off 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int rpSmiteOuterDamageMultiple() {',
    '    // and causes triple damage',
    '    return 3;',
    '}',
    '',
    'inline int rpSmiteRechargeable() {',
    '    // it cannot be recharged',
    '    return 0;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the regtest include ----
inc_old = [
    '#include "rules/mweapons.h"  // R243: p.131-132 the III.H misc weapons pins',
]
inc_new = [
    '#include "rules/mweapons.h"  // R243: p.131-132 the III.H misc weapons pins',
    '#include "rules/rodsprose.h"  // R244: pp.141-142 the III.D rods prose pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R244: the III.D rods explanation prose pins audit ----',
    '    // DMG pp.141-142: the section conventions',
    '    // and the seven rods of the RODS, et al.',
    '    // explanation prose.',
    '    {',
    '        int bad = 0;',
    '        // the charges conventions: rods 50 minus',
    '        // 0-9, staves 25 minus 0-5, wands 100',
    '        // minus 0-19',
    '        if (rules::rpRodChargesMax() != 50 ||',
    '            rules::rpRodChargesDieLo() != 0 ||',
    '            rules::rpRodChargesDieHi() != 9) ++bad;',
    '        if (rules::rpStaffChargesMax() != 25 ||',
    '            rules::rpStaffChargesDieLo() != 0 ||',
    '            rules::rpStaffChargesDieHi() != 5) ++bad;',
    '        if (rules::rpWandChargesMax() != 100 ||',
    '            rules::rpWandChargesDieLo() != 0 ||',
    '            rules::rpWandChargesDieHi() != 19) ++bad;',
    '        // the drained-crumble, command-word and',
    '        // silence conventions',
    '        if (rules::rpDrainedCrumble() != 1 ||',
    '            rules::rpCommandWordRule() != 1 ||',
    '            rules::rpSilenceBlocks() != 1) ++bad;',
    '        // the seven rods are the first seven rows',
    '        // of the engine III.D table - bands 01-19,',
    '        // the staff rows from 20 (the R224 pins)',
    '        if (rules::rpRodCount() != 7 ||',
    '            rules::rswRowLo(0) != 1 ||',
    '            rules::rswRowHi(6) != 19 ||',
    '            rules::rswRowLo(7) != 20) ++bad;',
    '        // Rod of Absorption',
    '        if (rules::rpAbsorbMaxSpellLevels() != 50 ||',
    '            rules::rpAbsorbCastSegments() != 1 ||',
    '            rules::rpAbsorbRechargeable() != 0) ++bad;',
    '        // Rod of Beguiling',
    '        if (rules::rpBeguileRadiusInches() != 2 ||',
    '            rules::rpBeguileMinIntelligence() != 1 ||',
    '            rules::rpBeguileHasSave() != 0 ||',
    '            rules::rpBeguileTurnsPerCharge() != 1 ||',
    '            rules::rpBeguileRechargeable() != 1) ++bad;',
    '        // Rod of Cancellation - the 11-row item',
    '        // saving throw table',
    '        static const int kCanc[11] = {',
    '            20, 19, 17, 14, 13, 15, 12, 3, 11, 9, 10,',
    '        };',
    '        if (rules::rpCancSaveCount() != 11) ++bad;',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::rpCancSaveValue(i) != kCanc[i]) ++bad;',
    '        // the +5 armor/shield and holy sword variants',
    '        if (rules::rpCancArmorShieldPlus5() != 8 ||',
    '            rules::rpCancHolySword() != 7) ++bad;',
    '        // drained items are not restorable, and the',
    '        // rod turns brittle',
    '        if (rules::rpCancDrainedRestorable() != 0 ||',
    '            rules::rpCancRodBecomesBrittle() != 1) ++bad;',
    '        // clamped reads land on the potion row below',
    '        // and the misc weapon row above',
    '        if (rules::rpCancSaveValue(-9) != 20 ||',
    '            rules::rpCancSaveValue(99) != 10) ++bad;',
    '        // Rod of Lordly Might',
    '        if (rules::rpLmWeightPounds() != 10 ||',
    '            rules::rpLmMinStrength() != 16 ||',
    '            rules::rpLmStrBelowPenalty() != 1 ||',
    '            rules::rpLmSpellLikeCount() != 3 ||',
    '            rules::rpLmSpellCostCharges() != 1 ||',
    '            rules::rpLmFearRangeInches() != 6 ||',
    '            rules::rpLmDrainHpLo() != 2 ||',
    '            rules::rpLmDrainHpHi() != 8) ++bad;',
    '        // the four weapon forms: +2 mace, +1 flame',
    '        // sword, +4 battle axe, +3 spear',
    '        static const int kLmBonus[4] = {',
    '            2, 1, 4, 3,',
    '        };',
    '        if (rules::rpLmWeaponFormCount() != 4) ++bad;',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::rpLmWeaponBonus(i) != kLmBonus[i]) ++bad;',
    '        // the spear lengths and the mundane uses',
    '        if (rules::rpLmSpearLenMinFeet() != 6 ||',
    '            rules::rpLmSpearLenMaxFeet() != 15 ||',
    '            rules::rpLmSpearHandleMaxFeet() != 12 ||',
    '            rules::rpLmMundaneUseCount() != 3 ||',
    '            rules::rpLmPoleGrowthPerSegment() != 5 ||',
    '            rules::rpLmPoleMaxFeet() != 50 ||',
    '            rules::rpLmPoleBearPounds() != 4000 ||',
    '            rules::rpLmDoorForceMaxFeet() != 30) ++bad;',
    '        // weapon functions 2 and 3 die with the',
    '        // charges, and the rod never recharges',
    '        if (rules::rpLmExhaustedWeaponCeaseLo() != 2 ||',
    '            rules::rpLmExhaustedWeaponCeaseHi() != 3 ||',
    '            rules::rpLmRechargeable() != 0) ++bad;',
    '        // clamped bonus reads land on the mace below',
    '        // and the spear above',
    '        if (rules::rpLmWeaponBonus(-9) != 2 ||',
    '            rules::rpLmWeaponBonus(99) != 3) ++bad;',
    '        // Rod of Resurrection - the charge table by',
    '        // class (11) and race (7)',
    '        static const int kResClass[11] = {',
    '            1, 2, 2, 1, 2, 3, 3, 3, 4, 3, 2,',
    '        };',
    '        static const int kResRace[7] = {',
    '            3, 4, 3, 2, 2, 4, 1,',
    '        };',
    '        if (rules::rpResUsesPerDay() != 1 ||',
    '            rules::rpResClassCount() != 11 ||',
    '            rules::rpResRaceCount() != 7) ++bad;',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::rpResClassCharges(i) != kResClass[i]) ++bad;',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::rpResRaceCharges(i) != kResRace[i]) ++bad;',
    '        // multi-classed takes the least favorable',
    '        if (rules::rpResMultiLeastFavorable() != 1 ||',
    '            rules::rpResRechargeable() != 0) ++bad;',
    '        // clamped reads land on the cleric below and',
    '        // the bard above, the dwarf below and the',
    '        // human above',
    '        if (rules::rpResClassCharges(-9) != 1 ||',
    '            rules::rpResClassCharges(99) != 2 ||',
    '            rules::rpResRaceCharges(-9) != 3 ||',
    '            rules::rpResRaceCharges(99) != 1) ++bad;',
    '        // Rod of Rulership',
    '        if (rules::rpRuleRadiusInches() != 12 ||',
    '            rules::rpRuleHdLo() != 200 ||',
    '            rules::rpRuleHdHi() != 500 ||',
    '            rules::rpRuleSaveIntMin() != 15 ||',
    '            rules::rpRuleSaveHdMin() != 12 ||',
    '            rules::rpRuleActivateSegments() != 5 ||',
    '            rules::rpRuleTurnsPerCharge() != 1 ||',
    '            rules::rpRuleRechargeable() != 0) ++bad;',
    '        // Rod of Smiting',
    '        if (rules::rpSmiteBonus() != 3 ||',
    '            rules::rpSmiteDamageLo() != 4 ||',
    '            rules::rpSmiteDamageHi() != 11 ||',
    '            rules::rpSmiteGolemDamageLo() != 8 ||',
    '            rules::rpSmiteGolemDamageHi() != 22 ||',
    '            rules::rpSmiteGolemDestroyRoll() != 20 ||',
    '            rules::rpSmiteGolemHitChargeDrain() != 1 ||',
    '            rules::rpSmiteOuterTripleRoll() != 20 ||',
    '            rules::rpSmiteOuterChargeDrain() != 1 ||',
    '            rules::rpSmiteOuterDamageMultiple() != 3 ||',
    '            rules::rpSmiteRechargeable() != 0) ++bad;',
    '        printf("R244 rods prose pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg gap report log entry ----
gap_old = [
    'wands and misc item explanation prose),',
    'or the next ranked gap.',
]
gap_new = [
    'wands and misc item explanation prose),',
    'or the next ranked gap.',
    '',
    'R244 landed the III.D rods explanation',
    'prose pins (DMG pp.141-142, upload',
    'lines ~10562-10687 - the FIRST prose',
    'round of the EXPLANATIONS AND',
    'DESCRIPTIONS section, upload ~9996+).',
    'rules/rodsprose.h (the grenade.h',
    'pattern, rp prefix): the section',
    'conventions (rods 50 charges minus',
    '0-9/d10-1, staves 25 minus 0-5/d6-1,',
    'wands 100 minus 0-19/d20-1 - six',
    'accessors; the completely drained',
    'item crumbles to powder, the',
    'distance-discharge command-word rule,',
    'magical silence stops the device) and',
    'the per-item facts of the SEVEN rods:',
    'Absorption (50 spell levels,',
    '1-segment casting, never recharged),',
    'Beguiling (2" radius, intelligence 1+,',
    'no save, 1 turn per charge,',
    'rechargeable), Cancellation (the 11-row',
    'item saving throw table - potion 20,',
    'scroll 19, ring 17, rod 14, staff 13,',
    'wand 15, misc magic 12, artifact/relic',
    '3, armor/shield 11 (8 if +5), sword 9',
    '(7 holy), misc weapon 10; drained',
    'items never restorable, the rod goes',
    'brittle), Lordly Might (10 lb, 16 Str,',
    '3 spell-like functions at 1 charge',
    'each, fear 6", drain 2-8 hp; the 4',
    'weapon forms +2/+1/+4/+3; the 3',
    'mundane uses, pole to 50 ft, 4,000 lb,',
    'doors at 30 ft, storm giant force;',
    'never recharged), Resurrection (once',
    'per day; the 11-class and 7-race',
    'charge tables; multi-classed takes the',
    'least favorable; never recharged),',
    'Rulership (12", 200-500 hit dice, save',
    'at intelligence 15 and 12 hit',
    'dice/levels, 5 segments to activate,',
    '1 turn per charge, never recharged),',
    'Smiting (+3, 4-11 damage, 8-22 and a',
    '20+ destroy vs golems with 1 charge',
    'per hit, 20+ vs outer-planar draws 1',
    'charge and triples damage, never',
    'recharged). The seven rods are the',
    'first seven rows of the engine III.D',
    'table (kRods bands 01-19, the staff',
    'rows from 20 - cross-checked against',
    'the R224 rodswands.h bands in the',
    'audit). New R244 battery audit;',
    'census 163. Next: R245 - the staves',
    'explanation prose (upload ~10688+),',
    'then the wands (upload ~10786+); the',
    'potions/scrolls/rings explanation prose',
    '(upload ~9998-10561) is also still',
    'open, as is the misc magic item',
    'explanation prose (upload ~10949+).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence,
# the R228 lesson)
marker = 'R244: the III.D rods explanation prose'
try:
    t = open(RP).read()
    if marker in t:
        already += 1
    else:
        print('R244 FAIL: rules/rodsprose.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(RP, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R244 audit', audit_old, audit_new),
    (GAP, 'the R244 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text (the R233
    # lesson: append-style patches leave the old text
    # inside the new)
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R244 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 163:
        print('R244 FAIL: census is not 163')
        sys.exit(1)
    if t.count('R244 rods prose pins audit') != 1:
        print('R244 FAIL: the R244 audit line must appear once')
        sys.exit(1)
    if t.count('rules/rodsprose.h') != 1:
        print('R244 FAIL: the rodsprose include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R244 landed the III.D rods explanation') != 1:
        print('R244 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(RP).read()
    if 'namespace rules' not in h or h.count('inline int rp') != 74:
        print('R244 FAIL: the header shape is wrong')
        sys.exit(1)

print('R244 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R244 note: 4 patches; the III.D rods explanation prose landed -')
print('the conventions and the seven rods; the first EXPLANATIONS prose')
print('round; census 163.')
print('commit: R244: the III.D rods explanation prose pins pinned - DMG pp.141-142, the section conventions and the seven rods (census 163)')

