#!/usr/bin/env python3
# R245 splice: the III.D staves explanation prose pins.
#
# DMG pp.142-143, upload lines ~10688-10785 - the second
# prose round of the EXPLANATIONS AND DESCRIPTIONS
# section: the staff conventions (8th level of magic-use;
# 2 segments to discharge, 8 to build up again; nominal
# damage 8d6) and the per-item facts of the SEVEN staves:
# Command (3 functions, only 2 for a magic-user; 1 charge
# per suggestion or charm, 1 per turn of control, 1 per
# 1" square of plants for 1 turn; rechargeable), Curing
# (4 functions, cure wounds 6-21 hp = 3d6+3; 1 charge
# each; once per person per day, max twice per function,
# 8 uses per 24 hours; rechargeable), the Magi (5 free
# powers, 10 at 1 charge, 4 at 2 charges; elementals 8
# hit dice, telekinesis 200 lb, +2 saves vs magic,
# absorption the only recharge), Power (6 one-charge and
# 3 two-charge powers; +2 AC and saves; smite +2 for 3-8
# hp, 1 charge doubles but 2 do not triple; paralyzation
# cone 4" long 2" wide; rechargeable), the Serpent
# (python +2 for 3-8 hp, snake 25 ft AC 3 49 hp 9" move,
# constriction 4-10 hp per round; adder +1 for 2-4 hp,
# head AC 5 20 hp for 1 turn, save versus poison or die;
# no charges, 60% pythons), Striking (+3, 4-9 = d6+3,
# bonuses 3/6/9 at 1/2/3 charges, max 3 per strike,
# rechargeable), Withering (+1, 2-5 hp, 2 charges age 10
# years, 3 wither a limb unless saved, ageless immune -
# NO recharge statement printed, unpinned). The
# retributive strike pins: globe 3" radius, damage 8/6/4
# times the spell levels (1-25) by distance band, save
# for half, 50% plane travel for the breaker, 2 items
# capable (the magi and the power). The seven staves are
# the engine kRods rows 8-14, bands 20-33, the wand rows
# from 34 - cross-checked against the R224 rodswands.h
# bands in the audit.
# Patches: 4 (new rules/stavesprose.h, the regtest
# include, the audit block, the dmg-gap-report log
# entry). Census 163 -> 164.
#
# commit: R245: the III.D staves explanation prose pins pinned - DMG pp.142-143, the staff conventions and the seven staves (census 164)

import sys

STF  = 'rules/stavesprose.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson); NO already-closed pre-check
# (the R235b lesson, re-caught at R237)
t = open(REG).read()
if t.count('audit: bad ') != 163 and t.count('audit: bad ') != 164:
    print('R245 FAIL: regtest census is neither 163 nor 164')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/stavesprose.h',
    '// R245: the III.D staves explanation prose',
    '// pins (DMG pp.142-143) - the staff',
    '// conventions and the per-item facts of',
    '// the SEVEN staves of the RODS, et al.',
    '// explanation prose (upload lines',
    '// ~10688-10785):',
    '//   - the conventions: staves function',
    '//     at the 8th level of magic-use; the',
    '//     magic functions discharge in 2',
    '//     segments and build up again in 8;',
    '//     nominal damage is 8d6.',
    '//   - Staff of Command: 3 functions, only',
    '//     2 effective for a magic-user; 1',
    '//     charge per suggestion or charm, 1',
    '//     per turn of mammal/animal control,',
    '//     1 per 1" square of plants per turn.',
    '//   - Staff of Curing: 4 functions; cure',
    '//     wounds 6-21 hit points (3d6 + 3);',
    '//     1 charge each; once per person per',
    '//     day, max twice per function, 8',
    '//     uses per 24 hours.',
    '//   - Staff of the Magi: 5 free powers',
    '//     (detect magic, enlarge, hold portal,',
    '//     light, protection from evil/good),',
    '//     10 powers at 1 charge, 4 at 2',
    '//     charges; elementals 8 hit dice;',
    '//     telekinesis 200 pounds; +2 saves',
    '//     versus magic. JUDGMENT: rechargeable',
    '//     is pinned 1 - absorption is the',
    '//     ONLY way it recharges.',
    '//   - The retributive strike (shared by',
    '//     the magi and the power): a 3" radius',
    '//     globe; damage 8/6/4 times the spell',
    '//     levels (1 to 25) by distance band;',
    '//     save for half; 50% plane travel for',
    '//     the breaker; 2 items capable.',
    '//   - Staff of Power: 6 one-charge powers',
    '//     (continual light, magic missile or',
    '//     lightning bolt, ray of enfeeblement,',
    '//     cone of cold or fireball, darkness',
    '//     5 ft radius, levitation) and 3',
    '//     two-charge powers (shield, globe of',
    '//     invulnerability, paralyzation - the',
    '//     book prints these lists in merged',
    '//     two-column lines; the counts are',
    '//     pinned, the names ride the comments).',
    '//     +2 AC and saves; smite +2 for 3-8;',
    '//     1 charge doubles, 2 do not triple;',
    '//     paralyzation cone 4" long, 2" wide.',
    '//   - Staff of the Serpent: 2 varieties;',
    '//     the python +2 for 3-8, snake 25 ft',
    '//     AC 3 49 hp 9" move, constriction',
    '//     4-10 per round; the adder +1 for',
    '//     2-4, head AC 5 20 hp for 1 turn,',
    '//     save versus poison or die; NO',
    '//     charges; 60% pythons.',
    '//   - Staff of Striking: +3; 4-9 (d6 + 3);',
    '//     bonus 3/6/9 at 1/2/3 charges; max 3',
    '//     charges per strike.',
    '//   - Staff of Withering: +1; 2-5; 2',
    '//     charges age 10 years; 3 wither a',
    '//     limb unless saved; ageless creatures',
    '//     immune. JUDGMENT: it prints NO',
    '//     recharge statement - unpinned.',
    '// The seven staves are the engine III.D',
    '// table rows 8-14 (dm/treasure.cpp kRods,',
    '// bands 20-33); the wand rows begin at',
    '// band 34.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int stfStaffLevelOfUse() {',
    '    // staves function at the 8th level of magic-use',
    '    return 8;',
    '}',
    '',
    'inline int stfDischargeSegments() {',
    '    // the magic functions discharge in 2 segments',
    '    return 2;',
    '}',
    '',
    'inline int stfRechargeSegments() {',
    '    // build up power again: 8 segments',
    '    return 8;',
    '}',
    '',
    'inline int stfNominalDamageDice() {',
    '    // nominal damage is 8d6 for fireballs,',
    '    // lightning bolts, etc.',
    '    return 8;',
    '}',
    '',
    'inline int stfNominalDamageDieFaces() {',
    '    return 6;',
    '}',
    '',
    'inline int stfStaffCount() {',
    '    // the staves subsection describes seven staves',
    '    return 7;',
    '}',
    '',
    'inline int stfCmdFunctionCount() {',
    '    // Staff of Command: 3 functions',
    '    return 3;',
    '}',
    '',
    'inline int stfCmdMuEffectiveFunctions() {',
    '    // only 2 effective for a magic-user,',
    '    // all 3 in cleric hands',
    '    return 2;',
    '}',
    '',
    'inline int stfCmdHumanInfluenceCharge() {',
    '    // each suggestion or charm: 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int stfCmdControlChargePerTurn() {',
    '    // mammal/animal control: 1 charge per',
    '    // turn or fraction thereof',
    '    return 1;',
    '}',
    '',
    'inline int stfCmdPlantAreaInches() {',
    '    // plant control: 1" square area of plants',
    '    // per 1 turn or less, at 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int stfCmdRechargeable() {',
    '    // it can be recharged',
    '    return 1;',
    '}',
    '',
    'inline int stfCureFunctionCount() {',
    '    // Staff of Curing: disease, blindness,',
    '    // wounds, insanity',
    '    return 4;',
    '}',
    '',
    'inline int stfCureWoundsHpLo() {',
    '    // cure wounds: 6-21 hit points',
    '    return 6;',
    '}',
    '',
    'inline int stfCureWoundsHpHi() {',
    '    return 21;',
    '}',
    '',
    'inline int stfCureChargePerFunction() {',
    '    // each function drains 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int stfCureUsesPerPersonPerDay() {',
    '    // once per day on any person',
    '    return 1;',
    '}',
    '',
    'inline int stfCureMaxPerFunctionPerDay() {',
    '    // no function more than twice per day',
    '    return 2;',
    '}',
    '',
    'inline int stfCureMaxPerDay() {',
    '    // only 8 functions per 24 hour period',
    '    return 8;',
    '}',
    '',
    'inline int stfCureRechargeable() {',
    '    // it can be recharged',
    '    return 1;',
    '}',
    '',
    'inline int stfMagiFreePowerCount() {',
    '    // Staff of the Magi: detect magic,',
    '    // enlarge, hold portal, light,',
    '    // protection from evil/good',
    '    return 5;',
    '}',
    '',
    'inline int stfMagiOneChargePowerCount() {',
    '    // invisibility, fireball, knock,',
    '    // lightning bolt, pyrotechnics,',
    '    // ice storm, web, wall of fire,',
    '    // dispel magic, passwall',
    '    return 10;',
    '}',
    '',
    'inline int stfMagiTwoChargePowerCount() {',
    '    // whirlwind, plane travel,',
    '    // conjure elemental, telekinesis',
    '    return 4;',
    '}',
    '',
    'inline int stfMagiElementalHitDice() {',
    '    // each conjured elemental: 8 hit dice',
    '    return 8;',
    '}',
    '',
    'inline int stfMagiTelekinesisPounds() {',
    '    // telekinesis at 8th level: 200 pounds',
    '    return 200;',
    '}',
    '',
    'inline int stfMagiSaveBonus() {',
    '    // +2 to all saving throws versus magic',
    '    return 2;',
    '}',
    '',
    'inline int stfMagiRechargeable() {',
    '    // absorption is the ONLY way it recharges',
    '    return 1;',
    '}',
    '',
    'inline int stfStrikeGlobeRadiusInches() {',
    '    // retributive strike: 3" radius globe',
    '    return 3;',
    '}',
    '',
    'inline int stfStrikeDamageMultiple(int i) {',
    '    // within 1", between 1-2", and 2-3" of',
    '    // the broken staff; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        8, 6, 4,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int stfStrikeMaxSpellLevels() {',
    '    // the spell levels of energy: 1 to 25',
    '    return 25;',
    '}',
    '',
    'inline int stfStrikeSaveHalf() {',
    '    // a save versus magic leaves one-half',
    '    // damage',
    '    return 1;',
    '}',
    '',
    'inline int stfStrikePlaneTravelPercent() {',
    '    // the breaker: 50% plane travelling',
    '    return 50;',
    '}',
    '',
    'inline int stfStrikeCapableItems() {',
    '    // the magi and the power only',
    '    return 2;',
    '}',
    '',
    'inline int stfPowerOneChargeCount() {',
    '    // Staff of Power: continual light, magic',
    '    // missile or lightning bolt, ray of',
    '    // enfeeblement, cone of cold or fireball,',
    '    // darkness 5 ft radius, levitation',
    '    return 6;',
    '}',
    '',
    'inline int stfPowerTwoChargeCount() {',
    '    // shield, globe of invulnerability,',
    '    // paralyzation',
    '    return 3;',
    '}',
    '',
    'inline int stfPowerAcSaveBonus() {',
    '    // the wielder: +2 on armor class and',
    '    // saving throws',
    '    return 2;',
    '}',
    '',
    'inline int stfPowerSmiteBonus() {',
    '    // strikes as a +2 magic weapon',
    '    return 2;',
    '}',
    '',
    'inline int stfPowerSmiteDamageLo() {',
    '    // 3-8 hit points of damage',
    '    return 3;',
    '}',
    '',
    'inline int stfPowerSmiteDamageHi() {',
    '    return 8;',
    '}',
    '',
    'inline int stfPowerSmiteDoubleChargeCost() {',
    '    // 1 charge expended: double damage',
    '    return 1;',
    '}',
    '',
    'inline int stfPowerSmiteTripleAllowed() {',
    '    // 2 charges do NOT triple the damage',
    '    return 0;',
    '}',
    '',
    'inline int stfPowerParalysisConeLengthInches() {',
    '    // the paralyzation ray: cone 4" long',
    '    return 4;',
    '}',
    '',
    'inline int stfPowerParalysisConeWidthInches() {',
    '    // and 2" wide at its base',
    '    return 2;',
    '}',
    '',
    'inline int stfPowerRechargeable() {',
    '    // it can be recharged',
    '    return 1;',
    '}',
    '',
    'inline int stfSerpentVarietyCount() {',
    '    // Staff of the Serpent: the Python and',
    '    // the Adder',
    '    return 2;',
    '}',
    '',
    'inline int stfPythonBonus() {',
    '    // the python strikes as a +2 magic weapon',
    '    return 2;',
    '}',
    '',
    'inline int stfPythonDamageLo() {',
    '    // 3-8 hit points when it hits',
    '    return 3;',
    '}',
    '',
    'inline int stfPythonDamageHi() {',
    '    return 8;',
    '}',
    '',
    'inline int stfPythonSnakeLengthFeet() {',
    '    // the constrictor snake: 25 feet long',
    '    return 25;',
    '}',
    '',
    'inline int stfPythonSnakeAc() {',
    '    return 3;',
    '}',
    '',
    'inline int stfPythonSnakeHp() {',
    '    return 49;',
    '}',
    '',
    'inline int stfPythonSnakeMoveInches() {',
    '    return 9;',
    '}',
    '',
    'inline int stfPythonTransformRounds() {',
    '    // the snake forms in 1 round',
    '    return 1;',
    '}',
    '',
    'inline int stfPythonConstrictLo() {',
    '    // constriction: 4-10 hit points per round',
    '    return 4;',
    '}',
    '',
    'inline int stfPythonConstrictHi() {',
    '    return 10;',
    '}',
    '',
    'inline int stfAdderBonus() {',
    '    // the adder strikes as a +1 magic weapon',
    '    return 1;',
    '}',
    '',
    'inline int stfAdderDamageLo() {',
    '    // 2-4 hit points when it hits',
    '    return 2;',
    '}',
    '',
    'inline int stfAdderDamageHi() {',
    '    return 4;',
    '}',
    '',
    'inline int stfAdderHeadAc() {',
    '    // the serpent head: AC 5',
    '    return 5;',
    '}',
    '',
    'inline int stfAdderHeadHp() {',
    '    return 20;',
    '}',
    '',
    'inline int stfAdderHeadTurns() {',
    '    // the head remains 1 full turn',
    '    return 1;',
    '}',
    '',
    'inline int stfAdderPoisonSaveOrDie() {',
    '    // a hit: save versus poison or be slain',
    '    return 1;',
    '}',
    '',
    'inline int stfSerpentHasCharges() {',
    '    // neither staff has or requires charges',
    '    return 0;',
    '}',
    '',
    'inline int stfSerpentPythonPercent() {',
    '    // 60% of these staves are pythons',
    '    return 60;',
    '}',
    '',
    'inline int stfStrikingBonus() {',
    '    // Staff of Striking: a +3 magic weapon',
    '    return 3;',
    '}',
    '',
    'inline int stfStrikingDamageLo() {',
    '    // 4-9 (d6 + 3) points of damage',
    '    return 4;',
    '}',
    '',
    'inline int stfStrikingDamageHi() {',
    '    return 9;',
    '}',
    '',
    'inline int stfStrikingBonusPerCharge(int i) {',
    '    // the bonus at 1, 2 and 3 charges:',
    '    // d6 + 3, d6 + 6, d6 + 9; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        3, 6, 9,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int stfStrikingMaxChargesPerStrike() {',
    '    // no more than 3 charges per strike',
    '    return 3;',
    '}',
    '',
    'inline int stfStrikingRechargeable() {',
    '    // it can be recharged',
    '    return 1;',
    '}',
    '',
    'inline int stfWitherBonus() {',
    '    // Staff of Withering: a +1 magic weapon',
    '    return 1;',
    '}',
    '',
    'inline int stfWitherDamageLo() {',
    '    // 2-5 points of damage',
    '    return 2;',
    '}',
    '',
    'inline int stfWitherDamageHi() {',
    '    return 5;',
    '}',
    '',
    'inline int stfWitherAgeYears() {',
    '    // 2 charges: the creature ages 10 years',
    '    return 10;',
    '}',
    '',
    'inline int stfWitherLimbCharges() {',
    '    // 3 charges: 1 limb withers unless it',
    '    // saves versus magic',
    '    return 3;',
    '}',
    '',
    'inline int stfWitherAgelessImmune() {',
    '    // undead, demons, devils and the like',
    '    // cannot be aged or withered',
    '    return 1;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the regtest include ----
inc_old = [
    '#include "rules/rodsprose.h"  // R244: pp.141-142 the III.D rods prose pins',
]
inc_new = [
    '#include "rules/rodsprose.h"  // R244: pp.141-142 the III.D rods prose pins',
    '#include "rules/stavesprose.h"  // R245: pp.142-143 the III.D staves prose pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R245: the III.D staves explanation prose pins audit ----',
    '    // DMG pp.142-143: the staff conventions and',
    '    // the seven staves of the RODS, et al.',
    '    // explanation prose.',
    '    {',
    '        int bad = 0;',
    '        // the conventions: 8th level, the 2/8',
    '        // segment cycle, nominal 8d6',
    '        if (rules::stfStaffLevelOfUse() != 8 ||',
    '            rules::stfDischargeSegments() != 2 ||',
    '            rules::stfRechargeSegments() != 8 ||',
    '            rules::stfNominalDamageDice() != 8 ||',
    '            rules::stfNominalDamageDieFaces() != 6) ++bad;',
    '        // the seven staves are the engine III.D',
    '        // table rows 8-14 - bands 20-33, the wand',
    '        // rows from 34 (the R224 pins)',
    '        if (rules::stfStaffCount() != 7 ||',
    '            rules::rswRowLo(7) != 20 ||',
    '            rules::rswRowHi(13) != 33 ||',
    '            rules::rswRowLo(14) != 34) ++bad;',
    '        // Staff of Command',
    '        if (rules::stfCmdFunctionCount() != 3 ||',
    '            rules::stfCmdMuEffectiveFunctions() != 2 ||',
    '            rules::stfCmdHumanInfluenceCharge() != 1 ||',
    '            rules::stfCmdControlChargePerTurn() != 1 ||',
    '            rules::stfCmdPlantAreaInches() != 1 ||',
    '            rules::stfCmdRechargeable() != 1) ++bad;',
    '        // Staff of Curing',
    '        if (rules::stfCureFunctionCount() != 4 ||',
    '            rules::stfCureWoundsHpLo() != 6 ||',
    '            rules::stfCureWoundsHpHi() != 21 ||',
    '            rules::stfCureChargePerFunction() != 1 ||',
    '            rules::stfCureUsesPerPersonPerDay() != 1 ||',
    '            rules::stfCureMaxPerFunctionPerDay() != 2 ||',
    '            rules::stfCureMaxPerDay() != 8 ||',
    '            rules::stfCureRechargeable() != 1) ++bad;',
    '        // Staff of the Magi - the three power',
    '        // lists and the facts',
    '        if (rules::stfMagiFreePowerCount() != 5 ||',
    '            rules::stfMagiOneChargePowerCount() != 10 ||',
    '            rules::stfMagiTwoChargePowerCount() != 4 ||',
    '            rules::stfMagiElementalHitDice() != 8 ||',
    '            rules::stfMagiTelekinesisPounds() != 200 ||',
    '            rules::stfMagiSaveBonus() != 2 ||',
    '            rules::stfMagiRechargeable() != 1) ++bad;',
    '        // the retributive strike - the globe, the',
    '        // 8/6/4 damage bands, save for half, the',
    '        // 50% plane travel, 2 items capable',
    '        static const int kStrike[3] = {',
    '            8, 6, 4,',
    '        };',
    '        if (rules::stfStrikeGlobeRadiusInches() != 3) ++bad;',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::stfStrikeDamageMultiple(i) != kStrike[i]) ++bad;',
    '        if (rules::stfStrikeMaxSpellLevels() != 25 ||',
    '            rules::stfStrikeSaveHalf() != 1 ||',
    '            rules::stfStrikePlaneTravelPercent() != 50 ||',
    '            rules::stfStrikeCapableItems() != 2) ++bad;',
    '        // clamped reads land on the inner band below',
    '        // and the outer band above',
    '        if (rules::stfStrikeDamageMultiple(-9) != 8 ||',
    '            rules::stfStrikeDamageMultiple(99) != 4) ++bad;',
    '        // Staff of Power',
    '        if (rules::stfPowerOneChargeCount() != 6 ||',
    '            rules::stfPowerTwoChargeCount() != 3 ||',
    '            rules::stfPowerAcSaveBonus() != 2 ||',
    '            rules::stfPowerSmiteBonus() != 2 ||',
    '            rules::stfPowerSmiteDamageLo() != 3 ||',
    '            rules::stfPowerSmiteDamageHi() != 8 ||',
    '            rules::stfPowerSmiteDoubleChargeCost() != 1 ||',
    '            rules::stfPowerSmiteTripleAllowed() != 0 ||',
    '            rules::stfPowerParalysisConeLengthInches() != 4 ||',
    '            rules::stfPowerParalysisConeWidthInches() != 2 ||',
    '            rules::stfPowerRechargeable() != 1) ++bad;',
    '        // Staff of the Serpent - the python',
    '        if (rules::stfSerpentVarietyCount() != 2 ||',
    '            rules::stfPythonBonus() != 2 ||',
    '            rules::stfPythonDamageLo() != 3 ||',
    '            rules::stfPythonDamageHi() != 8 ||',
    '            rules::stfPythonSnakeLengthFeet() != 25 ||',
    '            rules::stfPythonSnakeAc() != 3 ||',
    '            rules::stfPythonSnakeHp() != 49 ||',
    '            rules::stfPythonSnakeMoveInches() != 9 ||',
    '            rules::stfPythonTransformRounds() != 1 ||',
    '            rules::stfPythonConstrictLo() != 4 ||',
    '            rules::stfPythonConstrictHi() != 10) ++bad;',
    '        // the adder, and no charges at all',
    '        if (rules::stfAdderBonus() != 1 ||',
    '            rules::stfAdderDamageLo() != 2 ||',
    '            rules::stfAdderDamageHi() != 4 ||',
    '            rules::stfAdderHeadAc() != 5 ||',
    '            rules::stfAdderHeadHp() != 20 ||',
    '            rules::stfAdderHeadTurns() != 1 ||',
    '            rules::stfAdderPoisonSaveOrDie() != 1 ||',
    '            rules::stfSerpentHasCharges() != 0 ||',
    '            rules::stfSerpentPythonPercent() != 60) ++bad;',
    '        // Staff of Striking - the 3/6/9 bonus walk',
    '        static const int kStrike2[3] = {',
    '            3, 6, 9,',
    '        };',
    '        if (rules::stfStrikingBonus() != 3 ||',
    '            rules::stfStrikingDamageLo() != 4 ||',
    '            rules::stfStrikingDamageHi() != 9 ||',
    '            rules::stfStrikingMaxChargesPerStrike() != 3 ||',
    '            rules::stfStrikingRechargeable() != 1) ++bad;',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::stfStrikingBonusPerCharge(i) != kStrike2[i]) ++bad;',
    '        if (rules::stfStrikingBonusPerCharge(-9) != 3 ||',
    '            rules::stfStrikingBonusPerCharge(99) != 9) ++bad;',
    '        // Staff of Withering - no recharge accessor,',
    '        // the book prints none',
    '        if (rules::stfWitherBonus() != 1 ||',
    '            rules::stfWitherDamageLo() != 2 ||',
    '            rules::stfWitherDamageHi() != 5 ||',
    '            rules::stfWitherAgeYears() != 10 ||',
    '            rules::stfWitherLimbCharges() != 3 ||',
    '            rules::stfWitherAgelessImmune() != 1) ++bad;',
    '        printf("R245 staves prose pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg gap report log entry ----
gap_old = [
    'open, as is the misc magic item',
    'explanation prose (upload ~10949+).',
]
gap_new = [
    'open, as is the misc magic item',
    'explanation prose (upload ~10949+).',
    '',
    'R245 landed the III.D staves explanation',
    'prose pins (DMG pp.142-143, upload',
    'lines ~10688-10785 - the second prose',
    'round of the EXPLANATIONS AND',
    'DESCRIPTIONS section). rules/',
    'stavesprose.h (the grenade.h pattern,',
    'stf prefix, 76 accessors): the staff',
    'conventions (8th level of magic-use,',
    '2 segments to discharge and 8 to build',
    'up again, nominal damage 8d6) and the',
    'SEVEN staves - Command (3 functions,',
    '2 for a magic-user; 1 charge per',
    'suggestion/charm, 1 per turn of',
    'control, 1 per 1" square of plants',
    'per turn; rechargeable), Curing (4',
    'functions, cure wounds 6-21 hp =',
    '3d6+3, 1 charge each, once per person',
    'per day, max twice per function, 8',
    'uses per 24 hours, rechargeable), the',
    'Magi (5 free powers, 10 at 1 charge,',
    '4 at 2 charges; elementals 8 hit dice,',
    'telekinesis 200 lb, +2 saves,',
    'absorption the only recharge), Power',
    '(6 one-charge and 3 two-charge powers;',
    '+2 AC and saves, smite +2 3-8 hp, 1',
    'charge doubles but 2 do not triple;',
    'paralyzation cone 4" long 2" wide;',
    'rechargeable), the Serpent (python +2',
    '3-8 hp, snake 25 ft AC 3 49 hp 9"',
    'move, constriction 4-10 hp per round;',
    'adder +1 2-4 hp, head AC 5 20 hp 1',
    'turn, save versus poison or die; no',
    'charges, 60% pythons), Striking (+3,',
    '4-9 = d6+3, bonuses 3/6/9 at 1/2/3',
    'charges, max 3 per strike,',
    'rechargeable), Withering (+1, 2-5 hp,',
    '2 charges age 10 years, 3 wither a',
    'limb unless saved, ageless immune; NO',
    'recharge statement printed - unpinned).',
    'The retributive strike pins: globe 3"',
    'radius, damage 8/6/4 times the spell',
    'levels (1-25) by distance band, save',
    'for half, 50% plane travel for the',
    'breaker, 2 items capable (the magi and',
    'the power). The seven staves are the',
    'engine kRods rows 8-14, bands 20-33,',
    'the wand rows from 34 (cross-checked',
    'against the R224 rodswands.h bands in',
    'the audit). New R245 battery audit;',
    'census 164. Next: R246 - the wands',
    'explanation prose (upload',
    '~10786-10948, incl. the wand of',
    'wonder effect table), then the',
    'potions/scrolls/rings explanation',
    'prose (upload ~9998-10561) and the',
    'misc magic item explanations',
    '(~10949+).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence,
# the R228 lesson)
marker = 'R245: the III.D staves explanation prose'
try:
    t = open(STF).read()
    if marker in t:
        already += 1
    else:
        print('R245 FAIL: rules/stavesprose.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(STF, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R245 audit', audit_old, audit_new),
    (GAP, 'the R245 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text (the R233
    # lesson: append-style patches leave the old text
    # inside the new)
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R245 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 164:
        print('R245 FAIL: census is not 164')
        sys.exit(1)
    if t.count('R245 staves prose pins audit') != 1:
        print('R245 FAIL: the R245 audit line must appear once')
        sys.exit(1)
    if t.count('rules/stavesprose.h') != 1:
        print('R245 FAIL: the stavesprose include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R245 landed the III.D staves explanation') != 1:
        print('R245 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(STF).read()
    if 'namespace rules' not in h or h.count('inline int stf') != 76:
        print('R245 FAIL: the header shape is wrong')
        sys.exit(1)

print('R245 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R245 note: 4 patches; the III.D staves explanation prose landed -')
print('the conventions and the seven staves, with the retributive strike;')
print('census 164.')
print('commit: R245: the III.D staves explanation prose pins pinned - DMG pp.142-143, the staff conventions and the seven staves (census 164)')

