#!/usr/bin/env python3
# R247 splice: the III.D wands explanation prose pins, part 2.
#
# DMG pp.144-145, upload lines ~10828-10865 - the fourth
# prose round of the EXPLANATIONS AND DESCRIPTIONS
# section, part 2 of 3 for the wands: the remaining TEN
# wands - Illumination (4 separate functions, 3
# approximating magic-user spells and 1 singular:
# dancing lights 1 segment 1 charge; light 2 segments
# 1 charge; continual light 2 segments 2 charges;
# sunburst 12" maximum range, duration 1/10 of a
# second - pinned as 1 tenth, globe 4" diameter,
# undead within take 6-36 hp with no saving throw,
# others blinded 2-12 segments, 3 segments 3 charges),
# Illusion (14" maximum range, 3 segments to commence,
# 1 charge to effect and 1 per round to continue),
# Lightning (2 functions: shock 1-10 hp no save,
# metallic armor and shield discounted giving armor
# class 10, 1 charge; lightning bolt 12-36 hp, 6d6
# treating 1s as 2s, 2 charges, 2 segments; 1
# function per round), Magic Detection (3" radius
# pulse, 1 round operation, 1 charge per turn or
# fraction thereof, 2% cumulative chance per round of
# malfunction), Metal and Mineral Detection (3"
# radius, 1 round per operation, 1 charge per full
# turn), Magic Missiles (2-5 hp damage, 3 segments,
# 1 charge, maximum 2 per round), Negation (totally
# negates any wand function, 75% for other devices,
# 1 segment, once per round, 1 charge; the one wand
# that cannot be recharged), Paralyzation (ray to 6"
# maximum range, rigidly immobile 5-20 rounds,
# 3 segments, 1 charge, once per round), Polymorphing
# (ray to 6" maximum distance, 3 segments, 1 charge,
# 1 function per round), and Secret Door and Trap
# Location (radius 1.5 inch for secret doors - pinned
# as 3 half-inches, the first half-inch pin since the
# 2.25 inch quarter-inch of R246 - and 3" for traps,
# 1 round, 1 charge). All ten but Negation are
# rechargeable. The ten wands are the engine III.D
# table wand rows 6-15 (dm/treasure.cpp kRods, bands
# 48-94); the wand of wonder rows begin at band 95 -
# cross-checked against the R224 rodswands.h bands in
# the audit.
# Patches: 4 (new rules/wandsprose2.h, the regtest
# include, the audit block, the dmg-gap-report log
# entry). Census 165 -> 166.
#
# commit: R247: the III.D wands explanation prose part 2 pins pinned - DMG pp.144-145, the remaining ten wands (census 166)

import sys

WD   = 'rules/wandsprose2.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson); NO already-closed pre-check
# (the R235b lesson, re-caught at R237)
t = open(REG).read()
if t.count('audit: bad ') != 165 and t.count('audit: bad ') != 166:
    print('R247 FAIL: regtest census is neither 165 nor 166')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/wandsprose2.h',
    '// R247: the III.D wands explanation prose',
    '// pins, part 2 (DMG pp.144-145) - the',
    '// remaining TEN wands of the RODS, et al.',
    '// explanation prose (upload lines',
    '// ~10828-10865):',
    '//   - Wand of Illumination: 4 separate',
    '//     functions, 3 approximating',
    '//     magic-user spells and 1 singular;',
    '//     dancing lights 1 segment 1 charge;',
    '//     light 2 segments 1 charge;',
    '//     continual light 2 segments',
    '//     2 charges; sunburst 12" maximum',
    '//     range, duration 1/10 of a second',
    '//     - pinned as 1 tenth - a globe of',
    '//     4" diameter, undead within take',
    '//     6-36 hp with no saving throw,',
    '//     others blinded 2-12 segments,',
    '//     3 segments 3 charges.',
    '//   - Wand of Illusion: 14" maximum',
    '//     range, 3 segments to commence,',
    '//     1 charge to effect and 1 per',
    '//     round to continue.',
    '//   - Wand of Lightning: 2 functions',
    '//     resembling magic-user spells;',
    '//     shock 1-10 hp no save, metallic',
    '//     armor and shield discounted',
    '//     giving armor class 10, 1 charge;',
    '//     lightning bolt 12-36 hp (6d6,',
    '//     treating 1s as 2s), 2 charges,',
    '//     2 segments; 1 function per round.',
    '//   - Wand of Magic Detection: 3"',
    '//     radius pulse, 1 round operation,',
    '//     1 charge per turn or fraction',
    '//     thereof, 2% cumulative chance',
    '//     per round of malfunction.',
    '//   - Wand of Metal and Mineral',
    '//     Detection: 3" radius, 1 round',
    '//     per operation, 1 charge per',
    '//     full turn.',
    '//   - Wand of Magic Missiles: 2-5 hp',
    '//     damage per missile, 3 segments,',
    '//     1 charge, maximum 2 per round.',
    '//   - Wand of Negation: totally',
    '//     negates any wand function (100%),',
    '//     75% for other devices, 1 segment,',
    '//     once per round, 1 charge; the',
    '//     one wand that cannot be',
    '//     recharged.',
    '//   - Wand of Paralyzation: a thin',
    '//     ray to 6" maximum range,',
    '//     rigidly immobile 5-20 rounds,',
    '//     3 segments, 1 charge, once per',
    '//     round.',
    '//   - Wand of Polymorphing: a thin',
    '//     ray to 6" maximum distance,',
    '//     3 segments, 1 charge,',
    '//     1 function per round.',
    '//   - Wand of Secret Door and Trap',
    '//     Location: radius 1.5 inch for',
    '//     secret doors - pinned as 3',
    '//     half-inches, the first',
    '//     half-inch pin since the 2.25',
    '//     inch quarter-inch of R246 -',
    '//     and 3" for traps, 1 round,',
    '//     1 charge.',
    '// All ten but Negation are',
    '// rechargeable. The ten wands are',
    '// the engine III.D table wand rows',
    '// 6-15 (dm/treasure.cpp kRods, bands',
    '// 48-94); the wand of wonder rows',
    '// begin at band 95.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int wdIllumFunctionCount() {',
    '    // Wand of Illumination: 4 separate',
    '    // functions',
    '    return 4;',
    '}',
    '',
    'inline int wdIllumSpellLikeCount() {',
    '    // 3 approximate magic-user spells,',
    '    // and 1 is singular',
    '    return 3;',
    '}',
    '',
    'inline int wdIllumDanceSegments() {',
    '    // dancing lights: in 1 segment the',
    '    // wand will produce the effect',
    '    return 1;',
    '}',
    '',
    'inline int wdIllumDanceCharges() {',
    '    // at a cost of 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdIllumLightSegments() {',
    '    // light: sent forth in 2 segments',
    '    // time',
    '    return 2;',
    '}',
    '',
    'inline int wdIllumLightCharges() {',
    '    // at an expenditure of 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdIllumContinualSegments() {',
    '    // continual light: only 2 segments',
    '    // to perform',
    '    return 2;',
    '}',
    '',
    'inline int wdIllumContinualCharges() {',
    '    // but the cost is 2 charges',
    '    return 2;',
    '}',
    '',
    'inline int wdIllumSunburstRangeInches() {',
    '    // sunburst: the range is 12"',
    '    // maximum',
    '    return 12;',
    '}',
    '',
    'inline int wdIllumSunburstDurationTenths() {',
    '    // its duration is but 1/10 of a',
    '    // second - pinned as tenths',
    '    return 1;',
    '}',
    '',
    'inline int wdIllumSunburstGlobeInches() {',
    '    // a globe of 4" diameter',
    '    return 4;',
    '}',
    '',
    'inline int wdIllumSunburstUndeadLo() {',
    '    // any undead within the globe take',
    '    // 6-36 hit points of damage, with',
    '    // no saving throw',
    '    return 6;',
    '}',
    '',
    'inline int wdIllumSunburstUndeadHi() {',
    '    return 36;',
    '}',
    '',
    'inline int wdIllumSunburstBlindLo() {',
    '    // all others within the globe are',
    '    // blinded for 2-12 segments',
    '    return 2;',
    '}',
    '',
    'inline int wdIllumSunburstBlindHi() {',
    '    return 12;',
    '}',
    '',
    'inline int wdIllumSunburstSegments() {',
    '    // the function requires 3 segments',
    '    return 3;',
    '}',
    '',
    'inline int wdIllumSunburstCharges() {',
    '    // and expends 3 charges',
    '    return 3;',
    '}',
    '',
    'inline int wdIllumRechargeable() {',
    '    // the wand can be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdIllusionRangeInches() {',
    '    // Wand of Illusion: a 14" maximum',
    '    // range',
    '    return 14;',
    '}',
    '',
    'inline int wdIllusionSegments() {',
    '    // the effect takes 3 segments to',
    '    // commence',
    '    return 3;',
    '}',
    '',
    'inline int wdIllusionChargesPerPortion() {',
    '    // it costs 1 charge to effect',
    '    return 1;',
    '}',
    '',
    'inline int wdIllusionChargesPerRound() {',
    '    // and 1 per round to continue',
    '    return 1;',
    '}',
    '',
    'inline int wdIllusionRechargeable() {',
    '    // the wand may be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdLightningFunctionCount() {',
    '    // Wand of Lightning: 2 functions',
    '    // which closely resemble',
    '    // magic-user spells',
    '    return 2;',
    '}',
    '',
    'inline int wdLightningShockLo() {',
    '    // the shock: 1-10 hit points of',
    '    // damage, with no saving throw',
    '    return 1;',
    '}',
    '',
    'inline int wdLightningShockHi() {',
    '    return 10;',
    '}',
    '',
    'inline int wdLightningShockAc() {',
    '    // metallic armor and shield are',
    '    // discounted, giving opponents',
    '    // armor class 10',
    '    return 10;',
    '}',
    '',
    'inline int wdLightningShockCharges() {',
    '    // the shock uses 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdLightningBoltLo() {',
    '    // the lightning bolt: damage is',
    '    // 12-36 hit points',
    '    return 12;',
    '}',
    '',
    'inline int wdLightningBoltHi() {',
    '    return 36;',
    '}',
    '',
    'inline int wdLightningBoltDice() {',
    '    // 6d6, treating 1s as 2s',
    '    return 6;',
    '}',
    '',
    'inline int wdLightningBoltCharges() {',
    '    // this function uses 2 charges',
    '    return 2;',
    '}',
    '',
    'inline int wdLightningBoltSegments() {',
    '    // it requires 2 segments to',
    '    // discharge',
    '    return 2;',
    '}',
    '',
    'inline int wdLightningFunctionsPerRound() {',
    '    // it can perform but 1 function',
    '    // per round',
    '    return 1;',
    '}',
    '',
    'inline int wdLightningRechargeable() {',
    '    // the wand may be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdMDetectRadiusInches() {',
    '    // Wand of Magic Detection: within',
    '    // a 3" radius the wand will pulse',
    '    return 3;',
    '}',
    '',
    'inline int wdMDetectRounds() {',
    '    // operation requires 1 round',
    '    return 1;',
    '}',
    '',
    'inline int wdMDetectChargesPerTurn() {',
    '    // 1 charge is expended per turn',
    '    // (or fraction thereof) of use',
    '    return 1;',
    '}',
    '',
    'inline int wdMDetectMalfunctionPercent() {',
    '    // there is a 2% cumulative chance',
    '    // per round of a malfunction',
    '    return 2;',
    '}',
    '',
    'inline int wdMDetectRechargeable() {',
    '    // the wand may be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdMetalRadiusInches() {',
    '    // Wand of Metal and Mineral',
    '    // Detection: also a 3" radius',
    '    // range',
    '    return 3;',
    '}',
    '',
    'inline int wdMetalRounds() {',
    '    // each operation requires 1 round',
    '    return 1;',
    '}',
    '',
    'inline int wdMetalChargesPerTurn() {',
    '    // each charge powers the wand for',
    '    // 1 full turn',
    '    return 1;',
    '}',
    '',
    'inline int wdMetalRechargeable() {',
    '    // the wand may be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdMissileDamageLo() {',
    '    // Wand of Magic Missiles: each',
    '    // missile causes 2-5 hit points',
    '    // of damage',
    '    return 2;',
    '}',
    '',
    'inline int wdMissileDamageHi() {',
    '    return 5;',
    '}',
    '',
    'inline int wdMissileSegments() {',
    '    // each missile takes 3 segments to',
    '    // discharge',
    '    return 3;',
    '}',
    '',
    'inline int wdMissileCharges() {',
    '    // and costs 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdMissileMaxPerRound() {',
    '    // a maximum of 2 may be expended',
    '    // in 1 round',
    '    return 2;',
    '}',
    '',
    'inline int wdMissileRechargeable() {',
    '    // the wand may be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdNegateWandPercent() {',
    '    // Wand of Negation: this will',
    '    // totally negate any wand function',
    '    return 100;',
    '}',
    '',
    'inline int wdNegateDevicePercent() {',
    '    // any other device is 75% likely',
    '    // to be negated',
    '    return 75;',
    '}',
    '',
    'inline int wdNegateSegments() {',
    '    // operation requires but 1 segment',
    '    // of a round',
    '    return 1;',
    '}',
    '',
    'inline int wdNegateUsesPerRound() {',
    '    // it can function but once per',
    '    // round',
    '    return 1;',
    '}',
    '',
    'inline int wdNegateCharges() {',
    '    // each negation drains 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdNegateRechargeable() {',
    '    // the wand cannot be recharged -',
    '    // the only one of the ten',
    '    return 0;',
    '}',
    '',
    'inline int wdParalyzeRangeInches() {',
    '    // Wand of Paralyzation: a thin',
    '    // ray of bluish color to a',
    '    // maximum range of 6"',
    '    return 6;',
    '}',
    '',
    'inline int wdParalyzeDurationLo() {',
    '    // struck creatures are rigidly',
    '    // immobile for from 5-20 rounds',
    '    return 5;',
    '}',
    '',
    'inline int wdParalyzeDurationHi() {',
    '    return 20;',
    '}',
    '',
    'inline int wdParalyzeSegments() {',
    '    // each operation takes 3 segments',
    '    return 3;',
    '}',
    '',
    'inline int wdParalyzeCharges() {',
    '    // and costs 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdParalyzeUsesPerRound() {',
    '    // the wand may operate once per',
    '    // round',
    '    return 1;',
    '}',
    '',
    'inline int wdParalyzeRechargeable() {',
    '    // it may be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdPolyRangeInches() {',
    '    // Wand of Polymorphing: a thin ray',
    '    // which darts forth to a maximum',
    '    // distance of 6"',
    '    return 6;',
    '}',
    '',
    'inline int wdPolySegments() {',
    '    // either function requires 3',
    '    // segments',
    '    return 3;',
    '}',
    '',
    'inline int wdPolyCharges() {',
    '    // each draws 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdPolyFunctionsPerRound() {',
    '    // only 1 function per round is',
    '    // possible',
    '    return 1;',
    '}',
    '',
    'inline int wdPolyRechargeable() {',
    '    // the wand may be recharged',
    '    return 1;',
    '}',
    '',
    'inline int wdSecretDoorRadiusHalfInches() {',
    '    // Wand of Secret Door and Trap',
    '    // Location: an effective radius of',
    '    // 1.5 inch for secret door location',
    '    // - pinned as 3 half-inches, the',
    '    // first half-inch pin since the',
    '    // 2.25 inch quarter-inch of R246',
    '    return 3;',
    '}',
    '',
    'inline int wdTrapRadiusInches() {',
    '    // 3" for trap location',
    '    return 3;',
    '}',
    '',
    'inline int wdSecretRounds() {',
    '    // it requires 1 round to function',
    '    return 1;',
    '}',
    '',
    'inline int wdSecretCharges() {',
    '    // and draws 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int wdSecretRechargeable() {',
    '    // the wand may be recharged',
    '    return 1;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the regtest include ----
inc_old = [
    '#include "rules/wandsprose.h"  // R246: pp.143-144 the III.D wands prose pins',
]
inc_new = [
    '#include "rules/wandsprose.h"  // R246: pp.143-144 the III.D wands prose pins',
    '#include "rules/wandsprose2.h"  // R247: pp.144-145 the III.D wands prose part 2 pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R247: the III.D wands explanation prose part 2 pins audit ----',
    '    // DMG pp.144-145: the remaining ten',
    '    // wands of the RODS, et al.',
    '    // explanation prose.',
    '    {',
    '        int bad = 0;',
    '        // the ten wands are the engine III.D',
    '        // table wand rows 6-15 - bands 48-94,',
    '        // the wand of wonder from 95 (the',
    '        // R224 pins)',
    '        if (rules::rswRowLo(19) != 48 ||',
    '            rules::rswRowHi(28) != 94 ||',
    '            rules::rswRowLo(29) != 95 ||',
    '            rules::rswRowHi(29) != 100) ++bad;',
    '        // Wand of Illumination - the four functions',
    '        if (rules::wdIllumFunctionCount() != 4 ||',
    '            rules::wdIllumSpellLikeCount() != 3 ||',
    '            rules::wdIllumDanceSegments() != 1 ||',
    '            rules::wdIllumDanceCharges() != 1 ||',
    '            rules::wdIllumLightSegments() != 2 ||',
    '            rules::wdIllumLightCharges() != 1 ||',
    '            rules::wdIllumContinualSegments() != 2 ||',
    '            rules::wdIllumContinualCharges() != 2 ||',
    '            rules::wdIllumSunburstRangeInches() != 12 ||',
    '            rules::wdIllumSunburstDurationTenths() != 1 ||',
    '            rules::wdIllumSunburstGlobeInches() != 4 ||',
    '            rules::wdIllumSunburstUndeadLo() != 6 ||',
    '            rules::wdIllumSunburstUndeadHi() != 36 ||',
    '            rules::wdIllumSunburstBlindLo() != 2 ||',
    '            rules::wdIllumSunburstBlindHi() != 12 ||',
    '            rules::wdIllumSunburstSegments() != 3 ||',
    '            rules::wdIllumSunburstCharges() != 3 ||',
    '            rules::wdIllumRechargeable() != 1) ++bad;',
    '        // Wand of Illusion',
    '        if (rules::wdIllusionRangeInches() != 14 ||',
    '            rules::wdIllusionSegments() != 3 ||',
    '            rules::wdIllusionChargesPerPortion() != 1 ||',
    '            rules::wdIllusionChargesPerRound() != 1 ||',
    '            rules::wdIllusionRechargeable() != 1) ++bad;',
    '        // Wand of Lightning - the two functions',
    '        if (rules::wdLightningFunctionCount() != 2 ||',
    '            rules::wdLightningShockLo() != 1 ||',
    '            rules::wdLightningShockHi() != 10 ||',
    '            rules::wdLightningShockAc() != 10 ||',
    '            rules::wdLightningShockCharges() != 1 ||',
    '            rules::wdLightningBoltLo() != 12 ||',
    '            rules::wdLightningBoltHi() != 36 ||',
    '            rules::wdLightningBoltDice() != 6 ||',
    '            rules::wdLightningBoltCharges() != 2 ||',
    '            rules::wdLightningBoltSegments() != 2 ||',
    '            rules::wdLightningFunctionsPerRound() != 1 ||',
    '            rules::wdLightningRechargeable() != 1) ++bad;',
    '        // Wand of Magic Detection',
    '        if (rules::wdMDetectRadiusInches() != 3 ||',
    '            rules::wdMDetectRounds() != 1 ||',
    '            rules::wdMDetectChargesPerTurn() != 1 ||',
    '            rules::wdMDetectMalfunctionPercent() != 2 ||',
    '            rules::wdMDetectRechargeable() != 1) ++bad;',
    '        // Wand of Metal and Mineral Detection',
    '        if (rules::wdMetalRadiusInches() != 3 ||',
    '            rules::wdMetalRounds() != 1 ||',
    '            rules::wdMetalChargesPerTurn() != 1 ||',
    '            rules::wdMetalRechargeable() != 1) ++bad;',
    '        // Wand of Magic Missiles',
    '        if (rules::wdMissileDamageLo() != 2 ||',
    '            rules::wdMissileDamageHi() != 5 ||',
    '            rules::wdMissileSegments() != 3 ||',
    '            rules::wdMissileCharges() != 1 ||',
    '            rules::wdMissileMaxPerRound() != 2 ||',
    '            rules::wdMissileRechargeable() != 1) ++bad;',
    '        // Wand of Negation - the one wand',
    '        // that cannot be recharged',
    '        if (rules::wdNegateWandPercent() != 100 ||',
    '            rules::wdNegateDevicePercent() != 75 ||',
    '            rules::wdNegateSegments() != 1 ||',
    '            rules::wdNegateUsesPerRound() != 1 ||',
    '            rules::wdNegateCharges() != 1 ||',
    '            rules::wdNegateRechargeable() != 0) ++bad;',
    '        // Wand of Paralyzation',
    '        if (rules::wdParalyzeRangeInches() != 6 ||',
    '            rules::wdParalyzeDurationLo() != 5 ||',
    '            rules::wdParalyzeDurationHi() != 20 ||',
    '            rules::wdParalyzeSegments() != 3 ||',
    '            rules::wdParalyzeCharges() != 1 ||',
    '            rules::wdParalyzeUsesPerRound() != 1 ||',
    '            rules::wdParalyzeRechargeable() != 1) ++bad;',
    '        // Wand of Polymorphing',
    '        if (rules::wdPolyRangeInches() != 6 ||',
    '            rules::wdPolySegments() != 3 ||',
    '            rules::wdPolyCharges() != 1 ||',
    '            rules::wdPolyFunctionsPerRound() != 1 ||',
    '            rules::wdPolyRechargeable() != 1) ++bad;',
    '        // Wand of Secret Door and Trap Location',
    '        if (rules::wdSecretDoorRadiusHalfInches() != 3 ||',
    '            rules::wdTrapRadiusInches() != 3 ||',
    '            rules::wdSecretRounds() != 1 ||',
    '            rules::wdSecretCharges() != 1 ||',
    '            rules::wdSecretRechargeable() != 1) ++bad;',
    '        printf("R247 wands prose part 2 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg gap report log entry ----
gap_old = [
    'magic item explanations (~10949+)',
    'remain open after that.',
]
gap_new = [
    'magic item explanations (~10949+)',
    'remain open after that.',
    '',
    'R247 landed the III.D wands',
    'explanation prose pins, part 2 of 3',
    '(DMG pp.144-145, upload lines',
    '~10828-10865). rules/wandsprose2.h',
    '(the grenade.h pattern, wd prefix,',
    '73 scalar accessors - no arrays',
    'this round): the remaining TEN',
    'wands - Illumination (4 functions:',
    'dancing lights 1 segment 1 charge;',
    'light 2 segments 1 charge;',
    'continual light 2 segments 2',
    'charges; sunburst 12" range,',
    'duration 1/10 of a second (pinned',
    'as 1 tenth), 4" globe, undead',
    '6-36 hp no save, others blinded',
    '2-12 segments, 3 segments 3',
    'charges; rechargeable), Illusion',
    '(14" range, 3 segments, 1 charge to',
    'effect and 1 per round to',
    'continue, rechargeable), Lightning',
    '(2 functions: shock 1-10 hp no',
    'save, metallic armor and shield',
    'discounted AC 10, 1 charge; bolt',
    '12-36 hp 6d6 with 1s counted as',
    '2s, 2 charges 2 segments; 1',
    'function per round, rechargeable),',
    'Magic Detection (3" radius, 1',
    'round, 1 charge per turn or',
    'fraction, 2% cumulative chance per',
    'round of malfunction,',
    'rechargeable), Metal and Mineral',
    'Detection (3" radius, 1 round,',
    '1 charge per full turn,',
    'rechargeable), Magic Missiles (2-5',
    'hp, 3 segments, 1 charge, max 2',
    'per round, rechargeable), Negation',
    '(100% any wand function, 75% other',
    'devices, 1 segment, once per',
    'round, 1 charge; the one wand',
    'that cannot be recharged),',
    'Paralyzation (ray 6", 5-20 rounds,',
    '3 segments, 1 charge, once per',
    'round, rechargeable), Polymorphing',
    '(ray 6", 3 segments, 1 charge,',
    '1 function per round,',
    'rechargeable), and Secret Door and',
    'Trap Location (radius 1.5 inch for',
    'secret doors - pinned as 3',
    'half-inches, the first half-inch',
    'pin since the 2.25 inch',
    'quarter-inch of R246 - and 3" for',
    'traps, 1 round, 1 charge,',
    'rechargeable). The ten wands are',
    'the engine kRods wand rows 6-15,',
    'bands 48-94, the wand of wonder',
    'from 95 (cross-checked against the',
    'R224 rodswands.h bands in the',
    'audit). New R247 battery audit;',
    'census 166. Next: R248 - the wand',
    'of wonder effect table (upload',
    '~10867-10947, 19 bands). The',
    'potions/scrolls/rings explanation',
    'prose (upload ~9998-10561) and',
    'the misc magic item explanations',
    '(~10949+) remain open after that.',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence,
# the R228 lesson)
marker = 'R247: the III.D wands explanation prose'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R247 FAIL: rules/wandsprose2.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R247 audit', audit_old, audit_new),
    (GAP, 'the R247 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text (the R233
    # lesson: append-style patches leave the old text
    # inside the new)
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R247 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 166:
        print('R247 FAIL: census is not 166')
        sys.exit(1)
    if t.count('R247 wands prose part 2 pins audit') != 1:
        print('R247 FAIL: the R247 audit line must appear once')
        sys.exit(1)
    if t.count('rules/wandsprose2.h') != 1:
        print('R247 FAIL: the wandsprose2 include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R247 landed the III.D wands') != 1:
        print('R247 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int wd') != 73:
        print('R247 FAIL: the header shape is wrong')
        sys.exit(1)

print('R247 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R247 note: 4 patches; the III.D wands explanation prose part 2 -')
print('the remaining ten wands; census 166.')
print('commit: R247: the III.D wands explanation prose part 2 pins pinned - DMG pp.144-145, the remaining ten wands (census 166)')

