#!/usr/bin/env python3
# R250 splice: the III.A potions explanation prose pins, part 2.
#
# DMG pp.134-136, upload lines ~10063-10128 - potions 10
# through 19 of the III.A POTIONS explanation prose: Fire
# Resistance (all damage from intense fires reduced by -2
# from each die of damage, saves at +4; on a half dose
# invulnerability to normal fires and half the benefits,
# -1 and +2; the potion lasts 1 turn, or 5 rounds for
# half doses), Flying (same manner as the fly spell,
# third level magic-user), Gaseous Form (base speed 3"
# per round; a whirlwind inflicts double damage), Giant
# Control (influence 1 or 2 giants as if charm monster;
# save at -4 if only 1, at +2 if 2; the 6-row d20 giant
# type sub-table, hill giant 1-5 through storm giant 20;
# control lasts 5-30 5d6 rounds), Giant Strength (the
# 6-row die table: hill giant 1-6 through storm giant 20
# - weight allowances +4,500 through +12,000; damage
# bonuses +7 through +12; rock base ranges 8 through 16
# inches; rock hurling damage 1-6, 1-12, 1-8, 1-8, 1-10,
# 1-12; bend bars/lift gates 50-100 percent), Growth
# (6 feet per quarter of the potion, 24 feet for a full
# potion), Healing (restores 4-10 2d4+2), Heroism (only
# if fewer than 10 levels; the 3-row consumer table with
# energy levels 3/2/1 and accumulated damage 3+1/2+2/
# 1+3 on 10-sided dice), Human Control (up to 32 levels
# or hit dice as if charm person; the 8-row d20 human
# type table; 5-30 rounds), and Invisibility (a single
# gulp is 1/8 of the contents and bestows 3-6 turns).
# The ten potions are the engine III.A table rows 10-19
# (dm/treasure.cpp kPotions, bands 27-54,
# invulnerability from 55) - cross-checked row by row
# against the R221 potions.h pins in the audit.
# Patches: 4 (new rules/potionsprose2.h, the regtest
# include, the audit block, the dmg-gap-report log
# entry). Census 168 -> 169.
#
# commit: R250: the III.A potions explanation prose part 2 pins pinned - DMG pp.134-136, Fire Resistance through Invisibility (census 169)

import sys

WD   = 'rules/potionsprose2.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson); NO already-closed pre-check
# (the R235b lesson, re-caught at R237)
t = open(REG).read()
if t.count('audit: bad ') != 168 and t.count('audit: bad ') != 169:
    print('R250 FAIL: regtest census is neither 168 nor 169')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/potionsprose2.h',
    '// R250: the III.A potions explanation prose',
    '// pins, part 2 (DMG pp.134-136) - potions',
    '// 10 through 19 of the EXPLANATIONS AND',
    '// DESCRIPTIONS section (upload lines',
    '// ~10063-10128):',
    '//   - Fire Resistance: damage reduced',
    '//     by -2 per die of damage, saves at',
    '//     +4; half dose -1 and +2; 1 turn,',
    '//     or 5 rounds on a half dose.',
    '//   - Flying: as the fly spell, third',
    '//     level magic-user.',
    '//   - Gaseous Form: base speed 3" per',
    '//     round; a whirlwind inflicts double',
    '//     damage.',
    '//   - Giant Control: 1 or 2 giants; save',
    '//     -4 if 1, +2 if 2; the 6-row d20',
    '//     giant type sub-table; control lasts',
    '//     5-30 (5d6) rounds.',
    '//   - Giant Strength: the 6-row die',
    '//     table - hill 1-6 through storm 20 -',
    '//     weight allowance, damage bonus,',
    '//     rock base range, rock hurling',
    '//     damage, bend bars/lift gates',
    '//     percent.',
    '//   - Growth: 6 feet per quarter, 24',
    '//     feet for the full potion.',
    '//   - Healing: 4-10 (2d4 + 2) hit',
    '//     points.',
    '//   - Heroism: below 10 levels; the',
    '//     3-row consumer level table',
    '//     (10-sided dice for the',
    '//     accumulated damage).',
    '//   - Human Control: up to 32 levels',
    '//     or hit dice; the 8-row d20 human',
    '//     type table; 5-30 rounds.',
    '//   - Invisibility: a gulp is 1/8 of',
    '//     the contents; 3-6 turns.',
    '// The ten potions are the engine III.A',
    '// table rows 10-19 (dm/treasure.cpp',
    '// kPotions, bands 27-54, invulnerability',
    '// from 55) - cross-checked against the',
    '// R221 potions.h pins in the audit.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int potFireDieReduction() {',
    '    // Fire Resistance: all damage from',
    '    // such fires is reduced by -2 from',
    '    // each die of damage',
    '    return -2;',
    '}',
    '',
    'inline int potFireSaveMod() {',
    '    // if a saving throw is applicable it',
    '    // is made at +4',
    '    return 4;',
    '}',
    '',
    'inline int potFireHalfDieReduction() {',
    '    // one-half potion: half the',
    '    // benefits, -1',
    '    return -1;',
    '}',
    '',
    'inline int potFireHalfSaveMod() {',
    '    // one-half potion: half the',
    '    // benefits, +2',
    '    return 2;',
    '}',
    '',
    'inline int potFireTurns() {',
    '    // the potion lasts 1 turn',
    '    return 1;',
    '}',
    '',
    'inline int potFireHalfRounds() {',
    '    // or 5 rounds for half doses',
    '    return 5;',
    '}',
    '',
    'inline int potFlySpellLevel() {',
    '    // Flying: in the same manner as the',
    '    // third level magic-user spell, fly',
    '    return 3;',
    '}',
    '',
    'inline int potGasSpeedInches() {',
    '    // Gaseous Form: flows at a base',
    '    // speed of 3" per round',
    '    return 3;',
    '}',
    '',
    'inline int potGasWhirlwindMult() {',
    '    // a whirlwind inflicts double',
    '    // damage upon the gaseous form',
    '    return 2;',
    '}',
    '',
    'inline int potGiantControlLo() {',
    '    // Giant Control: influences 1 or 2',
    '    // giants as if a charm monster spell',
    '    return 1;',
    '}',
    '',
    'inline int potGiantControlHi() {',
    '    return 2;',
    '}',
    '',
    'inline int potGiantOneSaveMod() {',
    '    // if only 1 giant is influenced its',
    '    // save versus magic is at -4',
    '    return -4;',
    '}',
    '',
    'inline int potGiantTwoSaveMod() {',
    '    // if 2 are influenced the die rolls',
    '    // are at +2',
    '    return 2;',
    '}',
    '',
    'inline int potGiantRoundLo() {',
    '    // control lasts for only 5-30',
    '    // (5d6) rounds',
    '    return 5;',
    '}',
    '',
    'inline int potGiantRoundHi() {',
    '    return 30;',
    '}',
    '',
    'inline int potGiantRoundDice() {',
    '    return 5;',
    '}',
    '',
    'inline int potGiantRoundFaces() {',
    '    return 6;',
    '}',
    '',
    'inline int potGiantTypeRowCount() {',
    '    // the giant type sub-table: 6 rows',
    '    return 6;',
    '}',
    '',
    'inline int potGiantTypeLo(int i) {',
    '    // the printed band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        1, 6, 10, 14, 18, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGiantTypeHi(int i) {',
    '    // the printed band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        5, 9, 13, 17, 19, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGiantTypeFaces() {',
    '    // the giant type roll is on d20',
    '    return 20;',
    '}',
    '',
    'inline int potGStrRowCount() {',
    '    // Giant Strength: the die table has',
    '    // 6 rows',
    '    return 6;',
    '}',
    '',
    'inline int potGStrTypeLo(int i) {',
    '    // the printed die band lower edges;',
    '    // i clamps - hill, stone, frost, fire,',
    '    // cloud, storm',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        1, 7, 11, 15, 18, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGStrTypeHi(int i) {',
    '    // the printed die band upper edges;',
    '    // i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        6, 10, 14, 17, 19, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGStrWeightGp(int i) {',
    '    // the weight allowances; i clamps:',
    '    // hill +4,500, stone +5,000, frost',
    '    // +6,000, fire +7,500, cloud +9,000,',
    '    // storm +12,000',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        4500, 5000, 6000, 7500, 9000, 12000,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGStrDmgBonus(int i) {',
    '    // the damage bonuses; i clamps:',
    '    // +7, +8, +9, +10, +11, +12',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        7, 8, 9, 10, 11, 12,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGStrRockRangeInches(int i) {',
    '    // the rock base ranges; i clamps:',
    '    // hill 8", stone 16", frost 10",',
    '    // fire 12", cloud 14", storm 16"',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        8, 16, 10, 12, 14, 16,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGStrRockDmgLo(int i) {',
    '    // the rock hurling damage lower',
    '    // edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        1, 1, 1, 1, 1, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGStrRockDmgHi(int i) {',
    '    // the rock hurling damage upper',
    '    // edges; i clamps: 1-6, 1-12, 1-8,',
    '    // 1-8, 1-10, 1-12',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        6, 12, 8, 8, 10, 12,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGStrBendBarsPercent(int i) {',
    '    // the bend bars/lift gates',
    '    // percents; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        50, 60, 70, 80, 90, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potGrowthQuarterFeet() {',
    '    // Growth: each quarter of the potion',
    '    // causes 6 feet of height growth',
    '    return 6;',
    '}',
    '',
    'inline int potGrowthFullFeet() {',
    '    // a full potion increases height by',
    '    // 24 feet',
    '    return 24;',
    '}',
    '',
    'inline int potHealLo() {',
    '    // Healing: restores 4-10',
    '    // (2d4 + 2) hit points',
    '    return 4;',
    '}',
    '',
    'inline int potHealHi() {',
    '    return 10;',
    '}',
    '',
    'inline int potHealDice() {',
    '    return 2;',
    '}',
    '',
    'inline int potHealFaces() {',
    '    return 4;',
    '}',
    '',
    'inline int potHealBonus() {',
    '    return 2;',
    '}',
    '',
    'inline int potHeroMaxLevels() {',
    '    // Heroism: a temporary increase in',
    '    // life energy levels if the imbiber',
    '    // has fewer than 10 levels',
    '    return 10;',
    '}',
    '',
    'inline int potHeroRowCount() {',
    '    // the consumer level table: 3 rows',
    '    return 3;',
    '}',
    '',
    'inline int potHeroDmgFaces() {',
    '    // 10-sided dice for the accumulated',
    '    // damage bestowed',
    '    return 10;',
    '}',
    '',
    'inline int potHeroLevels(int i) {',
    '    // the energy levels bestowed; i',
    '    // clamps: 1st-3rd 3, 4th-6th 2,',
    '    // 7th-9th 1',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        3, 2, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potHeroDmgDice(int i) {',
    '    // the accumulated damage dice; i',
    '    // clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        3, 2, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potHeroDmgBonus(int i) {',
    '    // the accumulated damage bonus; i',
    '    // clamps: 3 + 1, 2 + 2, 1 + 3',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        1, 2, 3,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potHumanLevelsTotal() {',
    '    // Human Control: control up to 32',
    '    // levels/hit dice of humans and',
    '    // kindred as if a charm person spell',
    '    return 32;',
    '}',
    '',
    'inline int potHumanTypeRowCount() {',
    '    // the human type table: 8 rows',
    '    return 8;',
    '}',
    '',
    'inline int potHumanTypeLo(int i) {',
    '    // the printed band lower edges; i',
    '    // clamps: dwarves, elves or',
    '    // half-elves, gnomes, halflings,',
    '    // half-orcs, humans, humanoids,',
    '    // the mixed 20 row',
    '    if (i < 0) i = 0;',
    '    if (i > 7) i = 7;',
    '    static const int t[8] = {',
    '        1, 3, 5, 7, 9, 11, 17, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potHumanTypeHi(int i) {',
    '    // the printed band upper edges; i',
    '    // clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 7) i = 7;',
    '    static const int t[8] = {',
    '        2, 4, 6, 8, 10, 16, 19, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potHumanTypeFaces() {',
    '    // the human type roll is on d20',
    '    return 20;',
    '}',
    '',
    'inline int potHumanRoundLo() {',
    '    // the potion lasts for 5-30 rounds',
    '    return 5;',
    '}',
    '',
    'inline int potHumanRoundHi() {',
    '    return 30;',
    '}',
    '',
    'inline int potInvisGulpFraction() {',
    '    // Invisibility: a single gulp is',
    '    // equal to 1/8 of the contents',
    '    return 8;',
    '}',
    '',
    'inline int potInvisTurnsLo() {',
    '    // the gulp bestows invisibility for',
    '    // 3-6 turns',
    '    return 3;',
    '}',
    '',
    'inline int potInvisTurnsHi() {',
    '    return 6;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the regtest include ----
inc_old = [
    '#include "rules/potionsprose.h"  // R249: pp.133-134 the III.A potions prose part 1 pins',
]
inc_new = [
    '#include "rules/potionsprose.h"  // R249: pp.133-134 the III.A potions prose part 1 pins',
    '#include "rules/potionsprose2.h"  // R250: pp.134-136 the III.A potions prose part 2 pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R250: the III.A potions explanation prose part 2 pins audit ----',
    '    // DMG pp.134-136: Fire Resistance',
    '    // through Invisibility - potions part 2.',
    '    {',
    '        int bad = 0;',
    '        // the ten potions are the engine III.A',
    '        // table rows 10-19 - bands 27-54,',
    '        // invulnerability from 55 (the R221',
    '        // pins)',
    '        if (rules::potionRowLo(9) != 27 ||',
    '            rules::potionRowHi(18) != 54 ||',
    '            rules::potionRowLo(19) != 55) ++bad;',
    '        // the engine rows 10-19 checked band',
    '        // by band against the R221 pins',
    '        static const int kRowLo[10] = {',
    '            27, 30, 33, 35, 37, 40, 42, 48, 50, 52,',
    '        };',
    '        static const int kRowHi[10] = {',
    '            29, 32, 34, 36, 39, 41, 47, 49, 51, 54,',
    '        };',
    '        for (int i = 0; i < 10; ++i)',
    '            if (rules::potionRowLo(i + 9) != kRowLo[i] ||',
    '                rules::potionRowHi(i + 9) != kRowHi[i]) ++bad;',
    '        // Fire Resistance - the reduction,',
    '        // the save, and the durations',
    '        if (rules::potFireDieReduction() != -2 ||',
    '            rules::potFireSaveMod() != 4 ||',
    '            rules::potFireHalfDieReduction() != -1 ||',
    '            rules::potFireHalfSaveMod() != 2 ||',
    '            rules::potFireTurns() != 1 ||',
    '            rules::potFireHalfRounds() != 5) ++bad;',
    '        // Flying - the fly spell level',
    '        if (rules::potFlySpellLevel() != 3) ++bad;',
    '        // Gaseous Form - the speed and the',
    '        // whirlwind',
    '        if (rules::potGasSpeedInches() != 3 ||',
    '            rules::potGasWhirlwindMult() != 2) ++bad;',
    '        // Giant Control - the count, the',
    '        // saves, and the rounds',
    '        if (rules::potGiantControlLo() != 1 ||',
    '            rules::potGiantControlHi() != 2 ||',
    '            rules::potGiantOneSaveMod() != -4 ||',
    '            rules::potGiantTwoSaveMod() != 2 ||',
    '            rules::potGiantRoundLo() != 5 ||',
    '            rules::potGiantRoundHi() != 30 ||',
    '            rules::potGiantRoundDice() != 5 ||',
    '            rules::potGiantRoundFaces() != 6) ++bad;',
    '        // the giant type sub-table: 6 rows on d20',
    '        if (rules::potGiantTypeRowCount() != 6 ||',
    '            rules::potGiantTypeFaces() != 20) ++bad;',
    '        static const int kGLo[6] = {',
    '            1, 6, 10, 14, 18, 20,',
    '        };',
    '        static const int kGHi[6] = {',
    '            5, 9, 13, 17, 19, 20,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::potGiantTypeLo(i) != kGLo[i] ||',
    '                rules::potGiantTypeHi(i) != kGHi[i]) ++bad;',
    '        for (int i = 1; i < 6; ++i)',
    '            if (rules::potGiantTypeLo(i) !=',
    '                rules::potGiantTypeHi(i - 1) + 1) ++bad;',
    '        if (rules::potGiantTypeLo(-5) != 1 ||',
    '            rules::potGiantTypeHi(99) != 20) ++bad;',
    '        // Giant Strength - the 6-row die table',
    '        if (rules::potGStrRowCount() != 6) ++bad;',
    '        static const int kSLo[6] = {',
    '            1, 7, 11, 15, 18, 20,',
    '        };',
    '        static const int kSHi[6] = {',
    '            6, 10, 14, 17, 19, 20,',
    '        };',
    '        static const int kSWt[6] = {',
    '            4500, 5000, 6000, 7500, 9000, 12000,',
    '        };',
    '        static const int kSBon[6] = {',
    '            7, 8, 9, 10, 11, 12,',
    '        };',
    '        static const int kSRng[6] = {',
    '            8, 16, 10, 12, 14, 16,',
    '        };',
    '        static const int kSRkLo[6] = {',
    '            1, 1, 1, 1, 1, 1,',
    '        };',
    '        static const int kSRkHi[6] = {',
    '            6, 12, 8, 8, 10, 12,',
    '        };',
    '        static const int kSBend[6] = {',
    '            50, 60, 70, 80, 90, 100,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::potGStrTypeLo(i) != kSLo[i] ||',
    '                rules::potGStrTypeHi(i) != kSHi[i] ||',
    '                rules::potGStrWeightGp(i) != kSWt[i] ||',
    '                rules::potGStrDmgBonus(i) != kSBon[i] ||',
    '                rules::potGStrRockRangeInches(i) != kSRng[i] ||',
    '                rules::potGStrRockDmgLo(i) != kSRkLo[i] ||',
    '                rules::potGStrRockDmgHi(i) != kSRkHi[i] ||',
    '                rules::potGStrBendBarsPercent(i) != kSBend[i]) ++bad;',
    '        for (int i = 1; i < 6; ++i)',
    '            if (rules::potGStrTypeLo(i) !=',
    '                rules::potGStrTypeHi(i - 1) + 1) ++bad;',
    '        if (rules::potGStrTypeLo(-5) != 1 ||',
    '            rules::potGStrTypeHi(99) != 20) ++bad;',
    '        // Growth - the quarter and the full potion',
    '        if (rules::potGrowthQuarterFeet() != 6 ||',
    '            rules::potGrowthFullFeet() != 24) ++bad;',
    '        // Healing - the restored hit points',
    '        if (rules::potHealLo() != 4 ||',
    '            rules::potHealHi() != 10 ||',
    '            rules::potHealDice() != 2 ||',
    '            rules::potHealFaces() != 4 ||',
    '            rules::potHealBonus() != 2) ++bad;',
    '        // Heroism - the level ceiling and the table',
    '        if (rules::potHeroMaxLevels() != 10 ||',
    '            rules::potHeroRowCount() != 3 ||',
    '            rules::potHeroDmgFaces() != 10) ++bad;',
    '        static const int kHLvl[3] = {',
    '            3, 2, 1,',
    '        };',
    '        static const int kHDice[3] = {',
    '            3, 2, 1,',
    '        };',
    '        static const int kHBon[3] = {',
    '            1, 2, 3,',
    '        };',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::potHeroLevels(i) != kHLvl[i] ||',
    '                rules::potHeroDmgDice(i) != kHDice[i] ||',
    '                rules::potHeroDmgBonus(i) != kHBon[i]) ++bad;',
    '        // Human Control - the levels, the table,',
    '        // and the duration',
    '        if (rules::potHumanLevelsTotal() != 32 ||',
    '            rules::potHumanTypeRowCount() != 8 ||',
    '            rules::potHumanTypeFaces() != 20 ||',
    '            rules::potHumanRoundLo() != 5 ||',
    '            rules::potHumanRoundHi() != 30) ++bad;',
    '        static const int kHLo[8] = {',
    '            1, 3, 5, 7, 9, 11, 17, 20,',
    '        };',
    '        static const int kHHi[8] = {',
    '            2, 4, 6, 8, 10, 16, 19, 20,',
    '        };',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::potHumanTypeLo(i) != kHLo[i] ||',
    '                rules::potHumanTypeHi(i) != kHHi[i]) ++bad;',
    '        for (int i = 1; i < 8; ++i)',
    '            if (rules::potHumanTypeLo(i) !=',
    '                rules::potHumanTypeHi(i - 1) + 1) ++bad;',
    '        if (rules::potHumanTypeLo(-5) != 1 ||',
    '            rules::potHumanTypeHi(99) != 20) ++bad;',
    '        // Invisibility - the gulp and the turns',
    '        if (rules::potInvisGulpFraction() != 8 ||',
    '            rules::potInvisTurnsLo() != 3 ||',
    '            rules::potInvisTurnsHi() != 6) ++bad;',
    '        printf("R250 potions prose part 2 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg gap report log entry ----
gap_old = [
    '~10282-10561), then the misc magic',
    'item explanations (~10949+).',
]
gap_new = [
    '~10282-10561), then the misc magic',
    'item explanations (~10949+).',
    '',
    'R250 landed the III.A potions',
    'explanation prose pins, part 2 of 3',
    '(DMG pp.134-136, upload lines',
    '~10063-10128) - potions 10 through',
    '19 of the EXPLANATIONS section.',
    'rules/potionsprose2.h (the',
    'wandsprose2.h part-2 pattern, the',
    'pot prefix continues - 53 accessors,',
    'of which 15 are array walkers):',
    'Fire Resistance (damage -2 per die,',
    'saves +4; half dose -1 and +2; 1',
    'turn or 5 rounds), Flying (as the fly',
    'spell, 3rd level magic-user),',
    'Gaseous Form (base speed 3" per',
    'round, whirlwind double damage),',
    'Giant Control (1-2 giants, save -4',
    'if 1 / +2 if 2; the 6-row d20 giant',
    'type sub-table hill 1-5 through',
    'storm 20, tiling 1-20; 5-30 5d6',
    'rounds), Giant Strength (the 6-row',
    'die table: weight allowances',
    '4500-12000, damage bonuses +7',
    'through +12, rock base ranges',
    '8/16/10/12/14/16 inches, rock',
    'damage 1-6/1-12/1-8/1-8/1-10/1-12,',
    'bend bars/lift gates 50-100 percent',
    '- the upload table is cell-mangled',
    'and the ground truth parses it row',
    'by row), Growth (6 feet per quarter,',
    '24 feet full), Healing (4-10 2d4+2),',
    'Heroism (below 10 levels; the 3-row',
    'consumer table - energy levels 3/2/1',
    'for 1st-3rd/4th-6th/7th-9th,',
    'accumulated damage 3+1/2+2/1+3 on',
    'd10; the stray 04 4 upload row is',
    'paste noise and is skipped), Human',
    'Control (up to 32 levels/hit dice;',
    'the 8-row d20 type table dwarves 1-2',
    'through the mixed 20 row, the 20 row',
    'band and name in separate pipe',
    'cells; 5-30 rounds), and Invisibility',
    '(a gulp is 1/8 of the contents, 3-6',
    'turns). The ten potions are the',
    'engine kPotions rows 10-19, bands',
    '27-54, invulnerability from 55',
    '(cross-checked band by band against',
    'the R221 potions.h pins in the',
    'audit). New R250 battery audit;',
    'census 169. Next: R251 - potions',
    'part 3 (Invulnerability through',
    'Water Breathing, upload ~10129-10189),',
    'then the scrolls explanations (upload',
    '~10191-10280) and the rings',
    'explanations (upload ~10282-10561),',
    'then the misc magic item',
    'explanations (~10949+).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence,
# the R228 lesson; the marker MUST be contiguous in
# the header text - the R247 lesson)
marker = 'R250: the III.A potions explanation prose'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R250 FAIL: rules/potionsprose2.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R250 audit', audit_old, audit_new),
    (GAP, 'the R250 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text (the R233
    # lesson: append-style patches leave the old text
    # inside the new)
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R250 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 169:
        print('R250 FAIL: census is not 169')
        sys.exit(1)
    if t.count('R250 potions prose part 2 pins audit') != 1:
        print('R250 FAIL: the R250 audit line must appear once')
        sys.exit(1)
    if t.count('rules/potionsprose2.h') != 1:
        print('R250 FAIL: the potionsprose2 include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R250 landed the III.A potions') != 1:
        print('R250 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int pot') != 53:
        print('R250 FAIL: the header shape is wrong')
        sys.exit(1)

print('R250 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R250 note: 4 patches; the III.A potions explanation prose part 2 -')
print('Fire Resistance through Invisibility; census 169.')
print('commit: R250: the III.A potions explanation prose part 2 pins pinned - DMG pp.134-136, Fire Resistance through Invisibility (census 169)')

