#!/usr/bin/env python3
# R251 splice: the III.A potions explanation prose pins, part 3.
#
# DMG pp.136-137, upload lines ~10129-10189 - the final
# SIXTEEN potions of the III.A POTIONS explanation prose:
# Invulnerability (creatures with fewer than 4 hit dice
# cannot harm; armor class improves by 2 classes; +2 to
# saves; 5-20 rounds; fighters only), Levitation (the
# second level spell pattern; maximum weight 6,000 g.p.
# equivalent), Longevity (age reduced 1-12 years; 1%
# cumulative chance of reversal), Oil of Etherealness
# (3 rounds to take effect; lasts 4 + 1-4 turns), Oil of
# Slipperiness (95% chance per round to slip when poured
# on a floor; lasts 8 hours), Philter of Love (charm
# wears off in 4 + 1-4 turns), Philter of
# Persuasiveness (+25% on reaction dice; suggest once
# per turn within 3"), Plant Control (save at
# intelligence 5+; a 2" x 2" square; control range 9";
# 5-20 rounds), Poison (weak +1 to +4; deadly -1 to -4
# or more; neutralize poison lowers toxicity by 40%),
# Polymorph self (the fourth level spell), Speed
# (movement and combat +100%; 9" becomes 18"; ages 1
# year; 5-20 rounds), Super-Heroism (below 13 levels;
# the 4-row consumer table - energy levels 5/4/3/2,
# accumulated damage 4+1/3+2/2+3/1+4 on d10; 5-30
# melee rounds), Sweet Water (100,000 cubic feet of
# water, 1,000 cubic feet of acid; initial period
# 5-20 rounds), Treasure Finding (within 24"; at least
# 10,000 copper or 100 gems; 5-20 rounds), Undead
# Control (16 hit dice maximum; saves at -2; 5-20
# rounds; the 10-row d10 undead type table), and Water
# Breathing (75% two doses, 25% four; one hour per
# dose plus 1-10 rounds). The sixteen potions are the
# engine III.A table rows 20-35 (dm/treasure.cpp
# kPotions, bands 55-100, the table closing at 100) -
# cross-checked band by band against the R221 potions.h
# pins in the audit. THIS CLOSES THE III.A POTIONS ARC.
# Patches: 4 (new rules/potionsprose3.h, the regtest
# include, the audit block, the dmg-gap-report log
# entry). Census 169 -> 170.
#
# commit: R251: the III.A potions explanation prose part 3 pins pinned - DMG pp.136-137, Invulnerability through Water Breathing (census 170)

import sys

WD   = 'rules/potionsprose3.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson); NO already-closed pre-check
# (the R235b lesson, re-caught at R237)
t = open(REG).read()
if t.count('audit: bad ') != 169 and t.count('audit: bad ') != 170:
    print('R251 FAIL: regtest census is neither 169 nor 170')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/potionsprose3.h',
    '// R251: the III.A potions explanation prose',
    '// pins, part 3 (DMG pp.136-137) - the final',
    '// SIXTEEN potions of the EXPLANATIONS AND',
    '// DESCRIPTIONS section (upload lines',
    '// ~10129-10189):',
    '//   - Invulnerability: fewer than 4 hit',
    '//     dice cannot harm; armor class +2',
    '//     classes; +2 to saves; 5-20 rounds.',
    '//   - Levitation: as the spell, second',
    '//     level; maximum weight 6,000 g.p.',
    '//   - Longevity: age reduced 1-12 years;',
    '//     1% cumulative reversal chance.',
    '//   - Oil of Etherealness: effect in 3',
    '//     rounds; lasts 4 + 1-4 turns.',
    '//   - Oil of Slipperiness: 95% per round',
    '//     floor slip; lasts 8 hours.',
    '//   - Philter of Love: charm wears off in',
    '//     4 + 1-4 turns.',
    '//   - Philter of Persuasiveness: +25% on',
    '//     reaction dice; suggest once per',
    '//     turn within 3".',
    '//   - Plant Control: save at intelligence',
    '//     5+; a 2" x 2" square; range 9";',
    '//     5-20 rounds.',
    '//   - Poison: weak +1 to +4; deadly -1 to',
    '//     -4 or more; neutralize lowers',
    '//     toxicity by 40%.',
    '//   - Polymorph self: the fourth level',
    '//     spell.',
    '//   - Speed: +100% movement and combat; 9"',
    '//     becomes 18"; ages 1 year; 5-20',
    '//     rounds.',
    '//   - Super-Heroism: below 13 levels; the',
    '//     4-row consumer table (energy levels',
    '//     5/4/3/2, accumulated damage 4+1/',
    '//     3+2/2+3/1+4 on d10); 5-30 melee',
    '//     rounds.',
    '//   - Sweet Water: 100,000 cubic feet of',
    '//     water; 1,000 of acid; initial',
    '//     period 5-20 rounds.',
    '//   - Treasure Finding: within 24"; at',
    '//     least 10,000 copper or 100 gems;',
    '//     5-20 rounds.',
    '//   - Undead Control: 16 hit dice maximum;',
    '//     saves at -2; 5-20 rounds; the 10-row',
    '//     d10 undead type table.',
    '//   - Water Breathing: 75% two doses, 25%',
    '//     four; one hour per dose plus 1-10',
    '//     rounds.',
    '// The sixteen potions are the engine III.A',
    '// table rows 20-35 (dm/treasure.cpp',
    '// kPotions, bands 55-100, the table closing',
    '// at 100) - cross-checked against the R221',
    '// potions.h pins in the audit. THIS CLOSES',
    '// THE III.A POTIONS ARC.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int potInvulnMinHitDice() {',
    '    // Invulnerability: attacks from',
    '    // creatures with fewer than 4 hit dice',
    '    // cannot harm the imbiber',
    '    return 4;',
    '}',
    '',
    'inline int potInvulnAcClasses() {',
    '    // improves armor class rating by',
    '    // 2 classes',
    '    return 2;',
    '}',
    '',
    'inline int potInvulnSaveMod() {',
    '    // a bonus of +2 on saving throws',
    '    // versus all forms of attack',
    '    return 2;',
    '}',
    '',
    'inline int potInvulnRoundLo() {',
    '    // the effects last for 5-20 rounds',
    '    return 5;',
    '}',
    '',
    'inline int potInvulnRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int potLevitSpellLevel() {',
    '    // Levitation: much the same manner as',
    '    // the second level magic-user spell',
    '    return 2;',
    '}',
    '',
    'inline int potLevitMaxWeightGp() {',
    '    // the individual only, subject to a',
    '    // maximum weight of 6,000 g.p.',
    '    // equivalent',
    '    return 6000;',
    '}',
    '',
    'inline int potLongYearsLo() {',
    '    // Longevity: reduces game age by from',
    '    // 1-12 years',
    '    return 1;',
    '}',
    '',
    'inline int potLongYearsHi() {',
    '    return 12;',
    '}',
    '',
    'inline int potLongReversePercent() {',
    '    // each time one is drunk there is a 1%',
    '    // cumulative chance of reversing all',
    '    // previous age removal',
    '    return 1;',
    '}',
    '',
    'inline int potEtherRoundsToEffect() {',
    '    // Oil of Etherealness: takes effect 3',
    '    // rounds after application',
    '    return 3;',
    '}',
    '',
    'inline int potEtherTurnsBase() {',
    '    // it lasts for 4 + 1-4 turns',
    '    return 4;',
    '}',
    '',
    'inline int potEtherExtraLo() {',
    '    return 1;',
    '}',
    '',
    'inline int potEtherExtraHi() {',
    '    return 4;',
    '}',
    '',
    'inline int potSlipFallPercent() {',
    '    // Oil of Slipperiness: poured on a',
    '    // floor there is a 95% chance each',
    '    // round of slipping and falling',
    '    return 95;',
    '}',
    '',
    'inline int potSlipHours() {',
    '    // the oil lasts 8 hours to wear off',
    '    // normally',
    '    return 8;',
    '}',
    '',
    'inline int potLoveTurnsBase() {',
    '    // Philter of Love: charming effects',
    '    // wear off in 4 + 1-4 turns',
    '    return 4;',
    '}',
    '',
    'inline int potLoveExtraLo() {',
    '    return 1;',
    '}',
    '',
    'inline int potLoveExtraHi() {',
    '    return 4;',
    '}',
    '',
    'inline int potPersuadeReactPercent() {',
    '    // Philter of Persuasiveness: a bonus',
    '    // of 25% on reaction dice rolls',
    '    return 25;',
    '}',
    '',
    'inline int potPersuadePerTurn() {',
    '    // able to suggest once per turn',
    '    return 1;',
    '}',
    '',
    'inline int potPersuadeRangeInches() {',
    '    // to creatures within a range of 3"',
    '    return 3;',
    '}',
    '',
    'inline int potPlantSaveInt() {',
    '    // Plant Control: vegetable monsters',
    '    // of intelligence 5 or higher get a',
    '    // saving throw versus magic',
    '    return 5;',
    '}',
    '',
    'inline int potPlantSquareInches() {',
    '    // plants within a 2" x 2" square',
    '    return 2;',
    '}',
    '',
    'inline int potPlantRangeInches() {',
    '    // control range is 9"',
    '    return 9;',
    '}',
    '',
    'inline int potPlantRoundLo() {',
    '    // control for 5-20 rounds',
    '    return 5;',
    '}',
    '',
    'inline int potPlantRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int potPoisonWeakLo() {',
    '    // Poison: weak poison gives +1 to +4',
    '    // on the saving throw',
    '    return 1;',
    '}',
    '',
    'inline int potPoisonWeakHi() {',
    '    return 4;',
    '}',
    '',
    'inline int potPoisonDeadlyLo() {',
    '    // deadly poison gives -1 to -4 or',
    '    // more on the saving throw',
    '    return -4;',
    '}',
    '',
    'inline int potPoisonDeadlyHi() {',
    '    return -1;',
    '}',
    '',
    'inline int potPoisonNeutralizePercent() {',
    '    // neutralize poison can lower the',
    '    // toxicity level by 40%',
    '    return 40;',
    '}',
    '',
    'inline int potPolySpellLevel() {',
    '    // Polymorph self: the fourth level',
    '    // magic-user spell',
    '    return 4;',
    '}',
    '',
    'inline int potSpeedBoostPercent() {',
    '    // Speed: movement and combat',
    '    // capabilities increased by 100%',
    '    return 100;',
    '}',
    '',
    'inline int potSpeedMoveBaseInches() {',
    '    // a movement rate of 9" becomes 18"',
    '    return 9;',
    '}',
    '',
    'inline int potSpeedMoveBoostedInches() {',
    '    return 18;',
    '}',
    '',
    'inline int potSpeedAgeYears() {',
    '    // use ages the individual by 1 year',
    '    return 1;',
    '}',
    '',
    'inline int potSpeedRoundLo() {',
    '    // the other effects last for 5-20',
    '    // rounds',
    '    return 5;',
    '}',
    '',
    'inline int potSpeedRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int potSHeroMaxLevels() {',
    '    // Super-Heroism: a temporary increase',
    '    // in life energy levels if the imbiber',
    '    // has fewer than 13 levels',
    '    return 13;',
    '}',
    '',
    'inline int potSHeroRowCount() {',
    '    // the consumer level table: 4 rows',
    '    return 4;',
    '}',
    '',
    'inline int potSHeroDmgFaces() {',
    '    // 10-sided dice for the accumulated',
    '    // damage bestowed',
    '    return 10;',
    '}',
    '',
    'inline int potSHeroRoundLo() {',
    '    // the effects last from but 5 to 30',
    '    // melee rounds',
    '    return 5;',
    '}',
    '',
    'inline int potSHeroRoundHi() {',
    '    return 30;',
    '}',
    '',
    'inline int potSHeroLevels(int i) {',
    '    // the energy levels bestowed; i',
    '    // clamps: 1st-3rd 5, 4th-6th 4,',
    '    // 7th-9th 3, 10th-12th 2',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        5, 4, 3, 2,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potSHeroDmgDice(int i) {',
    '    // the accumulated damage dice; i',
    '    // clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        4, 3, 2, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potSHeroDmgBonus(int i) {',
    '    // the accumulated damage bonus; i',
    '    // clamps: 4 + 1, 3 + 2, 2 + 3, 1 + 4',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 2, 3, 4,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potSweetWaterCubicFeet() {',
    '    // Sweet Water: changes up to 100,000',
    '    // cubic feet of polluted, salt, or',
    '    // alkaline water to fresh water',
    '    return 100000;',
    '}',
    '',
    'inline int potSweetAcidCubicFeet() {',
    '    // turns up to 1,000 cubic feet of',
    '    // acid into pure water',
    '    return 1000;',
    '}',
    '',
    'inline int potSweetRoundLo() {',
    '    // an initial period of 5-20 rounds',
    '    return 5;',
    '}',
    '',
    'inline int potSweetRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int potTreasureRangeInches() {',
    '    // Treasure Finding: the treasure must',
    '    // be within 24" or less',
    '    return 24;',
    '}',
    '',
    'inline int potTreasureMinCopper() {',
    '    // a mass of at least 10,000 copper',
    '    // pieces',
    '    return 10000;',
    '}',
    '',
    'inline int potTreasureMinGems() {',
    '    // or 100 gems',
    '    return 100;',
    '}',
    '',
    'inline int potTreasureRoundLo() {',
    '    // the effects last for from 5-20',
    '    // rounds',
    '    return 5;',
    '}',
    '',
    'inline int potTreasureRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int potUndeadMaxHitDice() {',
    '    // Undead Control: affects a maximum',
    '    // of 16 hit dice of undead',
    '    return 16;',
    '}',
    '',
    'inline int potUndeadSaveMod() {',
    '    // saving throws are made at -2 due',
    '    // to the power of the potion',
    '    return -2;',
    '}',
    '',
    'inline int potUndeadRoundLo() {',
    '    // the effects wear off in from 5-20',
    '    // rounds',
    '    return 5;',
    '}',
    '',
    'inline int potUndeadRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int potUndeadTypeRowCount() {',
    '    // the undead type table: 10 rows',
    '    return 10;',
    '}',
    '',
    'inline int potUndeadTypeLo(int i) {',
    '    // the d10 band lower edges; i clamps:',
    '    // ghasts, ghosts, ghouls, shadows,',
    '    // skeletons, spectres, wights,',
    '    // wraiths, vampires, zombies (the',
    '    // printed 0 row is the 10 face)',
    '    if (i < 0) i = 0;',
    '    if (i > 9) i = 9;',
    '    static const int t[10] = {',
    '        1, 2, 3, 4, 5, 6, 7, 8, 9, 10,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potUndeadTypeHi(int i) {',
    '    // the d10 band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 9) i = 9;',
    '    static const int t[10] = {',
    '        1, 2, 3, 4, 5, 6, 7, 8, 9, 10,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int potUndeadTypeFaces() {',
    '    // the undead type roll is on d10',
    '    return 10;',
    '}',
    '',
    'inline int potWaterTwoDosePercent() {',
    '    // Water Breathing: 75% likely to',
    '    // contain two doses',
    '    return 75;',
    '}',
    '',
    'inline int potWaterFourDosePercent() {',
    '    // 25% probable that there will be',
    '    // four in the container',
    '    return 25;',
    '}',
    '',
    'inline int potWaterHourPerDose() {',
    '    // one full hour per dose quaffed',
    '    return 1;',
    '}',
    '',
    'inline int potWaterExtraLo() {',
    '    // an additional 1-10 rounds (minutes)',
    '    // variable',
    '    return 1;',
    '}',
    '',
    'inline int potWaterExtraHi() {',
    '    return 10;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the regtest include ----
inc_old = [
    '#include "rules/potionsprose2.h"  // R250: pp.134-136 the III.A potions prose part 2 pins',
]
inc_new = [
    '#include "rules/potionsprose2.h"  // R250: pp.134-136 the III.A potions prose part 2 pins',
    '#include "rules/potionsprose3.h"  // R251: pp.136-137 the III.A potions prose part 3 pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R251: the III.A potions explanation prose part 3 pins audit ----',
    '    // DMG pp.136-137: Invulnerability',
    '    // through Water Breathing - the potions',
    '    // arc closes.',
    '    {',
    '        int bad = 0;',
    '        // the sixteen potions are the engine III.A',
    '        // table rows 20-35 - bands 55-100, the',
    '        // table closing at 100 (the R221 pins)',
    '        if (rules::potionRowCount() != 35 ||',
    '            rules::potionRowLo(19) != 55 ||',
    '            rules::potionRowHi(34) != 100) ++bad;',
    '        // the engine rows 20-35 checked band',
    '        // by band against the R221 pins',
    '        static const int kRowLo[16] = {',
    '            55, 58, 61, 64, 67, 70, 73, 76, 79, 82,',
    '            85, 88, 91, 94, 97, 98,',
    '        };',
    '        static const int kRowHi[16] = {',
    '            57, 60, 63, 66, 69, 72, 75, 78, 81, 84,',
    '            87, 90, 93, 96, 97, 100,',
    '        };',
    '        for (int i = 0; i < 16; ++i)',
    '            if (rules::potionRowLo(i + 19) != kRowLo[i] ||',
    '                rules::potionRowHi(i + 19) != kRowHi[i]) ++bad;',
    '        // Invulnerability - the hit dice, the',
    '        // armor class, the save, and the rounds',
    '        if (rules::potInvulnMinHitDice() != 4 ||',
    '            rules::potInvulnAcClasses() != 2 ||',
    '            rules::potInvulnSaveMod() != 2 ||',
    '            rules::potInvulnRoundLo() != 5 ||',
    '            rules::potInvulnRoundHi() != 20) ++bad;',
    '        // Levitation - the spell level and the',
    '        // maximum weight',
    '        if (rules::potLevitSpellLevel() != 2 ||',
    '            rules::potLevitMaxWeightGp() != 6000) ++bad;',
    '        // Longevity - the years and the reversal',
    '        if (rules::potLongYearsLo() != 1 ||',
    '            rules::potLongYearsHi() != 12 ||',
    '            rules::potLongReversePercent() != 1) ++bad;',
    '        // Oil of Etherealness - the onset and',
    '        // the duration',
    '        if (rules::potEtherRoundsToEffect() != 3 ||',
    '            rules::potEtherTurnsBase() != 4 ||',
    '            rules::potEtherExtraLo() != 1 ||',
    '            rules::potEtherExtraHi() != 4) ++bad;',
    '        // Oil of Slipperiness - the slip chance',
    '        // and the hours',
    '        if (rules::potSlipFallPercent() != 95 ||',
    '            rules::potSlipHours() != 8) ++bad;',
    '        // Philter of Love - the charm duration',
    '        if (rules::potLoveTurnsBase() != 4 ||',
    '            rules::potLoveExtraLo() != 1 ||',
    '            rules::potLoveExtraHi() != 4) ++bad;',
    '        // Philter of Persuasiveness - the',
    '        // reaction bonus and the suggest',
    '        if (rules::potPersuadeReactPercent() != 25 ||',
    '            rules::potPersuadePerTurn() != 1 ||',
    '            rules::potPersuadeRangeInches() != 3) ++bad;',
    '        // Plant Control - the square, the range,',
    '        // and the duration',
    '        if (rules::potPlantSaveInt() != 5 ||',
    '            rules::potPlantSquareInches() != 2 ||',
    '            rules::potPlantRangeInches() != 9 ||',
    '            rules::potPlantRoundLo() != 5 ||',
    '            rules::potPlantRoundHi() != 20) ++bad;',
    '        // Poison - the save modifiers and the',
    '        // neutralize percent',
    '        if (rules::potPoisonWeakLo() != 1 ||',
    '            rules::potPoisonWeakHi() != 4 ||',
    '            rules::potPoisonDeadlyLo() != -4 ||',
    '            rules::potPoisonDeadlyHi() != -1 ||',
    '            rules::potPoisonNeutralizePercent() != 40) ++bad;',
    '        // Polymorph self - the spell level',
    '        if (rules::potPolySpellLevel() != 4) ++bad;',
    '        // Speed - the boost, the movement, the',
    '        // aging, and the rounds',
    '        if (rules::potSpeedBoostPercent() != 100 ||',
    '            rules::potSpeedMoveBaseInches() != 9 ||',
    '            rules::potSpeedMoveBoostedInches() != 18 ||',
    '            rules::potSpeedAgeYears() != 1 ||',
    '            rules::potSpeedRoundLo() != 5 ||',
    '            rules::potSpeedRoundHi() != 20) ++bad;',
    '        // Super-Heroism - the ceiling, the table,',
    '        // and the rounds',
    '        if (rules::potSHeroMaxLevels() != 13 ||',
    '            rules::potSHeroRowCount() != 4 ||',
    '            rules::potSHeroDmgFaces() != 10 ||',
    '            rules::potSHeroRoundLo() != 5 ||',
    '            rules::potSHeroRoundHi() != 30) ++bad;',
    '        static const int kSLvl[4] = {',
    '            5, 4, 3, 2,',
    '        };',
    '        static const int kSDice[4] = {',
    '            4, 3, 2, 1,',
    '        };',
    '        static const int kSBon[4] = {',
    '            1, 2, 3, 4,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::potSHeroLevels(i) != kSLvl[i] ||',
    '                rules::potSHeroDmgDice(i) != kSDice[i] ||',
    '                rules::potSHeroDmgBonus(i) != kSBon[i]) ++bad;',
    '        // Sweet Water - the volumes and the',
    '        // initial period',
    '        if (rules::potSweetWaterCubicFeet() != 100000 ||',
    '            rules::potSweetAcidCubicFeet() != 1000 ||',
    '            rules::potSweetRoundLo() != 5 ||',
    '            rules::potSweetRoundHi() != 20) ++bad;',
    '        // Treasure Finding - the range, the',
    '        // mass, and the rounds',
    '        if (rules::potTreasureRangeInches() != 24 ||',
    '            rules::potTreasureMinCopper() != 10000 ||',
    '            rules::potTreasureMinGems() != 100 ||',
    '            rules::potTreasureRoundLo() != 5 ||',
    '            rules::potTreasureRoundHi() != 20) ++bad;',
    '        // Undead Control - the hit dice, the',
    '        // save, the rounds, and the type table',
    '        if (rules::potUndeadMaxHitDice() != 16 ||',
    '            rules::potUndeadSaveMod() != -2 ||',
    '            rules::potUndeadRoundLo() != 5 ||',
    '            rules::potUndeadRoundHi() != 20 ||',
    '            rules::potUndeadTypeRowCount() != 10 ||',
    '            rules::potUndeadTypeFaces() != 10) ++bad;',
    '        static const int kULo[10] = {',
    '            1, 2, 3, 4, 5, 6, 7, 8, 9, 10,',
    '        };',
    '        static const int kUHi[10] = {',
    '            1, 2, 3, 4, 5, 6, 7, 8, 9, 10,',
    '        };',
    '        for (int i = 0; i < 10; ++i)',
    '            if (rules::potUndeadTypeLo(i) != kULo[i] ||',
    '                rules::potUndeadTypeHi(i) != kUHi[i]) ++bad;',
    '        for (int i = 1; i < 10; ++i)',
    '            if (rules::potUndeadTypeLo(i) !=',
    '                rules::potUndeadTypeHi(i - 1) + 1) ++bad;',
    '        if (rules::potUndeadTypeLo(-5) != 1 ||',
    '            rules::potUndeadTypeHi(99) != 10) ++bad;',
    '        // Water Breathing - the doses and the',
    '        // duration',
    '        if (rules::potWaterTwoDosePercent() != 75 ||',
    '            rules::potWaterFourDosePercent() != 25 ||',
    '            rules::potWaterHourPerDose() != 1 ||',
    '            rules::potWaterExtraLo() != 1 ||',
    '            rules::potWaterExtraHi() != 10) ++bad;',
    '        printf("R251 potions prose part 3 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg gap report log entry ----
gap_old = [
    'then the misc magic item',
    'explanations (~10949+).',
]
gap_new = [
    'then the misc magic item',
    'explanations (~10949+).',
    '',
    'R251 landed the III.A potions',
    'explanation prose pins, part 3 of 3',
    '(DMG pp.136-137, upload lines',
    '~10129-10189) - the final sixteen',
    'potions, Invulnerability through',
    'Water Breathing. THIS CLOSES THE',
    'III.A POTIONS ARC END TO END (the',
    'R249 conventions through the R251',
    'final row, engine bands 01-100).',
    'rules/potionsprose3.h (the part-3',
    'pattern, the pot prefix continues -',
    '69 accessors, of which 5 are array',
    'walkers): Invulnerability (fewer',
    'than 4 hit dice cannot harm, armor',
    'class +2 classes, saves +2, 5-20',
    'rounds), Levitation (second level',
    'spell, 6,000 g.p. maximum),',
    'Longevity (1-12 years, 1% cumulative',
    'reversal), Oil of Etherealness (3',
    'rounds onset, 4 + 1-4 turns), Oil',
    'of Slipperiness (95% per round',
    'floor slip, 8 hours), Philter of',
    'Love (charm 4 + 1-4 turns), Philter',
    'of Persuasiveness (+25% reaction',
    'dice, suggest once per turn within',
    '3"), Plant Control (intelligence 5+',
    'save, 2" x 2" square, range 9",',
    '5-20 rounds), Poison (weak +1/+4,',
    'deadly -1/-4 or more, neutralize',
    '40%), Polymorph self (fourth level',
    'spell), Speed (+100%, 9" becomes',
    '18", ages 1 year, 5-20 rounds),',
    'Super-Heroism (below 13 levels; the',
    '4-row consumer table - energy',
    'levels 5/4/3/2, accumulated damage',
    '4+1/3+2/2+3/1+4 on d10; 5-30 melee',
    'rounds; the stray 06 5 upload row',
    'is paste noise and is skipped),',
    'Sweet Water (100,000 cubic feet',
    'water, 1,000 acid, initial period',
    '5-20 rounds), Treasure Finding',
    '(within 24", 10,000 copper or 100',
    'gems, 5-20 rounds), Undead Control',
    '(16 hit dice, saves -2, 5-20',
    'rounds; the 10-row d10 undead type',
    'table ghasts through zombies, the',
    'printed 0 row pinned as the 10',
    'face; the upload table is',
    'cell-mangled - the band digit and',
    'the name share a cell with no',
    'space on some rows), and Water',
    'Breathing (75% two doses, 25% four,',
    'one hour per dose plus 1-10',
    'rounds). The TREASURE (POTIONS)',
    'running page header splits the Oil',
    'of Slipperiness paragraph mid-',
    'sentence (upload ~10138) - stripped',
    'by the ground truth, per the R249',
    'page-header lesson. The sixteen',
    'potions are the engine kPotions',
    'rows 20-35, bands 55-100, closing',
    'the table at 100 (cross-checked band',
    'by band against the R221 potions.h',
    'pins in the audit). New R251',
    'battery audit; census 170. Next:',
    'the scrolls explanations (upload',
    '~10191-10280), then the rings',
    'explanations (upload ~10282-10561),',
    'then the misc magic item',
    'explanations III.E (part1 ~10948-',
    '11067 continuing seamlessly into',
    'part2; global line = part1 line or',
    '~11065 + part2 line, the TREASURE',
    '(MISCELLANEOUS MAGIC) headers are',
    'running page headers mid-paragraph).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence,
# the R228 lesson; the marker MUST be contiguous in
# the header text - the R247 lesson)
marker = 'R251: the III.A potions explanation prose'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R251 FAIL: rules/potionsprose3.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R251 audit', audit_old, audit_new),
    (GAP, 'the R251 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text (the R233
    # lesson: append-style patches leave the old text
    # inside the new)
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R251 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 170:
        print('R251 FAIL: census is not 170')
        sys.exit(1)
    if t.count('R251 potions prose part 3 pins audit') != 1:
        print('R251 FAIL: the R251 audit line must appear once')
        sys.exit(1)
    if t.count('rules/potionsprose3.h') != 1:
        print('R251 FAIL: the potionsprose3 include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R251 landed the III.A potions') != 1:
        print('R251 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int pot') != 69:
        print('R251 FAIL: the header shape is wrong')
        sys.exit(1)

print('R251 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R251 note: 4 patches; the III.A potions explanation prose part 3 -')
print('Invulnerability through Water Breathing; census 170. THE POTIONS ARC CLOSES.')
print('commit: R251: the III.A potions explanation prose part 3 pins pinned - DMG pp.136-137, Invulnerability through Water Breathing (census 170)')

