#!/usr/bin/env python3
# R252 splice: the III.B scrolls explanation prose pins.
#
# DMG pp.137-139, upload lines ~10191-10280 - the III.B
# SCROLLS explanation prose, the opener of the second
# EXPLANATIONS arc (the III.A potions arc closed at
# R251): the general scroll mechanics and the EIGHT
# protection scrolls. The mechanics: the class table
# (first roll 01-70 magic-user, then 01-10 illusionist;
# 71-00 cleric, then 01-25 druid); unread scrolls 5% to
# 30% likely to fade (d6 option); scroll spells written
# 1 level above the usable level, never below 6th (a
# sixth level spell written at 13th, a seventh at
# 15th); a scroll fireball or lightning bolt is 6 dice
# (6d6); spell failure 5% per level difference (the
# wish example: 18 - 1 = 17 x 5% = 85%); the 6-row
# level-difference table (total failure 95/85/75/65/
# 50/30, reverse-or-harmful 5/15/25/35/50/70); reading
# a scroll of 7 spells makes it a scroll of 6. The
# protection scrolls: Demons (1 full round all demons,
# 7 segments type VI or lower, 3 segments type III or
# lower; 10 foot radius; 5-20 5d4 rounds), Devils (1
# round all, 7 segments greater, 3 segments lesser),
# Elementals (6 segments; the 5-variety table air
# 01-15 through all 61-00; 10 foot radius; 24 hit dice
# specific, 16 all; 5-40 5d8 rounds), Lycanthropes (4
# segments; the 7-type table werebears 01-05 through
# shape-changers 99-00; 10 foot radius; 49 hit dice,
# pluses rounded down unless they exceed +2; 5-30
# rounds), Magic (8 segments; 5 foot radius; 50%
# drain, save 11 or better on d20; 5-30 5d6 rounds),
# Petrification (5 segments; 10 foot radius; 5-20 5d4
# rounds), Possession (1 round; 10 foot radius; 10-60
# rounds in 90% of scrolls, 10% have 10-60 turns but
# stationary), and Undead (4 segments; 5 foot radius;
# 10 undead types; 35 hit dice/levels; 10-80 10d8
# rounds). The eight scrolls are the engine III.B
# table rows 61-97 (dm/treasure.cpp rollScroll, the
# R222 scrollpins.h pins) - cross-checked band by band
# in the audit. The undead type count cross-pins the
# R251 potUndeadTypeRowCount (the prose Cf. sanctions
# it). Patches: 4 (new rules/scrollsprose.h, the
# regtest include, the audit block, the dmg-gap-report
# log entry). Census 170 -> 171.
#
# commit: R252: the III.B scrolls explanation prose pins pinned - DMG pp.137-139, the scroll mechanics and the eight protection scrolls (census 171)

import sys

WD   = 'rules/scrollsprose.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson); NO already-closed pre-check
# (the R235b lesson, re-caught at R237)
t = open(REG).read()
if t.count('audit: bad ') != 170 and t.count('audit: bad ') != 171:
    print('R252 FAIL: regtest census is neither 170 nor 171')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/scrollsprose.h',
    '// R252: the III.B scrolls explanation prose',
    '// pins (DMG pp.137-139) - the general',
    '// scroll mechanics and the EIGHT protection',
    '// scrolls of the EXPLANATIONS AND',
    '// DESCRIPTIONS section (upload lines',
    '// ~10191-10280):',
    '//   - the class table: first roll 01-70',
    '//     magic-user (then 01-10 illusionist),',
    '//     71-00 cleric (then 01-25 druid).',
    '//   - unread scrolls: 5% to 30% likely to',
    '//     fade; a d6 can set the percentage.',
    '//   - scroll spells are written 1 level',
    '//     above the usable level, never below',
    '//     6th; a sixth level spell written at',
    '//     13th, a seventh at 15th; a scroll',
    '//     fireball or lightning bolt is 6 dice',
    '//     (6d6).',
    '//   - spell failure: 5% per level',
    '//     difference (the wish example 18 - 1 =',
    '//     17 x 5% = 85%); the 6-row',
    '//     level-difference table.',
    '//   - reading a scroll of 7 spells makes',
    '//     it a scroll of 6.',
    '//   - Demons: 1 full round all demons, 7',
    '//     segments type VI or lower, 3 segments',
    '//     type III or lower; 10 foot radius;',
    '//     5-20 (5d4) rounds.',
    '//   - Devils: 1 round all, 7 segments',
    '//     greater, 3 segments lesser.',
    '//   - Elementals: 6 segments; the',
    '//     5-variety table; 10 foot radius; 24',
    '//     hit dice specific, 16 all; 5-40',
    '//     (5d8) rounds.',
    '//   - Lycanthropes: 4 segments; the 7-type',
    '//     table; 10 foot radius; 49 hit dice,',
    '//     pluses rounded down unless they',
    '//     exceed +2; 5-30 rounds.',
    '//   - Magic: 8 segments; 5 foot radius;',
    '//     50% drain, save 11 or better on d20;',
    '//     5-30 (5d6) rounds.',
    '//   - Petrification: 5 segments; 10 foot',
    '//     radius; 5-20 (5d4) rounds.',
    '//   - Possession: 1 round; 10 foot',
    '//     radius; 10-60 rounds in 90% of',
    '//     scrolls, 10% have 10-60 turns but',
    '//     stationary.',
    '//   - Undead: 4 segments; 5 foot radius;',
    '//     10 undead types; 35 hit dice/levels;',
    '//     10-80 (10d8) rounds.',
    '// The eight scrolls are the engine III.B',
    '// table rows 61-97 (dm/treasure.cpp',
    '// rollScroll, the R222 scrollpins.h pins) -',
    '// cross-checked against them in the audit.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int scpClassMuLo() {',
    '    // the class table: first roll 01-70',
    '    // magic-user',
    '    return 1;',
    '}',
    '',
    'inline int scpClassMuHi() {',
    '    return 70;',
    '}',
    '',
    'inline int scpClassIlluLo() {',
    '    // then 01-10 illusionist',
    '    return 1;',
    '}',
    '',
    'inline int scpClassIlluHi() {',
    '    return 10;',
    '}',
    '',
    'inline int scpClassClericLo() {',
    '    // 71-00 cleric',
    '    return 71;',
    '}',
    '',
    'inline int scpClassClericHi() {',
    '    return 100;',
    '}',
    '',
    'inline int scpClassDruidLo() {',
    '    // then 01-25 druid',
    '    return 1;',
    '}',
    '',
    'inline int scpClassDruidHi() {',
    '    return 25;',
    '}',
    '',
    'inline int scpFadePercentLo() {',
    '    // unread scrolls are from 5% to 30%',
    '    // likely to fade',
    '    return 5;',
    '}',
    '',
    'inline int scpFadePercentHi() {',
    '    return 30;',
    '}',
    '',
    'inline int scpFadeDieFaces() {',
    '    // a d6 can randomly determine it',
    '    return 6;',
    '}',
    '',
    'inline int scpWriteLevelAdd() {',
    '    // scroll spells are written typically',
    '    // 1 level higher than that required',
    '    // to actually use the spell',
    '    return 1;',
    '}',
    '',
    'inline int scpWriteLevelFloor() {',
    '    // but never below 6th level of',
    '    // experience',
    '    return 6;',
    '}',
    '',
    'inline int scpSixthLevelSpellWrittenAt() {',
    '    // a sixth level magic-user spell is',
    '    // written at 13th level of ability',
    '    return 13;',
    '}',
    '',
    'inline int scpSeventhLevelSpellWrittenAt() {',
    '    // a seventh at 15th level',
    '    return 15;',
    '}',
    '',
    'inline int scpScrollFireballDice() {',
    '    // a scroll fireball or lightning bolt',
    '    // spell is of 6 dice (6d6)',
    '    return 6;',
    '}',
    '',
    'inline int scpScrollFireballFaces() {',
    '    return 6;',
    '}',
    '',
    'inline int scpFailPercentPerLevel() {',
    '    // spell failure: the chance of failure',
    '    // is 5% per level difference',
    '    return 5;',
    '}',
    '',
    'inline int scpWishExampleDiffLevels() {',
    '    // the wish example: 18 - 1 = 17 levels',
    '    // of difference',
    '    return 17;',
    '}',
    '',
    'inline int scpWishExampleFailPercent() {',
    '    // 17 x 5% = 85% chance of failure',
    '    return 85;',
    '}',
    '',
    'inline int scpFailRowCount() {',
    '    // the level-difference table: 6 rows',
    '    return 6;',
    '}',
    '',
    'inline int scpFailDiffStep() {',
    '    // the difference bands step by 3',
    '    return 3;',
    '}',
    '',
    'inline int scpFailDiffLo(int i) {',
    '    // the difference band lower edges; i',
    '    // clamps: 1-3, 4-6, 7-9, 10-12,',
    '    // 13-15, 16 and up',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        1, 4, 7, 10, 13, 16,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int scpFailTotal(int i) {',
    '    // the total failure percents; i clamps:',
    '    // 95, 85, 75, 65, 50, 30',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        95, 85, 75, 65, 50, 30,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int scpFailHarmful(int i) {',
    '    // the reverse-or-harmful percents; i',
    '    // clamps: 5, 15, 25, 35, 50, 70',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        5, 15, 25, 35, 50, 70,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int scpSevenSpellScrollReducesTo() {',
    '    // reading a spell from a scroll of 7',
    '    // spells makes it a scroll of 6',
    '    return 6;',
    '}',
    '',
    'inline int scpDemonsReadAllRounds() {',
    '    // Protection from Demons: 1 full round',
    '    // to read for all demons including',
    '    // demon princes',
    '    return 1;',
    '}',
    '',
    'inline int scpDemonsReadTypeVISegments() {',
    '    // 7 segments for type VI or lower',
    '    return 7;',
    '}',
    '',
    'inline int scpDemonsReadTypeIIISegments() {',
    '    // 3 segments for type III or lower',
    '    return 3;',
    '}',
    '',
    'inline int scpDemonsRadiusFeet() {',
    '    // the circle springs outwards in a 10',
    '    // foot radius',
    '    return 10;',
    '}',
    '',
    'inline int scpDemonsRoundLo() {',
    '    // the effect lasts for 5-20 (5d4)',
    '    // rounds',
    '    return 5;',
    '}',
    '',
    'inline int scpDemonsRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int scpDemonsDice() {',
    '    return 5;',
    '}',
    '',
    'inline int scpDemonsFaces() {',
    '    return 4;',
    '}',
    '',
    'inline int scpDevilsReadAllRounds() {',
    '    // Protection from Devils: 1 round to',
    '    // read for all kinds including',
    '    // arch-devils',
    '    return 1;',
    '}',
    '',
    'inline int scpDevilsReadGreaterSegments() {',
    '    // 7 segments for greater devils or',
    '    // lower',
    '    return 7;',
    '}',
    '',
    'inline int scpDevilsReadLesserSegments() {',
    '    // 3 segments for lesser devils or',
    '    // lower',
    '    return 3;',
    '}',
    '',
    'inline int scpElemReadSegments() {',
    '    // Protection from Elementals: reading',
    '    // time 6 segments',
    '    return 6;',
    '}',
    '',
    'inline int scpElemVarietyRowCount() {',
    '    // the variety table: 5 rows',
    '    return 5;',
    '}',
    '',
    'inline int scpElemVarLo(int i) {',
    '    // the printed band lower edges; i',
    '    // clamps: air, earth, fire, water, all',
    '    if (i < 0) i = 0;',
    '    if (i > 4) i = 4;',
    '    static const int t[5] = {',
    '        1, 16, 31, 46, 61,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int scpElemVarHi(int i) {',
    '    // the printed band upper edges; i',
    '    // clamps: 15, 30, 45, 60, 00 (=100)',
    '    if (i < 0) i = 0;',
    '    if (i > 4) i = 4;',
    '    static const int t[5] = {',
    '        15, 30, 45, 60, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int scpElemRadiusFeet() {',
    '    // the reader and all within 10 feet',
    '    return 10;',
    '}',
    '',
    'inline int scpElemHitDiceSpecific() {',
    '    // a maximum of 24 hit dice of elemental',
    '    // creatures for a specific type',
    '    return 24;',
    '}',
    '',
    'inline int scpElemHitDiceAll() {',
    '    // 16 hit dice against all sorts',
    '    return 16;',
    '}',
    '',
    'inline int scpElemRoundLo() {',
    '    // the spell lasts for 5-40 (5d8)',
    '    // rounds',
    '    return 5;',
    '}',
    '',
    'inline int scpElemRoundHi() {',
    '    return 40;',
    '}',
    '',
    'inline int scpElemDice() {',
    '    return 5;',
    '}',
    '',
    'inline int scpElemFaces() {',
    '    return 8;',
    '}',
    '',
    'inline int scpLycaReadSegments() {',
    '    // Protection from Lycanthropes: reading',
    '    // time 4 segments',
    '    return 4;',
    '}',
    '',
    'inline int scpLycaTypeRowCount() {',
    '    // the type table: 7 rows',
    '    return 7;',
    '}',
    '',
    'inline int scpLycaTypeLo(int i) {',
    '    // the printed band lower edges; i',
    '    // clamps: werebears, wereboars,',
    '    // wererats, weretigers, werewolves,',
    '    // all lycanthropes, shape-changers',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        1, 6, 11, 21, 26, 41, 99,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int scpLycaTypeHi(int i) {',
    '    // the printed band upper edges; i',
    '    // clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        5, 10, 20, 25, 40, 98, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int scpLycaRadiusFeet() {',
    '    // the magic circle extends in a 10',
    '    // foot radius',
    '    return 10;',
    '}',
    '',
    'inline int scpLycaHitDice() {',
    '    // each scroll protects against 49 hit',
    '    // dice of lycanthropes',
    '    return 49;',
    '}',
    '',
    'inline int scpLycaPlusTolerance() {',
    '    // hit point pluses are rounded down',
    '    // unless they exceed +2',
    '    return 2;',
    '}',
    '',
    'inline int scpLycaRoundLo() {',
    '    // the magic lasts for 5-30 rounds',
    '    return 5;',
    '}',
    '',
    'inline int scpLycaRoundHi() {',
    '    return 30;',
    '}',
    '',
    'inline int scpMagicReadSegments() {',
    '    // Protection from Magic: reading time',
    '    // 8 segments',
    '    return 8;',
    '}',
    '',
    'inline int scpMagicRadiusFeet() {',
    '    // the globe of anti-magic in a 5 foot',
    '    // radius',
    '    return 5;',
    '}',
    '',
    'inline int scpMagicDrainPercent() {',
    '    // a magical item touching the globe',
    '    // is 50% likely to be drained',
    '    return 50;',
    '}',
    '',
    'inline int scpMagicDrainSaveRoll() {',
    '    // save equals 11 or better',
    '    return 11;',
    '}',
    '',
    'inline int scpMagicDrainSaveFaces() {',
    '    // the save is with d20',
    '    return 20;',
    '}',
    '',
    'inline int scpMagicRoundLo() {',
    '    // the protection lasts for 5-30',
    '    // (5d6) rounds',
    '    return 5;',
    '}',
    '',
    'inline int scpMagicRoundHi() {',
    '    return 30;',
    '}',
    '',
    'inline int scpMagicDice() {',
    '    return 5;',
    '}',
    '',
    'inline int scpMagicFaces() {',
    '    return 6;',
    '}',
    '',
    'inline int scpPetrifyReadSegments() {',
    '    // Protection from Petrification:',
    '    // reading time 5 segments',
    '    return 5;',
    '}',
    '',
    'inline int scpPetrifyRadiusFeet() {',
    '    // a 10 foot radius circle of',
    '    // protection',
    '    return 10;',
    '}',
    '',
    'inline int scpPetrifyRoundLo() {',
    '    // the protection lasts for 5-20',
    '    // (5d4) rounds',
    '    return 5;',
    '}',
    '',
    'inline int scpPetrifyRoundHi() {',
    '    return 20;',
    '}',
    '',
    'inline int scpPetrifyDice() {',
    '    return 5;',
    '}',
    '',
    'inline int scpPetrifyFaces() {',
    '    return 4;',
    '}',
    '',
    'inline int scpPossessReadRounds() {',
    '    // Protection from Possession: reading',
    '    // time 1 round',
    '    return 1;',
    '}',
    '',
    'inline int scpPossessRadiusFeet() {',
    '    // a magic circle of 10 foot radius',
    '    return 10;',
    '}',
    '',
    'inline int scpPossessRoundLo() {',
    '    // the protection lasts 10 to 60 rounds',
    '    // in 90% of these scrolls',
    '    return 10;',
    '}',
    '',
    'inline int scpPossessRoundHi() {',
    '    return 60;',
    '}',
    '',
    'inline int scpPossessRoundsPercent() {',
    '    // 90% of these scrolls',
    '    return 90;',
    '}',
    '',
    'inline int scpPossessTurnsPercent() {',
    '    // 10% have power lasting in turns',
    '    return 10;',
    '}',
    '',
    'inline int scpPossessTurnLo() {',
    '    // 10 to 60 turns, but the protection',
    '    // is stationary',
    '    return 10;',
    '}',
    '',
    'inline int scpPossessTurnHi() {',
    '    return 60;',
    '}',
    '',
    'inline int scpUndeadReadSegments() {',
    '    // Protection from Undead: reading time',
    '    // 4 segments',
    '    return 4;',
    '}',
    '',
    'inline int scpUndeadRadiusFeet() {',
    '    // a 5 foot radius circle of',
    '    // protection',
    '    return 5;',
    '}',
    '',
    'inline int scpUndeadTypeCount() {',
    '    // physical attacks from 10 undead',
    '    // types: ghasts, ghosts, ghouls,',
    '    // shadows, skeletons, spectres,',
    '    // wights, wraiths, vampires, zombies',
    '    return 10;',
    '}',
    '',
    'inline int scpUndeadHitDice() {',
    '    // restrains up to 35 hit',
    '    // dice/levels of undead',
    '    return 35;',
    '}',
    '',
    'inline int scpUndeadRoundLo() {',
    '    // it remains in effect for 10-80',
    '    // (10d8) rounds',
    '    return 10;',
    '}',
    '',
    'inline int scpUndeadRoundHi() {',
    '    return 80;',
    '}',
    '',
    'inline int scpUndeadDice() {',
    '    return 10;',
    '}',
    '',
    'inline int scpUndeadFaces() {',
    '    return 8;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the regtest include ----
inc_old = [
    '#include "rules/potionsprose3.h"  // R251: pp.136-137 the III.A potions prose part 3 pins',
]
inc_new = [
    '#include "rules/potionsprose3.h"  // R251: pp.136-137 the III.A potions prose part 3 pins',
    '#include "rules/scrollsprose.h"  // R252: pp.137-139 the III.B scrolls explanation prose pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R252: the III.B scrolls explanation prose pins audit ----',
    '    // DMG pp.137-139: the scroll mechanics',
    '    // and the eight protection scrolls.',
    '    {',
    '        int bad = 0;',
    '        // the eight scrolls are the engine III.B',
    '        // table rows 61-97 (the R222',
    '        // scrollpins.h pins)',
    '        if (rules::scrollProtRowCount() != 8 ||',
    '            rules::scrollProtRowLo(0) != 61 ||',
    '            rules::scrollProtRowHi(7) != 97) ++bad;',
    '        static const int kPLo[8] = {',
    '            61, 63, 65, 71, 77, 83, 88, 93,',
    '        };',
    '        static const int kPHi[8] = {',
    '            62, 64, 70, 76, 82, 87, 92, 97,',
    '        };',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::scrollProtRowLo(i) != kPLo[i] ||',
    '                rules::scrollProtRowHi(i) != kPHi[i]) ++bad;',
    '        // the class table - the first and',
    '        // second rolls',
    '        if (rules::scpClassMuLo() != 1 ||',
    '            rules::scpClassMuHi() != 70 ||',
    '            rules::scpClassIlluLo() != 1 ||',
    '            rules::scpClassIlluHi() != 10 ||',
    '            rules::scpClassClericLo() != 71 ||',
    '            rules::scpClassClericHi() != 100 ||',
    '            rules::scpClassDruidLo() != 1 ||',
    '            rules::scpClassDruidHi() != 25) ++bad;',
    '        // the fading chance',
    '        if (rules::scpFadePercentLo() != 5 ||',
    '            rules::scpFadePercentHi() != 30 ||',
    '            rules::scpFadeDieFaces() != 6) ++bad;',
    '        // the spell level of scroll spells',
    '        if (rules::scpWriteLevelAdd() != 1 ||',
    '            rules::scpWriteLevelFloor() != 6 ||',
    '            rules::scpSixthLevelSpellWrittenAt() != 13 ||',
    '            rules::scpSeventhLevelSpellWrittenAt() != 15 ||',
    '            rules::scpScrollFireballDice() != 6 ||',
    '            rules::scpScrollFireballFaces() != 6) ++bad;',
    '        // magic spell failure - the percent,',
    '        // the wish example, and the table',
    '        if (rules::scpFailPercentPerLevel() != 5 ||',
    '            rules::scpWishExampleDiffLevels() != 17 ||',
    '            rules::scpWishExampleFailPercent() != 85 ||',
    '            rules::scpFailRowCount() != 6 ||',
    '            rules::scpFailDiffStep() != 3) ++bad;',
    '        static const int kFDiffLo[6] = {',
    '            1, 4, 7, 10, 13, 16,',
    '        };',
    '        static const int kFTotal[6] = {',
    '            95, 85, 75, 65, 50, 30,',
    '        };',
    '        static const int kFHarm[6] = {',
    '            5, 15, 25, 35, 50, 70,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::scpFailDiffLo(i) != kFDiffLo[i] ||',
    '                rules::scpFailTotal(i) != kFTotal[i] ||',
    '                rules::scpFailHarmful(i) != kFHarm[i]) ++bad;',
    '        for (int i = 1; i < 6; ++i)',
    '            if (rules::scpFailDiffLo(i) !=',
    '                rules::scpFailDiffLo(i - 1) + 3) ++bad;',
    '        // the use of scroll spells',
    '        if (rules::scpSevenSpellScrollReducesTo() != 6) ++bad;',
    '        // protection from demons',
    '        if (rules::scpDemonsReadAllRounds() != 1 ||',
    '            rules::scpDemonsReadTypeVISegments() != 7 ||',
    '            rules::scpDemonsReadTypeIIISegments() != 3 ||',
    '            rules::scpDemonsRadiusFeet() != 10 ||',
    '            rules::scpDemonsRoundLo() != 5 ||',
    '            rules::scpDemonsRoundHi() != 20 ||',
    '            rules::scpDemonsDice() != 5 ||',
    '            rules::scpDemonsFaces() != 4) ++bad;',
    '        // protection from devils',
    '        if (rules::scpDevilsReadAllRounds() != 1 ||',
    '            rules::scpDevilsReadGreaterSegments() != 7 ||',
    '            rules::scpDevilsReadLesserSegments() != 3) ++bad;',
    '        // protection from elementals - and the',
    '        // variety table',
    '        if (rules::scpElemReadSegments() != 6 ||',
    '            rules::scpElemVarietyRowCount() != 5 ||',
    '            rules::scpElemRadiusFeet() != 10 ||',
    '            rules::scpElemHitDiceSpecific() != 24 ||',
    '            rules::scpElemHitDiceAll() != 16 ||',
    '            rules::scpElemRoundLo() != 5 ||',
    '            rules::scpElemRoundHi() != 40 ||',
    '            rules::scpElemDice() != 5 ||',
    '            rules::scpElemFaces() != 8) ++bad;',
    '        static const int kELo[5] = {',
    '            1, 16, 31, 46, 61,',
    '        };',
    '        static const int kEHi[5] = {',
    '            15, 30, 45, 60, 100,',
    '        };',
    '        for (int i = 0; i < 5; ++i)',
    '            if (rules::scpElemVarLo(i) != kELo[i] ||',
    '                rules::scpElemVarHi(i) != kEHi[i]) ++bad;',
    '        for (int i = 1; i < 5; ++i)',
    '            if (rules::scpElemVarLo(i) !=',
    '                rules::scpElemVarHi(i - 1) + 1) ++bad;',
    '        if (rules::scpElemVarLo(-5) != 1 ||',
    '            rules::scpElemVarHi(99) != 100) ++bad;',
    '        // protection from lycanthropes - and the',
    '        // type table',
    '        if (rules::scpLycaReadSegments() != 4 ||',
    '            rules::scpLycaTypeRowCount() != 7 ||',
    '            rules::scpLycaRadiusFeet() != 10 ||',
    '            rules::scpLycaHitDice() != 49 ||',
    '            rules::scpLycaPlusTolerance() != 2 ||',
    '            rules::scpLycaRoundLo() != 5 ||',
    '            rules::scpLycaRoundHi() != 30) ++bad;',
    '        static const int kLLo[7] = {',
    '            1, 6, 11, 21, 26, 41, 99,',
    '        };',
    '        static const int kLHi[7] = {',
    '            5, 10, 20, 25, 40, 98, 100,',
    '        };',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::scpLycaTypeLo(i) != kLLo[i] ||',
    '                rules::scpLycaTypeHi(i) != kLHi[i]) ++bad;',
    '        for (int i = 1; i < 7; ++i)',
    '            if (rules::scpLycaTypeLo(i) !=',
    '                rules::scpLycaTypeHi(i - 1) + 1) ++bad;',
    '        if (rules::scpLycaTypeLo(-5) != 1 ||',
    '            rules::scpLycaTypeHi(99) != 100) ++bad;',
    '        // protection from magic',
    '        if (rules::scpMagicReadSegments() != 8 ||',
    '            rules::scpMagicRadiusFeet() != 5 ||',
    '            rules::scpMagicDrainPercent() != 50 ||',
    '            rules::scpMagicDrainSaveRoll() != 11 ||',
    '            rules::scpMagicDrainSaveFaces() != 20 ||',
    '            rules::scpMagicRoundLo() != 5 ||',
    '            rules::scpMagicRoundHi() != 30 ||',
    '            rules::scpMagicDice() != 5 ||',
    '            rules::scpMagicFaces() != 6) ++bad;',
    '        // protection from petrification',
    '        if (rules::scpPetrifyReadSegments() != 5 ||',
    '            rules::scpPetrifyRadiusFeet() != 10 ||',
    '            rules::scpPetrifyRoundLo() != 5 ||',
    '            rules::scpPetrifyRoundHi() != 20 ||',
    '            rules::scpPetrifyDice() != 5 ||',
    '            rules::scpPetrifyFaces() != 4) ++bad;',
    '        // protection from possession',
    '        if (rules::scpPossessReadRounds() != 1 ||',
    '            rules::scpPossessRadiusFeet() != 10 ||',
    '            rules::scpPossessRoundLo() != 10 ||',
    '            rules::scpPossessRoundHi() != 60 ||',
    '            rules::scpPossessRoundsPercent() != 90 ||',
    '            rules::scpPossessTurnsPercent() != 10 ||',
    '            rules::scpPossessTurnLo() != 10 ||',
    '            rules::scpPossessTurnHi() != 60) ++bad;',
    '        // protection from undead - the type',
    '        // count cross-pins the R251 undead',
    '        // control potion (the prose Cf.)',
    '        if (rules::scpUndeadReadSegments() != 4 ||',
    '            rules::scpUndeadRadiusFeet() != 5 ||',
    '            rules::scpUndeadTypeCount() != 10 ||',
    '            rules::potUndeadTypeRowCount() != 10 ||',
    '            rules::scpUndeadHitDice() != 35 ||',
    '            rules::scpUndeadRoundLo() != 10 ||',
    '            rules::scpUndeadRoundHi() != 80 ||',
    '            rules::scpUndeadDice() != 10 ||',
    '            rules::scpUndeadFaces() != 8) ++bad;',
    '        printf("R252 scrolls prose pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg gap report log entry ----
gap_old = [
    '(MISCELLANEOUS MAGIC) headers are',
    'running page headers mid-paragraph).',
]
gap_new = [
    '(MISCELLANEOUS MAGIC) headers are',
    'running page headers mid-paragraph).',
    '',
    'R252 landed the III.B scrolls',
    'explanation prose pins (DMG',
    'pp.137-139, upload lines',
    '~10191-10280) - the second',
    'EXPLANATIONS arc opens: the general',
    'scroll mechanics and the EIGHT',
    'protection scrolls. rules/',
    'scrollsprose.h (the grenade.h',
    'pattern, the scp prefix - distinct',
    'from the R222 scroll prefix - 88',
    'accessors, of which 7 are array',
    'walkers): the class table (01-70',
    'magic-user then 01-10 illusionist,',
    '71-00 cleric then 01-25 druid -',
    'matching the engine 30% clerical',
    'of which 25% druidical and 10%',
    'illusionist flavor note), unread',
    'scrolls 5-30% likely to fade',
    '(d6 option), scroll spells written',
    '1 level above usable level never',
    'below 6th (sixth at 13th, seventh',
    'at 15th), the scroll fireball 6',
    'dice 6d6, spell failure 5% per',
    'level difference (the wish example',
    '18 - 1 = 17 x 5% = 85%), the',
    '6-row level-difference table',
    '(total failure 95/85/75/65/50/30,',
    'reverse-or-harmful 5/15/25/35/50/',
    '70), the scroll of 7 spells reducing',
    'to 6 on a read, and the eight',
    'protection scrolls: Demons (1 full',
    'round / 7 segments type VI / 3',
    'segments type III, 10 foot radius,',
    '5-20 5d4 rounds), Devils (1 round /',
    '7 greater / 3 lesser), Elementals',
    '(6 segments, the 5-variety table',
    'air 01-15 through all 61-00, 10',
    'foot radius, 24 hit dice specific',
    '16 all, 5-40 5d8 rounds),',
    'Lycanthropes (4 segments, the',
    '7-type table werebears 01-05',
    'through shape-changers 99-00, 10',
    'foot radius, 49 hit dice, pluses',
    'rounded down unless they exceed',
    '+2, 5-30 rounds), Magic (8',
    'segments, 5 foot radius, 50% drain',
    'save 11 or better on d20, 5-30 5d6',
    'rounds), Petrification (5 segments,',
    '10 foot radius, 5-20 5d4 rounds),',
    'Possession (1 round, 10 foot',
    'radius, 10-60 rounds in 90% of',
    'scrolls, 10% have 10-60 turns but',
    'stationary), and Undead (4',
    'segments, 5 foot radius, 10 undead',
    'types cross-pinned against the',
    'R251 potUndeadTypeRowCount - the',
    'prose Cf. sanctions it - 35 hit',
    'dice/levels, 10-80 10d8 rounds).',
    'The eight scrolls are the engine',
    'III.B table rows 61-97 (rollScroll,',
    'the R222 scrollpins.h pins) -',
    'cross-checked band by band in the',
    'audit. The TREASURE (SCROLLS) and',
    'TREASURE (RINGS) running page',
    'headers are stripped by the ground',
    'truth - the RINGS header splits the',
    'Possession paragraph mid-sentence',
    '(upload ~10277), per the R249',
    'page-header lesson. New R252',
    'battery audit; census 171. Next:',
    'the rings explanations (upload',
    '~10282-10561, likely 3 parts),',
    'then the misc magic item',
    'explanations III.E (part1 ~10948-',
    '11067 continuing seamlessly into',
    'part2; global line = part1 line or',
    '~11065 + part2 line, the TREASURE',
    '(MISCELLANEOUS MAGIC) headers are',
    'running page headers mid-paragraph).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence,
# the R228 lesson; the marker MUST be contiguous in
# the header text - the R247 lesson)
marker = 'R252: the III.B scrolls explanation prose'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R252 FAIL: rules/scrollsprose.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R252 audit', audit_old, audit_new),
    (GAP, 'the R252 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text (the R233
    # lesson: append-style patches leave the old text
    # inside the new)
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R252 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 171:
        print('R252 FAIL: census is not 171')
        sys.exit(1)
    if t.count('R252 scrolls prose pins audit') != 1:
        print('R252 FAIL: the R252 audit line must appear once')
        sys.exit(1)
    if t.count('rules/scrollsprose.h') != 1:
        print('R252 FAIL: the scrollsprose include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R252 landed the III.B scrolls') != 1:
        print('R252 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int scp') != 88:
        print('R252 FAIL: the header shape is wrong')
        sys.exit(1)

print('R252 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R252 note: 4 patches; the III.B scrolls explanation prose -')
print('the scroll mechanics and the eight protection scrolls; census 171.')
print('commit: R252: the III.B scrolls explanation prose pins pinned - DMG pp.137-139, the scroll mechanics and the eight protection scrolls (census 171)')

