#!/usr/bin/env python3
# R254 splice: the III.C rings explanation prose pins,
# part 2 of 3.
#
# DMG pp.138-139, upload lines ~10393-10457 - the III.C
# RINGS explanation prose, part 2: Feather Falling
# through Shooting Stars (the ten rings of the engine
# III.C table rows 16-63). Feather Falling (automatic
# feather fall at 5 feet or more); Fire Resistance
# (immune to normal fires; very large/hot fires 10 hit
# points per round, 1 per segment; exceptionally hot
# fires save at +4, damage dice at -2 per die but never
# less than 1; the rule of thumb: very hot up to 24 hit
# points initial exposure, exceptional 25 or more);
# Free Action (web, hold, slow have no effect; normal
# underwater speed and full damage; no water
# breathing); Human Influence (charisma 18, suggestion
# and charm up to 21 levels, once per day, 3 segments,
# double-dagger); Invisibility (at will; 10% also
# inaudible); Mammal Control (intelligence 4 or less,
# 30 hit dice, control time 3 segments, double-dagger);
# Multiple Wishes (2-8, 2d4, double-dagger); Protection
# (the 7-row value table: 01-70 +1, 71-82 +2, 83 +2
# with 5 foot radius, 84-90 +3, 91 +3 with 5 foot
# radius, 92-97 +4 AC +2 saves, 98-00 +6 AC +1 saves;
# the radius covers saves only; NO double-dagger);
# Regeneration (2 forms; 1 hit point per turn; the
# vampiric form bestows one-half damage inflicted;
# 01-90 standard, 91-00 vampiric); Shooting Stars (2
# modes in relative darkness; dancing lights once per
# hour; light twice per night at 12 range; ball
# lightning once per night - 1 to 4 balls, 12 range, 4
# round duration, moved at 4 per round, 3 feet in
# diameter, the 4 charge tiers 4/3/2/1 balls (the
# upload drops the charge die bands); 3 shooting stars
# per week, 12 impact damage plus a 1 diameter sphere
# burst for 24, range 7, saves at -3 within 2 of the
# wearer, -1 within 2 to 4; indoors: faerie fire twice
# per day, spark shower once per day - 20 feet long to
# a 10 feet breadth, 2-8 damage with no metal, 4-16
# with; casting time 5 segments).
#
# DIVERGENCE FOUND BY THE GROUND TRUTH BEFORE ANY PIN:
# the R223 rings.h ringIsChargeLimited array flags
# Protection (row 11) and NOT Mammal Control (row 9),
# while the R223 comment names Mammal Control and the
# prose carries the double-dagger on Mammal Control but
# not Protection. The R223 audit kChg pins the wrong
# array too. This round pins the prose and documents the
# divergence; the fix (swap rows 9 and 11 in rings.h and
# in the R223 audit kChg + its per-index asserts) is
# the ranked candidate for the next round. The R254
# audit deliberately does NOT assert the divergent rows.
#
# Patches: 4 (new rules/ringsprose2.h, the regtest
# include, the audit block, the dmg-gap-report log
# entry). Census 172 -> 173.
#
# commit: R254: the III.C rings explanation prose part 2 pinned - DMG pp.138-139, Feather Falling through Shooting Stars (census 173)

import sys

WD   = 'rules/ringsprose2.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson); NO already-closed pre-check
# (the R235b lesson, re-caught at R237)
t = open(REG).read()
if t.count('audit: bad ') != 172 and t.count('audit: bad ') != 173:
    print('R254 FAIL: regtest census is neither 172 nor 173')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/ringsprose2.h',
    '// R254: the III.C rings explanation prose part 2',
    '// pins (DMG pp.138-139) - Feather Falling',
    '// through Shooting Stars, the second ten',
    '// rings of the EXPLANATIONS AND',
    '// DESCRIPTIONS section (upload lines',
    '// ~10393-10457):',
    '//   - Feather Falling: automatic feather',
    '//     fall at 5 feet or more.',
    '//   - Fire Resistance: immune to normal',
    '//     fires; very large/hot fires 10 hit',
    '//     points per round (1 per segment);',
    '//     exceptionally hot fires save at +4,',
    '//     damage dice at -2 per die but each',
    '//     die never less than 1; the rule of',
    '//     thumb: very hot up to 24 hit points',
    '//     initial exposure, exceptional heat',
    '//     25 or more.',
    '//   - Free Action: web, hold, slow have no',
    '//     effect; normal underwater speed and',
    '//     full damage; no water breathing.',
    '//   - Human Influence: charisma 18;',
    '//     suggestion and charm up to 21',
    '//     levels; once per day; 3 segments;',
    '//     double-dagger flagged.',
    '//   - Invisibility: at will, instantly;',
    '//     10% of these rings also have',
    '//     inaudibility.',
    '//   - Mammal Control: intelligence 4 or',
    '//     less; up to 30 hit dice; control',
    '//     time 3 segments; double-dagger',
    '//     flagged.',
    '//   - Multiple Wishes: 2-8 (2d4) wish',
    '//     spells; double-dagger flagged.',
    '//   - Protection: the 7-row value table',
    '//     01-70 +1 through 98-00 +6 on AC',
    '//     +1 saves; rows 83 and 91 carry the',
    '//     5 foot radius (saves only); NO',
    '//     double-dagger.',
    '//   - Regeneration: 2 forms; 1 hit point',
    '//     per turn; the vampiric form bestows',
    '//     one-half of damage inflicted; 01-90',
    '//     standard, 91-00 vampiric.',
    '//   - Shooting Stars: 2 modes in relative',
    '//     darkness; dancing lights once per',
    '//     hour; light twice per night at 12',
    '//     range; ball lightning once per night',
    '//     (1 to 4 balls, 12 range, 4 round',
    '//     duration, 4 per round move, 3 feet',
    '//     diameter, the 4 charge tiers 4/3/2/1',
    '//     balls); 3 stars per week, 12 impact',
    '//     plus a 1 diameter burst for 24;',
    '//     range 7; saves at -3 within 2 of',
    '//     the wearer, -1 within 2 to 4;',
    '//     indoors: faerie fire twice per day;',
    '//     spark shower once per day (20 feet',
    '//     to a 10 feet breadth, 2-8 damage',
    '//     with no metal, 4-16 with); casting',
    '//     time 5 segments.',
    '// The ten rings are the engine III.C table',
    '// rows 16-63 (dm/treasure.cpp kRings, the',
    '// R223 rings.h band pins) - cross-checked in',
    '// the audit, with the Human Influence and',
    '// Multiple Wishes double-daggers cross-pinned',
    '// against the R223 charge-limited rows. The',
    '// Mammal Control / Protection charge-limited',
    '// divergence (the R223 array flags the wrong',
    '// row) is documented in the gap report as',
    '// the ranked fix candidate. Pure data +',
    '// helpers, header-only (the grenade.h',
    '// pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int rgpFeatherFallMinFeet() {',
    '    // automatic activation if the',
    '    // individual falls 5 feet or more',
    '    return 5;',
    '}',
    '',
    'inline int rgpFireResistLargeFireDamagePerRound() {',
    '    // very large and hot fires cause',
    '    // this much per round',
    '    return 10;',
    '}',
    '',
    'inline int rgpFireResistLargeFirePerSegment() {',
    '    // the same damage expressed per',
    '    // segment',
    '    return 1;',
    '}',
    '',
    'inline int rgpFireResistHotSaveBonus() {',
    '    // exceptionally hot fires are',
    '    // saved against at +4',
    '    return 4;',
    '}',
    '',
    'inline int rgpFireResistHotDamagePerDieMod() {',
    '    // all damage dice calculated at',
    '    // -2 per die',
    '    return -2;',
    '}',
    '',
    'inline int rgpFireResistHotDieFloor() {',
    '    // each die is never less than 1',
    '    return 1;',
    '}',
    '',
    'inline int rgpFireResistVeryHotExposureMax() {',
    '    // rule of thumb: very hot fires',
    '    // are up to 24 hit points of',
    '    // maximum initial exposure',
    '    return 24;',
    '}',
    '',
    'inline int rgpFireResistExceptionalExposureMin() {',
    '    // fires of exceptional heat are',
    '    // 25 or more hit points',
    '    return 25;',
    '}',
    '',
    'inline int rgpHumanInfluenceCharisma() {',
    '    // raises the wearer charisma to',
    '    // 18 for encounter reactions',
    '    return 18;',
    '}',
    '',
    'inline int rgpHumanInfluenceCharmLevels() {',
    '    // charm up to 21 levels/hit',
    '    // dice of humans/humanoids',
    '    return 21;',
    '}',
    '',
    'inline int rgpHumanInfluenceUsesPerDay() {',
    '    // suggestion and charm are each',
    '    // applicable but once per day',
    '    return 1;',
    '}',
    '',
    'inline int rgpHumanInfluenceCastSegments() {',
    '    // suggestion or charm requires',
    '    // 3 segments of casting time',
    '    return 3;',
    '}',
    '',
    'inline int rgpHumanInfluenceDaggerFlag() {',
    '    // the prose entry carries the',
    '    // double-dagger; cross-pins the',
    '    // R223 charge-limited row 7',
    '    return 1;',
    '}',
    '',
    'inline int rgpInvisibilityInaudiblePercent() {',
    '    // 10% of these rings also have',
    '    // inaudibility',
    '    return 10;',
    '}',
    '',
    'inline int rgpMammalControlMaxIntelligence() {',
    '    // controls mammals with',
    '    // intelligence of 4 or less',
    '    return 4;',
    '}',
    '',
    'inline int rgpMammalControlHitDice() {',
    '    // up to 30 hit dice of mammals',
    '    return 30;',
    '}',
    '',
    'inline int rgpMammalControlTimeSegments() {',
    '    // control time is 3 segments',
    '    return 3;',
    '}',
    '',
    'inline int rgpMammalControlDaggerFlag() {',
    '    // the prose entry carries the',
    '    // double-dagger; the R223 array',
    '    // does NOT flag row 9 - the',
    '    // documented divergence, the',
    '    // ranked fix candidate',
    '    return 1;',
    '}',
    '',
    'inline int rgpMultipleWishesLo() {',
    '    // contains from 2 wish spells',
    '    return 2;',
    '}',
    '',
    'inline int rgpMultipleWishesHi() {',
    '    // up to 8 wish spells',
    '    return 8;',
    '}',
    '',
    'inline int rgpMultipleWishesDice() {',
    '    // 2 dice',
    '    return 2;',
    '}',
    '',
    'inline int rgpMultipleWishesFaces() {',
    '    // of 4 faces each',
    '    return 4;',
    '}',
    '',
    'inline int rgpMultipleWishesDaggerFlag() {',
    '    // the prose entry carries the',
    '    // double-dagger; cross-pins the',
    '    // R223 charge-limited row 10',
    '    return 1;',
    '}',
    '',
    'inline int rgpProtectionRowCount() {',
    '    // the value table has 7 rows',
    '    return 7;',
    '}',
    '',
    'inline int rgpProtectionRowLo(int i) {',
    '    // the row lower edges: 01-70,',
    '    // 71-82, 83, 84-90, 91, 92-97,',
    '    // 98-00; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        1, 71, 83, 84, 91, 92, 98,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rgpProtectionRowHi(int i) {',
    '    // the row upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        70, 82, 83, 90, 91, 97, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rgpProtectionRowAc(int i) {',
    '    // the armor class bonus per row:',
    '    // +1, +2, +2, +3, +3, +4, +6;',
    '    // i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        1, 2, 2, 3, 3, 4, 6,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rgpProtectionRowSave(int i) {',
    '    // the saving throw bonus per',
    '    // row: +1, +2, +2, +3, +3,',
    '    // +2, +1; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        1, 2, 2, 3, 3, 2, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rgpProtectionRowRadius(int i) {',
    '    // rows 83 and 91 carry the 5',
    '    // foot radius protection; i',
    '    // clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        0, 0, 1, 0, 1, 0, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rgpProtectionRadiusFeet() {',
    '    // the radius bonus extends to',
    '    // all creatures within its',
    '    // circle, but saves only',
    '    return 5;',
    '}',
    '',
    'inline int rgpProtectionDaggerFlag() {',
    '    // the prose entry carries NO',
    '    // double-dagger; the R223 array',
    '    // flags row 11 - the documented',
    '    // divergence, the ranked fix',
    '    // candidate',
    '    return 0;',
    '}',
    '',
    'inline int rgpRegenerationFormCount() {',
    '    // there are 2 forms of this',
    '    // ring',
    '    return 2;',
    '}',
    '',
    'inline int rgpRegenerationHpPerTurn() {',
    '    // the standard form restores 1',
    '    // hit point per turn',
    '    return 1;',
    '}',
    '',
    'inline int rgpRegenerationVampiricPercent() {',
    '    // the vampiric form bestows',
    '    // one-half of damage inflicted',
    '    return 50;',
    '}',
    '',
    'inline int rgpRegenerationStandardBandHi() {',
    '    // 01-90 = ring of regeneration',
    '    return 90;',
    '}',
    '',
    'inline int rgpRegenerationVampiricBandLo() {',
    '    // 91-00 = vampiric ring',
    '    return 91;',
    '}',
    '',
    'inline int rgpShootingStarsModeCount() {',
    '    // 2 modes of operation, both',
    '    // only in relative darkness',
    '    return 2;',
    '}',
    '',
    'inline int rgpShootingStarsDancingLightsPerHour() {',
    '    // dancing lights once per hour',
    '    return 1;',
    '}',
    '',
    'inline int rgpShootingStarsLightPerNight() {',
    '    // light twice per night',
    '    return 2;',
    '}',
    '',
    'inline int rgpShootingStarsLightRangeInches() {',
    '    // the light function range',
    '    return 12;',
    '}',
    '',
    'inline int rgpShootingStarsBallLightningPerNight() {',
    '    // ball lightning once per night',
    '    return 1;',
    '}',
    '',
    'inline int rgpBallLightningCountLo() {',
    '    // releases 1 to 4 balls of',
    '    // lightning',
    '    return 1;',
    '}',
    '',
    'inline int rgpBallLightningCountHi() {',
    '    // the upper ball count',
    '    return 4;',
    '}',
    '',
    'inline int rgpBallLightningRangeInches() {',
    '    // the spheres have a 12 range',
    '    return 12;',
    '}',
    '',
    'inline int rgpBallLightningDurationRounds() {',
    '    // a 4 round duration',
    '    return 4;',
    '}',
    '',
    'inline int rgpBallLightningMoveInches() {',
    '    // moved at 4 per round',
    '    return 4;',
    '}',
    '',
    'inline int rgpBallLightningDiameterFeet() {',
    '    // each sphere is about 3 feet',
    '    // in diameter',
    '    return 3;',
    '}',
    '',
    'inline int rgpBallLightningChargeTierCount() {',
    '    // the charge value list has 4',
    '    // tiers (the upload drops the',
    '    // charge die bands)',
    '    return 4;',
    '}',
    '',
    'inline int rgpBallLightningChargeBalls(int i) {',
    '    // the charge tiers: 4, 3, 2, 1',
    '    // lightning balls; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        4, 3, 2, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int rgpShootingStarsPerWeek() {',
    '    // 3 shooting stars per week',
    '    return 3;',
    '}',
    '',
    'inline int rgpShootingStarImpactDamage() {',
    '    // they impact for 12 hit',
    '    // points of damage',
    '    return 12;',
    '}',
    '',
    'inline int rgpShootingStarBurstDamage() {',
    '    // the burst is 24 hit points',
    '    return 24;',
    '}',
    '',
    'inline int rgpShootingStarBurstDiameterInches() {',
    '    // the burst is a 1 diameter',
    '    // sphere',
    '    return 1;',
    '}',
    '',
    'inline int rgpShootingStarRangeInches() {',
    '    // range is 7',
    '    return 7;',
    '}',
    '',
    'inline int rgpShootingStarSaveModNear() {',
    '    // saving throws at -3 within',
    '    // 2 of the ring wearer',
    '    return -3;',
    '}',
    '',
    'inline int rgpShootingStarNearLimitInches() {',
    '    // the near zone limit',
    '    return 2;',
    '}',
    '',
    'inline int rgpShootingStarSaveModMid() {',
    '    // saving throws at -1 within 2',
    '    // to 4',
    '    return -1;',
    '}',
    '',
    'inline int rgpShootingStarMidLimitInches() {',
    '    // the mid zone limit, normal',
    '    // beyond',
    '    return 4;',
    '}',
    '',
    'inline int rgpShootingStarsFaerieFirePerDay() {',
    '    // indoors: faerie fire twice',
    '    // per day',
    '    return 2;',
    '}',
    '',
    'inline int rgpShootingStarsSparkShowerPerDay() {',
    '    // indoors: spark shower once',
    '    // per day',
    '    return 1;',
    '}',
    '',
    'inline int rgpSparkShowerLengthFeet() {',
    '    // fans out from the ring for',
    '    // 20 feet',
    '    return 20;',
    '}',
    '',
    'inline int rgpSparkShowerBreadthFeet() {',
    '    // to a breadth of 10 feet',
    '    return 10;',
    '}',
    '',
    'inline int rgpSparkShowerDamageLo() {',
    '    // 2-8 damage with no metallic',
    '    // armor or weapon',
    '    return 2;',
    '}',
    '',
    'inline int rgpSparkShowerDamageHi() {',
    '    // the upper no-metal damage',
    '    return 8;',
    '}',
    '',
    'inline int rgpSparkShowerMetalDamageLo() {',
    '    // 4-16 damage with metal',
    '    return 4;',
    '}',
    '',
    'inline int rgpSparkShowerMetalDamageHi() {',
    '    // the upper with-metal damage',
    '    return 16;',
    '}',
    '',
    'inline int rgpShootingStarsCastSegments() {',
    '    // casting time is 5 segments',
    '    return 5;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the regtest include ----
inc_old = [
    '#include "rules/ringsprose.h"  // R253: pp.137-138 the III.C rings explanation prose part 1 pins',
]
inc_new = [
    '#include "rules/ringsprose.h"  // R253: pp.137-138 the III.C rings explanation prose part 1 pins',
    '#include "rules/ringsprose2.h"  // R254: pp.138-139 the III.C rings explanation prose part 2 pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R254: the III.C rings explanation prose part 2 pins audit ----',
    '    // DMG pp.138-139: Feather Falling through Shooting',
    '    // Stars (part 2 of 3).',
    '    {',
    '        int bad = 0;',
    '        // the ten rings are the engine III.C table',
    '        // rows 16-63 (the R223 rings.h pins)',
    '        if (rules::ringRowCount() != 24 ||',
    '            rules::ringRowLo(4) != 16 || rules::ringRowHi(4) != 21 ||',
    '            rules::ringRowLo(13) != 62 || rules::ringRowHi(13) != 63) ++bad;',
    '        static const int kCLo[10] = {',
    '            16, 22, 28, 31, 34, 41, 44, 45, 61, 62,',
    '        };',
    '        static const int kCHi[10] = {',
    '            21, 27, 30, 33, 40, 43, 44, 60, 61, 63,',
    '        };',
    '        for (int i = 0; i < 10; ++i)',
    '            if (rules::ringRowLo(4 + i) != kCLo[i] ||',
    '                rules::ringRowHi(4 + i) != kCHi[i]) ++bad;',
    '        // the double-dagger cross-pins. NOTE: the R223',
    '        // array flags Protection (row 11) instead of',
    '        // Mammal Control (row 9) - the documented',
    '        // divergence, the ranked fix candidate; this',
    '        // audit asserts only the consistent rows',
    '        if (rules::ringIsChargeLimited(7) != 1 ||',
    '            rules::ringIsChargeLimited(10) != 1 ||',
    '            rules::ringChargeLimitedCount() != 7) ++bad;',
    '        // the protection 7-row value table',
    '        static const int kPlo[7] = {',
    '            1, 71, 83, 84, 91, 92, 98,',
    '        };',
    '        static const int kPhi[7] = {',
    '            70, 82, 83, 90, 91, 97, 100,',
    '        };',
    '        static const int kPac[7] = {',
    '            1, 2, 2, 3, 3, 4, 6,',
    '        };',
    '        static const int kPsv[7] = {',
    '            1, 2, 2, 3, 3, 2, 1,',
    '        };',
    '        static const int kPrd[7] = {',
    '            0, 0, 1, 0, 1, 0, 0,',
    '        };',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::rgpProtectionRowLo(i) != kPlo[i] ||',
    '                rules::rgpProtectionRowHi(i) != kPhi[i] ||',
    '                rules::rgpProtectionRowAc(i) != kPac[i] ||',
    '                rules::rgpProtectionRowSave(i) != kPsv[i] ||',
    '                rules::rgpProtectionRowRadius(i) != kPrd[i]) ++bad;',
    '        // the ball lightning charge tiers',
    '        static const int kBall[4] = {',
    '            4, 3, 2, 1,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::rgpBallLightningChargeBalls(i) != kBall[i]) ++bad;',
    '        // feather falling and fire resistance',
    '        if (rules::rgpFeatherFallMinFeet() != 5 ||',
    '            rules::rgpFireResistLargeFireDamagePerRound() != 10 ||',
    '            rules::rgpFireResistLargeFirePerSegment() != 1 ||',
    '            rules::rgpFireResistHotSaveBonus() != 4 ||',
    '            rules::rgpFireResistHotDamagePerDieMod() != -2 ||',
    '            rules::rgpFireResistHotDieFloor() != 1 ||',
    '            rules::rgpFireResistVeryHotExposureMax() != 24 ||',
    '            rules::rgpFireResistExceptionalExposureMin() != 25) ++bad;',
    '        // human influence and invisibility',
    '        if (rules::rgpHumanInfluenceCharisma() != 18 ||',
    '            rules::rgpHumanInfluenceCharmLevels() != 21 ||',
    '            rules::rgpHumanInfluenceUsesPerDay() != 1 ||',
    '            rules::rgpHumanInfluenceCastSegments() != 3 ||',
    '            rules::rgpHumanInfluenceDaggerFlag() != 1 ||',
    '            rules::rgpInvisibilityInaudiblePercent() != 10) ++bad;',
    '        // mammal control and multiple wishes',
    '        if (rules::rgpMammalControlMaxIntelligence() != 4 ||',
    '            rules::rgpMammalControlHitDice() != 30 ||',
    '            rules::rgpMammalControlTimeSegments() != 3 ||',
    '            rules::rgpMammalControlDaggerFlag() != 1 ||',
    '            rules::rgpMultipleWishesLo() != 2 ||',
    '            rules::rgpMultipleWishesHi() != 8 ||',
    '            rules::rgpMultipleWishesDice() != 2 ||',
    '            rules::rgpMultipleWishesFaces() != 4 ||',
    '            rules::rgpMultipleWishesDaggerFlag() != 1) ++bad;',
    '        // protection scalars and regeneration',
    '        if (rules::rgpProtectionRowCount() != 7 ||',
    '            rules::rgpProtectionRadiusFeet() != 5 ||',
    '            rules::rgpProtectionDaggerFlag() != 0 ||',
    '            rules::rgpRegenerationFormCount() != 2 ||',
    '            rules::rgpRegenerationHpPerTurn() != 1 ||',
    '            rules::rgpRegenerationVampiricPercent() != 50 ||',
    '            rules::rgpRegenerationStandardBandHi() != 90 ||',
    '            rules::rgpRegenerationVampiricBandLo() != 91) ++bad;',
    '        // shooting stars: the night functions',
    '        if (rules::rgpShootingStarsModeCount() != 2 ||',
    '            rules::rgpShootingStarsDancingLightsPerHour() != 1 ||',
    '            rules::rgpShootingStarsLightPerNight() != 2 ||',
    '            rules::rgpShootingStarsLightRangeInches() != 12 ||',
    '            rules::rgpShootingStarsBallLightningPerNight() != 1 ||',
    '            rules::rgpBallLightningCountLo() != 1 ||',
    '            rules::rgpBallLightningCountHi() != 4 ||',
    '            rules::rgpBallLightningRangeInches() != 12 ||',
    '            rules::rgpBallLightningDurationRounds() != 4 ||',
    '            rules::rgpBallLightningMoveInches() != 4 ||',
    '            rules::rgpBallLightningDiameterFeet() != 3 ||',
    '            rules::rgpBallLightningChargeTierCount() != 4) ++bad;',
    '        // shooting stars: the missiles and indoors',
    '        if (rules::rgpShootingStarsPerWeek() != 3 ||',
    '            rules::rgpShootingStarImpactDamage() != 12 ||',
    '            rules::rgpShootingStarBurstDamage() != 24 ||',
    '            rules::rgpShootingStarBurstDiameterInches() != 1 ||',
    '            rules::rgpShootingStarRangeInches() != 7 ||',
    '            rules::rgpShootingStarSaveModNear() != -3 ||',
    '            rules::rgpShootingStarNearLimitInches() != 2 ||',
    '            rules::rgpShootingStarSaveModMid() != -1 ||',
    '            rules::rgpShootingStarMidLimitInches() != 4 ||',
    '            rules::rgpShootingStarsFaerieFirePerDay() != 2 ||',
    '            rules::rgpShootingStarsSparkShowerPerDay() != 1 ||',
    '            rules::rgpSparkShowerLengthFeet() != 20 ||',
    '            rules::rgpSparkShowerBreadthFeet() != 10 ||',
    '            rules::rgpSparkShowerDamageLo() != 2 ||',
    '            rules::rgpSparkShowerDamageHi() != 8 ||',
    '            rules::rgpSparkShowerMetalDamageLo() != 4 ||',
    '            rules::rgpSparkShowerMetalDamageHi() != 16 ||',
    '            rules::rgpShootingStarsCastSegments() != 5) ++bad;',
    '        printf("R254 rings prose part 2 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg-gap-report log entry ----
gap_old = [
    'plane anchors mix hyphen and em',
    'dashes. New R253 battery audit;',
    'census 172. Next: part 2 (upload',
    '~10393-10457, Feather Falling',
    'through Shooting Stars), then',
    'part 3 (~10458-10561, Spell',
    'Storing through X-Ray Vision),',
    'then the misc magic item',
    'explanations III.E (part1',
    '~10948-11067 continuing',
    'seamlessly into part2; global',
    'line = part1 line or ~11065 +',
    'part2 line, the TREASURE',
    '(MISCELLANEOUS MAGIC) headers',
    'are running page headers',
    'mid-paragraph).',
]
gap_new = [
    'plane anchors mix hyphen and em',
    'dashes. New R253 battery audit;',
    'census 172. Next: part 2 (upload',
    '~10393-10457, Feather Falling',
    'through Shooting Stars), then',
    'part 3 (~10458-10561, Spell',
    'Storing through X-Ray Vision),',
    'then the misc magic item',
    'explanations III.E (part1',
    '~10948-11067 continuing',
    'seamlessly into part2; global',
    'line = part1 line or ~11065 +',
    'part2 line, the TREASURE',
    '(MISCELLANEOUS MAGIC) headers',
    'are running page headers',
    'mid-paragraph).',
    '',
    'R254 landed the III.C rings',
    'explanation prose part 2 of 3',
    '(DMG pp.138-139, upload lines',
    '~10393-10457) - Feather Falling',
    'through Shooting Stars.',
    'rules/ringsprose2.h (the rgp',
    'prefix, part 2 - 67 accessors,',
    'of which 6 are array walkers):',
    'Feather Falling (5 feet),',
    'Fire Resistance (immune normal',
    'fires; very hot 10 per round /',
    '1 per segment; exceptionally',
    'hot saves +4, -2 per die floor',
    '1; the 24 hp / 25+ rule of',
    'thumb), Free Action (web hold',
    'slow, underwater, no water',
    'breathing), Human Influence',
    '(charisma 18, 21 levels, once',
    'per day, 3 segments,',
    'double-dagger), Invisibility',
    '(10% also inaudible), Mammal',
    'Control (intelligence 4 or',
    'less, 30 hit dice, 3 segments,',
    'double-dagger), Multiple',
    'Wishes (2-8 2d4,',
    'double-dagger), Protection',
    '(the 7-row value table 01-70',
    '+1 through 98-00 +6 AC +1',
    'saves, rows 83 and 91 the 5',
    'foot radius saves-only, NO',
    'double-dagger), Regeneration',
    '(2 forms, 1 hp per turn,',
    'vampiric one-half, 01-90 /',
    '91-00), Shooting Stars (2',
    'modes; dancing lights once per',
    'hour, light twice per night 12',
    'range, ball lightning once per',
    'night - 1 to 4 balls, 12',
    'range, 4 rounds, 4 per round',
    'move, 3 foot diameter, the 4',
    'charge tiers 4/3/2/1 balls; 3',
    'stars per week, 12 impact +',
    '24 burst in a 1 diameter',
    'sphere, 7 range, saves -3',
    'within 2 / -1 within 2 to 4;',
    'indoors faerie fire twice per',
    'day, spark shower once per day',
    '- 20 feet to 10 feet breadth,',
    '2-8 no metal / 4-16 metal;',
    'casting 5 segments). ENGINE',
    'CROSS-CHECK: the ten kRings',
    'rows 16-63 vs the R223 rings.h',
    'band edges; dagger cross-pins',
    'Human Influence and Multiple',
    'Wishes. DIVERGENCE FOUND BY',
    'THE GROUND TRUTH BEFORE ANY',
    'PIN (the ranked fix candidate):',
    'the R223 rings.h',
    'ringIsChargeLimited array flags',
    'Protection (row 11) and NOT',
    'Mammal Control (row 9), while',
    'the R223 comment names Mammal',
    'Control and the prose carries',
    'the double-dagger on Mammal',
    'Control but not Protection -',
    'the R223 audit kChg pins the',
    'wrong array too; the fix round',
    'must swap rows 9 and 11 in',
    'rings.h and in the R223 audit',
    'kChg + its per-index asserts.',
    'The R254 audit deliberately',
    'does NOT assert the divergent',
    'rows. The TREASURE (RINGS)',
    'header at ~10432 splits the',
    'ball lightning paragraph',
    'mid-sentence (stripped, the',
    'R249 lesson); the upload drops',
    'the ball lightning charge die',
    'bands (only the 4/3/2/1 ball',
    'counts survive). New R254',
    'battery audit; census 173.',
    'Next: R255 the',
    'ringIsChargeLimited fix round',
    '(rings.h + the R223 audit',
    'amendment), then part 3',
    '(~10458-10561, Spell Storing',
    'through X-Ray Vision), then',
    'III.E (part1 ~10948-11067',
    'continuing seamlessly into',
    'part2; global line = part1',
    'line or ~11065 + part2 line,',
    'the TREASURE (MISCELLANEOUS',
    'MAGIC) headers are running',
    'page headers mid-paragraph).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence,
# the R228 lesson; the marker MUST be contiguous in
# the header text - the R247 lesson, re-caught at
# R252)
marker = 'R254: the III.C rings explanation prose part 2'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R254 FAIL: rules/ringsprose2.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R254 audit', audit_old, audit_new),
    (GAP, 'the R254 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text (the R233
    # lesson: append-style patches leave the old text
    # inside the new)
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R254 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 173:
        print('R254 FAIL: census is not 173')
        sys.exit(1)
    if t.count('R254 rings prose part 2 pins audit') != 1:
        print('R254 FAIL: the R254 audit line must appear once')
        sys.exit(1)
    if t.count('rules/ringsprose2.h') != 1:
        print('R254 FAIL: the ringsprose2 include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R254 landed the III.C rings') != 1:
        print('R254 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int rgp') != 67:
        print('R254 FAIL: the header shape is wrong')
        sys.exit(1)

print('R254 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R254 note: 4 patches; the III.C rings explanation prose part 2 -')
print('Feather Falling through Shooting Stars; census 173.')
print('note: the R223 charge-limited divergence (Mammal Control vs')
print('Protection) is documented in the gap report as the fix candidate.')
print('commit: R254: the III.C rings explanation prose part 2 pinned - DMG pp.138-139, Feather Falling through Shooting Stars (census 173)')

