#!/usr/bin/env python3
# R257 splice: the III.E misc magic explanation prose
# pins, part 1 - the FIRST TWO-PART-FILE round.
#
# The III.E explanation prose spans the dmg-part1.md /
# dmg-part2.md seam. Part1 ends mid-sentence (Bag of
# Devouring: it has a 5%), part2 line 3 completes it.
# The seam is pinned exactly: part1 has 11067 lines,
# last content line 11065; part2 line 1 is the page
# header (stripped), line 3 continues the sentence;
# global line = part1 line or 11065 + part2 line.
#
# Slice: part1 10949-11065 + part2 lines 1-3 - the
# section intro plus Alchemy Jug through Bag of
# Devouring. New header rules/miscprose1.h (the mmp
# prefix, 65 accessors: 60 scalars + 5 array walkers),
# the regtest include, the audit block, the
# dmg-gap-report log.
#
# commit: R257: the III.E misc magic explanation prose part 1 pinned - intro + Alchemy Jug through Bag of Devouring across the part1/part2 seam (census 175)

import sys

WD   = 'rules/miscprose1.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson)
t = open(REG).read()
if t.count('audit: bad ') != 174 and t.count('audit: bad ') != 175:
    print('R257 FAIL: regtest census is neither 174 nor 175')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose1.h',
    '// R257: the III.E misc magic explanation prose part 1',
    '// pins - the FIRST TWO-PART-FILE round. The III.E',
    '// explanation prose spans the upload seam: part1',
    '// ends mid-sentence (Bag of Devouring: it has a',
    '// 5%), part2 line 3 completes it. The seam is',
    '// pinned exactly: part1 has 11067 lines, last',
    '// content line 11065; global line = part1 line or',
    '// 11065 + part2 line. Slice: part1 10949-11065',
    '// plus the stitched completion - the section intro',
    '// plus Alchemy Jug through Bag of Devouring:',
    '//   - Intro: a catch-all category, not more than',
    '//     2 or 3 duplicates; alphabetical; class',
    '//     letters; books appear normal - a second',
    '//     wish for exact contents.',
    '//   - Alchemy Jug: 11 liquids (16 gallons salt',
    '//     water down to 4 drams cyanide); 1 kind and',
    '//     7 pourings per day; 2 gallons per round; 8',
    '//     rounds for one salt water pouring.',
    '//   - Amulet of Inescapable Location: DOUBLES',
    '//     likelihood and range of detection.',
    '//   - Amulet of Life Protection: psyche safe',
    '//     7 full days; psionic blast and crush immune.',
    '//   - Amulet of the Planes: d6 (1-3 no add, 4-6',
    '//     add 12) on d12 = 1-24; the 17-row plane',
    '//     table; alternates 22/23/24.',
    '//   - Amulet of Proof: no aura discernible.',
    '//   - Apparatus of Kwalish: 10 levers; 3 forward,',
    '//     6 backward; pincers 4 feet, 2-12 damage,',
    '//     25% hit; 900 feet; 2 occupants; 2-5 hours',
    '//     air; AC 0; 100 leak, 200 stave.',
    '//   - Arrow of Direction: once per day, 7 times',
    '//     in 7 turns, 5 request kinds.',
    '//   - Bag of Beans: 5-20 explosion in 10 feet;',
    '//     3-12 optimum, 1-2 beneficial; the 7-row',
    '//     bean table (5-20 berries of 100/500 gems;',
    '//     50 feet 5 turn smoke, blind 1-6; 20 feet',
    '//     1 turn gas).',
    '//   - Bag of Devouring: 90% ignore, 60% close;',
    '//     base 75% less 5% per +1 (18 str = 65%, 5',
    '//     str = 80%); 30 cubic feet; acts as a bag',
    '//     of holding; 5% cumulative per turn swallow',
    '//     - THE SEAM FACT; consumed in 7 segments.',
    '// The nine items are the engine kMisc1 rows 0-6,',
    '// 8 and 10 (the R225 m1 band pins) - cross-checked',
    '// in the audit. Pure data + helpers, header-only',
    '// (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpIntroMaxDuplicates() {',
    '    // improbable to have more than 2 or 3',
    '    return 3;',
    '}',
    '',
    'inline int mmpIntroBooksExactWishCount() {',
    '    // a second wish determines exact contents',
    '    return 2;',
    '}',
    '',
    'inline int mmpAlchemyJugRowCount() {',
    '    // 11 pourable liquids',
    '    return 11;',
    '}',
    '',
    'inline int mmpAlchemyJugKindsPerDay() {',
    '    // only 1 kind of liquid on any given day',
    '    return 1;',
    '}',
    '',
    'inline int mmpAlchemyJugPouringsPerDay() {',
    '    // 7 pourings maximum',
    '    return 7;',
    '}',
    '',
    'inline int mmpAlchemyJugGallonsPerRound() {',
    '    // pours forth 2 gallons per round',
    '    return 2;',
    '}',
    '',
    'inline int mmpAlchemyJugRoundsPerLargePouring() {',
    '    // 8 rounds for 1 pouring of salt water',
    '    return 8;',
    '}',
    '',
    'inline int mmpAlchemyJugRowQty(int i) {',
    '    // salt water 16 gallons, fresh 8, beer 4,',
    '    // vinegar 2, wine 1, ammonia 1 quart, oil',
    '    // 1 pint, aqua regia 2 gills, alcohol 1',
    '    // gill, chlorine 8 drams, cyanide 4 drams',
    '    static const int t[11] = {',
    '        16, 8, 4, 2, 1, 1, 1, 2, 1, 8, 4,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpAlchemyJugRowUnit(int i) {',
    '    // 0 gallons, 1 quart, 2 pint, 3 gill,',
    '    // 4 drams',
    '    static const int t[11] = {',
    '        0, 0, 0, 0, 0, 1, 2, 3, 3, 4, 4,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpAmuletLocationMultiplier() {',
    '    // DOUBLES the likelihood and range (a cursed',
    '    // lure disguised as a protection amulet)',
    '    return 2;',
    '}',
    '',
    'inline int mmpAmuletLifeProtectionDays() {',
    '    // the psyche is protected for 7 full days',
    '    return 7;',
    '}',
    '',
    'inline int mmpAmuletPlanesRowCount() {',
    '    // the plane table has 17 rows',
    '    return 17;',
    '}',
    '',
    'inline int mmpAmuletPlanesLowDieFaces() {',
    '    // roll d6: 1-3 do not add 12',
    '    return 6;',
    '}',
    '',
    'inline int mmpAmuletPlanesHighDieFaces() {',
    '    // add 12 to d12 for 1-24 random results',
    '    return 12;',
    '}',
    '',
    'inline int mmpAmuletPlanesAddOnHigh() {',
    '    // the added 12 of the 4-6 results',
    '    return 12;',
    '}',
    '',
    'inline int mmpAmuletPlanesResultMax() {',
    '    // 1-24 random results',
    '    return 24;',
    '}',
    '',
    'inline int mmpAmuletPlanesAltRowCount() {',
    '    // the alternate results: 3 rows',
    '    return 3;',
    '}',
    '',
    'inline int mmpAmuletPlanesRowLo(int i) {',
    '    // 1-2 Seven Heavens through 21-24 Prime',
    '    // Material Plane',
    '    static const int t[17] = {',
    '        1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14,',
    '        15, 16, 18, 19, 20, 21,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpAmuletPlanesRowHi(int i) {',
    '    static const int t[17] = {',
    '        2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14,',
    '        15, 17, 18, 19, 20, 24,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpAmuletPlanesAltLo(int i) {',
    '    // alternates: 22 Ethereal, 23 Astral,',
    '    // 24 alternate Earth',
    '    static const int t[3] = {',
    '        22, 23, 24,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpAmuletProofNoAuraFlag() {',
    '    // no aura is discernible on the wearer',
    '    return 1;',
    '}',
    '',
    'inline int mmpKwalishLeverCount() {',
    '    // 10 levers inside',
    '    return 10;',
    '}',
    '',
    'inline int mmpKwalishForwardInches() {',
    '    // moves forward at 3 inches',
    '    return 3;',
    '}',
    '',
    'inline int mmpKwalishBackwardInches() {',
    '    // backwards at 6 inches',
    '    return 6;',
    '}',
    '',
    'inline int mmpKwalishPincerReachFeet() {',
    '    // pincers extend forward 4 feet',
    '    return 4;',
    '}',
    '',
    'inline int mmpKwalishPincerDamageLo() {',
    '    // snap for 2-12 hit points each',
    '    return 2;',
    '}',
    '',
    'inline int mmpKwalishPincerDamageHi() {',
    '    return 12;',
    '}',
    '',
    'inline int mmpKwalishPincerHitPct() {',
    '    // 25% chance, no armor reduction',
    '    return 25;',
    '}',
    '',
    'inline int mmpKwalishMaxDepthFeet() {',
    '    // operates in waters up to 900 feet',
    '    return 900;',
    '}',
    '',
    'inline int mmpKwalishOccupants() {',
    '    // holds 2 human-sized persons',
    '    return 2;',
    '}',
    '',
    'inline int mmpKwalishAirHoursLo() {',
    '    // air for 2-5 hours at maximum capacity',
    '    return 2;',
    '}',
    '',
    'inline int mmpKwalishAirHoursHi() {',
    '    return 5;',
    '}',
    '',
    'inline int mmpKwalishArmorClass() {',
    '    // the apparatus is AC 0',
    '    return 0;',
    '}',
    '',
    'inline int mmpKwalishLeakHp() {',
    '    // 100 hit points to cause a leak',
    '    return 100;',
    '}',
    '',
    'inline int mmpKwalishStaveHp() {',
    '    // 200 to stave in a side',
    '    return 200;',
    '}',
    '',
    'inline int mmpArrowDirectionUsesPerDay() {',
    '    // tossed into the air once per day',
    '    return 1;',
    '}',
    '',
    'inline int mmpArrowDirectionRepetitions() {',
    '    // the process can be repeated 7 times',
    '    return 7;',
    '}',
    '',
    'inline int mmpArrowDirectionTurns() {',
    '    // during the next 7 turns',
    '    return 7;',
    '}',
    '',
    'inline int mmpArrowDirectionRequestKinds() {',
    '    // stairway, sloping passage, dungeon exit',
    '    // or entrance, cave, cavern',
    '    return 5;',
    '}',
    '',
    'inline int mmpBeanExplodeDamageLo() {',
    '    // dumped beans explode for 5-20 hit points',
    '    return 5;',
    '}',
    '',
    'inline int mmpBeanExplodeDamageHi() {',
    '    return 20;',
    '}',
    '',
    'inline int mmpBeanExplodeRadiusFeet() {',
    '    // all creatures within 10 feet save',
    '    return 10;',
    '}',
    '',
    'inline int mmpBeanOptimumLo() {',
    '    // 3-12 beans are optimum',
    '    return 3;',
    '}',
    '',
    'inline int mmpBeanOptimumHi() {',
    '    return 12;',
    '}',
    '',
    'inline int mmpBeanBeneficialMax() {',
    '    // only 1 or 2 will be beneficial',
    '    return 2;',
    '}',
    '',
    'inline int mmpBeanEffectRowCount() {',
    '    // the example bean table has 7 rows',
    '    return 7;',
    '}',
    '',
    'inline int mmpBeanBerryCountLo() {',
    '    // the raspberry bush: 5-20 berries',
    '    return 5;',
    '}',
    '',
    'inline int mmpBeanBerryCountHi() {',
    '    return 20;',
    '}',
    '',
    'inline int mmpBeanBerryGemLo() {',
    '    // berries are gems of 100 or 500 g.p.',
    '    return 100;',
    '}',
    '',
    'inline int mmpBeanBerryGemHi() {',
    '    return 500;',
    '}',
    '',
    'inline int mmpBeanSmokeRadiusFeet() {',
    '    // smoke covers 50 feet radius',
    '    return 50;',
    '}',
    '',
    'inline int mmpBeanSmokeTurns() {',
    '    // for 5 turns',
    '    return 5;',
    '}',
    '',
    'inline int mmpBeanBlindRoundsLo() {',
    '    // blinded for 1-6 rounds even outside',
    '    return 1;',
    '}',
    '',
    'inline int mmpBeanBlindRoundsHi() {',
    '    return 6;',
    '}',
    '',
    'inline int mmpBeanGasRadiusFeet() {',
    '    // poison gas cloud of 20 feet radius',
    '    return 20;',
    '}',
    '',
    'inline int mmpBeanGasTurns() {',
    '    // persists for 1 turn',
    '    return 1;',
    '}',
    '',
    'inline int mmpDevouringIgnorePct() {',
    '    // 90% likely to ignore initial intrusions',
    '    return 90;',
    '}',
    '',
    'inline int mmpDevouringClosePct() {',
    '    // 60% likely to close on living human flesh',
    '    return 60;',
    '}',
    '',
    'inline int mmpDevouringBaseDrawPct() {',
    '    // base 75% chance to draw the victim in',
    '    return 75;',
    '}',
    '',
    'inline int mmpDevouringDrawModPerPlus() {',
    '    // each +1 damage bonus is -5% on the base',
    '    return 5;',
    '}',
    '',
    'inline int mmpDevouringExampleStr18Pct() {',
    '    // 18 strength (+2 damage): only 65%',
    '    return 65;',
    '}',
    '',
    'inline int mmpDevouringExampleStr5Pct() {',
    '    // 5 strength (-1 damage): 80%',
    '    return 80;',
    '}',
    '',
    'inline int mmpDevouringCapacityCubicFeet() {',
    '    // holds up to 30 cubic feet of matter',
    '    return 30;',
    '}',
    '',
    'inline int mmpDevouringSwallowPctPerTurn() {',
    '    // 5% cumulative chance per turn - THE SEAM',
    '    // FACT, completed from part2 line 3',
    '    return 5;',
    '}',
    '',
    'inline int mmpDevouringConsumeSegments() {',
    '    // creatures drawn within are consumed in',
    '    // 7 segments',
    '    return 7;',
    '}',
    '',
    '}  // namespace rules',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the include patch ----
inc_old = [
    '#include "rules/ringsprose3.h"  // R256: pp.139-140 the III.C rings explanation prose part 3 pins',
]
inc_new = [
    '#include "rules/ringsprose3.h"  // R256: pp.139-140 the III.C rings explanation prose part 3 pins',
    '#include "rules/miscprose1.h"  // R257: the III.E misc magic explanation prose part 1 pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R257: the III.E misc magic explanation prose part 1 pins audit ----',
    '    // The first two-part-file round: part1 10949-',
    '    // 11065 stitched into part2 line 3 (Bag of',
    '    // Devouring, the seam fact pinned exactly).',
    '    {',
    '        int bad = 0;',
    '        // the nine items are the engine kMisc1 rows',
    '        // 0-6, 8 and 9 (the R225 m1 band pins);',
    '        // row 7 is the Artifact or Relic row',
    '        if (rules::m1RowCount() != 33) ++bad;',
    '        static const int kM1Lo[7] = {',
    '            1, 3, 5, 6, 8, 12, 14,',
    '        };',
    '        static const int kM1Hi[7] = {',
    '            2, 4, 5, 7, 11, 13, 16,',
    '        };',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::m1RowLo(i) != kM1Lo[i] ||',
    '                rules::m1RowHi(i) != kM1Hi[i]) ++bad;',
    '        if (rules::m1RowLo(8) != 18 ||',
    '            rules::m1RowHi(8) != 20 ||',
    '            rules::m1RowLo(9) != 21 ||',
    '            rules::m1RowHi(9) != 21) ++bad;',
    '        // the intro',
    '        if (rules::mmpIntroMaxDuplicates() != 3 ||',
    '            rules::mmpIntroBooksExactWishCount() != 2) ++bad;',
    '        // the alchemy jug: 11 liquids',
    '        if (rules::mmpAlchemyJugRowCount() != 11 ||',
    '            rules::mmpAlchemyJugKindsPerDay() != 1 ||',
    '            rules::mmpAlchemyJugPouringsPerDay() != 7 ||',
    '            rules::mmpAlchemyJugGallonsPerRound() != 2 ||',
    '            rules::mmpAlchemyJugRoundsPerLargePouring() != 8) ++bad;',
    '        static const int kJugQty[11] = {',
    '            16, 8, 4, 2, 1, 1, 1, 2, 1, 8, 4,',
    '        };',
    '        static const int kJugUnit[11] = {',
    '            0, 0, 0, 0, 0, 1, 2, 3, 3, 4, 4,',
    '        };',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::mmpAlchemyJugRowQty(i) != kJugQty[i] ||',
    '                rules::mmpAlchemyJugRowUnit(i) != kJugUnit[i]) ++bad;',
    '        // the amulets',
    '        if (rules::mmpAmuletLocationMultiplier() != 2 ||',
    '            rules::mmpAmuletLifeProtectionDays() != 7 ||',
    '            rules::mmpAmuletProofNoAuraFlag() != 1) ++bad;',
    '        // the amulet of the planes: d6 on d12',
    '        if (rules::mmpAmuletPlanesRowCount() != 17 ||',
    '            rules::mmpAmuletPlanesLowDieFaces() != 6 ||',
    '            rules::mmpAmuletPlanesHighDieFaces() != 12 ||',
    '            rules::mmpAmuletPlanesAddOnHigh() != 12 ||',
    '            rules::mmpAmuletPlanesResultMax() != 24 ||',
    '            rules::mmpAmuletPlanesAltRowCount() != 3) ++bad;',
    '        static const int kPlLo[17] = {',
    '            1, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14,',
    '            15, 16, 18, 19, 20, 21,',
    '        };',
    '        static const int kPlHi[17] = {',
    '            2, 3, 4, 5, 7, 8, 9, 10, 12, 13, 14,',
    '            15, 17, 18, 19, 20, 24,',
    '        };',
    '        for (int i = 0; i < 17; ++i)',
    '            if (rules::mmpAmuletPlanesRowLo(i) != kPlLo[i] ||',
    '                rules::mmpAmuletPlanesRowHi(i) != kPlHi[i]) ++bad;',
    '        static const int kPlAlt[3] = {',
    '            22, 23, 24,',
    '        };',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpAmuletPlanesAltLo(i) != kPlAlt[i]) ++bad;',
    '        // the apparatus of kwalish',
    '        if (rules::mmpKwalishLeverCount() != 10 ||',
    '            rules::mmpKwalishForwardInches() != 3 ||',
    '            rules::mmpKwalishBackwardInches() != 6 ||',
    '            rules::mmpKwalishPincerReachFeet() != 4 ||',
    '            rules::mmpKwalishPincerDamageLo() != 2 ||',
    '            rules::mmpKwalishPincerDamageHi() != 12 ||',
    '            rules::mmpKwalishPincerHitPct() != 25 ||',
    '            rules::mmpKwalishMaxDepthFeet() != 900 ||',
    '            rules::mmpKwalishOccupants() != 2 ||',
    '            rules::mmpKwalishAirHoursLo() != 2 ||',
    '            rules::mmpKwalishAirHoursHi() != 5 ||',
    '            rules::mmpKwalishArmorClass() != 0 ||',
    '            rules::mmpKwalishLeakHp() != 100 ||',
    '            rules::mmpKwalishStaveHp() != 200) ++bad;',
    '        // the arrow of direction',
    '        if (rules::mmpArrowDirectionUsesPerDay() != 1 ||',
    '            rules::mmpArrowDirectionRepetitions() != 7 ||',
    '            rules::mmpArrowDirectionTurns() != 7 ||',
    '            rules::mmpArrowDirectionRequestKinds() != 5) ++bad;',
    '        // the bag of beans',
    '        if (rules::mmpBeanExplodeDamageLo() != 5 ||',
    '            rules::mmpBeanExplodeDamageHi() != 20 ||',
    '            rules::mmpBeanExplodeRadiusFeet() != 10 ||',
    '            rules::mmpBeanOptimumLo() != 3 ||',
    '            rules::mmpBeanOptimumHi() != 12 ||',
    '            rules::mmpBeanBeneficialMax() != 2 ||',
    '            rules::mmpBeanEffectRowCount() != 7 ||',
    '            rules::mmpBeanBerryCountLo() != 5 ||',
    '            rules::mmpBeanBerryCountHi() != 20 ||',
    '            rules::mmpBeanBerryGemLo() != 100 ||',
    '            rules::mmpBeanBerryGemHi() != 500 ||',
    '            rules::mmpBeanSmokeRadiusFeet() != 50 ||',
    '            rules::mmpBeanSmokeTurns() != 5 ||',
    '            rules::mmpBeanBlindRoundsLo() != 1 ||',
    '            rules::mmpBeanBlindRoundsHi() != 6 ||',
    '            rules::mmpBeanGasRadiusFeet() != 20 ||',
    '            rules::mmpBeanGasTurns() != 1) ++bad;',
    '        // the bag of devouring (the seam item)',
    '        if (rules::mmpDevouringIgnorePct() != 90 ||',
    '            rules::mmpDevouringClosePct() != 60 ||',
    '            rules::mmpDevouringBaseDrawPct() != 75 ||',
    '            rules::mmpDevouringDrawModPerPlus() != 5 ||',
    '            rules::mmpDevouringExampleStr18Pct() != 65 ||',
    '            rules::mmpDevouringExampleStr5Pct() != 80 ||',
    '            rules::mmpDevouringCapacityCubicFeet() != 30 ||',
    '            rules::mmpDevouringSwallowPctPerTurn() != 5 ||',
    '            rules::mmpDevouringConsumeSegments() != 7) ++bad;',
    '        printf("R257 misc magic prose part 1 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg-gap-report log entry ----
gap_old = [
    'not. New R256 battery audit;',
    'census 174. Next: III.E misc',
    'magic explanations (part1',
    '~10948-11067 continuing',
    'seamlessly into part2; global',
    'line = part1 line or ~11065 +',
    'part2 line, the TREASURE',
    '(MISCELLANEOUS MAGIC) headers',
    'are running page headers',
    'mid-paragraph).',
]
gap_new = [
    'not. New R256 battery audit;',
    'census 174. Next: III.E misc',
    'magic explanations (part1',
    '~10948-11067 continuing',
    'seamlessly into part2; global',
    'line = part1 line or ~11065 +',
    'part2 line, the TREASURE',
    '(MISCELLANEOUS MAGIC) headers',
    'are running page headers',
    'mid-paragraph).',
    '',
    'R257 landed the III.E misc',
    'magic explanation prose part 1',
    '(part1 10949-11065 stitched',
    'into part2 at line 3 - the',
    'FIRST TWO-PART-FILE round).',
    'rules/miscprose1.h (the mmp',
    'prefix, 65 accessors: 60',
    'scalars + 5 array walkers):',
    'the section intro (not more',
    'than 2 or 3 duplicates; books:',
    'a second wish for exact',
    'contents), Alchemy Jug (11',
    'liquids - 16 gallons salt water',
    'down to 4 drams cyanide; 1 kind',
    'and 7 pourings per day; 2',
    'gallons per round, 8 rounds for',
    'the salt water), Amulet of',
    'Inescapable Location (DOUBLES',
    'likelihood and range - the',
    'cursed lure), Amulet of Life',
    'Protection (7 full days),',
    'Amulet of the Planes (d6: 1-3',
    'no add, 4-6 add 12 to d12; the',
    '17-row plane table 1-2 through',
    '21-24; the alternates 22',
    'Ethereal / 23 Astral / 24',
    'alternate Earth), Amulet of',
    'Proof (no aura), Apparatus of',
    'Kwalish (10 levers, 3 forward 6',
    'backward, pincers 4 feet 2-12',
    'damage at 25%, 900 feet depth,',
    '2 occupants, 2-5 hours air,',
    'AC 0, 100 leak 200 stave),',
    'Arrow of Direction (once per',
    'day, 7 times in 7 turns, 5',
    'request kinds), Bag of Beans',
    '(5-20 explosion in 10 feet,',
    '3-12 optimum, 1-2 beneficial,',
    'the 7-row bean table: 5-20',
    'berries of 100/500 gp gems, 50',
    'feet 5 turn smoke blinding 1-6',
    'rounds, 20 feet 1 turn gas),',
    'Bag of Devouring (90% ignore,',
    '60% close, base 75% less 5% per',
    '+1, the 18/65% and 5/80%',
    'examples, 30 cubic feet, acts',
    'as bag of holding normal',
    'capacity, the 5% cumulative per',
    'turn swallow - THE SEAM FACT',
    'from part2 line 3 - creatures',
    'consumed in 7 segments). THE',
    'SEAM PINNED EXACTLY: part1 has',
    '11067 lines, last content line',
    '11065 ends IT HAS A 5%; part2',
    'line 1 is the page header,',
    'line 3 completes the sentence;',
    'the stitched sentence carries',
    'each turn it has a 5%',
    'cumulative chance of; global',
    'line = part1 line or 11065 +',
    'part2 line. ENGINE CROSS-',
    'CHECK: kMisc1 rows 0-6 (Alchemy',
    'Jug 1-2 through Arrow of',
    'Direction 14-16), row 8 Bag of',
    'Beans 18-20, row 9 Bag of',
    'Devouring 21 against the',
    'R225 m1 band pins. The TABLE',
    '(III.E.) 1. header at 10962',
    'is a running page header,',
    'stripped (the R249 lesson).',
    'New R257 battery audit; census',
    '175. Next: part 2 - Bag of',
    'Holding onward in part2 (line',
    '5 onward; global = 11065 +',
    'part2 line), through the end',
    'of the III.E explanations.',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence; the
# marker MUST be contiguous in the header text)
marker = 'R257: the III.E misc magic explanation prose part 1'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R257 FAIL: rules/miscprose1.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R257 audit', audit_old, audit_new),
    (GAP, 'the R257 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R257 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 175:
        print('R257 FAIL: census is not 175')
        sys.exit(1)
    if t.count('R257 misc magic prose part 1 pins audit') != 1:
        print('R257 FAIL: the R257 audit line must appear once')
        sys.exit(1)
    if t.count('rules/miscprose1.h') != 1:
        print('R257 FAIL: the miscprose1 include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R257 landed the III.E misc') != 1:
        print('R257 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int mmp') != 65:
        print('R257 FAIL: the header shape is wrong')
        sys.exit(1)

print('R257 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R257 note: 4 patches; the III.E misc magic explanation prose')
print('part 1 - intro + Alchemy Jug through Bag of Devouring, the')
print('first two-part-file round; census 175.')
print('commit: R257: the III.E misc magic explanation prose part 1 pinned - intro + Alchemy Jug through Bag of Devouring across the part1/part2 seam (census 175)')

