#!/usr/bin/env python3
# R258 splice: the III.E misc magic explanation prose
# pins, part 2 - Bag of Holding through Book of
# Exalted Deeds, all inside dmg-part2.md.
#
# Slice: part2 lines 5-66 (global line = 11065 +
# part2 line). No page headers inside the slice -
# the nearest TREASURE page header is at part2
# line 70, inside the Book of Infinite Spells
# section (R259 scope). The Bag of Tricks animal
# stat columns are mangled in the upload - the
# type bands and counts are pinned, the per-animal
# stats are not (the R256 lesson).
#
# New header rules/miscprose2.h (the mmp prefix
# again, 83 accessors: 74 scalars + 9 array
# walkers), the regtest include, the audit block,
# the dmg-gap-report log.
#
# commit: R258: the III.E misc magic explanation prose part 2 pinned - Bag of Holding through Book of Exalted Deeds in part2 lines 5-66 (census 176)

import sys

WD   = 'rules/miscprose2.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson)
t = open(REG).read()
if t.count('audit: bad ') != 175 and t.count('audit: bad ') != 176:
    print('R258 FAIL: regtest census is neither 175 nor 176')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose2.h',
    '// R258: the III.E misc magic explanation prose part 2',
    '// pins - part2 lines 5-66, Bag of Holding through',
    '// Book of Exalted Deeds (global line = 11065 +',
    '// part2 line; no page headers inside the slice).',
    '//   - Bag of Holding: the 4-row quality table',
    '//     (01-30: 15/250/30; 31-70: 15/500/70;',
    '//     71-90: 35/1000/150; 91-00: 60/1500/250);',
    '//     overload or a sharp pierce ruptures it,',
    '//     contents lost forever in nilspace.',
    '//   - Bag of Transmuting: appears as one of',
    '//     the 4 quality types; 2-5 proper uses;',
    '//     precious metals and gems to no worth;',
    '//     magic items (except artifacts and',
    '//     relics) to lead, glass or wood, no save.',
    '//   - Bag of Tricks: tossed 1-20 feet; d10',
    '//     type (1-5 / 6-8 / 9-0), 8 animals each;',
    '//     the animal stat columns are mangled in',
    '//     the upload - bands and counts pinned,',
    '//     stats not (the R256 lesson); 1 drawn at',
    '//     a time, slain or 1 turn then ordered',
    '//     back, 10 per week.',
    '//   - Beaker of Plentiful Potions: 2-5 doses',
    '//     of 2-5 potions; d4+1 count; 1 round per',
    '//     pour of 1 dose; delusion and poison',
    '//     possible; 2 potions: 1/day 3/week,',
    '//     3: 1/day 2/week, 4-5: 1/week; 1 potion',
    '//     type lost per month.',
    '//   - Boat, Folding: box 1 x half x half foot',
    '//     (12/6/6 inches); boat 10 x 4 x 2, ship',
    '//     24 x 8 x 6; 1 pair of oars vs 5 sets;',
    '//     3-4 vs 15 persons; 3 command words.',
    '//   - Book of Exalted Deeds: 1 week perusal;',
    '//     good cleric +1 wisdom, halfway XP;',
    '//     neutral 20,000-80,000; evil -1 level',
    '//     plus 50% for 2-5 adventures; MU -1 int',
    '//     or 2,000-20,000; thief 5-30 hp, -1 dex,',
    '//     10-60% conversion at wisdom 15; assassin',
    '//     5-40 hp; vanishes after perusal, one',
    '//     benefit per character.',
    '// The six items are the engine kMisc1 rows',
    '// 10-15 (the R225 m1 band pins) - cross-checked',
    '// in the audit, with the Exalted (C) class mark',
    '// at row 15. Pure data + helpers, header-only',
    '// (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpHoldingSackShortSideFeet() {',
    '    // a common cloth sack about 2 feet by 4',
    '    return 2;',
    '}',
    '',
    'inline int mmpHoldingSackLongSideFeet() {',
    '    // the long side of the 2 by 4 sack',
    '    return 4;',
    '}',
    '',
    'inline int mmpHoldingRowCount() {',
    '    // the 4 quality rows',
    '    return 4;',
    '}',
    '',
    'inline int mmpHoldingRuptureCauseCount() {',
    '    // overloaded, or pierced by sharp objects',
    '    return 2;',
    '}',
    '',
    'inline int mmpHoldingRowLo(int i) {',
    '    // the d100 band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 31, 71, 91,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHoldingRowHi(int i) {',
    '    // the d100 band upper edges (00 = 100)',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        30, 70, 90, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHoldingRowWeightPounds(int i) {',
    '    // the fixed bag weight by quality; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        15, 15, 35, 60,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHoldingRowWeightLimitPounds(int i) {',
    '    // the contents weight limit by quality; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        250, 500, 1000, 1500,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHoldingRowVolumeLimitCubicFeet(int i) {',
    '    // the volume limit by quality; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        30, 70, 150, 250,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpTransmutingDisguiseQualityCount() {',
    '    // appears as one of the 4 quality types',
    '    return 4;',
    '}',
    '',
    'inline int mmpTransmutingProperUsesMin() {',
    '    // performs properly for 2-5 uses',
    '    return 2;',
    '}',
    '',
    'inline int mmpTransmutingProperUsesMax() {',
    '    // the top of the 2-5 use range',
    '    return 5;',
    '}',
    '',
    'inline int mmpTransmutingTransmuteKindCount() {',
    '    // precious metals and gems to no worth',
    '    return 2;',
    '}',
    '',
    'inline int mmpTransmutingItemBaseMaterialCount() {',
    '    // magic items to lead, glass or wood',
    '    return 3;',
    '}',
    '',
    'inline int mmpTransmutingExemptKindCount() {',
    '    // artifacts and relics exempt',
    '    return 2;',
    '}',
    '',
    'inline int mmpTricksTossMinFeet() {',
    '    // withdrawn and tossed 1 to 20 feet away',
    '    return 1;',
    '}',
    '',
    'inline int mmpTricksTossMaxFeet() {',
    '    // the top of the 1-20 foot toss',
    '    return 20;',
    '}',
    '',
    'inline int mmpTricksTypeDieSides() {',
    '    // roll d10 to determine the bag type',
    '    return 10;',
    '}',
    '',
    'inline int mmpTricksTypeCount() {',
    '    // three type tables',
    '    return 3;',
    '}',
    '',
    'inline int mmpTricksAnimalsPerType() {',
    '    // 8 animals per type table, die 1-8',
    '    return 8;',
    '}',
    '',
    'inline int mmpTricksAnimalDieMin() {',
    '    // the animal die low edge',
    '    return 1;',
    '}',
    '',
    'inline int mmpTricksAnimalDieMax() {',
    '    // the animal die high edge',
    '    return 8;',
    '}',
    '',
    'inline int mmpTricksDrawnAtOnceMax() {',
    '    // only 1 creature drawn forth at a time',
    '    return 1;',
    '}',
    '',
    'inline int mmpTricksDurationTurns() {',
    '    // exists until slain or 1 turn elapsed',
    '    return 1;',
    '}',
    '',
    'inline int mmpTricksEndConditionCount() {',
    '    // slain, or ordered back after the turn',
    '    return 2;',
    '}',
    '',
    'inline int mmpTricksTypeRollCount() {',
    '    // one roll only for the bag type',
    '    return 1;',
    '}',
    '',
    'inline int mmpTricksWeeklyDrawMax() {',
    '    // up to 10 creatures per week',
    '    return 10;',
    '}',
    '',
    'inline int mmpTricksTypeLo(int i) {',
    '    // the d10 type band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        1, 6, 9,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpTricksTypeHi(int i) {',
    '    // the d10 type band upper edges (0 = 10)',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        5, 8, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpBeakerDoseMin() {',
    '    // compounds from 2-5 doses',
    '    return 2;',
    '}',
    '',
    'inline int mmpBeakerDoseMax() {',
    '    // the top of the 2-5 dose range',
    '    return 5;',
    '}',
    '',
    'inline int mmpBeakerPotionCountMin() {',
    '    // of from 2-5 potions',
    '    return 2;',
    '}',
    '',
    'inline int mmpBeakerPotionCountMax() {',
    '    // the top of the 2-5 potion range',
    '    return 5;',
    '}',
    '',
    'inline int mmpBeakerCountDieSides() {',
    '    // roll d4 plus 1 for the potion count',
    '    return 4;',
    '}',
    '',
    'inline int mmpBeakerCountDiePlus() {',
    '    // the +1 on the count die',
    '    return 1;',
    '}',
    '',
    'inline int mmpBeakerPourRounds() {',
    '    // each pouring takes 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpBeakerPourDoses() {',
    '    // spills forth 1 dose of 1 potion type',
    '    return 1;',
    '}',
    '',
    'inline int mmpBeakerBadTypeCount() {',
    '    // delusion and poison are possible',
    '    return 2;',
    '}',
    '',
    'inline int mmpBeakerMonthlyTypeLoss() {',
    '    // one potion type lost per month, permanent',
    '    return 1;',
    '}',
    '',
    'inline int mmpBeakerDispenseRowMin() {',
    '    // dispensing rows keyed by potions held',
    '    return 2;',
    '}',
    '',
    'inline int mmpBeakerDispenseRowMax() {',
    '    // the top row key (5 potions)',
    '    return 5;',
    '}',
    '',
    'inline int mmpBeakerPerDayByCount(int i) {',
    '    // row i = potions held - 2; per-day rate,',
    '    // 0 for the 4-5 potion rows; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 1, 0, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpBeakerPerWeekByCount(int i) {',
    '    // row i = potions held - 2; per-week rate;',
    '    // i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        3, 2, 1, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpBoatBoxLengthInches() {',
    '    // the box: 1 foot long',
    '    return 12;',
    '}',
    '',
    'inline int mmpBoatBoxWidthInches() {',
    '    // the box: half a foot wide',
    '    return 6;',
    '}',
    '',
    'inline int mmpBoatBoxDepthInches() {',
    '    // the box: half a foot deep',
    '    return 6;',
    '}',
    '',
    'inline int mmpBoatLengthFeet() {',
    '    // first word: the boat, 10 feet long',
    '    return 10;',
    '}',
    '',
    'inline int mmpBoatWidthFeet() {',
    '    // the boat, 4 feet wide',
    '    return 4;',
    '}',
    '',
    'inline int mmpBoatDepthFeet() {',
    '    // the boat, 2 feet deep',
    '    return 2;',
    '}',
    '',
    'inline int mmpBoatShipLengthFeet() {',
    '    // second word: the ship, 24 feet long',
    '    return 24;',
    '}',
    '',
    'inline int mmpBoatShipWidthFeet() {',
    '    // the ship, 8 feet wide',
    '    return 8;',
    '}',
    '',
    'inline int mmpBoatShipDepthFeet() {',
    '    // the ship, 6 feet deep',
    '    return 6;',
    '}',
    '',
    'inline int mmpBoatOarPairs() {',
    '    // the boat: 1 pair of oars',
    '    return 1;',
    '}',
    '',
    'inline int mmpBoatComponentCount() {',
    '    // oars, anchor, mast, lateen sail',
    '    return 4;',
    '}',
    '',
    'inline int mmpBoatShipOarSets() {',
    '    // the ship: 5 sets of oars',
    '    return 5;',
    '}',
    '',
    'inline int mmpBoatShipComponentCount() {',
    '    // rowing seats, oar sets, steering oar,',
    '    // anchor, deck cabin, mast, square sail',
    '    return 7;',
    '}',
    '',
    'inline int mmpBoatPersonsMin() {',
    '    // the boat holds 3 or 4 persons',
    '    return 3;',
    '}',
    '',
    'inline int mmpBoatPersonsMax() {',
    '    // the comfortable top',
    '    return 4;',
    '}',
    '',
    'inline int mmpBoatShipPersons() {',
    '    // the ship carries 15 persons',
    '    return 15;',
    '}',
    '',
    'inline int mmpBoatCommandWordCount() {',
    '    // third word folds it to a box again',
    '    return 3;',
    '}',
    '',
    'inline int mmpExaltedReadingWeeks() {',
    '    // reading requires 1 week',
    '    return 1;',
    '}',
    '',
    'inline int mmpExaltedWisdomGain() {',
    '    // the good cleric gains 1 wisdom',
    '    return 1;',
    '}',
    '',
    'inline int mmpExaltedHalfwayPct() {',
    '    // XP to exactly half way into next level',
    '    return 50;',
    '}',
    '',
    'inline int mmpExaltedNeutralXpLossMin() {',
    '    // neutral clerics lose 20,000-80,000 XP',
    '    return 20000;',
    '}',
    '',
    'inline int mmpExaltedNeutralXpLossMax() {',
    '    // the top of the neutral loss',
    '    return 80000;',
    '}',
    '',
    'inline int mmpExaltedLevelFloor() {',
    '    // negative XP possible, never below 1st',
    '    return 1;',
    '}',
    '',
    'inline int mmpExaltedEvilLevelLoss() {',
    '    // evil clerics lose 1 full level',
    '    return 1;',
    '}',
    '',
    'inline int mmpExaltedAtonementPct() {',
    '    // or offer up 50% of everything gained',
    '    return 50;',
    '}',
    '',
    'inline int mmpExaltedAtonementAdventuresMin() {',
    '    // for 2-5 adventures',
    '    return 2;',
    '}',
    '',
    'inline int mmpExaltedAtonementAdventuresMax() {',
    '    // the top of the 2-5 adventures',
    '    return 5;',
    '}',
    '',
    'inline int mmpExaltedMuIntLoss() {',
    '    // magic-users lose 1 intelligence,',
    '    // unless they save versus magic',
    '    return 1;',
    '}',
    '',
    'inline int mmpExaltedMuSaveXpLossMin() {',
    '    // on a save they lose 2,000-20,000 XP',
    '    return 2000;',
    '}',
    '',
    'inline int mmpExaltedMuSaveXpLossMax() {',
    '    // the top of the save loss',
    '    return 20000;',
    '}',
    '',
    'inline int mmpExaltedThiefHpMin() {',
    '    // the thief takes 5-30 hit points',
    '    return 5;',
    '}',
    '',
    'inline int mmpExaltedThiefHpMax() {',
    '    // the top of the thief damage',
    '    return 30;',
    '}',
    '',
    'inline int mmpExaltedThiefDexLoss() {',
    '    // save or lose 1 dexterity',
    '    return 1;',
    '}',
    '',
    'inline int mmpExaltedThiefConvertPctMin() {',
    '    // 10%-60% chance to become a good cleric',
    '    return 10;',
    '}',
    '',
    'inline int mmpExaltedThiefConvertPctMax() {',
    '    // the top of the conversion range',
    '    return 60;',
    '}',
    '',
    'inline int mmpExaltedThiefConvertWisReq() {',
    '    // if wisdom is 15 or higher',
    '    return 15;',
    '}',
    '',
    'inline int mmpExaltedAssassinHpMin() {',
    '    // the assassin takes 5-40 hit points',
    '    return 5;',
    '}',
    '',
    'inline int mmpExaltedAssassinHpMax() {',
    '    // the top of the assassin damage',
    '    return 40;',
    '}',
    '',
    'inline int mmpExaltedVanishesAfterPerusal() {',
    '    // once perused the book vanishes',
    '    return 1;',
    '}',
    '',
    'inline int mmpExaltedMaxBenefitTimes() {',
    '    // never a second benefit, same character',
    '    return 1;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the include patch ----
inc_old = [
    '#include "rules/miscprose1.h"  // R257: the III.E misc magic explanation prose part 1 pins',
]
inc_new = [
    '#include "rules/miscprose1.h"  // R257: the III.E misc magic explanation prose part 1 pins',
    '#include "rules/miscprose2.h"  // R258: the III.E misc magic explanation prose part 2 pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R258: the III.E misc magic explanation prose part 2 pins audit ----',
    '    // part2 lines 5-66 - Bag of Holding through',
    '    // Book of Exalted Deeds, global = 11065 +',
    '    // part2 line; no page headers inside the',
    '    // slice.',
    '    {',
    '        int bad = 0;',
    '        // the six items are the engine kMisc1 rows',
    '        // 10-15 (the R225 m1 band pins); the',
    '        // Exalted (C) class mark is row 15, the',
    '        // Boat row 14 is the negative control',
    '        if (rules::m1RowCount() != 33) ++bad;',
    '        static const int kM1Lo[6] = {',
    '            22, 27, 28, 30, 32, 33,',
    '        };',
    '        static const int kM1Hi[6] = {',
    '            26, 27, 29, 31, 32, 33,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::m1RowLo(10 + i) != kM1Lo[i] ||',
    '                rules::m1RowHi(10 + i) != kM1Hi[i]) ++bad;',
    '        if (rules::m1UsableByCleric(15) != 1 ||',
    '            rules::m1UsableByCleric(14) != 0) ++bad;',
    '        // the bag of holding: the 4 quality rows',
    '        if (rules::mmpHoldingSackShortSideFeet() != 2 ||',
    '            rules::mmpHoldingSackLongSideFeet() != 4 ||',
    '            rules::mmpHoldingRowCount() != 4 ||',
    '            rules::mmpHoldingRuptureCauseCount() != 2) ++bad;',
    '        static const int kHoldingLo[4] = {',
    '            1, 31, 71, 91,',
    '        };',
    '        static const int kHoldingHi[4] = {',
    '            30, 70, 90, 100,',
    '        };',
    '        static const int kHoldingWeight[4] = {',
    '            15, 15, 35, 60,',
    '        };',
    '        static const int kHoldingWeightLimit[4] = {',
    '            250, 500, 1000, 1500,',
    '        };',
    '        static const int kHoldingVolume[4] = {',
    '            30, 70, 150, 250,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpHoldingRowLo(i) != kHoldingLo[i] ||',
    '                rules::mmpHoldingRowHi(i) != kHoldingHi[i] ||',
    '                rules::mmpHoldingRowWeightPounds(i) !=',
    '                    kHoldingWeight[i] ||',
    '                rules::mmpHoldingRowWeightLimitPounds(i) !=',
    '                    kHoldingWeightLimit[i] ||',
    '                rules::mmpHoldingRowVolumeLimitCubicFeet(i) !=',
    '                    kHoldingVolume[i]) ++bad;',
    '        // the bag of transmuting',
    '        if (rules::mmpTransmutingDisguiseQualityCount() != 4 ||',
    '            rules::mmpTransmutingProperUsesMin() != 2 ||',
    '            rules::mmpTransmutingProperUsesMax() != 5 ||',
    '            rules::mmpTransmutingTransmuteKindCount() != 2 ||',
    '            rules::mmpTransmutingItemBaseMaterialCount() != 3 ||',
    '            rules::mmpTransmutingExemptKindCount() != 2) ++bad;',
    '        // the bag of tricks: the animal stat columns',
    '        // are mangled in the upload - the type bands',
    '        // and counts are pinned, the stats are not',
    '        // (the R256 lesson)',
    '        if (rules::mmpTricksTossMinFeet() != 1 ||',
    '            rules::mmpTricksTossMaxFeet() != 20 ||',
    '            rules::mmpTricksTypeDieSides() != 10 ||',
    '            rules::mmpTricksTypeCount() != 3 ||',
    '            rules::mmpTricksAnimalsPerType() != 8 ||',
    '            rules::mmpTricksAnimalDieMin() != 1 ||',
    '            rules::mmpTricksAnimalDieMax() != 8 ||',
    '            rules::mmpTricksDrawnAtOnceMax() != 1 ||',
    '            rules::mmpTricksDurationTurns() != 1 ||',
    '            rules::mmpTricksEndConditionCount() != 2 ||',
    '            rules::mmpTricksTypeRollCount() != 1 ||',
    '            rules::mmpTricksWeeklyDrawMax() != 10) ++bad;',
    '        static const int kTricksTypeLo[3] = {',
    '            1, 6, 9,',
    '        };',
    '        static const int kTricksTypeHi[3] = {',
    '            5, 8, 100,',
    '        };',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpTricksTypeLo(i) != kTricksTypeLo[i] ||',
    '                rules::mmpTricksTypeHi(i) != kTricksTypeHi[i]) ++bad;',
    '        // the beaker of plentiful potions',
    '        if (rules::mmpBeakerDoseMin() != 2 ||',
    '            rules::mmpBeakerDoseMax() != 5 ||',
    '            rules::mmpBeakerPotionCountMin() != 2 ||',
    '            rules::mmpBeakerPotionCountMax() != 5 ||',
    '            rules::mmpBeakerCountDieSides() != 4 ||',
    '            rules::mmpBeakerCountDiePlus() != 1 ||',
    '            rules::mmpBeakerPourRounds() != 1 ||',
    '            rules::mmpBeakerPourDoses() != 1 ||',
    '            rules::mmpBeakerBadTypeCount() != 2 ||',
    '            rules::mmpBeakerMonthlyTypeLoss() != 1 ||',
    '            rules::mmpBeakerDispenseRowMin() != 2 ||',
    '            rules::mmpBeakerDispenseRowMax() != 5) ++bad;',
    '        static const int kBeakerPerDay[4] = {',
    '            1, 1, 0, 0,',
    '        };',
    '        static const int kBeakerPerWeek[4] = {',
    '            3, 2, 1, 1,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpBeakerPerDayByCount(i) !=',
    '                    kBeakerPerDay[i] ||',
    '                rules::mmpBeakerPerWeekByCount(i) !=',
    '                    kBeakerPerWeek[i]) ++bad;',
    '        // the boat, folding',
    '        if (rules::mmpBoatBoxLengthInches() != 12 ||',
    '            rules::mmpBoatBoxWidthInches() != 6 ||',
    '            rules::mmpBoatBoxDepthInches() != 6 ||',
    '            rules::mmpBoatLengthFeet() != 10 ||',
    '            rules::mmpBoatWidthFeet() != 4 ||',
    '            rules::mmpBoatDepthFeet() != 2 ||',
    '            rules::mmpBoatShipLengthFeet() != 24 ||',
    '            rules::mmpBoatShipWidthFeet() != 8 ||',
    '            rules::mmpBoatShipDepthFeet() != 6 ||',
    '            rules::mmpBoatOarPairs() != 1 ||',
    '            rules::mmpBoatComponentCount() != 4 ||',
    '            rules::mmpBoatShipOarSets() != 5 ||',
    '            rules::mmpBoatShipComponentCount() != 7 ||',
    '            rules::mmpBoatPersonsMin() != 3 ||',
    '            rules::mmpBoatPersonsMax() != 4 ||',
    '            rules::mmpBoatShipPersons() != 15 ||',
    '            rules::mmpBoatCommandWordCount() != 3) ++bad;',
    '        // the book of exalted deeds',
    '        if (rules::mmpExaltedReadingWeeks() != 1 ||',
    '            rules::mmpExaltedWisdomGain() != 1 ||',
    '            rules::mmpExaltedHalfwayPct() != 50 ||',
    '            rules::mmpExaltedNeutralXpLossMin() != 20000 ||',
    '            rules::mmpExaltedNeutralXpLossMax() != 80000 ||',
    '            rules::mmpExaltedLevelFloor() != 1 ||',
    '            rules::mmpExaltedEvilLevelLoss() != 1 ||',
    '            rules::mmpExaltedAtonementPct() != 50 ||',
    '            rules::mmpExaltedAtonementAdventuresMin() != 2 ||',
    '            rules::mmpExaltedAtonementAdventuresMax() != 5 ||',
    '            rules::mmpExaltedMuIntLoss() != 1 ||',
    '            rules::mmpExaltedMuSaveXpLossMin() != 2000 ||',
    '            rules::mmpExaltedMuSaveXpLossMax() != 20000 ||',
    '            rules::mmpExaltedThiefHpMin() != 5 ||',
    '            rules::mmpExaltedThiefHpMax() != 30 ||',
    '            rules::mmpExaltedThiefDexLoss() != 1 ||',
    '            rules::mmpExaltedThiefConvertPctMin() != 10 ||',
    '            rules::mmpExaltedThiefConvertPctMax() != 60 ||',
    '            rules::mmpExaltedThiefConvertWisReq() != 15 ||',
    '            rules::mmpExaltedAssassinHpMin() != 5 ||',
    '            rules::mmpExaltedAssassinHpMax() != 40 ||',
    '            rules::mmpExaltedVanishesAfterPerusal() != 1 ||',
    '            rules::mmpExaltedMaxBenefitTimes() != 1) ++bad;',
    '        printf("R258 misc magic prose part 2 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg-gap-report log entry ----
gap_old = [
    'New R257 battery audit; census',
    '175. Next: part 2 - Bag of',
    'Holding onward in part2 (line',
    '5 onward; global = 11065 +',
    'part2 line), through the end',
    'of the III.E explanations.',
]
gap_new = [
    'New R257 battery audit; census',
    '175. Next: part 2 - Bag of',
    'Holding onward in part2 (line',
    '5 onward; global = 11065 +',
    'part2 line), through the end',
    'of the III.E explanations.',
    '',
    'R258 landed the III.E misc',
    'magic explanation prose part 2',
    '(part2 lines 5-66; global =',
    '11065 + part2 line; no page',
    'headers inside the slice).',
    'rules/miscprose2.h (the mmp',
    'prefix again, 83 accessors: 74',
    'scalars + 9 array walkers): Bag',
    'of Holding (the 4-row quality',
    'table 01-30 15/250/30 through',
    '91-00 60/1500/250; overload or',
    'sharp pierce ruptures, contents',
    'lost in nilspace), Bag of',
    'Transmuting (one of the 4',
    'quality types, 2-5 proper uses,',
    'metals and gems to no worth,',
    'magic items to lead/glass/wood',
    'no save), Bag of Tricks (toss',
    '1-20 feet; d10 type bands 1-5,',
    '6-8, 9-0; 8 animals each; only',
    'the bands and counts are',
    'pinned - the animal stat',
    'columns are mangled in the',
    'upload, the R256 lesson; 1',
    'drawn at a time, slain or 1',
    'turn then ordered back, 10 per',
    'week), Beaker of Plentiful',
    'Potions (2-5 doses of 2-5',
    'potions, d4+1 count, 1 round',
    'pours of 1 dose, delusion and',
    'poison possible, 2: 1/day',
    '3/week, 3: 1/day 2/week, 4-5:',
    '1/week, 1 type lost per month),',
    'Boat, Folding (box 12/6/6',
    'inches; boat 10x4x2 with 1 pair',
    'of oars, holds 3-4; ship 24x8x6',
    'with 5 oar sets, carries 15; 3',
    'command words), Book of',
    'Exalted Deeds (1 week perusal,',
    '+1 wisdom halfway XP, neutral',
    '20,000-80,000, evil -1 level +',
    '50% for 2-5 adventures, MU -1',
    'int or 2,000-20,000, thief 5-30',
    'hp -1 dex 10-60% convert at',
    'wisdom 15, assassin 5-40 hp,',
    'vanishes after perusal). ENGINE',
    'CROSS-CHECK: kMisc1 rows 10-15',
    '(Holding 22-26, Transmuting 27,',
    'Tricks 28-29, Beaker 30-31,',
    'Boat 32, Exalted 33) plus the',
    'Exalted (C) class mark at row',
    '15 (Boat row 14 as the',
    'negative control) against the',
    'R225 m1 pins. New R258 battery',
    'audit; census 176. Next: part 3',
    '- Book of Infinite Spells onward',
    'in part2 from line 67 (global =',
    '11065 + part2 line; the TREASURE',
    'page header at line 70 splits',
    'its page table).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence; the
# marker MUST be contiguous in the header text)
marker = 'R258: the III.E misc magic explanation prose part 2'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R258 FAIL: rules/miscprose2.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R258 audit', audit_old, audit_new),
    (GAP, 'the R258 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R258 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 176:
        print('R258 FAIL: census is not 176')
        sys.exit(1)
    if t.count('R258 misc magic prose part 2 pins audit') != 1:
        print('R258 FAIL: the R258 audit line must appear once')
        sys.exit(1)
    if t.count('rules/miscprose2.h') != 1:
        print('R258 FAIL: the miscprose2 include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R258 landed the III.E misc') != 1:
        print('R258 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int mmp') != 83:
        print('R258 FAIL: the header shape is wrong')
        sys.exit(1)

print('R258 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R258 note: 4 patches; the III.E misc magic explanation prose')
print('part 2 - Bag of Holding through Book of Exalted Deeds,')
print('part2 lines 5-66; census 176.')
print('commit: R258: the III.E misc magic explanation prose part 2 pinned - Bag of Holding through Book of Exalted Deeds in part2 lines 5-66 (census 176)')

