#!/usr/bin/env python3
# R259 splice: the III.E misc magic explanation prose
# pins, part 3 - Book of Infinite Spells through Boots
# of Striding and Springing, all inside dmg-part2.md.
#
# Slice: part2 lines 67-108 (global line = 11065 +
# part2 line). TWO page headers inside the slice,
# both stripped (the R249 lesson): line 70 splits
# the page table from the Book of Infinite Spells
# intro, line 102 splits the Boots of Levitation
# paragraph mid-sentence - the seam pinned exactly
# (line 100 ends the ascent/descent speed mid-phrase,
# line 104 continues ROUND (MINUTE)). The stray
# table-title line 83 is a duplicated header, noted
# not pinned.
#
# New header rules/miscprose3.h (the mmp prefix
# again, 76 accessors: 73 scalars + 3 array
# walkers), the regtest include, the audit block,
# the dmg-gap-report log.
#
# commit: R259: the III.E misc magic explanation prose part 3 pinned - Book of Infinite Spells through Boots of Striding and Springing in part2 lines 67-108 (census 177)

import sys

WD   = 'rules/miscprose3.h'
REG  = 'regtest.cpp'
GAP  = 'tools/dmg_gap_report.md'

NL = chr(10)
BS = chr(92)

# pre-checks - pristine OR fully-patched (the R234
# two-state lesson)
t = open(REG).read()
if t.count('audit: bad ') != 176 and t.count('audit: bad ') != 177:
    print('R259 FAIL: regtest census is neither 176 nor 177')
    sys.exit(1)

# ---- the new header ----
hdr_lines = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose3.h',
    '// R259: the III.E misc magic explanation prose part 3',
    '// pins - part2 lines 67-108, Book of Infinite Spells',
    '// through Boots of Striding and Springing (global line',
    '// = 11065 + part2 line). TWO page headers inside the',
    '// slice, both stripped (the R249 lesson): line 70 splits',
    '// the page table from the Book of Infinite Spells intro;',
    '// line 102 splits the Boots of Levitation paragraph',
    '// mid-sentence - the seam pinned exactly (line 100 ends',
    '// the ascent/descent speed mid-phrase, line 104 continues',
    '// ROUND (MINUTE)).',
    '//   - Book of Infinite Spells: non-casters 5-20 hp and',
    '//     5-20 turns stunned on first read; 23-30 (22 + d8)',
    '//     pages; the 5-row page table; d10 level die (d12 for',
    '//     magic-user), 8-10 / 10-12 reroll to d6 / d8; cast',
    '//     the open page 1/day (4/day if already castable);',
    '//     the page-turn ladder 10/20/25/30%; the last page',
    '//     turned and the book vanishes.',
    '//   - Book of Vile Darkness: 1 week, +1 wisdom, halfway',
    '//     XP; neutral 30,000-120,000 or turn evil, 50% either;',
    '//     good clerics 2 saves (poison or die, magic or',
    '//     insane), then 250,000 XP less 10,000 per wisdom;',
    '//     other good 5-30 hp, 80% night hag if opened;',
    '//     non-evil neutral 5-20 hp handling.',
    '//   - Boots of Dancing: masquerade as one of the other 4',
    '//     useful types until melee or fleeing; AC penalty 4,',
    '//     no saves, no attacks; remove curse only.',
    '//   - Boots of Elvenkind: 95% silence worst, 100% best.',
    '//   - Boots of Levitation: 20 inches per round; d20 in',
    '//     14 pound increments over a 280 pound base, 294',
    '//     to 560 pounds.',
    '//   - Boots of Speed: 24 inch base; 1 inch slower per 10',
    '//     pounds over 200 (the 180/60 example at 20; the 500',
    '//     coin sack at 5 more); 1 rest hour per move hour, 8',
    '//     hours max; AC +2.',
    '//   - Boots of Striding and Springing: 12 inch base, 12',
    '//     hours then 12 recharge; 3 foot paces, 30 forward,',
    '//     9 backward, 15 vertical; 20% stumble less 3% per',
    '//     dex above 12 (the 17/14/11/8/5/2 ladder); AC +1.',
    '// The seven items are the engine kMisc1 rows 16-22 (the',
    '// R225 m1 band pins) - cross-checked in the audit, with',
    '// the Vile (C) class mark at row 17. Pure data +',
    '// helpers, header-only (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpInfiniteFirstReadHpMin() {',
    '    // non-casters suffer 5-20 hit points',
    '    return 5;',
    '}',
    '',
    'inline int mmpInfiniteFirstReadHpMax() {',
    '    // the top of the first-read damage',
    '    return 20;',
    '}',
    '',
    'inline int mmpInfiniteFirstReadStunTurnsMin() {',
    '    // and are stunned 5-20 turns',
    '    return 5;',
    '}',
    '',
    'inline int mmpInfiniteFirstReadStunTurnsMax() {',
    '    // the top of the stun range',
    '    return 20;',
    '}',
    '',
    'inline int mmpInfinitePageMin() {',
    '    // contains from 23-30 pages',
    '    return 23;',
    '}',
    '',
    'inline int mmpInfinitePageMax() {',
    '    // the top of the page range',
    '    return 30;',
    '}',
    '',
    'inline int mmpInfinitePageBase() {',
    '    // 22 + d8 pages',
    '    return 22;',
    '}',
    '',
    'inline int mmpInfinitePageDieSides() {',
    '    // the d8 on the page count',
    '    return 8;',
    '}',
    '',
    'inline int mmpInfinitePageRowCount() {',
    '    // the 5-row page table',
    '    return 5;',
    '}',
    '',
    'inline int mmpInfinitePageLo(int i) {',
    '    // the d100 page-band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 4) i = 4;',
    '    static const int t[5] = {',
    '        1, 31, 51, 61, 96,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpInfinitePageHi(int i) {',
    '    // the d100 page-band upper edges (00 = 100)',
    '    if (i < 0) i = 0;',
    '    if (i > 4) i = 4;',
    '    static const int t[5] = {',
    '        30, 50, 60, 95, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpInfiniteLevelDieSides() {',
    '    // roll d10 for spell level, all but magic-user',
    '    return 10;',
    '}',
    '',
    'inline int mmpInfiniteMuLevelDieSides() {',
    '    // the magic-user level die is a d12',
    '    return 12;',
    '}',
    '',
    'inline int mmpInfiniteLevelRerollLo() {',
    '    // results 8-10 reroll to d6',
    '    return 8;',
    '}',
    '',
    'inline int mmpInfiniteLevelRerollHi() {',
    '    // the top of the 8-10 reroll band',
    '    return 10;',
    '}',
    '',
    'inline int mmpInfiniteMuLevelRerollLo() {',
    '    // magic-user 10-12 reroll to d8',
    '    return 10;',
    '}',
    '',
    'inline int mmpInfiniteMuLevelRerollHi() {',
    '    // the top of the 10-12 reroll band',
    '    return 12;',
    '}',
    '',
    'inline int mmpInfiniteRerollDieSides() {',
    '    // the reroll die',
    '    return 6;',
    '}',
    '',
    'inline int mmpInfiniteMuRerollDieSides() {',
    '    // the magic-user reroll die',
    '    return 8;',
    '}',
    '',
    'inline int mmpInfiniteVanishesAtLastPage() {',
    '    // the last page turned, the book vanishes',
    '    return 1;',
    '}',
    '',
    'inline int mmpInfiniteCastPerDay() {',
    '    // cast the open page once per day',
    '    return 1;',
    '}',
    '',
    'inline int mmpInfiniteCastPerDayIfKnown() {',
    '    // 4 per day if already castable by class',
    '    return 4;',
    '}',
    '',
    'inline int mmpInfiniteTurnPctUsable() {',
    '    // page turns: usable by class and level',
    '    return 10;',
    '}',
    '',
    'inline int mmpInfiniteTurnPctForeign() {',
    '    // foreign to class and/or level',
    '    return 20;',
    '}',
    '',
    'inline int mmpInfiniteTurnPctNonCasterCleric() {',
    '    // non-caster using a cleric spell',
    '    return 25;',
    '}',
    '',
    'inline int mmpInfiniteTurnPctNonCasterMu() {',
    '    // non-caster using a magic-user spell',
    '    return 30;',
    '}',
    '',
    'inline int mmpVileReadingWeeks() {',
    '    // full consumption requires 1 week',
    '    return 1;',
    '}',
    '',
    'inline int mmpVileWisdomGain() {',
    '    // the evil cleric gains 1 wisdom',
    '    return 1;',
    '}',
    '',
    'inline int mmpVileHalfwayPct() {',
    '    // XP to exactly half way into next level',
    '    return 50;',
    '}',
    '',
    'inline int mmpVileNeutralXpLossMin() {',
    '    // neutral clerics lose 30,000-120,000 XP',
    '    return 30000;',
    '}',
    '',
    'inline int mmpVileNeutralXpLossMax() {',
    '    // or become evil, 50% for either',
    '    return 120000;',
    '}',
    '',
    'inline int mmpVileNeutralSplitPct() {',
    '    // the either-or chance',
    '    return 50;',
    '}',
    '',
    'inline int mmpVileGoodSaveCount() {',
    '    // good clerics: poison or die, then magic or',
    '    // become permanently insane - two saves',
    '    return 2;',
    '}',
    '',
    'inline int mmpVileGoodXpLossBase() {',
    '    // the good cleric XP loss base',
    '    return 250000;',
    '}',
    '',
    'inline int mmpVileGoodXpLossPerWis() {',
    '    // less 10,000 per wisdom point',
    '    return 10000;',
    '}',
    '',
    'inline int mmpVileGoodHandlingHpMin() {',
    '    // other good characters take 5-30 hp',
    '    return 5;',
    '}',
    '',
    'inline int mmpVileGoodHandlingHpMax() {',
    '    // the top of the good handling damage',
    '    return 30;',
    '}',
    '',
    'inline int mmpVileNightHagPct() {',
    '    // 80% a night hag comes if they look inside',
    '    return 80;',
    '}',
    '',
    'inline int mmpVileNeutralHandlingHpMin() {',
    '    // non-evil neutral handling: 5-20 hp',
    '    return 5;',
    '}',
    '',
    'inline int mmpVileNeutralHandlingHpMax() {',
    '    // the top of the neutral handling damage',
    '    return 20;',
    '}',
    '',
    'inline int mmpDancingDisguisedBootTypeCount() {',
    '    // masquerade as one of the other 4 useful',
    '    // types until melee combat',
    '    return 4;',
    '}',
    '',
    'inline int mmpDancingTriggerCaseCount() {',
    '    // in melee, or fleeing from the actuality',
    '    return 2;',
    '}',
    '',
    'inline int mmpDancingAcPenalty() {',
    '    // the armor class penalty',
    '    return 4;',
    '}',
    '',
    'inline int mmpDancingRemovalSpellCount() {',
    '    // only a remove curse spell frees the wearer',
    '    return 1;',
    '}',
    '',
    'inline int mmpElvenkindSilencePctWorst() {',
    '    // 95% chance of silence in the worst conditions',
    '    return 95;',
    '}',
    '',
    'inline int mmpElvenkindSilencePctBest() {',
    '    // 100% in the best',
    '    return 100;',
    '}',
    '',
    'inline int mmpLevitationSpeedInchesPerRound() {',
    '    // the ascent/descent speed per round (the 102',
    '    // seam fact, completed across the page header)',
    '    return 20;',
    '}',
    '',
    'inline int mmpLevitationWeightIncrementPounds() {',
    '    // d20 in 14 pound increments',
    '    return 14;',
    '}',
    '',
    'inline int mmpLevitationWeightDieSides() {',
    '    // the d20 on the weight capacity',
    '    return 20;',
    '}',
    '',
    'inline int mmpLevitationWeightBasePounds() {',
    '    // added to a base of 280 pounds',
    '    return 280;',
    '}',
    '',
    'inline int mmpLevitationWeightMinPounds() {',
    '    // 294 pounds at the minimum roll',
    '    return 294;',
    '}',
    '',
    'inline int mmpLevitationWeightMaxPounds() {',
    '    // 560 pounds at the maximum roll',
    '    return 560;',
    '}',
    '',
    'inline int mmpSpeedBaseMovementInches() {',
    '    // the speed of a fast horse, 24 inches base',
    '    return 24;',
    '}',
    '',
    'inline int mmpSpeedSlowPoundsPerInch() {',
    '    // 1 inch slower per 10 pounds over 200',
    '    return 10;',
    '}',
    '',
    'inline int mmpSpeedFreeWeightPounds() {',
    '    // the 200 pound free allowance',
    '    return 200;',
    '}',
    '',
    'inline int mmpSpeedExampleHumanPounds() {',
    '    // the example: a 180 pound human',
    '    return 180;',
    '}',
    '',
    'inline int mmpSpeedExampleGearPounds() {',
    '    // with 60 pounds of gear',
    '    return 60;',
    '}',
    '',
    'inline int mmpSpeedExampleRateInches() {',
    '    // moves at 20 inches base rate',
    '    return 20;',
    '}',
    '',
    'inline int mmpSpeedSackCoins() {',
    '    // the extra sack of 500 gold pieces',
    '    return 500;',
    '}',
    '',
    'inline int mmpSpeedSackSlowInches() {',
    '    // slows the rate yet another 5 inches',
    '    return 5;',
    '}',
    '',
    'inline int mmpSpeedRestHoursPerMoveHour() {',
    '    // 1 rest hour per hour of fast movement',
    '    return 1;',
    '}',
    '',
    'inline int mmpSpeedMaxContinuousHours() {',
    '    // no more than 8 hours continuous',
    '    return 8;',
    '}',
    '',
    'inline int mmpSpeedAcBonus() {',
    '    // +2 to armor class value in combat',
    '    return 2;',
    '}',
    '',
    'inline int mmpStridingBaseMovementInches() {',
    '    // base movement rate of 12 inches regardless',
    '    return 12;',
    '}',
    '',
    'inline int mmpStridingMaxHoursPerDay() {',
    '    // tirelessly for up to 12 hours per day',
    '    return 12;',
    '}',
    '',
    'inline int mmpStridingRechargeHours() {',
    '    // then no function for 12 hours (recharge)',
    '    return 12;',
    '}',
    '',
    'inline int mmpStridingNormalPaceFeet() {',
    '    // normal paces are 3 feet long',
    '    return 3;',
    '}',
    '',
    'inline int mmpStridingForwardJumpFeet() {',
    '    // forward jumps of up to 30 feet',
    '    return 30;',
    '}',
    '',
    'inline int mmpStridingBackwardLeapFeet() {',
    '    // backward leaps of 9 feet',
    '    return 9;',
    '}',
    '',
    'inline int mmpStridingVerticalSpringFeet() {',
    '    // vertical springs of 15 feet',
    '    return 15;',
    '}',
    '',
    'inline int mmpStridingStumbleBasePct() {',
    '    // base 20% stumble chance',
    '    return 20;',
    '}',
    '',
    'inline int mmpStridingStumbleDexAdjPct() {',
    '    // less 3% per point of dexterity above 12',
    '    return 3;',
    '}',
    '',
    'inline int mmpStridingStumbleDexThreshold() {',
    '    // the dexterity threshold',
    '    return 12;',
    '}',
    '',
    'inline int mmpStridingStumbleRowCount() {',
    '    // the dex ladder rows, 13 through 18',
    '    return 6;',
    '}',
    '',
    'inline int mmpStridingStumblePctByDex(int i) {',
    '    // row i = dexterity - 13; the stumble chance;',
    '    // i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        17, 14, 11, 8, 5, 2,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpStridingAcBonus() {',
    '    // increases armor class value by 1',
    '    return 1;',
    '}',
    '',
    '}  // namespace rules',
    '',
]
hdr_text = NL.join(hdr_lines) + NL

# ---- the include patch ----
inc_old = [
    '#include "rules/miscprose2.h"  // R258: the III.E misc magic explanation prose part 2 pins',
]
inc_new = [
    '#include "rules/miscprose2.h"  // R258: the III.E misc magic explanation prose part 2 pins',
    '#include "rules/miscprose3.h"  // R259: the III.E misc magic explanation prose part 3 pins',
]

# ---- the regtest audit block ----
audit_old = [
    '    // ---- R227: the wis mental save wiring audit ----',
]
audit_new = [
    '    // ---- R259: the III.E misc magic explanation prose part 3 pins audit ----',
    '    // part2 lines 67-108 - Book of Infinite Spells',
    '    // through Boots of Striding and Springing,',
    '    // global = 11065 + part2 line; the page headers',
    '    // at 70 and 102 stripped (the R249 lesson),',
    '    // the 102 seam splits the levitation paragraph',
    '    // mid-sentence, pinned exactly.',
    '    {',
    '        int bad = 0;',
    '        // the seven items are the engine kMisc1 rows',
    '        // 16-22 (the R225 m1 band pins); the Vile',
    '        // (C) class mark is row 17, the Infinite',
    '        // row 16 is the negative control',
    '        if (rules::m1RowCount() != 33) ++bad;',
    '        static const int kM1Lo[7] = {',
    '            34, 35, 36, 37, 43, 48, 52,',
    '        };',
    '        static const int kM1Hi[7] = {',
    '            34, 35, 36, 42, 47, 51, 55,',
    '        };',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::m1RowLo(16 + i) != kM1Lo[i] ||',
    '                rules::m1RowHi(16 + i) != kM1Hi[i]) ++bad;',
    '        if (rules::m1UsableByCleric(17) != 1 ||',
    '            rules::m1UsableByCleric(16) != 0) ++bad;',
    '        // the book of infinite spells',
    '        if (rules::mmpInfiniteFirstReadHpMin() != 5 ||',
    '            rules::mmpInfiniteFirstReadHpMax() != 20 ||',
    '            rules::mmpInfiniteFirstReadStunTurnsMin() != 5 ||',
    '            rules::mmpInfiniteFirstReadStunTurnsMax() != 20 ||',
    '            rules::mmpInfinitePageMin() != 23 ||',
    '            rules::mmpInfinitePageMax() != 30 ||',
    '            rules::mmpInfinitePageBase() != 22 ||',
    '            rules::mmpInfinitePageDieSides() != 8 ||',
    '            rules::mmpInfinitePageRowCount() != 5 ||',
    '            rules::mmpInfiniteLevelDieSides() != 10 ||',
    '            rules::mmpInfiniteMuLevelDieSides() != 12 ||',
    '            rules::mmpInfiniteLevelRerollLo() != 8 ||',
    '            rules::mmpInfiniteLevelRerollHi() != 10 ||',
    '            rules::mmpInfiniteMuLevelRerollLo() != 10 ||',
    '            rules::mmpInfiniteMuLevelRerollHi() != 12 ||',
    '            rules::mmpInfiniteRerollDieSides() != 6 ||',
    '            rules::mmpInfiniteMuRerollDieSides() != 8 ||',
    '            rules::mmpInfiniteVanishesAtLastPage() != 1 ||',
    '            rules::mmpInfiniteCastPerDay() != 1 ||',
    '            rules::mmpInfiniteCastPerDayIfKnown() != 4 ||',
    '            rules::mmpInfiniteTurnPctUsable() != 10 ||',
    '            rules::mmpInfiniteTurnPctForeign() != 20 ||',
    '            rules::mmpInfiniteTurnPctNonCasterCleric() != 25 ||',
    '            rules::mmpInfiniteTurnPctNonCasterMu() != 30) ++bad;',
    '        static const int kInfLo[5] = {',
    '            1, 31, 51, 61, 96,',
    '        };',
    '        static const int kInfHi[5] = {',
    '            30, 50, 60, 95, 100,',
    '        };',
    '        for (int i = 0; i < 5; ++i)',
    '            if (rules::mmpInfinitePageLo(i) != kInfLo[i] ||',
    '                rules::mmpInfinitePageHi(i) != kInfHi[i]) ++bad;',
    '        // the book of vile darkness',
    '        if (rules::mmpVileReadingWeeks() != 1 ||',
    '            rules::mmpVileWisdomGain() != 1 ||',
    '            rules::mmpVileHalfwayPct() != 50 ||',
    '            rules::mmpVileNeutralXpLossMin() != 30000 ||',
    '            rules::mmpVileNeutralXpLossMax() != 120000 ||',
    '            rules::mmpVileNeutralSplitPct() != 50 ||',
    '            rules::mmpVileGoodSaveCount() != 2 ||',
    '            rules::mmpVileGoodXpLossBase() != 250000 ||',
    '            rules::mmpVileGoodXpLossPerWis() != 10000 ||',
    '            rules::mmpVileGoodHandlingHpMin() != 5 ||',
    '            rules::mmpVileGoodHandlingHpMax() != 30 ||',
    '            rules::mmpVileNightHagPct() != 80 ||',
    '            rules::mmpVileNeutralHandlingHpMin() != 5 ||',
    '            rules::mmpVileNeutralHandlingHpMax() != 20) ++bad;',
    '        // the boots of dancing',
    '        if (rules::mmpDancingDisguisedBootTypeCount() != 4 ||',
    '            rules::mmpDancingTriggerCaseCount() != 2 ||',
    '            rules::mmpDancingAcPenalty() != 4 ||',
    '            rules::mmpDancingRemovalSpellCount() != 1) ++bad;',
    '        // the boots of elvenkind',
    '        if (rules::mmpElvenkindSilencePctWorst() != 95 ||',
    '            rules::mmpElvenkindSilencePctBest() != 100) ++bad;',
    '        // the boots of levitation (the 102 seam)',
    '        if (rules::mmpLevitationSpeedInchesPerRound() != 20 ||',
    '            rules::mmpLevitationWeightIncrementPounds() != 14 ||',
    '            rules::mmpLevitationWeightDieSides() != 20 ||',
    '            rules::mmpLevitationWeightBasePounds() != 280 ||',
    '            rules::mmpLevitationWeightMinPounds() != 294 ||',
    '            rules::mmpLevitationWeightMaxPounds() != 560) ++bad;',
    '        // the boots of speed',
    '        if (rules::mmpSpeedBaseMovementInches() != 24 ||',
    '            rules::mmpSpeedSlowPoundsPerInch() != 10 ||',
    '            rules::mmpSpeedFreeWeightPounds() != 200 ||',
    '            rules::mmpSpeedExampleHumanPounds() != 180 ||',
    '            rules::mmpSpeedExampleGearPounds() != 60 ||',
    '            rules::mmpSpeedExampleRateInches() != 20 ||',
    '            rules::mmpSpeedSackCoins() != 500 ||',
    '            rules::mmpSpeedSackSlowInches() != 5 ||',
    '            rules::mmpSpeedRestHoursPerMoveHour() != 1 ||',
    '            rules::mmpSpeedMaxContinuousHours() != 8 ||',
    '            rules::mmpSpeedAcBonus() != 2) ++bad;',
    '        // the boots of striding and springing',
    '        if (rules::mmpStridingBaseMovementInches() != 12 ||',
    '            rules::mmpStridingMaxHoursPerDay() != 12 ||',
    '            rules::mmpStridingRechargeHours() != 12 ||',
    '            rules::mmpStridingNormalPaceFeet() != 3 ||',
    '            rules::mmpStridingForwardJumpFeet() != 30 ||',
    '            rules::mmpStridingBackwardLeapFeet() != 9 ||',
    '            rules::mmpStridingVerticalSpringFeet() != 15 ||',
    '            rules::mmpStridingStumbleBasePct() != 20 ||',
    '            rules::mmpStridingStumbleDexAdjPct() != 3 ||',
    '            rules::mmpStridingStumbleDexThreshold() != 12 ||',
    '            rules::mmpStridingStumbleRowCount() != 6 ||',
    '            rules::mmpStridingAcBonus() != 1) ++bad;',
    '        static const int kStridingStumble[6] = {',
    '            17, 14, 11, 8, 5, 2,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpStridingStumblePctByDex(i) !=',
    '                    kStridingStumble[i]) ++bad;',
    '        printf("R259 misc magic prose part 3 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
    '    // ---- R227: the wis mental save wiring audit ----',
]

# ---- the dmg-gap-report log entry ----
gap_old = [
    '- Book of Infinite Spells onward',
    'in part2 from line 67 (global =',
    '11065 + part2 line; the TREASURE',
    'page header at line 70 splits',
    'its page table).',
]
gap_new = [
    '- Book of Infinite Spells onward',
    'in part2 from line 67 (global =',
    '11065 + part2 line; the TREASURE',
    'page header at line 70 splits',
    'its page table).',
    '',
    'R259 landed the III.E misc',
    'magic explanation prose part 3',
    '(part2 lines 67-108; global =',
    '11065 + part2 line). TWO page',
    'headers inside the slice, both',
    'stripped (the R249 lesson): line',
    '70 splits the page table from',
    'the Book of Infinite Spells',
    'intro, line 102 splits the Boots',
    'of Levitation paragraph',
    'mid-sentence - the seam pinned',
    'exactly (line 100 ends the',
    'ascent/descent speed phrase,',
    'line 104 continues ROUND',
    '(MINUTE); the stray table-title',
    'line 83 is a duplicated header,',
    'noted not pinned).',
    'rules/miscprose3.h (the mmp',
    'prefix again, 76 accessors: 73',
    'scalars + 3 array walkers): Book',
    'of Infinite Spells (5-20 hp,',
    '5-20 turns stunned on first',
    'read; 23-30 = 22 + d8 pages; the',
    '5-row page table; d10 level die,',
    'd12 for magic-user, 8-10 / 10-12',
    'reroll to d6 / d8; 1 cast per',
    'day, 4 if already castable; the',
    '10/20/25/30 page-turn ladder;',
    'vanishes at the last page), Book',
    'of Vile Darkness (1 week, +1',
    'wisdom halfway XP; neutral',
    '30,000-120,000 or turn evil, 50%',
    'either; good clerics 2 saves then',
    '250,000 less 10,000 per wisdom;',
    'other good 5-30 hp with 80% night',
    'hag; neutral 5-20 hp), Boots of',
    'Dancing (the other 4 useful types',
    'until melee or fleeing, AC',
    'penalty 4, remove curse only),',
    'Boots of Elvenkind (95% worst,',
    '100% best), Boots of Levitation',
    '(20 inches per round; d20 in 14',
    'pound increments over 280 base,',
    '294 to 560), Boots of Speed (24',
    'inch base, 1 inch per 10 pounds',
    'over 200, the 180/60 example at',
    '20, the 500 coin sack at 5, 1',
    'rest hour per move hour, 8 hours',
    'max, AC +2), Boots of Striding',
    'and Springing (12 inch base, 12',
    'hours + 12 recharge; 3 foot',
    'paces, 30/9/15 jumps; 20% stumble',
    'less 3% per dex above 12, the',
    '17/14/11/8/5/2 ladder; AC +1).',
    'ENGINE CROSS-CHECK: kMisc1 rows',
    '16-22 (Infinite 34, Vile 35,',
    'Dancing 36, Elvenkind 37-42,',
    'Levitation 43-47, Speed 48-51,',
    'Striding 52-55) plus the Vile',
    '(C) class mark at row 17',
    '(Infinite row 16 as the',
    'negative control) against the',
    'R225 m1 pins. New R259 battery',
    'audit; census 177. Next: part 4',
    '- Bowl Commanding Water',
    'Elementals onward in part2 from',
    'line 110 (global = 11065 +',
    'part2 line).',
]

applied = 0
already = 0

# the created-file patch (marker-based idempotence; the
# marker MUST be contiguous in the header text)
marker = 'R259: the III.E misc magic explanation prose part 3'
try:
    t = open(WD).read()
    if marker in t:
        already += 1
    else:
        print('R259 FAIL: rules/miscprose3.h exists without the marker')
        sys.exit(1)
except IOError:
    with open(WD, 'w') as f:
        f.write(hdr_text)
    applied += 1

for path, mark, old, new in [
    (REG, 'the regtest include', inc_old, inc_new),
    (REG, 'the R259 audit', audit_old, audit_new),
    (GAP, 'the R259 log entry', gap_old, gap_new),
]:
    with open(path) as f:
        text = f.read()
    old_s = NL.join(old)
    new_s = NL.join(new)
    # the idempotence signal is the NEW text
    if new_s in text:
        already += 1
        continue
    if text.count(old_s) == 1:
        text = text.replace(old_s, new_s)
        applied += 1
    else:
        print('R259 FAIL: anchor count is ' + str(text.count(old_s)) + ' for: ' + mark)
        sys.exit(1)
    with open(path, 'w') as f:
        f.write(text)

# post-conditions on the full pass
if applied + already == 4:
    t = open(REG).read()
    if t.count('audit: bad ') != 177:
        print('R259 FAIL: census is not 177')
        sys.exit(1)
    if t.count('R259 misc magic prose part 3 pins audit') != 1:
        print('R259 FAIL: the R259 audit line must appear once')
        sys.exit(1)
    if t.count('rules/miscprose3.h') != 1:
        print('R259 FAIL: the miscprose3 include must appear once')
        sys.exit(1)
    g = open(GAP).read()
    if g.count('R259 landed the III.E misc') != 1:
        print('R259 FAIL: the dmg log entry is missing')
        sys.exit(1)
    h = open(WD).read()
    if 'namespace rules' not in h or h.count('inline int mmp') != 76:
        print('R259 FAIL: the header shape is wrong')
        sys.exit(1)

print('R259 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R259 note: 4 patches; the III.E misc magic explanation prose')
print('part 3 - Book of Infinite Spells through Boots of Striding')
print('and Springing, part2 lines 67-108; census 177.')
print('commit: R259: the III.E misc magic explanation prose part 3 pinned - Book of Infinite Spells through Boots of Striding and Springing in part2 lines 67-108 (census 177)')

