#!/usr/bin/env python3
# R261 splice: the III.E misc magic explanation prose
# part 5 pins - Candle of Invocation through Cloak of
# Protection, part2 lines 155-220 (DMG p.132) - the
# slice completing the kMisc2 rows 0-10. THREE page
# headers strip (155, 159, 183); TWO seams pin (the
# Candle 157/161, the Displacement 180/185). 4
# patches, marker-based idempotence, assert after
# every patch. ZERO apostrophes and ZERO literal
# backslashes in the content below (the printf
# newline is built via BS = chr(92)).

import os
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

# ---- patch 1: rules/miscprose5.h ----
HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose5.h',
    '// R261: the III.E misc magic explanation prose part 5',
    '// (DMG p.132) - Candle of Invocation through Cloak',
    '// of Protection, part2 lines 155-220 (global =',
    '// 11065 + part2 line). THREE page headers strip',
    '// (155 TABLE (III.E.) 2., 159 and 183 both the',
    '// TREASURE page); TWO seams pin exactly: the Candle',
    '// (line 157 ends one of the, line 161 continues',
    '// nine alignments) and the Cloak of Displacement',
    '// (line 180 ends with such as spells,, line 185',
    '// continues gaze weapon attacks). 60 accessors:',
    '// 50 scalars + 10 array walkers, no name',
    '// collisions with miscprose1.h through',
    '// miscprose4.h. The slice completes kMisc2 rows',
    '// 0-10; the per-plus asterisk sits on row 10',
    '// (Cloak of Protection 33-55) - the R226 pin is',
    '// correct, no R260-style off-by-one.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpCandleAlignments() {',
    '    // one candle per alignment',
    '    return 9;',
    '}',
    '',
    'inline int mmpCandleClericLevelBoost() {',
    '    // same-alignment cleric level, while aflame',
    '    return 2;',
    '}',
    '',
    'inline int mmpCandleBurnHours() {',
    '    // each candle burns for 4 hours',
    '    return 4;',
    '}',
    '',
    'inline int mmpCandleGateSpell() {',
    '    // any burning allows a gate; taper consumed',
    '    return 1;',
    '}',
    '',
    'inline int mmpCarpetRowCount() {',
    '    // the random carpet table rows',
    '    return 4;',
    '}',
    '',
    'inline int mmpCenserAirHd() {',
    '    // the summoned air elemental',
    '    return 12;',
    '}',
    '',
    'inline int mmpCenserAirMedBonusPerDie() {',
    '    // incense of meditation: +3 per die',
    '    return 3;',
    '}',
    '',
    'inline int mmpCenserAirWidthInches() {',
    '    // the half-foot-wide vessel',
    '    return 6;',
    '}',
    '',
    'inline int mmpCenserAirHeightInches() {',
    '    // the 1-foot-high vessel',
    '    return 12;',
    '}',
    '',
    'inline int mmpCenserAirTurnsIfExtinguished() {',
    '    // extinguished: elemental remains, turns hostile',
    '    return 1;',
    '}',
    '',
    'inline int mmpCenserHostileMin() {',
    '    // enraged elementals, minimum',
    '    return 1;',
    '}',
    '',
    'inline int mmpCenserHostileMax() {',
    '    // enraged elementals, maximum',
    '    return 4;',
    '}',
    '',
    'inline int mmpCenserHostilePerRound() {',
    '    // elementals appear 1 per round',
    '    return 1;',
    '}',
    '',
    'inline int mmpChimeOpenLengthInches() {',
    '    // the hollow mithral tube',
    '    return 12;',
    '}',
    '',
    'inline int mmpChimeOpenWizardLockLevel() {',
    '    // defeats locks cast below 15th level',
    '    return 15;',
    '}',
    '',
    'inline int mmpChimeOpenRoundPerFunction() {',
    '    // one function completes per round',
    '    return 1;',
    '}',
    '',
    'inline int mmpChimeOpenSoundingsMin() {',
    '    // the fully chained and locked chest',
    '    return 4;',
    '}',
    '',
    'inline int mmpChimeOpenSoundingsMax() {',
    '    // the fully chained and locked chest',
    '    return 5;',
    '}',
    '',
    'inline int mmpChimeOpenChargesMin() {',
    '    // 20-80 charges, 20 + d6 x 10',
    '    return 20;',
    '}',
    '',
    'inline int mmpChimeOpenChargesMax() {',
    '    // 20-80 charges, 20 + d6 x 10',
    '    return 80;',
    '}',
    '',
    'inline int mmpChimeOpenChargesDieSides() {',
    '    // 20 + d6 x 10',
    '    return 6;',
    '}',
    '',
    'inline int mmpChimeOpenChargesDieMult() {',
    '    // 20 + d6 x 10',
    '    return 10;',
    '}',
    '',
    'inline int mmpChimeHungerRadiusInches() {',
    '    // ravenous hunger radius',
    '    return 6;',
    '}',
    '',
    'inline int mmpChimeHungerMinEatRounds() {',
    '    // must eat at least 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpDisplacementMinFeet() {',
    '    // apparent offset, minimum',
    '    return 1;',
    '}',
    '',
    'inline int mmpDisplacementMaxFeet() {',
    '    // apparent offset, maximum',
    '    return 2;',
    '}',
    '',
    'inline int mmpDisplacementAcBonus() {',
    '    // 2 classes better, after the first attack',
    '    return 2;',
    '}',
    '',
    'inline int mmpDisplacementSaveBonus() {',
    '    // saving throw dice bonus',
    '    return 2;',
    '}',
    '',
    'inline int mmpDisplacementHumanoidPct() {',
    '    // sized for humans or elves',
    '    return 75;',
    '}',
    '',
    'inline int mmpDisplacementSmallPct() {',
    '    // sized for 4-foot persons',
    '    return 25;',
    '}',
    '',
    'inline int mmpElvenkindRowCount() {',
    '    // the invisibility table rows',
    '    return 9;',
    '}',
    '',
    'inline int mmpElvenkindOutdoorNaturalRows() {',
    '    // heavy growth, light growth, open fields',
    '    return 3;',
    '}',
    '',
    'inline int mmpElvenkindOutdoorOtherRows() {',
    '    // rocky terrain, buildings, bright room',
    '    return 3;',
    '}',
    '',
    'inline int mmpElvenkindUndergroundRows() {',
    '    // torch, infravision, light',
    '    return 3;',
    '}',
    '',
    'inline int mmpElvenkindHumanoidPct() {',
    '    // human to elven sized cloaks',
    '    return 90;',
    '}',
    '',
    'inline int mmpElvenkindSmallPct() {',
    '    // smaller persons, about 4 feet',
    '    return 10;',
    '}',
    '',
    'inline int mmpMantaRayLikenessPct() {',
    '    // identical to a manta ray in salt water',
    '    return 90;',
    '}',
    '',
    'inline int mmpMantaRayMoveInches() {',
    '    // moves as a manta ray',
    '    return 18;',
    '}',
    '',
    'inline int mmpMantaRayAc() {',
    '    // armor class of at least 6',
    '    return 6;',
    '}',
    '',
    'inline int mmpMantaRayTailDmgMin() {',
    '    // tail spine damage',
    '    return 1;',
    '}',
    '',
    'inline int mmpMantaRayTailDmgMax() {',
    '    // tail spine damage',
    '    return 6;',
    '}',
    '',
    'inline int mmpMantaRayTailStun() {',
    '    // no chance of stunning',
    '    return 0;',
    '}',
    '',
    'inline int mmpMantaRaySaltWaterTrigger() {',
    '    // the cloak adheres in salt water',
    '    return 1;',
    '}',
    '',
    'inline int mmpPoisonCloakRevivalPctPenalty() {',
    '    // raise dead chance penalty',
    '    return 10;',
    '}',
    '',
    'inline int mmpPoisonCloakRemoveCurseDestroys() {',
    '    // remove curse removes and destroys the magic',
    '    return 1;',
    '}',
    '',
    'inline int mmpPoisonCloakNeutralizeNoEffect() {',
    '    // neutralize poison does not affect it',
    '    return 1;',
    '}',
    '',
    'inline int mmpCloakProtRowCount() {',
    '    // the random plus table rows',
    '    return 5;',
    '}',
    '',
    'inline int mmpCloakProtAcPerPlus() {',
    '    // armor class better per plus',
    '    return 1;',
    '}',
    '',
    'inline int mmpCloakProtSavePerPlus() {',
    '    // saving throw added per plus',
    '    return 1;',
    '}',
    '',
    'inline int mmpCloakProtExampleBaseAc() {',
    '    // the +1 example: AC 10 becomes 9',
    '    return 10;',
    '}',
    '',
    'inline int mmpCarpetBandLo(int i) {',
    '    // the carpet band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 21, 56, 81,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCarpetBandHi(int i) {',
    '    // the carpet band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        20, 55, 80, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCarpetWidthFeet(int i) {',
    '    // the carpet width; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        3, 4, 5, 6,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCarpetLengthFeet(int i) {',
    '    // the carpet length; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        5, 6, 7, 9,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCarpetPersons(int i) {',
    '    // the carpet capacity; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 2, 3, 4,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCarpetSpeedInches(int i) {',
    '    // the carpet speed; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        42, 36, 30, 24,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpElvenkindInvisibilityPct(int i) {',
    '    // invisibility per setting; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 8) i = 8;',
    '    static const int t[9] = {',
    '        100, 99, 95, 98, 90, 50, 95, 90, 50,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCloakProtBandLo(int i) {',
    '    // the plus band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 4) i = 4;',
    '    static const int t[5] = {',
    '        1, 36, 66, 86, 96,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCloakProtBandHi(int i) {',
    '    // the plus band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 4) i = 4;',
    '    static const int t[5] = {',
    '        35, 65, 85, 95, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCloakProtPlus(int i) {',
    '    // the cloak plus per band; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 4) i = 4;',
    '    static const int t[5] = {',
    '        1, 2, 3, 4, 5,',
    '    };',
    '    return t[i];',
    '}',
    '',
    '} // namespace rules',
    '',
]
P1 = 'rules/miscprose5.h'
if os.path.exists(os.path.join(ROOT, P1)):
    already += 1
    assert rd(P1) == NL.join(HDR), P1 + ' exists but differs'
else:
    wr(P1, NL.join(HDR))
    applied += 1
    assert rd(P1) == NL.join(HDR), P1 + ' write mismatch'
assert rd(P1).count(
    'R261: the III.E misc magic explanation prose part 5') == 1

# ---- patch 2: the regtest include ----
INC_OLD = ('#include "rules/miscprose4.h"  // R260: the III.E misc'
           ' magic explanation prose part 4 pins')
INC_NEW = ('#include "rules/miscprose5.h"  // R261: the III.E misc'
           ' magic explanation prose part 5 pins')
RG = rd('regtest.cpp')
if INC_NEW in RG:
    already += 1
    assert RG.count(INC_NEW) == 1, 'include not unique'
else:
    assert RG.count(INC_OLD) == 1, 'R260 include anchor missing'
    RG = RG.replace(INC_OLD, INC_OLD + NL + INC_NEW)
    applied += 1
    assert RG.count(INC_NEW) == 1, 'include insert failed'
wr('regtest.cpp', RG)

# ---- patch 3: the R261 audit block ----
AUDIT = [
    '    // ---- R261: the III.E misc magic explanation',
    '    // prose part 5 ----',
    '    // Candle of Invocation through Cloak of',
    '    // Protection, part2 lines 155-220 - the prose',
    '    // pins, completing the kMisc2 rows 0-10. The',
    '    // R226 per-plus asterisk pin verified correct',
    '    // (row 10, 33-55), no off-by-one.',
    '    {',
    '        int bad = 0;',
    '        if (rules::mmpCandleAlignments() != 9 ||',
    '            rules::mmpCandleClericLevelBoost() != 2 ||',
    '            rules::mmpCandleBurnHours() != 4 ||',
    '            rules::mmpCandleGateSpell() != 1) ++bad;',
    '        if (rules::mmpCarpetRowCount() != 4 ||',
    '            rules::mmpCenserAirHd() != 12 ||',
    '            rules::mmpCenserAirMedBonusPerDie() != 3 ||',
    '            rules::mmpCenserAirWidthInches() != 6 ||',
    '            rules::mmpCenserAirHeightInches() != 12 ||',
    '            rules::mmpCenserAirTurnsIfExtinguished() != 1) ++bad;',
    '        if (rules::mmpCenserHostileMin() != 1 ||',
    '            rules::mmpCenserHostileMax() != 4 ||',
    '            rules::mmpCenserHostilePerRound() != 1) ++bad;',
    '        if (rules::mmpChimeOpenLengthInches() != 12 ||',
    '            rules::mmpChimeOpenWizardLockLevel() != 15 ||',
    '            rules::mmpChimeOpenRoundPerFunction() != 1 ||',
    '            rules::mmpChimeOpenSoundingsMin() != 4 ||',
    '            rules::mmpChimeOpenSoundingsMax() != 5 ||',
    '            rules::mmpChimeOpenChargesMin() != 20 ||',
    '            rules::mmpChimeOpenChargesMax() != 80 ||',
    '            rules::mmpChimeOpenChargesDieSides() != 6 ||',
    '            rules::mmpChimeOpenChargesDieMult() != 10) ++bad;',
    '        if (rules::mmpChimeHungerRadiusInches() != 6 ||',
    '            rules::mmpChimeHungerMinEatRounds() != 1) ++bad;',
    '        if (rules::mmpDisplacementMinFeet() != 1 ||',
    '            rules::mmpDisplacementMaxFeet() != 2 ||',
    '            rules::mmpDisplacementAcBonus() != 2 ||',
    '            rules::mmpDisplacementSaveBonus() != 2 ||',
    '            rules::mmpDisplacementHumanoidPct() != 75 ||',
    '            rules::mmpDisplacementSmallPct() != 25) ++bad;',
    '        if (rules::mmpElvenkindRowCount() != 9 ||',
    '            rules::mmpElvenkindOutdoorNaturalRows() != 3 ||',
    '            rules::mmpElvenkindOutdoorOtherRows() != 3 ||',
    '            rules::mmpElvenkindUndergroundRows() != 3 ||',
    '            rules::mmpElvenkindHumanoidPct() != 90 ||',
    '            rules::mmpElvenkindSmallPct() != 10) ++bad;',
    '        if (rules::mmpMantaRayLikenessPct() != 90 ||',
    '            rules::mmpMantaRayMoveInches() != 18 ||',
    '            rules::mmpMantaRayAc() != 6 ||',
    '            rules::mmpMantaRayTailDmgMin() != 1 ||',
    '            rules::mmpMantaRayTailDmgMax() != 6 ||',
    '            rules::mmpMantaRayTailStun() != 0 ||',
    '            rules::mmpMantaRaySaltWaterTrigger() != 1) ++bad;',
    '        if (rules::mmpPoisonCloakRevivalPctPenalty() != 10 ||',
    '            rules::mmpPoisonCloakRemoveCurseDestroys() != 1 ||',
    '            rules::mmpPoisonCloakNeutralizeNoEffect() != 1) ++bad;',
    '        if (rules::mmpCloakProtRowCount() != 5 ||',
    '            rules::mmpCloakProtAcPerPlus() != 1 ||',
    '            rules::mmpCloakProtSavePerPlus() != 1 ||',
    '            rules::mmpCloakProtExampleBaseAc() != 10) ++bad;',
    '        static const int kCarpetLo[4] = {',
    '            1, 21, 56, 81,',
    '        };',
    '        static const int kCarpetHi[4] = {',
    '            20, 55, 80, 100,',
    '        };',
    '        static const int kCarpetWidth[4] = {',
    '            3, 4, 5, 6,',
    '        };',
    '        static const int kCarpetLength[4] = {',
    '            5, 6, 7, 9,',
    '        };',
    '        static const int kCarpetPersons[4] = {',
    '            1, 2, 3, 4,',
    '        };',
    '        static const int kCarpetSpeed[4] = {',
    '            42, 36, 30, 24,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpCarpetBandLo(i) != kCarpetLo[i] ||',
    '                rules::mmpCarpetBandHi(i) != kCarpetHi[i] ||',
    '                rules::mmpCarpetWidthFeet(i) != kCarpetWidth[i] ||',
    '                rules::mmpCarpetLengthFeet(i) != kCarpetLength[i] ||',
    '                rules::mmpCarpetPersons(i) != kCarpetPersons[i] ||',
    '                rules::mmpCarpetSpeedInches(i) != kCarpetSpeed[i]) ++bad;',
    '        static const int kElvenkindPct[9] = {',
    '            100, 99, 95, 98, 90, 50, 95, 90, 50,',
    '        };',
    '        for (int i = 0; i < 9; ++i)',
    '            if (rules::mmpElvenkindInvisibilityPct(i) !=',
    '                    kElvenkindPct[i]) ++bad;',
    '        static const int kCloakProtLo[5] = {',
    '            1, 36, 66, 86, 96,',
    '        };',
    '        static const int kCloakProtHi[5] = {',
    '            35, 65, 85, 95, 100,',
    '        };',
    '        static const int kCloakProtPlus[5] = {',
    '            1, 2, 3, 4, 5,',
    '        };',
    '        for (int i = 0; i < 5; ++i)',
    '            if (rules::mmpCloakProtBandLo(i) != kCloakProtLo[i] ||',
    '                rules::mmpCloakProtBandHi(i) != kCloakProtHi[i] ||',
    '                rules::mmpCloakProtPlus(i) !=',
    '                    kCloakProtPlus[i]) ++bad;',
    '        static const int kM2Lo[11] = {',
    '            1, 7, 9, 11, 12, 14, 15, 19, 28, 31, 33,',
    '        };',
    '        static const int kM2Hi[11] = {',
    '            6, 8, 10, 11, 13, 14, 18, 27, 30, 32, 55,',
    '        };',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::m2RowLo(i) != kM2Lo[i] ||',
    '                rules::m2RowHi(i) != kM2Hi[i]) ++bad;',
    '        // the class marks: the Candle is (C); the',
    '        // two Censers are (M); the Carpet row 1',
    '        // is the negative control',
    '        if (!rules::m2UsableByCleric(0) ||',
    '            rules::m2UsableByCleric(1)) ++bad;',
    '        if (!rules::m2UsableByMagicUser(2) ||',
    '            !rules::m2UsableByMagicUser(3) ||',
    '            rules::m2UsableByMagicUser(1) ||',
    '            rules::m2UsableByMagicUser(10)) ++bad;',
    '        // the per-plus asterisk: row 10 (33-55),',
    '        // the R226 pin verified correct',
    '        if (!rules::m2IsPerPlusValued(10) ||',
    '            rules::m2IsPerPlusValued(9) ||',
    '            rules::m2IsPerPlusValued(11)) ++bad;',
    '        // the printed +2 cloak: 1000 xp / 10000 gp',
    '        // per plus = 2000 / 20000, cross-pinned',
    '        // against the prose plus table',
    '        if (rules::mmpCloakProtPlus(1) != 2 ||',
    '            rules::m2CloakPerPlusXp() *',
    '                rules::mmpCloakProtPlus(1) != 2000 ||',
    '            rules::m2CloakPerPlusGp() *',
    '                rules::mmpCloakProtPlus(1) != 20000) ++bad;',
    '        printf("R261 misc magic prose part 5 pins audit:'
    ' bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]
RG = rd('regtest.cpp')
ANCHOR = ('    // ---- R227: the wis mental save wiring audit ----')
AUDIT_STR = NL.join(AUDIT)
if ('printf("R261 misc magic prose part 5 pins audit:') in RG:
    already += 1
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
else:
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
    RG = RG.replace(ANCHOR, AUDIT_STR + NL + ANCHOR)
    applied += 1
    assert RG.count(
        'printf("R261 misc magic prose part 5 pins audit:') == 1, \
        'audit printf not unique'
wr('regtest.cpp', RG)

# ---- patch 4: the gap entry ----
GAP = [
    'R261 landed the III.E misc',
    'magic explanation prose part',
    '5 (part2 lines 155-220;',
    'global = 11065 + part2',
    'line), Candle of Invocation',
    'through Cloak of Protection -',
    'completing the kMisc2 rows',
    '0-10. THREE page headers',
    'inside the slice, all',
    'stripped (the R249 lesson):',
    '155 (TABLE (III.E.) 2.),',
    '159 and 183 (both TREASURE).',
    'TWO seams pinned exactly:',
    'the Candle (line 157 ends one',
    'of the, line 161 continues',
    'nine alignments) and the',
    'Cloak of Displacement (line',
    '180 ends with such as',
    'spells,, line 185 continues',
    'gaze weapon attacks).',
    'rules/miscprose5.h (the mmp',
    'prefix again, 60 accessors:',
    '50 scalars + 10 array',
    'walkers, no name collisions',
    'with parts 1-4): Candle of',
    'Invocation (nine alignments;',
    'cleric level +2 while',
    'aflame; any burning casts a',
    'gate, taper consumed; 4',
    'hour burn), Carpet of',
    'Flying (the 4-row table',
    '01-20 3x5 1 person 42',
    'through 81-00 6x9 4 persons',
    '24; command word, voice',
    'range; repairs only in the',
    'East), Censer Controlling',
    'Air Elementals (12 HD next',
    'round; incense of meditation',
    '+3 per die and obeys;',
    'extinguished turns on the',
    'summoner; half foot wide, 1',
    'foot high), Censer of',
    'Summoning Hostile Air',
    'Elementals (cursed; 1-4',
    'enraged elementals, 1 per',
    'round; burns until the',
    'summoner or elementals die),',
    'Chime of Opening (mithral',
    'tube 1 foot; defeats hold',
    'portal and wizard lock below',
    '15th level; 1 round per',
    'function; the chained and',
    'locked chest 4-5 soundings;',
    'silence negates; 20-80',
    'charges, 20 + d6 x 10),',
    'Chime of Hunger (6 inch',
    'radius; eat at least 1',
    'round, save each round',
    'after; mirrors a chime of',
    'opening first), Cloak of',
    'Displacement (1-2 foot',
    'offset; first attack auto',
    'miss; then +2 AC and +2',
    'saves; 75% human/elven',
    'sized, 25% small), Cloak of',
    'Elvenkind (the 9-row',
    'invisibility table: heavy',
    'growth 100, light growth 99,',
    'open fields 95, rocky 98,',
    'buildings 90, bright room',
    '50, torch 95, infravision',
    '90, light 50; 90% human or',
    'elven sized, 10% small),',
    'Cloak of the Manta Ray',
    '(salt water trigger; 90%',
    'manta likeness; breathe',
    'underwater; move 18; AC at',
    'least 6; tail spine 1-6, no',
    'stun; arms free), Cloak of',
    'Poisonousness (handled',
    'safely; neutralize poison no',
    'effect; worn is stone dead;',
    'remove curse destroys the',
    'magic, then neutralize plus',
    'raise dead at minus 10%),',
    'Cloak of Protection (the',
    '5-row plus table 01-35 +1',
    'through 96-00 +5; +1 AC and',
    '+1 save per plus; the +1',
    'example AC 10 to 9; stacks',
    'with items and leather only,',
    'never magical armor, other',
    'armor, or shields). ENGINE',
    'CROSS-CHECK: kMisc2 rows',
    '0-10 (Candle 1-6, Carpet',
    '7-8, Censer Air 9-10, Censer',
    'Hostile 11, Chime Open',
    '12-13, Chime Hunger 14,',
    'Displacement 15-18,',
    'Elvenkind 19-27, Manta',
    '28-30, Poisonous 31-32,',
    'Protection 33-55) plus the',
    '(C) mark on the Candle and',
    'the (M) marks on the two',
    'Censers, and the per-plus',
    'asterisk on row 10 -',
    'VERIFIED CORRECT, no',
    'R260-style off-by-one (the',
    'R226 pin already sat on row',
    '10). The R261 audit',
    'cross-pins the +2 cloak',
    'example (1000 xp / 10000 gp',
    'per plus -> 2000 / 20000).',
    'New R261 battery audit;',
    'census 179. Next: part 6 -',
    'Crystal Ball onward in',
    'part2 from line 222 (global',
    '11287; the Crystal Ball',
    'locating chance table and',
    'the Crystal Hypnosis Ball',
    'follow; the double-asterisk',
    'feature row 56-60 is',
    'R226-pinned).',
]
GP = rd('tools/dmg_gap_report.md')
if GP.count('R261 landed the III.E misc') == 1:
    already += 1
else:
    TAIL = ('the, line 161 continues' + NL + 'nine alignments).' + NL +
            NL + 'Categories:')
    assert GP.count(TAIL) == 1, 'R260 gap tail anchor not unique'
    NEWTAIL = ('the, line 161 continues' + NL + 'nine alignments).' +
               NL + NL + NL.join(GAP) + NL + NL + 'Categories:')
    GP = GP.replace(TAIL, NEWTAIL)
    applied += 1
    assert GP.count('R261 landed the III.E misc') == 1, \
        'gap entry insert failed'
wr('tools/dmg_gap_report.md', GP)

# ---- report ----
assert applied + already == 4, 'patch count wrong'
print('R261 splice: ALL OK (applied %d, already %d)'
      % (applied, already))
print('R261 note: 4 patches; the III.E misc magic')
print('explanation prose part 5 - Candle of Invocation')
print('through Cloak of Protection, part2 lines')
print('155-220; census 179.')
COMMIT = ('R261: the III.E misc magic explanation prose part 5'
          ' pinned - Candle of Invocation through Cloak of'
          ' Protection in part2 lines 155-220 (census 179)')
print('commit: ' + COMMIT)

