#!/usr/bin/env python3
# R262 splice: the III.E misc magic explanation prose
# part 6 pins - Crystal Ball and Crystal Hypnosis
# Ball, part2 lines 222-283 (DMG p.132) - the slice
# completing the kMisc2 rows 11-12. ONE page header
# strips (279, the TREASURE page). 4 patches,
# marker-based idempotence, assert after every
# patch. ZERO apostrophes and ZERO literal
# backslashes in the content below (the printf
# newline is built via BS = chr(92)).

import os
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

# ---- patch 1: rules/miscprose6.h ----
HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose6.h',
    '// R262: the III.E misc magic explanation prose part 6',
    '// (DMG p.132) - Crystal Ball and Crystal Hypnosis',
    '// Ball, part2 lines 222-283 (global = 11065 + part2',
    '// line). ONE page header strips (279, the TREASURE',
    '// page). The slice is table-dense: the locating',
    '// chance table, the viewing period table, the',
    '// additional powers table and the notice-by-class',
    '// table all pin. 45 accessors: 36 scalars + 9',
    '// array walkers, no name collisions with',
    '// miscprose1.h through miscprose5.h. The slice',
    '// completes kMisc2 rows 11-12; the double',
    '// asterisk sits on row 11 (Crystal Ball 56-60) -',
    '// the R226 pin is correct. The Crystal Hypnosis',
    '// Ball is prose-only: three influencer kinds,',
    '// three fates, referee picks the pace.',
    '// Pure data + helpers, header-only (the',
    '// grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpCrystalBallDiameterInches() {',
    '    // a crystal sphere, half a foot across',
    '    return 6;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingRowCount() {',
    '    // the subject-is table rows',
    '    return 8;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingWellKnownPct() {',
    '    // personally well known',
    '    return 100;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingKnownSlightlyPct() {',
    '    // personally known slightly',
    '    return 85;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingPicturedPct() {',
    '    // pictured',
    '    return 50;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingPartPct() {',
    '    // part of in possession',
    '    return 50;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingGarmentPct() {',
    '    // garment in possession',
    '    return 25;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingWellInformedPct() {',
    '    // well informed of',
    '    return 25;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingSlightlyInformedPct() {',
    '    // slightly informed of',
    '    return 20;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingOtherPlanePct() {',
    '    // on another plane: a minus',
    '    return -25;',
    '}',
    '',
    'inline int mmpCrystalBallViewingRowCount() {',
    '    // the viewing period table rows',
    '    return 6;',
    '}',
    '',
    'inline int mmpCrystalBallOverrunIntLoss() {',
    '    // past the limits, failed save: int down',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallOverrunInsaneUntilHealed() {',
    '    // driven insane until healed',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallImprovingSpellCount() {',
    '    // comprehend languages, read magic,',
    '    // infravision, tongues',
    '    return 4;',
    '}',
    '',
    'inline int mmpCrystalBallCastThroughSpellCount() {',
    '    // detect magic, detect evil per good',
    '    return 2;',
    '}',
    '',
    'inline int mmpCrystalBallCastThroughChancePerLevelPct() {',
    '    // cast through the ball, per level',
    '    return 5;',
    '}',
    '',
    'inline int mmpCrystalBallFeatureRowCount() {',
    '    // the additional powers table rows',
    '    return 4;',
    '}',
    '',
    'inline int mmpCrystalBallSpellFunctionLevel() {',
    '    // the spell function operates at',
    '    return 10;',
    '}',
    '',
    'inline int mmpCrystalBallNoticeMinInt() {',
    '    // creatures of int 12 or better notice',
    '    return 12;',
    '}',
    '',
    'inline int mmpCrystalBallDetectClassCount() {',
    '    // the notice-by-class table entries',
    '    return 7;',
    '}',
    '',
    'inline int mmpCrystalBallIntFactorCount() {',
    '    // int 13 through 18, one rung each',
    '    return 6;',
    '}',
    '',
    'inline int mmpCrystalBallDetectPerLevelPct() {',
    '    // cumulative chance per level of experience',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallDetectionTablePage() {',
    '    // spell-users: the detection table page',
    '    return 60;',
    '}',
    '',
    'inline int mmpCrystalBallDispelDownDays() {',
    '    // dispel magic: ceases functioning for',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallCheckPerRound() {',
    '    // scrying detection checks each round',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallSpellUserClassCount() {',
    '    // cleric, druid, magic-user, illusionist',
    '    return 4;',
    '}',
    '',
    'inline int mmpCrystalBallClericDevicesAllowed() {',
    '    // the note: clerics and druids may scry',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallKnowledgeNotDistance() {',
    '    // knowledge is the key, not distance',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallTelepathyCommunicationOnly() {',
    '    // the telepathy ball footnote',
    '    return 1;',
    '}',
    '',
    'inline int mmpHypnosisBallCursed() {',
    '    // the cursed item type',
    '    return 1;',
    '}',
    '',
    'inline int mmpHypnosisBallRadiatesEvil() {',
    '    // radiates magic, but NOT evil',
    '    return 0;',
    '}',
    '',
    'inline int mmpHypnosisBallSuggestionImplanted() {',
    '    // hypnotized, telepathic suggestion implanted',
    '    return 1;',
    '}',
    '',
    'inline int mmpHypnosisBallIndistinguishable() {',
    '    // indistinguishable from a normal ball',
    '    return 1;',
    '}',
    '',
    'inline int mmpHypnosisBallInfluencerKindCount() {',
    '    // magic-user, lich, other-planar power',
    '    return 3;',
    '}',
    '',
    'inline int mmpHypnosisBallFateCount() {',
    '    // servant, tool, or possession object',
    '    return 3;',
    '}',
    '',
    'inline int mmpHypnosisBallRefereePace() {',
    '    // gradual or sudden, referee decides',
    '    return 1;',
    '}',
    '',
    'inline int mmpCrystalBallLocatingPct(int i) {',
    '    // the locating chance; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 7) i = 7;',
    '    static const int t[8] = {',
    '        100, 85, 50, 50, 25, 25, 20, -25,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallViewingMinutes(int i) {',
    '    // the viewing period, in minutes; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        60, 30, 30, 30, 15, 10,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallViewingTimesPerDay(int i) {',
    '    // the daily frequency; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        3, 3, 2, 1, 1, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallViewingBandHiPct(int i) {',
    '    // the band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        100, 99, 89, 74, 49, 24,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallFeatureBandLo(int i) {',
    '    // the additional powers band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 51, 76, 91,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallFeatureBandHi(int i) {',
    '    // the band upper edges, 91-00 is 100; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        50, 75, 90, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallFeatureCountAt(int i) {',
    '    // the additional feature count per band; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        0, 1, 2, 3,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallDetectBasePct(int i) {',
    '    // Fighter, Thief, Paladin, Assassin, Ranger,',
    '    // Monk, Bard - the printed table order; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        2, 6, 6, 5, 4, 1, 3,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpCrystalBallIntFactorPct(int i) {',
    '    // the cumulative int ladder at int 13-18; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        1, 3, 6, 10, 15, 21,',
    '    };',
    '    return t[i];',
    '}',
    '',
    '} // namespace rules',
]
P1 = 'rules/miscprose6.h'
if os.path.exists(os.path.join(ROOT, P1)):
    already += 1
    assert rd(P1) == NL.join(HDR), P1 + ' exists but differs'
else:
    wr(P1, NL.join(HDR))
    applied += 1
    assert rd(P1) == NL.join(HDR), P1 + ' write mismatch'
assert rd(P1).count(
    'R262: the III.E misc magic explanation prose part 6') == 1

# ---- patch 2: the regtest include ----
INC_OLD = ('#include "rules/miscprose5.h"  // R261: the III.E misc'
           ' magic explanation prose part 5 pins')
INC_NEW = ('#include "rules/miscprose6.h"  // R262: the III.E misc'
           ' magic explanation prose part 6 pins')
RG = rd('regtest.cpp')
if INC_NEW in RG:
    already += 1
    assert RG.count(INC_NEW) == 1, 'include not unique'
else:
    assert RG.count(INC_OLD) == 1, 'R261 include anchor missing'
    RG = RG.replace(INC_OLD, INC_OLD + NL + INC_NEW)
    applied += 1
    assert RG.count(INC_NEW) == 1, 'include insert failed'
wr('regtest.cpp', RG)

# ---- patch 3: the R262 audit block ----
AUDIT = [
    '    // ---- R262: the III.E misc magic explanation',
    '    // prose part 6 ----',
    '    // Crystal Ball and Crystal Hypnosis Ball,',
    '    // part2 lines 222-283 - the prose pins,',
    '    // completing the kMisc2 rows 11-12. The R226',
    '    // double-asterisk pin verified correct',
    '    // (row 11, 56-60), no off-by-one.',
    '    {',
    '        int bad = 0;',
    '        if (rules::mmpCrystalBallDiameterInches() != 6 ||',
    '            rules::mmpCrystalBallLocatingRowCount() != 8 ||',
    '            rules::mmpCrystalBallViewingRowCount() != 6 ||',
    '            rules::mmpCrystalBallFeatureRowCount() != 4 ||',
    '            rules::mmpCrystalBallDetectClassCount() != 7 ||',
    '            rules::mmpCrystalBallIntFactorCount() != 6) ++bad;',
    '        if (rules::mmpCrystalBallLocatingWellKnownPct() != 100 ||',
    '            rules::mmpCrystalBallLocatingKnownSlightlyPct() != 85 ||',
    '            rules::mmpCrystalBallLocatingPicturedPct() != 50 ||',
    '            rules::mmpCrystalBallLocatingPartPct() != 50 ||',
    '            rules::mmpCrystalBallLocatingGarmentPct() != 25 ||',
    '            rules::mmpCrystalBallLocatingWellInformedPct() != 25 ||',
    '            rules::mmpCrystalBallLocatingSlightlyInformedPct() != 20 ||',
    '            rules::mmpCrystalBallLocatingOtherPlanePct() != -25) ++bad;',
    '        if (rules::mmpCrystalBallOverrunIntLoss() != 1 ||',
    '            rules::mmpCrystalBallOverrunInsaneUntilHealed() != 1 ||',
    '            rules::mmpCrystalBallImprovingSpellCount() != 4 ||',
    '            rules::mmpCrystalBallCastThroughSpellCount() != 2 ||',
    '            rules::mmpCrystalBallCastThroughChancePerLevelPct() != 5 ||',
    '            rules::mmpCrystalBallSpellFunctionLevel() != 10) ++bad;',
    '        if (rules::mmpCrystalBallNoticeMinInt() != 12 ||',
    '            rules::mmpCrystalBallDetectPerLevelPct() != 1 ||',
    '            rules::mmpCrystalBallDetectionTablePage() != 60 ||',
    '            rules::mmpCrystalBallDispelDownDays() != 1 ||',
    '            rules::mmpCrystalBallCheckPerRound() != 1 ||',
    '            rules::mmpCrystalBallSpellUserClassCount() != 4 ||',
    '            rules::mmpCrystalBallClericDevicesAllowed() != 1 ||',
    '            rules::mmpCrystalBallKnowledgeNotDistance() != 1 ||',
    '            rules::mmpCrystalBallTelepathyCommunicationOnly() != 1) ++bad;',
    '        if (rules::mmpHypnosisBallCursed() != 1 ||',
    '            rules::mmpHypnosisBallRadiatesEvil() != 0 ||',
    '            rules::mmpHypnosisBallSuggestionImplanted() != 1 ||',
    '            rules::mmpHypnosisBallIndistinguishable() != 1 ||',
    '            rules::mmpHypnosisBallInfluencerKindCount() != 3 ||',
    '            rules::mmpHypnosisBallFateCount() != 3 ||',
    '            rules::mmpHypnosisBallRefereePace() != 1) ++bad;',
    '        static const int kLocPct[8] = {',
    '            100, 85, 50, 50, 25, 25, 20, -25,',
    '        };',
    '        static const int kViewMin[6] = {',
    '            60, 30, 30, 30, 15, 10,',
    '        };',
    '        static const int kViewFreq[6] = {',
    '            3, 3, 2, 1, 1, 1,',
    '        };',
    '        static const int kViewHi[6] = {',
    '            100, 99, 89, 74, 49, 24,',
    '        };',
    '        static const int kFeatLo[4] = {',
    '            1, 51, 76, 91,',
    '        };',
    '        static const int kFeatHi[4] = {',
    '            50, 75, 90, 100,',
    '        };',
    '        static const int kFeatCount[4] = {',
    '            0, 1, 2, 3,',
    '        };',
    '        static const int kDetPct[7] = {',
    '            2, 6, 6, 5, 4, 1, 3,',
    '        };',
    '        static const int kIntPct[6] = {',
    '            1, 3, 6, 10, 15, 21,',
    '        };',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::mmpCrystalBallLocatingPct(i) !=',
    '                kLocPct[i]) ++bad;',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpCrystalBallViewingMinutes(i) !=',
    '                kViewMin[i] ||',
    '                rules::mmpCrystalBallViewingTimesPerDay(i) !=',
    '                kViewFreq[i] ||',
    '                rules::mmpCrystalBallViewingBandHiPct(i) !=',
    '                kViewHi[i]) ++bad;',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpCrystalBallFeatureBandLo(i) !=',
    '                kFeatLo[i] ||',
    '                rules::mmpCrystalBallFeatureBandHi(i) !=',
    '                kFeatHi[i] ||',
    '                rules::mmpCrystalBallFeatureCountAt(i) !=',
    '                kFeatCount[i]) ++bad;',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::mmpCrystalBallDetectBasePct(i) !=',
    '                kDetPct[i]) ++bad;',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpCrystalBallIntFactorPct(i) !=',
    '                kIntPct[i]) ++bad;',
    '        // the kMisc2 rows this slice completes:',
    '        // row 11 Crystal Ball 56-60, row 12 the',
    '        // Crystal Hypnosis Ball 61-61',
    '        static const int kM2Lo2[2] = {',
    '            56, 61,',
    '        };',
    '        static const int kM2Hi2[2] = {',
    '            60, 61,',
    '        };',
    '        for (int i = 0; i < 2; ++i)',
    '            if (rules::m2RowLo(11 + i) != kM2Lo2[i] ||',
    '                rules::m2RowHi(11 + i) != kM2Hi2[i]) ++bad;',
    '        // the class marks: both rows are (M); the',
    '        // Cloak row 10 and the row 13 are negative',
    '        // controls',
    '        if (!rules::m2UsableByMagicUser(11) ||',
    '            !rules::m2UsableByMagicUser(12) ||',
    '            rules::m2UsableByMagicUser(10) ||',
    '            rules::m2UsableByMagicUser(13)) ++bad;',
    '        // the double asterisk: row 11 only, the R226',
    '        // pin verified correct',
    '        if (!rules::m2HasFeatureAsterisk(11) ||',
    '            rules::m2HasFeatureAsterisk(10) ||',
    '            rules::m2HasFeatureAsterisk(12)) ++bad;',
    '        // the printed ball values: 1000 xp / 5000 gp',
    '        // base, +100 percent per additional feature -',
    '        // clairaudience 2000/10000, ESP 3000/15000,',
    '        // telepathy 4000/20000, cross-pinned against',
    '        // the prose feature table',
    '        if (rules::m2CrystalBallBaseXp() != 1000 ||',
    '            rules::m2CrystalBallBaseGp() != 5000 ||',
    '            rules::m2CrystalBallFeatureBonusPct() != 100) ++bad;',
    '        if (rules::m2CrystalBallBaseXp() *',
    '                (1 + rules::mmpCrystalBallFeatureCountAt(1)) !=',
    '            2000 ||',
    '            rules::m2CrystalBallBaseGp() *',
    '                (1 + rules::mmpCrystalBallFeatureCountAt(1)) !=',
    '            10000 ||',
    '            rules::m2CrystalBallBaseXp() *',
    '                (1 + rules::mmpCrystalBallFeatureCountAt(3)) !=',
    '            4000 ||',
    '            rules::m2CrystalBallBaseGp() *',
    '                (1 + rules::mmpCrystalBallFeatureCountAt(3)) !=',
    '            20000) ++bad;',
    '        printf("R262 misc magic prose part 6 pins audit:'
    ' bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]
RG = rd('regtest.cpp')
ANCHOR = ('    // ---- R227: the wis mental save wiring audit ----')
AUDIT_STR = NL.join(AUDIT)
if ('printf("R262 misc magic prose part 6 pins audit:') in RG:
    already += 1
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
else:
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
    RG = RG.replace(ANCHOR, AUDIT_STR + NL + ANCHOR)
    applied += 1
    assert RG.count(
        'printf("R262 misc magic prose part 6 pins audit:') == 1, \
        'audit printf not unique'
wr('regtest.cpp', RG)

# ---- patch 4: the gap entry ----
GAP = [
    'R262 landed the III.E misc',
    'magic explanation prose part',
    '6 (part2 lines 222-283;',
    'global = 11065 + part2',
    'line), Crystal Ball and',
    'Crystal Hypnosis Ball -',
    'completing the kMisc2 rows',
    '11-12. ONE page header',
    'inside the slice strips (the',
    '279 TREASURE page, the R249',
    'lesson); the slice is',
    'table-dense: the locating',
    'chance table (well known',
    '100, slightly 85, pictured',
    '50, part 50, garment 25,',
    'informed 25, slightly',
    'informed 20, other plane',
    '-25), the viewing period',
    'table (1 hour 3 times a day',
    'down to 1/6 hour once), the',
    'additional powers table',
    '(01-50 plain, 51-75',
    'clairaudience, 76-90 ESP,',
    '91-00 telepathy,',
    'communication only), the',
    'notice-by-class table',
    '(Fighter 2, Thief 6,',
    'Paladin 6, Assassin 5,',
    'Ranger 4, Monk 1, Bard 3).',
    'The spell function is 10th',
    'level; notice needs int 12',
    'or better; the int ladder',
    '1, 3, 6, 10, 15, 21 at int',
    '13-18 plus 1 percent per',
    'level; a dispel magic shuts',
    'the ball down 1 day; the',
    'spell-user detection uses',
    'the page 60 table; clerics',
    'and druids may take water',
    'basin or mirror scriers.',
    'Crystal Hypnosis Ball:',
    'cursed, indistinguishable,',
    'radiates magic not evil; the',
    'gazer gets a telepathic',
    'suggestion and slides under',
    'the influence (magic-user,',
    'lich, or other-planar power;',
    'servant, tool, or possession',
    'object), gradual or sudden',
    'at the referee call. ENGINE',
    'CROSS-CHECK: kMisc2 rows',
    '11-12 (Crystal Ball 56-60,',
    'Hypnosis 61), the (M) marks',
    'on both, and the',
    'double-asterisk row 11 -',
    'the R226 pin VERIFIED',
    'CORRECT (1000 xp / 5000 gp',
    'base, +100 percent per',
    'feature: clairaudience',
    '2000/10000, ESP 3000/15000,',
    'telepathy 4000/20000). New',
    'R262 battery audit; census',
    '180. Next: part 7 - Cube of',
    'Force onward in part2 from',
    'line 285 (global 11350; the',
    'cube of force charge table',
    'and the attack-form',
    'surcharge table follow).',
]
GP = rd('tools/dmg_gap_report.md')
if GP.count('R262 landed the III.E misc') == 1:
    already += 1
else:
    TAIL = ('feature row 56-60 is' + NL + 'R226-pinned).' + NL +
            NL + 'Categories:')
    assert GP.count(TAIL) == 1, 'R261 gap tail anchor not unique'
    NEWTAIL = ('feature row 56-60 is' + NL + 'R226-pinned).' +
               NL + NL + NL.join(GAP) + NL + NL + 'Categories:')
    GP = GP.replace(TAIL, NEWTAIL)
    applied += 1
    assert GP.count('R262 landed the III.E misc') == 1, \
        'gap entry insert failed'
wr('tools/dmg_gap_report.md', GP)

# ---- report ----
assert applied + already == 4, 'patch count wrong'
print('R262 splice: ALL OK (applied %d, already %d)'
      % (applied, already))
print('R262 note: 4 patches; the III.E misc magic')
print('explanation prose part 6 - Crystal Ball and')
print('Crystal Hypnosis Ball, part2 lines 222-283;')
print('census 180.')
COMMIT = ('R262: the III.E misc magic explanation prose part 6'
          ' pinned - Crystal Ball and Crystal Hypnosis Ball in'
          ' part2 lines 222-283 (census 180)')
print('commit: ' + COMMIT)

