#!/usr/bin/env python3
# R265 splice: the III.E misc magic explanation prose
# part 9 pins - Drums of Deafening through Eyes of
# Petrification plus the eye-mix note, part2 lines
# 402-429 (DMG p.134-135) - the slice that completes
# the kMisc2 rows 19-29 (Candle of Invocation through
# Eyes of Petrification, the full 30-row table). ONE
# page header strips (417, the TREASURE page) cutting
# the Eversmoking Bottle paragraph mid-sentence (one
# seam, restored). The R264 pointer said four dusts;
# the print shows three. 4 patches, marker-based
# idempotence, assert after every patch. ZERO
# apostrophes and ZERO literal backslashes in the
# content below (the printf newline is built via
# BS = chr(92)).

import os
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

# ---- patch 1: rules/miscprose9.h ----
P1 = 'rules/miscprose9.h'
HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose9.h',
    '// R265: the III.E misc magic explanation prose part 9',
    '// (DMG p.134-135) - Drums of Deafening through Eyes',
    '// of Petrification plus the eye-mix note, part2',
    '// lines 402-429 (global = 11065 + part2 line). ONE',
    '// page header strips (417, the TREASURE page) cutting',
    '// the Eversmoking Bottle paragraph mid-sentence (one',
    '// seam, restored). The R264 pointer said four dusts;',
    '// the print shows three. 50 scalar accessors, no',
    '// name collisions with miscprose1.h through',
    '// miscprose8.h. The slice pins kMisc2 rows 19-29 -',
    '// completing the 30-row table (Candle of Invocation',
    '// through Eyes of Petrification). Pure data +',
    '// helpers, header-only (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpDrumDeafDeafRangeInches() {',
    '    // both drums: permanent deafness radius',
    '    return 7;',
    '}',
    '',
    'inline int mmpDrumDeafStunRangeInches() {',
    '    // the stun zone radius',
    '    return 1;',
    '}',
    '',
    'inline int mmpDrumDeafStunMinRounds() {',
    '    // stunned for from 2-8 rounds',
    '    return 2;',
    '}',
    '',
    'inline int mmpDrumDeafStunMaxRounds() {',
    '    // stunned for from 2-8 rounds',
    '    return 8;',
    '}',
    '',
    'inline int mmpDrumDeafHemisphereHalfFeet() {',
    '    // each drum: 1.5 feet diameter hemisphere',
    '    return 3;',
    '}',
    '',
    'inline int mmpDrumPanicRangeInches() {',
    '    // both drums: the panic radius',
    '    return 12;',
    '}',
    '',
    'inline int mmpDrumPanicSafeZoneInches() {',
    '    // the safe zone radius from the drums',
    '    return 2;',
    '}',
    '',
    'inline int mmpDrumPanicFleeTurns() {',
    '    // move directly away for 1 full turn',
    '    return 1;',
    '}',
    '',
    'inline int mmpDrumPanicRestRoundsPerTurn() {',
    '    // 3 rounds of rest per 1 turn of flight',
    '    return 3;',
    '}',
    '',
    'inline int mmpDrumPanicInt2SaveMod() {',
    '    // intelligence of 2 saves at -2',
    '    return -2;',
    '}',
    '',
    'inline int mmpDrumPanicInt1SaveMod() {',
    '    // intelligence of 1 or less saves at -4',
    '    return -4;',
    '}',
    '',
    'inline int mmpDrumPanicHemisphereHalfFeet() {',
    '    // each drum: 1.5 feet diameter hemisphere',
    '    return 3;',
    '}',
    '',
    'inline int mmpDustAppearDurationMinTurns() {',
    '    // appearance lasts for 2-20 turns',
    '    return 2;',
    '}',
    '',
    'inline int mmpDustAppearDurationMaxTurns() {',
    '    // appearance lasts for 2-20 turns',
    '    return 20;',
    '}',
    '',
    'inline int mmpDustAppearPacketRadiusFeet() {',
    '    // a packet covers a 10 feet radius',
    '    return 10;',
    '}',
    '',
    'inline int mmpDustAppearTubeStartFeet() {',
    '    // the cone: 1 feet wide at the start',
    '    return 1;',
    '}',
    '',
    'inline int mmpDustAppearTubeEndFeet() {',
    '    // the cone: 15 feet wide at the end',
    '    return 15;',
    '}',
    '',
    'inline int mmpDustAppearTubeLengthFeet() {',
    '    // the cone: 20 feet long',
    '    return 20;',
    '}',
    '',
    'inline int mmpDustAppearContainerMin() {',
    '    // from 5 to 50 containers in one place',
    '    return 5;',
    '}',
    '',
    'inline int mmpDustAppearContainerMax() {',
    '    // from 5 to 50 containers in one place',
    '    return 50;',
    '}',
    '',
    'inline int mmpDustGoneDurationMinTurns() {',
    '    // invisibility lasts 2 to 20 turns',
    '    return 2;',
    '}',
    '',
    'inline int mmpDustGoneDurationMaxTurns() {',
    '    // invisibility lasts 2 to 20 turns',
    '    return 20;',
    '}',
    '',
    'inline int mmpDustGoneSprinkleMinTurns() {',
    '    // carefully sprinkled: 11-20 turns',
    '    return 11;',
    '}',
    '',
    'inline int mmpDustGoneSprinkleMaxTurns() {',
    '    // carefully sprinkled: 11-20 turns',
    '    return 20;',
    '}',
    '',
    'inline int mmpDustGoneAcBonusPlaces() {',
    '    // armor class 4 places better',
    '    return 4;',
    '}',
    '',
    'inline int mmpDustChokeRadiusFeet() {',
    '    // the sneezing fits radius',
    '    return 20;',
    '}',
    '',
    'inline int mmpDustChokeDisabledMinRounds() {',
    '    // survivors disabled 5-20 rounds',
    '    return 5;',
    '}',
    '',
    'inline int mmpDustChokeDisabledMaxRounds() {',
    '    // survivors disabled 5-20 rounds',
    '    return 20;',
    '}',
    '',
    'inline int mmpEfreetiInsanePct() {',
    '    // 10 percent insane, attacks at once',
    '    return 10;',
    '}',
    '',
    'inline int mmpEfreetiWishesPct() {',
    '    // 10 percent grants 3 wishes only',
    '    return 10;',
    '}',
    '',
    'inline int mmpEfreetiServePct() {',
    '    // the other 80 percent serves normally',
    '    return 80;',
    '}',
    '',
    'inline int mmpEfreetiWishCount() {',
    '    // the wishes-only bottle grants 3',
    '    return 3;',
    '}',
    '',
    'inline int mmpEfreetiReleaseSegments() {',
    '    // issues from the bottle in but 1 segment',
    '    return 1;',
    '}',
    '',
    'inline int mmpEversmokeFirstRoundCubicFeet() {',
    '    // obscures a 50000 cubic foot area',
    '    return 50000;',
    '}',
    '',
    'inline int mmpEversmokePerRoundCubicFeet() {',
    '    // 10000 cubic feet more each round',
    '    return 10000;',
    '}',
    '',
    'inline int mmpEversmokeMaxCubicFeet() {',
    '    // until 120000 cubic feet are fogged',
    '    return 120000;',
    '}',
    '',
    'inline int mmpEyesCharmTargetsPerRound() {',
    '    // one person per round can be looked at',
    '    return 1;',
    '}',
    '',
    'inline int mmpEyesCharmBothSaveMod() {',
    '    // both lenses: saves at -2',
    '    return -2;',
    '}',
    '',
    'inline int mmpEyesCharmOneSaveMod() {',
    '    // only 1 of a pair: saves at +2',
    '    return 2;',
    '}',
    '',
    'inline int mmpEyesEagleVisionFactor() {',
    '    // vision 100 times greater than normal',
    '    return 100;',
    '}',
    '',
    'inline int mmpEyesEagleMinDistanceFeet() {',
    '    // at distances of 1 feet or more',
    '    return 1;',
    '}',
    '',
    'inline int mmpEyesEagleSeeAtFeet() {',
    '    // sees at 2000 feet',
    '    return 2000;',
    '}',
    '',
    'inline int mmpEyesEagleNormalSeeFeet() {',
    '    // what normal sight does at 20 feet',
    '    return 20;',
    '}',
    '',
    'inline int mmpEyesEagleSingleStunRounds() {',
    '    // one cusp: dizzy, stunned, for 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpEyesMinuteVisionFactor() {',
    '    // see 100 times better at 1 feet or less',
    '    return 100;',
    '}',
    '',
    'inline int mmpEyesMinuteMaxDistanceFeet() {',
    '    // only within 1 feet',
    '    return 1;',
    '}',
    '',
    'inline int mmpEyesPetrifyBasiliskGazePct() {',
    '    // 25 percent work as basilisk gaze',
    '    return 25;',
    '}',
    '',
    'inline int mmpEyesMixInsanityMinTurns() {',
    '    // mixing eye types: insanity 2-8 turns',
    '    return 2;',
    '}',
    '',
    'inline int mmpEyesMixInsanityMaxTurns() {',
    '    // mixing eye types: insanity 2-8 turns',
    '    return 8;',
    '}',
    '',
    'inline int mmpEyesMixInsanityDice() {',
    '    // the insanity lasts 2-8 (2d4) turns',
    '    return 2;',
    '}',
    '',
    '}  // namespace rules',
]
if os.path.exists(os.path.join(ROOT, P1)):
    already += 1
    assert rd(P1) == NL.join(HDR), P1 + ' exists but differs'
else:
    wr(P1, NL.join(HDR))
    applied += 1
    assert rd(P1) == NL.join(HDR), P1 + ' write mismatch'
assert rd(P1).count(
    'R265: the III.E misc magic explanation prose part 9') == 1

# ---- patch 2: the regtest include ----
INC_OLD = ('#include "rules/miscprose8.h"  // R264: the III.E misc'
           ' magic explanation prose part 8 pins')
INC_NEW = ('#include "rules/miscprose9.h"  // R265: the III.E misc'
           ' magic explanation prose part 9 pins')
RG = rd('regtest.cpp')
if INC_NEW in RG:
    already += 1
    assert RG.count(INC_NEW) == 1, 'include not unique'
else:
    assert RG.count(INC_OLD) == 1, 'R264 include anchor missing'
    RG = RG.replace(INC_OLD, INC_OLD + NL + INC_NEW)
    applied += 1
    assert RG.count(INC_NEW) == 1, 'include insert failed'
wr('regtest.cpp', RG)

# ---- patch 3: the R265 audit block ----
AUDIT = [
    '    // ---- R265: the III.E misc magic explanation',
    '    // prose part 9 ----',
    '    // Drums of Deafening through Eyes of Petrification',
    '    // plus the eye-mix note, part2 lines 402-429 -',
    '    // the slice that completes the kMisc2 rows 19-29.',
    '    {',
    '        int bad = 0;',
    '        if (rules::mmpDrumDeafDeafRangeInches() != 7 ||',
    '            rules::mmpDrumDeafStunRangeInches() != 1 ||',
    '            rules::mmpDrumDeafStunMinRounds() != 2 ||',
    '            rules::mmpDrumDeafStunMaxRounds() != 8 ||',
    '            rules::mmpDrumDeafHemisphereHalfFeet() !=',
    '            3) ++bad;',
    '        if (rules::mmpDrumPanicRangeInches() != 12 ||',
    '            rules::mmpDrumPanicSafeZoneInches() != 2 ||',
    '            rules::mmpDrumPanicFleeTurns() != 1 ||',
    '            rules::mmpDrumPanicRestRoundsPerTurn() != 3 ||',
    '            rules::mmpDrumPanicInt2SaveMod() != -2 ||',
    '            rules::mmpDrumPanicInt1SaveMod() != -4 ||',
    '            rules::mmpDrumPanicHemisphereHalfFeet() !=',
    '            3) ++bad;',
    '        if (rules::mmpDustAppearDurationMinTurns() != 2 ||',
    '            rules::mmpDustAppearDurationMaxTurns() != 20 ||',
    '            rules::mmpDustAppearPacketRadiusFeet() != 10 ||',
    '            rules::mmpDustAppearTubeStartFeet() != 1 ||',
    '            rules::mmpDustAppearTubeEndFeet() != 15 ||',
    '            rules::mmpDustAppearTubeLengthFeet() != 20 ||',
    '            rules::mmpDustAppearContainerMin() != 5 ||',
    '            rules::mmpDustAppearContainerMax() != 50) ++bad;',
    '        if (rules::mmpDustGoneDurationMinTurns() != 2 ||',
    '            rules::mmpDustGoneDurationMaxTurns() != 20 ||',
    '            rules::mmpDustGoneSprinkleMinTurns() != 11 ||',
    '            rules::mmpDustGoneSprinkleMaxTurns() != 20 ||',
    '            rules::mmpDustGoneAcBonusPlaces() != 4) ++bad;',
    '        if (rules::mmpDustChokeRadiusFeet() != 20 ||',
    '            rules::mmpDustChokeDisabledMinRounds() != 5 ||',
    '            rules::mmpDustChokeDisabledMaxRounds() !=',
    '            20) ++bad;',
    '        if (rules::mmpEfreetiInsanePct() != 10 ||',
    '            rules::mmpEfreetiWishesPct() != 10 ||',
    '            rules::mmpEfreetiServePct() != 80 ||',
    '            rules::mmpEfreetiWishCount() != 3 ||',
    '            rules::mmpEfreetiReleaseSegments() != 1) ++bad;',
    '        if (rules::mmpEversmokeFirstRoundCubicFeet() !=',
    '            50000 ||',
    '            rules::mmpEversmokePerRoundCubicFeet() !=',
    '            10000 ||',
    '            rules::mmpEversmokeMaxCubicFeet() !=',
    '            120000) ++bad;',
    '        if (rules::mmpEyesCharmTargetsPerRound() != 1 ||',
    '            rules::mmpEyesCharmBothSaveMod() != -2 ||',
    '            rules::mmpEyesCharmOneSaveMod() != 2) ++bad;',
    '        if (rules::mmpEyesEagleVisionFactor() != 100 ||',
    '            rules::mmpEyesEagleMinDistanceFeet() != 1 ||',
    '            rules::mmpEyesEagleSeeAtFeet() != 2000 ||',
    '            rules::mmpEyesEagleNormalSeeFeet() != 20 ||',
    '            rules::mmpEyesEagleSingleStunRounds() !=',
    '            1) ++bad;',
    '        if (rules::mmpEyesMinuteVisionFactor() != 100 ||',
    '            rules::mmpEyesMinuteMaxDistanceFeet() != 1 ||',
    '            rules::mmpEyesPetrifyBasiliskGazePct() != 25 ||',
    '            rules::mmpEyesMixInsanityMinTurns() != 2 ||',
    '            rules::mmpEyesMixInsanityMaxTurns() != 8 ||',
    '            rules::mmpEyesMixInsanityDice() != 2) ++bad;',
    '        // the arithmetic: the efreeti chances sum',
    '        if (rules::mmpEfreetiInsanePct() +',
    '            rules::mmpEfreetiWishesPct() +',
    '            rules::mmpEfreetiServePct() != 100) ++bad;',
    '        if (rules::mmpEversmokeFirstRoundCubicFeet() +',
    '            7 * rules::mmpEversmokePerRoundCubicFeet() !=',
    '            rules::mmpEversmokeMaxCubicFeet()) ++bad;',
    '        // the kMisc2 rows this slice pins: 19-29,',
    '        // completing the 30-row table',
    '        static const int kLo[11] = {',
    '            77, 78, 80, 86, 92, 93, 94, 95,',
    '            96, 98, 100,',
    '        };',
    '        static const int kHi[11] = {',
    '            77, 79, 85, 91, 92, 93, 94, 95,',
    '            97, 99, 100,',
    '        };',
    '        static const int kM[11] = {',
    '            0, 0, 0, 0, 0, 0, 0, 1,',
    '            0, 0, 0,',
    '        };',
    '        static const int kTriple[11] = {',
    '            0, 0, 0, 0, 0, 0, 0, 0,',
    '            0, 0, 1,',
    '        };',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::m2RowLo(19 + i) != kLo[i] ||',
    '                rules::m2RowHi(19 + i) != kHi[i]) ++bad;',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::m2UsableByCleric(19 + i) ||',
    '                rules::m2IsPerPlusValued(19 + i) ||',
    '                rules::m2HasFeatureAsterisk(19 + i) ||',
    '                rules::m2UsableByMagicUser(19 + i) !=',
    '                kM[i] ||',
    '                rules::m2IsTripleStar(19 + i) !=',
    '                kTriple[i]) ++bad;',
    '        // the row 26 (M) positive control, Eyes',
    '        // of Charming; the row 29 triple-star',
    '        // control, Eyes of Petrification',
    '        if (!rules::m2UsableByMagicUser(26)) ++bad;',
    '        if (!rules::m2IsTripleStar(29)) ++bad;',
    '        printf("R265 misc magic prose part 9 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]
RG = rd('regtest.cpp')
ANCHOR = ('    // ---- R227: the wis mental save wiring audit ----')
AUDIT_STR = NL.join(AUDIT)
if ('printf("R265 misc magic prose part 9 pins audit:') in RG:
    already += 1
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
else:
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
    RG = RG.replace(ANCHOR, AUDIT_STR + NL + ANCHOR)
    applied += 1
    assert RG.count(
        'printf("R265 misc magic prose part 9 pins audit:') == 1, \
        'audit printf not unique'
wr('regtest.cpp', RG)

# ---- patch 4: the gap entry ----
GAP = [
    'R265 landed the III.E misc',
    'magic explanation prose part',
    '9 (part2 lines 402-429;',
    'global = 11065 + part2',
    'line), Drums of Deafening',
    'through Eyes of Petrification',
    'plus the eye-mix note -',
    'pinning the kMisc2 rows',
    '19-29, the slice that',
    'COMPLETES the 30-row table',
    '(Candle of Invocation through',
    'Eyes of Petrification). ONE',
    'page header inside the slice',
    'strips (the 417 TREASURE',
    'page), cutting the',
    'Eversmoking Bottle paragraph',
    'mid-sentence (until the /',
    'eversmoking bottle is',
    'stoppered) - one seam,',
    'restored. The R264 pointer',
    'said four dusts; the print',
    'shows three (Appearance,',
    'Disappearance, Sneezing and',
    'Choking). The items: Drums',
    'of Deafening (both drums:',
    'permanent deafness within 7',
    'inches, heal or similar',
    'cures; 1 inch zone stunned',
    '2-8 rounds), Drums of Panic',
    '(12 inches, safe zone 2',
    'inches, flee 1 turn per',
    'failed save, 3 rest rounds',
    'per 1 turn of flight, int 2',
    'saves -2, int 1 or less',
    '-4; both drum pairs are',
    '1.5 feet hemispheres), Dust',
    'of Appearance (2-20 turns;',
    'packet 10 feet radius, tube',
    'cone 1 to 15 feet wide and',
    '20 long; 5-50 containers;',
    'reveals invisible, out of',
    'phase, astral, ethereal;',
    'images; negates the',
    'displacement, elvenkind and',
    'blending cloaks), Dust of',
    'Disappearance (2-20 turns,',
    '11-20 sprinkled; even',
    'detect invisibility fails;',
    'the dust of appearance',
    'exception; AC 4 places',
    'better; attack does not',
    'obviate it), Dust of',
    'Sneezing and Choking (20',
    'feet radius; failed poison',
    'save dies, survivors',
    'choked 5-20 rounds),',
    'Efreeti Bottle (brass or',
    'bronze, lead stopper; 10',
    'percent insane attack, 10',
    'percent 3 wishes only, 80',
    'percent serve; issues in 1',
    'segment), Eversmoking',
    'Bottle (urn identical to',
    'the efreeti bottle; 50000',
    'cubic feet in 1 round,',
    '10000 more per round to',
    '120000; smokes until',
    'stoppered; command word',
    'reseals), Eyes of Charming',
    '(1 person per round; both',
    'lenses save -2, one lens',
    '+2), Eyes of the Eagle',
    '(100x at 1 foot or more;',
    '2000 vs 20 feet; one cusp',
    'dizzy-stunned 1 round,',
    'then always cover 1 eye),',
    'Eyes of Minute Seeing (100x',
    'at 1 foot or less; seams,',
    'marks, compartments),',
    'Eyes of Petrification',
    '(instant stone; 25 percent',
    'as basilisk gaze including',
    'reflection), Mixing eye',
    'types (immediate insanity',
    '2-8 turns, 2d4). Engine',
    'rows 19-29: 77, 78-79,',
    '80-85, 86-91, 92, 93, 94,',
    '95, 96-97, 98-99, 100;',
    'only Eyes of Charming (M);',
    'row 29 the triple star.',
    'New R265 battery audit;',
    'census 183. Next: part 10 -',
    'Figurines of Wondrous Power',
    'onward in part2 from line',
    '433 (global 11498; TABLE',
    'III.E. 3, the kMisc3 rows,',
    'begins; the figurines,',
    'gauntlets and girdles',
    'follow).',
]
GP = rd('tools/dmg_gap_report.md')
if GP.count('R265 landed the III.E misc') == 1:
    already += 1
else:
    TAIL = ('bottles and the eyes follow;' + NL + 'rows 19+).' + NL +
            NL + 'Categories:')
    assert GP.count(TAIL) == 1, 'R264 gap tail anchor not unique'
    NEWTAIL = ('bottles and the eyes follow;' + NL + 'rows 19+).' +
               NL + NL + NL.join(GAP) + NL + NL + 'Categories:')
    GP = GP.replace(TAIL, NEWTAIL)
    applied += 1
    assert GP.count('R265 landed the III.E misc') == 1, \
        'gap entry insert failed'
wr('tools/dmg_gap_report.md', GP)

# ---- report ----
assert applied + already == 4, 'patch count wrong'
print('R265 splice: ALL OK (applied %d, already %d)'
      % (applied, already))
print('R265 note: 4 patches; the III.E misc magic')
print('explanation prose part 9 - Drums of Deafening')
print('through Eyes of Petrification, part2 lines')
print('402-429; census 183.')
COMMIT = ('R265: the III.E misc magic explanation prose part 9'
          ' pinned - Drums of Deafening through Eyes of'
          ' Petrification in part2 lines 402-429 (census 183)')
print('commit: ' + COMMIT)

