#!/usr/bin/env python3
# R266 splice: the III.E misc magic explanation prose
# part 10 pins - Figurines of Wondrous Power, part2
# lines 433-479 (DMG p.135-136) - the slice that
# opens the kMisc3 rows (row 0, the figurine band
# 01-15, single asterisk, per hit die values). ONE
# page header strips (477, the TREASURE page) cutting
# the Serpentine Owl paragraph mid-sentence (one
# seam, restored); the compilation also wraps the
# Goat of Travelling paragraph at a bare blank line
# (450/452, no page header) - one wrap artifact,
# restored. 4 patches, marker-based idempotence,
# assert after every patch. ZERO apostrophes and
# ZERO literal backslashes in the content below
# (the printf newline is built via BS = chr(92)).

import os
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

# ---- patch 1: rules/miscprose10.h ----
P1 = 'rules/miscprose10.h'
HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose10.h',
    '// R266: the III.E misc magic explanation prose part 10',
    '// (DMG p.135-136) - Figurines of Wondrous Power, part2',
    '// lines 433-479 (global = 11065 + part2 line). ONE page',
    '// header strips (477, the TREASURE page) cutting the',
    '// Serpentine Owl paragraph mid-sentence (one seam,',
    '// restored); the compilation also wraps the Goat of',
    '// Travelling paragraph at a bare blank line (450/452,',
    '// no page header) - one wrap artifact, restored. 90',
    '// accessors: 86 scalars + 4 array walkers (the figurine',
    '// type and marble elephant type tables), no name',
    '// collisions with miscprose1.h through miscprose9.h.',
    '// The slice pins kMisc3 row 0 (the Figurine band',
    '// 01-15, the single asterisk, per hit die values).',
    '// Pure data + helpers, header-only (the grenade.h',
    '// pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpFigTypeCount() {',
    '    // the printed figurine type table rows',
    '    return 7;',
    '}',
    '',
    'inline int mmpFigStatuetteInchesHigh() {',
    '    // a statuette of small size, an inch or so',
    '    return 1;',
    '}',
    '',
    'inline int mmpFigTypeLo(int i) {',
    '    // the printed type band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        1, 16, 31, 41, 56, 66, 86,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpFigTypeHi(int i) {',
    '    // the printed type band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        15, 30, 40, 55, 65, 85, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpFlyAc() {',
    '    // the ebony fly armor class',
    '    return 4;',
    '}',
    '',
    'inline int mmpFlyHitDiceBase() {',
    '    // 4 + 4 hit dice: the base',
    '    return 4;',
    '}',
    '',
    'inline int mmpFlyHitDiceExtra() {',
    '    // 4 + 4 hit dice: the plus',
    '    return 4;',
    '}',
    '',
    'inline int mmpFlyAirManeuverClass() {',
    '    // air maneuverability class C, the 3rd letter',
    '    return 3;',
    '}',
    '',
    'inline int mmpFlySpeedUnladenInches() {',
    '    // flies at 48 inches without a rider',
    '    return 48;',
    '}',
    '',
    'inline int mmpFlySpeedLadenInches() {',
    '    // 36 inches carrying up to 210 pounds',
    '    return 36;',
    '}',
    '',
    'inline int mmpFlySpeedMaxLoadInches() {',
    '    // 24 inches carrying from 211 to 350 pounds',
    '    return 24;',
    '}',
    '',
    'inline int mmpFlyLadenMaxPounds() {',
    '    // the 36 inch band carries up to 210 pounds',
    '    return 210;',
    '}',
    '',
    'inline int mmpFlyMaxLoadPounds() {',
    '    // the 24 inch band carries up to 350 pounds',
    '    return 350;',
    '}',
    '',
    'inline int mmpFlyUsesPerWeek() {',
    '    // a maximum of 3 times per week',
    '    return 3;',
    '}',
    '',
    'inline int mmpFlyHoursPerDay() {',
    '    // 12 hours per day',
    '    return 12;',
    '}',
    '',
    'inline int mmpLionCount() {',
    '    // the pair becomes 2 adult male lions',
    '    return 2;',
    '}',
    '',
    'inline int mmpLionAcFront() {',
    '    // lion armor class 5/6: the front',
    '    return 5;',
    '}',
    '',
    'inline int mmpLionAcRear() {',
    '    // lion armor class 5/6: the rear',
    '    return 6;',
    '}',
    '',
    'inline int mmpLionHitDiceBase() {',
    '    // 5 + 2 hit dice: the base',
    '    return 5;',
    '}',
    '',
    'inline int mmpLionHitDiceExtra() {',
    '    // 5 + 2 hit dice: the plus',
    '    return 2;',
    '}',
    '',
    'inline int mmpLionSlainReturnWeeks() {',
    '    // slain: no statuette return for 1 full week',
    '    return 1;',
    '}',
    '',
    'inline int mmpLionUseDays() {',
    '    // otherwise usable once every day',
    '    return 1;',
    '}',
    '',
    'inline int mmpGoatCount() {',
    '    // the trio of statuettes',
    '    return 3;',
    '}',
    '',
    'inline int mmpGoatUsesBeforeBurnout() {',
    '    // after 3 uses each goat loses its magic',
    '    return 3;',
    '}',
    '',
    'inline int mmpGoatTravelAc() {',
    '    // the travelling mount armor class',
    '    return 6;',
    '}',
    '',
    'inline int mmpGoatTravelHp() {',
    '    // the travelling mount hit points',
    '    return 24;',
    '}',
    '',
    'inline int mmpGoatTravelAttacks() {',
    '    // 2 attacks, the horns',
    '    return 2;',
    '}',
    '',
    'inline int mmpGoatTravelHornDmgMin() {',
    '    // horns for 1-8 each',
    '    return 1;',
    '}',
    '',
    'inline int mmpGoatTravelHornDmgMax() {',
    '    // horns for 1-8 each',
    '    return 8;',
    '}',
    '',
    'inline int mmpGoatTravelHitDice() {',
    '    // consider as a 4 hit dice monster',
    '    return 4;',
    '}',
    '',
    'inline int mmpGoatTravelMoveInches() {',
    '    // moves at 48 inches',
    '    return 48;',
    '}',
    '',
    'inline int mmpGoatTravelMaxLoadPounds() {',
    '    // bearing 280 pounds or less',
    '    return 280;',
    '}',
    '',
    'inline int mmpGoatTravelPoundsPerMoveLoss() {',
    '    // minus 1 inch per 14 extra pounds',
    '    return 14;',
    '}',
    '',
    'inline int mmpGoatTravelHoursPerWeek() {',
    '    // 1 day each week, totalling 24 hours',
    '    return 24;',
    '}',
    '',
    'inline int mmpGoatTravelRestDays() {',
    '    // small form for not less than 1 day',
    '    return 1;',
    '}',
    '',
    'inline int mmpGoatTravailHoofDmgMin() {',
    '    // sharp hooves 4-10/4-10',
    '    return 4;',
    '}',
    '',
    'inline int mmpGoatTravailHoofDmgMax() {',
    '    // sharp hooves 4-10/4-10',
    '    return 10;',
    '}',
    '',
    'inline int mmpGoatTravailBiteDmgMin() {',
    '    // the vicious bite 2-8',
    '    return 2;',
    '}',
    '',
    'inline int mmpGoatTravailBiteDmgMax() {',
    '    // the vicious bite 2-8',
    '    return 8;',
    '}',
    '',
    'inline int mmpGoatTravailHornDmgMin() {',
    '    // the horns 2-12/2-12 (print: 2- 12)',
    '    return 2;',
    '}',
    '',
    'inline int mmpGoatTravailHornDmgMax() {',
    '    // the horns 2-12/2-12 (print: 2- 12)',
    '    return 12;',
    '}',
    '',
    'inline int mmpGoatTravailChargeBonus() {',
    '    // charging: +6 damage added to each hit',
    '    return 6;',
    '}',
    '',
    'inline int mmpGoatTravailChargeHornMin() {',
    '    // charging horns: 8-18 per horn',
    '    return 8;',
    '}',
    '',
    'inline int mmpGoatTravailChargeHornMax() {',
    '    // charging horns: 8-18 per horn',
    '    return 18;',
    '}',
    '',
    'inline int mmpGoatTravailAc() {',
    '    // armor class 0',
    '    return 0;',
    '}',
    '',
    'inline int mmpGoatTravailHp() {',
    '    // 96 hit points',
    '    return 96;',
    '}',
    '',
    'inline int mmpGoatTravailHitDice() {',
    '    // attacks as a 16 hit dice monster',
    '    return 16;',
    '}',
    '',
    'inline int mmpGoatTravailUsesPerMonth() {',
    '    // called to life but once per month',
    '    return 1;',
    '}',
    '',
    'inline int mmpGoatTravailMoveInches() {',
    '    // it moves 24 inches',
    '    return 24;',
    '}',
    '',
    'inline int mmpGoatTerrorMoveInches() {',
    '    // the destrier-like mount moves 36 inches',
    '    return 36;',
    '}',
    '',
    'inline int mmpGoatTerrorAc() {',
    '    // armor class 2',
    '    return 2;',
    '}',
    '',
    'inline int mmpGoatTerrorHp() {',
    '    // 48 hit points',
    '    return 48;',
    '}',
    '',
    'inline int mmpGoatTerrorHornSpearBonus() {',
    '    // one horn as a +3 spear (lance)',
    '    return 3;',
    '}',
    '',
    'inline int mmpGoatTerrorHornSwordBonus() {',
    '    // the other horn as a +6 sword',
    '    return 6;',
    '}',
    '',
    'inline int mmpGoatTerrorRadiusInches() {',
    '    // radiates terror in a 3 inch radius',
    '    return 3;',
    '}',
    '',
    'inline int mmpGoatTerrorStrengthLossPct() {',
    '    // save or lose 50 percent of strength',
    '    return 50;',
    '}',
    '',
    'inline int mmpGoatTerrorHitPenalty() {',
    '    // and at least -3 on to hit dice',
    '    return -3;',
    '}',
    '',
    'inline int mmpGoatTerrorIntervalWeeks() {',
    '    // used once every 2 weeks',
    '    return 2;',
    '}',
    '',
    'inline int mmpElephantTypeLo(int i) {',
    '    // the elephant type band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 51, 91, 94,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpElephantTypeHi(int i) {',
    '    // the elephant type band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        50, 90, 93, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpElephantHoursPerUse() {',
    '    // 24 hours at a time',
    '    return 24;',
    '}',
    '',
    'inline int mmpElephantUsesPerMonth() {',
    '    // 4 times per month',
    '    return 4;',
    '}',
    '',
    'inline int mmpSteadGoodRiderPct() {',
    '    // good rider: 10 percent per use to Hades',
    '    return 10;',
    '}',
    '',
    'inline int mmpSteadHoursPerUse() {',
    '    // a 24 hour period maximum',
    '    return 24;',
    '}',
    '',
    'inline int mmpSteadUsesPerWeek() {',
    '    // once per week',
    '    return 1;',
    '}',
    '',
    'inline int mmpDogIntMin() {',
    '    // intelligence of 8-10: the low',
    '    return 8;',
    '}',
    '',
    'inline int mmpDogIntMax() {',
    '    // intelligence of 8-10: the high',
    '    return 10;',
    '}',
    '',
    'inline int mmpDogScentFreshPct() {',
    '    // scents a known trail 100 percent if fresh',
    '    return 100;',
    '}',
    '',
    'inline int mmpDogScentFreshHours() {',
    '    // fresh means 1 hour or less old',
    '    return 1;',
    '}',
    '',
    'inline int mmpDogScentDecayPctPerHour() {',
    '    // minus 10 percent per hour thereafter',
    '    return 10;',
    '}',
    '',
    'inline int mmpDogInfravisionFeet() {',
    '    // 90 feet range infravision',
    '    return 90;',
    '}',
    '',
    'inline int mmpDogSpotHiddenPct() {',
    '    // spots hidden things 80 percent',
    '    return 80;',
    '}',
    '',
    'inline int mmpDogSpotInvisiblePct() {',
    '    // spots invisible things 65 percent',
    '    return 65;',
    '}',
    '',
    'inline int mmpDogSpotPhasedPct() {',
    '    // notes astral, ethereal, out-of-phase 50 percent',
    '    return 50;',
    '}',
    '',
    'inline int mmpDogHoursPerUse() {',
    '    // up to 6 continuous hours',
    '    return 6;',
    '}',
    '',
    'inline int mmpDogUsesPerWeek() {',
    '    // once per week',
    '    return 1;',
    '}',
    '',
    'inline int mmpOwlAc() {',
    '    // the normal-sized horned owl AC',
    '    return 7;',
    '}',
    '',
    'inline int mmpOwlMoveInches() {',
    '    // 24 inch move',
    '    return 24;',
    '}',
    '',
    'inline int mmpOwlHpMin() {',
    '    // 2-4 hit points: the low',
    '    return 2;',
    '}',
    '',
    'inline int mmpOwlHpMax() {',
    '    // 2-4 hit points: the high',
    '    return 4;',
    '}',
    '',
    'inline int mmpOwlDmgMin() {',
    '    // 1-2/1-2 damage: the low',
    '    return 1;',
    '}',
    '',
    'inline int mmpOwlDmgMax() {',
    '    // 1-2/1-2 damage: the high',
    '    return 2;',
    '}',
    '',
    'inline int mmpOwlGiantUses() {',
    '    // the giant owl form limited to 3 times',
    '    return 3;',
    '}',
    '',
    'inline int mmpOwlSilencePct() {',
    '    // the normal form moves with 95 percent silence',
    '    return 95;',
    '}',
    '',
    'inline int mmpOwlInfravisionFeet() {',
    '    // infravision to 90 feet',
    '    return 90;',
    '}',
    '',
    'inline int mmpOwlDarkVisionFactor() {',
    '    // sees dark as full light, twice a human',
    '    return 2;',
    '}',
    '',
    'inline int mmpOwlHearMouseFeet() {',
    '    // detects a mouse moving at 60 feet',
    '    return 60;',
    '}',
    '',
    'inline int mmpOwlCounterStealthPct() {',
    '    // silent movement vs the owl reduced 50 percent',
    '    return 50;',
    '}',
    '',
    'inline int mmpOwlIntMin() {',
    '    // low 2-4 intelligence: the low',
    '    return 2;',
    '}',
    '',
    'inline int mmpOwlIntMax() {',
    '    // low 2-4 intelligence: the high',
    '    return 4;',
    '}',
    '',
    '}  // namespace rules',
]
if os.path.exists(os.path.join(ROOT, P1)):
    already += 1
    assert rd(P1) == NL.join(HDR), P1 + ' exists but differs'
else:
    wr(P1, NL.join(HDR))
    applied += 1
    assert rd(P1) == NL.join(HDR), P1 + ' write mismatch'
assert rd(P1).count(
    'R266: the III.E misc magic explanation prose part 10') == 1

# ---- patch 2: the regtest include ----
INC_OLD = ('#include "rules/miscprose9.h"  // R265: the III.E misc'
           ' magic explanation prose part 9 pins')
INC_NEW = ('#include "rules/miscprose10.h"  // R266: the III.E misc'
           ' magic explanation prose part 10 pins')
RG = rd('regtest.cpp')
if INC_NEW in RG:
    already += 1
    assert RG.count(INC_NEW) == 1, 'include not unique'
else:
    assert RG.count(INC_OLD) == 1, 'R265 include anchor missing'
    RG = RG.replace(INC_OLD, INC_OLD + NL + INC_NEW)
    applied += 1
    assert RG.count(INC_NEW) == 1, 'include insert failed'
wr('regtest.cpp', RG)

# ---- patch 3: the R266 audit block ----
AUDIT = [
    '    // ---- R266: the III.E misc magic explanation',
    '    // prose part 10 ----',
    '    // Figurines of Wondrous Power, part2 lines',
    '    // 433-479 - the slice that opens the kMisc3 rows',
    '    // (row 0, the figurine band 01-15).',
    '    {',
    '        int bad = 0;',
    '        if (rules::mmpFigTypeCount() != 7 ||',
    '            rules::mmpFigStatuetteInchesHigh() != 1) ++bad;',
    '        if (rules::mmpFlyAc() != 4 ||',
    '            rules::mmpFlyHitDiceBase() != 4 ||',
    '            rules::mmpFlyHitDiceExtra() != 4 ||',
    '            rules::mmpFlyAirManeuverClass() != 3 ||',
    '            rules::mmpFlySpeedUnladenInches() != 48 ||',
    '            rules::mmpFlySpeedLadenInches() != 36 ||',
    '            rules::mmpFlySpeedMaxLoadInches() != 24 ||',
    '            rules::mmpFlyLadenMaxPounds() != 210 ||',
    '            rules::mmpFlyMaxLoadPounds() != 350 ||',
    '            rules::mmpFlyUsesPerWeek() != 3 ||',
    '            rules::mmpFlyHoursPerDay() != 12) ++bad;',
    '        if (rules::mmpLionCount() != 2 ||',
    '            rules::mmpLionAcFront() != 5 ||',
    '            rules::mmpLionAcRear() != 6 ||',
    '            rules::mmpLionHitDiceBase() != 5 ||',
    '            rules::mmpLionHitDiceExtra() != 2 ||',
    '            rules::mmpLionSlainReturnWeeks() != 1 ||',
    '            rules::mmpLionUseDays() != 1) ++bad;',
    '        if (rules::mmpGoatCount() != 3 ||',
    '            rules::mmpGoatUsesBeforeBurnout() != 3 ||',
    '            rules::mmpGoatTravelAc() != 6 ||',
    '            rules::mmpGoatTravelHp() != 24 ||',
    '            rules::mmpGoatTravelAttacks() != 2 ||',
    '            rules::mmpGoatTravelHornDmgMin() != 1 ||',
    '            rules::mmpGoatTravelHornDmgMax() != 8 ||',
    '            rules::mmpGoatTravelHitDice() != 4) ++bad;',
    '        if (rules::mmpGoatTravelMoveInches() != 48 ||',
    '            rules::mmpGoatTravelMaxLoadPounds() != 280 ||',
    '            rules::mmpGoatTravelPoundsPerMoveLoss() != 14 ||',
    '            rules::mmpGoatTravelHoursPerWeek() != 24 ||',
    '            rules::mmpGoatTravelRestDays() != 1) ++bad;',
    '        if (rules::mmpGoatTravailHoofDmgMin() != 4 ||',
    '            rules::mmpGoatTravailHoofDmgMax() != 10 ||',
    '            rules::mmpGoatTravailBiteDmgMin() != 2 ||',
    '            rules::mmpGoatTravailBiteDmgMax() != 8 ||',
    '            rules::mmpGoatTravailHornDmgMin() != 2 ||',
    '            rules::mmpGoatTravailHornDmgMax() != 12 ||',
    '            rules::mmpGoatTravailChargeBonus() != 6 ||',
    '            rules::mmpGoatTravailChargeHornMin() != 8 ||',
    '            rules::mmpGoatTravailChargeHornMax() != 18) ++bad;',
    '        if (rules::mmpGoatTravailAc() != 0 ||',
    '            rules::mmpGoatTravailHp() != 96 ||',
    '            rules::mmpGoatTravailHitDice() != 16 ||',
    '            rules::mmpGoatTravailUsesPerMonth() != 1 ||',
    '            rules::mmpGoatTravailMoveInches() != 24 ||',
    '            rules::mmpGoatTerrorMoveInches() != 36 ||',
    '            rules::mmpGoatTerrorAc() != 2 ||',
    '            rules::mmpGoatTerrorHp() != 48) ++bad;',
    '        if (rules::mmpGoatTerrorHornSpearBonus() != 3 ||',
    '            rules::mmpGoatTerrorHornSwordBonus() != 6 ||',
    '            rules::mmpGoatTerrorRadiusInches() != 3 ||',
    '            rules::mmpGoatTerrorStrengthLossPct() != 50 ||',
    '            rules::mmpGoatTerrorHitPenalty() != -3 ||',
    '            rules::mmpGoatTerrorIntervalWeeks() != 2 ||',
    '            rules::mmpElephantHoursPerUse() != 24 ||',
    '            rules::mmpElephantUsesPerMonth() != 4) ++bad;',
    '        if (rules::mmpSteadGoodRiderPct() != 10 ||',
    '            rules::mmpSteadHoursPerUse() != 24 ||',
    '            rules::mmpSteadUsesPerWeek() != 1 ||',
    '            rules::mmpDogIntMin() != 8 ||',
    '            rules::mmpDogIntMax() != 10 ||',
    '            rules::mmpDogScentFreshPct() != 100 ||',
    '            rules::mmpDogScentFreshHours() != 1 ||',
    '            rules::mmpDogScentDecayPctPerHour() != 10) ++bad;',
    '        if (rules::mmpDogInfravisionFeet() != 90 ||',
    '            rules::mmpDogSpotHiddenPct() != 80 ||',
    '            rules::mmpDogSpotInvisiblePct() != 65 ||',
    '            rules::mmpDogSpotPhasedPct() != 50 ||',
    '            rules::mmpDogHoursPerUse() != 6 ||',
    '            rules::mmpDogUsesPerWeek() != 1 ||',
    '            rules::mmpOwlAc() != 7 ||',
    '            rules::mmpOwlMoveInches() != 24) ++bad;',
    '        if (rules::mmpOwlHpMin() != 2 ||',
    '            rules::mmpOwlHpMax() != 4 ||',
    '            rules::mmpOwlDmgMin() != 1 ||',
    '            rules::mmpOwlDmgMax() != 2 ||',
    '            rules::mmpOwlGiantUses() != 3 ||',
    '            rules::mmpOwlSilencePct() != 95 ||',
    '            rules::mmpOwlInfravisionFeet() != 90 ||',
    '            rules::mmpOwlDarkVisionFactor() != 2) ++bad;',
    '        if (rules::mmpOwlHearMouseFeet() != 60 ||',
    '            rules::mmpOwlCounterStealthPct() != 50 ||',
    '            rules::mmpOwlIntMin() != 2 ||',
    '            rules::mmpOwlIntMax() != 4) ++bad;',
    '        // the arithmetic: the travail charge horn',
    '        // equals the horn plus the charge bonus',
    '        if (rules::mmpGoatTravailHornDmgMin() +',
    '            rules::mmpGoatTravailChargeBonus() !=',
    '            rules::mmpGoatTravailChargeHornMin() ||',
    '            rules::mmpGoatTravailHornDmgMax() +',
    '            rules::mmpGoatTravailChargeBonus() !=',
    '            rules::mmpGoatTravailChargeHornMax()) ++bad;',
    '        // the figurine type table bands, static',
    '        static const int kFigLo[7] = {',
    '            1, 16, 31, 41, 56, 66, 86,',
    '        };',
    '        static const int kFigHi[7] = {',
    '            15, 30, 40, 55, 65, 85, 100,',
    '        };',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::mmpFigTypeLo(i) != kFigLo[i] ||',
    '                rules::mmpFigTypeHi(i) != kFigHi[i]) ++bad;',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpFigTypeLo(i + 1) !=',
    '                rules::mmpFigTypeHi(i) + 1) ++bad;',
    '        // the marble elephant type table bands',
    '        static const int kEleLo[4] = {',
    '            1, 51, 91, 94,',
    '        };',
    '        static const int kEleHi[4] = {',
    '            50, 90, 93, 100,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpElephantTypeLo(i) != kEleLo[i] ||',
    '                rules::mmpElephantTypeHi(i) != kEleHi[i]) ++bad;',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpElephantTypeLo(i + 1) !=',
    '                rules::mmpElephantTypeHi(i) + 1) ++bad;',
    '        // the kMisc3 row this slice pins: row 0,',
    '        // the Figurine band 01-15, no class marks',
    '        if (rules::m3RowLo(0) != 1 ||',
    '            rules::m3RowHi(0) != 15 ||',
    '            rules::m3UsableByCleric(0) ||',
    '            rules::m3UsableByFighter(0) ||',
    '            rules::m3UsableByThief(0) ||',
    '            rules::m3StarCount(0) != 1 ||',
    '            rules::m3IsPerFacetValued(0)) ++bad;',
    '        // the per-hit-die values and the row 4',
    '        // (C, F, T) positive control',
    '        if (rules::m3FigurinePerHitDieXp() != 100 ||',
    '            rules::m3FigurinePerHitDieGp() != 1000 ||',
    '            !rules::m3UsableByCleric(4) ||',
    '            !rules::m3UsableByFighter(4) ||',
    '            !rules::m3UsableByThief(4)) ++bad;',
    '        printf("R266 misc magic prose part 10 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]
RG = rd('regtest.cpp')
ANCHOR = ('    // ---- R227: the wis mental save wiring audit ----')
AUDIT_STR = NL.join(AUDIT)
if ('printf("R266 misc magic prose part 10 pins audit:') in RG:
    already += 1
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
else:
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
    RG = RG.replace(ANCHOR, AUDIT_STR + NL + ANCHOR)
    applied += 1
    assert RG.count(
        'printf("R266 misc magic prose part 10 pins audit:') == 1, \
        'audit printf not unique'
wr('regtest.cpp', RG)

# ---- patch 4: the gap entry ----
GAP = [
    'R266 landed the III.E misc',
    'magic explanation prose part',
    '10 (part2 lines 433-479;',
    'global = 11065 + part2',
    'line), Figurines of',
    'Wondrous Power - pinning',
    'the kMisc3 row 0 (the',
    'Figurine band 01-15, the',
    'single asterisk, per hit',
    'die values 100 xp / 1000',
    'gp, no class marks). ONE',
    'page header inside the',
    'slice strips (the 477',
    'TREASURE page), cutting',
    'the Serpentine Owl',
    'paragraph mid-sentence',
    '(the owl in / smaller',
    'form) - one seam,',
    'restored; the compilation',
    'also wraps the Goat of',
    'Travelling paragraph at a',
    'bare blank line (450/452,',
    'no page header) - one',
    'wrap artifact, restored.',
    'The figurine type table:',
    '01-15 ebony fly, 16-30',
    'golden lions, 31-40 ivory',
    'goats, 41-55 marble',
    'elephant, 56-65 obsidian',
    'steed, 66-85 onyx dog,',
    '86-00 serpentine owl.',
    'The figurines: Ebony Fly',
    '(pony size; AC 4, 4+4 HD,',
    'air maneuver class C; 48',
    'inches unladen, 36 at up',
    'to 210 pounds, 24 at',
    '211-350; 3 uses per week,',
    '12 hours per day), Golden',
    'Lions (2 adult lions, AC',
    '5/6, 5+2 HD; slain: 1',
    'full week; otherwise',
    'daily), Ivory Goats (a',
    'trio; after 3 uses each',
    'loses magic forever) -',
    'Travelling (mount AC 6,',
    '24 hp, 2 horn attacks',
    '1-8, 4 HD; 48 inches at',
    '280 pounds, minus 1 inch',
    'per 14 extra pounds; 24',
    'hours per week; rests 1',
    'day), Travail (hooves',
    '4-10, bite 2-8, horns',
    '2-12; charging: horns',
    'only at +6, 8-18 per',
    'horn; AC 0, 96 hp, 16 HD;',
    'once per month; moves 24',
    'inches), Terror (destrier',
    'mount, 36 inches, AC 2,',
    '48 hp, no own attacks;',
    'horns a +3 spear lance',
    'and a +6 sword; terror',
    'radius 3 inches, save or',
    'lose 50 percent strength',
    'and at least -3 to hit;',
    'once every 2 weeks),',
    'Marble Elephant (hand',
    'size statuette; types',
    '01-50 Asiatic, 51-90',
    'African, 91-93 Mammoth,',
    '94-00 Mastodon; 24 hours',
    'per use, 4 uses per',
    'month), Obsidian Steed (a',
    'nightmare; a good rider:',
    '10 percent per use to the',
    'Hades first layer floor,',
    'then statuette; 24 hours',
    'once per week; astral and',
    'ethereal carry rider and',
    'gear), Onyx Dog (war dog',
    'with int 8-10 and common',
    'speech; scent 100 percent',
    'within 1 hour, minus 10',
    'per hour after;',
    'infravision 90 feet;',
    'hidden 80, invisible 65,',
    'phased 50 percent; 6',
    'hours once per week;',
    'obeys only its owner),',
    'Serpentine Owl (horned',
    'owl AC 7, 24 inches, 2-4',
    'hp, 1-2 damage; giant',
    'form 3 uses only, then',
    'burnout; 95 percent',
    'silent, infravision 90',
    'feet, dark vision as full',
    'light and 2x human; mouse',
    'at 60 feet; counter-',
    'stealth reduced 50',
    'percent; telepathy reports',
    'to owner; int 2-4; giant',
    'form equals the giant',
    'owl). 90 accessors: 86',
    'scalars + 4 walkers (the',
    'figurine type and the',
    'elephant type tables).',
    'New R266 battery audit;',
    'census 184. Next: part 11',
    '- Flask of Curses onward',
    'in part2 from line 481',
    '(global 11546; the',
    'gauntlets, gems, girdles',
    'and helms follow; kMisc3',
    'rows 1+).',
]
GP = rd('tools/dmg_gap_report.md')
if GP.count('R266 landed the III.E misc') == 1:
    already += 1
else:
    TAIL = ('gauntlets and girdles' + NL + 'follow).' + NL +
            NL + 'Categories:')
    assert GP.count(TAIL) == 1, 'R265 gap tail anchor not unique'
    NEWTAIL = ('gauntlets and girdles' + NL + 'follow).' +
               NL + NL + NL.join(GAP) + NL + NL + 'Categories:')
    GP = GP.replace(TAIL, NEWTAIL)
    applied += 1
    assert GP.count('R266 landed the III.E misc') == 1, \
        'gap entry insert failed'
wr('tools/dmg_gap_report.md', GP)

# ---- report ----
assert applied + already == 4, 'patch count wrong'
print('R266 splice: ALL OK (applied %d, already %d)'
      % (applied, already))
print('R266 note: 4 patches; the III.E misc magic')
print('explanation prose part 10 - Figurines of')
print('Wondrous Power, part2 lines 433-479;')
print('census 184.')
COMMIT = ('R266: the III.E misc magic explanation prose part 10'
          ' pinned - Figurines of Wondrous Power in part2 lines'
          ' 433-479 (census 184)')
print('commit: ' + COMMIT)

