#!/usr/bin/env python3
# R267 splice: the III.E misc magic explanation prose
# part 11 pins - Flask of Curses through the Girdle
# of Giant Strength, part2 lines 481-530 (DMG
# p.136-137) - the slice pinning the kMisc3 rows
# 1-9 (the gauntlets carry the (C, F, T) marks on
# rows 4 and 5; the two girdles on rows 8 and 9).
# ONE page header strips (493, the TREASURE page)
# cutting the Gem of Brightness paragraph
# mid-sentence (one seam, restored). 4 patches,
# marker-based idempotence, assert after every
# patch. ZERO apostrophes and ZERO literal
# backslashes in the content below (the printf
# newline is built via BS = chr(92)).

import os
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

# ---- patch 1: rules/miscprose11.h ----
P1 = 'rules/miscprose11.h'
HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose11.h',
    '// R267: the III.E misc magic explanation prose part 11',
    '// (DMG p.136-137) - Flask of Curses through the Girdle',
    '// of Giant Strength, part2 lines 481-530 (global =',
    '// 11065 + part2 line). ONE page header strips (493,',
    '// the TREASURE page) cutting the Gem of Brightness',
    '// paragraph mid-sentence (one seam, restored). 63',
    '// accessors: 49 scalars + 14 array walkers (the giant',
    '// strength and rock hurling tables), no name',
    '// collisions with miscprose1.h through miscprose10.h.',
    '// The slice pins kMisc3 rows 1-9, the (C, F, T) marks',
    '// riding rows 4, 5, 8 and 9. Pure data + helpers,',
    '// header-only (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpFlaskCurseOnFirstOpen() {',
    '    // first unstoppering visits a curse nearby',
    '    return 1;',
    '}',
    '',
    'inline int mmpFlaskHarmlessAfterUse() {',
    '    // subsequently the flask is harmless',
    '    return 1;',
    '}',
    '',
    'inline int mmpGauntDexBoostLow() {',
    '    // +4 dexterity if at 6 or less',
    '    return 4;',
    '}',
    '',
    'inline int mmpGauntDexBoostMid() {',
    '    // +2 dexterity if at 7-13',
    '    return 2;',
    '}',
    '',
    'inline int mmpGauntDexBoostHigh() {',
    '    // +1 dexterity if at 14 or higher',
    '    return 1;',
    '}',
    '',
    'inline int mmpGauntDexThiefLevel() {',
    '    // non-thieves act as a 4th level thief',
    '    return 4;',
    '}',
    '',
    'inline int mmpGauntDexThiefBonusPct() {',
    '    // thieves gain +10 percent for their level',
    '    return 10;',
    '}',
    '',
    'inline int mmpGauntFumbDropPct() {',
    '    // 50 percent each round of dropping held items',
    '    return 50;',
    '}',
    '',
    'inline int mmpGauntFumbDexPenalty() {',
    '    // lowers overall dexterity by 2 points',
    '    return 2;',
    '}',
    '',
    'inline int mmpGauntFumbRemoveCurseOnly() {',
    '    // only remove curse or a wish takes them off',
    '    return 1;',
    '}',
    '',
    'inline int mmpGauntOgreStrength() {',
    '    // 18/00 strength in hands, arms and shoulders',
    '    return 18;',
    '}',
    '',
    'inline int mmpGauntOgreStrengthPercentile() {',
    '    // the 18/00 exceptional percentile',
    '    return 0;',
    '}',
    '',
    'inline int mmpGauntOgreHitBonus() {',
    '    // +3 to hit probability',
    '    return 3;',
    '}',
    '',
    'inline int mmpGauntOgreDmgBonus() {',
    '    // +6 to damage inflicted',
    '    return 6;',
    '}',
    '',
    'inline int mmpGauntSwimUnderwaterInches() {',
    '    // swims as a triton: 15 inches under water',
    '    return 15;',
    '}',
    '',
    'inline int mmpGauntSwimSurfaceInches() {',
    '    // swims as a merman: 18 inches on the surface',
    '    return 18;',
    '}',
    '',
    'inline int mmpGauntSwimClimbSuccessPct() {',
    '    // 95 percent of not slipping while climbing',
    '    return 95;',
    '}',
    '',
    'inline int mmpGauntSwimThiefSuccessTenthPct() {',
    '    // a thief climbs at 99.5 percent (tenths)',
    '    return 995;',
    '}',
    '',
    'inline int mmpGemBrightLightSorts() {',
    '    // the gem emits bright light of 3 sorts',
    '    return 3;',
    '}',
    '',
    'inline int mmpGemBrightConeLengthFeet() {',
    '    // the pale light cone is 10 feet long',
    '    return 10;',
    '}',
    '',
    'inline int mmpGemBrightConeRadiusHalfFeet() {',
    '    // cone radius 2.5 feet at the beam end',
    '    return 5;',
    '}',
    '',
    'inline int mmpGemBrightRayDiameterFeet() {',
    '    // the bright ray is 1 feet diameter',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightRayLengthFeet() {',
    '    // the bright ray is 50 feet long',
    '    return 50;',
    '}',
    '',
    'inline int mmpGemBrightDazzleMinRounds() {',
    '    // dazzled 1-4 rounds',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightDazzleMaxRounds() {',
    '    // dazzled 1-4 rounds',
    '    return 4;',
    '}',
    '',
    'inline int mmpGemBrightRayCharges() {',
    '    // the ray use expends 1 energy charge',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightFlashLengthFeet() {',
    '    // the blinding flash cone is 30 feet long',
    '    return 30;',
    '}',
    '',
    'inline int mmpGemBrightFlashRadiusFeet() {',
    '    // flash cone radius 5 feet at its terminus',
    '    return 5;',
    '}',
    '',
    'inline int mmpGemBrightBlindMinRounds() {',
    '    // blinded 1-4 rounds',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightBlindMaxRounds() {',
    '    // blinded 1-4 rounds',
    '    return 4;',
    '}',
    '',
    'inline int mmpGemBrightEyePenaltyMin() {',
    '    // permanent eye damage: -1 at least',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightEyePenaltyMax() {',
    '    // permanent eye damage: up to -4',
    '    return 4;',
    '}',
    '',
    'inline int mmpGemBrightFlashCharges() {',
    '    // the flash use expends 5 charges',
    '    return 5;',
    '}',
    '',
    'inline int mmpGemBrightTotalCharges() {',
    '    // 50 charges, cannot be recharged',
    '    return 50;',
    '}',
    '',
    'inline int mmpGemBrightDarknessDrainCharges() {',
    '    // a darkness spell drains 1 charge',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightDarknessRoundUseless() {',
    '    // or makes the gem useless for 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightDarknessDayUseless() {',
    '    // continual darkness: useless for 1 day',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemBrightDarknessExpelCharges() {',
    '    // or the owner expends 5 charges',
    '    return 5;',
    '}',
    '',
    'inline int mmpGemSeeCursoryRangeInches() {',
    '    // cursory scan range 30 inches',
    '    return 30;',
    '}',
    '',
    'inline int mmpGemSeeCarefulRangeInches() {',
    '    // small things: 10 inches',
    '    return 10;',
    '}',
    '',
    'inline int mmpGemSeeCursoryAreaFeet() {',
    '    // 1 round scans a 200 feet square',
    '    return 200;',
    '}',
    '',
    'inline int mmpGemSeeCursoryRounds() {',
    '    // the cursory scan takes 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpGemSeeCarefulAreaFeet() {',
    '    // 2 rounds view a 100 feet square',
    '    return 100;',
    '}',
    '',
    'inline int mmpGemSeeCarefulRounds() {',
    '    // the careful view takes 2 rounds',
    '    return 2;',
    '}',
    '',
    'inline int mmpGemSeeHallucinationPct() {',
    '    // 5 percent chance of an hallucination',
    '    return 5;',
    '}',
    '',
    'inline int mmpGirdleSexWishRestorePct() {',
    '    // a wish restores the sex: 50 percent',
    '    return 50;',
    '}',
    '',
    'inline int mmpGirdleSexSexlessPct() {',
    '    // 10 percent of these remove all sex',
    '    return 10;',
    '}',
    '',
    'inline int mmpGirdleGiantTypeCount() {',
    '    // the six giant strength types',
    '    return 6;',
    '}',
    '',
    'inline int mmpGirdleGiantRockDmgMin() {',
    '    // every type hurls rocks from 1 die',
    '    return 1;',
    '}',
    '',
    'inline int mmpGirdleGiantDiceLo(int i) {',
    '    // the type dice band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        1, 31, 51, 71, 86, 96,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantDiceHi(int i) {',
    '    // the type dice band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        30, 50, 70, 85, 95, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantStrength(int i) {',
    '    // the strength and rating column; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        19, 20, 21, 22, 23, 24,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantHitBonus(int i) {',
    '    // the to hit column; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        3, 3, 4, 4, 5, 6,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantDmgBonus(int i) {',
    '    // the damage column; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        7, 8, 9, 10, 11, 12,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantOpenDoorsTop(int i) {',
    '    // open doors numerator (7 in 8); i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        7, 7, 9, 11, 11, 19,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantOpenDoorsBottom(int i) {',
    '    // open doors denominator (in 8); i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        8, 8, 10, 12, 12, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantOpenChances(int i) {',
    '    // the parenthesized chances (3 of 6); i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        3, 3, 4, 4, 5, 7,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantOpenOutOf(int i) {',
    '    // chances out of 6 (8 for storm); i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        6, 6, 6, 6, 6, 8,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantWeightAllowance(int i) {',
    '    // the weight allowance column; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        4500, 5000, 6000, 7500, 9000, 12000,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantRangeInches(int i) {',
    '    // the rock range column; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        8, 16, 10, 12, 14, 16,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantRockDmgMax(int i) {',
    '    // the rock base damage top die; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        6, 12, 8, 8, 10, 12,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantRockWeight(int i) {',
    '    // the approximate average missile weight; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        140, 198, 156, 170, 184, 212,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpGirdleGiantBendBarsPct(int i) {',
    '    // bend bars and lift gates percent; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        50, 60, 70, 80, 90, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    '}  // namespace rules',
]
if os.path.exists(os.path.join(ROOT, P1)):
    already += 1
    assert rd(P1) == NL.join(HDR), P1 + ' exists but differs'
else:
    wr(P1, NL.join(HDR))
    applied += 1
    assert rd(P1) == NL.join(HDR), P1 + ' write mismatch'
assert rd(P1).count(
    'R267: the III.E misc magic explanation prose part 11') == 1

# ---- patch 2: the regtest include ----
INC_OLD = ('#include "rules/miscprose10.h"  // R266: the III.E misc'
           ' magic explanation prose part 10 pins')
INC_NEW = ('#include "rules/miscprose11.h"  // R267: the III.E misc'
           ' magic explanation prose part 11 pins')
RG = rd('regtest.cpp')
if INC_NEW in RG:
    already += 1
    assert RG.count(INC_NEW) == 1, 'include not unique'
else:
    assert RG.count(INC_OLD) == 1, 'R266 include anchor missing'
    RG = RG.replace(INC_OLD, INC_OLD + NL + INC_NEW)
    applied += 1
    assert RG.count(INC_NEW) == 1, 'include insert failed'
wr('regtest.cpp', RG)

# ---- patch 3: the R267 audit block ----
AUDIT = [
    '    // ---- R267: the III.E misc magic explanation',
    '    // prose part 11 ----',
    '    // Flask of Curses through the Girdle of Giant',
    '    // Strength, part2 lines 481-530 - the slice',
    '    // pinning the kMisc3 rows 1-9.',
    '    {',
    '        int bad = 0;',
    '        if (rules::mmpFlaskCurseOnFirstOpen() != 1 ||',
    '            rules::mmpFlaskHarmlessAfterUse() != 1) ++bad;',
    '        if (rules::mmpGauntDexBoostLow() != 4 ||',
    '            rules::mmpGauntDexBoostMid() != 2 ||',
    '            rules::mmpGauntDexBoostHigh() != 1 ||',
    '            rules::mmpGauntDexThiefLevel() != 4 ||',
    '            rules::mmpGauntDexThiefBonusPct() != 10) ++bad;',
    '        if (rules::mmpGauntFumbDropPct() != 50 ||',
    '            rules::mmpGauntFumbDexPenalty() != 2 ||',
    '            rules::mmpGauntFumbRemoveCurseOnly() != 1 ||',
    '            rules::mmpGauntOgreStrength() != 18 ||',
    '            rules::mmpGauntOgreStrengthPercentile() != 0 ||',
    '            rules::mmpGauntOgreHitBonus() != 3 ||',
    '            rules::mmpGauntOgreDmgBonus() != 6) ++bad;',
    '        if (rules::mmpGauntSwimUnderwaterInches() != 15 ||',
    '            rules::mmpGauntSwimSurfaceInches() != 18 ||',
    '            rules::mmpGauntSwimClimbSuccessPct() != 95 ||',
    '            rules::mmpGauntSwimThiefSuccessTenthPct() !=',
    '            995) ++bad;',
    '        if (rules::mmpGemBrightLightSorts() != 3 ||',
    '            rules::mmpGemBrightConeLengthFeet() != 10 ||',
    '            rules::mmpGemBrightConeRadiusHalfFeet() != 5 ||',
    '            rules::mmpGemBrightRayDiameterFeet() != 1 ||',
    '            rules::mmpGemBrightRayLengthFeet() != 50 ||',
    '            rules::mmpGemBrightDazzleMinRounds() != 1 ||',
    '            rules::mmpGemBrightDazzleMaxRounds() != 4 ||',
    '            rules::mmpGemBrightRayCharges() != 1) ++bad;',
    '        if (rules::mmpGemBrightFlashLengthFeet() != 30 ||',
    '            rules::mmpGemBrightFlashRadiusFeet() != 5 ||',
    '            rules::mmpGemBrightBlindMinRounds() != 1 ||',
    '            rules::mmpGemBrightBlindMaxRounds() != 4 ||',
    '            rules::mmpGemBrightEyePenaltyMin() != 1 ||',
    '            rules::mmpGemBrightEyePenaltyMax() != 4 ||',
    '            rules::mmpGemBrightFlashCharges() != 5 ||',
    '            rules::mmpGemBrightTotalCharges() != 50) ++bad;',
    '        if (rules::mmpGemBrightDarknessDrainCharges() != 1 ||',
    '            rules::mmpGemBrightDarknessRoundUseless() != 1 ||',
    '            rules::mmpGemBrightDarknessDayUseless() != 1 ||',
    '            rules::mmpGemBrightDarknessExpelCharges() !=',
    '            5) ++bad;',
    '        if (rules::mmpGemSeeCursoryRangeInches() != 30 ||',
    '            rules::mmpGemSeeCarefulRangeInches() != 10 ||',
    '            rules::mmpGemSeeCursoryAreaFeet() != 200 ||',
    '            rules::mmpGemSeeCursoryRounds() != 1 ||',
    '            rules::mmpGemSeeCarefulAreaFeet() != 100 ||',
    '            rules::mmpGemSeeCarefulRounds() != 2 ||',
    '            rules::mmpGemSeeHallucinationPct() != 5) ++bad;',
    '        if (rules::mmpGirdleSexWishRestorePct() != 50 ||',
    '            rules::mmpGirdleSexSexlessPct() != 10 ||',
    '            rules::mmpGirdleGiantTypeCount() != 6 ||',
    '            rules::mmpGirdleGiantRockDmgMin() != 1) ++bad;',
    '        // the arithmetic: the two 5-charge expends',
    '        if (rules::mmpGemBrightFlashCharges() !=',
    '            rules::mmpGemBrightDarknessExpelCharges() ||',
    '            rules::mmpGemBrightDazzleMinRounds() !=',
    '            rules::mmpGemBrightBlindMinRounds() ||',
    '            rules::mmpGemBrightDazzleMaxRounds() !=',
    '            rules::mmpGemBrightBlindMaxRounds()) ++bad;',
    '        // the giant strength ladders: strength and',
    '        // damage climb by 1, bend bars by 10',
    '        for (int i = 0; i < 5; ++i)',
    '            if (rules::mmpGirdleGiantStrength(i + 1) !=',
    '                rules::mmpGirdleGiantStrength(i) + 1 ||',
    '                rules::mmpGirdleGiantDmgBonus(i + 1) !=',
    '                rules::mmpGirdleGiantDmgBonus(i) + 1 ||',
    '                rules::mmpGirdleGiantBendBarsPct(i + 1) !=',
    '                rules::mmpGirdleGiantBendBarsPct(i) +',
    '                10) ++bad;',
    '        // the dice bands run 01-00 without gaps',
    '        for (int i = 0; i < 5; ++i)',
    '            if (rules::mmpGirdleGiantDiceLo(i + 1) !=',
    '                rules::mmpGirdleGiantDiceHi(i) + 1) ++bad;',
    '        if (rules::mmpGirdleGiantDiceLo(0) != 1 ||',
    '            rules::mmpGirdleGiantDiceHi(5) != 100) ++bad;',
    '        // the static twin of the printed tables',
    '        static const int kStr[6] = {',
    '            19, 20, 21, 22, 23, 24,',
    '        };',
    '        static const int kHit[6] = {',
    '            3, 3, 4, 4, 5, 6,',
    '        };',
    '        static const int kTop[6] = {',
    '            7, 7, 9, 11, 11, 19,',
    '        };',
    '        static const int kBot[6] = {',
    '            8, 8, 10, 12, 12, 20,',
    '        };',
    '        static const int kCh[6] = {',
    '            3, 3, 4, 4, 5, 7,',
    '        };',
    '        static const int kOf[6] = {',
    '            6, 6, 6, 6, 6, 8,',
    '        };',
    '        static const int kWa[6] = {',
    '            4500, 5000, 6000, 7500,',
    '            9000, 12000,',
    '        };',
    '        static const int kRg[6] = {',
    '            8, 16, 10, 12, 14, 16,',
    '        };',
    '        static const int kRd[6] = {',
    '            6, 12, 8, 8, 10, 12,',
    '        };',
    '        static const int kRw[6] = {',
    '            140, 198, 156, 170,',
    '            184, 212,',
    '        };',
    '        static const int kBb[6] = {',
    '            50, 60, 70, 80, 90, 100,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpGirdleGiantStrength(i) != kStr[i] ||',
    '                rules::mmpGirdleGiantHitBonus(i) != kHit[i] ||',
    '                rules::mmpGirdleGiantOpenDoorsTop(i) !=',
    '                kTop[i] ||',
    '                rules::mmpGirdleGiantOpenDoorsBottom(i) !=',
    '                kBot[i] ||',
    '                rules::mmpGirdleGiantOpenChances(i) !=',
    '                kCh[i] ||',
    '                rules::mmpGirdleGiantOpenOutOf(i) !=',
    '                kOf[i]) ++bad;',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpGirdleGiantWeightAllowance(i) !=',
    '                kWa[i] ||',
    '                rules::mmpGirdleGiantRangeInches(i) !=',
    '                kRg[i] ||',
    '                rules::mmpGirdleGiantRockDmgMax(i) !=',
    '                kRd[i] ||',
    '                rules::mmpGirdleGiantRockWeight(i) !=',
    '                kRw[i] ||',
    '                rules::mmpGirdleGiantBendBarsPct(i) !=',
    '                kBb[i]) ++bad;',
    '        // the kMisc3 rows this slice pins: 1-9,',
    '        // the (C, F, T) marks on rows 4, 5, 8, 9',
    '        static const int kLo[9] = {',
    '            16, 17, 19, 21, 23, 26, 27, 28, 29,',
    '        };',
    '        static const int kHi[9] = {',
    '            16, 18, 20, 22, 25, 26, 27, 28, 29,',
    '        };',
    '        static const int kMk[9] = {',
    '            0, 0, 0, 1, 1, 0, 0, 1, 1,',
    '        };',
    '        for (int i = 0; i < 9; ++i)',
    '            if (rules::m3RowLo(1 + i) != kLo[i] ||',
    '                rules::m3RowHi(1 + i) != kHi[i]) ++bad;',
    '        for (int i = 0; i < 9; ++i)',
    '            if (rules::m3UsableByCleric(1 + i) != kMk[i] ||',
    '                rules::m3UsableByFighter(1 + i) !=',
    '                kMk[i] ||',
    '                rules::m3UsableByThief(1 + i) !=',
    '                kMk[i] ||',
    '                rules::m3StarCount(1 + i) ||',
    '                rules::m3IsPerFacetValued(1 + i)) ++bad;',
    '        printf("R267 misc magic prose part 11 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]
RG = rd('regtest.cpp')
ANCHOR = ('    // ---- R227: the wis mental save wiring audit ----')
AUDIT_STR = NL.join(AUDIT)
if ('printf("R267 misc magic prose part 11 pins audit:') in RG:
    already += 1
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
else:
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
    RG = RG.replace(ANCHOR, AUDIT_STR + NL + ANCHOR)
    applied += 1
    assert RG.count(
        'printf("R267 misc magic prose part 11 pins audit:') == 1, \
        'audit printf not unique'
wr('regtest.cpp', RG)

# ---- patch 4: the gap entry ----
GAP = [
    'R267 landed the III.E misc',
    'magic explanation prose part',
    '11 (part2 lines 481-530;',
    'global = 11065 + part2',
    'line), Flask of Curses',
    'through the Girdle of Giant',
    'Strength - pinning the',
    'kMisc3 rows 1-9, the (C, F,',
    'T) marks riding rows 4',
    '(Ogre Power), 5 (Swimming',
    'and Climbing), 8',
    '(Femininity/Masculinity) and',
    '9 (Giant Strength). ONE',
    'page header inside the slice',
    'strips (the 493 TREASURE',
    'page), cutting the Gem of',
    'Brightness paragraph',
    'mid-sentence (at the /',
    'option of the gem owner) -',
    'one seam, restored. The',
    'items: Flask of Curses',
    '(beaker-like, detection',
    'hides its nature; first',
    'unstopper curses nearby,',
    'then harmless), Gauntlets of',
    'Dexterity (+4 if dex 6 or',
    'less, +2 at 7-13, +1 at 14+;',
    'non-thieves as a 4th level',
    'thief, thieves +10 percent),',
    'Gauntlets of Fumbling (mimic',
    'dexterity or ogre power;',
    'curse: 50 percent drop',
    'chance per round, not both',
    'singly; dex -2; remove',
    'curse or wish only),',
    'Gauntlets of Ogre Power',
    '(18/00 strength; +3 to hit,',
    '+6 damage), Gauntlets of',
    'Swimming and Climbing',
    '(triton 15 inches under,',
    'merman 18 on top; no water',
    'breathing; climb 95',
    'percent, thieves 99.5), Gem',
    'of Brightness (3 lights:',
    'pale cone 10 feet at 2.5',
    'radius free; ray 1 feet wide',
    '50 long, dazzle 1-4 rounds,',
    '1 charge; flash cone 30',
    'feet at 5 radius, blind',
    '1-4 rounds then -1 to -4',
    'permanent eye damage, 5',
    'charges; cure blindness or',
    'heal; 50 charges, no',
    'recharge; darkness drains 1',
    'or 1 round useless;',
    'continual darkness: 1 day',
    'useless or 5 charges), Gem',
    'of Seeing (30 inches',
    'cursory, 10 careful; 1',
    'round per 200 feet square,',
    '2 per 100; 5 percent',
    'hallucination), Girdle of',
    'Femininity/Masculinity',
    '(changes sex, then',
    'powerless; wish 50 percent,',
    'a god certain; 10 percent',
    'remove all sex), Girdle of',
    'Giant Strength (Hill 19',
    '+3/+7, Stone 20 +3/+8,',
    'Frost 21 +4/+9, Fire 22',
    '+4/+10, Cloud 23 +5/+11,',
    'Storm 24 +6/+12; open',
    'doors 7 in 8 (3), 7 in 8',
    '(3), 9 in 10 (4), 11 in 12',
    '(4), 11 in 12 (5), 19 in 20',
    '(7 in 8); weight allowance',
    '+4500 to +12000; rock',
    'range 8 to 16 inches,',
    'damage 1-6 to 1-12,',
    'missile weight 140 to 212,',
    'bend bars 50 to 100',
    'percent; not cumulative',
    'except with ogre power',
    'gauntlets and magic war',
    'hammers). 63 accessors:',
    '49 scalars + 14 walkers',
    '(the strength and rock',
    'tables; the strength,',
    'damage and bend-bars',
    'ladders are arithmetic',
    'checks). New R267 battery',
    'audit; census 185. Next:',
    'part 12 - Helm of',
    'Brilliance onward in',
    'part2 from line 532',
    '(global 11597; the helm',
    'jewel functions, horns,',
    'horseshoes, incenses and',
    'instruments follow; kMisc3',
    'rows 10+).',
]
GP = rd('tools/dmg_gap_report.md')
if GP.count('R267 landed the III.E misc') == 1:
    already += 1
else:
    TAIL = ('rows 1+).' + NL + NL + 'Categories:')
    assert GP.count(TAIL) == 1, 'R266 gap tail anchor not unique'
    NEWTAIL = ('rows 1+).' + NL + NL + NL.join(GAP) +
               NL + NL + 'Categories:')
    GP = GP.replace(TAIL, NEWTAIL)
    applied += 1
    assert GP.count('R267 landed the III.E misc') == 1, \
        'gap entry insert failed'
wr('tools/dmg_gap_report.md', GP)

# ---- report ----
assert applied + already == 4, 'patch count wrong'
print('R267 splice: ALL OK (applied %d, already %d)'
      % (applied, already))
print('R267 note: 4 patches; the III.E misc magic')
print('explanation prose part 11 - Flask of Curses')
print('through Girdle of Giant Strength, part2')
print('lines 481-530; census 185.')
COMMIT = ('R267: the III.E misc magic explanation prose part 11'
          ' pinned - Flask of Curses through the Girdle of Giant'
          ' Strength in part2 lines 481-530 (census 185)')
print('commit: ' + COMMIT)

