#!/usr/bin/env python3
# R268 splice: the III.E misc magic explanation prose
# part 12 pins - Helm of Brilliance through the Horn
# of Bubbles, part2 lines 532-579 (DMG p.137-139) -
# the slice pinning the kMisc3 rows 10-17 (no class
# marks and no asterisks ride these rows). ONE page
# header inside the slice (541, the TREASURE page)
# falls between the jewel functions table and the
# Each gem paragraph of the Brilliance item. The
# jewel functions table: the book upload flattens
# the four gem rows into the Diamond cell (the Ruby,
# Fire Opal and Opal cells empty) - the four-row
# table restored from the 1eonline.info compilation
# (the R175 precedent). 4 patches, marker-based
# idempotence, assert after every patch. ZERO
# apostrophes and ZERO literal backslashes in the
# content below (the printf newline is built via
# BS = chr(92)).

import os
import re
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

# ---- patch 1: rules/miscprose12.h ----
P1 = 'rules/miscprose12.h'
HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose12.h',
    '// R268: the III.E misc magic explanation prose part 12',
    '// (DMG p.137-139) - Helm of Brilliance through the Horn',
    '// of Bubbles, part2 lines 532-579 (global =',
    '// 11065 + part2 line). ONE page header inside the slice',
    '// (541, the TREASURE page) falls between the jewel',
    '// functions table and the Each gem paragraph of the',
    '// Brilliance item. The jewel functions table: the book',
    '// upload flattens the four gem rows into the Diamond',
    '// cell (the Ruby, Fire Opal and Opal cells empty) -',
    '// the four-row table restored from the compilation',
    '// (the R175 precedent): Diamond prismatic spray (7th',
    '// illusionist), Ruby wall of fire (5th druid), Fire',
    '// Opal fireball (3rd magic-user), Opal light (1st',
    '// cleric). 91 accessors: 87 scalars + 4 array walkers',
    '// (the jewel functions table), no name collisions with',
    '// miscprose1.h through miscprose11.h.',
    '// The slice pins kMisc3 rows 10-17, no class marks and',
    '// no asterisks ride these rows. Pure data + helpers,',
    '// header-only (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpHelmBrilCommandWordOnly() {',
    '    // functions only upon the utterance of a',
    '    // special command word',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilTrueNatureVisible() {',
    '    // when empowered the true nature of the helm',
    '    // is visible to all',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilArmorPlus() {',
    '    // the helm is armor of +2 value',
    '    return 2;',
    '}',
    '',
    'inline int mmpHelmBrilDiamondCount() {',
    '    // set with 10 diamonds of large size',
    '    return 10;',
    '}',
    '',
    'inline int mmpHelmBrilRubyCount() {',
    '    // 20 rubies',
    '    return 20;',
    '}',
    '',
    'inline int mmpHelmBrilFireOpalCount() {',
    '    // 30 fire opals',
    '    return 30;',
    '}',
    '',
    'inline int mmpHelmBrilOpalCount() {',
    '    // 40 opals',
    '    return 40;',
    '}',
    '',
    'inline int mmpHelmBrilScintillatesInBrightLight() {',
    '    // struck by bright light it scintillates and',
    '    // sends reflective rays from the crown-like',
    '    // spikes set with gems',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilJewelUseSegments() {',
    '    // each gem performs its spell-like power in',
    '    // but 1 segment',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilJewelUsableOnce() {',
    '    // each gem is usable only once',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilUsesPerRound() {',
    '    // the helm may be thus used once per round',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilSpellLevelDoublingFactor() {',
    '    // the level of the spell is doubled for range,',
    '    // duration and such considerations',
    '    return 2;',
    '}',
    '',
    'inline int mmpHelmBrilUndeadGlowRangeFeet() {',
    '    // glows with a bluish light when undead are',
    '    // within 30 feet',
    '    return 30;',
    '}',
    '',
    'inline int mmpHelmBrilUndeadPainDmgMin() {',
    '    // the light causes pain and damage to undead',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilUndeadPainDmgMax() {',
    '    // 1-6 points of damage',
    '    return 6;',
    '}',
    '',
    'inline int mmpHelmBrilUndeadExemptKinds() {',
    '    // save skeletons and zombies take neither',
    '    // the pain nor the damage',
    '    return 2;',
    '}',
    '',
    'inline int mmpHelmBrilFlameSwordEffectRounds() {',
    '    // 1 round of time is required to effect',
    '    // this fire',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilFlameSwordAdditional() {',
    '    // the sword of flame is additional to the',
    '    // other special properties of the sword,',
    '    // if any',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilProduceFlameDruidLevel() {',
    '    // the wearer may produce flame just as if',
    '    // a 5th level druid',
    '    return 5;',
    '}',
    '',
    'inline int mmpHelmBrilFireResistRingStrength() {',
    '    // protected just as if a double strength',
    '    // fire resistance ring were worn',
    '    return 2;',
    '}',
    '',
    'inline int mmpHelmBrilFireResistAugmentable() {',
    '    // this protection cannot be augmented by',
    '    // further magical means',
    '    return 0;',
    '}',
    '',
    'inline int mmpHelmBrilPowderOnExpenditure() {',
    '    // once all jewels lose their magic the helm',
    '    // loses its powers and the gems turn to',
    '    // worthless powder',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilJewelRemovalDestroys() {',
    '    // removing a jewel destroys the gem',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilJewelRemagickable() {',
    '    // the gems may not be re-magicked',
    '    return 0;',
    '}',
    '',
    'inline int mmpHelmBrilRetrySaveWithoutMagic() {',
    '    // a failed save versus a magical fire attack',
    '    // demands another saving throw for the',
    '    // helmet without magical additions',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilOverloadDetonatesRemaining() {',
    '    // if the helmet save fails the remaining',
    '    // gems all overload and detonate',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilOverloadEffectsInMultiple() {',
    '    // the detonation causes in multiple',
    '    // whatever effects the gems would',
    '    // normally have',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmBrilJewelRowCount() {',
    '    // the restored jewel functions table rows',
    '    return 4;',
    '}',
    '',
    'inline int mmpHelmBrilJewelGemCount(int i) {',
    '    // the stones set per gem row; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        10, 20, 30, 40,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHelmBrilJewelSpellLevel(int i) {',
    '    // the restored spell levels: 7th, 5th,',
    '    // 3rd, 1st; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        7, 5, 3, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHelmBrilJewelCasterKind(int i) {',
    '    // 0 illusionist, 1 druid, 2 magic-user,',
    '    // 3 cleric; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        0, 1, 2, 3,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHelmBrilJewelFunctionKind(int i) {',
    '    // 0 prismatic spray, 1 wall of fire,',
    '    // 2 fireball, 3 light; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        0, 1, 2, 3,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHelmComprStrangeTonguesPct() {',
    '    // understand 90 percent of strange tongues',
    '    // and writings',
    '    return 90;',
    '}',
    '',
    'inline int mmpHelmComprMagicalWritingsPct() {',
    '    // 80 percent of magical writings',
    '    return 80;',
    '}',
    '',
    'inline int mmpHelmComprAllOrNone() {',
    '    // the figures apply to whether all or none',
    '    // of the tongue or inscription is',
    '    // understandable',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmComprImpliesSpellUse() {',
    '    // understanding does not necessarily imply',
    '    // spell use',
    '    return 0;',
    '}',
    '',
    'inline int mmpHelmComprHelmetOfAcValue() {',
    '    // equal to a normal helmet of the type',
    '    // accompanying armor class 5',
    '    return 5;',
    '}',
    '',
    'inline int mmpHelmOppAlignIndeterminateDweomer() {',
    '    // by test it radiates an indeterminate',
    '    // dweomer',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmOppAlignCurseOnDonning() {',
    '    // once placed upon the head the curse',
    '    // immediately takes place',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmOppAlignAbsoluteKinds() {',
    '    // neutral goes to some absolute',
    '    // commitment: LE, LG, CE or CG',
    '    return 4;',
    '}',
    '',
    'inline int mmpHelmOppAlignAlterationDesired() {',
    '    // the alteration, once effected, is',
    '    // desired by the individual the magic',
    '    // changed',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmOppAlignRestoreSpellKinds() {',
    '    // only a wish, or alter reality, can',
    '    // restore the former alignment',
    '    return 2;',
    '}',
    '',
    'inline int mmpHelmOppAlignSelfRestoreAttempts() {',
    '    // the affected individual will make no',
    '    // attempt to return to the former',
    '    // alignment',
    '    return 0;',
    '}',
    '',
    'inline int mmpHelmOppAlignPaladinQuestAndAtone() {',
    '    // a paladin must undergo a special quest',
    '    // and atone for the curse to be',
    '    // obliterated',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmOppAlignPowersAfterFunctioning() {',
    '    // once functioned the helm loses all of',
    '    // its magical properties',
    '    return 0;',
    '}',
    '',
    'inline int mmpHelmTelepathyRangeInches() {',
    '    // the thoughts of creatures within a',
    '    // 6 inch range',
    '    return 6;',
    '}',
    '',
    'inline int mmpHelmTelepathyStoneBarrierFeet() {',
    '    // no more than 3 feet of solid stone',
    '    // between the wearer and the creatures',
    '    return 3;',
    '}',
    '',
    'inline int mmpHelmTelepathyIronBarrierQuarterFeet() {',
    '    // a quarter foot of iron',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTelepathyLeadGoldSheetBlocks() {',
    '    // any solid sheeting of lead or gold',
    '    // blocks the pick-up entirely',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTelepathyDirectional() {',
    '    // the thought pick-up is directional',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTelepathyConsciousEffort() {',
    '    // conscious effort must be made to pick',
    '    // up thoughts',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTelepathySuggestPctPer2IntAbove() {',
    '    // for every 2 points of intelligence',
    '    // greater than the subject the wearer is',
    '    // 5 percent more likely to implant',
    '    return 5;',
    '}',
    '',
    'inline int mmpHelmTelepathySuggestPctPer1IntBelow() {',
    '    // for every 1 point lower the probability',
    '    // decreases by 5 percent',
    '    return 5;',
    '}',
    '',
    'inline int mmpHelmTelepathySavePenaltyPer2IntBelow() {',
    '    // the subject saves versus magic with a',
    '    // minus 1 for every 2 points of',
    '    // intelligence lower than the telepathist',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTelepathySaveBonusPer1IntAbove() {',
    '    // the subject saves with a plus 1 for',
    '    // every 1 point of intelligence higher',
    '    // than the wearer of the helm',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTelepathyEqualIntSaveAdjustment() {',
    '    // if intelligence is equal no adjustment',
    '    // is made',
    '    return 0;',
    '}',
    '',
    'inline int mmpHelmTelepathyPsionicAttackBonus() {',
    '    // a plus 4 with respect to psionic related',
    '    // attacks',
    '    return 4;',
    '}',
    '',
    'inline int mmpHelmTelepathyPsionicStrengthBonus() {',
    '    // increases total psionic strength by',
    '    // 40 points',
    '    return 40;',
    '}',
    '',
    'inline int mmpHelmTeleportPerDay() {',
    '    // the wearer may teleport once per day,',
    '    // exactly as if a magic-user: destination',
    '    // known, a risk involved',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTeleportMuRefreshRepeats() {',
    '    // a magic-user may memorize the spell and',
    '    // use the helm to refresh memory,',
    '    // repeating the spell up to 3 times',
    '    return 3;',
    '}',
    '',
    'inline int mmpHelmTeleportMuStillPersonalAfterRefresh() {',
    '    // and still be able to personally',
    '    // teleport by means of the helm',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmTeleportMuUncastPersonalCount() {',
    '    // while the spell is retained uncast the',
    '    // magic-user can personally teleport up',
    '    // to 6 times before the memory is lost',
    '    return 6;',
    '}',
    '',
    'inline int mmpHelmTeleportUsageAfterMemoryLost() {',
    '    // even then a usage of the helm remains',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmUnderwaterSeeAndBreathe() {',
    '    // the possessor is able to both see and',
    '    // breathe under water',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmUnderwaterLensCompartments() {',
    '    // small lenses drawn across the device',
    '    // from compartments on either side',
    '    return 2;',
    '}',
    '',
    'inline int mmpHelmUnderwaterVisionFactor() {',
    '    // see 5 times farther than normal water',
    '    // and light conditions allow for normal',
    '    // human vision',
    '    return 5;',
    '}',
    '',
    'inline int mmpHelmUnderwaterObstructionsBlock() {',
    '    // weeds, obstructions and such block',
    '    // vision in the usual manner',
    '    return 1;',
    '}',
    '',
    'inline int mmpHelmUnderwaterAirGlobeUntilRepeat() {',
    '    // the command word creates a globe of air',
    '    // around the head, maintained until the',
    '    // word is again spoken',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornBlastingConeLengthInches() {',
    '    // a cone of sound 12 inches long',
    '    return 12;',
    '}',
    '',
    'inline int mmpHornBlastingConeBaseWidthInches() {',
    '    // 3 inches wide at the base',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornBlastingSaveStunRounds() {',
    '    // those saving versus magic are stunned',
    '    // for 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornBlastingSaveDeafRounds() {',
    '    // those saving are deafened for 2',
    '    return 2;',
    '}',
    '',
    'inline int mmpHornBlastingFailDmgMin() {',
    '    // those failing the save sustain damage',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornBlastingFailDmgMax() {',
    '    // 1-10 hit points of damage',
    '    return 10;',
    '}',
    '',
    'inline int mmpHornBlastingFailStunRounds() {',
    '    // those failing are stunned for 2 rounds',
    '    return 2;',
    '}',
    '',
    'inline int mmpHornBlastingFailDeafRounds() {',
    '    // those failing are deafened for 4',
    '    return 4;',
    '}',
    '',
    'inline int mmpHornBlastingPulseWidthFeet() {',
    '    // a wave of ultrasonic sound, a 1 foot',
    '    // wide pulse',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornBlastingPulseLengthInches() {',
    '    // the pulse is 10 inches long',
    '    return 10;',
    '}',
    '',
    'inline int mmpHornBlastingCatapultMultiplier() {',
    '    // the weakening of metal, stone and wood',
    '    // equals 3 times a large catapult',
    '    // missile hit',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornBlastingCatapultHitDamage() {',
    '    // the large catapult missile hit damage',
    '    // (derived: 18 structural at triple)',
    '    return 6;',
    '}',
    '',
    'inline int mmpHornBlastingStructuralPoints() {',
    '    // 18 structural points, sufficient to',
    '    // smash a drawbridge or flatten a normal',
    '    // cottage',
    '    return 18;',
    '}',
    '',
    'inline int mmpHornBlastingExplodePctPerExtraUse() {',
    '    // winded magically more than once per',
    '    // day: a 10 percent cumulative chance to',
    '    // explode itself',
    '    return 10;',
    '}',
    '',
    'inline int mmpHornBlastingExplodeDmgMin() {',
    '    // the explosion inflicts 5-50 hit points',
    '    // of damage on the person sounding it',
    '    return 5;',
    '}',
    '',
    'inline int mmpHornBlastingExplodeDmgMax() {',
    '    // the 5-50 upper edge',
    '    return 50;',
    '}',
    '',
    'inline int mmpHornBlastingCharges() {',
    '    // there are no charges upon a horn',
    '    return 0;',
    '}',
    '',
    'inline int mmpHornBlastingShiverPctPerUse() {',
    '    // each magical use: a 2 percent',
    '    // cumulative chance of shivering itself',
    '    return 2;',
    '}',
    '',
    'inline int mmpHornBlastingShiverWielderDamage() {',
    '    // a shiver inflicts no damage on the',
    '    // character blowing it',
    '    return 0;',
    '}',
    '',
    'inline int mmpHornBubblesBlindRoundsMin() {',
    '    // the bubbles surround and blind the',
    '    // individual who blew the horn',
    '    return 2;',
    '}',
    '',
    'inline int mmpHornBubblesBlindRoundsMax() {',
    '    // blinded for 2-20 rounds',
    '    return 20;',
    '}',
    '',
    'inline int mmpHornBubblesOnlyWhenSlayerSeeks() {',
    '    // the bubbles only appear in the presence',
    '    // of a creature actively seeking to slay',
    '    // the character who winded the horn',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornBubblesAppearanceMayDelay() {',
    '    // the appearance might be delayed for a',
    '    // very short or extremely lengthy period',
    '    return 1;',
    '}',
    '',
    '}  // namespace rules',
]

# ---- patch 3 content: the R268 audit block ----
AUDIT = [
    '    // ---- R268: the III.E misc magic explanation',
    '    // prose part 12 ----',
    '    // Helm of Brilliance through the Horn of',
    '    // Bubbles, part2 lines 532-579 - the slice',
    '    // pinning the kMisc3 rows 10-17.',
    '    {',
    '        int bad = 0;',
    '        if (rules::mmpHelmBrilCommandWordOnly() != 1 ||',
    '            rules::mmpHelmBrilTrueNatureVisible() != 1 ||',
    '            rules::mmpHelmBrilArmorPlus() != 2) ++bad;',
    '        if (rules::mmpHelmBrilDiamondCount() != 10 ||',
    '            rules::mmpHelmBrilRubyCount() != 20 ||',
    '            rules::mmpHelmBrilFireOpalCount() != 30 ||',
    '            rules::mmpHelmBrilOpalCount() != 40 ||',
    '            rules::mmpHelmBrilScintillatesInBrightLight() !=',
    '            1) ++bad;',
    '        if (rules::mmpHelmBrilJewelUseSegments() != 1 ||',
    '            rules::mmpHelmBrilJewelUsableOnce() != 1 ||',
    '            rules::mmpHelmBrilUsesPerRound() != 1 ||',
    '            rules::mmpHelmBrilSpellLevelDoublingFactor() !=',
    '            2) ++bad;',
    '        if (rules::mmpHelmBrilUndeadGlowRangeFeet() != 30 ||',
    '            rules::mmpHelmBrilUndeadPainDmgMin() != 1 ||',
    '            rules::mmpHelmBrilUndeadPainDmgMax() != 6 ||',
    '            rules::mmpHelmBrilUndeadExemptKinds() != 2) ++bad;',
    '        if (rules::mmpHelmBrilFlameSwordEffectRounds() != 1 ||',
    '            rules::mmpHelmBrilFlameSwordAdditional() != 1 ||',
    '            rules::mmpHelmBrilProduceFlameDruidLevel() !=',
    '            5) ++bad;',
    '        if (rules::mmpHelmBrilFireResistRingStrength() != 2 ||',
    '            rules::mmpHelmBrilFireResistAugmentable() != 0 ||',
    '            rules::mmpHelmBrilPowderOnExpenditure() != 1) ++bad;',
    '        if (rules::mmpHelmBrilJewelRemovalDestroys() != 1 ||',
    '            rules::mmpHelmBrilJewelRemagickable() != 0 ||',
    '            rules::mmpHelmBrilRetrySaveWithoutMagic() !=',
    '            1) ++bad;',
    '        if (rules::mmpHelmBrilOverloadDetonatesRemaining() !=',
    '            1 ||',
    '            rules::mmpHelmBrilOverloadEffectsInMultiple() !=',
    '            1 ||',
    '            rules::mmpHelmBrilJewelRowCount() != 4) ++bad;',
    '        // the jewel functions table: the four',
    '        // restored rows against static twins',
    '        static const int kGem[4] = {',
    '            10, 20, 30, 40,',
    '        };',
    '        static const int kLvl[4] = {',
    '            7, 5, 3, 1,',
    '        };',
    '        static const int kCst[4] = {',
    '            0, 1, 2, 3,',
    '        };',
    '        static const int kFn[4] = {',
    '            0, 1, 2, 3,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpHelmBrilJewelGemCount(i) !=',
    '                kGem[i] ||',
    '                rules::mmpHelmBrilJewelSpellLevel(i) !=',
    '                kLvl[i] ||',
    '                rules::mmpHelmBrilJewelCasterKind(i) !=',
    '                kCst[i] ||',
    '                rules::mmpHelmBrilJewelFunctionKind(i) !=',
    '                kFn[i]) ++bad;',
    '        // the gem ladder climbs by 10, the spell',
    '        // level ladder falls by 2',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpHelmBrilJewelGemCount(i + 1) !=',
    '                rules::mmpHelmBrilJewelGemCount(i) + 10 ||',
    '                rules::mmpHelmBrilJewelSpellLevel(i) !=',
    '                rules::mmpHelmBrilJewelSpellLevel(i + 1) +',
    '                2) ++bad;',
    '        // the diamond function is the highest spell',
    '        // level, the opal function the lowest; the',
    '        // diamond row is the sparsest gem row',
    '        if (rules::mmpHelmBrilJewelSpellLevel(0) !=',
    '            rules::mmpHelmBrilJewelSpellLevel(3) + 6 ||',
    '            rules::mmpHelmBrilJewelGemCount(0) + 30 !=',
    '            rules::mmpHelmBrilJewelGemCount(3)) ++bad;',
    '        // the intro counts name the table rows',
    '        if (rules::mmpHelmBrilDiamondCount() !=',
    '            rules::mmpHelmBrilJewelGemCount(0) ||',
    '            rules::mmpHelmBrilRubyCount() !=',
    '            rules::mmpHelmBrilJewelGemCount(1) ||',
    '            rules::mmpHelmBrilFireOpalCount() !=',
    '            rules::mmpHelmBrilJewelGemCount(2) ||',
    '            rules::mmpHelmBrilOpalCount() !=',
    '            rules::mmpHelmBrilJewelGemCount(3)) ++bad;',
    '        // the walker clamps',
    '        if (rules::mmpHelmBrilJewelGemCount(99) != 40 ||',
    '            rules::mmpHelmBrilJewelSpellLevel(99) != 1) ++bad;',
    '        if (rules::mmpHelmComprStrangeTonguesPct() != 90 ||',
    '            rules::mmpHelmComprMagicalWritingsPct() != 80 ||',
    '            rules::mmpHelmComprAllOrNone() != 1 ||',
    '            rules::mmpHelmComprImpliesSpellUse() != 0 ||',
    '            rules::mmpHelmComprHelmetOfAcValue() != 5) ++bad;',
    '        // the comprehend ladder: 90 = 80 + 10',
    '        if (rules::mmpHelmComprStrangeTonguesPct() !=',
    '            rules::mmpHelmComprMagicalWritingsPct() + 10) ++bad;',
    '        if (rules::mmpHelmOppAlignIndeterminateDweomer() !=',
    '            1 ||',
    '            rules::mmpHelmOppAlignCurseOnDonning() != 1 ||',
    '            rules::mmpHelmOppAlignAbsoluteKinds() != 4 ||',
    '            rules::mmpHelmOppAlignAlterationDesired() !=',
    '            1) ++bad;',
    '        if (rules::mmpHelmOppAlignRestoreSpellKinds() != 2 ||',
    '            rules::mmpHelmOppAlignSelfRestoreAttempts() !=',
    '            0 ||',
    '            rules::mmpHelmOppAlignPaladinQuestAndAtone() !=',
    '            1 ||',
    '            rules::mmpHelmOppAlignPowersAfterFunctioning() !=',
    '            0) ++bad;',
    '        if (rules::mmpHelmTelepathyRangeInches() != 6 ||',
    '            rules::mmpHelmTelepathyStoneBarrierFeet() != 3 ||',
    '            rules::mmpHelmTelepathyIronBarrierQuarterFeet() !=',
    '            1 ||',
    '            rules::mmpHelmTelepathyLeadGoldSheetBlocks() !=',
    '            1) ++bad;',
    '        if (rules::mmpHelmTelepathyDirectional() != 1 ||',
    '            rules::mmpHelmTelepathyConsciousEffort() != 1 ||',
    '            rules::mmpHelmTelepathySuggestPctPer2IntAbove() !=',
    '            5 ||',
    '            rules::mmpHelmTelepathySuggestPctPer1IntBelow() !=',
    '            5) ++bad;',
    '        if (rules::mmpHelmTelepathySavePenaltyPer2IntBelow() !=',
    '            1 ||',
    '            rules::mmpHelmTelepathySaveBonusPer1IntAbove() !=',
    '            1 ||',
    '            rules::mmpHelmTelepathyEqualIntSaveAdjustment() !=',
    '            0 ||',
    '            rules::mmpHelmTelepathyPsionicAttackBonus() !=',
    '            4 ||',
    '            rules::mmpHelmTelepathyPsionicStrengthBonus() !=',
    '            40) ++bad;',
    '        if (rules::mmpHelmTeleportPerDay() != 1 ||',
    '            rules::mmpHelmTeleportMuRefreshRepeats() != 3 ||',
    '            rules::mmpHelmTeleportMuStillPersonalAfterRefresh() !=',
    '            1) ++bad;',
    '        if (rules::mmpHelmTeleportMuUncastPersonalCount() !=',
    '            6 ||',
    '            rules::mmpHelmTeleportUsageAfterMemoryLost() !=',
    '            1) ++bad;',
    '        if (rules::mmpHelmUnderwaterSeeAndBreathe() != 1 ||',
    '            rules::mmpHelmUnderwaterLensCompartments() != 2 ||',
    '            rules::mmpHelmUnderwaterVisionFactor() != 5 ||',
    '            rules::mmpHelmUnderwaterObstructionsBlock() !=',
    '            1 ||',
    '            rules::mmpHelmUnderwaterAirGlobeUntilRepeat() !=',
    '            1) ++bad;',
    '        if (rules::mmpHornBlastingConeLengthInches() != 12 ||',
    '            rules::mmpHornBlastingConeBaseWidthInches() != 3 ||',
    '            rules::mmpHornBlastingSaveStunRounds() != 1 ||',
    '            rules::mmpHornBlastingSaveDeafRounds() != 2) ++bad;',
    '        if (rules::mmpHornBlastingFailDmgMin() != 1 ||',
    '            rules::mmpHornBlastingFailDmgMax() != 10 ||',
    '            rules::mmpHornBlastingFailStunRounds() != 2 ||',
    '            rules::mmpHornBlastingFailDeafRounds() != 4) ++bad;',
    '        if (rules::mmpHornBlastingPulseWidthFeet() != 1 ||',
    '            rules::mmpHornBlastingPulseLengthInches() != 10 ||',
    '            rules::mmpHornBlastingCatapultMultiplier() != 3 ||',
    '            rules::mmpHornBlastingCatapultHitDamage() !=',
    '            6) ++bad;',
    '        // the structural ladder: 18 = 6 + 6 + 6',
    '        if (rules::mmpHornBlastingStructuralPoints() !=',
    '            rules::mmpHornBlastingCatapultHitDamage() +',
    '            rules::mmpHornBlastingCatapultHitDamage() +',
    '            rules::mmpHornBlastingCatapultHitDamage()) ++bad;',
    '        if (rules::mmpHornBlastingExplodePctPerExtraUse() !=',
    '            10 ||',
    '            rules::mmpHornBlastingExplodeDmgMin() != 5 ||',
    '            rules::mmpHornBlastingExplodeDmgMax() != 50) ++bad;',
    '        // the explosion is five fold the save',
    '        // damage: 50 = 10 x 5 and 5 = 1 x 5, as',
    '        // sums over the save damage accessor',
    '        if (rules::mmpHornBlastingExplodeDmgMax() !=',
    '            rules::mmpHornBlastingFailDmgMax() +',
    '            rules::mmpHornBlastingFailDmgMax() +',
    '            rules::mmpHornBlastingFailDmgMax() +',
    '            rules::mmpHornBlastingFailDmgMax() +',
    '            rules::mmpHornBlastingFailDmgMax() ||',
    '            rules::mmpHornBlastingExplodeDmgMin() !=',
    '            rules::mmpHornBlastingFailDmgMin() +',
    '            rules::mmpHornBlastingFailDmgMin() +',
    '            rules::mmpHornBlastingFailDmgMin() +',
    '            rules::mmpHornBlastingFailDmgMin() +',
    '            rules::mmpHornBlastingFailDmgMin()) ++bad;',
    '        if (rules::mmpHornBlastingCharges() != 0 ||',
    '            rules::mmpHornBlastingShiverPctPerUse() != 2 ||',
    '            rules::mmpHornBlastingShiverWielderDamage() !=',
    '            0) ++bad;',
    '        if (rules::mmpHornBubblesBlindRoundsMin() != 2 ||',
    '            rules::mmpHornBubblesBlindRoundsMax() != 20 ||',
    '            rules::mmpHornBubblesOnlyWhenSlayerSeeks() !=',
    '            1 ||',
    '            rules::mmpHornBubblesAppearanceMayDelay() !=',
    '            1) ++bad;',
    '        // the kMisc3 rows this slice pins: 10-17,',
    '        // no class marks and no asterisks',
    '        static const int kLo[8] = {',
    '            30, 31, 36, 38, 40, 41, 46, 47,',
    '        };',
    '        static const int kHi[8] = {',
    '            30, 35, 37, 39, 40, 45, 46, 48,',
    '        };',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::m3RowLo(10 + i) != kLo[i] ||',
    '                rules::m3RowHi(10 + i) != kHi[i]) ++bad;',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::m3UsableByCleric(10 + i) ||',
    '                rules::m3UsableByFighter(10 + i) ||',
    '                rules::m3UsableByThief(10 + i) ||',
    '                rules::m3StarCount(10 + i) ||',
    '                rules::m3IsPerFacetValued(10 + i)) ++bad;',
    '        printf("R268 misc magic prose part 12 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]

# ---- patch 4 content: the gap entry ----
GAP = [
    'R268 landed the III.E misc',
    'magic explanation prose part',
    '12 (part2 lines 532-579;',
    'global = 11065 + part2',
    'line), Helm of Brilliance',
    'through the Horn of Bubbles -',
    'pinning the kMisc3 rows 10-17,',
    'NO class marks and NO',
    'asterisks ride these rows. ONE',
    'page header inside the slice',
    '(the 541 TREASURE page) falls',
    'between the jewel functions',
    'table and the Each gem',
    'paragraph of the Brilliance',
    'item - restored. The jewel',
    'functions table: the book',
    'upload flattens the four gem',
    'rows into the Diamond cell',
    '(the Ruby, Fire Opal and Opal',
    'cells empty) - the four-row',
    'table restored from the',
    'compilation (the R175',
    'precedent): Diamond prismatic',
    'spray (7th illusionist), Ruby',
    'wall of fire (5th druid), Fire',
    'Opal fireball (3rd',
    'magic-user), Opal light (1st',
    'cleric). The items: Helm of',
    'Brilliance (+2 armor, 10',
    'diamonds, 20 rubies, 30 fire',
    'opals, 40 opals; each gem one',
    'spell in 1 segment once, the',
    'helm once per round, spell',
    'level doubled; undead glow at',
    '30 feet, pain 1-6, skeletons',
    'and zombies exempt; sword of',
    'flame in 1 round, additional',
    'to specials; produce flame as',
    'a 5th level druid; double',
    'strength fire resistance, no',
    'augment; spent gems turn to',
    'powder, removal destroys, no',
    're-magicking; a failed save',
    'versus magical fire: another',
    'save for the helm without',
    'magic, failed: the gems',
    'overload, multiple effects),',
    'Helm of Comprehending',
    'Languages and Reading Magic',
    '(90 percent strange tongues,',
    '80 magic writings, all or',
    'none; not spell use; a helmet',
    'of armor class 5), Helm of',
    'Opposite Alignment',
    '(indeterminate dweomer; curse',
    'on donning; good to evil,',
    'neutral to LE LG CE CG; the',
    'alteration desired; wish or',
    'alter reality only; no self',
    'return; paladin quest and',
    'atone; powerless after',
    'functioning), Helm of',
    'Telepathy (thoughts within 6',
    'inches; racial tongue over',
    'common over alignment',
    'tongues; 3 feet of stone, a',
    'quarter foot of iron, lead or',
    'gold sheeting blocks;',
    'directional, conscious effort;',
    'language or empathy;',
    'suggestion +5 percent per 2',
    'intelligence above, -5 per 1',
    'below; the subject save',
    'minus 1 per 2 below, plus 1',
    'per 1 above, equal flat; +4',
    'psionic attacks; +40 psionic',
    'strength), Helm of',
    'Teleportation (once per day',
    'as a magic-user, destination',
    'known, risk; a magic-user',
    'memorizes and refreshes:',
    'repeat 3 times and still',
    'personally teleport; the',
    'spell retained: 6 personal',
    'teleports, then a helm',
    'usage), Helm of Underwater',
    'Action (see and breathe;',
    'lenses from two compartments;',
    '5 times farther vision;',
    'obstructions block; the',
    'command word: an air globe',
    'until repeated), Horn of',
    'Blasting (a normal trumpet; a',
    'sound cone 12 inches by 3;',
    'save: stunned 1, deafened 2;',
    'fail: 1-10 damage, stunned 2,',
    'deafened 4; an ultrasonic',
    'pulse 1 foot by 10 inches; 3',
    'times a large catapult hit =',
    '18 structural points, smash a',
    'drawbridge or flatten a',
    'cottage; over once a day: 10',
    'percent cumulative explode,',
    '5-50 on the user; no',
    'charges; 2 percent cumulative',
    'shiver, no wielder damage),',
    'Horn of Bubbles (the bubbles',
    'blind the blower 2-20',
    'rounds; only when a slayer',
    'actively seeks the',
    'character; appearance may',
    'delay). 91 accessors: 87',
    'scalars + 4 walkers (the',
    'jewel functions table; the',
    'gem, spell-level, structural',
    'and explosion ladders are',
    'arithmetic checks). New R268',
    'battery audit; census 186.',
    'Next: part 13 - Horn of',
    'Collapsing onward in part2',
    'from line 581 (global 11646;',
    'the tritons, Valhalla,',
    'horseshoes, incenses and',
    'instruments follow; kMisc3',
    'rows 18+).',
]

# ---- the splice self-asserts ----
HTEXT = NL.join(HDR)
defs = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(]', HTEXT)
assert len(defs) == 91, 'accessor count is not 91'
assert len(set(defs)) == 91, 'accessor names not unique'
scal = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(][)]', HTEXT)
walk = [d for d in defs if d not in scal]
assert len(scal) == 87, 'scalar count is not 87'
assert len(walk) == 4, 'walker count is not 4'
ATEXT = NL.join(AUDIT)
audited = set(re.findall(r'rules::(mmp[A-Za-z0-9]+)[(]', ATEXT))
assert audited == set(defs), 'audit does not probe every accessor'
for p in range(1, 12):
    pp = os.path.join(ROOT, 'rules/miscprose%d.h' % p)
    if os.path.exists(pp):
        pt = open(pp, encoding='utf-8').read()
        for n in defs:
            assert n not in pt, 'name collision with part %d' % p
for grp in (HDR, AUDIT, GAP):
    for el in grp:
        if isinstance(el, str):
            assert chr(39) not in el, 'apostrophe in content'
            probe = el.replace(chr(92) + 'n', '')
            assert chr(92) not in probe, 'backslash in content'
for grp in (HDR, AUDIT):
    for el in grp:
        assert len(el) <= 79, 'content line too long'
for el in GAP:
    assert len(el) <= 38, 'gap line too long'

# ---- apply patch 1 ----
if os.path.exists(os.path.join(ROOT, P1)):
    already += 1
    assert rd(P1) == NL.join(HDR), P1 + ' exists but differs'
else:
    wr(P1, NL.join(HDR))
    applied += 1
    assert rd(P1) == NL.join(HDR), P1 + ' write mismatch'
assert rd(P1).count(
    'R268: the III.E misc magic explanation prose part 12') == 1

# ---- apply patch 2: the regtest include ----
INC_OLD = ('#include "rules/miscprose11.h"  // R267: the III.E misc'
           ' magic explanation prose part 11 pins')
INC_NEW = ('#include "rules/miscprose12.h"  // R268: the III.E misc'
           ' magic explanation prose part 12 pins')
RG = rd('regtest.cpp')
if INC_NEW in RG:
    already += 1
    assert RG.count(INC_NEW) == 1, 'include not unique'
else:
    assert RG.count(INC_OLD) == 1, 'R267 include anchor missing'
    RG = RG.replace(INC_OLD, INC_OLD + NL + INC_NEW)
    applied += 1
    assert RG.count(INC_NEW) == 1, 'include insert failed'
wr('regtest.cpp', RG)

# ---- apply patch 3: the R268 audit block ----
ANCHOR = ('    // ---- R227: the wis mental save wiring audit ----')
AUDIT_STR = NL.join(AUDIT)
if ('printf("R268 misc magic prose part 12 pins audit:') in RG:
    already += 1
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
else:
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
    RG = RG.replace(ANCHOR, AUDIT_STR + NL + ANCHOR)
    applied += 1
    assert RG.count(
        'printf("R268 misc magic prose part 12 pins audit:') == 1, (
        'audit printf not unique')
wr('regtest.cpp', RG)

# ---- apply patch 4: the gap entry ----
GP = rd('tools/dmg_gap_report.md')
if GP.count('R268 landed the III.E misc') == 1:
    already += 1
else:
    TAIL = ('rows 10+).' + NL + NL + 'Categories:')
    assert GP.count(TAIL) == 1, 'R267 gap tail anchor not unique'
    NEWTAIL = ('rows 10+).' + NL + NL + NL.join(GAP) +
               NL + NL + 'Categories:')
    GP = GP.replace(TAIL, NEWTAIL)
    applied += 1
    assert GP.count('R268 landed the III.E misc') == 1, (
        'gap entry insert failed')
wr('tools/dmg_gap_report.md', GP)

# ---- report ----
assert applied + already == 4, 'patch count wrong'
print('R268 splice: ALL OK (applied %d, already %d)'
      % (applied, already))
print('R268 note: 4 patches; the III.E misc magic')
print('explanation prose part 12 - Helm of')
print('Brilliance through Horn of Bubbles, part2')
print('lines 532-579; census 186.')
COMMIT = ('R268: the III.E misc magic explanation prose part 12'
          ' pinned - Helm of Brilliance through the Horn of'
          ' Bubbles in part2 lines 532-579 (census 186)')
print('commit: ' + COMMIT)

