#!/usr/bin/env python3
# R269 splice: the III.E misc magic explanation prose
# part 13 pins - Horn of Collapsing through the Incense
# of Meditation, part2 lines 581-626 (DMG p.139-140) -
# the slice pinning the kMisc3 rows 18-23 (the (C, F)
# mark rides the Horn of the Tritons, the (C) mark the
# Incense of Meditation, the Valhalla double asterisk
# row 20). ONE page header inside the slice (592, the
# TREASURE page) cuts the Collapsing proper-use
# paragraph mid-sentence. ONE OCR artifact restored from
# the 1eonline.info compilation (the R175 precedent):
# the meditation survival clause reads (rounded down).
# 4 patches, marker-based idempotence, assert after
# every patch. ZERO apostrophes and ZERO literal
# backslashes in the content below (the printf newline
# is built via BS = chr(92)).

import os
import re
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

# ---- patch 1: rules/miscprose13.h ----
P1 = 'rules/miscprose13.h'
HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose13.h',
    '// R269: the III.E misc magic explanation prose part 13',
    '// (DMG p.139-140) - Horn of Collapsing through the',
    '// Incense of Meditation, part2 lines 581-626 (global =',
    '// 11065 + part2 line). ONE page header inside the slice',
    '// (592, the TREASURE page) cuts the Collapsing proper',
    '// use paragraph mid-sentence (one seam, restored). ONE',
    '// OCR artifact restored from the compilation (the R175',
    '// precedent): the meditation survival clause reads',
    '// (rounded down), the upload prints grounded down).',
    '// 73 accessors: 60 scalars + 13 array walkers (the',
    '// triton summon and the Valhalla variety tables), no',
    '// name collisions with miscprose1.h through',
    '// miscprose12.h. The slice pins kMisc3 rows 18-23: the',
    '// (C, F) mark on the Horn of the Tritons (row 19), the',
    '// (C) mark on the Incense of Meditation (row 23), the',
    '// Valhalla double asterisk (row 20). Pure data +',
    '// helpers, header-only (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpHornCollapseMisfirePct() {',
    '    // sounded without the proper rune, or 10',
    '    // percent of the time in any event',
    '    return 10;',
    '}',
    '',
    'inline int mmpHornCollapseOutRocksMin() {',
    '    // outside: a rain of fist-sized rocks',
    '    return 2;',
    '}',
    '',
    'inline int mmpHornCollapseOutRocksMax() {',
    '    // from 2-12 in number',
    '    return 12;',
    '}',
    '',
    'inline int mmpHornCollapseOutRockDmgMin() {',
    '    // each rock causes 1-6 hit points of damage',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornCollapseOutRockDmgMax() {',
    '    // the 1-6 upper edge',
    '    return 6;',
    '}',
    '',
    'inline int mmpHornCollapseIndoorDmgMin() {',
    '    // indoors: the ceiling collapses on the character',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornCollapseIndoorDmgMax() {',
    '    // 3-36 hit points of damage',
    '    return 36;',
    '}',
    '',
    'inline int mmpHornCollapseUnderDmgMin() {',
    '    // underground: the material above falls',
    '    return 5;',
    '}',
    '',
    'inline int mmpHornCollapseUnderDmgMax() {',
    '    // 5-20 hit points base damage',
    '    return 20;',
    '}',
    '',
    'inline int mmpHornCollapseUnderHeightFactorFeet() {',
    '    // the base damage is multiplied by 1 factor for',
    '    // each 10 feet of drop height (twice at 20 feet,',
    '    // three times at 30 feet, etc.)',
    '    return 10;',
    '}',
    '',
    'inline int mmpHornCollapseAimRangeMinFeet() {',
    '    // proper use: point at the roof overhead from',
    '    return 30;',
    '}',
    '',
    'inline int mmpHornCollapseAimRangeMaxFeet() {',
    '    // 30 to 60 feet beyond the user',
    '    return 60;',
    '}',
    '',
    'inline int mmpHornCollapseRoofWidthFeet() {',
    '    // collapses a roof section up to 20 feet wide',
    '    return 20;',
    '}',
    '',
    'inline int mmpHornCollapseRoofLengthFeet() {',
    '    // and 20 feet long',
    '    return 20;',
    '}',
    '',
    'inline int mmpHornCollapseRoofRadiusFeet() {',
    '    // a 10 feet radius from the central aiming point',
    '    return 10;',
    '}',
    '',
    'inline int mmpHornCollapseIndoorsOrUndergroundOnly() {',
    '    // the aimed collapse inflicts damage only if',
    '    // indoors or underground',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornTritonPerDay() {',
    '    // a conch shell horn blown but once per day',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornTritonTritonPerDay() {',
    '    // except by a triton who can sound it 3 times',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornTritonFunctionCount() {',
    '    // any 1 of the following functions',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornTritonCalmRadiusMiles() {',
    '    // calm rough waters in a 1 mile radius',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornTritonCalmDispelKinds() {',
    '    // dispels a water elemental or water weird',
    '    return 2;',
    '}',
    '',
    'inline int mmpHornTritonSummonKindCount() {',
    '    // hippocampi, giant sea horses, sea lions',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornTritonSummonDieLo(int i) {',
    '    // the selection die band lower edges: 1-2 the',
    '    // hippocampi, 3-5 the sea horses, 6 the lions;',
    '    // i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        1, 3, 6,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornTritonSummonDieHi(int i) {',
    '    // the selection die band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        2, 5, 6,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornTritonSummonCountMin(int i) {',
    '    // the creatures summoned lower edges: 5-20',
    '    // hippocampi, 5-30 sea horses, 1-10 sea lions;',
    '    // i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        5, 5, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornTritonSummonCountMax(int i) {',
    '    // the summon upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        20, 30, 10,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornTritonPanicAnimalOrLower() {',
    '    // panics marine creatures with animal, or',
    '    // lower, intelligence',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornTritonPanicToHitPenalty() {',
    '    // those who save take a minus 5 on to hit dice',
    '    return 5;',
    '}',
    '',
    'inline int mmpHornTritonPanicTurnsMin() {',
    '    // the penalty lasts 3-18 turns',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornTritonPanicTurnsMax() {',
    '    // the turns upper edge',
    '    return 18;',
    '}',
    '',
    'inline int mmpHornTritonPanicRoundsPerTurn() {',
    '    // 3-18 turns is 30-180 rounds: 10 rounds per',
    '    // turn',
    '    return 10;',
    '}',
    '',
    'inline int mmpHornTritonPanicRoundsMin() {',
    '    // the 30 rounds lower edge',
    '    return 30;',
    '}',
    '',
    'inline int mmpHornTritonPanicRoundsMax() {',
    '    // the 180 rounds upper edge',
    '    return 180;',
    '}',
    '',
    'inline int mmpHornTritonHearRadiusLeagues() {',
    '    // any sounding is heard by all tritons within',
    '    // a 1 league radius',
    '    return 1;',
    '}',
    '',
    'inline int mmpHornValhallaVarietyCount() {',
    '    // there are 4 varieties of this magical device',
    '    return 4;',
    '}',
    '',
    'inline int mmpHornValhallaBlowIntervalDays() {',
    '    // each variety can be blown but once every 7',
    '    // days',
    '    return 7;',
    '}',
    '',
    'inline int mmpHornValhallaSummonedAc() {',
    '    // the fighters summoned are armor class 4',
    '    return 4;',
    '}',
    '',
    'inline int mmpHornValhallaSummonedHpPerDie() {',
    '    // they have 6 hit points per die',
    '    return 6;',
    '}',
    '',
    'inline int mmpHornValhallaSwordSpearPct() {',
    '    // armed with sword and spear 50 percent',
    '    return 50;',
    '}',
    '',
    'inline int mmpHornValhallaAxeSpearPct() {',
    '    // or battle axe and spear 50 percent',
    '    return 50;',
    '}',
    '',
    'inline int mmpHornValhallaServiceTurns() {',
    '    // they fight until slain or 6 turns have',
    '    // elapsed, whichever occurs first',
    '    return 6;',
    '}',
    '',
    'inline int mmpHornValhallaAlignedPct() {',
    '    // fully 50 percent of these horns are aligned',
    '    // and summon only same-alignment fighters',
    '    return 50;',
    '}',
    '',
    'inline int mmpHornValhallaBronzeXpMultiplier() {',
    '    // the base 1,000 xp is doubled for a bronze',
    '    // horn - the row 20 double asterisk',
    '    return 2;',
    '}',
    '',
    'inline int mmpHornValhallaIronXpMultiplier() {',
    '    // and tripled for an iron horn',
    '    return 3;',
    '}',
    '',
    'inline int mmpHornValhallaDiceLo(int i) {',
    '    // the variety dice band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 9, 16, 19,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaDiceHi(int i) {',
    '    // silver 1-8, brass 9-15, bronze 16-18, iron',
    '    // 19-20; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        8, 15, 18, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaCountMin(int i) {',
    '    // berserk fighters summoned lower edges;',
    '    // i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        4, 3, 2, 2,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaCountMax(int i) {',
    '    // the 4-10, 3-9, 2-8, 2-5 upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        10, 9, 8, 5,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaLevel(int i) {',
    '    // the summoned fighter levels: 2nd, 3rd, 4th,',
    '    // 5th; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        2, 3, 4, 5,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaUsableAny(int i) {',
    '    // the silver horn is usable by any class; i',
    '    // clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 0, 0, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaUsableCleric(int i) {',
    '    // the (C) employ marks; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        0, 1, 1, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaUsableFighter(int i) {',
    '    // the (F) employ marks; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        0, 1, 1, 1,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHornValhallaUsableThief(int i) {',
    '    // the (T) employ marks; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        0, 1, 0, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpHorseshoesSpeedShoeCount() {',
    '    // 4 normal-appearing iron horse shoes',
    '    return 4;',
    '}',
    '',
    'inline int mmpHorseshoesSpeedFullPct() {',
    '    // affixed, they double the animal speed (the',
    '    // 200 percent full rate)',
    '    return 200;',
    '}',
    '',
    'inline int mmpHorseshoesSpeedDropPct() {',
    '    // a 1 percent chance per 7 leagues travelled',
    '    // that 1 shoe drops off',
    '    return 1;',
    '}',
    '',
    'inline int mmpHorseshoesSpeedDropLeagues() {',
    '    // the drop interval in leagues',
    '    return 7;',
    '}',
    '',
    'inline int mmpHorseshoesSpeedOneLostPct() {',
    '    // one lost and unnoticed: 150 percent of the',
    '    // normal rate',
    '    return 150;',
    '}',
    '',
    'inline int mmpHorseshoesSpeedTwoLostPct() {',
    '    // 2 lost: the speed is normal',
    '    return 100;',
    '}',
    '',
    'inline int mmpHorseshoesZephyrGroundless() {',
    '    // the horse travels without touching the',
    '    // ground',
    '    return 1;',
    '}',
    '',
    'inline int mmpHorseshoesZephyrNoTracks() {',
    '    // water can be passed over and no tracks are',
    '    // made on any sort of ground',
    '    return 1;',
    '}',
    '',
    'inline int mmpHorseshoesZephyrNoTireHours() {',
    '    // the horse will not tire for 12 hours of',
    '    // continuous riding',
    '    return 12;',
    '}',
    '',
    'inline int mmpHorseshoesZephyrPerDay() {',
    '    // per day of continuous riding',
    '    return 1;',
    '}',
    '',
    'inline int mmpIncenseMedRecognizeClericLevel() {',
    '    // the smoke is recognizable by any cleric of',
    '    // 5th or higher level',
    '    return 5;',
    '}',
    '',
    'inline int mmpIncenseMedPrayHours() {',
    '    // the cleric spends 8 hours praying and',
    '    // meditating nearby',
    '    return 8;',
    '}',
    '',
    'inline int mmpIncenseMedCureAlwaysMax() {',
    '    // cure wounds spells are always maximum',
    '    return 1;',
    '}',
    '',
    'inline int mmpIncenseMedBroadestArea() {',
    '    // spell effects are of the broadest area',
    '    // possible',
    '    return 1;',
    '}',
    '',
    'inline int mmpIncenseMedSavePenalty() {',
    '    // saving throws against the effects are at',
    '    // minus 1',
    '    return 1;',
    '}',
    '',
    'inline int mmpIncenseMedNotSurvivingDivisor() {',
    '    // the revived dead reduce their chance of not',
    '    // surviving by one-half (rounded down)',
    '    return 2;',
    '}',
    '',
    'inline int mmpIncenseMedPieceCountMin() {',
    '    // discovered with from 2-8 pieces of incense',
    '    return 2;',
    '}',
    '',
    'inline int mmpIncenseMedPieceCountMax() {',
    '    // the piece count upper edge',
    '    return 8;',
    '}',
    '',
    'inline int mmpIncenseMedBurnHours() {',
    '    // one piece burns for 8 hours',
    '    return 8;',
    '}',
    '',
    'inline int mmpIncenseMedEffectHours() {',
    '    // the effects remain for 24 hours',
    '    return 24;',
    '}',
    '',
    '}  // namespace rules',
]

# ---- patch 3 content: the R269 audit block ----
AUDIT = [
    '    // ---- R269: the III.E misc magic explanation',
    '    // prose part 13 ----',
    '    // Horn of Collapsing through the Incense of',
    '    // Meditation, part2 lines 581-626 - the slice',
    '    // pinning the kMisc3 rows 18-23.',
    '    {',
    '        int bad = 0;',
    '        if (rules::mmpHornCollapseMisfirePct() != 10 ||',
    '            rules::mmpHornCollapseOutRocksMin() != 2 ||',
    '            rules::mmpHornCollapseOutRocksMax() != 12 ||',
    '            rules::mmpHornCollapseOutRockDmgMin() != 1 ||',
    '            rules::mmpHornCollapseOutRockDmgMax() != 6) ++bad;',
    '        if (rules::mmpHornCollapseIndoorDmgMin() != 3 ||',
    '            rules::mmpHornCollapseIndoorDmgMax() != 36 ||',
    '            rules::mmpHornCollapseUnderDmgMin() != 5 ||',
    '            rules::mmpHornCollapseUnderDmgMax() != 20 ||',
    '            rules::mmpHornCollapseUnderHeightFactorFeet() !=',
    '            10) ++bad;',
    '        if (rules::mmpHornCollapseAimRangeMinFeet() != 30 ||',
    '            rules::mmpHornCollapseAimRangeMaxFeet() != 60 ||',
    '            rules::mmpHornCollapseRoofWidthFeet() != 20 ||',
    '            rules::mmpHornCollapseRoofLengthFeet() != 20 ||',
    '            rules::mmpHornCollapseRoofRadiusFeet() !=',
    '            10) ++bad;',
    '        if (rules::mmpHornCollapseIndoorsOrUndergroundOnly() !=',
    '            1) ++bad;',
    '        // the collapse roof geometry: 20 = 10 + 10',
    '        if (rules::mmpHornCollapseRoofWidthFeet() !=',
    '            rules::mmpHornCollapseRoofRadiusFeet() +',
    '            rules::mmpHornCollapseRoofRadiusFeet() ||',
    '            rules::mmpHornCollapseRoofLengthFeet() !=',
    '            rules::mmpHornCollapseRoofWidthFeet() ||',
    '            rules::mmpHornCollapseAimRangeMaxFeet() !=',
    '            rules::mmpHornCollapseAimRangeMinFeet() +',
    '            30) ++bad;',
    '        if (rules::mmpHornTritonPerDay() != 1 ||',
    '            rules::mmpHornTritonTritonPerDay() != 3 ||',
    '            rules::mmpHornTritonFunctionCount() != 3 ||',
    '            rules::mmpHornTritonCalmRadiusMiles() != 1 ||',
    '            rules::mmpHornTritonCalmDispelKinds() !=',
    '            2) ++bad;',
    '        // the triton summon table against static twins',
    '        static const int kDlo[3] = {',
    '            1, 3, 6,',
    '        };',
    '        static const int kDhi[3] = {',
    '            2, 5, 6,',
    '        };',
    '        static const int kClo[3] = {',
    '            5, 5, 1,',
    '        };',
    '        static const int kChi[3] = {',
    '            20, 30, 10,',
    '        };',
    '        if (rules::mmpHornTritonSummonKindCount() !=',
    '            3) ++bad;',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpHornTritonSummonDieLo(i) !=',
    '                kDlo[i] ||',
    '                rules::mmpHornTritonSummonDieHi(i) !=',
    '                kDhi[i] ||',
    '                rules::mmpHornTritonSummonCountMin(i) !=',
    '                kClo[i] ||',
    '                rules::mmpHornTritonSummonCountMax(i) !=',
    '                kChi[i]) ++bad;',
    '        // the selection die runs 1-6 without gaps',
    '        for (int i = 0; i < 2; ++i)',
    '            if (rules::mmpHornTritonSummonDieLo(i + 1) !=',
    '                rules::mmpHornTritonSummonDieHi(i) +',
    '                1) ++bad;',
    '        if (rules::mmpHornTritonSummonDieLo(0) != 1 ||',
    '            rules::mmpHornTritonSummonDieHi(2) != 6) ++bad;',
    '        if (rules::mmpHornTritonPanicAnimalOrLower() != 1 ||',
    '            rules::mmpHornTritonPanicToHitPenalty() != 5 ||',
    '            rules::mmpHornTritonPanicTurnsMin() != 3 ||',
    '            rules::mmpHornTritonPanicTurnsMax() != 18 ||',
    '            rules::mmpHornTritonPanicRoundsPerTurn() !=',
    '            10) ++bad;',
    '        // the panic ladder: turns times 10 = rounds',
    '        if (rules::mmpHornTritonPanicRoundsMin() !=',
    '            rules::mmpHornTritonPanicTurnsMin() *',
    '            rules::mmpHornTritonPanicRoundsPerTurn() ||',
    '            rules::mmpHornTritonPanicRoundsMax() !=',
    '            rules::mmpHornTritonPanicTurnsMax() *',
    '            rules::mmpHornTritonPanicRoundsPerTurn() ||',
    '            rules::mmpHornTritonHearRadiusLeagues() !=',
    '            1) ++bad;',
    '        if (rules::mmpHornValhallaVarietyCount() != 4 ||',
    '            rules::mmpHornValhallaBlowIntervalDays() != 7 ||',
    '            rules::mmpHornValhallaSummonedAc() != 4 ||',
    '            rules::mmpHornValhallaSummonedHpPerDie() !=',
    '            6) ++bad;',
    '        if (rules::mmpHornValhallaSwordSpearPct() != 50 ||',
    '            rules::mmpHornValhallaAxeSpearPct() != 50 ||',
    '            rules::mmpHornValhallaServiceTurns() != 6 ||',
    '            rules::mmpHornValhallaAlignedPct() != 50) ++bad;',
    '        // the valhalla variety table against twins',
    '        static const int kVlo[4] = {',
    '            1, 9, 16, 19,',
    '        };',
    '        static const int kVhi[4] = {',
    '            8, 15, 18, 20,',
    '        };',
    '        static const int kNlo[4] = {',
    '            4, 3, 2, 2,',
    '        };',
    '        static const int kNhi[4] = {',
    '            10, 9, 8, 5,',
    '        };',
    '        static const int kLvl[4] = {',
    '            2, 3, 4, 5,',
    '        };',
    '        static const int kAny[4] = {',
    '            1, 0, 0, 0,',
    '        };',
    '        static const int kVc[4] = {',
    '            0, 1, 1, 0,',
    '        };',
    '        static const int kVf[4] = {',
    '            0, 1, 1, 1,',
    '        };',
    '        static const int kVt[4] = {',
    '            0, 1, 0, 0,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpHornValhallaDiceLo(i) != kVlo[i] ||',
    '                rules::mmpHornValhallaDiceHi(i) != kVhi[i] ||',
    '                rules::mmpHornValhallaCountMin(i) !=',
    '                kNlo[i] ||',
    '                rules::mmpHornValhallaCountMax(i) !=',
    '                kNhi[i] ||',
    '                rules::mmpHornValhallaLevel(i) != kLvl[i] ||',
    '                rules::mmpHornValhallaUsableAny(i) !=',
    '                kAny[i] ||',
    '                rules::mmpHornValhallaUsableCleric(i) !=',
    '                kVc[i] ||',
    '                rules::mmpHornValhallaUsableFighter(i) !=',
    '                kVf[i] ||',
    '                rules::mmpHornValhallaUsableThief(i) !=',
    '                kVt[i]) ++bad;',
    '        // the variety dice run 1-20 without gaps, the',
    '        // levels climb by 1',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpHornValhallaDiceLo(i + 1) !=',
    '                rules::mmpHornValhallaDiceHi(i) + 1 ||',
    '                rules::mmpHornValhallaLevel(i + 1) !=',
    '                rules::mmpHornValhallaLevel(i) + 1) ++bad;',
    '        if (rules::mmpHornValhallaDiceLo(0) != 1 ||',
    '            rules::mmpHornValhallaDiceHi(3) != 20) ++bad;',
    '        // the asterisk ladder: bronze doubles, iron',
    '        // triples, the row 20 star count is 2',
    '        if (rules::mmpHornValhallaIronXpMultiplier() !=',
    '            rules::mmpHornValhallaBronzeXpMultiplier() +',
    '            1 ||',
    '            rules::mmpHornValhallaBronzeXpMultiplier() !=',
    '            rules::m3StarCount(20)) ++bad;',
    '        if (rules::mmpHorseshoesSpeedShoeCount() != 4 ||',
    '            rules::mmpHorseshoesSpeedFullPct() != 200 ||',
    '            rules::mmpHorseshoesSpeedDropPct() != 1 ||',
    '            rules::mmpHorseshoesSpeedDropLeagues() !=',
    '            7) ++bad;',
    '        // the speed ladder: 200 = 100 + 100,',
    '        // 150 = 100 + 50',
    '        if (rules::mmpHorseshoesSpeedFullPct() !=',
    '            rules::mmpHorseshoesSpeedTwoLostPct() +',
    '            rules::mmpHorseshoesSpeedTwoLostPct() ||',
    '            rules::mmpHorseshoesSpeedOneLostPct() !=',
    '            rules::mmpHorseshoesSpeedTwoLostPct() +',
    '            50) ++bad;',
    '        if (rules::mmpHorseshoesZephyrGroundless() != 1 ||',
    '            rules::mmpHorseshoesZephyrNoTracks() != 1 ||',
    '            rules::mmpHorseshoesZephyrNoTireHours() != 12 ||',
    '            rules::mmpHorseshoesZephyrPerDay() != 1) ++bad;',
    '        if (rules::mmpIncenseMedRecognizeClericLevel() !=',
    '            5 ||',
    '            rules::mmpIncenseMedPrayHours() != 8 ||',
    '            rules::mmpIncenseMedCureAlwaysMax() != 1 ||',
    '            rules::mmpIncenseMedBroadestArea() != 1 ||',
    '            rules::mmpIncenseMedSavePenalty() !=',
    '            1) ++bad;',
    '        // the incense ladders: burn = pray hours,',
    '        // 24 = 8 + 8 + 8, the halved survival divisor',
    '        if (rules::mmpIncenseMedBurnHours() !=',
    '            rules::mmpIncenseMedPrayHours() ||',
    '            rules::mmpIncenseMedEffectHours() !=',
    '            rules::mmpIncenseMedBurnHours() +',
    '            rules::mmpIncenseMedBurnHours() +',
    '            rules::mmpIncenseMedBurnHours() ||',
    '            rules::mmpIncenseMedNotSurvivingDivisor() !=',
    '            2) ++bad;',
    '        if (rules::mmpIncenseMedPieceCountMin() != 2 ||',
    '            rules::mmpIncenseMedPieceCountMax() != 8) ++bad;',
    '        // the kMisc3 rows this slice pins: 18-23,',
    '        // the (C, F) mark on row 19, the (C) mark on',
    '        // row 23, the double asterisk on row 20',
    '        static const int kLo[6] = {',
    '            49, 50, 54, 61, 64, 66,',
    '        };',
    '        static const int kHi[6] = {',
    '            49, 53, 60, 63, 65, 70,',
    '        };',
    '        static const int kCm[6] = {',
    '            0, 1, 0, 0, 0, 1,',
    '        };',
    '        static const int kFm[6] = {',
    '            0, 1, 0, 0, 0, 0,',
    '        };',
    '        static const int kTm[6] = {',
    '            0, 0, 0, 0, 0, 0,',
    '        };',
    '        static const int kSt[6] = {',
    '            0, 0, 2, 0, 0, 0,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::m3RowLo(18 + i) != kLo[i] ||',
    '                rules::m3RowHi(18 + i) != kHi[i] ||',
    '                rules::m3StarCount(18 + i) != kSt[i]) ++bad;',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::m3UsableByCleric(18 + i) != kCm[i] ||',
    '                rules::m3UsableByFighter(18 + i) !=',
    '                kFm[i] ||',
    '                rules::m3UsableByThief(18 + i) !=',
    '                kTm[i] ||',
    '                rules::m3IsPerFacetValued(18 + i)) ++bad;',
    '        printf("R269 misc magic prose part 13 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]

# ---- patch 4 content: the gap entry ----
GAP = [
    'R269 landed the III.E misc',
    'magic explanation prose part',
    '13 (part2 lines 581-626;',
    'global = 11065 + part2',
    'line), Horn of Collapsing',
    'through the Incense of',
    'Meditation - pinning the',
    'kMisc3 rows 18-23: the (C, F)',
    'mark on the Horn of the',
    'Tritons (row 19), the (C)',
    'mark on the Incense of',
    'Meditation (row 23), the',
    'Valhalla double asterisk',
    '(row 20). ONE page header',
    'inside the slice (the 592',
    'TREASURE page) cuts the',
    'Collapsing proper-use',
    'paragraph mid-sentence (at',
    'the 10 feet radius from',
    'the / central aiming',
    'point) - restored. ONE OCR',
    'artifact restored from the',
    'compilation (the R175',
    'precedent): the meditation',
    'survival clause reads',
    '(rounded down), the upload',
    'prints grounded down). The',
    'items: Horn of Collapsing',
    '(misfire without the rune',
    'or 10 percent anyway;',
    'outside: 2-12 fist-sized',
    'rocks at 1-6 each; indoors:',
    '3-36; underground: 5-20',
    'base times 1 per 10 feet',
    'of drop height; proper',
    'use aims at the roof 30-60',
    'feet beyond, collapses up',
    'to 20 by 20 feet, a 10',
    'feet radius, damage only',
    'indoors or underground),',
    'Horn of the Tritons (conch',
    'shell; once per day, a',
    'triton 3; calm 1 mile,',
    'dispels water elemental or',
    'weird; summon on a d6 band',
    '1-2 hippocampi 5-20, 3-5',
    'giant sea horses 5-30, 6',
    'sea lions 1-10, friendly;',
    'panic animal-or-lower',
    'intelligence, flee unless',
    'save, the savers minus 5',
    'to hit for 3-18 turns =',
    '30-180 rounds; heard by',
    'tritons 1 league), Horn of',
    'Valhalla (4 varieties,',
    'blown once every 7 days;',
    'silver 1-8, 4-10 at 2nd,',
    'any class; brass 9-15, 3-9',
    'at 3rd, C F T; bronze',
    '16-18, 2-8 at 4th, C F;',
    'iron 19-20, 2-5 at 5th, F;',
    'the wrong class is',
    'attacked; AC 4, 6 hp per',
    'die, sword and spear or',
    'axe and spear 50 50;',
    'fights until slain or',
    '6 turns; 50 percent',
    'aligned, radical',
    'difference: the blower',
    'attacked; bronze doubles',
    'and iron triples the',
    '1,000 xp / 15,000 gp base',
    '- the row 20 double',
    'asterisk), Horseshoes of',
    'Speed (4 iron shoes, never',
    'wear out; double speed; 1',
    'percent per 7 leagues that',
    '1 drops; one lost: 150',
    'percent; two lost: normal),',
    'Horseshoes of a Zephyr',
    '(travel without touching',
    'ground, water crossed, no',
    'tracks; normal speeds; no',
    'tire for 12 hours per day),',
    'Incense of Meditation',
    '(recognizable by a',
    '5th-plus cleric when',
    'burning; 8 hours of prayer:',
    'full and best spell',
    'effects, cure always max,',
    'broadest area, saves at',
    'minus 1, the dead revived',
    'with the not-surviving',
    'chance halved (rounded',
    'down); 2-8 pieces, one',
    'burns 8 hours, effects 24',
    'hours). 73 accessors: 60',
    'scalars + 13 walkers (the',
    'triton summon and Valhalla',
    'variety tables; the dice,',
    'level, percent and',
    'turn-rounds ladders are',
    'arithmetic checks). New',
    'R269 battery audit; census',
    '187. Next: part 14 - Incense',
    'of Obsession onward in',
    'part2 from line 630 (global',
    '11695; the ioun stones and',
    'instruments follow; kMisc3',
    'rows 24+).',
]

# ---- the splice self-asserts ----
HTEXT = NL.join(HDR)
defs = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(]', HTEXT)
assert len(defs) == 73, 'accessor count is not 73'
assert len(set(defs)) == 73, 'accessor names not unique'
scal = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(][)]', HTEXT)
walk = [d for d in defs if d not in scal]
assert len(scal) == 60, 'scalar count is not 60'
assert len(walk) == 13, 'walker count is not 13'
ATEXT = NL.join(AUDIT)
audited = set(re.findall(r'rules::(mmp[A-Za-z0-9]+)[(]', ATEXT))
assert audited == set(defs), 'audit does not probe every accessor'
for p in range(1, 13):
    pp = os.path.join(ROOT, 'rules/miscprose%d.h' % p)
    if os.path.exists(pp):
        pt = open(pp, encoding='utf-8').read()
        for n in defs:
            assert n not in pt, 'name collision with part %d' % p
for grp in (HDR, AUDIT, GAP):
    for el in grp:
        if isinstance(el, str):
            assert chr(39) not in el, 'apostrophe in content'
            probe = el.replace(chr(92) + 'n', '')
            assert chr(92) not in probe, 'backslash in content'
for grp in (HDR, AUDIT):
    for el in grp:
        assert len(el) <= 79, 'content line too long'
for el in GAP:
    assert len(el) <= 38, 'gap line too long'

# ---- apply patch 1 ----
if os.path.exists(os.path.join(ROOT, P1)):
    already += 1
    assert rd(P1) == NL.join(HDR), P1 + ' exists but differs'
else:
    wr(P1, NL.join(HDR))
    applied += 1
    assert rd(P1) == NL.join(HDR), P1 + ' write mismatch'
assert rd(P1).count(
    'R269: the III.E misc magic explanation prose part 13') == 1

# ---- apply patch 2: the regtest include ----
INC_OLD = ('#include "rules/miscprose12.h"  // R268: the III.E misc'
           ' magic explanation prose part 12 pins')
INC_NEW = ('#include "rules/miscprose13.h"  // R269: the III.E misc'
           ' magic explanation prose part 13 pins')
RG = rd('regtest.cpp')
if INC_NEW in RG:
    already += 1
    assert RG.count(INC_NEW) == 1, 'include not unique'
else:
    assert RG.count(INC_OLD) == 1, 'R268 include anchor missing'
    RG = RG.replace(INC_OLD, INC_OLD + NL + INC_NEW)
    applied += 1
    assert RG.count(INC_NEW) == 1, 'include insert failed'
wr('regtest.cpp', RG)

# ---- apply patch 3: the R269 audit block ----
ANCHOR = ('    // ---- R227: the wis mental save wiring audit ----')
AUDIT_STR = NL.join(AUDIT)
if ('printf("R269 misc magic prose part 13 pins audit:') in RG:
    already += 1
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
else:
    assert RG.count(ANCHOR) == 1, 'R227 anchor not unique'
    RG = RG.replace(ANCHOR, AUDIT_STR + NL + ANCHOR)
    applied += 1
    assert RG.count(
        'printf("R269 misc magic prose part 13 pins audit:') == 1, (
        'audit printf not unique')
wr('regtest.cpp', RG)

# ---- apply patch 4: the gap entry ----
GP = rd('tools/dmg_gap_report.md')
if GP.count('R269 landed the III.E misc') == 1:
    already += 1
else:
    TAIL = ('rows 18+).' + NL + NL + 'Categories:')
    assert GP.count(TAIL) == 1, 'R268 gap tail anchor not unique'
    NEWTAIL = ('rows 18+).' + NL + NL + NL.join(GAP) +
               NL + NL + 'Categories:')
    GP = GP.replace(TAIL, NEWTAIL)
    applied += 1
    assert GP.count('R269 landed the III.E misc') == 1, (
        'gap entry insert failed')
wr('tools/dmg_gap_report.md', GP)

# ---- report ----
assert applied + already == 4, 'patch count wrong'
print('R269 splice: ALL OK (applied %d, already %d)'
      % (applied, already))
print('R269 note: 4 patches; the III.E misc magic')
print('explanation prose part 13 - Horn of Collapsing')
print('through Incense of Meditation, part2 lines')
print('581-626; census 187.')
COMMIT = ('R269: the III.E misc magic explanation prose part 13'
          ' pinned - Horn of Collapsing through the Incense of'
          ' Meditation in part2 lines 581-626 (census 187)')
print('commit: ' + COMMIT)

