#!/usr/bin/env python3
# R274 splice: the III.E misc magic explanation prose
# part 18 pins - the Manual of Stealthy Pilfering, the
# Mattock and Maul of the Titans, the Medallions of
# ESP and Thought Projection, the Mirrors of Life
# Trapping, Mental Prowess and Opposition and the
# Necklaces of Adaptation and Missiles, part2 lines
# 843-900 (DMG p.150-151), pinning the kMisc4 rows
# 9-18 of the 36-row III.E.4 table. ONE mid-sentence
# break inside the slice: the mirror of life trapping
# paragraph splits between not a (863) and factor
# (865), the upload prints no running head at the
# break - ONE seam restored this round; the slice
# rides the pp.150-151 attribution on the
# R273-established p.150 base. The upload quirks this
# round: the necklace of missiles table is badly
# mangled (pipes misplaced, fragments pushed into the
# wrong cells) - the dash-separated count ladders
# reconstruct it exactly and cross-check against the
# printed 9-12 example (one 7-dice, two 5-dice, four
# 3-dice); the stray apostrophe artifact after the
# word manual recurs in the pilfering paragraph (a
# like manual) beside a printed magic- users with a
# space (both pinned as the upload prints them,
# apostrophe-free here); the medallion table prints
# clean. 4 patches, marker-based idempotence, assert
# after every patch. ZERO apostrophes and ZERO literal
# backslashes in the content below (the printf newline
# is built via BS = chr(92)).

import os
import re
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose18.h',
    '// R274: the III.E misc magic explanation prose part 18',
    '// (DMG p.150-151) - the Manual of Stealthy Pilfering, the',
    '// Mattock and Maul of the Titans, the Medallions of ESP',
    '// and Thought Projection, the Mirrors of Life Trapping,',
    '// Mental Prowess and Opposition and the Necklaces of',
    '// Adaptation and Missiles, part2 lines 843-900 (global',
    '// = 11065 + part2 line), pinning the kMisc4 rows 9-18 of',
    '// the 36-row III.E.4 table. ONE mid-sentence break inside',
    '// the slice: the mirror of life trapping paragraph splits',
    '// between not a (863) and factor (865), the upload',
    '// prints no running head at the break - ONE',
    '// seam restored this round; the slice rides the',
    '// pp.150-151 attribution on the R273-established p.150',
    '// base. The upload quirks this round: the necklace of',
    '// missiles table is badly mangled (pipes misplaced,',
    '// fragments pushed into the wrong cells) - the',
    '// dash-separated count ladders reconstruct it exactly',
    '// and cross-check against the printed example:',
    '// one 7-dice, two 5-dice, four 3-dice (the 9-12 row);',
    '// the stray apostrophe artifact after the word manual',
    '// recurs in the pilfering paragraph (a like manual)',
    '// beside a printed magic- users with a space (both',
    '// pinned as the upload prints them,',
    '// apostrophe-free here); the medallion table prints',
    '// clean. 67',
    '// accessors: 59 scalars + 8 walkers (the medallion die',
    '// bands, ranges and empathy marks; the necklace die',
    '// bands, hit dice columns and the flattened 70-cell',
    '// count table), no name collisions with miscprose1.h',
    '// through miscprose17.h. Pure data + helpers,',
    '// header-only (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpStealthyPracticeMonths() {',
    '    // the thief practices 1 month thereafter',
    '    return 1;',
    '}',
    '',
    'inline int mmpStealthyKnowledgeMonths() {',
    '    // the knowledge is retained for 3 months',
    '    return 3;',
    '}',
    '',
    'inline int mmpStealthyAssassinXp() {',
    '    // an assassin gains but 5,000 additional xp',
    '    return 5000;',
    '}',
    '',
    'inline int mmpStealthyAssassinWeeks() {',
    '    // the contents pondered for 1 week',
    '    return 1;',
    '}',
    '',
    'inline int mmpStealthyWrongDamageMin() {',
    '    // a wrong-class reader takes 5-20 damage',
    '    return 5;',
    '}',
    '',
    'inline int mmpStealthyWrongDamageMax() {',
    '    // the upper edge of the 5-20 damage',
    '    return 20;',
    '}',
    '',
    'inline int mmpStealthyStunRoundsMin() {',
    '    // stunned a like number of rounds',
    '    return 5;',
    '}',
    '',
    'inline int mmpStealthyStunRoundsMax() {',
    '    // the upper edge of the like-number rounds',
    '    return 20;',
    '}',
    '',
    'inline int mmpStealthyXpLossMin() {',
    '    // a failed save loses 5,000-20,000 xp',
    '    return 5000;',
    '}',
    '',
    'inline int mmpStealthyXpLossMax() {',
    '    // the upper edge of the 5,000-20,000 xp loss',
    '    return 20000;',
    '}',
    '',
    'inline int mmpStealthyAtoneDays() {',
    '    // must atone within 1 day',
    '    return 1;',
    '}',
    '',
    'inline int mmpStealthyWisdomLoss() {',
    '    // or lose 1 point of wisdom',
    '    return 1;',
    '}',
    '',
    'inline int mmpMattockLengthFeet() {',
    '    // the huge digging tool is 10 feet long',
    '    return 10;',
    '}',
    '',
    'inline int mmpMattockWeightLb() {',
    '    // and weighs over 100 pounds',
    '    return 100;',
    '}',
    '',
    'inline int mmpMattockMinStrength() {',
    '    // a giant-sized user of strength 20 or more',
    '    return 20;',
    '}',
    '',
    'inline int mmpMattockEarthCubicFeet() {',
    '    // loosens earth in a 100 cubic foot area',
    '    return 100;',
    '}',
    '',
    'inline int mmpMattockRockCubicFeet() {',
    '    // smashes rock in a 20 cubic feet area',
    '    return 20;',
    '}',
    '',
    'inline int mmpMattockAreaTurns() {',
    '    // either area in 1 turn of work',
    '    return 1;',
    '}',
    '',
    'inline int mmpMattockHitBonus() {',
    '    // +3 to hit as a weapon',
    '    return 3;',
    '}',
    '',
    'inline int mmpMattockDamageMin() {',
    '    // does 5-30 damage, strength bonuses aside',
    '    return 5;',
    '}',
    '',
    'inline int mmpMattockDamageMax() {',
    '    // the upper edge of the 5-30 damage',
    '    return 30;',
    '}',
    '',
    'inline int mmpMaulLengthFeet() {',
    '    // the huge mallet is 8 feet long',
    '    return 8;',
    '}',
    '',
    'inline int mmpMaulWeightLb() {',
    '    // and weighs over 150 pounds',
    '    return 150;',
    '}',
    '',
    'inline int mmpMaulMinStrength() {',
    '    // a giant-sized user of strength 21 or greater',
    '    return 21;',
    '}',
    '',
    'inline int mmpMaulPileDiameterFeet() {',
    '    // drives piles of up to 2 feet diameter',
    '    return 2;',
    '}',
    '',
    'inline int mmpMaulPileDepthFeet() {',
    '    // into normal earth at 4 feet per blow',
    '    return 4;',
    '}',
    '',
    'inline int mmpMaulBlowsPerRound() {',
    '    // 2 blows per round',
    '    return 2;',
    '}',
    '',
    'inline int mmpMaulDoorHeightFeet() {',
    '    // an oaken door of up to 10 feet height',
    '    return 10;',
    '}',
    '',
    'inline int mmpMaulDoorWidthFeet() {',
    '    // by 4 feet width',
    '    return 4;',
    '}',
    '',
    'inline int mmpMaulDoorThicknessInches() {',
    '    // by 2 inch thickness',
    '    return 2;',
    '}',
    '',
    'inline int mmpMaulDoorBlows() {',
    '    // smashed to flinders in 1 blow',
    '    return 1;',
    '}',
    '',
    'inline int mmpMaulDoorIronBlows() {',
    '    // 2 blows if heavily bound with iron',
    '    return 2;',
    '}',
    '',
    'inline int mmpMaulHitBonus() {',
    '    // +2 to hit as a weapon',
    '    return 2;',
    '}',
    '',
    'inline int mmpMaulDamageMin() {',
    '    // inflicts 10-40 damage, strength bonuses aside',
    '    return 10;',
    '}',
    '',
    'inline int mmpMaulDamageMax() {',
    '    // the upper edge of the 10-40 damage',
    '    return 40;',
    '}',
    '',
    'inline int mmpEspPathWidthFeet() {',
    '    // the path is 1 foot wide at the medallion',
    '    return 1;',
    '}',
    '',
    'inline int mmpEspBroadenFeet() {',
    '    // broadening 2 feet every 10 feet of reach',
    '    return 2;',
    '}',
    '',
    'inline int mmpEspBroadenPerFeet() {',
    '    // every 10 feet from the device',
    '    return 10;',
    '}',
    '',
    'inline int mmpEspMaxWidthFeet() {',
    '    // up to an 11 foot maximum width',
    '    return 11;',
    '}',
    '',
    'inline int mmpEspMaxWidthAtFeet() {',
    '    // the maximum reached at 50 feet',
    '    return 50;',
    '}',
    '',
    'inline int mmpEspUseRounds() {',
    '    // a full round to use the device',
    '    return 1;',
    '}',
    '',
    'inline int mmpEspStoneBlockFeet() {',
    '    // stone of over 3 feet thickness blocks',
    '    return 3;',
    '}',
    '',
    'inline int mmpEspMetalBlockSixthsFeet() {',
    '    // metal of over 1/6 foot thickness blocks',
    '    return 1;',
    '}',
    '',
    'inline int mmpEspMalfunctionRoll() {',
    '    // malfunctions on a die roll of 6',
    '    return 6;',
    '}',
    '',
    'inline int mmpEspMalfunctionDieSides() {',
    '    // the roll is on d6, checked each use',
    '    return 6;',
    '}',
    '',
    'inline int mmpEspRowLo(int i) {',
    '    // the printed die band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 16, 19, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpEspRowHi(int i) {',
    '    // the printed die band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        15, 18, 19, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpEspRangeFeet(int i) {',
    '    // the medallion range per type; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        30, 30, 60, 90,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpEspEmpathy(int i) {',
    '    // the with-empathy mark per type; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        0, 1, 0, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpProjectionWorksRoll() {',
    '    // correct without projecting on a roll of 6',
    '    return 6;',
    '}',
    '',
    'inline int mmpTrapAreaSquareFeet() {',
    '    // the crystal device about 4 square feet',
    '    return 4;',
    '}',
    '',
    'inline int mmpTrapCellMin() {',
    '    // from 13 compartments at the fewest',
    '    return 13;',
    '}',
    '',
    'inline int mmpTrapCellMax() {',
    '    // to 18 compartments at the most',
    '    return 18;',
    '}',
    '',
    'inline int mmpTrapTriggerFeet() {',
    '    // a looker coming within 30 feet',
    '    return 30;',
    '}',
    '',
    'inline int mmpTrapSeePctUnaware() {',
    '    // 100 percent when unaware of the device',
    '    return 100;',
    '}',
    '',
    'inline int mmpTrapSeePctAvoiding() {',
    '    // dropping to 50 when actively avoiding',
    '    return 50;',
    '}',
    '',
    'inline int mmpTrapSeePctAware() {',
    '    // and 20 when aware it traps life',
    '    return 20;',
    '}',
    '',
    'inline int mmpTrapOverflowFreed() {',
    '    // 1 random victim freed on overflow',
    '    return 1;',
    '}',
    '',
    'inline int mmpProwessQuestionsPerWeek() {',
    '    // answers one short question per week',
    '    return 1;',
    '}',
    '',
    'inline int mmpProwessWidthFeet() {',
    '    // the typical mirror 5 feet by',
    '    return 5;',
    '}',
    '',
    'inline int mmpProwessHeightFeet() {',
    '    // 2 feet',
    '    return 2;',
    '}',
    '',
    'inline int mmpAdaptationAirlessDays() {',
    '    // exists in airless space for up to 7 days',
    '    return 7;',
    '}',
    '',
    'inline int mmpMissileRangeInches() {',
    '    // the globes hurled up to 7 inches distance',
    '    return 7;',
    '}',
    '',
    'inline int mmpNeckRowLo(int i) {',
    '    // the printed die band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        1, 5, 9, 13, 17, 19, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpNeckRowHi(int i) {',
    '    // the printed die band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 6) i = 6;',
    '    static const int t[7] = {',
    '        4, 8, 12, 16, 18, 19, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpNeckDieOf(int i) {',
    '    // the hit dice column ladder; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 9) i = 9;',
    '    static const int t[10] = {',
    '        11, 10, 9, 8, 7, 6, 5, 4, 3, 2,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpNeckCell(int i) {',
    '    // the flattened count table, the row-major',
    '    // index i = row * 10 + column, the columns',
    '    // running the 11-dice through 2-dice ladder;',
    '    // the 9-12 row reads the printed example:',
    '    // one 7-dice, two 5-dice, four 3-dice; clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 69) i = 69;',
    '    static const int t[70] = {',
    '        0, 0, 0, 0, 0, 0, 1, 0, 2, 0,',
    '        0, 0, 0, 0, 0, 1, 0, 2, 0, 2,',
    '        0, 0, 0, 0, 1, 0, 2, 0, 4, 0,',
    '        0, 0, 0, 1, 0, 2, 0, 2, 0, 4,',
    '        0, 0, 1, 0, 2, 0, 2, 0, 2, 0,',
    '        0, 1, 0, 2, 0, 2, 0, 4, 0, 0,',
    '        1, 0, 2, 0, 2, 0, 2, 0, 2, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    '}  // namespace rules',
]

AUDIT = [
    '    // ---- R274: the III.E misc magic explanation',
    '    // prose part 18 ----',
    '    // The Manual of Stealthy Pilfering, the Mattock',
    '    // and Maul of the Titans, the Medallions of ESP',
    '    // and Thought Projection, the Mirrors of Life',
    '    // Trapping, Mental Prowess and Opposition and',
    '    // the Necklaces of Adaptation and Missiles,',
    '    // part2 lines 843-900 - the slice pinning the',
    '    // kMisc4 rows 9-18 of the 36-row III.E.4 table.',
    '    {',
    '        int bad = 0;',
    '        // the manual of stealthy pilfering',
    '        if (rules::mmpStealthyPracticeMonths() != 1 ||',
    '            rules::mmpStealthyKnowledgeMonths() != 3 ||',
    '            rules::mmpStealthyAssassinXp() != 5000 ||',
    '            rules::mmpStealthyAssassinWeeks() != 1 ||',
    '            rules::mmpStealthyWrongDamageMin() != 5 ||',
    '            rules::mmpStealthyWrongDamageMax() != 20 ||',
    '            rules::mmpStealthyXpLossMin() != 5000 ||',
    '            rules::mmpStealthyXpLossMax() != 20000 ||',
    '            rules::mmpStealthyAtoneDays() != 1 ||',
    '            rules::mmpStealthyWisdomLoss() != 1) ++bad;',
    '        // the stun rounds are a like number of the',
    '        // printed damage pair',
    '        if (rules::mmpStealthyStunRoundsMin() !=',
    '            rules::mmpStealthyWrongDamageMin() ||',
    '            rules::mmpStealthyStunRoundsMax() !=',
    '            rules::mmpStealthyWrongDamageMax()) ++bad;',
    '        // the mattock of the titans',
    '        if (rules::mmpMattockLengthFeet() != 10 ||',
    '            rules::mmpMattockWeightLb() != 100 ||',
    '            rules::mmpMattockMinStrength() != 20 ||',
    '            rules::mmpMattockEarthCubicFeet() != 100 ||',
    '            rules::mmpMattockRockCubicFeet() != 20 ||',
    '            rules::mmpMattockAreaTurns() != 1 ||',
    '            rules::mmpMattockHitBonus() != 3 ||',
    '            rules::mmpMattockDamageMin() != 5 ||',
    '            rules::mmpMattockDamageMax() != 30) ++bad;',
    '        // the maul of the titans',
    '        if (rules::mmpMaulLengthFeet() != 8 ||',
    '            rules::mmpMaulWeightLb() != 150 ||',
    '            rules::mmpMaulMinStrength() != 21 ||',
    '            rules::mmpMaulPileDiameterFeet() != 2 ||',
    '            rules::mmpMaulPileDepthFeet() != 4 ||',
    '            rules::mmpMaulBlowsPerRound() != 2 ||',
    '            rules::mmpMaulDoorHeightFeet() != 10 ||',
    '            rules::mmpMaulDoorWidthFeet() != 4 ||',
    '            rules::mmpMaulDoorThicknessInches() != 2 ||',
    '            rules::mmpMaulDoorBlows() != 1 ||',
    '            rules::mmpMaulDoorIronBlows() != 2 ||',
    '            rules::mmpMaulHitBonus() != 2 ||',
    '            rules::mmpMaulDamageMin() != 10 ||',
    '            rules::mmpMaulDamageMax() != 40) ++bad;',
    '        // the medallion of esp scalars',
    '        if (rules::mmpEspPathWidthFeet() != 1 ||',
    '            rules::mmpEspBroadenFeet() != 2 ||',
    '            rules::mmpEspBroadenPerFeet() != 10 ||',
    '            rules::mmpEspMaxWidthFeet() != 11 ||',
    '            rules::mmpEspMaxWidthAtFeet() != 50 ||',
    '            rules::mmpEspUseRounds() != 1 ||',
    '            rules::mmpEspStoneBlockFeet() != 3 ||',
    '            rules::mmpEspMetalBlockSixthsFeet() != 1 ||',
    '            rules::mmpEspMalfunctionRoll() != 6 ||',
    '            rules::mmpEspMalfunctionDieSides() != 6) ++bad;',
    '        // the medallion type table against static twins',
    '        static const int kElo[4] = {',
    '            1, 16, 19, 20,',
    '        };',
    '        static const int kEhi[4] = {',
    '            15, 18, 19, 20,',
    '        };',
    '        static const int kErg[4] = {',
    '            30, 30, 60, 90,',
    '        };',
    '        static const int kEmp[4] = {',
    '            0, 1, 0, 0,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpEspRowLo(i) != kElo[i] ||',
    '                rules::mmpEspRowHi(i) != kEhi[i] ||',
    '                rules::mmpEspRangeFeet(i) != kErg[i] ||',
    '                rules::mmpEspEmpathy(i) != kEmp[i]) ++bad;',
    '        // the medallion die bands tile 1-20 without gaps',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpEspRowLo(i + 1) !=',
    '                rules::mmpEspRowHi(i) + 1) ++bad;',
    '        if (rules::mmpEspRowLo(0) != 1 ||',
    '            rules::mmpEspRowHi(3) != 20) ++bad;',
    '        // the medallion of thought projection',
    '        if (rules::mmpProjectionWorksRoll() != 6) ++bad;',
    '        // both printed medallion rolls are the 6 on d6',
    '        if (rules::mmpProjectionWorksRoll() !=',
    '            rules::mmpEspMalfunctionRoll()) ++bad;',
    '        // the mirror of life trapping',
    '        if (rules::mmpTrapAreaSquareFeet() != 4 ||',
    '            rules::mmpTrapCellMin() != 13 ||',
    '            rules::mmpTrapCellMax() != 18 ||',
    '            rules::mmpTrapTriggerFeet() != 30 ||',
    '            rules::mmpTrapSeePctUnaware() != 100 ||',
    '            rules::mmpTrapSeePctAvoiding() != 50 ||',
    '            rules::mmpTrapSeePctAware() != 20 ||',
    '            rules::mmpTrapOverflowFreed() != 1) ++bad;',
    '        // the 13-18 cell span is the 5 gap',
    '        if (rules::mmpTrapCellMax() -',
    '            rules::mmpTrapCellMin() != 5) ++bad;',
    '        // the mirror of mental prowess',
    '        if (rules::mmpProwessQuestionsPerWeek() != 1 ||',
    '            rules::mmpProwessWidthFeet() != 5 ||',
    '            rules::mmpProwessHeightFeet() != 2) ++bad;',
    '        // the necklace of adaptation',
    '        if (rules::mmpAdaptationAirlessDays() != 7) ++bad;',
    '        // the necklace of missiles',
    '        if (rules::mmpMissileRangeInches() != 7) ++bad;',
    '        static const int kNlo[7] = {',
    '            1, 5, 9, 13, 17, 19, 20,',
    '        };',
    '        static const int kNhi[7] = {',
    '            4, 8, 12, 16, 18, 19, 20,',
    '        };',
    '        static const int kHdc[10] = {',
    '            11, 10, 9, 8, 7, 6, 5, 4, 3, 2,',
    '        };',
    '        static const int kNcl[70] = {',
    '            0, 0, 0, 0, 0, 0, 1, 0, 2, 0,',
    '            0, 0, 0, 0, 0, 1, 0, 2, 0, 2,',
    '            0, 0, 0, 0, 1, 0, 2, 0, 4, 0,',
    '            0, 0, 0, 1, 0, 2, 0, 2, 0, 4,',
    '            0, 0, 1, 0, 2, 0, 2, 0, 2, 0,',
    '            0, 1, 0, 2, 0, 2, 0, 4, 0, 0,',
    '            1, 0, 2, 0, 2, 0, 2, 0, 2, 0,',
    '        };',
    '        for (int i = 0; i < 7; ++i)',
    '            if (rules::mmpNeckRowLo(i) != kNlo[i] ||',
    '                rules::mmpNeckRowHi(i) != kNhi[i]) ++bad;',
    '        for (int i = 0; i < 10; ++i)',
    '            if (rules::mmpNeckDieOf(i) != kHdc[i]) ++bad;',
    '        for (int i = 0; i < 70; ++i)',
    '            if (rules::mmpNeckCell(i) != kNcl[i]) ++bad;',
    '        // the necklace die bands tile 1-20 without gaps',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpNeckRowLo(i + 1) !=',
    '                rules::mmpNeckRowHi(i) + 1) ++bad;',
    '        if (rules::mmpNeckRowLo(0) != 1 ||',
    '            rules::mmpNeckRowHi(6) != 20) ++bad;',
    '        // the hit dice columns descend by one',
    '        for (int i = 0; i < 9; ++i)',
    '            if (rules::mmpNeckDieOf(i + 1) !=',
    '                rules::mmpNeckDieOf(i) - 1) ++bad;',
    '        // the printed 9-12 example: one 7-dice, two',
    '        // 5-dice and four 3-dice - seven missiles',
    '        if (rules::mmpNeckCell(24) != 1 ||',
    '            rules::mmpNeckCell(26) != 2 ||',
    '            rules::mmpNeckCell(28) != 4) ++bad;',
    '        // every row sums to its missile count',
    '        static const int kTot[7] = {',
    '            3, 5, 7, 9, 7, 9, 9,',
    '        };',
    '        for (int r = 0; r <= 6; ++r)',
    '            if (rules::mmpNeckCell(r * 10) +',
    '                rules::mmpNeckCell(r * 10 + 1) +',
    '                rules::mmpNeckCell(r * 10 + 2) +',
    '                rules::mmpNeckCell(r * 10 + 3) +',
    '                rules::mmpNeckCell(r * 10 + 4) +',
    '                rules::mmpNeckCell(r * 10 + 5) +',
    '                rules::mmpNeckCell(r * 10 + 6) +',
    '                rules::mmpNeckCell(r * 10 + 7) +',
    '                rules::mmpNeckCell(r * 10 + 8) +',
    '                rules::mmpNeckCell(r * 10 + 9) !=',
    '                kTot[r]) ++bad;',
    '        // the engine kMisc4 rows 9-18: the die band',
    '        // edges, the (T), (F) and (M) marks, the single',
    '        // star on the necklace of missiles and the one',
    '        // dual row on the medallion of esp',
    '        static const int kRlo[10] = {',
    '            10, 11, 12, 13, 16, 18, 19, 20, 21, 24,',
    '        };',
    '        static const int kRhi[10] = {',
    '            10, 11, 12, 15, 17, 18, 19, 20, 23, 27,',
    '        };',
    '        for (int i = 0; i < 10; ++i)',
    '            if (rules::m4RowLo(9 + i) != kRlo[i] ||',
    '                rules::m4RowHi(9 + i) != kRhi[i]) ++bad;',
    '        if (rules::m4StarCount(18) != 1 ||',
    '            rules::m4IsDualValued(12) != 1 ||',
    '            rules::m4UsableByThief(9) != 1 ||',
    '            rules::m4UsableByFighter(10) != 1 ||',
    '            rules::m4UsableByMagicUser(14) != 1 ||',
    '            rules::m4RowCount() != 36) ++bad;',
    '        for (int i = 9; i < 18; ++i)',
    '            if (rules::m4StarCount(i) != 0 ||',
    '                rules::m4UsableByCleric(i) != 0) ++bad;',
    '        for (int i = 9; i < 19; ++i)',
    '            if (i != 12 && rules::m4IsDualValued(i) != 0) ++bad;',
    '        for (int i = 9; i < 19; ++i)',
    '            if (i != 9 && rules::m4UsableByThief(i) != 0) ++bad;',
    '        for (int i = 9; i < 19; ++i)',
    '            if (i != 10 && rules::m4UsableByFighter(i) != 0) ++bad;',
    '        for (int i = 9; i < 19; ++i)',
    '            if (i != 14 &&',
    '                rules::m4UsableByMagicUser(i) != 0) ++bad;',
    '        // the engine per-hit-die and dual-value pins',
    '        if (rules::m4MissilePerHitDieXp() != 50 ||',
    '            rules::m4MissilePerHitDieGp() != 200 ||',
    '            rules::m4MedallionEspXpLow() != 1000 ||',
    '            rules::m4MedallionEspXpHigh() != 3000 ||',
    '            rules::m4MedallionEspGpLow() != 10000 ||',
    '            rules::m4MedallionEspGpHigh() != 30000 ||',
    '            rules::m4ThiefCount() != 3 ||',
    '            rules::m4FighterCount() != 4 ||',
    '            rules::m4MagicUserCount() != 6) ++bad;',
    '        printf("R274 misc magic prose part 18 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]

GAP = [
    'R274 landed the III.E misc',
    'magic explanation prose part',
    '18 (part2 lines 843-900;',
    'global = 11065 + part2',
    'line), the Manual of Stealthy',
    'Pilfering, the Mattock and',
    'Maul of the Titans, the',
    'Medallions of ESP and',
    'Thought Projection, the',
    'Mirrors of Life Trapping,',
    'Mental Prowess and',
    'Opposition and the Necklaces',
    'of Adaptation and Missiles',
    '(DMG p.150-151) - the slice',
    'pinning the kMisc4',
    'rows 9-18 of the 36-row',
    'III.E.4 table. ONE',
    'mid-sentence break: the',
    'mirror of life trapping',
    'paragraph splits between',
    'not a (863) and factor',
    '(865), the upload prints no',
    'running head at the break -',
    'ONE seam restored this',
    'round; the slice rides the',
    'pp.150-151 attribution on',
    'the R273-established p.150',
    'base. The upload quirks:',
    'the necklace of missiles',
    'table is badly mangled (the',
    'pipes misplaced, fragments',
    'pushed into the wrong',
    'cells), the dash-separated',
    'count ladders reconstruct',
    'it and cross-check against',
    'the printed 9-12 example',
    '(one 7-dice, two 5-dice,',
    'four 3-dice); the stray',
    'apostrophe artifact after',
    'the word manual recurs (a',
    'like manual) and the',
    'pilfering paragraph prints',
    'magic- users with a space',
    '(pinned as the upload',
    'prints it, apostrophe-free',
    'in the header); the',
    'medallion table prints',
    'clean. The items: Manual',
    'of Stealthy Pilfering (thief',
    'only, 1 month practice to',
    'the mid-point, remembered',
    '3 months, assassins 5,000',
    'xp after 1 week pondering,',
    'fighters magic-users and',
    'monks no comprehension,',
    'clerics rangers and',
    'paladins take 5-20 damage,',
    'stunned a like number of',
    'rounds, failed save loses',
    '5,000-20,000 xp, atone in',
    '1 day or lose 1 wisdom),',
    'Mattock of the Titans (10',
    'feet, over 100 pounds,',
    'strength 20+, 100 cubic',
    'foot earth or 20 cubic foot',
    'rock per turn, +3 to hit,',
    '5-30 damage), Maul of the',
    'Titans (8 feet, over 150',
    'pounds, strength 21+, piles',
    'of 2 feet diameter driven 4',
    'feet per blow, 2 blows per',
    'round, oaken door 10 by 4',
    'by 2 inches smashed in 1',
    'blow, 2 if iron-bound, +2',
    'to hit, 10-40 damage),',
    'Medallion of ESP (path 1',
    'foot wide broadening 2',
    'feet every 10 feet to an',
    '11 foot maximum at 50',
    'feet, full round use,',
    'blocked by 3 foot stone,',
    '1/6 foot metal or lead',
    'gold platinum sheeting,',
    'malfunctions on 6 on d6,',
    'surface thoughts only;',
    'table 1-15 30 feet, 16-18',
    '30 feet with empathy, 19',
    '60 feet, 20 90 feet),',
    'Medallion of Thought',
    'Projection (like the ESP',
    'even as to range, also',
    'broadcasts the user',
    'thoughts, correct without',
    'projecting on 6), Mirror of',
    'Life Trapping (magic-user',
    'only, 4 square feet, 13-18',
    'cells, trigger within 30',
    'feet, save or trapped, 100',
    'percent unaware, 50',
    'avoiding, 20 aware,',
    'overflow frees 1 random,',
    'broken frees all), Mirror',
    'of Mental Prowess (reads',
    'thoughts even in unknown',
    'languages, scrys as a',
    'crystal ball with',
    'clairaudience into other',
    'planes, portal both ways,',
    '1 short question per week,',
    '5 by 2 feet), Mirror of',
    'Opposition (an exact',
    'duplicate with all items',
    'and powers attacks at',
    'once, either defeat makes',
    'it vanish), Necklace of',
    'Adaptation (ignores',
    'respiratory gases,',
    'breathes water, 7 days',
    'airless), Necklace of',
    'Missiles (golden globes',
    'hurled to 7 inches, burst',
    'as fireballs; table 1-4',
    'one 5-dice two 3-dice,',
    '5-8 one 6-dice two 4-dice',
    'two 2-dice, 9-12 one',
    '7-dice two 5-dice four',
    '3-dice, 13-16 one 8-dice',
    'two 6-dice two 4-dice four',
    '2-dice, 17-18 one 9-dice',
    'two 7-dice two 5-dice two',
    '3-dice, 19 one 10-dice two',
    '8-dice two 6-dice four',
    '4-dice, 20 one 11-dice two',
    '9-dice two 7-dice two',
    '5-dice two 3-dice; a',
    'failed save on magical',
    'fire detonates all). 67',
    'accessors: 59 scalars + 8',
    'walkers (the medallion',
    'bands, ranges and empathy;',
    'the necklace bands, hit',
    'dice columns and cells),',
    'no name collisions parts',
    '1-17. New R274 battery',
    'audit; census 192. Next:',
    'R275 III.E part 19 - the',
    'Necklace of Prayer Beads',
    'onward in part2 from line',
    '905 (global 11970; the',
    'strangulation necklace,',
    'nets, pigments, pearls and',
    'periapts follow; kMisc4',
    'rows 19+ continue).',
]

# ---- the splice self-asserts ----
HTEXT = NL.join(HDR)
defs = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(]', HTEXT)
assert len(defs) == 67, 'accessor count is not 67'
assert len(set(defs)) == 67, 'accessor names not unique'
scal = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(][)]', HTEXT)
walk = [d for d in defs if d not in scal]
assert len(scal) == 59, 'scalar count is not 59'
assert len(walk) == 8, 'walker count is not 8'
assert set(walk) == {'mmpEspRowLo', 'mmpEspRowHi',
                    'mmpEspRangeFeet', 'mmpEspEmpathy',
                    'mmpNeckRowLo', 'mmpNeckRowHi',
                    'mmpNeckDieOf', 'mmpNeckCell'}, 'wrong walkers'
ATEXT = NL.join(AUDIT)
audited = set(re.findall(r'rules::(mmp[A-Za-z0-9]+)[(]', ATEXT))
assert audited == set(defs), 'audit does not probe every accessor'
for p in range(1, 18):
    pp = os.path.join(ROOT, 'rules/miscprose%d.h' % p)
    if os.path.exists(pp):
        pt = open(pp, encoding='utf-8').read()
        for n in defs:
            assert n not in pt, 'name collision with part %d' % p
for grp in (HDR, AUDIT, GAP):
    for el in grp:
        if isinstance(el, str):
            assert chr(39) not in el, 'apostrophe in content'
            probe = el.replace(chr(92) + 'n', '')
            assert chr(92) not in probe, 'backslash in content'
            assert NL not in el, 'list element spans lines'
assert ATEXT.count('{') == ATEXT.count('}'), 'audit braces unbalanced'
assert ATEXT.count('(') == ATEXT.count(')'), 'audit parens unbalanced'
assert AUDIT[-1] == '    }', 'audit block does not close'
assert HDR[-1] == '}  // namespace rules', 'header does not close'
assert ATEXT.count('R274 misc magic prose part 18 pins audit: bad %d' + BS + 'n') == 1, 'audit printf label not unique'
GJOINED = ' '.join(GAP)
assert 'rows 9-18' in GJOINED.replace(chr(10), ' '), 'gap rows frag split'
for frag in ('seam restored', 'part 18', 'III.E.4', 'p.150-151',
             'Prayer Beads', '11970', 'line 905', 'rows 19+',
             'census 192', '67 accessors: 59'):
    assert frag in GJOINED.replace(chr(10), ' '), 'gap frag missing: ' + frag

# ---- patch 1: create rules/miscprose18.h ----
p = 'rules/miscprose18.h'
if os.path.exists(os.path.join(ROOT, p)):
    assert rd(p) == HTEXT, 'miscprose18.h exists but differs'
    already += 1
else:
    wr(p, HTEXT)
    applied += 1
assert rd(p) == HTEXT, 'patch 1 failed'

# ---- patch 2: the regtest include ----
p = 'regtest.cpp'
s = rd(p)
inc = '#include "rules/miscprose18.h"  // R274: the III.E misc magic explanation prose part 18 pins'
if inc in s:
    already += 1
else:
    anchor = '#include "rules/miscprose17.h"  // R273: the III.E misc magic explanation prose part 17 pins'
    assert s.count(anchor) == 1, 'include anchor not unique'
    s = s.replace(anchor, anchor + NL + inc, 1)
    wr(p, s)
    applied += 1
assert inc in rd(p), 'patch 2 failed'
assert rd(p).count('#include "rules/miscprose18.h"') == 1, 'patch 2 doubled'

# ---- patch 3: the regtest audit block ----
p = 'regtest.cpp'
s = rd(p)
mark = '    // ---- R274: the III.E misc magic explanation'
if mark in s:
    already += 1
else:
    anchor = '    // ---- R227: the wis mental save wiring audit ----'
    assert s.count(anchor) == 1, 'audit anchor not unique'
    s = s.replace(anchor, ATEXT + NL + anchor, 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 3 failed'
assert rd(p).count(mark) == 1, 'patch 3 doubled'

# ---- patch 4: the gap report entry ----
p = 'tools/dmg_gap_report.md'
s = rd(p)
mark = 'R274 landed the III.E misc'
if mark in s:
    already += 1
else:
    anchor = 'continue).' + NL + NL + 'Categories:'
    assert s.count(anchor) == 1, 'gap anchor not unique'
    s = s.replace(anchor, 'continue).' + NL + NL + NL.join(GAP) + NL + NL + 'Categories:', 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 4 failed'
assert rd(p).count(mark) == 1, 'patch 4 doubled'

print('R274 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R274 note: 4 patches; the III.E misc magic')
print('explanation prose part 18 - the Manual of')
print('Stealthy Pilfering through the Necklace of')
print('Missiles, part2 lines 843-900; census 192.')
print('commit: R274: the III.E misc magic explanation prose part 18 pinned - the Manual of Stealthy Pilfering through the Necklace of Missiles in part2 lines 843-900 (census 192)')

