#!/usr/bin/env python3
# R275 splice: the III.E misc magic explanation prose
# part 19 pins - the Necklace of Prayer Beads, the
# Necklace of Strangulation, the Nets of Entrapment
# and Snaring, Nolzurs Marvelous Pigments, the Pearls
# of Power and Wisdom and the Periapts of Foul
# Rotting, Health, Proof Against Poison and Wound
# Closure, part2 lines 905-969 (DMG p.152-153),
# pinning the kMisc4 rows 19-29 of the 36-row III.E.4
# table. ONE mid-sentence break inside the slice: the
# pearl of power paragraph splits between a pearl of
# power (933) and enables the possessor (935), the
# upload prints no running head at the break - ONE
# seam restored this round; the slice rides the
# pp.152-153 attribution on the R274-established
# p.152 base (the TREASURE running head at 903). The
# upload quirks this round: the bead table rows are
# split across multiple table lines (the karma and
# summons beads span three each); the part1 pigments
# row misplaces the apostrophe after the s; the net of
# entrapment prints the one-quarter character (mesh)
# and an en-dash (AC -10) - pinned as plain digits,
# apostrophe-free here. 4 patches, marker-based
# idempotence, assert after every patch. ZERO
# apostrophes and ZERO literal backslashes in the
# content below (the printf newline is built via
# BS = chr(92)).

import os
import re
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose19.h',
    '// R275: the III.E misc magic explanation prose part 19',
    '// (DMG p.152-153) - the Necklace of Prayer Beads, the',
    '// Necklace of Strangulation, the Nets of Entrapment and',
    '// Snaring, Nolzurs Marvelous Pigments, the Pearls of',
    '// Power and Wisdom and the Periapts of Foul Rotting,',
    '// Health, Proof Against Poison and Wound Closure,',
    '// part2 lines 905-969 (global = 11065 + part2 line),',
    '// pinning the kMisc4 rows 19-29 of the 36-row III.E.4',
    '// table. ONE mid-sentence break inside the slice: the',
    '// pearl of power paragraph splits between a pearl of',
    '// power (933) and enables the possessor (935), the',
    '// upload prints no running head at the break - ONE',
    '// seam restored this round; the slice rides the',
    '// pp.152-153 attribution on the R274-established p.152',
    '// base (the TREASURE running head at 903). The upload',
    '// quirks this round: the bead table rows are split',
    '// across multiple table lines (the karma and summons',
    '// beads span three each); the part1 pigments row',
    '// misplaces the apostrophe after the s; the net of',
    '// entrapment prints the one-quarter character (mesh)',
    '// and an en-dash (AC -10) - pinned as plain digits,',
    '// apostrophe-free here. 49 accessors: 41 scalars + 8',
    '// walkers (the bead die bands; the pearl die bands',
    '// and spell levels; the periapt plus ladder), no name',
    '// collisions with miscprose1.h through miscprose18.h.',
    '// Pure data + helpers, header-only (the grenade.h',
    '// pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpBeadStoneMin() {',
    '    // the necklace consists of 25-30 stones',
    '    return 25;',
    '}',
    '',
    'inline int mmpBeadStoneMax() {',
    '    // the upper edge of the 25-30 stones',
    '    return 30;',
    '}',
    '',
    'inline int mmpBeadSemiPreciousPct() {',
    '    // 60 percent semi-precious stones',
    '    return 60;',
    '}',
    '',
    'inline int mmpBeadFancyPct() {',
    '    // 40 percent fancy stones',
    '    return 40;',
    '}',
    '',
    'inline int mmpBeadPetitionBonusPct() {',
    '    // 25 percent more likely to petition the deity',
    '    return 25;',
    '}',
    '',
    'inline int mmpBeadSpecialMin() {',
    '    // 3-6 special beads',
    '    return 3;',
    '}',
    '',
    'inline int mmpBeadSpecialMax() {',
    '    // the upper edge of the 3-6 special beads',
    '    return 6;',
    '}',
    '',
    'inline int mmpBeadGemBaseGp() {',
    '    // precious stones of 1,000 gp base value',
    '    return 1000;',
    '}',
    '',
    'inline int mmpBeadUsesPerDay() {',
    '    // each special bead once per day',
    '    return 1;',
    '}',
    '',
    'inline int mmpBeadKarmaLevels() {',
    '    // the karma bead casts 4 levels higher',
    '    return 4;',
    '}',
    '',
    'inline int mmpBeadSummonsPct() {',
    '    // the summons bead calls the deity at 90 percent',
    '    return 90;',
    '}',
    '',
    'inline int mmpBeadRowLo(int i) {',
    '    // the printed die band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        1, 6, 11, 16, 18, 19,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpBeadRowHi(int i) {',
    '    // the printed die band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 5) i = 5;',
    '    static const int t[6] = {',
    '        5, 10, 15, 17, 18, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpStrangleDamagePerRound() {',
    '    // 6 hit points of strangulation damage per round',
    '    return 6;',
    '}',
    '',
    'inline int mmpEntrapMinStrength() {',
    '    // defies strength under 20',
    '    return 20;',
    '}',
    '',
    'inline int mmpEntrapCutAc() {',
    '    // equal to AC -10 against cutting blows',
    '    return -10;',
    '}',
    '',
    'inline int mmpEntrapSizeFeet() {',
    '    // each net is 10 feet square',
    '    return 10;',
    '}',
    '',
    'inline int mmpEntrapMeshQuarterFeet() {',
    '    // with a quarter-foot mesh',
    '    return 1;',
    '}',
    '',
    'inline int mmpEntrapThrowFeet() {',
    '    // it can be thrown 20 feet',
    '    return 20;',
    '}',
    '',
    'inline int mmpEntrapCloseCubeFeet() {',
    '    // stretches to close over a 5 foot cube',
    '    return 5;',
    '}',
    '',
    'inline int mmpSnareRangeInches() {',
    '    // shoots forth up to 3 inches underwater',
    '    return 3;',
    '}',
    '',
    'inline int mmpPigPotCubicFeet() {',
    '    // one pot creates a 1,000 cubic foot object',
    '    return 1000;',
    '}',
    '',
    'inline int mmpPigDepictSquareFeet() {',
    '    // depicted over a 100 square foot surface',
    '    return 100;',
    '}',
    '',
    'inline int mmpPigContainersMin() {',
    '    // from 1-4 containers found',
    '    return 1;',
    '}',
    '',
    'inline int mmpPigContainersMax() {',
    '    // the upper edge of the 1-4 containers',
    '    return 4;',
    '}',
    '',
    'inline int mmpPigInstrumentFeet() {',
    '    // a single instrument about 1 foot long',
    '    return 1;',
    '}',
    '',
    'inline int mmpPigDepictTurns() {',
    '    // 1 turn to depict an object',
    '    return 1;',
    '}',
    '',
    'inline int mmpPowerRecallPerDay() {',
    '    // once a day the pearl recalls',
    '    return 1;',
    '}',
    '',
    'inline int mmpPowerSpellsRecalled() {',
    '    // recalls any 1 spell as desired',
    '    return 1;',
    '}',
    '',
    'inline int mmpPowerReverseOneIn() {',
    '    // 1 in 20 of opposite effect',
    '    return 20;',
    '}',
    '',
    'inline int mmpPowerDoubleMin() {',
    '    // the 00 row recalls 2 spells',
    '    return 2;',
    '}',
    '',
    'inline int mmpPowerDoubleMaxLevel() {',
    '    // of 1st to 6th level',
    '    return 6;',
    '}',
    '',
    'inline int mmpPowerDoubleDieSides() {',
    '    // the level picked by d6',
    '    return 6;',
    '}',
    '',
    'inline int mmpPowerRowLo(int i) {',
    '    // the printed die band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 9) i = 9;',
    '    static const int t[10] = {',
    '        1, 26, 46, 61, 76, 86, 93, 97, 99, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpPowerRowHi(int i) {',
    '    // the printed die band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 9) i = 9;',
    '    static const int t[10] = {',
    '        25, 45, 60, 75, 85, 92, 96, 98, 99, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpPowerSpellLevel(int i) {',
    '    // the spell level per die band, the 00 row',
    '    // marked 0 for the double-spell special; clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 9) i = 9;',
    '    static const int t[10] = {',
    '        1, 2, 3, 4, 5, 6, 7, 8, 9, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpWisdomGain() {',
    '    // the cleric gains 1 point of wisdom',
    '    return 1;',
    '}',
    '',
    'inline int mmpWisdomMonths() {',
    '    // retained for a 1 month period',
    '    return 1;',
    '}',
    '',
    'inline int mmpWisdomDays() {',
    '    // the gain at the expiration of 30 days',
    '    return 30;',
    '}',
    '',
    'inline int mmpWisdomReverseOneIn() {',
    '    // 1 in 20 cursed to work in reverse',
    '    return 20;',
    '}',
    '',
    'inline int mmpRotAbilityLossPerWeek() {',
    '    // 1 point per ability per week',
    '    return 1;',
    '}',
    '',
    'inline int mmpRotStartWeek() {',
    '    // beginning 1 week after claiming',
    '    return 1;',
    '}',
    '',
    'inline int mmpRotAbilityCount() {',
    '    // dexterity, constitution and charisma',
    '    return 3;',
    '}',
    '',
    'inline int mmpRotDeathScore() {',
    '    // dead when any score reaches 0',
    '    return 0;',
    '}',
    '',
    'inline int mmpPoisonSavePctPerPlus() {',
    '    // a 10 percent saving throw per plus',
    '    return 10;',
    '}',
    '',
    'inline int mmpPoisonRowLo(int i) {',
    '    // the printed die band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 9, 15, 19,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpPoisonRowHi(int i) {',
    '    // the printed die band upper edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        8, 14, 18, 20,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpPoisonPlus(int i) {',
    '    // the plus of periapt per die band; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 3) i = 3;',
    '    static const int t[4] = {',
    '        1, 2, 3, 4,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpWoundHealRateMult() {',
    '    // doubles the normal rate of healing',
    '    return 2;',
    '}',
    '',
    '}  // namespace rules',
]

AUDIT = [
    '    // ---- R275: the III.E misc magic explanation',
    '    // prose part 19 ----',
    '    // The Necklace of Prayer Beads, the Necklace of',
    '    // Strangulation, the Nets of Entrapment and',
    '    // Snaring, Nolzurs Marvelous Pigments, the Pearls',
    '    // of Power and Wisdom and the Periapts of Foul',
    '    // Rotting, Health, Proof Against Poison and Wound',
    '    // Closure, part2 lines 905-969 - the slice pinning',
    '    // the kMisc4 rows 19-29 of the 36-row III.E.4',
    '    // table.',
    '    {',
    '        int bad = 0;',
    '        // the necklace of prayer beads scalars',
    '        if (rules::mmpBeadStoneMin() != 25 ||',
    '            rules::mmpBeadStoneMax() != 30 ||',
    '            rules::mmpBeadSemiPreciousPct() != 60 ||',
    '            rules::mmpBeadFancyPct() != 40 ||',
    '            rules::mmpBeadPetitionBonusPct() != 25 ||',
    '            rules::mmpBeadSpecialMin() != 3 ||',
    '            rules::mmpBeadSpecialMax() != 6 ||',
    '            rules::mmpBeadGemBaseGp() != 1000 ||',
    '            rules::mmpBeadUsesPerDay() != 1 ||',
    '            rules::mmpBeadKarmaLevels() != 4 ||',
    '            rules::mmpBeadSummonsPct() != 90) ++bad;',
    '        // the stone split sums to the full necklace',
    '        if (rules::mmpBeadSemiPreciousPct() +',
    '            rules::mmpBeadFancyPct() != 100) ++bad;',
    '        // the bead type table against static twins',
    '        static const int kBlo[6] = {',
    '            1, 6, 11, 16, 18, 19,',
    '        };',
    '        static const int kBhi[6] = {',
    '            5, 10, 15, 17, 18, 20,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::mmpBeadRowLo(i) != kBlo[i] ||',
    '                rules::mmpBeadRowHi(i) != kBhi[i]) ++bad;',
    '        // the bead die bands tile 1-20 without gaps',
    '        for (int i = 0; i < 5; ++i)',
    '            if (rules::mmpBeadRowLo(i + 1) !=',
    '                rules::mmpBeadRowHi(i) + 1) ++bad;',
    '        if (rules::mmpBeadRowLo(0) != 1 ||',
    '            rules::mmpBeadRowHi(5) != 20) ++bad;',
    '        // the necklace of strangulation',
    '        if (rules::mmpStrangleDamagePerRound() != 6) ++bad;',
    '        // the net of entrapment',
    '        if (rules::mmpEntrapMinStrength() != 20 ||',
    '            rules::mmpEntrapSizeFeet() != 10 ||',
    '            rules::mmpEntrapMeshQuarterFeet() != 1 ||',
    '            rules::mmpEntrapThrowFeet() != 20 ||',
    '            rules::mmpEntrapCloseCubeFeet() != 5) ++bad;',
    '        // AC -10 against cutting blows',
    '        if (rules::mmpEntrapCutAc() + 10 != 0) ++bad;',
    '        // the net of snaring',
    '        if (rules::mmpSnareRangeInches() != 3) ++bad;',
    '        // the marvelous pigments',
    '        if (rules::mmpPigPotCubicFeet() != 1000 ||',
    '            rules::mmpPigDepictSquareFeet() != 100 ||',
    '            rules::mmpPigContainersMin() != 1 ||',
    '            rules::mmpPigContainersMax() != 4 ||',
    '            rules::mmpPigInstrumentFeet() != 1 ||',
    '            rules::mmpPigDepictTurns() != 1) ++bad;',
    '        // the pearl of power scalars',
    '        if (rules::mmpPowerRecallPerDay() != 1 ||',
    '            rules::mmpPowerSpellsRecalled() != 1 ||',
    '            rules::mmpPowerReverseOneIn() != 20 ||',
    '            rules::mmpPowerDoubleMin() != 2 ||',
    '            rules::mmpPowerDoubleMaxLevel() != 6 ||',
    '            rules::mmpPowerDoubleDieSides() != 6) ++bad;',
    '        // the 00 row d6 equals the 1st to 6th ladder',
    '        if (rules::mmpPowerDoubleDieSides() !=',
    '            rules::mmpPowerDoubleMaxLevel()) ++bad;',
    '        // the pearl power table against static twins',
    '        static const int kPlo[10] = {',
    '            1, 26, 46, 61, 76, 86, 93, 97, 99, 100,',
    '        };',
    '        static const int kPhi[10] = {',
    '            25, 45, 60, 75, 85, 92, 96, 98, 99, 100,',
    '        };',
    '        static const int kLvl[10] = {',
    '            1, 2, 3, 4, 5, 6, 7, 8, 9, 0,',
    '        };',
    '        for (int i = 0; i < 10; ++i)',
    '            if (rules::mmpPowerRowLo(i) != kPlo[i] ||',
    '                rules::mmpPowerRowHi(i) != kPhi[i] ||',
    '                rules::mmpPowerSpellLevel(i) !=',
    '                kLvl[i]) ++bad;',
    '        // the pearl die bands tile 1-100 without gaps',
    '        for (int i = 0; i < 9; ++i)',
    '            if (rules::mmpPowerRowLo(i + 1) !=',
    '                rules::mmpPowerRowHi(i) + 1) ++bad;',
    '        if (rules::mmpPowerRowLo(0) != 1 ||',
    '            rules::mmpPowerRowHi(9) != 100) ++bad;',
    '        // the spell levels ascend first to ninth',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::mmpPowerSpellLevel(i + 1) !=',
    '                rules::mmpPowerSpellLevel(i) + 1) ++bad;',
    '        // the 00 row carries the double-spell mark',
    '        if (rules::mmpPowerSpellLevel(9) != 0) ++bad;',
    '        // the pearl of wisdom',
    '        if (rules::mmpWisdomGain() != 1 ||',
    '            rules::mmpWisdomMonths() != 1 ||',
    '            rules::mmpWisdomDays() != 30 ||',
    '            rules::mmpWisdomReverseOneIn() != 20) ++bad;',
    '        // the month expires at the printed 30 days',
    '        if (rules::mmpWisdomMonths() * 30 !=',
    '            rules::mmpWisdomDays()) ++bad;',
    '        // the periapt of foul rotting',
    '        if (rules::mmpRotAbilityLossPerWeek() != 1 ||',
    '            rules::mmpRotStartWeek() != 1 ||',
    '            rules::mmpRotAbilityCount() != 3 ||',
    '            rules::mmpRotDeathScore() != 0) ++bad;',
    '        // the periapt of proof against poison',
    '        if (rules::mmpPoisonSavePctPerPlus() != 10) ++bad;',
    '        static const int kOlo[4] = {',
    '            1, 9, 15, 19,',
    '        };',
    '        static const int kOhi[4] = {',
    '            8, 14, 18, 20,',
    '        };',
    '        static const int kOpl[4] = {',
    '            1, 2, 3, 4,',
    '        };',
    '        for (int i = 0; i < 4; ++i)',
    '            if (rules::mmpPoisonRowLo(i) != kOlo[i] ||',
    '                rules::mmpPoisonRowHi(i) != kOhi[i] ||',
    '                rules::mmpPoisonPlus(i) != kOpl[i]) ++bad;',
    '        // the periapt bands tile 1-20 without gaps',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpPoisonRowLo(i + 1) !=',
    '                rules::mmpPoisonRowHi(i) + 1) ++bad;',
    '        if (rules::mmpPoisonRowLo(0) != 1 ||',
    '            rules::mmpPoisonRowHi(3) != 20) ++bad;',
    '        // the periapt of wound closure',
    '        if (rules::mmpWoundHealRateMult() != 2) ++bad;',
    '        // the engine kMisc4 rows 19-29: the die band',
    '        // edges, the double star on the beads, the',
    '        // triple on the pigments, the quadruple on the',
    '        // pearl of power, the (C), (F), (T) and (M)',
    '        // marks, no dual rows',
    '        static const int kRlo[11] = {',
    '            28, 34, 36, 39, 43, 45, 47, 49, 51, 54, 61,',
    '        };',
    '        static const int kRhi[11] = {',
    '            33, 35, 38, 42, 44, 46, 48, 50, 53, 60, 64,',
    '        };',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::m4RowLo(19 + i) != kRlo[i] ||',
    '                rules::m4RowHi(19 + i) != kRhi[i]) ++bad;',
    '        if (rules::m4StarCount(19) != 2 ||',
    '            rules::m4StarCount(23) != 3 ||',
    '            rules::m4StarCount(24) != 4 ||',
    '            rules::m4RowCount() != 36) ++bad;',
    '        for (int i = 19; i < 30; ++i)',
    '            if (i != 19 && i != 23 && i != 24 &&',
    '                rules::m4StarCount(i) != 0) ++bad;',
    '        for (int i = 19; i < 30; ++i)',
    '            if (rules::m4IsDualValued(i) != 0) ++bad;',
    '        if (rules::m4UsableByCleric(19) != 1 ||',
    '            rules::m4UsableByCleric(21) != 1 ||',
    '            rules::m4UsableByCleric(22) != 1 ||',
    '            rules::m4UsableByCleric(25) != 1 ||',
    '            rules::m4UsableByFighter(21) != 1 ||',
    '            rules::m4UsableByFighter(22) != 1 ||',
    '            rules::m4UsableByThief(21) != 1 ||',
    '            rules::m4UsableByThief(22) != 1 ||',
    '            rules::m4UsableByMagicUser(24) != 1) ++bad;',
    '        for (int i = 19; i < 30; ++i)',
    '            if (i != 19 && i != 21 && i != 22 &&',
    '                i != 25 &&',
    '                rules::m4UsableByCleric(i) != 0) ++bad;',
    '        for (int i = 19; i < 30; ++i)',
    '            if (i != 21 && i != 22 &&',
    '                rules::m4UsableByFighter(i) != 0) ++bad;',
    '        for (int i = 19; i < 30; ++i)',
    '            if (i != 24 &&',
    '                rules::m4UsableByMagicUser(i) != 0) ++bad;',
    '        for (int i = 19; i < 30; ++i)',
    '            if (i != 21 && i != 22 &&',
    '                rules::m4UsableByThief(i) != 0) ++bad;',
    '        // the engine footnote helpers',
    '        if (rules::m4BeadPerSpecialXp() != 500 ||',
    '            rules::m4BeadPerSpecialGp() != 3000 ||',
    '            rules::m4PigmentsPerPotXp() != 500 ||',
    '            rules::m4PigmentsPerPotGp() != 3000 ||',
    '            rules::m4PearlPerSpellLevelXp() != 200 ||',
    '            rules::m4PearlPerSpellLevelGp() != 2000 ||',
    '            rules::m4ClericCount() != 8 ||',
    '            rules::m4FighterCount() != 4 ||',
    '            rules::m4MagicUserCount() != 6 ||',
    '            rules::m4ThiefCount() != 3) ++bad;',
    '        printf("R275 misc magic prose part 19 pins audit: bad %d' + BS + 'n", bad);',
    '        if (bad) return 1;',
    '    }',
]

GAP = [
    'R275 landed the III.E misc',
    'magic explanation prose',
    'part 19 (part2 lines 905-969;',
    'global = 11065 + part2',
    'line), the Necklace of Prayer',
    'Beads, the Necklace of',
    'Strangulation, the Nets of',
    'Entrapment and Snaring,',
    'Nolzurs Marvelous Pigments,',
    'the Pearls of Power and',
    'Wisdom and the Periapts of',
    'Foul Rotting, Health, Proof',
    'Against Poison and Wound',
    'Closure (DMG p.152-153) -',
    'the slice pinning the kMisc4',
    'rows 19-29 of the 36-row',
    'III.E.4 table. ONE',
    'mid-sentence break: the',
    'pearl of power paragraph',
    'splits between a pearl of',
    'power (933) and enables the',
    'possessor (935), the upload',
    'prints no running head at',
    'the break - ONE',
    'seam restored this round;',
    'the slice rides the',
    'pp.152-153 attribution on',
    'the R274-established p.152',
    'base (the TREASURE running',
    'head at 903). The upload',
    'quirks: the bead table rows',
    'are split across multiple',
    'table lines (the karma and',
    'summons beads span three',
    'each); the part1 pigments',
    'row misplaces the',
    'apostrophe after the s; the',
    'net of entrapment prints',
    'the one-quarter character',
    '(mesh) and an en-dash (AC',
    '-10) - pinned as plain',
    'digits, apostrophe-free in',
    'the header. The items:',
    'Necklace of Prayer Beads',
    '(cleric only, 25-30 stones',
    'at 60 percent semi-precious',
    'and 40 fancy, 25 percent',
    'petition bonus, 3-6 special',
    'beads of 1,000 gp gems,',
    'each once per day: 1-5',
    'atonement as the 5th level',
    'spell, 6-10 blessing as the',
    '1st, 11-15 curing, 16-17',
    'karma casting 4 levels',
    'higher, 18 summons calling',
    'the deity at 90 percent,',
    '19-20 wind walking as the',
    '7th; known only via a',
    'commune, lost if removed),',
    'Necklace of Strangulation',
    '(constricts on wearing, 6',
    'damage per round until',
    'dead, removed only by',
    'alter reality, limited wish',
    'or wish, stays until a dry',
    'skeleton), Net of',
    'Entrapment (defies strength',
    'under 20, AC -10 to cut,',
    'sawing fails, hacking',
    'severs, 10 foot square with',
    'quarter-foot mesh, thrown',
    '20 feet, save versus magic',
    'or entrapped, drops or',
    'closes on command, up to a',
    '5 foot cube, loosened on',
    'command), Net of Snaring',
    '(entrapment look-alike,',
    'underwater only, shoots 3',
    'inches), Marvelous Pigments',
    '(one pot creates a 1,000',
    'cubic foot object depicted',
    'over a 100 square foot',
    'surface, only normal',
    'inanimate things, 1-4',
    'containers with a 1 foot',
    'instrument, 1 turn to',
    'depict, false valuables',
    'are tin lead paste brass',
    'bone), Pearl of Power',
    '(magic-user aid, once a',
    'day recalls any 1 memorized',
    'spell; table 01-25 first,',
    '26-45 second, 46-60 third,',
    '61-75 fourth, 76-85 fifth,',
    '86-92 sixth, 93-96 seventh,',
    '97-98 eighth, 99 ninth, 00',
    'recalls 2 spells of 1st to',
    '6th by d6; 1 in 20 reversed',
    'causes forgetting, removed',
    'only by exorcism or a',
    'wish), Pearl of Wisdom',
    '(cleric +1 wisdom at the',
    '30-day month expiration,',
    'kept or lost; 1 in 20',
    'reversed, loss permanent',
    'barring a wish or Tome of',
    'Understanding), Periapt of',
    'Foul Rotting (rotting',
    'leprosy on claim, removed',
    'by remove curse, cure',
    'disease then heal or wish,',
    'countered by crushed',
    'health periapt dust; else 1',
    'point each of dexterity',
    'constitution and charisma',
    'per week from week 1, dead',
    'at 0, losses permanent),',
    'Periapt of Health (immune',
    'to all diseases save the',
    'foul rotting), Periapt of',
    'Proof Against Poison (10',
    'percent save per plus where',
    'none allowed, normal score',
    'at penalty, plus on other',
    'saves; table 1-8 plus one,',
    '9-14 plus two, 15-18 plus',
    'three, 19-20 plus four),',
    'Periapt of Wound Closure',
    '(no open bleeding wounds,',
    'doubles healing, heals',
    'the non-healing).',
    '49 accessors: 41 scalars',
    '+ 8 walkers (the bead, pearl',
    'and periapt die bands, the',
    'pearl spell levels and the',
    'periapt plus ladder), no',
    'name collisions parts',
    '1-18. New R275 battery',
    'audit; census 193. Next:',
    'R276 III.E part 20 - the',
    'Phylactery of Faithfulness',
    'onward in part2 from',
    'line 971 (global 12036; the',
    'long years and monstrous',
    'attention phylacteries, the',
    'pipes, the portable hole',
    'and the feather token',
    'follow; kMisc4 rows 30+',
    'continue).',
]

# ---- the splice self-asserts ----
HTEXT = NL.join(HDR)
defs = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(]', HTEXT)
assert len(defs) == 49, 'accessor count is not 49'
assert len(set(defs)) == 49, 'accessor names not unique'
scal = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(][)]', HTEXT)
walk = [d for d in defs if d not in scal]
assert len(scal) == 41, 'scalar count is not 41'
assert len(walk) == 8, 'walker count is not 8'
assert set(walk) == {'mmpBeadRowLo', 'mmpBeadRowHi',
                    'mmpPowerRowLo', 'mmpPowerRowHi',
                    'mmpPowerSpellLevel', 'mmpPoisonRowLo',
                    'mmpPoisonRowHi', 'mmpPoisonPlus'}, 'wrong walkers'
ATEXT = NL.join(AUDIT)
audited = set(re.findall(r'rules::(mmp[A-Za-z0-9]+)[(]', ATEXT))
assert audited == set(defs), 'audit does not probe every accessor'
for p in range(1, 19):
    pp = os.path.join(ROOT, 'rules/miscprose%d.h' % p)
    if os.path.exists(pp):
        pt = open(pp, encoding='utf-8').read()
        for n in defs:
            assert n not in pt, 'name collision with part %d' % p
for grp in (HDR, AUDIT, GAP):
    for el in grp:
        if isinstance(el, str):
            assert chr(39) not in el, 'apostrophe in content'
            probe = el.replace(chr(92) + 'n', '')
            assert chr(92) not in probe, 'backslash in content'
            assert NL not in el, 'list element spans lines'
assert ATEXT.count('{') == ATEXT.count('}'), 'audit braces unbalanced'
assert ATEXT.count('(') == ATEXT.count(')'), 'audit parens unbalanced'
assert AUDIT[-1] == '    }', 'audit block does not close'
assert HDR[-1] == '}  // namespace rules', 'header does not close'
assert ATEXT.count('R275 misc magic prose part 19 pins audit: bad %d' + BS + 'n') == 1, 'audit printf label not unique'
GJOIN = ' '.join(GAP)
for frag in ('rows 19-29', 'seam restored', 'part 19', 'III.E.4',
             'p.152-153', 'Faithfulness', '12036', 'line 971',
             'rows 30+', 'census 193', '49 accessors: 41'):
    assert frag in GJOIN, 'gap frag missing: ' + frag

# ---- patch 1: create rules/miscprose19.h ----
p = 'rules/miscprose19.h'
if os.path.exists(os.path.join(ROOT, p)):
    assert rd(p) == HTEXT, 'miscprose19.h exists but differs'
    already += 1
else:
    wr(p, HTEXT)
    applied += 1
assert rd(p) == HTEXT, 'patch 1 failed'

# ---- patch 2: the regtest include ----
p = 'regtest.cpp'
s = rd(p)
inc = '#include "rules/miscprose19.h"  // R275: the III.E misc magic explanation prose part 19 pins'
if inc in s:
    already += 1
else:
    anchor = '#include "rules/miscprose18.h"  // R274: the III.E misc magic explanation prose part 18 pins'
    assert s.count(anchor) == 1, 'include anchor not unique'
    s = s.replace(anchor, anchor + NL + inc, 1)
    wr(p, s)
    applied += 1
assert inc in rd(p), 'patch 2 failed'
assert rd(p).count('#include "rules/miscprose19.h"') == 1, 'patch 2 doubled'

# ---- patch 3: the regtest audit block ----
p = 'regtest.cpp'
s = rd(p)
mark = '    // ---- R275: the III.E misc magic explanation'
if mark in s:
    already += 1
else:
    anchor = '    // ---- R227: the wis mental save wiring audit ----'
    assert s.count(anchor) == 1, 'audit anchor not unique'
    s = s.replace(anchor, ATEXT + NL + anchor, 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 3 failed'
assert rd(p).count(mark) == 1, 'patch 3 doubled'

# ---- patch 4: the gap report entry ----
p = 'tools/dmg_gap_report.md'
s = rd(p)
mark = 'R275 landed the III.E misc'
if mark in s:
    already += 1
else:
    anchor = 'continue).' + NL + NL + 'Categories:'
    assert s.count(anchor) == 1, 'gap anchor not unique'
    s = s.replace(anchor, 'continue).' + NL + NL + NL.join(GAP) + NL + NL + 'Categories:', 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 4 failed'
assert rd(p).count(mark) == 1, 'patch 4 doubled'

print('R275 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R275 note: 4 patches; the III.E misc magic')
print('explanation prose part 19 - the Necklace of')
print('Prayer Beads through the Periapt of Wound')
print('Closure, part2 lines 905-969; census 193.')
print('commit: R275: the III.E misc magic explanation prose part 19 pinned - the Necklace of Prayer Beads through the Periapt of Wound Closure in part2 lines 905-969 (census 193)')

