#!/usr/bin/env python3
# R277 splice: the III.E misc magic explanation prose
# part 21 pins - the Robe of the Archmagi, the Robe of
# Blending, the Robe of Eyes, the Robe of Powerlessness,
# the Robe of Scintillating Colors and the Robe of
# Useful Items, part2 lines 1002-1052 (DMG p.153-154),
# pinning the kMisc5 rows 0-5 of the 35-row III.E.5
# table - the slice that opens the table. This round
# has one seam: the Powerlessness paragraph splits
# between the 1018 tail (and becomes) and the 1021
# head (weak as well), with the 1019-1020 pair of
# blanks - the p.153-154 page break with no running
# head - seam restored here. The upload quirks this
# round: the OCR splits two words with a space (magic-
# user and language/ noise); the curly apostrophes
# print in the robe and wearer possessives; curly
# quotes wrap see, eyes and flowing; the foot and
# inch primes print as curly marks; the 20%/minus 4
# reduction prints the true minus sign; the coffer and
# window rows carry one-half and multiplication signs;
# the door and window rows separate with em-dashes -
# all pinned as plain digits and words, apostrophe-free
# here. The part1 quirks: the six robe rows print
# side-by-side with armor-table columns (part1
# 9875-9880); the Powerlessness row prints --- in the
# x.p. column; the Scintillating row misplaces 2,750
# after the (C, M) marks. The useful items table
# flattens its two header rows (Dice and Roll Result
# each on an own line) and prints 13 die bands, pinned
# as the twin walkers. 67 accessors: 65 scalars + 2
# walkers, no name collisions with miscprose1.h
# through miscprose20.h. Pure data + helpers,
# header-only (the grenade.h pattern). 4 patches,
# marker-based idempotence, assert after every patch.
# ZERO apostrophes and ZERO literal backslashes in the
# content below (the printf newline is built via
# BS = chr(92)).

import os
import re
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose21.h',
    '// R277: the III.E misc magic explanation prose part 21',
    '// (DMG p.153-154) - the Robe of the Archmagi, the Robe',
    '// of Blending, the Robe of Eyes, the Robe of Powerlessness,',
    '// the Robe of Scintillating Colors and the Robe of Useful',
    '// Items, part2 lines 1002-1052 (global = 11065 + part2',
    '// line), pinning the kMisc5 rows 0-5 of the 35-row III.E.5',
    '// table - the slice that opens the table. This round has',
    '// one seam: the Powerlessness paragraph splits between the',
    '// 1018 tail (and becomes) and the 1021 head (weak as well),',
    '// with the 1019-1020 pair of blanks - the p.153-154 page',
    '// break with no running head - seam restored here. The',
    '// upload quirks this round: the OCR splits two words with',
    '// a space (magic- user and language/ noise); the curly',
    '// apostrophes print in the robe and wearer possessives;',
    '// curly quotes wrap see, eyes and flowing; the foot and',
    '// inch primes print as curly marks; the 20%/minus 4',
    '// reduction prints the true minus sign; the coffer and',
    '// window rows carry one-half and multiplication signs;',
    '// the door and window rows separate with em-dashes - all',
    '// pinned as plain digits and words, apostrophe-free here.',
    '// The part1 quirks: the six robe rows print side-by-side',
    '// with armor-table columns (part1 9875-9880); the',
    '// Powerlessness row prints --- in the x.p. column; the',
    '// Scintillating row misplaces 2,750 after the (C, M)',
    '// marks. The useful items table flattens its two header',
    '// rows (Dice and Roll Result each on an own line) and',
    '// prints 13 die bands, pinned as the twin walkers.',
    '// 67 accessors: 65 scalars + 2 walkers (the useful item',
    '// die bands), no name collisions with miscprose1.h',
    '// through miscprose20.h. Pure data + helpers, header-only',
    '// (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpArchmagiWhitePct() {',
    '    // white: 45 percent (good alignment)',
    '    return 45;',
    '}',
    '',
    'inline int mmpArchmagiGrayPct() {',
    '    // gray: 30 percent (neutral alignment)',
    '    return 30;',
    '}',
    '',
    'inline int mmpArchmagiBlackPct() {',
    '    // black: 25 percent (evil alignment)',
    '    return 25;',
    '}',
    '',
    'inline int mmpArchmagiAcClass() {',
    '    // power 1: serves as armor equal to AC 5',
    '    return 5;',
    '}',
    '',
    'inline int mmpArchmagiMagicResistPct() {',
    '    // power 2: confers a 5 percent magic resistance',
    '    return 5;',
    '}',
    '',
    'inline int mmpArchmagiSaveBonus() {',
    '    // power 3: adds +1 to saving throw scores',
    '    return 1;',
    '}',
    '',
    'inline int mmpArchmagiPenaltyPct() {',
    '    // power 4: worn spells cut foe magic',
    '    // resistance and saves by 20 percent',
    '    return 20;',
    '}',
    '',
    'inline int mmpArchmagiPenaltyMinus() {',
    '    // the saving throw half of the 20 percent cut',
    '    return 4;',
    '}',
    '',
    'inline int mmpArchmagiCharmFamilyCount() {',
    '    // the seven spells of the power 4 list',
    '    return 7;',
    '}',
    '',
    'inline int mmpArchmagiClashDmgMin() {',
    '    // white on evil: take 18-51 hit points',
    '    return 18;',
    '}',
    '',
    'inline int mmpArchmagiClashDmgMax() {',
    '    // the clash damage ceiling',
    '    return 51;',
    '}',
    '',
    'inline int mmpArchmagiClashDiceCount() {',
    '    // the clash dice are 11d4',
    '    return 11;',
    '}',
    '',
    'inline int mmpArchmagiClashDiceBonus() {',
    '    // the clash dice bonus is +7',
    '    return 7;',
    '}',
    '',
    'inline int mmpArchmagiClashXpMin() {',
    '    // and lose 18,000-51,000 experience points',
    '    return 18000;',
    '}',
    '',
    'inline int mmpArchmagiClashXpMax() {',
    '    // the clash experience loss ceiling',
    '    return 51000;',
    '}',
    '',
    'inline int mmpArchmagiGrayDmgMin() {',
    '    // the gray or crossed clash: 6-24 hit points',
    '    return 6;',
    '}',
    '',
    'inline int mmpArchmagiGrayDmgMax() {',
    '    // the gray clash damage ceiling',
    '    return 24;',
    '}',
    '',
    'inline int mmpArchmagiGrayXpMin() {',
    '    // 6,000-24,000 experience points loss',
    '    return 6000;',
    '}',
    '',
    'inline int mmpArchmagiGrayXpMax() {',
    '    // the gray experience loss ceiling',
    '    return 24000;',
    '}',
    '',
    'inline int mmpBlendDetectRangeInches() {',
    '    // within 3 inches something amiss is detectable',
    '    return 3;',
    '}',
    '',
    'inline int mmpBlendDetectPerIntPct() {',
    '    // 1 percent per intelligence point chance',
    '    return 1;',
    '}',
    '',
    'inline int mmpBlendDetectIntMin() {',
    '    // exceptional (15+) or better intelligence',
    '    return 15;',
    '}',
    '',
    'inline int mmpBlendLevelDetectIntMin() {',
    '    // low intelligence (5+) or better and',
    '    return 5;',
    '}',
    '',
    'inline int mmpBlendLevelDetectLevelMin() {',
    '    // 10 or more levels of experience or hit dice',
    '    return 10;',
    '}',
    '',
    'inline int mmpBlendDetectPerLevelPct() {',
    '    // 1 percent per level or hit die chance',
    '    return 1;',
    '}',
    '',
    'inline int mmpBlendExamplePct() {',
    '    // the 18 int / 12th level example: 30 percent',
    '    return 30;',
    '}',
    '',
    'inline int mmpEyesInfravisionInches() {',
    '    // infravisual capability to 12 inch range',
    '    return 12;',
    '}',
    '',
    'inline int mmpEyesSeeInvisibleInches() {',
    '    // invisible things within a 24 inch',
    '    // normal vision range',
    '    return 24;',
    '}',
    '',
    'inline int mmpEyesSeeInfraredInches() {',
    '    // or 12 inches if infravision is used',
    '    return 12;',
    '}',
    '',
    'inline int mmpEyesTrackRangerLevel() {',
    '    // tracks as if a 12th level ranger',
    '    return 12;',
    '}',
    '',
    'inline int mmpEyesBlindLightMin() {',
    '    // a light spell blinds it for 1-3 rounds',
    '    return 1;',
    '}',
    '',
    'inline int mmpEyesBlindLightMax() {',
    '    // the light blindness ceiling',
    '    return 3;',
    '}',
    '',
    'inline int mmpEyesBlindContinualMin() {',
    '    // a continual light for 2-8 rounds',
    '    return 2;',
    '}',
    '',
    'inline int mmpEyesBlindContinualMax() {',
    '    // the continual light blindness ceiling',
    '    return 8;',
    '}',
    '',
    'inline int mmpPowerlessIntelligence() {',
    '    // the wearer drops to 3 intelligence',
    '    return 3;',
    '}',
    '',
    'inline int mmpPowerlessStrength() {',
    '    // and becomes weak as well (3 strength)',
    '    return 3;',
    '}',
    '',
    'inline int mmpScintIntMin() {',
    '    // needs intelligence of 15 or higher',
    '    return 15;',
    '}',
    '',
    'inline int mmpScintWisMin() {',
    '    // and a wisdom of 13 or more',
    '    return 13;',
    '}',
    '',
    'inline int mmpScintLightFeet() {',
    '    // sheds light in a 40 foot diameter sphere',
    '    return 40;',
    '}',
    '',
    'inline int mmpScintStartRounds() {',
    '    // a full round to cause the colors to flow',
    '    return 1;',
    '}',
    '',
    'inline int mmpScintTransfixMin() {',
    '    // stand transfixed for 2-5 rounds',
    '    return 2;',
    '}',
    '',
    'inline int mmpScintTransfixMax() {',
    '    // the transfix ceiling',
    '    return 5;',
    '}',
    '',
    'inline int mmpScintHitPctPerRound() {',
    '    // 5 percent harder to hit per round of play',
    '    return 5;',
    '}',
    '',
    'inline int mmpScintHitPctMax() {',
    '    // to a maximum of 25 percent (minus 5)',
    '    return 25;',
    '}',
    '',
    'inline int mmpScintHitMaxRounds() {',
    '    // attained after 5 continuous rounds',
    '    return 5;',
    '}',
    '',
    'inline int mmpScintCastRangeInches() {',
    '    // activity within 1 inch of the start point',
    '    return 1;',
    '}',
    '',
    'inline int mmpScintHypnotizeMin() {',
    '    // non-combat hypnosis for 2-5 turns',
    '    return 2;',
    '}',
    '',
    'inline int mmpScintHypnotizeMax() {',
    '    // the non-combat hypnosis ceiling',
    '    return 5;',
    '}',
    '',
    'inline int mmpUsefulDetachRounds() {',
    '    // detach any 1 of the patches in 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpUsefulBaseEach() {',
    '    // always 2 each of the base patches',
    '    return 2;',
    '}',
    '',
    'inline int mmpUsefulBaseCount() {',
    '    // the six base patch kinds (3 table rows)',
    '    return 6;',
    '}',
    '',
    'inline int mmpUsefulExtraMin() {',
    '    // 4-16 extra items which must be diced for',
    '    return 4;',
    '}',
    '',
    'inline int mmpUsefulExtraMax() {',
    '    // the extra item ceiling',
    '    return 16;',
    '}',
    '',
    'inline int mmpUsefulGpBag() {',
    '    // bag of 100 gold pieces',
    '    return 100;',
    '}',
    '',
    'inline int mmpUsefulCofferGp() {',
    '    // the silver coffer: 500 g.p. value',
    '    return 500;',
    '}',
    '',
    'inline int mmpUsefulGemsCount() {',
    '    // gems, 10 of',
    '    return 10;',
    '}',
    '',
    'inline int mmpUsefulGemValueGp() {',
    '    // 100 gold piece value each',
    '    return 100;',
    '}',
    '',
    'inline int mmpUsefulLadderFeet() {',
    '    // wooden ladder, 24 feet long',
    '    return 24;',
    '}',
    '',
    'inline int mmpUsefulPitCubicFeet() {',
    '    // pit, 10 cubic feet, open',
    '    return 10;',
    '}',
    '',
    'inline int mmpUsefulRowboatFeet() {',
    '    // rowboat, 12 feet long',
    '    return 12;',
    '}',
    '',
    'inline int mmpUsefulWindowWidthFeet() {',
    '    // window, 2 feet wide',
    '    return 2;',
    '}',
    '',
    'inline int mmpUsefulWindowHeightFeet() {',
    '    // 4 feet high',
    '    return 4;',
    '}',
    '',
    'inline int mmpUsefulWindowDepthFeet() {',
    '    // up to 2 feet deep',
    '    return 2;',
    '}',
    '',
    'inline int mmpUsefulScrollSpells() {',
    '    // scroll of 1 spell',
    '    return 1;',
    '}',
    '',
    'inline int mmpUsefulWarDogsPair() {',
    '    // war dogs, pair',
    '    return 2;',
    '}',
    '',
    'inline int mmpUsefulRowLo(int i) {',
    '    // the printed extra item band lower edges',
    '    if (i < 0) i = 0;',
    '    if (i > 12) i = 12;',
    '    static const int t[13] = {',
    '        1, 9, 16, 23, 31, 45, 52,',
    '        60, 69, 76, 84, 91, 97,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpUsefulRowHi(int i) {',
    '    // the printed extra item band upper edges',
    '    if (i < 0) i = 0;',
    '    if (i > 12) i = 12;',
    '    static const int t[13] = {',
    '        8, 15, 22, 30, 44, 51, 59,',
    '        68, 75, 83, 90, 96, 100,',
    '    };',
    '    return t[i];',
    '}',
    '',
    '}  // namespace rules',
]

AUDIT = [
    '    // ---- R277: the III.E misc magic explanation',
    '    // prose part 21 ----',
    '    // The Robe of the Archmagi, the Robe of Blending,',
    '    // the Robe of Eyes, the Robe of Powerlessness, the',
    '    // Robe of Scintillating Colors and the Robe of',
    '    // Useful Items, part2 lines 1002-1052 - the slice',
    '    // pinning the kMisc5 rows 0-5 of the 35-row III.E.5',
    '    // table (and opening it).',
    '    {',
    '        int bad = 0;',
    '        // the robe of the archmagi scalars',
    '        if (rules::mmpArchmagiWhitePct() != 45 ||',
    '            rules::mmpArchmagiGrayPct() != 30 ||',
    '            rules::mmpArchmagiBlackPct() != 25 ||',
    '            rules::mmpArchmagiAcClass() != 5 ||',
    '            rules::mmpArchmagiMagicResistPct() != 5 ||',
    '            rules::mmpArchmagiSaveBonus() != 1 ||',
    '            rules::mmpArchmagiPenaltyPct() != 20 ||',
    '            rules::mmpArchmagiPenaltyMinus() != 4 ||',
    '            rules::mmpArchmagiCharmFamilyCount() != 7) ++bad;',
    '        // the archmagi clash scalars',
    '        if (rules::mmpArchmagiClashDmgMin() != 18 ||',
    '            rules::mmpArchmagiClashDmgMax() != 51 ||',
    '            rules::mmpArchmagiClashDiceCount() != 11 ||',
    '            rules::mmpArchmagiClashDiceBonus() != 7 ||',
    '            rules::mmpArchmagiClashXpMin() != 18000 ||',
    '            rules::mmpArchmagiClashXpMax() != 51000 ||',
    '            rules::mmpArchmagiGrayDmgMin() != 6 ||',
    '            rules::mmpArchmagiGrayDmgMax() != 24 ||',
    '            rules::mmpArchmagiGrayXpMin() != 6000 ||',
    '            rules::mmpArchmagiGrayXpMax() != 24000) ++bad;',
    '        // the color split sums to 100 percent',
    '        if (rules::mmpArchmagiWhitePct() +',
    '            rules::mmpArchmagiGrayPct() +',
    '            rules::mmpArchmagiBlackPct() != 100) ++bad;',
    '        // the clash dice reproduce the printed damage',
    '        if (rules::mmpArchmagiClashDiceCount() +',
    '            rules::mmpArchmagiClashDiceBonus() !=',
    '            rules::mmpArchmagiClashDmgMin() ||',
    '            4 * rules::mmpArchmagiClashDiceCount() +',
    '            rules::mmpArchmagiClashDiceBonus() !=',
    '            rules::mmpArchmagiClashDmgMax()) ++bad;',
    '        // the robe of blending scalars',
    '        if (rules::mmpBlendDetectRangeInches() != 3 ||',
    '            rules::mmpBlendDetectPerIntPct() != 1 ||',
    '            rules::mmpBlendDetectIntMin() != 15 ||',
    '            rules::mmpBlendLevelDetectIntMin() != 5 ||',
    '            rules::mmpBlendLevelDetectLevelMin() != 10 ||',
    '            rules::mmpBlendDetectPerLevelPct() != 1 ||',
    '            rules::mmpBlendExamplePct() != 30) ++bad;',
    '        // the example is the two chances summed',
    '        if (18 * rules::mmpBlendDetectPerIntPct() +',
    '            12 * rules::mmpBlendDetectPerLevelPct() !=',
    '            rules::mmpBlendExamplePct()) ++bad;',
    '        // the robe of eyes scalars',
    '        if (rules::mmpEyesInfravisionInches() != 12 ||',
    '            rules::mmpEyesSeeInvisibleInches() != 24 ||',
    '            rules::mmpEyesSeeInfraredInches() != 12 ||',
    '            rules::mmpEyesTrackRangerLevel() != 12 ||',
    '            rules::mmpEyesBlindLightMin() != 1 ||',
    '            rules::mmpEyesBlindLightMax() != 3 ||',
    '            rules::mmpEyesBlindContinualMin() != 2 ||',
    '            rules::mmpEyesBlindContinualMax() != 8) ++bad;',
    '        // the robe of powerlessness scalars',
    '        if (rules::mmpPowerlessIntelligence() != 3 ||',
    '            rules::mmpPowerlessStrength() != 3) ++bad;',
    '        // the robe of scintillating colors scalars',
    '        if (rules::mmpScintIntMin() != 15 ||',
    '            rules::mmpScintWisMin() != 13 ||',
    '            rules::mmpScintLightFeet() != 40 ||',
    '            rules::mmpScintStartRounds() != 1 ||',
    '            rules::mmpScintTransfixMin() != 2 ||',
    '            rules::mmpScintTransfixMax() != 5 ||',
    '            rules::mmpScintHitPctPerRound() != 5 ||',
    '            rules::mmpScintHitPctMax() != 25 ||',
    '            rules::mmpScintHitMaxRounds() != 5 ||',
    '            rules::mmpScintCastRangeInches() != 1 ||',
    '            rules::mmpScintHypnotizeMin() != 2 ||',
    '            rules::mmpScintHypnotizeMax() != 5) ++bad;',
    '        // the hit ladder reaches the max at the max rounds',
    '        if (rules::mmpScintHitPctPerRound() *',
    '            rules::mmpScintHitMaxRounds() !=',
    '            rules::mmpScintHitPctMax()) ++bad;',
    '        // the robe of useful items scalars',
    '        if (rules::mmpUsefulDetachRounds() != 1 ||',
    '            rules::mmpUsefulBaseEach() != 2 ||',
    '            rules::mmpUsefulBaseCount() != 6 ||',
    '            rules::mmpUsefulExtraMin() != 4 ||',
    '            rules::mmpUsefulExtraMax() != 16 ||',
    '            rules::mmpUsefulGpBag() != 100 ||',
    '            rules::mmpUsefulCofferGp() != 500 ||',
    '            rules::mmpUsefulGemsCount() != 10 ||',
    '            rules::mmpUsefulGemValueGp() != 100 ||',
    '            rules::mmpUsefulLadderFeet() != 24 ||',
    '            rules::mmpUsefulPitCubicFeet() != 10 ||',
    '            rules::mmpUsefulRowboatFeet() != 12 ||',
    '            rules::mmpUsefulWindowWidthFeet() != 2 ||',
    '            rules::mmpUsefulWindowHeightFeet() != 4 ||',
    '            rules::mmpUsefulWindowDepthFeet() != 2 ||',
    '            rules::mmpUsefulScrollSpells() != 1 ||',
    '            rules::mmpUsefulWarDogsPair() != 2) ++bad;',
    '        // the extra items dice table against static twins',
    '        static const int kUlo[13] = {',
    '            1, 9, 16, 23, 31, 45, 52,',
    '            60, 69, 76, 84, 91, 97,',
    '        };',
    '        static const int kUhi[13] = {',
    '            8, 15, 22, 30, 44, 51, 59,',
    '            68, 75, 83, 90, 96, 100,',
    '        };',
    '        for (int i = 0; i < 13; ++i)',
    '            if (rules::mmpUsefulRowLo(i) != kUlo[i] ||',
    '                rules::mmpUsefulRowHi(i) != kUhi[i]) ++bad;',
    '        // the bands run 01 through 00 with no gaps',
    '        if (rules::mmpUsefulRowLo(0) != 1 ||',
    '            rules::mmpUsefulRowHi(12) != 100) ++bad;',
    '        for (int i = 0; i < 12; ++i)',
    '            if (rules::mmpUsefulRowLo(i + 1) !=',
    '                rules::mmpUsefulRowHi(i) + 1) ++bad;',
    '        for (int i = 0; i < 13; ++i)',
    '            if (rules::mmpUsefulRowLo(i) >',
    '                rules::mmpUsefulRowHi(i)) ++bad;',
    '        // the kMisc5 table opening cross-check',
    '        static const int kRlo[6] = {',
    '            1, 2, 9, 10, 11, 12,',
    '        };',
    '        static const int kRhi[6] = {',
    '            1, 8, 9, 10, 11, 19,',
    '        };',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::m5RowLo(i) != kRlo[i] ||',
    '                rules::m5RowHi(i) != kRhi[i]) ++bad;',
    '        // the marks: only the scintillating robe is (C)',
    '        for (int i = 0; i < 6; ++i)',
    '            if (i != 4 &&',
    '                rules::m5UsableByCleric(i) != 0) ++bad;',
    '        // no fighter or thief marks on the robes',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::m5UsableByFighter(i) != 0) ++bad;',
    '        for (int i = 0; i < 6; ++i)',
    '            if (rules::m5UsableByThief(i) != 0) ++bad;',
    '        // the magic-user marks: all robes but the blending',
    '        for (int i = 0; i < 6; ++i)',
    '            if (i != 1 &&',
    '                rules::m5UsableByMagicUser(i) != 1) ++bad;',
    '        // the whole-table counts and row census',
    '        if (rules::m5ClericCount() != 5 ||',
    '            rules::m5FighterCount() != 5 ||',
    '            rules::m5MagicUserCount() != 8 ||',
    '            rules::m5ThiefCount() != 2 ||',
    '            rules::m5RowCount() != 35) ++bad;',
    '        printf("R277 misc magic prose part 21 pins audit: bad %d' + BS + 'n", bad);',
    '    }',
]

GAP = [
    'R277 landed the III.E misc',
    'magic explanation prose',
    'part 21 (part2 lines 1002-1052;',
    'global = 11065 + part2 line),',
    'the Robe of the Archmagi, the',
    'Robe of Blending, the Robe of',
    'Eyes, the Robe of Powerlessness,',
    'the Robe of Scintillating Colors',
    'and the Robe of Useful Items (DMG',
    'p.153-154) - the slice pinning',
    'the kMisc5 rows 0-5 of the 35-row',
    'III.E.5 table, opening it. This',
    'round has one seam: the',
    'Powerlessness paragraph splits',
    'between the 1018 tail (and',
    'becomes) and the 1021 head (weak',
    'as well), with the 1019-1020',
    'pair of blanks - the p.153-154',
    'page break with no running head -',
    'seam restored here. The upload',
    'quirks: the OCR splits two words',
    'with a space (magic- user and',
    'language/ noise); curly',
    'apostrophes print in the robe and',
    'wearer possessives; curly quotes',
    'wrap see, eyes and flowing; the',
    'foot and inch primes print as',
    'curly marks; the 20%/minus 4',
    'reduction prints the true minus',
    'sign; the coffer and window rows',
    'carry one-half and multiplication',
    'signs; the door and window rows',
    'separate with em-dashes - all',
    'pinned as plain digits and words.',
    'The part1 quirks: the six robe',
    'rows print side-by-side with',
    'armor-table columns (part1',
    '9875-9880); the Powerlessness row',
    'prints --- in the x.p. column;',
    'the Scintillating row misplaces',
    '2,750 after the (C, M) marks. The',
    'useful items table flattens its',
    'two header rows (Dice and Roll',
    'Result each on an own line) and',
    'prints 13 die bands, pinned as',
    'the twin walkers. The items: Robe',
    'of the Archmagi (white 45 percent',
    'good, gray 30 percent neutral,',
    'black 25 percent evil; AC 5',
    'armor, 5 percent magic',
    'resistance, +1 saves; worn spells',
    'cut foe magic resistance and',
    'saves by 20 percent and minus 4',
    'across seven charm-family spells;',
    'wrong-aligned donning: 18-51',
    '(11d4 + 7) hit points and',
    '18,000-51,000 experience lost;',
    'the gray or crossed clash: 6-24',
    'hit points and 6,000-24,000',
    'experience), Robe of Blending',
    '(cannot be detected by magical',
    'means; appears part of a rock',
    'wall, a plant, a creature,',
    'whatever is appropriate; never',
    'more than twice one-half normal',
    'height; exceptional (15+)',
    'intelligence: 1 percent per point',
    'within 3 inches; low (5+)',
    'intelligence with 10+ levels or',
    'hit dice: 1 percent per level or',
    'hit die; cumulative - the 18 int',
    '12th level example is 30 percent;',
    'checks each turn thereafter',
    'within the 3 inch range), Robe of',
    'Eyes (sees in all directions at',
    'once; infravision to 12 inches;',
    'ultravision; displaced or out of',
    'phase things in actual positions;',
    'invisible things within 24 inches',
    '(or 12); solid objects obstruct;',
    'astral or ethereal things unseen;',
    'illusions and secret doors unseen',
    'but hidden creatures detected -',
    'ambush or surprise impossible;',
    'tracks as a 12th level ranger; a',
    'light spell blinds 1-3 rounds, a',
    'continual light 2-8), Robe of',
    'Powerlessness (appears as another',
    'robe, only a magic aura detected;',
    'donning drops the wearer to 3',
    'intelligence and 3 strength;',
    'removed easily but restoring mind',
    'and body needs a remove curse and',
    'then a heal spell), Robe of',
    'Scintillating Colors (needs',
    'intelligence 15+ and wisdom 13+;',
    'sheds light in a 40 foot diameter',
    'sphere; a full round to start; a',
    'failed save versus magic stands',
    'opponents transfixed 2-5 rounds;',
    'each round of scintillation makes',
    'the wearer 5 percent harder to',
    'hit up to 25 percent (minus 5) at',
    '5 continuous rounds; then spell',
    'casting and activity within 1',
    'inch of the start point;',
    'non-combat hypnosis for 2-5',
    'turns), Robe of Useful Items (the',
    'wearer alone sees the patches;',
    'detach any 1 in 1 round; always 2',
    'each of the six base patches -',
    'dagger, pole (10 foot), lantern',
    '(filled and lit), rope (50 foot',
    'coil), mirror (large), sack',
    '(large); plus 4-16 diced items',
    'across 13 bands: 01-08 bag of 100',
    'gold pieces, 09-15 silver coffer',
    '(500 g.p. value), 16-22 iron',
    'door, 23-30 ten gems of 100 gold',
    'piece value each, 31-44 wooden',
    'ladder 24 feet long, 45-51 mule',
    'with saddle bags, 52-59 open pit',
    'of 10 cubic feet, 60-68 potion of',
    'extra healing, 69-75 rowboat 12',
    'feet long, 76-83 scroll of 1',
    'spell, 84-90 pair of war dogs,',
    '91-96 window (2 foot by 4 foot,',
    'up to 2 foot deep), 97-00 roll',
    'twice more; removed items never',
    'replaced). 67 accessors: 65',
    'scalars + 2 walkers (the useful',
    'item die bands), no name',
    'collisions parts 1-20. New R277',
    'battery audit; census 195. Next:',
    'R278 III.E part 22 - the Rope of',
    'Climbing onward in part2 from',
    'line 1054 (global 12119; the three',
    'ropes, the rope note, the two',
    'rugs, the saw, the four scarabs',
    'and the spade follow; the kMisc5',
    'rows 7+',
    'continue).',
]

# ---- the splice self-asserts ----
HTEXT = NL.join(HDR)
defs = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(]', HTEXT)
assert len(defs) == 67, 'accessor count is not 67'
assert len(set(defs)) == 67, 'accessor names not unique'
scal = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(][)]', HTEXT)
walk = [d for d in defs if d not in scal]
assert len(scal) == 65, 'scalar count is not 65'
assert len(walk) == 2, 'walker count is not 2'
assert set(walk) == {'mmpUsefulRowLo', 'mmpUsefulRowHi'}, 'wrong walkers'
ATEXT = NL.join(AUDIT)
audited = set(re.findall(r'rules::(mmp[A-Za-z0-9]+)[(]', ATEXT))
assert audited == set(defs), 'audit does not probe every accessor'
for p in range(1, 21):
    pp = os.path.join(ROOT, 'rules/miscprose%d.h' % p)
    if os.path.exists(pp):
        pt = open(pp, encoding='utf-8').read()
        for n in defs:
            assert n not in pt, 'name collision with part %d' % p
for grp in (HDR, AUDIT, GAP):
    for el in grp:
        if isinstance(el, str):
            assert chr(39) not in el, 'apostrophe in content'
            probe = el.replace(chr(92) + 'n', '')
            assert chr(92) not in probe, 'backslash in content'
            assert NL not in el, 'list element spans lines'
assert ATEXT.count('{') == ATEXT.count('}'), 'audit braces unbalanced'
assert ATEXT.count('(') == ATEXT.count(')'), 'audit parens unbalanced'
assert AUDIT[-1] == '    }', 'audit block does not close'
assert HDR[-1] == '}  // namespace rules', 'header does not close'
assert ATEXT.count('R277 misc magic prose part 21 pins audit: bad %d' + BS + 'n') == 1, 'audit printf label not unique'
GJOIN = ' '.join(GAP)
for frag in ('part 21', 'rows 0-5', 'seam restored', 'III.E.5',
             'p.153-154', '67 accessors: 65', 'Climbing',
             '12119', 'line 1054', 'rows 7+', 'census 195'):
    assert any(frag in el for el in GAP), 'gap frag not contiguous: ' + frag
    assert frag in GJOIN, 'gap frag missing: ' + frag
hfrags = ('part 21', 'rows 0-5', 'seam restored', 'III.E.5',
          'p.153-154', '67 accessors: 65')
for frag in hfrags:
    assert any(frag in el for el in HDR), 'header frag not contiguous: ' + frag

# ---- patch 1: create rules/miscprose21.h ----
p = 'rules/miscprose21.h'
if os.path.exists(os.path.join(ROOT, p)):
    assert rd(p) == HTEXT, 'miscprose21.h exists but differs'
    already += 1
else:
    wr(p, HTEXT)
    applied += 1
assert rd(p) == HTEXT, 'patch 1 failed'

# ---- patch 2: the regtest include ----
p = 'regtest.cpp'
s = rd(p)
inc = '#include "rules/miscprose21.h"  // R277: the III.E misc magic explanation prose part 21 pins'
if inc in s:
    already += 1
else:
    anchor = '#include "rules/miscprose20.h"  // R276: the III.E misc magic explanation prose part 20 pins'
    assert s.count(anchor) == 1, 'include anchor not unique'
    s = s.replace(anchor, anchor + NL + inc, 1)
    wr(p, s)
    applied += 1
assert inc in rd(p), 'patch 2 failed'
assert rd(p).count('#include "rules/miscprose21.h"') == 1, 'patch 2 doubled'

# ---- patch 3: the regtest audit block ----
p = 'regtest.cpp'
s = rd(p)
mark = '    // ---- R277: the III.E misc magic explanation'
if mark in s:
    already += 1
else:
    anchor = '    // ---- R227: the wis mental save wiring audit ----'
    assert s.count(anchor) == 1, 'audit anchor not unique'
    s = s.replace(anchor, ATEXT + NL + anchor, 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 3 failed'
assert rd(p).count(mark) == 1, 'patch 3 doubled'

# ---- patch 4: the gap report entry ----
p = 'tools/dmg_gap_report.md'
s = rd(p)
mark = 'R277 landed the III.E misc'
if mark in s:
    already += 1
else:
    anchor = 'continue).' + NL + NL + 'Categories:'
    assert s.count(anchor) == 1, 'gap anchor not unique'
    s = s.replace(anchor, 'continue).' + NL + NL + NL.join(GAP) + NL + NL + 'Categories:', 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 4 failed'
assert rd(p).count(mark) == 1, 'patch 4 doubled'

print('R277 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R277 note: 4 patches; the III.E misc magic')
print('explanation prose part 21 - the Robe of the')
print('Archmagi through the Robe of Useful Items,')
print('part2 lines 1002-1052; census 195.')
print('commit: R277: the III.E misc magic explanation prose part 21 pinned - the Robe of the Archmagi through the Robe of Useful Items in part2 lines 1002-1052 (census 195)')

