#!/usr/bin/env python3
# R278 splice: the III.E misc magic explanation prose
# part 22 pins - the Rope of Climbing, the Rope of
# Constriction, the Rope of Entanglement, the rope
# note, the Rug of Smothering, the Rug of Welcome,
# the Saw of Mighty Cutting, the Scarab of Death, the
# Scarab of Enraging Enemies, the Scarab of
# Insanity, the Scarab of Protection and the Spade
# of Colossal Excavation, part2 lines 1054-1081
# (DMG p.154-156), pinning the kMisc5 rows 6-16 of
# the 35-row III.E.5 table - the eleven consecutive
# rows opening with the Rope of Climbing. This
# round has two seams restored: seam A splits the
# Constriction paragraph between the 1056 tail
# (delivers 2-12 hit) and the 1058 head (points of
# damage) across the single 1057 blank - the
# p.154-155 page break, no running head captured;
# seam B is the p.155-156 page break between the
# Insanity tail (1074) and the Protection head
# (1079) with the blank pair at 1075-1076, the
# TREASURE (MISCELLANEOUS MAGIC) running head at
# 1077 and the 1078 post-head blank. The upload
# quirks this round: the OCR splits spade- like
# with a space; the curly apostrophe prints in the
# victim possessive of the Scarab of Death; curly
# quotes wrap to hit in the enraging mods; the
# minus signs print true (minus 2, minus 3, minus
# 10 percent, minus 2 saves); the foot and inch
# primes print as curly marks; the welcome rug
# carries a multiplication sign on its 6 x 9
# flying size and the 1/12 shrink fraction; the
# rope note prints as a heading line - all pinned
# as plain digits and words, apostrophe-free here.
# The part1 quirks: the eleven slice rows print
# side-by-side with armor-table columns (part1
# 9881-9891); the Constriction, Smothering and
# Death rows print --- in the x.p. column; the
# Welcome, Saw and Spade rows carry the (M)/(F)
# marks. The Entanglement man-sized equivalence
# chain (1 storm giant = 2 giants = 3 ogres = 4
# bugbears = 6 gnolls = 8 men = 10 elves = 12
# dwarves = 16 gnomes or kobolds) is pinned as
# the lone walker. 85 accessors: 84 scalars + 1
# walker, no name collisions with miscprose1.h
# through miscprose21.h. Pure data + helpers,
# header-only (the grenade.h pattern). 4 patches,
# marker-based idempotence, assert after every
# patch. ZERO apostrophes and ZERO literal
# backslashes in the content below (the printf
# newline is built via BS = chr(92)).

import os
import re
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose22.h',
    '// R278: the III.E misc magic explanation prose part 22',
    '// (DMG p.154-156) - the Rope of Climbing, the Rope of',
    '// Constriction, the Rope of Entanglement, the rope note,',
    '// the Rug of Smothering, the Rug of Welcome, the Saw of',
    '// Mighty Cutting, the Scarab of Death, the Scarab of',
    '// Enraging Enemies, the Scarab of Insanity, the Scarab of',
    '// Protection and the Spade of Colossal Excavation, part2',
    '// lines 1054-1081 (global = 11065 + part2 line), pinning',
    '// the kMisc5 rows 6-16 of the 35-row III.E.5 table - the',
    '// eleven consecutive rows opening with the Rope of',
    '// Climbing. This round has two seams restored: seam A',
    '// splits the Constriction paragraph between the 1056 tail',
    '// (delivers 2-12 hit) and the 1058 head (points of damage)',
    '// across the single 1057 blank - the p.154-155 page break,',
    '// no running head captured; seam B is the p.155-156 page',
    '// break between the Insanity tail (1074) and the Protection',
    '// head (1079) with the blank pair at 1075-1076, the',
    '// TREASURE (MISCELLANEOUS MAGIC) running head at 1077 and',
    '// the 1078 post-head blank. The upload quirks this round:',
    '// the OCR splits spade- like with a space; the curly',
    '// apostrophe prints in the victim possessive of the Scarab',
    '// of Death; curly quotes wrap to hit in the enraging mods;',
    '// the minus signs print true (minus 2, minus 3, minus 10',
    '// percent, minus 2 saves); the foot and inch primes print',
    '// as curly marks; the welcome rug carries a multiplication',
    '// sign on its 6 x 9 flying size and the 1/12 shrink',
    '// fraction; the rope note prints as a heading line - all',
    '// pinned as plain digits and words, apostrophe-free here.',
    '// The part1 quirks: the eleven slice rows print',
    '// side-by-side with armor-table columns (part1 9881-9891);',
    '// the Constriction, Smothering and Death rows print --- in',
    '// the x.p. column; the Welcome, Saw and Spade rows carry',
    '// the (M)/(F) marks. The Entanglement man-sized',
    '// equivalence chain is pinned as the lone walker.',
    '// 85 accessors: 84 scalars + 1 walker, no name collisions',
    '// with miscprose1.h through miscprose21.h. Pure data +',
    '// helpers, header-only (the grenade.h pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpClimbLengthFeet() {',
    '    // a 60 foot long rope of climbing',
    '    return 60;',
    '}',
    '',
    'inline int mmpClimbWeightPounds() {',
    '    // weighs no more than 3 pounds',
    '    return 3;',
    '}',
    '',
    'inline int mmpClimbSupportPounds() {',
    '    // strong enough to support 3,000 pounds',
    '    return 3000;',
    '}',
    '',
    'inline int mmpClimbSpeedFeetPerRound() {',
    '    // moves at 10 feet per round upon command',
    '    return 10;',
    '}',
    '',
    'inline int mmpClimbKnotIntervalFeet() {',
    '    // large knots appear at 1 foot intervals',
    '    return 1;',
    '}',
    '',
    'inline int mmpClimbKnottedLengthFeet() {',
    '    // knotting shortens the rope to 50 feet',
    '    return 50;',
    '}',
    '',
    'inline int mmpConstrictExtraVictimsMin() {',
    '    // lashes at 1-4 others near the holder',
    '    return 1;',
    '}',
    '',
    'inline int mmpConstrictExtraVictimsMax() {',
    '    // the extra victim ceiling',
    '    return 4;',
    '}',
    '',
    'inline int mmpConstrictVictimRangeFeet() {',
    '    // the others within 10 feet of the victim',
    '    return 10;',
    '}',
    '',
    'inline int mmpConstrictDmgMin() {',
    '    // each round delivers 2-12 hit points',
    '    return 2;',
    '}',
    '',
    'inline int mmpConstrictDmgMax() {',
    '    // the constriction damage ceiling',
    '    return 12;',
    '}',
    '',
    'inline int mmpConstrictAcClass() {',
    '    // the rope itself is AC -2',
    '    return -2;',
    '}',
    '',
    'inline int mmpConstrictCutHitPoints() {',
    '    // takes 22 hit points to cut through',
    '    return 22;',
    '}',
    '',
    'inline int mmpEntangleLashFeet() {',
    '    // lashes forward 20 feet upon command',
    '    return 20;',
    '}',
    '',
    'inline int mmpEntangleUpwardFeet() {',
    '    // or upwards 10 feet',
    '    return 10;',
    '}',
    '',
    'inline int mmpEntangleManSizedMax() {',
    '    // ties fast up to 8 man-sized creatures',
    '    return 8;',
    '}',
    '',
    'inline int mmpEntangleStrikeSegments() {',
    '    // a single segment to strike',
    '    return 1;',
    '}',
    '',
    'inline int mmpEntangleEntwineSegments() {',
    '    // another segment to entwine',
    '    return 1;',
    '}',
    '',
    'inline int mmpEntangleCommandSegments() {',
    '    // the command requires 1 segment',
    '    return 1;',
    '}',
    '',
    'inline int mmpEntangleWholeSegments() {',
    '    // the whole takes 3 segments to perform',
    '    return 3;',
    '}',
    '',
    'inline int mmpEntangleAcClass() {',
    '    // the rope is AC -2',
    '    return -2;',
    '}',
    '',
    'inline int mmpEntangleCutHitPoints() {',
    '    // takes 22 hit points to cut through',
    '    return 22;',
    '}',
    '',
    'inline int mmpEntangleRepairTurns() {',
    '    // damage under 22 repairs itself in 6 turns',
    '    return 6;',
    '}',
    '',
    'inline int mmpSmotherRoundsMin() {',
    '    // suffocates its victim in 3-6 rounds',
    '    return 3;',
    '}',
    '',
    'inline int mmpSmotherRoundsMax() {',
    '    // the suffocation ceiling',
    '    return 6;',
    '}',
    '',
    'inline int mmpSmotherBlockingSpells() {',
    '    // four spells prevent the smothering: alter',
    '    // reality, animate object, hold plant, wish',
    '    return 4;',
    '}',
    '',
    'inline int mmpWelcomeFlyWidthFeet() {',
    '    // functions as a carpet of flying (6 x 9',
    '    return 6;',
    '}',
    '',
    'inline int mmpWelcomeFlyLengthFeet() {',
    '    // size)',
    '    return 9;',
    '}',
    '',
    'inline int mmpWelcomeBridgeFeet() {',
    '    // stiffens as steel up to 27 feet long',
    '    return 27;',
    '}',
    '',
    'inline int mmpWelcomeBridgeWidthFeet() {',
    '    // at a 2 foot width',
    '    return 2;',
    '}',
    '',
    'inline int mmpWelcomeAcClass() {',
    '    // the bridge form is AC 0',
    '    return 0;',
    '}',
    '',
    'inline int mmpWelcomeDestroyHitPoints() {',
    '    // takes 100 hit points to destroy',
    '    return 100;',
    '}',
    '',
    'inline int mmpWelcomeShrinkDivisor() {',
    '    // shrinks to 1/12 size on command',
    '    return 12;',
    '}',
    '',
    'inline int mmpSawLengthFeet() {',
    '    // the notched adamantite blade is 12 feet',
    '    return 12;',
    '}',
    '',
    'inline int mmpSawWidthFeet() {',
    '    // long and over 1 foot wide',
    '    return 1;',
    '}',
    '',
    'inline int mmpSawSoloStrength() {',
    '    // requires 18/00 or greater strength alone',
    '    return 18;',
    '}',
    '',
    'inline int mmpSawTandemStrength() {',
    '    // or 2 persons of 17 or greater strength',
    '    return 17;',
    '}',
    '',
    'inline int mmpSawTandemPersons() {',
    '    // working in tandem',
    '    return 2;',
    '}',
    '',
    'inline int mmpSawHardwoodFeet() {',
    '    // a 2 foot thick hardwood tree',
    '    return 2;',
    '}',
    '',
    'inline int mmpSawHardwoodTurns() {',
    '    // sliced through in 1 turn',
    '    return 1;',
    '}',
    '',
    'inline int mmpSawTrunkFeet() {',
    '    // a 4 foot thick trunk',
    '    return 4;',
    '}',
    '',
    'inline int mmpSawTrunkTurns() {',
    '    // sliced through in 3 turns',
    '    return 3;',
    '}',
    '',
    'inline int mmpSawSmallDiameterFeet() {',
    '    // a 1 foot diameter tree',
    '    return 1;',
    '}',
    '',
    'inline int mmpSawSmallRounds() {',
    '    // sliced through in but 3 rounds',
    '    return 3;',
    '}',
    '',
    'inline int mmpSawWorkTurns() {',
    '    // after 6 turns of cutting',
    '    return 6;',
    '}',
    '',
    'inline int mmpSawRestTurns() {',
    '    // the users must rest for 6 turns',
    '    return 6;',
    '}',
    '',
    'inline int mmpDeathHoldRounds() {',
    '    // changes if held for more than 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpDeathContainerFeet() {',
    '    // or placed within 1 foot of a warm',
    '    return 1;',
    '}',
    '',
    'inline int mmpDeathContainerTurns() {',
    '    // living body for 1 turn',
    '    return 1;',
    '}',
    '',
    'inline int mmpDeathHeartRounds() {',
    '    // reaches the victim heart in a single round',
    '    return 1;',
    '}',
    '',
    'inline int mmpEnrageRadiusInches() {',
    '    // enrages hostiles within a 4 inch radius',
    '    return 4;',
    '}',
    '',
    'inline int mmpEnrageToHitBonus() {',
    '    // the enraged gain +1 to hit',
    '    return 1;',
    '}',
    '',
    'inline int mmpEnrageDamageBonus() {',
    '    // and +2 on damage',
    '    return 2;',
    '}',
    '',
    'inline int mmpEnrageAcPenalty() {',
    '    // and -3 on their own armor class',
    '    return 3;',
    '}',
    '',
    'inline int mmpEnrageRageMin() {',
    '    // the rage lasts for 7-12 rounds',
    '    return 7;',
    '}',
    '',
    'inline int mmpEnrageRageMax() {',
    '    // the rage ceiling',
    '    return 12;',
    '}',
    '',
    'inline int mmpEnrageChargesMin() {',
    '    // contains from 19-24 charges',
    '    return 19;',
    '}',
    '',
    'inline int mmpEnrageChargesMax() {',
    '    // the charge ceiling',
    '    return 24;',
    '}',
    '',
    'inline int mmpInsanityRadiusInches() {',
    '    // insanity within a 2 inch radius',
    '    return 2;',
    '}',
    '',
    'inline int mmpInsanitySavePenalty() {',
    '    // the save versus magic at -2',
    '    return 2;',
    '}',
    '',
    'inline int mmpInsanityMagicResistPenaltyPct() {',
    '    // and -10 percent from magic resistance',
    '    return 10;',
    '}',
    '',
    'inline int mmpInsanityRoundsMin() {',
    '    // completely insane for 9-12 rounds',
    '    return 9;',
    '}',
    '',
    'inline int mmpInsanityRoundsMax() {',
    '    // the insanity ceiling',
    '    return 12;',
    '}',
    '',
    'inline int mmpInsanityChargesMin() {',
    '    // the scarab has 9-16 charges',
    '    return 9;',
    '}',
    '',
    'inline int mmpInsanityChargesMax() {',
    '    // the charge ceiling',
    '    return 16;',
    '}',
    '',
    'inline int mmpProtectSaveBonus() {',
    '    // +1 on all saving throws versus magic',
    '    return 1;',
    '}',
    '',
    'inline int mmpProtectNoSaveBase() {',
    '    // a save of 20 when none is possible',
    '    return 20;',
    '}',
    '',
    'inline int mmpProtectAbsorbCount() {',
    '    // absorbs up to 12 level drains or death',
    '    return 12;',
    '}',
    '',
    'inline int mmpProtectReversedOneIn() {',
    '    // 1 in 20 are reversed cursed items',
    '    return 20;',
    '}',
    '',
    'inline int mmpProtectReversedPenalty() {',
    '    // giving the possessor a -2 on the dice',
    '    return 2;',
    '}',
    '',
    'inline int mmpProtectFixedOneIn() {',
    '    // 1 in 5 of the cursed items are fixed',
    '    return 5;',
    '}',
    '',
    'inline int mmpProtectFixedBonus() {',
    '    // actually +2 once the curse is removed',
    '    return 2;',
    '}',
    '',
    'inline int mmpProtectRemoveClericLevel() {',
    '    // removed by a cleric of 16 or higher level',
    '    return 16;',
    '}',
    '',
    'inline int mmpProtectRemovedAbsorbCount() {',
    '    // the fixed scarab absorbs 24 rather than 12',
    '    return 24;',
    '}',
    '',
    'inline int mmpSpadeLengthFeet() {',
    '    // the digging tool is 8 feet long',
    '    return 8;',
    '}',
    '',
    'inline int mmpSpadeBladeWidthFeet() {',
    '    // with a blade 2 feet wide',
    '    return 2;',
    '}',
    '',
    'inline int mmpSpadeBladeLengthFeet() {',
    '    // and 3 feet long',
    '    return 3;',
    '}',
    '',
    'inline int mmpSpadeUserStrength() {',
    '    // any fighter with 18 strength can use it',
    '    return 18;',
    '}',
    '',
    'inline int mmpSpadeDigYardsPerRound() {',
    '    // 1 cubic yard excavated in 1 round',
    '    return 1;',
    '}',
    '',
    'inline int mmpSpadeWorkRounds() {',
    '    // every 10 rounds of digging',
    '    return 10;',
    '}',
    '',
    'inline int mmpSpadeRestRounds() {',
    '    // forces a rest of 5 rounds',
    '    return 5;',
    '}',
    '',
    'inline int mmpSpadeHardPanFactor() {',
    '    // hard pan clay takes twice as long',
    '    return 2;',
    '}',
    '',
    'inline int mmpSpadeGravelFactor() {',
    '    // as does gravel',
    '    return 2;',
    '}',
    '',
    'inline int mmpSpadeLooseSoilDivisor() {',
    '    // loose soil takes half as long',
    '    return 2;',
    '}',
    '',
    'inline int mmpEntangleManUnits(int i) {',
    '    // the man-sized equivalence chain; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 8) i = 8;',
    '    // 1 storm giant or fire giant = 2 frost or stone or',
    '    // hill giants = 3 ogres = 4 bugbears = 6 gnolls = 8 men',
    '    // = 10 elves = 12 dwarves = 16 gnomes or kobolds',
    '    static const int t[9] = {',
    '        1, 2, 3, 4, 6,',
    '        8, 10, 12, 16,',
    '    };',
    '    return t[i];',
    '}',
    '',
    '}  // namespace rules',
]

AUDIT = [
    '    // ---- R278: the III.E misc magic explanation',
    '    // prose part 22 ----',
    '    // The Rope of Climbing, the Rope of Constriction, the',
    '    // Rope of Entanglement, the rope note, the Rug of',
    '    // Smothering, the Rug of Welcome, the Saw of Mighty',
    '    // Cutting, the Scarab of Death, the Scarab of Enraging',
    '    // Enemies, the Scarab of Insanity, the Scarab of',
    '    // Protection and the Spade of Colossal Excavation,',
    '    // part2 lines 1054-1081 - the slice pinning the kMisc5',
    '    // rows 6-16 of the 35-row III.E.5 table.',
    '    {',
    '        int bad = 0;',
    '        // the rope of climbing scalars',
    '        if (rules::mmpClimbLengthFeet() != 60 ||',
    '            rules::mmpClimbWeightPounds() != 3 ||',
    '            rules::mmpClimbSupportPounds() != 3000 ||',
    '            rules::mmpClimbSpeedFeetPerRound() != 10 ||',
    '            rules::mmpClimbKnotIntervalFeet() != 1 ||',
    '            rules::mmpClimbKnottedLengthFeet() != 50) ++bad;',
    '        // the knotted rope is shorter than the full rope',
    '        if (rules::mmpClimbKnottedLengthFeet() >=',
    '            rules::mmpClimbLengthFeet()) ++bad;',
    '        // the rope of constriction scalars',
    '        if (rules::mmpConstrictExtraVictimsMin() != 1 ||',
    '            rules::mmpConstrictExtraVictimsMax() != 4 ||',
    '            rules::mmpConstrictVictimRangeFeet() != 10 ||',
    '            rules::mmpConstrictDmgMin() != 2 ||',
    '            rules::mmpConstrictDmgMax() != 12 ||',
    '            rules::mmpConstrictAcClass() != -2 ||',
    '            rules::mmpConstrictCutHitPoints() != 22) ++bad;',
    '        // the victim band and damage band are ordered',
    '        if (rules::mmpConstrictExtraVictimsMin() >',
    '            rules::mmpConstrictExtraVictimsMax() ||',
    '            rules::mmpConstrictDmgMin() >',
    '            rules::mmpConstrictDmgMax()) ++bad;',
    '        // the rope of entanglement scalars',
    '        if (rules::mmpEntangleLashFeet() != 20 ||',
    '            rules::mmpEntangleUpwardFeet() != 10 ||',
    '            rules::mmpEntangleManSizedMax() != 8 ||',
    '            rules::mmpEntangleStrikeSegments() != 1 ||',
    '            rules::mmpEntangleEntwineSegments() != 1 ||',
    '            rules::mmpEntangleCommandSegments() != 1 ||',
    '            rules::mmpEntangleWholeSegments() != 3 ||',
    '            rules::mmpEntangleAcClass() != -2 ||',
    '            rules::mmpEntangleCutHitPoints() != 22 ||',
    '            rules::mmpEntangleRepairTurns() != 6) ++bad;',
    '        // the three segment costs sum to the whole',
    '        if (rules::mmpEntangleStrikeSegments() +',
    '            rules::mmpEntangleEntwineSegments() +',
    '            rules::mmpEntangleCommandSegments() !=',
    '            rules::mmpEntangleWholeSegments()) ++bad;',
    '        // the man-sized equivalence chain against a twin',
    '        static const int kMu[9] = {',
    '            1, 2, 3, 4, 6,',
    '            8, 10, 12, 16,',
    '        };',
    '        for (int i = 0; i < 9; ++i)',
    '            if (rules::mmpEntangleManUnits(i) != kMu[i]) ++bad;',
    '        // the chain rises strictly and the men equal the max',
    '        if (rules::mmpEntangleManUnits(0) != 1 ||',
    '            rules::mmpEntangleManUnits(8) != 16) ++bad;',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::mmpEntangleManUnits(i) >=',
    '                rules::mmpEntangleManUnits(i + 1)) ++bad;',
    '        if (rules::mmpEntangleManUnits(5) !=',
    '            rules::mmpEntangleManSizedMax()) ++bad;',
    '        // the rug of smothering scalars',
    '        if (rules::mmpSmotherRoundsMin() != 3 ||',
    '            rules::mmpSmotherRoundsMax() != 6 ||',
    '            rules::mmpSmotherBlockingSpells() != 4) ++bad;',
    '        // the rug of welcome scalars',
    '        if (rules::mmpWelcomeFlyWidthFeet() != 6 ||',
    '            rules::mmpWelcomeFlyLengthFeet() != 9 ||',
    '            rules::mmpWelcomeBridgeFeet() != 27 ||',
    '            rules::mmpWelcomeBridgeWidthFeet() != 2 ||',
    '            rules::mmpWelcomeAcClass() != 0 ||',
    '            rules::mmpWelcomeDestroyHitPoints() != 100 ||',
    '            rules::mmpWelcomeShrinkDivisor() != 12) ++bad;',
    '        // the bridge is longer than it is wide',
    '        if (rules::mmpWelcomeBridgeWidthFeet() >=',
    '            rules::mmpWelcomeBridgeFeet()) ++bad;',
    '        // the saw of mighty cutting scalars',
    '        if (rules::mmpSawLengthFeet() != 12 ||',
    '            rules::mmpSawWidthFeet() != 1 ||',
    '            rules::mmpSawSoloStrength() != 18 ||',
    '            rules::mmpSawTandemStrength() != 17 ||',
    '            rules::mmpSawTandemPersons() != 2 ||',
    '            rules::mmpSawHardwoodFeet() != 2 ||',
    '            rules::mmpSawHardwoodTurns() != 1 ||',
    '            rules::mmpSawTrunkFeet() != 4 ||',
    '            rules::mmpSawTrunkTurns() != 3 ||',
    '            rules::mmpSawSmallDiameterFeet() != 1 ||',
    '            rules::mmpSawSmallRounds() != 3 ||',
    '            rules::mmpSawWorkTurns() != 6 ||',
    '            rules::mmpSawRestTurns() != 6) ++bad;',
    '        // the work and rest turns match',
    '        if (rules::mmpSawWorkTurns() !=',
    '            rules::mmpSawRestTurns()) ++bad;',
    '        // the scarab of death scalars',
    '        if (rules::mmpDeathHoldRounds() != 1 ||',
    '            rules::mmpDeathContainerFeet() != 1 ||',
    '            rules::mmpDeathContainerTurns() != 1 ||',
    '            rules::mmpDeathHeartRounds() != 1) ++bad;',
    '        // the scarab of enraging enemies scalars',
    '        if (rules::mmpEnrageRadiusInches() != 4 ||',
    '            rules::mmpEnrageToHitBonus() != 1 ||',
    '            rules::mmpEnrageDamageBonus() != 2 ||',
    '            rules::mmpEnrageAcPenalty() != 3 ||',
    '            rules::mmpEnrageRageMin() != 7 ||',
    '            rules::mmpEnrageRageMax() != 12 ||',
    '            rules::mmpEnrageChargesMin() != 19 ||',
    '            rules::mmpEnrageChargesMax() != 24) ++bad;',
    '        // the rage and charge bands are ordered',
    '        if (rules::mmpEnrageRageMin() >',
    '            rules::mmpEnrageRageMax() ||',
    '            rules::mmpEnrageChargesMin() >',
    '            rules::mmpEnrageChargesMax()) ++bad;',
    '        // the scarab of insanity scalars',
    '        if (rules::mmpInsanityRadiusInches() != 2 ||',
    '            rules::mmpInsanitySavePenalty() != 2 ||',
    '            rules::mmpInsanityMagicResistPenaltyPct() != 10 ||',
    '            rules::mmpInsanityRoundsMin() != 9 ||',
    '            rules::mmpInsanityRoundsMax() != 12 ||',
    '            rules::mmpInsanityChargesMin() != 9 ||',
    '            rules::mmpInsanityChargesMax() != 16) ++bad;',
    '        if (rules::mmpInsanityRoundsMin() >',
    '            rules::mmpInsanityRoundsMax() ||',
    '            rules::mmpInsanityChargesMin() >',
    '            rules::mmpInsanityChargesMax()) ++bad;',
    '        // the scarab of protection scalars',
    '        if (rules::mmpProtectSaveBonus() != 1 ||',
    '            rules::mmpProtectNoSaveBase() != 20 ||',
    '            rules::mmpProtectAbsorbCount() != 12 ||',
    '            rules::mmpProtectReversedOneIn() != 20 ||',
    '            rules::mmpProtectReversedPenalty() != 2 ||',
    '            rules::mmpProtectFixedOneIn() != 5 ||',
    '            rules::mmpProtectFixedBonus() != 2 ||',
    '            rules::mmpProtectRemoveClericLevel() != 16 ||',
    '            rules::mmpProtectRemovedAbsorbCount() != 24) ++bad;',
    '        // the fixed scarab absorbs double',
    '        if (2 * rules::mmpProtectAbsorbCount() !=',
    '            rules::mmpProtectRemovedAbsorbCount()) ++bad;',
    '        // the fix rate is rarer than the curse rate',
    '        if (rules::mmpProtectFixedOneIn() >',
    '            rules::mmpProtectReversedOneIn()) ++bad;',
    '        // the spade of colossal excavation scalars',
    '        if (rules::mmpSpadeLengthFeet() != 8 ||',
    '            rules::mmpSpadeBladeWidthFeet() != 2 ||',
    '            rules::mmpSpadeBladeLengthFeet() != 3 ||',
    '            rules::mmpSpadeUserStrength() != 18 ||',
    '            rules::mmpSpadeDigYardsPerRound() != 1 ||',
    '            rules::mmpSpadeWorkRounds() != 10 ||',
    '            rules::mmpSpadeRestRounds() != 5 ||',
    '            rules::mmpSpadeHardPanFactor() != 2 ||',
    '            rules::mmpSpadeGravelFactor() != 2 ||',
    '            rules::mmpSpadeLooseSoilDivisor() != 2) ++bad;',
    '        // the work-to-rest ratio is 2 to 1',
    '        if (2 * rules::mmpSpadeRestRounds() !=',
    '            rules::mmpSpadeWorkRounds()) ++bad;',
    '        // the kMisc5 table rows 6-16 against static twins',
    '        static const int kRlo[11] = {',
    '            20, 26, 28, 32, 33, 34,',
    '            35, 36, 39, 41, 47,',
    '        };',
    '        static const int kRhi[11] = {',
    '            25, 27, 31, 32, 33, 34,',
    '            35, 38, 40, 46, 47,',
    '        };',
    '        for (int i = 0; i < 11; ++i)',
    '            if (rules::m5RowLo(6 + i) != kRlo[i] ||',
    '                rules::m5RowHi(6 + i) != kRhi[i]) ++bad;',
    '        // the slice bands run 20 through 47 with no gaps',
    '        if (rules::m5RowLo(6) != 20 ||',
    '            rules::m5RowHi(16) != 47) ++bad;',
    '        for (int i = 6; i < 16; ++i)',
    '            if (rules::m5RowLo(i + 1) !=',
    '                rules::m5RowHi(i) + 1) ++bad;',
    '        for (int i = 6; i < 17; ++i)',
    '            if (rules::m5RowLo(i) >',
    '                rules::m5RowHi(i)) ++bad;',
    '        // no cleric or thief marks on the slice rows',
    '        for (int i = 6; i < 17; ++i)',
    '            if (rules::m5UsableByCleric(i) != 0) ++bad;',
    '        for (int i = 6; i < 17; ++i)',
    '            if (rules::m5UsableByThief(i) != 0) ++bad;',
    '        // the fighter marks: the Saw and the Spade only',
    '        for (int i = 6; i < 17; ++i)',
    '            if (i != 11 && i != 16 &&',
    '                rules::m5UsableByFighter(i) != 0) ++bad;',
    '        if (rules::m5UsableByFighter(11) != 1 ||',
    '            rules::m5UsableByFighter(16) != 1) ++bad;',
    '        // the magic-user marks: the Rug of Welcome only',
    '        for (int i = 6; i < 17; ++i)',
    '            if (i != 10 &&',
    '                rules::m5UsableByMagicUser(i) != 0) ++bad;',
    '        if (rules::m5UsableByMagicUser(10) != 1) ++bad;',
    '        // the whole-table counts and row census',
    '        if (rules::m5ClericCount() != 5 ||',
    '            rules::m5FighterCount() != 5 ||',
    '            rules::m5MagicUserCount() != 8 ||',
    '            rules::m5ThiefCount() != 2 ||',
    '            rules::m5RowCount() != 35) ++bad;',
    '        printf("R278 misc magic prose part 22 pins audit: bad %d' + BS + 'n", bad);',
    '    }',
]

GAP = [
    'R278 landed the III.E misc',
    'magic explanation prose',
    'part 22 (part2 lines 1054-1081;',
    'global = 11065 + part2 line),',
    'the Rope of Climbing, the Rope',
    'of Constriction, the Rope of',
    'Entanglement, the rope note,',
    'the Rug of Smothering, the Rug',
    'of Welcome, the Saw of Mighty',
    'Cutting, the Scarab of Death,',
    'the Scarab of Enraging',
    'Enemies, the Scarab of',
    'Insanity, the Scarab of',
    'Protection and the Spade of',
    'Colossal Excavation (DMG',
    'p.154-156) - the slice pinning',
    'the kMisc5 rows 6-16 of the',
    '35-row III.E.5 table, the',
    'eleven consecutive rows',
    'opening with the Rope of',
    'Climbing. This round has',
    'two seams restored: seam A',
    'splits the Constriction',
    'paragraph between the 1056',
    'tail',
    '(delivers 2-12 hit) and the',
    '1058 head (points of damage)',
    'across the single 1057 blank',
    '- the p.154-155 page break,',
    'no running head captured;',
    'seam B is the p.155-156 page',
    'break between the Insanity',
    'tail (1074) and the Protection',
    'head (1079) with the blank',
    'pair at 1075-1076, the',
    'TREASURE (MISCELLANEOUS',
    'MAGIC) running head at 1077',
    'and the 1078 post-head blank.',
    'The upload quirks: the OCR',
    'splits spade- like with a',
    'space; the curly apostrophe',
    'prints in the victim',
    'possessive of the Scarab of',
    'Death; curly quotes wrap to',
    'hit in the enraging mods; the',
    'minus signs print true (the',
    'minus 2 AC pins, the minus 3',
    'armor class, the minus 10',
    'percent MR, the minus 2',
    'saves); the foot and inch',
    'primes print as curly marks;',
    'the welcome rug carries a',
    'multiplication sign on its',
    '6 x 9 flying size and the',
    '1/12 shrink fraction; the',
    'rope note prints as a heading',
    'line. The part1 quirks: the',
    'eleven slice rows print',
    'side-by-side with armor-table',
    'columns (part1 9881-9891);',
    'the Constriction, Smothering',
    'and Death rows print --- in',
    'the x.p. column; the Welcome,',
    'Saw and Spade rows carry the',
    '(M)/(F) marks. The items:',
    'Rope of Climbing (60 feet',
    'long, no thicker than a',
    'slender wand, 3 pounds,',
    'supports 3,000 pounds; moves',
    '10 feet per round on command;',
    'knots at 1 foot intervals,',
    'shortening to 50 feet), Rope',
    'of Constriction (resembles a',
    'climbing or entanglement',
    'rope; lashes the holder and',
    '1-4 others within 10 feet;',
    '2-12 hit points per round',
    'until dispelled; the entwined',
    'cannot free themselves; the',
    'rope is AC -2 and takes 22',
    'hit points to cut, all from',
    'one creature), Rope of',
    'Entanglement (lashes 20 feet',
    'or upward 10 feet; up to 8',
    'man-sized creatures by the',
    'equivalence chain 1 storm',
    'giant = 2 giants = 3 ogres =',
    '4 bugbears = 6 gnolls = 8 men',
    '= 10 elves = 12 dwarves = 16',
    'gnomes or kobolds; 1 segment',
    'to strike, 1 to entwine, 1',
    'for the command, 3 for the',
    'whole; AC -2, 22 hit points to',
    'cut, repairs in 6 turns,',
    'severing destroys it; note:',
    'a broken or severed rope',
    'loses its powers), Rug of',
    'Smothering (resembles a',
    'carpet of flying; rolls and',
    'suffocates in 3-6 rounds;',
    'blocked only by alter reality,',
    'animate object, hold plant or',
    'wish), Rug of Welcome (a 6 x 9',
    'carpet of flying; traps up to',
    'ogre-size as a rug of',
    'smothering; stiffens as steel',
    '27 feet long at 2 feet width,',
    'AC 0, 100 hit points to',
    'destroy; shrinks to 1/12',
    'size), Saw of Mighty Cutting',
    '(a 12 foot adamantite blade',
    'over 1 foot wide; 18/00',
    'strength alone or 2 persons',
    'of 17+ in tandem; 2 foot',
    'hardwood in 1 turn, 4 foot',
    'trunk in 3 turns, 1 foot',
    'diameter tree in 3 rounds; 6',
    'turns of work then 6 turns of',
    'rest), Scarab of Death',
    '(appears as a beneficial',
    'brooch; held over 1 round or',
    'within 1 foot of a warm body',
    'for 1 turn it becomes a',
    'burrowing beetle reaching the',
    'heart in 1 round; hard wood,',
    'ceramic, bone, ivory or metal',
    'containers prevent it),',
    'Scarab of Enraging Enemies',
    '(enrages intelligent',
    'hostiles within 4 inches',
    'failing saves; +1 to hit, +2',
    'damage, -3 armor class; the',
    'rage lasts 7-12 rounds; 19-24',
    'charges), Scarab of Insanity',
    '(insanity within 2 inches,',
    'saves at -2 and -10 percent',
    'magic resistance; insane 9-12',
    'rounds; 9-16 charges), Scarab',
    'of Protection (+1 saves',
    'versus magic, a save of 20',
    'when none possible; absorbs',
    '12 level drains or death',
    'touches, powdering at 12; 1',
    'in 20 reversed cursed (-2),',
    '1 in 5 of those fixed to +2',
    'by a 16th+ cleric, absorbing',
    '24), Spade of Colossal',
    'Excavation (8 feet long,',
    'blade 2 x 3 feet; any fighter',
    'with 18 strength; 1 cubic',
    'yard per round; 10 rounds of',
    'work then 5 of rest; hard pan',
    'and gravel twice as long,',
    'loose soil half).',
    '85 accessors: 84 scalars +',
    '1 walker (the man-sized',
    'equivalence chain), no name',
    'collisions parts 1-21. New',
    'R278 battery audit;',
    'census 196. Next: R279 III.E',
    'part 23 - the Sphere of',
    'Annihilation',
    'onward in part2 from',
    'line 1083 (global 12148;',
    'the sphere control table,',
    'the three stones and the',
    'four talismans follow; the',
    'kMisc5 rows 17+',
    'continue).',
]

# ---- the splice self-asserts ----
HTEXT = NL.join(HDR)
defs = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(]', HTEXT)
assert len(defs) == 85, 'accessor count is not 85'
assert len(set(defs)) == 85, 'accessor names not unique'
scal = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(][)]', HTEXT)
walk = [d for d in defs if d not in scal]
assert len(scal) == 84, 'scalar count is not 84'
assert len(walk) == 1, 'walker count is not 1'
assert set(walk) == {'mmpEntangleManUnits'}, 'wrong walker'
ATEXT = NL.join(AUDIT)
audited = set(re.findall(r'rules::(mmp[A-Za-z0-9]+)[(]', ATEXT))
assert audited == set(defs), 'audit does not probe every accessor'
for p in range(1, 22):
    pp = os.path.join(ROOT, 'rules/miscprose%d.h' % p)
    if os.path.exists(pp):
        pt = open(pp, encoding='utf-8').read()
        for n in defs:
            assert n not in pt, 'name collision with part %d' % p
for grp in (HDR, AUDIT, GAP):
    for el in grp:
        if isinstance(el, str):
            assert chr(39) not in el, 'apostrophe in content'
            probe = el.replace(chr(92) + 'n', '')
            assert chr(92) not in probe, 'backslash in content'
            assert NL not in el, 'list element spans lines'
assert ATEXT.count('{') == ATEXT.count('}'), 'audit braces unbalanced'
assert ATEXT.count('(') == ATEXT.count(')'), 'audit parens unbalanced'
assert AUDIT[-1] == '    }', 'audit block does not close'
assert HDR[-1] == '}  // namespace rules', 'header does not close'
assert ATEXT.count('R278 misc magic prose part 22 pins audit: bad %d' + BS + 'n') == 1, 'audit printf label not unique'
GJOIN = ' '.join(GAP)
for frag in ('part 22', 'rows 6-16', 'two seams', 'III.E.5',
             'p.154-156', '85 accessors: 84', 'Annihilation',
             '12148', 'line 1083', 'rows 17+', 'census 196'):
    assert any(frag in el for el in GAP), 'gap frag not contiguous: ' + frag
    assert frag in GJOIN, 'gap frag missing: ' + frag
hfrags = ('part 22', 'rows 6-16', 'two seams', 'III.E.5',
          'p.154-156', '85 accessors: 84')
for frag in hfrags:
    assert any(frag in el for el in HDR), 'header frag not contiguous: ' + frag

# ---- patch 1: create rules/miscprose22.h ----
p = 'rules/miscprose22.h'
if os.path.exists(os.path.join(ROOT, p)):
    assert rd(p) == HTEXT, 'miscprose22.h exists but differs'
    already += 1
else:
    wr(p, HTEXT)
    applied += 1
assert rd(p) == HTEXT, 'patch 1 failed'

# ---- patch 2: the regtest include ----
p = 'regtest.cpp'
s = rd(p)
inc = '#include "rules/miscprose22.h"  // R278: the III.E misc magic explanation prose part 22 pins'
if inc in s:
    already += 1
else:
    anchor = '#include "rules/miscprose21.h"  // R277: the III.E misc magic explanation prose part 21 pins'
    assert s.count(anchor) == 1, 'include anchor not unique'
    s = s.replace(anchor, anchor + NL + inc, 1)
    wr(p, s)
    applied += 1
assert inc in rd(p), 'patch 2 failed'
assert rd(p).count('#include "rules/miscprose22.h"') == 1, 'patch 2 doubled'

# ---- patch 3: the regtest audit block ----
p = 'regtest.cpp'
s = rd(p)
mark = '    // ---- R278: the III.E misc magic explanation'
if mark in s:
    already += 1
else:
    anchor = '    // ---- R227: the wis mental save wiring audit ----'
    assert s.count(anchor) == 1, 'audit anchor not unique'
    s = s.replace(anchor, ATEXT + NL + anchor, 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 3 failed'
assert rd(p).count(mark) == 1, 'patch 3 doubled'

# ---- patch 4: the gap report entry ----
p = 'tools/dmg_gap_report.md'
s = rd(p)
mark = 'R278 landed the III.E misc'
if mark in s:
    already += 1
else:
    anchor = 'continue).' + NL + NL + 'Categories:'
    assert s.count(anchor) == 1, 'gap anchor not unique'
    s = s.replace(anchor, 'continue).' + NL + NL + NL.join(GAP) + NL + NL + 'Categories:', 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 4 failed'
assert rd(p).count(mark) == 1, 'patch 4 doubled'

print('R278 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R278 note: 4 patches; the III.E misc magic')
print('explanation prose part 22 - the Rope of')
print('Climbing through the Spade of Colossal')
print('Excavation, part2 lines 1054-1081; census 196.')
print('commit: R278: the III.E misc magic explanation prose part 22 pinned - the Rope of Climbing through the Spade of Colossal Excavation in part2 lines 1054-1081 (census 196)')

