#!/usr/bin/env python3
# R279 splice: the III.E misc magic explanation prose
# part 23 pins - the Sphere of Annihilation, the Stone
# of Controlling Earth Elementals, the Stone of Good
# Luck, the Stone of Weight, the Talisman of Pure Good,
# the Talisman of the Sphere, the Talisman of Ultimate
# Evil, the Talisman of Zagy, the Tome of Clear Thought,
# the Tome of Leadership and Influence, the Tome of
# Understanding, the Trident of Fish Command, the
# Trident of Submission, the Trident of Warning, the
# Trident of Yearning, the Vacuous Grimoire, the Well
# of Many Worlds and the Wings of Flying, part2 lines
# 1083-1149 (DMG p.156-158), pinning the kMisc5 rows
# 17-34 of the 35-row III.E.5 table - the closing
# slice: rows 0-5 landed with part 21, rows 6-16 with
# part 22 and rows 17-34 here, the table complete.
# This round has two seams restored: seam A is the
# p.156-157 page break between the Stone of Weight
# tail (1108) and the Talisman of Pure Good head
# (1113) with the blank pair at 1109-1110, the
# TREASURE (MISCELLANEOUS MAGIC) running head at 1111
# and the 1112 post-head blank; seam B splits the
# Fish Command paragraph between the 1127 tail (but
# they will not) and the 1129 head (approach closer
# than 10 feet of the trident) across the single
# 1128 blank - the p.157-158 page break, no running
# head captured. The upload quirks this round: the
# foot and inch primes print as curly marks; curly
# quotes wrap to hit on the luckstone; curly
# apostrophes print throughout; the minus sign
# prints true on the Yearning cursed weapon; the
# plus-minus sign prints on the luckstone 1 to 10
# percent range; a multiplication sign prints in the
# cancellation 3d4 x 10 damage; the OCR splits Non-
# clerics and largest/ deepest with spaces; the
# sphere control table prints as a nine-row level
# grid; the wings durations print as a bare
# three-line list - all pinned as plain digits and
# words, apostrophe-free here. The part1 quirks: the
# eighteen slice rows print side-by-side with
# armor-table columns (part1 9892-9910); the Earth
# Elementals row wraps its name across two lines;
# the Loadstone, Yearning and Vacuous rows print ---
# in the x.p. column; the Sphere and its Talisman
# carry the (M) marks, the Pure Good and Ultimate
# Evil the (C) marks, the command/warning Tridents
# the (C, F, T) marks and the Submission the lone
# (F). The sphere control grid (level bands 1-5
# through 21-and-above, movement 8 through 16 feet,
# control 15 through 80 percent) and the wings
# duration list (2 turns at 32, 4 at 18, 8 at 12
# inches) are pinned as the walkers. 110 accessors:
# 104 scalars + 6 walkers, no name collisions with
# miscprose1.h through miscprose22.h. Pure data +
# helpers, header-only (the grenade.h pattern).
# 4 patches, marker-based idempotence, assert after
# every patch. ZERO apostrophes and ZERO literal
# backslashes in the content below (the printf
# newline is built via BS = chr(92)).

import os
import re
import sys

HERE = os.path.abspath(os.path.dirname(sys.argv[0]))
ROOT = os.path.abspath(HERE + '/..')
NL = chr(10)
BS = chr(92)

applied = 0
already = 0

def rd(p):
    f = open(os.path.join(ROOT, p), encoding='utf-8')
    s = f.read()
    f.close()
    return s

def wr(p, s):
    f = open(os.path.join(ROOT, p), 'w', encoding='utf-8')
    f.write(s)
    f.close()

HDR = [
    '// ====================================================================',
    '// Adnd1 - rules/miscprose23.h',
    '// R279: the III.E misc magic explanation prose part 23',
    '// (DMG p.156-158) - the Sphere of Annihilation, the Stone',
    '// of Controlling Earth Elementals, the Stone of Good Luck,',
    '// the Stone of Weight, the Talisman of Pure Good, the',
    '// Talisman of the Sphere, the Talisman of Ultimate Evil,',
    '// the Talisman of Zagy, the Tome of Clear Thought, the',
    '// Tome of Leadership and Influence, the Tome of',
    '// Understanding, the Trident of Fish Command, the Trident',
    '// of Submission, the Trident of Warning, the Trident of',
    '// Yearning, the Vacuous Grimoire, the Well of Many Worlds',
    '// and the Wings of Flying, part2 lines 1083-1149',
    '// (global = 11065 + part2 line), pinning the kMisc5 rows',
    '// 17-34 of the 35-row III.E.5 table - the closing slice:',
    '// rows 0-5 landed with part 21, rows 6-16 with part 22',
    '// and rows 17-34 here, the table complete. This round has',
    '// two seams restored: seam A is the p.156-157 page break',
    '// between the Stone of Weight tail (1108) and the',
    '// Talisman of Pure Good head (1113) with the blank pair',
    '// at 1109-1110, the TREASURE (MISCELLANEOUS MAGIC) running',
    '// head at 1111 and the 1112 post-head blank; seam B',
    '// splits the Fish Command paragraph between the 1127 tail',
    '// (but they will not) and the 1129 head (approach closer',
    '// than 10 feet of the trident) across the single 1128',
    '// blank - the p.157-158 page break, no running head',
    '// captured. The upload quirks this round: the foot and',
    '// inch primes print as curly marks; curly quotes wrap to',
    '// hit on the luckstone; curly apostrophes print',
    '// throughout; the minus sign prints true on the Yearning',
    '// cursed weapon; the plus-minus sign prints on the',
    '// luckstone 1 to 10 percent range; a multiplication sign',
    '// prints in the cancellation 3d4 x 10 damage; the OCR',
    '// splits Non- clerics and largest/ deepest with spaces;',
    '// the sphere control table prints as a nine-row level',
    '// grid; the wings durations print as a bare three-line',
    '// list - all pinned as plain digits and words,',
    '// apostrophe-free here. The part1 quirks: the eighteen',
    '// slice rows print side-by-side with armor-table columns',
    '// (part1 9892-9910); the Earth Elementals row wraps its',
    '// name across two lines; the Loadstone, Yearning and',
    '// Vacuous rows print --- in the x.p. column; the Sphere',
    '// and its Talisman carry the (M) marks, the Pure Good',
    '// and Ultimate Evil the (C) marks, the command/warning',
    '// Tridents the (C, F, T) marks and the Submission the',
    '// lone (F). The sphere control grid and the wings',
    '// duration list are pinned as the walkers.',
    '// 110 accessors: 104 scalars + 6 walkers, no name',
    '// collisions with miscprose1.h through miscprose22.h.',
    '// Pure data + helpers, header-only (the grenade.h',
    '// pattern).',
    '// ====================================================================',
    '',
    '#pragma once',
    '',
    'namespace rules {',
    '',
    'inline int mmpSphereDiameterFeet() {',
    '    // a ball of nothingness 2 feet in diameter',
    '    return 2;',
    '}',
    '',
    'inline int mmpSphereControlRangeFeet() {',
    '    // control range is 40 feet initially',
    '    return 40;',
    '}',
    '',
    'inline int mmpSphereControlPerLevelInches() {',
    '    // 1 inch per level once control is established',
    '    return 1;',
    '}',
    '',
    'inline int mmpSphereBaseMoveFeetPerRound() {',
    '    // basic movement rate is 10 feet per round',
    '    return 10;',
    '}',
    '',
    'inline int mmpSphereIntBonusLowPct() {',
    '    // adds 1 percent for each point from 13 to 15',
    '    return 1;',
    '}',
    '',
    'inline int mmpSphereIntBonusHighPct() {',
    '    // another 3 percent for each point from 16 to 18',
    '    return 3;',
    '}',
    '',
    'inline int mmpSphereIntBonusMaxPct() {',
    '    // a maximum of 12 percent bonus',
    '    return 12;',
    '}',
    '',
    'inline int mmpSphereIntBonusLowStat() {',
    '    // the low band runs from intelligence 13',
    '    return 13;',
    '}',
    '',
    'inline int mmpSphereIntBonusHighStat() {',
    '    // the high band runs from intelligence 16',
    '    return 16;',
    '}',
    '',
    'inline int mmpSphereIntBonusMaxStat() {',
    '    // the maximum bonus lands at 18 intelligence',
    '    return 18;',
    '}',
    '',
    'inline int mmpSphereDriftRoundsMin() {',
    '    // uncontrolled it slides toward the user 1-4 rounds',
    '    return 1;',
    '}',
    '',
    'inline int mmpSphereDriftRoundsMax() {',
    '    // the drift ceiling',
    '    return 4;',
    '}',
    '',
    'inline int mmpSphereDriftRangeFeet() {',
    '    // it keeps coming if the user stays within 30 feet',
    '    return 30;',
    '}',
    '',
    'inline int mmpSphereMultiUserPenaltyPct() {',
    '    // 2 or more users drop the chance 5 percent each',
    '    return 5;',
    '}',
    '',
    'inline int mmpSphereGateDestroyPct() {',
    '    // a gate spell destroys it 50 percent of the time',
    '    return 50;',
    '}',
    '',
    'inline int mmpSphereGateNothingPct() {',
    '    // the gate does nothing 35 percent',
    '    return 35;',
    '}',
    '',
    'inline int mmpSphereGateTearPct() {',
    '    // the gate tears a spatial gap 15 percent',
    '    return 15;',
    '}',
    '',
    'inline int mmpSphereGateTearRadiusInches() {',
    '    // the gap catapults everything within 18 inches',
    '    return 18;',
    '}',
    '',
    'inline int mmpSphereCancelRadiusInches() {',
    '    // a rod of cancellation explodes within 6 inches',
    '    return 6;',
    '}',
    '',
    'inline int mmpSphereCancelDmgMin() {',
    '    // the cancellation blast delivers 30-120 damage',
    '    return 30;',
    '}',
    '',
    'inline int mmpSphereCancelDmgMax() {',
    '    // the cancellation damage ceiling',
    '    return 120;',
    '}',
    '',
    'inline int mmpSphereCtlRows() {',
    '    // the control grid has nine level bands',
    '    return 9;',
    '}',
    '',
    'inline int mmpSphereCtlLevelLo(int i) {',
    '    // the control grid level band lower edges; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 8) i = 8;',
    '    // up to 5th, 6th-7th, 8th-9th, 10th-11th, 12th-13th,',
    '    // 14th-15th, 16th-17th, 18th-20th, 21st and above',
    '    static const int t[9] = {',
    '        1, 6, 8, 10, 12, 14, 16, 18, 21,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpSphereCtlLevelHi(int i) {',
    '    // the level band upper edges; i clamps; the open',
    '    // 21st-and-above band prints no ceiling and pins 0',
    '    if (i < 0) i = 0;',
    '    if (i > 8) i = 8;',
    '    static const int t[9] = {',
    '        5, 7, 9, 11, 13, 15, 17, 20, 0,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpSphereCtlMoveFeet(int i) {',
    '    // the movement per round per band; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 8) i = 8;',
    '    static const int t[9] = {',
    '        8, 9, 10, 11, 12, 13, 14, 15, 16,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpSphereCtlProbPct(int i) {',
    '    // the control probability per round per band; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 8) i = 8;',
    '    static const int t[9] = {',
    '        15, 20, 30, 40, 50, 60, 70, 75, 80,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpEarthStoneEarthDice() {',
    '    // an earth elemental of 12 hit dice from earth',
    '    return 12;',
    '}',
    '',
    'inline int mmpEarthStoneRoughDice() {',
    '    // 8 hit dice from rough unhewn stone or sand',
    '    return 8;',
    '}',
    '',
    'inline int mmpEarthStoneWorkedStoneDice() {',
    '    // none can be summoned from worked stone',
    '    return 0;',
    '}',
    '',
    'inline int mmpEarthStoneAreaFeet() {',
    '    // the summoning area must be 4 feet square',
    '    return 4;',
    '}',
    '',
    'inline int mmpEarthStoneVolumeYards() {',
    '    // and hold 4 cubic yards of medium',
    '    return 4;',
    '}',
    '',
    'inline int mmpEarthStoneRoundsMin() {',
    '    // the elemental appears in 1-4 rounds',
    '    return 1;',
    '}',
    '',
    'inline int mmpEarthStoneRoundsMax() {',
    '    // the appearance ceiling',
    '    return 4;',
    '}',
    '',
    'inline int mmpEarthStonePerDay() {',
    '    // one elemental per day by means of the stone',
    '    return 1;',
    '}',
    '',
    'inline int mmpLuckSaveBonus() {',
    '    // +1 on adverse-happening dice rolls',
    '    return 1;',
    '}',
    '',
    'inline int mmpLuckSavePctBonus() {',
    '    // +5 percent where applicable',
    '    return 5;',
    '}',
    '',
    'inline int mmpLuckItemPctMin() {',
    '    // 1 percent on magic item and treasure division rolls',
    '    return 1;',
    '}',
    '',
    'inline int mmpLuckItemPctMax() {',
    '    // up to 10 percent at owner option',
    '    return 10;',
    '}',
    '',
    'inline int mmpLoadMoveReductionPct() {',
    '    // a 50 percent reduction in movement when haste is due',
    '    return 50;',
    '}',
    '',
    'inline int mmpLoadAttackReductionPct() {',
    '    // attacks also reduced to 50 percent normal rate',
    '    return 50;',
    '}',
    '',
    'inline int mmpLoadDispelClears() {',
    '    // a dispel evil makes the item disappear',
    '    return 1;',
    '}',
    '',
    'inline int mmpPureGoodCharges() {',
    '    // the talisman of pure good has 7 charges',
    '    return 7;',
    '}',
    '',
    'inline int mmpPureGoodRechargeable() {',
    '    // it cannot be recharged',
    '    return 0;',
    '}',
    '',
    'inline int mmpPureGoodNeutralDmgMin() {',
    '    // a neutral cleric touching it takes 7-28 damage',
    '    return 7;',
    '}',
    '',
    'inline int mmpPureGoodNeutralDmgMax() {',
    '    // the neutral touch ceiling',
    '    return 28;',
    '}',
    '',
    'inline int mmpPureGoodEvilDmgMin() {',
    '    // an evil cleric touching it takes 12-48 damage',
    '    return 12;',
    '}',
    '',
    'inline int mmpPureGoodEvilDmgMax() {',
    '    // the evil touch ceiling',
    '    return 48;',
    '}',
    '',
    'inline int mmpPureGoodNonClericDmg() {',
    '    // non-clerics are not affected by the device',
    '    return 0;',
    '}',
    '',
    'inline int mmpSphereTaliNonMuDmgMin() {',
    '    // any other class touching it takes 5-30 damage',
    '    return 5;',
    '}',
    '',
    'inline int mmpSphereTaliNonMuDmgMax() {',
    '    // the wrong-class touch ceiling',
    '    return 30;',
    '}',
    '',
    'inline int mmpSphereTaliLowPctPerPoint() {',
    '    // doubles the bonus: 2 percent per point 13-15',
    '    return 2;',
    '}',
    '',
    'inline int mmpSphereTaliHighPctPerPoint() {',
    '    // and 6 percent per point 16-18',
    '    return 6;',
    '}',
    '',
    'inline int mmpSphereTaliCheckIntervalRounds() {',
    '    // held, the wielder checks control every other round',
    '    return 2;',
    '}',
    '',
    'inline int mmpSphereTaliMaxMoveFeet() {',
    '    // an uncontrolled sphere approaches at 16 feet',
    '    return 16;',
    '}',
    '',
    'inline int mmpSphereWandNegationOnTalisman() {',
    '    // a wand of negation stops the talisman control',
    '    return 1;',
    '}',
    '',
    'inline int mmpSphereWandNegationOnSphere() {',
    '    // but has no effect upon the sphere itself',
    '    return 0;',
    '}',
    '',
    'inline int mmpUltimateEvilCharges() {',
    '    // the exact opposite of pure good; 6 charges',
    '    return 6;',
    '}',
    '',
    'inline int mmpZagyHostileDmgMin() {',
    '    // a hostile reaction acts as a stone of weight;',
    '    // discarding or destroying it costs 5-30 damage',
    '    return 5;',
    '}',
    '',
    'inline int mmpZagyHostileDmgMax() {',
    '    // the hostile discard ceiling',
    '    return 30;',
    '}',
    '',
    'inline int mmpZagyNeutralHoursMin() {',
    '    // a neutral reaction stays 5-30 hours',
    '    return 5;',
    '}',
    '',
    'inline int mmpZagyNeutralHoursMax() {',
    '    // the neutral stay ceiling',
    '    return 30;',
    '}',
    '',
    'inline int mmpZagyFriendlyMonthsPerChaPoint() {',
    '    // friendly, it stays one month per charisma point',
    '    return 1;',
    '}',
    '',
    'inline int mmpZagyWishChaDivisor() {',
    '    // it grants 1 wish per 6 charisma points',
    '    return 6;',
    '}',
    '',
    'inline int mmpZagyTrapRangeFeet() {',
    '    // it grows warm within 20 feet of a trap',
    '    return 20;',
    '}',
    '',
    'inline int mmpZagyDiamondGp() {',
    '    // a base 10,000 gp diamond remains behind',
    '    return 10000;',
    '}',
    '',
    'inline int mmpClearThoughtIntGain() {',
    '    // the tome raises intelligence by 1 point',
    '    return 1;',
    '}',
    '',
    'inline int mmpClearThoughtReadHours() {',
    '    // reading takes 48 hours over 6 days',
    '    return 48;',
    '}',
    '',
    'inline int mmpClearThoughtReadDays() {',
    '    // the six reading days',
    '    return 6;',
    '}',
    '',
    'inline int mmpClearThoughtStartWeeks() {',
    '    // the exercises must begin within 1 week',
    '    return 1;',
    '}',
    '',
    'inline int mmpClearThoughtGainMonths() {',
    '    // intelligence goes up after 1 full month',
    '    return 1;',
    '}',
    '',
    'inline int mmpClearThoughtRereadGain() {',
    '    // any further perusal is of no benefit',
    '    return 0;',
    '}',
    '',
    'inline int mmpLeadershipChaGain() {',
    '    // leadership and influence raises charisma by 1',
    '    return 1;',
    '}',
    '',
    'inline int mmpUnderstandingWisGain() {',
    '    // the tome of understanding raises wisdom by 1',
    '    return 1;',
    '}',
    '',
    'inline int mmpFishCmdRadiusInches() {',
    '    // all fish within a 6 inch radius save versus magic',
    '    return 6;',
    '}',
    '',
    'inline int mmpFishCmdChargeCost() {',
    '    // the command uses one charge',
    '    return 1;',
    '}',
    '',
    'inline int mmpFishCmdProtectFeet() {',
    '    // commanded fish spare all within 10 feet',
    '    return 10;',
    '}',
    '',
    'inline int mmpFishCmdApproachFeet() {',
    '    // free fish keep 10 feet off the trident',
    '    return 10;',
    '}',
    '',
    'inline int mmpFishCmdSchoolsAsOne() {',
    '    // schooling fish check as a single entity',
    '    return 1;',
    '}',
    '',
    'inline int mmpFishCmdChargesMin() {',
    '    // it contains 17-20 charges',
    '    return 17;',
    '}',
    '',
    'inline int mmpFishCmdChargesMax() {',
    '    // the charge ceiling',
    '    return 20;',
    '}',
    '',
    'inline int mmpFishCmdMagicBonus() {',
    '    // otherwise a +1 magic weapon',
    '    return 1;',
    '}',
    '',
    'inline int mmpSubmitMoraleDelayRounds() {',
    '    // a failed save means a morale check the next round',
    '    return 1;',
    '}',
    '',
    'inline int mmpSubmitHopelessRoundsMin() {',
    '    // the hopelessness lasts 2-8 rounds',
    '    return 2;',
    '}',
    '',
    'inline int mmpSubmitHopelessRoundsMax() {',
    '    // the hopelessness ceiling',
    '    return 8;',
    '}',
    '',
    'inline int mmpSubmitChargesMin() {',
    '    // it has 17-20 charges',
    '    return 17;',
    '}',
    '',
    'inline int mmpSubmitChargesMax() {',
    '    // the charge ceiling',
    '    return 20;',
    '}',
    '',
    'inline int mmpSubmitMagicBonus() {',
    '    // a +1 magic weapon',
    '    return 1;',
    '}',
    '',
    'inline int mmpWarningRadiusInches() {',
    '    // it scans hostile hungry predators within 24 inches',
    '    return 24;',
    '}',
    '',
    'inline int mmpWarningScanRounds() {',
    '    // one round scans the 24 inch hemisphere',
    '    return 1;',
    '}',
    '',
    'inline int mmpWarningChargesMin() {',
    '    // it carries 19-24 charges',
    '    return 19;',
    '}',
    '',
    'inline int mmpWarningChargesMax() {',
    '    // the charge ceiling',
    '    return 24;',
    '}',
    '',
    'inline int mmpWarningChargeRounds() {',
    '    // each charge lasts for 2 rounds of scanning',
    '    return 2;',
    '}',
    '',
    'inline int mmpWarningMagicBonus() {',
    '    // otherwise a +2 magic weapon',
    '    return 2;',
    '}',
    '',
    'inline int mmpYearningMagicPenalty() {',
    '    // a -2 cursed magical weapon',
    '    return 2;',
    '}',
    '',
    'inline int mmpYearningFreeingSpells() {',
    '    // freed by water breathing, wish or alter reality',
    '    return 3;',
    '}',
    '',
    'inline int mmpYearningGrantsWaterBreathing() {',
    '    // it does not confer the ability to breathe underwater',
    '    return 0;',
    '}',
    '',
    'inline int mmpVacuousSaveCount() {',
    '    // the reader must make 2 saving throws versus magic',
    '    return 2;',
    '}',
    '',
    'inline int mmpVacuousIntLoss() {',
    '    // the first throw: 1 point of intelligence lost',
    '    return 1;',
    '}',
    '',
    'inline int mmpVacuousWisLoss() {',
    '    // the second throw: 2 points of wisdom lost',
    '    return 2;',
    '}',
    '',
    'inline int mmpVacuousBurnAfterRemoveCurse() {',
    '    // it must be burned to be rid of after remove curse',
    '    return 1;',
    '}',
    '',
    'inline int mmpWellTwoWay() {',
    '    // things come through the opening both ways',
    '    return 1;',
    '}',
    '',
    'inline int mmpWingsSpanFeet() {',
    '    // gigantic bat wings of 20 foot span',
    '    return 20;',
    '}',
    '',
    'inline int mmpWingsRestHours() {',
    '    // after maximum flight the wearer rests 1 hour',
    '    return 1;',
    '}',
    '',
    'inline int mmpWingsQuietHours() {',
    '    // shorter flights need only 1 hour of quiet',
    '    return 1;',
    '}',
    '',
    'inline int mmpWingsNoRestTurns() {',
    '    // flights under 1 turn need no rest at all',
    '    return 1;',
    '}',
    '',
    'inline int mmpWingsUsesPerDay() {',
    '    // the wings work but once per day',
    '    return 1;',
    '}',
    '',
    'inline int mmpWingsSupportPounds() {',
    '    // they support up to 500 pounds weight',
    '    return 500;',
    '}',
    '',
    'inline int mmpWingsSpeedRows() {',
    '    // the duration list has three entries',
    '    return 3;',
    '}',
    '',
    'inline int mmpWingsSpeedTurns(int i) {',
    '    // the turns flown per speed entry; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    // 2 turns at 32 inches, 4 at 18, 8 at 12',
    '    static const int t[3] = {',
    '        2, 4, 8,',
    '    };',
    '    return t[i];',
    '}',
    '',
    'inline int mmpWingsSpeedInches(int i) {',
    '    // the flight speed per entry; i clamps',
    '    if (i < 0) i = 0;',
    '    if (i > 2) i = 2;',
    '    static const int t[3] = {',
    '        32, 18, 12,',
    '    };',
    '    return t[i];',
    '}',
    '',
    '}  // namespace rules',
]

AUDIT = [
    '    // ---- R279: the III.E misc magic explanation',
    '    // prose part 23 ----',
    '    // The Sphere of Annihilation, the three Stones, the',
    '    // four Talismans, the three Tomes, the four Tridents,',
    '    // the Vacuous Grimoire, the Well of Many Worlds and',
    '    // the Wings of Flying, part2 lines 1083-1149 - the',
    '    // closing slice pinning the kMisc5 rows 17-34 of the',
    '    // 35-row III.E.5 table (rows 0-5 by part 21 and',
    '    // 6-16 by part 22; the table is complete).',
    '    {',
    '        int bad = 0;',
    '        // the sphere of annihilation scalars',
    '        if (rules::mmpSphereDiameterFeet() != 2 ||',
    '            rules::mmpSphereControlRangeFeet() != 40 ||',
    '            rules::mmpSphereControlPerLevelInches() != 1 ||',
    '            rules::mmpSphereBaseMoveFeetPerRound() != 10 ||',
    '            rules::mmpSphereIntBonusLowPct() != 1 ||',
    '            rules::mmpSphereIntBonusHighPct() != 3 ||',
    '            rules::mmpSphereIntBonusMaxPct() != 12 ||',
    '            rules::mmpSphereIntBonusLowStat() != 13 ||',
    '            rules::mmpSphereIntBonusHighStat() != 16 ||',
    '            rules::mmpSphereIntBonusMaxStat() != 18 ||',
    '            rules::mmpSphereDriftRoundsMin() != 1 ||',
    '            rules::mmpSphereDriftRoundsMax() != 4 ||',
    '            rules::mmpSphereDriftRangeFeet() != 30 ||',
    '            rules::mmpSphereMultiUserPenaltyPct() != 5 ||',
    '            rules::mmpSphereGateDestroyPct() != 50 ||',
    '            rules::mmpSphereGateNothingPct() != 35 ||',
    '            rules::mmpSphereGateTearPct() != 15 ||',
    '            rules::mmpSphereGateTearRadiusInches() != 18 ||',
    '            rules::mmpSphereCancelRadiusInches() != 6 ||',
    '            rules::mmpSphereCancelDmgMin() != 30 ||',
    '            rules::mmpSphereCancelDmgMax() != 120) ++bad;',
    '        // the intelligence bonus arithmetic: three low',
    '        // points plus three high points make the 12',
    '        if (rules::mmpSphereIntBonusLowPct() * 3 +',
    '            rules::mmpSphereIntBonusHighPct() * 3 !=',
    '            rules::mmpSphereIntBonusMaxPct()) ++bad;',
    '        // the gate spell chances sum to 100 percent',
    '        if (rules::mmpSphereGateDestroyPct() +',
    '            rules::mmpSphereGateNothingPct() +',
    '            rules::mmpSphereGateTearPct() != 100) ++bad;',
    '        // the drift band is ordered',
    '        if (rules::mmpSphereDriftRoundsMin() >',
    '            rules::mmpSphereDriftRoundsMax()) ++bad;',
    '        // the sphere control grid against static twins',
    '        if (rules::mmpSphereCtlRows() != 9) ++bad;',
    '        static const int kSlo[9] = {',
    '            1, 6, 8, 10, 12, 14, 16, 18, 21,',
    '        };',
    '        static const int kShi[9] = {',
    '            5, 7, 9, 11, 13, 15, 17, 20, 0,',
    '        };',
    '        static const int kSmov[9] = {',
    '            8, 9, 10, 11, 12, 13, 14, 15, 16,',
    '        };',
    '        static const int kSprob[9] = {',
    '            15, 20, 30, 40, 50, 60, 70, 75, 80,',
    '        };',
    '        for (int i = 0; i < 9; ++i)',
    '            if (rules::mmpSphereCtlLevelLo(i) != kSlo[i] ||',
    '                rules::mmpSphereCtlLevelHi(i) != kShi[i] ||',
    '                rules::mmpSphereCtlMoveFeet(i) != kSmov[i] ||',
    '                rules::mmpSphereCtlProbPct(i) != kSprob[i]) ++bad;',
    '        // the level bands chain 1 through 20, the ninth',
    '        // band open above the 20th (0 = no ceiling)',
    '        if (rules::mmpSphereCtlLevelLo(0) != 1 ||',
    '            rules::mmpSphereCtlLevelHi(7) != 20 ||',
    '            rules::mmpSphereCtlLevelLo(8) != 21 ||',
    '            rules::mmpSphereCtlLevelHi(8) != 0) ++bad;',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::mmpSphereCtlLevelLo(i + 1) !=',
    '                rules::mmpSphereCtlLevelHi(i) + 1) ++bad;',
    '        // the movement and probability both rise',
    '        for (int i = 0; i < 8; ++i)',
    '            if (rules::mmpSphereCtlMoveFeet(i) >=',
    '                rules::mmpSphereCtlMoveFeet(i + 1) ||',
    '                rules::mmpSphereCtlProbPct(i) >=',
    '                rules::mmpSphereCtlProbPct(i + 1)) ++bad;',
    '        // the stone of controlling earth elementals scalars',
    '        if (rules::mmpEarthStoneEarthDice() != 12 ||',
    '            rules::mmpEarthStoneRoughDice() != 8 ||',
    '            rules::mmpEarthStoneWorkedStoneDice() != 0 ||',
    '            rules::mmpEarthStoneAreaFeet() != 4 ||',
    '            rules::mmpEarthStoneVolumeYards() != 4 ||',
    '            rules::mmpEarthStoneRoundsMin() != 1 ||',
    '            rules::mmpEarthStoneRoundsMax() != 4 ||',
    '            rules::mmpEarthStonePerDay() != 1) ++bad;',
    '        // worked stone summons nothing, earth summons the 12',
    '        if (rules::mmpEarthStoneWorkedStoneDice() >=',
    '            rules::mmpEarthStoneEarthDice()) ++bad;',
    '        if (rules::mmpEarthStoneRoundsMin() >',
    '            rules::mmpEarthStoneRoundsMax()) ++bad;',
    '        // the stone of good luck scalars',
    '        if (rules::mmpLuckSaveBonus() != 1 ||',
    '            rules::mmpLuckSavePctBonus() != 5 ||',
    '            rules::mmpLuckItemPctMin() != 1 ||',
    '            rules::mmpLuckItemPctMax() != 10) ++bad;',
    '        if (rules::mmpLuckItemPctMin() >',
    '            rules::mmpLuckItemPctMax()) ++bad;',
    '        // the stone of weight scalars',
    '        if (rules::mmpLoadMoveReductionPct() != 50 ||',
    '            rules::mmpLoadAttackReductionPct() != 50 ||',
    '            rules::mmpLoadDispelClears() != 1) ++bad;',
    '        // the talisman of pure good scalars',
    '        if (rules::mmpPureGoodCharges() != 7 ||',
    '            rules::mmpPureGoodRechargeable() != 0 ||',
    '            rules::mmpPureGoodNeutralDmgMin() != 7 ||',
    '            rules::mmpPureGoodNeutralDmgMax() != 28 ||',
    '            rules::mmpPureGoodEvilDmgMin() != 12 ||',
    '            rules::mmpPureGoodEvilDmgMax() != 48 ||',
    '            rules::mmpPureGoodNonClericDmg() != 0) ++bad;',
    '        if (rules::mmpPureGoodNeutralDmgMin() >',
    '            rules::mmpPureGoodNeutralDmgMax() ||',
    '            rules::mmpPureGoodEvilDmgMin() >',
    '            rules::mmpPureGoodEvilDmgMax()) ++bad;',
    '        // evil hands take the heavier damage of the two',
    '        if (rules::mmpPureGoodEvilDmgMax() <=',
    '            rules::mmpPureGoodNeutralDmgMax()) ++bad;',
    '        // the talisman of the sphere scalars',
    '        if (rules::mmpSphereTaliNonMuDmgMin() != 5 ||',
    '            rules::mmpSphereTaliNonMuDmgMax() != 30 ||',
    '            rules::mmpSphereTaliLowPctPerPoint() != 2 ||',
    '            rules::mmpSphereTaliHighPctPerPoint() != 6 ||',
    '            rules::mmpSphereTaliCheckIntervalRounds() != 2 ||',
    '            rules::mmpSphereTaliMaxMoveFeet() != 16 ||',
    '            rules::mmpSphereWandNegationOnTalisman() != 1 ||',
    '            rules::mmpSphereWandNegationOnSphere() != 0) ++bad;',
    '        // the talisman doubles the sphere intelligence bonus',
    '        if (2 * rules::mmpSphereIntBonusLowPct() !=',
    '            rules::mmpSphereTaliLowPctPerPoint() ||',
    '            2 * rules::mmpSphereIntBonusHighPct() !=',
    '            rules::mmpSphereTaliHighPctPerPoint()) ++bad;',
    '        // the talisman top speed equals the grid top move',
    '        if (rules::mmpSphereTaliMaxMoveFeet() !=',
    '            rules::mmpSphereCtlMoveFeet(8)) ++bad;',
    '        // the wand of negation stops the talisman only',
    '        if (rules::mmpSphereWandNegationOnTalisman() ==',
    '            rules::mmpSphereWandNegationOnSphere()) ++bad;',
    '        // the talisman of ultimate evil scalars',
    '        if (rules::mmpUltimateEvilCharges() != 6) ++bad;',
    '        // the talisman of zagy scalars',
    '        if (rules::mmpZagyHostileDmgMin() != 5 ||',
    '            rules::mmpZagyHostileDmgMax() != 30 ||',
    '            rules::mmpZagyNeutralHoursMin() != 5 ||',
    '            rules::mmpZagyNeutralHoursMax() != 30 ||',
    '            rules::mmpZagyFriendlyMonthsPerChaPoint() != 1 ||',
    '            rules::mmpZagyWishChaDivisor() != 6 ||',
    '            rules::mmpZagyTrapRangeFeet() != 20 ||',
    '            rules::mmpZagyDiamondGp() != 10000) ++bad;',
    '        if (rules::mmpZagyHostileDmgMin() >',
    '            rules::mmpZagyHostileDmgMax() ||',
    '            rules::mmpZagyNeutralHoursMin() >',
    '            rules::mmpZagyNeutralHoursMax()) ++bad;',
    '        // the tome of clear thought scalars',
    '        if (rules::mmpClearThoughtIntGain() != 1 ||',
    '            rules::mmpClearThoughtReadHours() != 48 ||',
    '            rules::mmpClearThoughtReadDays() != 6 ||',
    '            rules::mmpClearThoughtStartWeeks() != 1 ||',
    '            rules::mmpClearThoughtGainMonths() != 1 ||',
    '            rules::mmpClearThoughtRereadGain() != 0) ++bad;',
    '        // the reading spreads 48 hours over 6 days',
    '        if (rules::mmpClearThoughtReadHours() !=',
    '            8 * rules::mmpClearThoughtReadDays()) ++bad;',
    '        // the tome of leadership scalars',
    '        if (rules::mmpLeadershipChaGain() != 1) ++bad;',
    '        // the tome of understanding scalars',
    '        if (rules::mmpUnderstandingWisGain() != 1) ++bad;',
    '        // the trident of fish command scalars',
    '        if (rules::mmpFishCmdRadiusInches() != 6 ||',
    '            rules::mmpFishCmdChargeCost() != 1 ||',
    '            rules::mmpFishCmdProtectFeet() != 10 ||',
    '            rules::mmpFishCmdApproachFeet() != 10 ||',
    '            rules::mmpFishCmdSchoolsAsOne() != 1 ||',
    '            rules::mmpFishCmdChargesMin() != 17 ||',
    '            rules::mmpFishCmdChargesMax() != 20 ||',
    '            rules::mmpFishCmdMagicBonus() != 1) ++bad;',
    '        if (rules::mmpFishCmdChargesMin() >',
    '            rules::mmpFishCmdChargesMax()) ++bad;',
    '        // the trident of submission scalars',
    '        if (rules::mmpSubmitMoraleDelayRounds() != 1 ||',
    '            rules::mmpSubmitHopelessRoundsMin() != 2 ||',
    '            rules::mmpSubmitHopelessRoundsMax() != 8 ||',
    '            rules::mmpSubmitChargesMin() != 17 ||',
    '            rules::mmpSubmitChargesMax() != 20 ||',
    '            rules::mmpSubmitMagicBonus() != 1) ++bad;',
    '        if (rules::mmpSubmitHopelessRoundsMin() >',
    '            rules::mmpSubmitHopelessRoundsMax() ||',
    '            rules::mmpSubmitChargesMin() >',
    '            rules::mmpSubmitChargesMax()) ++bad;',
    '        // the trident of warning scalars',
    '        if (rules::mmpWarningRadiusInches() != 24 ||',
    '            rules::mmpWarningScanRounds() != 1 ||',
    '            rules::mmpWarningChargesMin() != 19 ||',
    '            rules::mmpWarningChargesMax() != 24 ||',
    '            rules::mmpWarningChargeRounds() != 2 ||',
    '            rules::mmpWarningMagicBonus() != 2) ++bad;',
    '        if (rules::mmpWarningChargesMin() >',
    '            rules::mmpWarningChargesMax()) ++bad;',
    '        // the warning trident out-bonuses the other two',
    '        if (rules::mmpWarningMagicBonus() <=',
    '            rules::mmpFishCmdMagicBonus() ||',
    '            rules::mmpWarningMagicBonus() <=',
    '            rules::mmpSubmitMagicBonus()) ++bad;',
    '        // the trident of yearning scalars',
    '        if (rules::mmpYearningMagicPenalty() != 2 ||',
    '            rules::mmpYearningFreeingSpells() != 3 ||',
    '            rules::mmpYearningGrantsWaterBreathing() != 0) ++bad;',
    '        // the vacuous grimoire scalars',
    '        if (rules::mmpVacuousSaveCount() != 2 ||',
    '            rules::mmpVacuousIntLoss() != 1 ||',
    '            rules::mmpVacuousWisLoss() != 2 ||',
    '            rules::mmpVacuousBurnAfterRemoveCurse() != 1) ++bad;',
    '        // the wisdom loss doubles the intelligence loss',
    '        if (2 * rules::mmpVacuousIntLoss() !=',
    '            rules::mmpVacuousWisLoss()) ++bad;',
    '        // the well of many worlds scalars',
    '        if (rules::mmpWellTwoWay() != 1) ++bad;',
    '        // the wings of flying scalars',
    '        if (rules::mmpWingsSpanFeet() != 20 ||',
    '            rules::mmpWingsRestHours() != 1 ||',
    '            rules::mmpWingsQuietHours() != 1 ||',
    '            rules::mmpWingsNoRestTurns() != 1 ||',
    '            rules::mmpWingsUsesPerDay() != 1 ||',
    '            rules::mmpWingsSupportPounds() != 500) ++bad;',
    '        // the flight duration list against static twins',
    '        if (rules::mmpWingsSpeedRows() != 3) ++bad;',
    '        static const int kWt[3] = { 2, 4, 8 };',
    '        static const int kWi[3] = { 32, 18, 12 };',
    '        for (int i = 0; i < 3; ++i)',
    '            if (rules::mmpWingsSpeedTurns(i) != kWt[i] ||',
    '                rules::mmpWingsSpeedInches(i) != kWi[i]) ++bad;',
    '        // the turns double down the list, the speeds fall',
    '        if (rules::mmpWingsSpeedTurns(0) != 2 ||',
    '            rules::mmpWingsSpeedTurns(1) != 4 ||',
    '            rules::mmpWingsSpeedTurns(2) != 8) ++bad;',
    '        for (int i = 0; i < 2; ++i)',
    '            if (rules::mmpWingsSpeedTurns(i) >=',
    '                rules::mmpWingsSpeedTurns(i + 1) ||',
    '                rules::mmpWingsSpeedInches(i) <=',
    '                rules::mmpWingsSpeedInches(i + 1)) ++bad;',
    '        // the kMisc5 table rows 17-34 against static twins',
    '        static const int kRlo[18] = {',
    '            48, 49, 51, 53, 55, 58, 59, 61, 67, 68,',
    '            69, 70, 77, 79, 84, 86, 88, 91,',
    '        };',
    '        static const int kRhi[18] = {',
    '            48, 50, 52, 54, 57, 58, 60, 66, 67, 68,',
    '            69, 76, 78, 83, 85, 87, 90, 100,',
    '        };',
    '        for (int i = 0; i < 18; ++i)',
    '            if (rules::m5RowLo(17 + i) != kRlo[i] ||',
    '                rules::m5RowHi(17 + i) != kRhi[i]) ++bad;',
    '        // the slice bands run 48 through 100 with no gaps',
    '        if (rules::m5RowLo(17) != 48 ||',
    '            rules::m5RowHi(34) != 100) ++bad;',
    '        for (int i = 17; i < 34; ++i)',
    '            if (rules::m5RowLo(i + 1) !=',
    '                rules::m5RowHi(i) + 1) ++bad;',
    '        for (int i = 17; i < 35; ++i)',
    '            if (rules::m5RowLo(i) >',
    '                rules::m5RowHi(i)) ++bad;',
    '        // the cleric marks: the Pure Good, the Ultimate',
    '        // Evil and the two command/warning Tridents',
    '        for (int i = 17; i < 35; ++i)',
    '            if (i != 21 && i != 23 && i != 28 && i != 30 &&',
    '                rules::m5UsableByCleric(i) != 0) ++bad;',
    '        if (rules::m5UsableByCleric(21) != 1 ||',
    '            rules::m5UsableByCleric(23) != 1 ||',
    '            rules::m5UsableByCleric(28) != 1 ||',
    '            rules::m5UsableByCleric(30) != 1) ++bad;',
    '        // the fighter marks: the Submission and the two',
    '        // command/warning Tridents',
    '        for (int i = 17; i < 35; ++i)',
    '            if (i != 28 && i != 29 && i != 30 &&',
    '                rules::m5UsableByFighter(i) != 0) ++bad;',
    '        if (rules::m5UsableByFighter(28) != 1 ||',
    '            rules::m5UsableByFighter(29) != 1 ||',
    '            rules::m5UsableByFighter(30) != 1) ++bad;',
    '        // the magic-user marks: the Sphere and its Talisman',
    '        for (int i = 17; i < 35; ++i)',
    '            if (i != 17 && i != 22 &&',
    '                rules::m5UsableByMagicUser(i) != 0) ++bad;',
    '        if (rules::m5UsableByMagicUser(17) != 1 ||',
    '            rules::m5UsableByMagicUser(22) != 1) ++bad;',
    '        // the thief marks: the two command/warning Tridents',
    '        for (int i = 17; i < 35; ++i)',
    '            if (i != 28 && i != 30 &&',
    '                rules::m5UsableByThief(i) != 0) ++bad;',
    '        if (rules::m5UsableByThief(28) != 1 ||',
    '            rules::m5UsableByThief(30) != 1) ++bad;',
    '        // the whole-table counts and row census',
    '        if (rules::m5ClericCount() != 5 ||',
    '            rules::m5FighterCount() != 5 ||',
    '            rules::m5MagicUserCount() != 8 ||',
    '            rules::m5ThiefCount() != 2 ||',
    '            rules::m5RowCount() != 35) ++bad;',
    '        printf("R279 misc magic prose part 23 pins audit: bad %d' + BS + 'n", bad);',
    '    }',
]

GAP = [
    'R279 landed the III.E misc',
    'magic explanation prose',
    'part 23 (part2 lines 1083-1149;',
    'global = 11065 + part2 line),',
    'the Sphere of Annihilation, the',
    'Stone of Controlling Earth',
    'Elementals, the Stone of Good',
    'Luck, the Stone of Weight, the',
    'Talisman of Pure Good, the',
    'Talisman of the Sphere, the',
    'Talisman of Ultimate Evil, the',
    'Talisman of Zagy, the Tome of',
    'Clear Thought, the Tome of',
    'Leadership and Influence, the',
    'Tome of Understanding, the',
    'Trident of Fish Command, the',
    'Trident of Submission, the',
    'Trident of Warning, the Trident',
    'of Yearning, the Vacuous',
    'Grimoire, the Well of Many',
    'Worlds and the Wings of Flying',
    '(DMG p.156-158) - the closing',
    'slice pinning the kMisc5',
    'rows 17-34 of the 35-row',
    'III.E.5 table: with rows 0-5',
    'by part 21 and 6-16 by part',
    '22, the table is complete. This',
    'round has two seams restored:',
    'seam A is the p.156-157 page',
    'break between the Stone of Weight',
    'tail (1108) and the Talisman',
    'of Pure Good head (1113) with',
    'the blank pair at 1109-1110,',
    'the TREASURE (MISCELLANEOUS',
    'MAGIC) running head at 1111',
    'and the 1112 post-head blank;',
    'seam B splits the Fish Command',
    'paragraph between the 1127',
    'tail (but they will not) and',
    'the 1129 head (approach',
    'closer than 10 feet of the',
    'trident) across the single',
    '1128 blank - the p.157-158',
    'page break, no running head',
    'captured. The upload quirks:',
    'the foot and inch primes print',
    'as curly marks; curly quotes',
    'wrap to hit on the luckstone;',
    'curly apostrophes print',
    'throughout; the minus sign',
    'prints true on the Yearning',
    'cursed weapon; the plus-minus',
    'sign prints on the luckstone 1',
    'to 10 percent range; a',
    'multiplication sign prints in',
    'the cancellation 3d4 x 10',
    'damage; the OCR splits Non-',
    'clerics and largest/ deepest',
    'with spaces; the sphere',
    'control table prints as a',
    'nine-row level grid; the wings',
    'durations print as a bare',
    'three-line list - all pinned',
    'as plain digits and words,',
    'apostrophe-free here. The',
    'part1 quirks: the eighteen',
    'slice rows print side-by-side',
    'with armor-table columns',
    '(part1 9892-9910); the Earth',
    'Elementals row wraps its name',
    'across two lines; the',
    'Loadstone, Yearning and',
    'Vacuous rows print --- in the',
    'x.p. column; the Sphere and',
    'its Talisman carry the (M)',
    'marks, the Pure Good and',
    'Ultimate Evil the (C) marks,',
    'the command/warning Tridents',
    'the (C, F, T) marks and the',
    'Submission the lone (F). The',
    'items: Sphere of Annihilation',
    '(a 2 foot black globe, a hole',
    'in the multiverse; control',
    'range 40 feet, 1 inch per',
    'level once established, base',
    'move 10 feet per round; the',
    'intelligence bonus 1 percent',
    'per point 13-15 and 3 percent',
    'per point 16-18, 12 max at 18;',
    'the nine-row control grid from',
    'up to 5th at 8 feet 15 percent',
    'through 21st+ at 16 feet 80',
    'percent; failed control drifts',
    'it toward the user 1-4 rounds',
    'within 30 feet; 2 or more',
    'users drop the chance 5',
    'percent each, cumulative; a',
    'gate spell: 50 destroy, 35',
    'nothing, 15 tear an 18 inch',
    'gap; a rod of cancellation:',
    'mutual negation, 6 inch',
    'radius, 30-120 damage), Stone',
    'of Controlling Earth',
    'Elementals (12 dice from',
    'earth, 8 from rough stone or',
    'sand, none from worked stone;',
    '4 feet square and 4 cubic',
    'yards; appears in 1-4 rounds;',
    'one per day), Stone of Good',
    'Luck (+1, +5 percent where',
    'applicable, never on to hit,',
    'damage or spell failure dice;',
    '1 to 10 percent on item and',
    'treasure rolls), Stone of',
    'Weight (50 percent movement',
    'and attack reduction when',
    'quick movement is needed;',
    'cannot be discarded; dispel',
    'evil ends it), Talisman of',
    'Pure Good (swallows an evil',
    'cleric in a flaming crack; 7',
    'charges, never recharged;',
    'neutral touch 7-28 damage,',
    'evil touch 12-48, non-clerics',
    'safe), Talisman of the Sphere',
    '(non-magic-users take 5-30;',
    'doubles the intelligence',
    'bonus to 2 and 6 percent per',
    'point; checks every other',
    'round once held; an',
    'uncontrolled sphere',
    'approaches at 16 feet per',
    'round; a wand of negation',
    'stops the talisman, never',
    'the sphere), Talisman of',
    'Ultimate Evil (the exact',
    'opposite of pure good; 6',
    'charges), Talisman of Zagy',
    '(reaction-checked on touch:',
    'hostile acts as a loadstone',
    'and discarding costs 5-30;',
    'neutral stays 5-30 hours or',
    'until a wish; friendly stays',
    'charisma months, grants 1',
    'wish per 6 charisma points',
    'and warns within 20 feet of',
    'traps; a 10,000 gp diamond',
    'remains), Tome of Clear',
    'Thought (intelligence +1',
    'after 48 hours of reading',
    'over 6 days and a month of',
    'exercise; never twice), Tome',
    'of Leadership and Influence',
    '(charisma +1), Tome of',
    'Understanding (wisdom +1),',
    'Trident of Fish Command (a 6',
    'inch radius of fish save or',
    'fall under empathic command,',
    'one charge; free fish keep',
    '10 feet off; schooling fish',
    'check as one; 17-20 charges;',
    '+1 weapon), Trident of',
    'Submission (a failed save',
    'means a morale check instead',
    'of attacking; poor morale',
    'surrenders, hopelessness 2-8',
    'rounds; 17-20 charges; +1',
    'weapon), Trident of Warning',
    '(locates hostile or hungry',
    'predators within 24 inches;',
    '1 round per scan; 19-24',
    'charges, 2 rounds each; +2',
    'weapon), Trident of Yearning',
    '(forces submersion in the',
    'deepest water; freed only by',
    'water breathing, wish or',
    'alter reality; -2 cursed; no',
    'water breathing granted),',
    'Vacuous Grimoire (2 saves',
    'versus magic or lose 1',
    'intelligence and 2 wisdom;',
    'burn it after remove curse),',
    'Well of Many Worlds (a',
    'portable hole into another',
    'world; traffic flows both',
    'ways), Wings of Flying (20',
    'foot bat wings; 2 turns at 32',
    'inches, 4 at 18, 8 at 12;',
    'then 1 hour rest; shorter',
    'flights need only 1 hour of',
    'quiet; under 1 turn none;',
    'once per day; 500 pound',
    'support).',
    '110 accessors: 104 scalars +',
    '6 walkers (the sphere control',
    'grid and the wings duration',
    'list), no name collisions',
    'parts 1-22. New R279 battery',
    'audit; census 197. Next:',
    'R280 III.E Special - the',
    'Notes Regarding Artifacts and',
    'Relics onward in part2 from',
    'line 1153 (global 12218; the',
    'kMisc5 prose series is closed',
    'at all 35 rows; the artifact',
    'and relic notes and powers',
    'tables follow; the III.E',
    'Special prose',
    'continue).',
]

# ---- the splice self-asserts ----
HTEXT = NL.join(HDR)
defs = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(]', HTEXT)
assert len(defs) == 110, 'accessor count is not 110'
assert len(set(defs)) == 110, 'accessor names not unique'
scal = re.findall(r'inline int (mmp[A-Za-z0-9]+)[(][)]', HTEXT)
walk = [d for d in defs if d not in scal]
assert len(scal) == 104, 'scalar count is not 104'
assert len(walk) == 6, 'walker count is not 6'
assert set(walk) == {'mmpSphereCtlLevelLo', 'mmpSphereCtlLevelHi',
                    'mmpSphereCtlMoveFeet', 'mmpSphereCtlProbPct',
                    'mmpWingsSpeedTurns', 'mmpWingsSpeedInches',
                    }, 'wrong walkers'
ATEXT = NL.join(AUDIT)
audited = set(re.findall(r'rules::(mmp[A-Za-z0-9]+)[(]', ATEXT))
assert audited == set(defs), 'audit does not probe every accessor'
for p in range(1, 23):
    pp = os.path.join(ROOT, 'rules/miscprose%d.h' % p)
    if os.path.exists(pp):
        pt = open(pp, encoding='utf-8').read()
        for n in defs:
            assert n not in pt, 'name collision with part %d' % p
for grp in (HDR, AUDIT, GAP):
    for el in grp:
        if isinstance(el, str):
            assert chr(39) not in el, 'apostrophe in content'
            probe = el.replace(chr(92) + 'n', '')
            assert chr(92) not in probe, 'backslash in content'
            assert NL not in el, 'list element spans lines'
for el in GAP:
    assert len(el) <= 34, 'gap line too long: ' + el
assert ATEXT.count('{') == ATEXT.count('}'), 'audit braces unbalanced'
assert ATEXT.count('(') == ATEXT.count(')'), 'audit parens unbalanced'
assert AUDIT[-1] == '    }', 'audit block does not close'
assert HDR[-1] == '}  // namespace rules', 'header does not close'
assert ATEXT.count('R279 misc magic prose part 23 pins audit: bad %d' + BS + 'n') == 1, 'audit printf label not unique'
GJOIN = ' '.join(GAP)
for frag in ('part 23', 'rows 17-34', 'two seams', 'III.E.5',
             'p.156-158', '110 accessors: 104', 'Special',
             '12218', 'line 1153', 'census 197'):
    assert any(frag in el for el in GAP), 'gap frag not contiguous: ' + frag
    assert frag in GJOIN, 'gap frag missing: ' + frag
hfrags = ('part 23', 'rows 17-34', 'two seams', 'III.E.5',
          'p.156-158', '110 accessors: 104')
for frag in hfrags:
    assert any(frag in el for el in HDR), 'header frag not contiguous: ' + frag

# ---- patch 1: create rules/miscprose23.h ----
p = 'rules/miscprose23.h'
if os.path.exists(os.path.join(ROOT, p)):
    assert rd(p) == HTEXT, 'miscprose23.h exists but differs'
    already += 1
else:
    wr(p, HTEXT)
    applied += 1
assert rd(p) == HTEXT, 'patch 1 failed'

# ---- patch 2: the regtest include ----
p = 'regtest.cpp'
s = rd(p)
inc = '#include "rules/miscprose23.h"  // R279: the III.E misc magic explanation prose part 23 pins'
if inc in s:
    already += 1
else:
    anchor = '#include "rules/miscprose22.h"  // R278: the III.E misc magic explanation prose part 22 pins'
    assert s.count(anchor) == 1, 'include anchor not unique'
    s = s.replace(anchor, anchor + NL + inc, 1)
    wr(p, s)
    applied += 1
assert inc in rd(p), 'patch 2 failed'
assert rd(p).count('#include "rules/miscprose23.h"') == 1, 'patch 2 doubled'

# ---- patch 3: the regtest audit block ----
p = 'regtest.cpp'
s = rd(p)
mark = '    // ---- R279: the III.E misc magic explanation'
if mark in s:
    already += 1
else:
    anchor = '    // ---- R227: the wis mental save wiring audit ----'
    assert s.count(anchor) == 1, 'audit anchor not unique'
    s = s.replace(anchor, ATEXT + NL + anchor, 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 3 failed'
assert rd(p).count(mark) == 1, 'patch 3 doubled'

# ---- patch 4: the gap report entry ----
p = 'tools/dmg_gap_report.md'
s = rd(p)
mark = 'R279 landed the III.E misc'
if mark in s:
    already += 1
else:
    anchor = 'continue).' + NL + NL + 'Categories:'
    assert s.count(anchor) == 1, 'gap anchor not unique'
    s = s.replace(anchor, 'continue).' + NL + NL + NL.join(GAP) + NL + NL + 'Categories:', 1)
    wr(p, s)
    applied += 1
assert mark in rd(p), 'patch 4 failed'
assert rd(p).count(mark) == 1, 'patch 4 doubled'

print('R279 splice: ALL OK (applied %d, already %d)' % (applied, already))
print('R279 note: 4 patches; the III.E misc magic')
print('explanation prose part 23 - the Sphere of')
print('Annihilation through the Wings of Flying,')
print('part2 lines 1083-1149; census 197.')
print('commit: R279: the III.E misc magic explanation prose part 23 pinned - the Sphere of Annihilation through the Wings of Flying in part2 lines 1083-1149 (census 197)')

